Repository gravitational/teleport, pull requests merged in 2019-12, with the labels that each got.

#3189 Add SessionCreate to launchd example
  examples/launchd/teleport.plist
Labels: mac

#3187 4.2 - Docs: WIP Enhanced Session Recording
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/features/enhanced_session_recording.md
Labels: documentation

#3191 4.2 - Docs: GCP Backend Docs
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/gcp_guide.md
  docs/4.2/img/gcp/gcp-permissions.png
  docs/4.2/img/gcp/gcp-service-key.png
  docs/4.2/img/gcp/gcp-teleport.svg
Labels: documentation

#3159 Adds support for client-only builds for Mac, plus signing/notarization/stapling
  Makefile
  build.assets/build-package.sh
Labels: packaging
