Repository gravitational/teleport, pull requests merged in 2019-10, with the labels that each got.

#3035 Fixed anti-pattern use of /var/run as the PID dir
  examples/systemd/teleport.service
Labels: enhancement, ux

#3051 Added FIPS AMI build support
  assets/marketplace/Jenkinsfile-build-ent
  assets/marketplace/Jenkinsfile-build-oss
  assets/marketplace/Makefile
  assets/marketplace/files/bin/teleport-generate-config
  assets/marketplace/files/install.sh
  assets/marketplace/files/make-amis-public.sh
  assets/marketplace/single-ami.json
  examples/aws/terraform/README.md
Labels: feature request

#3034 Update teleport.yaml, copied from docs
  build.assets/pkg/etc/teleport.yaml
  build.assets/pkg/init-scripts/systemd/system/teleport.service
  examples/systemd/teleport.service
Labels: documentation, enhancement, ux

#3106 Remove blacklisted HTTP/2 ciphersuites from documentation example
  docs/4.0/admin-guide.md
  docs/4.1/admin-guide.md
Labels: documentation
