Repository gravitational/teleport, pull requests merged in 2020-07, with the labels that each got.

#3970 http -> https in docs and fix some formatting
  README.md
  docs/3.1/enterprise.md
  docs/3.2/enterprise.md
  docs/4.0/enterprise.md
  docs/4.1/enterprise/index.md
  docs/4.2/enterprise/index.md
  docs/4.3/enterprise/index.md
Labels: documentation

#3821 Update to Teleport Chart
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/HIGHAVAILABILITY.md
  examples/chart/teleport/README.md
  examples/chart/teleport/templates/config.yaml
  examples/chart/teleport/templates/deployment.yaml
  examples/chart/teleport/templates/service.yaml
  examples/chart/teleport/values.yaml
Labels: helm, release-engineering

#3943 Add Helm chart packaging for Teleport
  .drone.yml
  examples/chart/teleport/README.md
Labels: helm, release-engineering

#3968 Readme: use https
  README.md
Labels: documentation

#3976 Release v4.3.0-beta.1
  Makefile
  version.go
Labels: release-engineering

#3959 Updated Docs Theme
  docs/4.2.yaml
  docs/4.3.yaml
  docs/4.3/admin-guide.md
  docs/4.3/architecture/teleport_architecture_overview.md
  docs/4.3/architecture/teleport_auth.md
  docs/4.3/architecture/teleport_nodes.md
  docs/4.3/architecture/teleport_proxy.md
  docs/4.3/architecture/teleport_users.md
  docs/4.3/aws_oss_guide.md
  docs/4.3/enterprise/introduction.md
  docs/4.3/enterprise/quickstart-enterprise.md
  docs/4.3/enterprise/ssh_fips.md
  docs/4.3/enterprise/sso/ssh_sso.md
  docs/4.3/faq.md
  docs/4.3/index.md
  docs/4.3/user-manual.md
  docs/theme/cta.html
  docs/theme/fonts/Colfax-Medium.ttf
  docs/theme/fonts/Colfax-Regular.ttf
  docs/theme/fonts/fontawesome-webfont.eot
  docs/theme/fonts/fontawesome-webfont.svg
  docs/theme/fonts/fontawesome-webfont.ttf
  docs/theme/fonts/fontawesome-webfont.woff
  docs/theme/fonts/icomoon.eot
  docs/theme/fonts/icomoon.svg
  docs/theme/fonts/icomoon.ttf
  docs/theme/fonts/icomoon.woff
  docs/theme/fonts/icomoon.woff2
  docs/theme/footer.html
  docs/theme/head.html
  docs/theme/jumpnav.html
  docs/theme/license/highlight.js/LICENSE
  docs/theme/main.html
  docs/theme/pagination.html
  docs/theme/scripts.html
  docs/theme/src/default.css
  docs/theme/src/docs.css
  docs/theme/src/docs.js
  docs/theme/src/highlight.pack.js
  docs/theme/src/solarized-dark.css
  docs/theme/toc.html
  docs/theme/topnav.html
Labels: documentation, ux

#3977 Fix all connector references in docs
  docs/3.1/admin-guide.md
  docs/3.2/admin-guide.md
  docs/4.0/admin-guide.md
  docs/4.1/admin-guide.md
  docs/4.1/cli-docs.md
  docs/4.2/admin-guide.md
  docs/4.2/cli-docs.md
  docs/4.3/admin-guide.md
  docs/4.3/cli-docs.md
Labels: documentation

#3979 Add info on ca_signature_algo
  docs/4.3/admin-guide.md
  docs/4.3/features/enhanced_session_recording.md
Labels: documentation

#3978 whitespace issues
  docs/4.2/admin-guide.md
  docs/4.2/faq.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_server.md
  docs/4.3/enterprise/workflow/ssh_approval_mattermost.md
  docs/4.3/enterprise/workflow/ssh_approval_pagerduty.md
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
Labels: documentation

#3990 Update ssh_okta.md
  docs/4.3/enterprise/sso/ssh_okta.md
Labels: documentation, sso

#3989 Bugs in G Suite Guide
  docs/4.3/enterprise/sso/ssh_gsuite.md
Labels: documentation

#3998 Update cron image versions for 4.3
  .drone.yml
Labels: release-engineering

#3982 Various buildbox/Drone fixes
  .drone.yml
  build.assets/Dockerfile
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
  build.assets/Makefile
Labels: release-engineering

#4009 Fix approval plugins grammar
  docs/4.3/enterprise/introduction.md
Labels: documentation

#4011 Added entity_descriptor_url to SAML example.
  docs/4.3/enterprise/sso/ssh_sso.md
Labels: documentation

#4014 Backport #3982 to branch/4.3
  .drone.yml
  .github/CODEOWNERS
  build.assets/Dockerfile
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
  build.assets/Makefile
Labels: release-engineering

#4017 Sign .drone.yml
  .drone.yml
Labels: release-engineering

#4026 YubiKey Example
  docs/4.3/admin-guide.md
  docs/4.3/architecture/teleport_users.md
Labels: documentation

#3921 Teleport EKS Guide
  assets/marketplace/files/install.sh
  docs/4.3/aws_oss_guide.md
  docs/4.3/production.md
  examples/aws/eks/teleport.yaml
Labels: aws, documentation

#4036 Update prerelease.md
  docs/prerelease.md
Labels: documentation

#4039 Remove extra PAM steps from buildbox builds
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
Labels: release-engineering

#4043 Add note to verify that prometheus metrics are accurate.
  docs/testplan.md
Labels: testplan

#4041 Fix a nil pointer dereference in firestore index creation
  lib/backend/firestore/firestorebk.go
Labels: backport-required

#4052 Add Docker & Helm to installation page
  docs/4.3/installation.md
  docs/testplan.md
Labels: documentation

#4062 Fix Mattermost URL for download
  docs/4.3/enterprise/workflow/ssh_approval_mattermost.md
Labels: documentation, teleport-plugin

#4006 Add RPM/DEB/i386 releases to Drone pipeline
  .drone.yml
  Makefile
  build.assets/Dockerfile
  build.assets/Makefile
  build.assets/build-package.sh
Labels: backport-required, release-engineering

#4063 Move around references
  docs/4.3.yaml
  docs/4.3/admin-guide.md
  docs/4.3/api_reference.md
  docs/4.3/cli-docs.md
  docs/4.3/config_reference.md
Labels: documentation

#4059 Updating Kubernetes Diagrams and Docs
  docs/4.3/admin-guide.md
  docs/4.3/aws_oss_guide.md
  docs/4.3/img/teleport-k8s-pod.svg
  docs/4.3/img/teleport-kube.png
  docs/4.3/img/teleport-kubernetes-outside.svg
  docs/4.3/kubernetes_ssh.md
  docs/4.3/milv.config.yaml
Labels: documentation

#4070 Change cron Docker image base to ubuntu
  .drone.yml
  build.assets/Dockerfile-cron
Labels: release-engineering

#4072 Add plan to test cloud providers
  docs/testplan.md
Labels: testplan

#4029 Add Docker builds to Drone
  .drone.yml
  Makefile
  build.assets/Makefile
Labels: backport-required, release-engineering

#4081 Update CODEOWNERS
  .github/CODEOWNERS
Labels: release-engineering

#4084 Fix Drone signature
  .drone.yml
Labels: release-engineering

#4002 Allow user with at in name
  lib/sshutils/scp/scp.go
  lib/sshutils/scp/scp_test.go
  lib/utils/proxyjump.go
  lib/utils/proxyjump_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: backport-required

#4071 Add Docker OSS/Enterprise quickstarts
  docker/teleport-ent-quickstart.yml
  docker/teleport-quickstart.yml
  docs/4.3.yaml
  docs/4.3/enterprise/quickstart-enterprise.md
  docs/4.3/milv.config.yaml
  docs/4.3/quickstart.md
Labels: documentation

#4090 Backport .drone.yml from master
  .drone.yml
Labels: release-engineering

#4098 Update workflow role reference
  docs/4.2/enterprise/index.md
  docs/4.3/enterprise/workflow/index.md
Labels: documentation

#4069 Add docs / table for Prometheus endpoint.
  assets/monitoring/README.md
  assets/monitoring/docker-compose.yml
  assets/monitoring/telegraf.conf
  assets/monitoring/teleport.service
  docs/4.3.yaml
  docs/4.3/admin-guide.md
  docs/4.3/metrics_logs_reference.md
Labels: c-sn, documentation

#4108 Fix verbose mode message in help text
  tool/tsh/tsh.go
Labels: good-starter-issue

#4103 Updated Backup section
  docs/4.3/admin-guide.md
Labels: documentation

#4116 Fix Docker Quickstart configuration paths
  docker/teleport-ent-quickstart.yml
  docker/teleport-quickstart.yml
Labels: documentation

#4109 Use TELEPORT_LOGIN_BIND_ADDR if set
  tool/tsh/tsh.go
Labels: good-starter-issue

#4093 Add jobs for Drone MacOS/ARM exec runners
  .drone.yml
  Makefile
  build.assets/build-package.sh
Labels: release-engineering

#4112 Adding Tabs to the docs
  docs/4.3.yaml
  docs/4.3/aws_oss_guide.md
  docs/4.3/features/ssh_pam.md
  docs/4.3/installation.md
  docs/4.3/quickstart.md
  docs/4.3/quickstart_docker.md
  docs/theme/src/docs.css
  docs/theme/src/docs.js
Labels: documentation

#4115 Only check out Enterprise code when running on Gravitational repos
  .drone.yml
Labels: release-engineering

#4129 Correct port for proxy public address example
  docs/4.3/admin-guide.md
Labels: documentation

#4128 Backport Drone and Dockerfile changes to 4.3
  .drone.yml
  build.assets/Dockerfile
  build.assets/Dockerfile-fips
  build.assets/Makefile
Labels: release-engineering

#4107 Fix Helm chart public_addr for proxy when using Ingress
  examples/chart/teleport-daemonset/README.md
  examples/chart/teleport-demo/README.md
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/HIGHAVAILABILITY.md
  examples/chart/teleport/README.md
  examples/chart/teleport/templates/config.yaml
  examples/chart/teleport/templates/deployment.yaml
  examples/chart/teleport/templates/ingress.yaml
  examples/chart/teleport/templates/service.yaml
  examples/chart/teleport/values.yaml
Labels: helm, kubernetes

#4126 Fix up clone logic and doc tests for forks
  .drone.yml
Labels: release-engineering

#4148 Bump 4.3 docs ref for 4.3.2
  docs/4.3.yaml
Labels: documentation

#4153 correct public web address port in eks example
  examples/aws/eks/teleport.yaml
Labels: documentation, examples

#4130 Creating a dedicated OpenSSH section in docs
  docs/4.3.yaml
  docs/4.3/admin-guide.md
  docs/4.3/features/enhanced_session_recording.md
  docs/4.3/img/openssh-proxy.svg
  docs/4.3/openssh_teleport.md
Labels: documentation
