Repository gravitational/teleport, pull requests merged in 2020-09, with the labels that each got.

#4278 Fix triggers for tests to run on PRs only
  .drone.yml
Labels: release-engineering

#4280 min js files
  docs/theme/main.html
  docs/theme/scripts.html
  docs/theme/src/docs.css
  docs/theme/src/docs.js
  docs/theme/src/docs.js.LICENSE.txt
  docs/theme/topnav.html
Labels: documentation

#4238 Add permalink to Docs Header Pages
  docs/4.3.yaml
Labels: documentation

#4298 Add scopes to slack approval workflow docs
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
  docs/4.3/img/enterprise/plugins/slack/api-scopes.png
Labels: documentation

#4300 Update default keep_alive_interval
  docs/4.3/config_reference.md
Labels: documentation

#4306 updated login screen for azuread docs to 4.3
  docs/4.3/img/azuread/azure-11-loginwithmsft.png
Labels: documentation

#4302 Update AWS Guide to point to diagnostic endpoint
  docs/4.3/admin-guide.md
  docs/4.3/aws_oss_guide.md
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
Labels: documentation

#4223 Get teleport /readyz state from heartbeats instead of cert rotation
  lib/service/connect.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/service/state_test.go
  lib/srv/heartbeat.go
  lib/srv/regular/sshserver.go
Labels: backport-required

#4271 DynamoDB respect HTTP Connect proxies
  lib/backend/dynamo/dynamodbbk.go
Labels: c-pa

#4341 Updated README AMI example to 4.3.5 from 4.2.3
  examples/aws/terraform/README.md
Labels: terraform

#4346 Re-add links to enhanced session recording page
  docs/4.2/admin-guide.md
  docs/4.3/admin-guide.md
Labels: documentation

#4349 Fix OpenSSH client docs
  docs/4.3/openssh-teleport.md
Labels: documentation

#4351 Update docs aws terraform ami example to 4.3.5 from 4.2.3
  docs/4.3/aws-terraform-guide.md
Labels: documentation, terraform

#4360 Remove autoscaler ARN from Terraform
  examples/aws/terraform/dynamo.tf
Labels: terraform

#4361 Fix SSH examples in Terraform guides
  docs/4.2/aws-terraform-guide.md
  docs/4.3/aws-terraform-guide.md
Labels: documentation, terraform

#4367 Update HA docs
  docs/4.3/admin-guide.md
  docs/4.3/config-reference.md
Labels: documentation

#4378 Release 4.3.6-dev.1
  Makefile
  version.go
Labels: release-engineering

#4382 Release 4.3.6
  Makefile
  version.go
Labels: release-engineering

#4388 Fix namespace usage in k8s-auth script
  examples/k8s-auth/get-kubeconfig.sh
Labels: kubernetes

#4347 remove symlink usage for tsh profile
  lib/client/api.go
  lib/client/profile.go
  lib/client/profile_test.go
  tool/tsh/tsh.go
Labels: c-ju

#4398 Add port/clarification to node tunnelling/IoT instructions
  docs/4.1/admin-guide.md
  docs/4.2/admin-guide.md
  docs/4.3/admin-guide.md
Labels: documentation

#4394 Update G Suite docs to add clarification
  docs/4.2/enterprise/sso/ssh-gsuite.md
  docs/4.3/enterprise/sso/ssh-gsuite.md
Labels: documentation, sso

#4413 Release 4.1.11
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#4410 Release 4.4.0-alpha.1
  Makefile
  version.go
Labels: release-engineering

#4414 Release 4.2.12
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering
