Repository gravitational/teleport, pull requests merged in 2020-04, with the labels that each got.

#3509 Add mention of node tunnelling to port 3024
  docs/4.2/admin-guide.md
Labels: documentation

#3511 Add warning about table_name vs audit_events_uri
  docs/4.2/admin-guide.md
Labels: documentation

#3514 Microsoft Azure Active Directory SSO Instructions
  docs/4.2.yaml
  docs/4.2/img/azuread/azure-11-loginwithmsft.png
  docs/4.2/img/azuread/azuread-1-home.png
  docs/4.2/img/azuread/azuread-10-fedmeatadataxml.png
  docs/4.2/img/azuread/azuread-12-sampleconnector.png
  docs/4.2/img/azuread/azuread-2-newapp.png
  docs/4.2/img/azuread/azuread-3-selectnongalleryapp.png
  docs/4.2/img/azuread/azuread-4-enterappname.png
  docs/4.2/img/azuread/azuread-5-turnoffuserassign.png
  docs/4.2/img/azuread/azuread-6-selectsaml.png
  docs/4.2/img/azuread/azuread-7-editbasicsaml.png
  docs/4.2/img/azuread/azuread-8-entityandreplyurl.png
  docs/4.2/img/azuread/azuread-9a-nameidentifier.png
  docs/4.2/img/azuread/azuread-9b-groupclaim.png
  docs/4.2/img/azuread/azuread-9c-usernameclaim.png
  docs/4.2/ssh_azuread.md
Labels: documentation, sso

#3521 Relabel Sidebar
  docs/4.2.yaml
Labels: documentation

#3548 Add tunnel_public_addr
  docs/4.2/admin-guide.md
Labels: documentation

#3535 Correct Msft azure ad link in docs
  docs/4.2/ssh_azuread.md
Labels: documentation

#3560 Update enhanced session recording docs for Amazon 2 Linux
  docs/4.2/features/enhanced_session_recording.md
Labels: documentation

#3567 Minor wording cleanup to FIPS docs
  docs/4.2/enterprise/ssh_fips.md
Labels: documentation

#3522 Update admin manual config file
  docs/4.2/admin-guide.md
Labels: documentation

#3587 Correct FIPS binary question
  docs/4.2/enterprise/ssh_fips.md
Labels: documentation

#3618 added zoho script for heat mapping
  docs/theme/head.html
Labels: documentation

#3616 Add note on OIDC for Auth0
  docs/4.2/oidc.md
Labels: documentation, sso

#3589 Fix for #3420 - Docs for OIDC
  docs/4.2/kubernetes_ssh.md
  docs/4.2/oidc.md
  examples/resources/oidc-connector.yaml
Labels: documentation

#3622 A couple of theme tweaks
  docs/4.2/architecture/teleport_auth.md
  docs/4.2/aws_terraform_guide.md
  docs/4.2/installation.md
  docs/4.2/quickstart.md
  docs/theme/scripts.html
  docs/theme/toc.html
  docs/theme/topnav.html
Labels: documentation

#3628 Docs for external email identities and Kube Users
  docs/4.3/enterprise/ssh_sso.md
  docs/4.3/kubernetes_ssh.md
Labels: documentation

#3640 Remove failing CentOS 6 build steps
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Makefile
Labels: build-pipeline
