Repository gravitational/teleport, pull requests merged in 2020-06, with the labels that each got.

#3799 Fix ExecSuite.TestOSCommandPrep test when running as root user
  lib/srv/exec.go
  lib/srv/exec_test.go
Labels: test problem

#3699 Teleport Plugins Documentation
  Makefile
  docs/4.2/gcp_guide.md
  docs/4.3.yaml
  docs/4.3/admin-guide.md
  docs/4.3/cli-docs.md
  docs/4.3/enterprise/index.md
  docs/4.3/enterprise/ssh_sso.md
  docs/4.3/enterprise/workflow/index.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_cloud.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_server.md
  docs/4.3/enterprise/workflow/ssh_approval_mattermost.md
  docs/4.3/enterprise/workflow/ssh_approval_pagerduty.md
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
  docs/4.3/img/enterprise/plugins/mattermost/mattermost-bot-ui.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost.mp4
  docs/4.3/img/enterprise/plugins/mattermost/mattermost.practice.io_8065_admin_console_integrations_bot_accounts.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost.webm
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_OAuth_token.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_admin_console_integrations_bot_accounts.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_bot.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_console_integrations_bot_accounts.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_create_private_channel.png
  docs/4.3/img/enterprise/plugins/mattermost/mattermost_invite_bot.png
  docs/4.3/img/enterprise/plugins/pagerduty/approve-workflow-pd.png
  docs/4.3/img/enterprise/plugins/pagerduty/create-new-service-pd.png
  docs/4.3/img/enterprise/plugins/pagerduty/pagerduty-api-key.png
  docs/4.3/img/enterprise/plugins/pagerduty/pagerduty-demo.mp4
  docs/4.3/img/enterprise/plugins/pagerduty/pagerduty-demo.png
  docs/4.3/img/enterprise/plugins/pagerduty/pagerduty-demo.webm
  docs/4.3/img/enterprise/plugins/slack/Create-a-Slack-App.png
  docs/4.3/img/enterprise/plugins/slack/OAuth.png
  docs/4.3/img/enterprise/plugins/slack/SlackSigningSecret.png
  docs/4.3/img/enterprise/plugins/slack/Slackbot-Permissions.png
  docs/4.3/img/enterprise/plugins/slack/api-scopes.png
  docs/4.3/img/enterprise/plugins/slack/invite-user-to-team.png
  docs/4.3/img/enterprise/plugins/slack/setup-interactive-component.png
  docs/4.3/img/enterprise/plugins/slack/slack.mp4
  docs/4.3/img/enterprise/plugins/slack/slack.webm
  docs/4.3/img/enterprise/plugins/teleport_bot@2x.png
  docs/4.3/kubernetes_ssh.md
  docs/4.3/ssh_adfs.md
  examples/resources/plugins/teleport-gitlab.toml
  examples/resources/plugins/teleport-jira.toml
  examples/resources/plugins/teleport-mattermost.toml
  examples/resources/plugins/teleport-pagerduty.toml
  examples/resources/plugins/teleport-slack.toml
  examples/systemd/plugins/teleport-jira.service
  examples/systemd/plugins/teleport-mattermost.service
  examples/systemd/plugins/teleport-pagerduty.service
  examples/systemd/plugins/teleport-slack.service
Labels: documentation

#3858 Plugin Content & --browser flag
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/img/teleport-sha.png
  docs/4.2/installation.md
  docs/4.3/admin-guide.md
  docs/4.3/cli-docs.md
  docs/4.3/enterprise/index.md
  docs/4.3/enterprise/ssh_sso.md
  docs/4.3/enterprise/sso/oidc.md
  docs/4.3/enterprise/workflow/index.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_cloud.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_server.md
  docs/4.3/enterprise/workflow/ssh_approval_mattermost.md
  docs/4.3/enterprise/workflow/ssh_approval_pagerduty.md
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
  docs/4.3/img/teleport-sha.png
  docs/4.3/installation.md
  docs/4.3/trustedclusters.md
  docs/4.3/user-manual.md
Labels: documentation

#3803 Proxy X11 Forwarding Support
  constants.go
  lib/auth/auth.go
  lib/auth/native/native.go
  lib/auth/testauthority/testauthority.go
  lib/auth/tls_test.go
  lib/events/api.go
  lib/events/codes.go
  lib/services/authority.go
  lib/services/role.go
  lib/services/types.pb.go
  lib/services/types.proto
  lib/srv/forward/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/req.go
Labels: OpenSSH

#3884 Update Okta Connector to use latest UI
  docs/4.3/enterprise/sso/ssh_okta.md
  docs/4.3/img/sso/okta/obtain-okta-xml.png
  docs/4.3/img/sso/okta/okta-saml-0.png
  docs/4.3/img/sso/okta/okta-saml-1.png
  docs/4.3/img/sso/okta/okta-saml-2.1.png
  docs/4.3/img/sso/okta/okta-saml-2.2.png
  docs/4.3/img/sso/okta/okta-saml-2.png
  docs/4.3/img/sso/okta/okta-saml-3.1.png
  docs/4.3/img/sso/okta/okta-saml-3.png
  docs/4.3/img/sso/okta/okta-saml-4.png
  docs/4.3/img/sso/okta/okta-saml-5.png
  docs/4.3/img/sso/okta/regex.png
  docs/4.3/img/sso/okta/setup-redirection.png
  docs/4.3/img/sso/okta/switch-to-classic.gif
Labels: documentation

#3898 Update SSO Docs
  docs/4.3/enterprise/ssh_sso.md
  docs/4.3/enterprise/sso/oidc.md
  docs/4.3/img/teleport-sso/bitbucket.png
  docs/4.3/img/teleport-sso/github.png
  docs/4.3/img/teleport-sso/google.png
  docs/4.3/img/teleport-sso/microsoft.png
  docs/4.3/img/teleport-sso/openId.png
  docs/4.3/oidc.md
  examples/resources/oidc-connector.yaml
Labels: documentation

#3879 Updated Jira Server Docs & Updated Plugin TOML
  docs/4.3/enterprise/workflow/ssh_approval_jira_server.md
  docs/4.3/img/enterprise/plugins/jira/jira-server.mp4
  docs/4.3/img/enterprise/plugins/jira/jira-server.webm
  examples/resources/plugins/teleport-gitlab.toml
  examples/resources/plugins/teleport-jira.toml
  examples/resources/plugins/teleport-mattermost.toml
  examples/resources/plugins/teleport-pagerduty.toml
  examples/resources/plugins/teleport-slack.toml
Labels: documentation

#3793 Add Drone pipeline to Teleport repo
  .drone.yml
  build.assets/Dockerfile-cron
Labels: release-engineering

#3880 Update master branch version tag
  Makefile
  version.go
Labels: release-engineering

#3909 Admin and FAQ Updates for 4.2 and 4.3
  docs/4.2/admin-guide.md
  docs/4.2/faq.md
  docs/4.3/admin-guide.md
  docs/4.3/faq.md
Labels: documentation

#3915 Adds detail that joining sessions is not supported in recording proxy mode
  .drone.yml
  docs/3.1/user-manual.md
  docs/3.2/user-manual.md
  docs/4.0/user-manual.md
  docs/4.1/user-manual.md
  docs/4.2/user-manual.md
  docs/4.3/enterprise/index.md
  docs/4.3/enterprise/sso/oidc.md
  docs/4.3/enterprise/workflow/ssh_approval_jira_server.md
  docs/4.3/enterprise/workflow/ssh_approval_mattermost.md
  docs/4.3/enterprise/workflow/ssh_approval_pagerduty.md
  docs/4.3/enterprise/workflow/ssh_approval_slack.md
  docs/4.3/user-manual.md
Labels: documentation, release-engineering

#3885 Create preflight checklist.
  docs/preflight.md
Labels: documentation

#3926 Backport .drone.yml to branch/4.3
  .drone.yml
Labels: release-engineering
