Repository gravitational/teleport, pull requests merged in 2020-08, with the labels that each got.

#4158 Correct SAML web callback url example
  examples/resources/saml-connector.yaml
Labels: documentation, examples, sso

#4003 Use host CA to validate proxy cert on tsh login -o id.pam
  tool/tsh/tsh.go
Labels: backport-required

#4144 Add AMI builds to Drone
  .drone.yml
  assets/aws/.gitignore
  assets/aws/Jenkinsfile
  assets/aws/Jenkinsfile-build-ent
  assets/aws/Jenkinsfile-build-oss
  assets/aws/LICENSE
  assets/aws/Makefile
  assets/aws/README.md
  assets/aws/cloudformation/README.md
  assets/aws/files/bin/teleport-all-pre-start
  assets/aws/files/bin/teleport-check-cert
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-get-cert
  assets/aws/files/bin/teleport-lock
  assets/aws/files/bin/teleport-monitor-setup
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/bin/teleport-ssm-get-token
  assets/aws/files/bin/teleport-ssm-publish-tokens
  assets/aws/files/bin/teleport-upload-cert
  assets/aws/files/install.sh
  assets/aws/files/make-amis-public.sh
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-check-cert.service
  assets/aws/files/system/teleport-check-cert.timer
  assets/aws/files/system/teleport-generate-config.service
  assets/aws/files/system/teleport-get-cert.service
  assets/aws/files/system/teleport-get-cert.timer
  assets/aws/files/system/teleport-monitor-setup.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport-renew-cert.service
  assets/aws/files/system/teleport-renew-cert.timer
  assets/aws/files/system/teleport-ssm-publish-tokens.service
  assets/aws/files/system/teleport-ssm-publish-tokens.timer
  assets/aws/files/system/teleport.service
  assets/aws/single-ami.json
  docs/4.0/aws_oss_guide.md
  docs/4.1/aws_oss_guide.md
  docs/4.2/aws_oss_guide.md
  docs/4.3/aws_oss_guide.md
  docs/preflight.md
Labels: backport-required, release-engineering

#4147 Fix some Drone tag build failures
  .drone.yml
Labels: backport-required, release-engineering

#4174 Backport of Add AMI builds to Drone (#4144)
  .drone.yml
  assets/aws/.gitignore
  assets/aws/Jenkinsfile
  assets/aws/Jenkinsfile-build-ent
  assets/aws/Jenkinsfile-build-oss
  assets/aws/LICENSE
  assets/aws/Makefile
  assets/aws/README.md
  assets/aws/cloudformation/README.md
  assets/aws/files/bin/teleport-all-pre-start
  assets/aws/files/bin/teleport-check-cert
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-get-cert
  assets/aws/files/bin/teleport-lock
  assets/aws/files/bin/teleport-monitor-setup
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/bin/teleport-ssm-get-token
  assets/aws/files/bin/teleport-ssm-publish-tokens
  assets/aws/files/bin/teleport-upload-cert
  assets/aws/files/install.sh
  assets/aws/files/make-amis-public.sh
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-check-cert.service
  assets/aws/files/system/teleport-check-cert.timer
  assets/aws/files/system/teleport-generate-config.service
  assets/aws/files/system/teleport-get-cert.service
  assets/aws/files/system/teleport-get-cert.timer
  assets/aws/files/system/teleport-monitor-setup.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport-renew-cert.service
  assets/aws/files/system/teleport-renew-cert.timer
  assets/aws/files/system/teleport-ssm-publish-tokens.service
  assets/aws/files/system/teleport-ssm-publish-tokens.timer
  assets/aws/files/system/teleport.service
  assets/aws/single-ami.json
Labels: release-engineering

#4181 Backport of Fix some Drone tag build failures (#4147)
  .drone.yml
Labels: release-engineering

#4162 Removed GOPATH from readme
  README.md
Labels: documentation

#4197 Backport missing Makefile commands
  Makefile
  build.assets/Makefile
Labels: release-engineering

#4198 Release 4.3.4-dev.2
  Makefile
  build.assets/Makefile
  version.go
Labels: release-engineering

#4199 Release 4.3.4-dev.3
  Makefile
  build.assets/Makefile
  version.go
Labels: release-engineering

#4201 More build pipeline fixes
  .drone.yml
  build.assets/Makefile
Labels: backport-required, release-engineering

#4207 Backport of More build pipeline fixes (#4201)
  .drone.yml
  assets/aws/single-ami.json
  build.assets/Makefile
Labels: release-engineering

#4208 Release 4.3.5-dev.2
  Makefile
  version.go
Labels: release-engineering

#4209 Export FIPS_AMI_NAME for Enterprise AMI builds
  .drone.yml
Labels: backport-required, release-engineering

#4219 Add scripts and Makefile targets to automatically update AMI IDs
  assets/aws/Makefile
  assets/aws/update-ami-ids.sh
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/README.md
Labels: documentation, release-engineering

#4251 Fix milv failing test
  docs/4.3/admin-guide.md
Labels: documentation

#4260 Fix windowsaccountname claim format in ADFS examples
  docs/4.1/ssh_adfs.md
  docs/4.2/enterprise/sso/ssh_adfs.md
  docs/4.3/enterprise/sso/ssh_adfs.md
Labels: documentation

#4258 Seperate milv tests to run independently for internal and external links
  .drone.yml
Labels: documentation, release-engineering
