Repository gravitational/teleport, pull requests merged in 2020-05, with the labels that each got.

#3664 Word correction in teleport proxy docs
  docs/4.2/architecture/teleport_proxy.md
Labels: documentation

#3661 Add instructions to install vbguest plugin
  vagrant/README.md
Labels: documentation

#3685 Admin guide minor cleanup
  docs/4.2/admin-guide.md
Labels: documentation

#3687 Add a simple docker pull into installation.
  docs/4.2.yaml
  docs/4.2/installation.md
Labels: documentation

#3702 Change location of /releases/ to downloads
  docs/4.1/installation.md
  docs/4.1/quickstart.md
  docs/4.2/installation.md
  docs/4.2/quickstart.md
Labels: documentation

#3698 Moved SSO outside main Nav
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/enterprise/quickstart-enterprise.md
  docs/4.2/enterprise/ssh_sso.md
  docs/4.2/enterprise/sso/oidc.md
  docs/4.2/enterprise/sso/ssh_adfs.md
  docs/4.2/enterprise/sso/ssh_azuread.md
  docs/4.2/enterprise/sso/ssh_gsuite.md
  docs/4.2/enterprise/sso/ssh_okta.md
  docs/4.2/enterprise/sso/ssh_one_login.md
  docs/4.2/gcp_guide.md
  docs/4.2/index.md
  docs/4.2/kubernetes_ssh.md
  docs/4.2/milv.config.yaml
Labels: documentation

#3723 Set directory permissions for /var/lib/teleport to 0700 when installed via packages
  build.assets/build-package.sh
Labels: build-pipeline, packaging

#3721 Add options to skip connecting to ssh-agent from tsh
  lib/client/api.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  tool/tsh/tsh.go
Labels: docs-required, tsh

#3750 Teleport example helm README update
  examples/chart/teleport/README.md
Labels: helm
