Repository gravitational/teleport, pull requests merged in 2020-12, with the labels that each got.

#5009 Fix response flushing on streaming k8s requests
  lib/kube/proxy/forwarder.go
Labels: backport-required

#4305 RFD 3: Extended approval workflows
  rfd/0003-extended-approval-workflows.md
Labels: rfd

#5018 [5.0] Backport of "Implement DEB repo creation via Drone (#4996)"
  .drone.yml
Labels: release-engineering

#4961 Teleport Kubernetes Service
  docs/4.4/cli-docs.md
  docs/5.0.yaml
  docs/5.0/admin-guide.md
  docs/5.0/api-reference.md
  docs/5.0/cli-docs.md
  docs/5.0/config-reference.md
  docs/5.0/enterprise/ssh-rbac.md
  docs/5.0/faq.md
  docs/5.0/kubernetes-access.md
  docs/5.0/production.md
Labels: documentation

#5019 Always set proxy public_addr port to 443 when ingress is enabled
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/templates/config.yaml
Labels: helm

#4740 RFD 11: Teleport Database Access Preview
  rfd/0011-database-access.md
Labels: database-access, rfd

#5040 Added systemd references to oss quickstart
  docs/5.0/quickstart.md
Labels: documentation

#5008 Always set expiry on server resource in heartbeats
  lib/kube/proxy/server.go
  lib/services/server.go
Labels: backport-required

#5060 Highlight syntax for ports in table production docs
  docs/5.0/production.md
Labels: documentation

#5015 Added --no-use-local-ssh-agent and TELEPORT_USE_LOCAL_SSH_AGENT to CLI docs
  docs/4.4/cli-docs.md
  docs/5.0/cli-docs.md
Labels: documentation

#5038 Multiple fixes for k8s forwarder
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: backport-required

#5069 Provide enterprise create user instructions for terraform example
  examples/aws/terraform/starter-cluster/README.md
Labels: examples, terraform

#5097 Release 5.0.1
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#5066 Add skip secure option example in app access docs
  docs/5.0/application-access.md
Labels: documentation

#5095 Update k8s access and migration docs role example to remove extra brackets
  docs/5.0/kubernetes-5.0-migration.md
  docs/5.0/kubernetes-access.md
Labels: documentation, kubernetes

#5100 [auto] Update AMI IDs for 5.0.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#5101 Add correct volumes to DEB publishing step
  .drone.yml
Labels: backport-required, release-engineering

#5099 Update CHANGELOG for 5.0.1
  CHANGELOG.md
  docs/5.0.yaml
Labels: release-engineering

#5127 [5.0] Backport: Add correct volumes to DEB publishing step (#5101)
  .drone.yml
Labels: release-engineering

#5039 RFD 12: Teleport versioning
  rfd/0012-teleport-versioning.md
Labels: rfd

#5130 [auto] Update AMI IDs for 5.0.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#5131 Update support matrix in FAQ docs for 5.0
  docs/5.0/faq.md
  docs/postrelease.md
Labels: documentation

#5142 Migrated email domain references to goteleport.com
  docs/5.0/admin-guide.md
  docs/5.0/aws-oss-guide.md
  docs/5.0/enterprise/introduction.md
  docs/5.0/enterprise/workflow/ssh-approval-jira-cloud.md
  docs/5.0/faq.md
  docs/5.0/index.md
  docs/5.0/milv.config.yaml
  docs/5.0/user-manual.md
Labels: documentation

#5112 Removes nested tabs
  docs/5.0/quickstart.md
Labels: documentation

#5148 [docs] Fix formatting and indentation
  docs/5.0/cli-docs.md
  docs/5.0/config-reference.md
Labels: documentation

#5157 Teleport AMI fixes
  assets/aws/files/bin/teleport-generate-config
Labels: backport-required, terraform

#5164 [5.0] Backport: Teleport AMI fixes (#5157)
  assets/aws/files/bin/teleport-generate-config
Labels: terraform
