Repository gravitational/teleport, pull requests merged in 2020-10, with the labels that each got.

#4415 Release 4.3.7
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#4149 AWS Terraform Quick Start
  docs/4.0/aws-oss-guide.md
  docs/4.1/aws-oss-guide.md
  docs/4.2/aws-oss-guide.md
  docs/4.2/aws-terraform-guide.md
  docs/4.3/aws-oss-guide.md
  docs/4.3/aws-terraform-guide.md
  examples/aws/terraform/README.md
  examples/aws/terraform/ha-autoscale-cluster/Makefile
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/ha-autoscale-cluster/acm.tf
  examples/aws/terraform/ha-autoscale-cluster/ansible/access.yaml
  examples/aws/terraform/ha-autoscale-cluster/ansible/ansible.cfg
  examples/aws/terraform/ha-autoscale-cluster/ansible/ec2.py
  examples/aws/terraform/ha-autoscale-cluster/ansible/upgrade.yaml
  examples/aws/terraform/ha-autoscale-cluster/ansible/vars.yaml
  examples/aws/terraform/ha-autoscale-cluster/assets/grafana-nginx-acm.conf
  examples/aws/terraform/ha-autoscale-cluster/assets/grafana-nginx.conf
  examples/aws/terraform/ha-autoscale-cluster/assets/health-dashboard.json
  examples/aws/terraform/ha-autoscale-cluster/auth-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/auth_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/auth_network.tf
  examples/aws/terraform/ha-autoscale-cluster/bastion.tf
  examples/aws/terraform/ha-autoscale-cluster/data.tf
  examples/aws/terraform/ha-autoscale-cluster/dynamo.tf
  examples/aws/terraform/ha-autoscale-cluster/locks.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/network.tf
  examples/aws/terraform/ha-autoscale-cluster/node-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/node_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/node_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/node_network.tf
  examples/aws/terraform/ha-autoscale-cluster/provider.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/proxy_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy_network.tf
  examples/aws/terraform/ha-autoscale-cluster/route53.tf
  examples/aws/terraform/ha-autoscale-cluster/s3.tf
  examples/aws/terraform/ha-autoscale-cluster/ssm.tf
  examples/aws/terraform/ha-autoscale-cluster/vars.tf
  examples/aws/terraform/ha-autoscale-cluster/vpc.tf
  examples/aws/terraform/starter-cluster/Makefile
  examples/aws/terraform/starter-cluster/README.md
  examples/aws/terraform/starter-cluster/cluster.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
  examples/aws/terraform/starter-cluster/cluster_sg.tf
  examples/aws/terraform/starter-cluster/data.tf
  examples/aws/terraform/starter-cluster/data.tpl
  examples/aws/terraform/starter-cluster/dynamo.tf
  examples/aws/terraform/starter-cluster/route53.tf
  examples/aws/terraform/starter-cluster/s3.tf
  examples/aws/terraform/starter-cluster/ssm.tf
  examples/aws/terraform/starter-cluster/vars.tf
Labels: documentation

#4453 Update Teleport Helm/Terraform/CloudFormation to 4.3.7
  Makefile
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/README.md
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport/values.yaml
Labels: release-engineering

#4465 Fix Drone signature on master
  .drone.yml
Labels: release-engineering

#4467 Release 4.4.0-rc.1
  Makefile
  version.go
Labels: release-engineering

#4463 Add amazon linux 2 instructions for enhanced logging
  docs/4.3/features/enhanced-session-recording.md
  docs/4.4/features/enhanced-session-recording.md
Labels: documentation

#4470 Fix build script after shellcheck breakage
  build.assets/build-package.sh
Labels: backport-required, release-engineering

#4472 [4.4] Backport "Fix build script after shellcheck breakage" (#4470)
  build.assets/build-package.sh
Labels: release-engineering

#4474 Fix AWS AMI install script after shellcheck breakage
  assets/aws/files/install.sh
Labels: backport-required, release-engineering

#4464 Run Drone tests on stratus branch
  .drone.yml
Labels: release-engineering

#4477 Revert "Fix shellcheck quotation warnings"
  Makefile
  assets/aws/files/install.sh
  assets/aws/files/make-amis-public.sh
  assets/aws/update-ami-ids.sh
  build.assets/build-package.sh
  docs/build.sh
  docs/run.sh
  examples/etcd/etcdctl.sh
  examples/etcd/start-etcd-insecure.sh
  examples/etcd/start-etcd.sh
  examples/etcd/start-teleport-insecure.sh
  examples/etcd/start-teleport.sh
  examples/gke-auth/get-kubeconfig.sh
  examples/k8s-auth/get-kubeconfig.sh
Labels: release-engineering

#4480 Release 4.4.0-rc.3
  Makefile
  version.go
Labels: release-engineering

#4478 Fix whitespace errors in docs causing linter failures
  docs/4.3/features/enhanced-session-recording.md
  docs/4.4/features/enhanced-session-recording.md
Labels: documentation

#4437 Run k8s integration tests in Drone
  .drone.yml
  fixtures/ci-teleport-rbac/ci-teleport.yaml
  integration/kube_integration_test.go
Labels: release-engineering

#4483 [4.4] Backport "Run k8s integration tests in Drone (#4437)"
  .drone.yml
  fixtures/ci-teleport-rbac/ci-teleport.yaml
  integration/kube_integration_test.go
Labels: release-engineering

#4487 Fix name of unit test job in Drone
  .drone.yml
Labels: release-engineering

#4492 Add X11 Forwarding to Role example doc
  docs/4.3/enterprise/ssh-rbac.md
  docs/4.4/enterprise/ssh-rbac.md
Labels: documentation

#4505 Update .drone.yml in stratus
  .drone.yml
Labels: release-engineering

#4502 Remove Marketplace AMI builds, plus other tidying
  .drone.yml
  assets/aws/Jenkinsfile-build-ent
  assets/aws/Jenkinsfile-build-oss
  assets/aws/Makefile
  assets/aws/single-ami.json
  assets/aws/update-ami-ids.sh
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/README.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: backport-required, release-engineering, terraform

#4527 Add minimum OpenSSH version plus raw/endraw directives
  docs/4.3/openssh-teleport.md
  docs/4.4/enterprise/ssh-rbac.md
  docs/4.4/openssh-teleport.md
Labels: documentation

#4529 Added --out parameter to openssh host signing example
  docs/4.3/openssh-teleport.md
  docs/4.4/openssh-teleport.md
Labels: documentation

#4528 Explicitly mount /tmp as an emptyDir for docker:dind and integration tests
  .drone.yml
Labels: release-engineering

#4555 Try to build Teleport release on push and send a Slack notification if it fails
  .drone.yml
Labels: release-engineering

#4558 Write binary build failure notifications to dev-teleport channel instead
  .drone.yml
Labels: release-engineering

#4561 Modify script example to pull k8s config in docs
  docs/4.3/kubernetes-ssh.md
  docs/4.4/kubernetes-ssh.md
Labels: documentation, kubernetes

#4563 Release 4.4.0-rc.4
  Makefile
  version.go
Labels: release-engineering

#4560 Stop test execution early for changes to docs only
  .drone.yml
Labels: release-engineering

#4576 Install ca-certificates from package rather than copying manually
  .drone.yml
  build.assets/Dockerfile-cron
Labels: release-engineering

#4604 Add clarification on *-sync modes to changelog
  CHANGELOG.md
Labels: backport-required, documentation

#4608 Update examples to 4.4
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport/values.yaml
Labels: documentation, release-engineering

#4609 Backport of "Add clarification on *-sync modes to changelog (#4604)"
  CHANGELOG.md
Labels: documentation

#4612 Release 4.4.1
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#4596 Fix syntax and indentation in PAM docs
  docs/4.2/features/ssh-pam.md
  docs/4.3/features/ssh-pam.md
  docs/4.4/features/ssh-pam.md
Labels: documentation

#4614 Update changelog for 4.4.1
  CHANGELOG.md
Labels: release-engineering

#4602 Bump up Teleport version for cron-built Docker images
  .drone.yml
Labels: release-engineering

#4615 Update docs reference to 4.4.1
  docs/4.4.yaml
Labels: documentation

#4620 Add post-release checklist
  docs/postrelease.md
  docs/preflight.md
  docs/prerelease.md
Labels: documentation

#4624 Add auto PR logic for AMIs
  assets/aws/Makefile
Labels: release-engineering

#4625 [auto] Update AMI IDs for 4.4.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#4647 Use tmpfs instead of disk storage
  .drone.yml
  build.assets/Makefile
Labels: release-engineering

#4639 Add arm64 builds to Drone
  .drone.yml
Labels: backport-required, release-engineering

#4657 [4.4] Backport: Add arm64 builds
  .drone.yml
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#4658 [4.3] Backport: Add arm64 builds
  .drone.yml
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#4671 Restore tunnel_public_addr to docs
  docs/4.3/config-reference.md
  docs/4.4/config-reference.md
Labels: documentation

#4628 Update Ubuntu versions in enhanced sessions docs
  docs/4.4/features/enhanced-session-recording.md
Labels: documentation

#4668 Added 4.4.2 to CHANGELOG
  CHANGELOG.md
Labels: release-engineering
