Repository gravitational/teleport, pull requests merged in 2020-11, with the labels that each got.

#4679 Update Docker docs for 4.4
  docs/4.4/enterprise/quickstart-enterprise.md
  docs/4.4/quickstart-docker.md
Labels: documentation

#4683 Fixing extra s/admins/admin in examples resources
  examples/resources/github.yaml
  examples/resources/oidc-connector.yaml
Labels: examples, sso

#4691 Bump Teleport 4.4.2 and add Arm64
  docs/4.4.yaml
  docs/4.4/installation.md
Labels: documentation

#4701 Fix dead link in README
  README.md
Labels: documentation

#4649 Utilize IMDS v2 endpoints for instance metadata.
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-lock
Labels: c-co

#4728 Fix 4.4 closed issues link text
  CHANGELOG.md
Labels: documentation

#4607 Backport of "Remove Marketplace AMI builds, plus other tidying (#4502)"
  .drone.yml
  assets/aws/Jenkinsfile-build-ent
  assets/aws/Jenkinsfile-build-oss
  assets/aws/Makefile
  assets/aws/files/make-amis-public.sh
  assets/aws/single-ami.json
  assets/aws/update-ami-ids.sh
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/README.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: release-engineering, terraform

#4743 [auto] Update AMI IDs for 4.4.4
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#4664 Fixes IAM Permissions
  docs/4.4/aws-oss-guide.md
Labels: documentation

#4732 Adding Request Reason to Access Workflows
  docs/4.4/cli-docs.md
  docs/4.4/enterprise/workflow/index.md
Labels: documentation

#4690 Implement RPM repo creation via Drone
  .drone.yml
  build.assets/build-package.sh
Labels: release-engineering

#4775 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#4704 Go API Docs improved descriptions/examples
  docs/4.4/api-reference.md
  examples/go-client/.gitignore
  examples/go-client/README.md
  examples/go-client/access_workflow.go
  examples/go-client/api-admin.yaml
  examples/go-client/client.go
  examples/go-client/main.go
  examples/go-client/role.go
  examples/go-client/token.go
Labels: documentation

#4796 Skip publishing of pre-release RPMs
  .drone.yml
Labels: release-engineering

#4809 Update to Helm v3 and package all charts
  .drone.yml
  examples/chart/teleport-auto-trustedcluster/Chart.yaml
  examples/chart/teleport-auto-trustedcluster/README.md
  examples/chart/teleport-auto-trustedcluster/templates/deployment.yaml
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-daemonset/Chart.yaml
  examples/chart/teleport-daemonset/README.md
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/HIGHAVAILABILITY.md
  examples/chart/teleport/README.md
  examples/chart/teleport/values.yaml
Labels: helm, release-engineering

#4816 Fix S3 bucket location for Helm chart publishing job
  .drone.yml
Labels: helm, release-engineering

#4810 Creation of preview folder for early access releases.
  docs/4.4.yaml
  docs/4.4/img/aap.svg
  docs/4.4/img/dbaccess.svg
  docs/4.4/preview/teleport-application-access.md
  docs/4.4/preview/teleport-database-access.md
  docs/5.0/img/aap.svg
  docs/5.0/img/dbaccess.svg
  docs/5.0/preview/teleport-database-access.md
Labels: documentation

#4827 Release 4.4.5
  Makefile
  version.go
Labels: release-engineering

#4831 Update CHANGELOG.md
  CHANGELOG.md
Labels: backport-required, documentation, release-engineering

#4839 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, release-engineering

#4853 Bump Go to 1.15.5
  .drone.yml
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
  build.assets/Makefile
  docker/Dockerfile
Labels: release-engineering

#4854 Update all charts repo references to new domain
  docs/4.3/installation.md
  docs/4.3/kubernetes-ssh.md
  docs/4.4/installation.md
  docs/4.4/kubernetes-ssh.md
  docs/5.0/installation.md
  docs/5.0/kubernetes-ssh.md
Labels: documentation

#4744 Various AMI fixes
  Makefile
  assets/aws/Makefile
  assets/aws/files/bin/teleport-check-cert
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-lock
  assets/aws/files/bin/teleport-monitor-setup
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/bin/teleport-ssm-publish-tokens
  assets/aws/files/install.sh
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-check-cert.service
  assets/aws/files/system/teleport-generate-config.service
  assets/aws/files/system/teleport-get-cert.service
  assets/aws/files/system/teleport-monitor-setup.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport-renew-cert.service
  assets/aws/files/system/teleport-ssm-publish-tokens.service
  assets/aws/files/system/teleport.service
  assets/aws/single-ami.json
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
Labels: backport-required, release-engineering, terraform

#4779 Updated RBAC Resources Section
  docs/4.4/enterprise/ssh-rbac.md
  docs/5.0/enterprise/ssh-rbac.md
Labels: documentation

#4742 Fixed a bug with making AMIs public
  assets/aws/files/make-amis-public.sh
Labels: release-engineering

#4865 Fix a server parsing regression between 4.4 and 5.0
  lib/auth/proto/authservice.pb.go
  lib/auth/proto/authservice.proto
  lib/services/server.go
  lib/services/servers_test.go
  lib/services/types.pb.go
  lib/services/types.proto
Labels: backport-required

#4858 Add more data to k8s session events
  lib/auth/permissions.go
  lib/events/events.pb.go
  lib/events/events.proto
  lib/kube/proxy/auth.go
  lib/kube/proxy/auth_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/remotecommand.go
  lib/kube/proxy/server.go
  lib/utils/conn.go
Labels: backport-required

#4802 Selectively backport branch/4.4 .drone.yml to branch/4.3
  .drone.yml
Labels: release-engineering

#4888 [5.0] Backport #4742 and #4744
  Makefile
  assets/aws/Makefile
  assets/aws/files/bin/teleport-check-cert
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-lock
  assets/aws/files/bin/teleport-monitor-setup
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/bin/teleport-ssm-publish-tokens
  assets/aws/files/install.sh
  assets/aws/files/make-amis-public.sh
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-check-cert.service
  assets/aws/files/system/teleport-generate-config.service
  assets/aws/files/system/teleport-get-cert.service
  assets/aws/files/system/teleport-monitor-setup.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport-renew-cert.service
  assets/aws/files/system/teleport-ssm-publish-tokens.service
  assets/aws/files/system/teleport.service
  assets/aws/single-ami.json
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
Labels: release-engineering, terraform

#4885 Prevent a panic in tsh kube login when logged out
  lib/client/api.go
  tool/tsh/kube.go
Labels: backport-required

#4635 RFD 8: Teleport Application Access
  rfd/0008-application-access.md
Labels: rfd

#4887 Updated default admin role.
  lib/services/role.go
Labels: backport-required

#4893 UX improvements for kube CLI interactions
  lib/config/fileconf.go
  lib/kube/kubeconfig/kubeconfig.go
  tool/tctl/common/resource_command.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: backport-required

#4791 Application Access
  docs/5.0.yaml
  docs/5.0/admin-guide.md
  docs/5.0/application-access.md
  docs/5.0/cli-docs.md
  docs/5.0/config-reference.md
  docs/5.0/enterprise/ssh-rbac.md
  docs/5.0/img/applications/applications-example.svg
  docs/5.0/index.md
  docs/5.0/milv.config.yaml
  docs/5.0/production.md
  docs/5.0/quickstart.md
Labels: documentation

#4800 Configure etcd client's message size
  docs/4.4/admin-guide.md
  docs/5.0/admin-guide.md
  lib/backend/etcdbk/etcd.go
  lib/backend/etcdbk/etcd_test.go
  lib/srv/regular/sshserver_test.go
Labels: backport-required

#4926 Adds a note about installing for MacOS via Homebrew
  docs/4.3/installation.md
  docs/4.3/user-manual.md
  docs/4.4/installation.md
  docs/4.4/user-manual.md
  docs/5.0/installation.md
  docs/5.0/quickstart.md
  docs/5.0/user-manual.md
Labels: documentation

#4868 [auto] Update AMI IDs for 4.4.5
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#4830 Only test internal docs links with milv via Makefile
  Makefile
Labels: documentation

#4950 Update Terraform to 0.13
  examples/aws/terraform/ha-autoscale-cluster/provider.tf
  examples/aws/terraform/ha-autoscale-cluster/versions.tf
Labels: terraform

#4952 Update descriptions for short-lived dynamic tokens
  docs/4.4/admin-guide.md
  docs/5.0/admin-guide.md
Labels: documentation

#4927 Fix Demo and Application Access
  docs/5.0/application-access.md
  docs/5.0/preview/teleport-database-access.md
Labels: documentation

#4947 Added HTTP method to app.session.request.
  lib/events/events.pb.go
  lib/events/events.proto
  lib/services/types.pb.go
  lib/srv/app/transport.go
Labels: backport-required

#4948 Added error checking to Application Access CLI.
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: backport-required

#4962 Add Meta / Desc to Database Access Preview
  docs/5.0/preview/teleport-database-access.md
Labels: documentation

#4935 Change log about missing kube clusters on login to debug
  lib/auth/auth.go
Labels: backport-required

#4973 Use the absolute tsh path in kube exec plugin
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: backport-required

#4979 [5.0] Backport of "Teleport 5.0 Changelog (#4785)"
  CHANGELOG.md
Labels: documentation

#4980 Release 5.0.0
  Makefile
  version.go
Labels: release-engineering

#4932 Cherry pick Gravitational -> GoTeleport CLI Messages
  CODE_OF_CONDUCT.md
  lib/auth/saml.go
  lib/config/configuration.go
  lib/events/gcssessions/gcsstream_test.go
  lib/kube/proxy/auth.go
  lib/service/cfg.go
  lib/utils/parse/parse.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh.go
Labels: cli

#4971 Add Slack notification on failure of `teleport-helm-cron` job
  .drone.yml
Labels: release-engineering

#4981 [auto] Update AMI IDs for 5.0.0
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#4982 Post-release checklist for 5.0
  .drone.yml
  docker/teleport-ent-quickstart.yml
  docker/teleport-quickstart.yml
  docs/5.0.yaml
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport/values.yaml
Labels: documentation, release-engineering

#4955 Update metrics endpoint from 3434 to default 3000 as per docs
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
  docs/5.0/aws-terraform-guide.md
  docs/5.0/cli-docs.md
  examples/systemd/production/auth/teleport.service
  tool/tctl/common/top_command.go
Labels: backport-required, observability, terraform

#4632 RFD 2: Adds RBAC in OSS proposal
  rfd/0007-rbac-oss.md
Labels: rfd

#4983 Firestore `audit_events_uri` needs projectID set otherwise it fails to work
  docs/4.4/gcp-guide.md
  docs/5.0/gcp-guide.md
Labels: documentation, test-plan-problem

#5006 Update quickstart docs
  docs/5.0/quickstart.md
Labels: documentation

#4996 Implement DEB repo creation via Drone
  .drone.yml
Labels: backport-required, release-engineering
