Repository gravitational/teleport, pull requests merged in 2020-03, with the labels that each got.

#3388 grammar fixes
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/architecture/teleport_auth.md
  docs/4.2/architecture/teleport_nodes.md
  docs/4.2/enterprise/index.md
  docs/4.2/enterprise/quickstart-enterprise.md
  docs/4.2/quickstart.md
Labels: documentation

#3399 Use HTTPS for backend connections from LB with Terraform and ACM
  assets/marketplace/Makefile
  assets/marketplace/files/system/teleport-acm.service
  assets/marketplace/files/system/teleport-proxy-acm.service
  examples/aws/terraform/proxy_network.tf
Labels: terraform

#3338 Documentation for using Teleport with Linux PAM
  docs/4.2.yaml
  docs/4.2/admin-guide.md
  docs/4.2/features/ssh_pam.md
  docs/4.2/img/motd/teleport-no-MOTD.png
  docs/4.2/img/motd/teleport-with-MOTD.png
  docs/4.2/img/motd/teleport-with-updated-MOTD.png
Labels: documentation

#3403 Additional formatting fixes for PAM documentation
  docs/4.2/features/ssh_pam.md
Labels: documentation

#3405 Update region list/Teleport version for Terraform
  examples/aws/terraform/README.md
Labels: terraform

#3410 Add Terraform docs/HA guide
  docs/4.2.yaml
  docs/4.2/aws_terraform_guide.md
  docs/4.2/milv.config.yaml
Labels: documentation, terraform

#3409 Adds support for custom OIDC prompts
  constants.go
  lib/auth/oidc.go
  lib/services/oidc.go
  lib/services/oidc_test.go
Labels: R1, sso

#3406 Small tweaks to AWS Docs
  docs/4.1/aws_oss_guide.md
  docs/4.2/aws_oss_guide.md
Labels: aws, documentation

#3426 GCP Documentation updates for permissions
  docs/4.2/gcp_guide.md
  docs/4.2/img/gcp/gcp-permissions.png
Labels: documentation

#3424 Add link to Terraform HA guide
  docs/4.2/aws_oss_guide.md
Labels: documentation, terraform

#3443 Fix formatting on Okta Guide
  docs/4.2/ssh_okta.md
Labels: documentation

#3448 Remove toc_depth
  docs/4.2.yaml
Labels: documentation

#3451 Teleport version incorrect on pam doc
  docs/4.2/features/ssh_pam.md
Labels: PAM, documentation

#3450 Update doc
  docs/4.2/admin-guide.md
  docs/4.2/quickstart.md
Labels: documentation

#3452 Update keep_alive_interval to reflect default
  docs/4.1/admin-guide.md
  docs/4.2/admin-guide.md
Labels: documentation

#3453 Add keep_alive_interval to AMI config
  assets/marketplace/files/bin/teleport-generate-config
Labels: documentation

#3456 Added ability for RequestSubsystem to cancelled.
  lib/client/client.go
Labels: tsh

#3466 Improve trusted cluster guide with specifics
  docs/4.2/aws_terraform_guide.md
Labels: documentation

#3475 Fix auth_service token documentation in GCP Guide
  docs/4.2/gcp_guide.md
Labels: documentation

#3461 Remove extra mention of jump hosts in user manual
  docs/4.2/user-manual.md
Labels: documentation

#3486 Update confusing Kubernetes wording in admin guide
  docs/4.2/admin-guide.md
Labels: documentation

#3498 Update gsuite instructions for service account
  docs/4.1/img/gsuite/gsuite-6-manage-api-access.png
  docs/4.1/img/gsuite/gsuite-6a-manage-access.png
  docs/4.2/img/gsuite/gsuite-6-manage-api-access.png
  docs/4.2/img/gsuite/gsuite-6a-manage-access.png
  docs/4.2/ssh_gsuite.md
Labels: documentation

#3501 Update to include testing SSO Providers / Partners
  docs/testplan.md
Labels: testplan

#3502 Update Cloudformation to reflect AMI changes
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
Labels: cloudformation
