Repository gravitational/teleport, pull requests merged in 2020-02, with the labels that each got.

#3287 Add reset/passwd capability for local users
  Makefile
  build.assets/grpc/Dockerfile
  integration/integration_test.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/new_web_user.go
  lib/auth/password.go
  lib/auth/password_test.go
  lib/auth/proto/auth.pb.go
  lib/auth/proto/auth.proto
  lib/auth/proto/proto.go
  lib/auth/resetpasswordtoken.go
  lib/auth/resetpasswordtoken_test.go
  lib/auth/tls_test.go
  lib/auth/user.go
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/slice.pb.go
  lib/events/slice.proto
  lib/services/identity.go
  lib/services/invite.go
  lib/services/local/resetpasswordtoken.go
  lib/services/local/users.go
  lib/services/resetpasswordtoken.go
  lib/services/resetpasswordtoken_test.go
  lib/services/resetpasswordtokensecrets.go
  lib/services/resource.go
  lib/services/types.pb.go
  lib/services/types.proto
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
  lib/web/ui/resetpasswordtoken.go
  lib/wrappers/wrappers.pb.go
  lib/wrappers/wrappers.proto
  tool/tctl/common/user_command.go
Labels: hornet

#3314 Updated mkdocs base image
  build.assets/docs.dockerfile
  docs/1.3.yaml
  docs/2.0.yaml
  docs/2.3.yaml
  docs/2.4.yaml
  docs/2.5.yaml
  docs/2.5/index.html
  docs/2.5/index.md
  docs/2.7.yaml
  docs/2.7/index.html
  docs/2.7/index.md
  docs/3.0.yaml
  docs/3.0/index.html
  docs/3.0/index.md
  docs/3.1.yaml
  docs/3.1/index.html
  docs/3.1/index.md
  docs/3.2.yaml
  docs/3.2/README.md
  docs/3.2/index.html
  docs/3.2/index.md
  docs/4.0.yaml
  docs/4.0/README.md
  docs/4.0/architecture.md
  docs/4.0/index.html
  docs/4.0/index.md
  docs/4.1.yaml
  docs/4.1/admin-guide.md
  docs/4.1/architecture/teleport_architecture_overview.md
  docs/4.1/index.html
  docs/4.1/index.md
  docs/4.1/quickstart.md
  docs/4.2.yaml
  docs/4.2/README.md
  docs/4.2/aws_ent_guide.md
  docs/4.2/draw.io/README.md
  docs/4.2/draw.io/teleport-auth.html
  docs/4.2/draw.io/teleport-just-proxy.html
  docs/4.2/draw.io/teleport-proxy-ssh.html
  docs/4.2/draw.io/teleport-tunnels.html
  docs/4.2/enterprise/ssh_fips.md
  docs/4.2/index.html
  docs/4.2/index.md
  docs/4.2/quickstart__archive.md
  docs/run.sh
  docs/theme/main.html
  docs/theme/scripts.html
  docs/theme/search.html
  docs/theme/searchbox.html
  docs/theme/src/default.css
  docs/theme/src/docs.js
  docs/theme/src/highlight.pack.js
  docs/theme/src/solarized-dark.css
  docs/theme/src/third-party.js
  docs/theme/toc.html
Labels: documentation

#3319 Update Terraform code to support Terraform 0.12.x and AWS provider 2.x
  examples/aws/terraform/acm.tf
  examples/aws/terraform/auth_asg.tf
  examples/aws/terraform/auth_iam.tf
  examples/aws/terraform/auth_network.tf
  examples/aws/terraform/bastion.tf
  examples/aws/terraform/data.tf
  examples/aws/terraform/dynamo.tf
  examples/aws/terraform/locks.tf
  examples/aws/terraform/monitor_asg.tf
  examples/aws/terraform/monitor_iam.tf
  examples/aws/terraform/network.tf
  examples/aws/terraform/node_asg.tf
  examples/aws/terraform/node_iam.tf
  examples/aws/terraform/node_network.tf
  examples/aws/terraform/provider.tf
  examples/aws/terraform/proxy_asg.tf
  examples/aws/terraform/proxy_iam.tf
  examples/aws/terraform/proxy_network.tf
  examples/aws/terraform/route53.tf
  examples/aws/terraform/s3.tf
  examples/aws/terraform/ssm.tf
  examples/aws/terraform/vars.tf
  examples/aws/terraform/vpc.tf
Labels: terraform

#3333 Add auth server LB public_addr to Teleport config
  assets/marketplace/files/bin/teleport-generate-config
  examples/aws/terraform/auth-user-data.tpl
  examples/aws/terraform/auth_asg.tf
Labels: terraform

#3355 Add clarification on platforms for clients
  docs/4.2/architecture/teleport_architecture_overview.md
Labels: documentation

#3352 grammar fixes
  docs/4.2/admin-guide.md
  docs/4.2/architecture/teleport_architecture_overview.md
  docs/4.2/faq.md
  docs/4.2/features/enhanced_session_recording.md
  docs/4.2/index.md
  docs/4.2/installation.md
  docs/4.2/quickstart.md
  docs/4.2/ssh_okta.md
  docs/4.2/user-manual.md
Labels: documentation

#3364 Fix typo which prevents certificate renewal on all-in-one AMI installs
  assets/marketplace/files/bin/teleport-generate-config
Labels: build-pipeline

#3380 Tip on our enhanced session recording page.
  docs/4.2/architecture/teleport_architecture_overview.md
  docs/4.2/architecture/teleport_auth.md
  docs/4.2/features/enhanced_session_recording.md
  docs/4.2/trustedclusters.md
Labels: documentation

#3381 Updated Auth Connectors Examples
  build.assets/docs.dockerfile
  docs/4.2.yaml
  docs/4.2/enterprise/ssh_sso.md
  docs/4.2/img/teleport-sso/bitbucket.png
  docs/4.2/img/teleport-sso/custom-content.png
  docs/4.2/img/teleport-sso/github.png
  docs/4.2/img/teleport-sso/google.png
  docs/4.2/img/teleport-sso/microsoft.png
  docs/4.2/img/teleport-sso/openId.png
  docs/4.2/oidc.md
  docs/4.2/ssh_adfs.md
  docs/4.2/ssh_gsuite.md
  docs/4.2/ssh_okta.md
  docs/4.2/ssh_one_login.md
  examples/resources/adfs-connector.yaml
  examples/resources/admin.yaml
  examples/resources/github.yaml
  examples/resources/gsuite-connector.yaml
  examples/resources/oidc-connector.yaml
  examples/resources/onelogin-connector.yaml
  examples/resources/role.yaml
  examples/resources/saml-connector.yaml
  examples/resources/trusted_cluster.yaml
  examples/resources/trusted_cluster_enterprise.yaml
  examples/resources/user.yaml
Labels: documentation
