Repository gravitational/teleport, pull requests merged in 2021-03, with the labels that each got.

#5784 fix #5783 utmp regression on MacOS
  lib/srv/reexec.go
  lib/srv/uacc/uacc_linux.go
  lib/srv/uacc/uacc_stub.go
Labels: backport-required

#5802 Release 6.0.0-rc.2
  Makefile
  version.go
Labels: release-engineering

#5810 Update Admin Guide user section to mention roles
  docs/pages/admin-guide.mdx
Labels: documentation

#5814 Fixed `tctl get`. Had `delete` instead of `get`
  docs/pages/cli-docs.mdx
Labels: documentation

#5805 mfa: delete user MFA devices on account reset
  lib/auth/resetpasswordtoken.go
  lib/auth/resetpasswordtoken_test.go
Labels: backport-required

#5895 Publish teleport-cluster Helm chart
  .drone.yml
  examples/chart/index.html
Labels: release-engineering

#5894 [auto] Update AMI IDs for 6.0.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#5922 (v6) Fix --insecure-no-tls flag
  integration/integration_test.go
  lib/service/service.go
Labels: backport-required, regression

#5908 Run next linter on docs PRs
  .drone.yml
  Makefile
  build.assets/Makefile
  build.assets/docs.dockerfile
  docs/README.md
Labels: release-engineering

#5888 RFD 12: add git branching details
  rfd/0012-teleport-versioning.md
Labels: rfd

#5865 Update Kubernetes Access docs
  docs/config.json
  docs/img/k8s/auth.svg
  docs/pages/kubernetes-access.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/kubernetes-access/guides/cicd.mdx
  docs/pages/kubernetes-access/guides/federation.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
Labels: documentation

#5896 Add teleport:6 nightly Docker image
  .drone.yml
Labels: release-engineering

#5742 Add Features and PublicAddrs to PingResponse
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  lib/auth/auth_with_roles.go
  lib/modules/modules.go
Labels: feature-request

#5944 correct title for app access docs
  docs/pages/application-access.mdx
Labels: documentation

#5598 Support encrypted SAML assertions
  api/types/saml.go
  docs/testplan.md
  lib/auth/saml_test.go
  lib/fixtures/fixtures.go
  lib/services/saml.go
  lib/services/suite/suite.go
  lib/services/types.go
Labels: c-pa

#5931 Update VERSION on master to v7.0.0-dev
  .drone.yml
  Makefile
  version.go
Labels: release-engineering

#5563 Add google_service_account inline field option for Google Workspace/GSuite OIDC
  api/types/oidc.go
  lib/auth/oidc.go
  lib/services/local/users.go
  lib/services/oidc.go
Labels: cloud, sso

#5963 getting started configure doc fix
  docs/pages/getting-started.mdx
Labels: documentation

#5980 misspellings in docs
  docs/pages/admin-guide.mdx
  docs/pages/application-access.mdx
  docs/pages/cloud.mdx
  docs/pages/index.mdx
  docs/pages/kubernetes-access.mdx
Labels: documentation

#5983 Update Helm charts to use Teleport 6 by default
  examples/chart/teleport-auto-trustedcluster/Chart.yaml
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-daemonset/Chart.yaml
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-all-v5.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-all-v6.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-db.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/values.yaml
Labels: backport-required, release-engineering

#5535 Updating starter-cluster to Terraform 0.14
  examples/aws/terraform/starter-cluster/README.md
  examples/aws/terraform/starter-cluster/data.tf
  examples/aws/terraform/starter-cluster/route53.tf
Labels: examples

#5974 Fix title for app access in 6 docs
  docs/pages/application-access.mdx
Labels: documentation

#5682 Add unit tests to teleport-generate-config AMI script
  Makefile
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/tests/fixtures/common.bash
  assets/aws/files/tests/fixtures/test-setup.bash
  assets/aws/files/tests/fixtures/test-teardown.bash
  assets/aws/files/tests/ha-auth-fips.bats
  assets/aws/files/tests/ha-auth-oss.bats
  assets/aws/files/tests/ha-auth.bats
  assets/aws/files/tests/ha-node.bats
  assets/aws/files/tests/ha-proxy-acm.bats
  assets/aws/files/tests/ha-proxy.bats
  assets/aws/files/tests/starter-cluster-acm-fips.bats
  assets/aws/files/tests/starter-cluster-acm.bats
  assets/aws/files/tests/starter-cluster-fips.bats
  assets/aws/files/tests/starter-cluster.bats
  build.assets/Dockerfile
  build.assets/Makefile
Labels: release-engineering, terraform

#5937 Add support for building ARM/ARM64 RPM/DEB packages
  build.assets/build-package.sh
Labels: release-engineering

#5885 RFD 19 - Event Fetch API with Pagination
  rfd/0019-event-iteration-api.md
Labels: rfd

#5939 mfa: add cluster-level require_session_mfa option
  api/types/authentication.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/permissions.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/config/fileconf.go
  lib/kube/proxy/forwarder.go
  lib/services/authentication.go
  lib/services/configuration.go
  lib/services/local/configuration.go
  lib/services/local/events.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/app/server.go
  lib/srv/authhandlers.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
Labels: documentation

#6053 Remove .bash suffix from bats includes to enable compatibility with older versions
  assets/aws/files/tests/fixtures/common.bash
  assets/aws/files/tests/ha-auth-fips.bats
  assets/aws/files/tests/ha-auth-oss.bats
  assets/aws/files/tests/ha-auth.bats
  assets/aws/files/tests/ha-node.bats
  assets/aws/files/tests/ha-proxy-acm.bats
  assets/aws/files/tests/ha-proxy.bats
  assets/aws/files/tests/starter-cluster-acm-fips.bats
  assets/aws/files/tests/starter-cluster-acm.bats
  assets/aws/files/tests/starter-cluster-fips.bats
  assets/aws/files/tests/starter-cluster.bats
Labels: release-engineering

#6052 Move linter config to .golangci.yml and remove surplus Makefile lines
  .golangci.yml
  Makefile
  build.assets/Dockerfile
  lib/auth/middleware.go
Labels: release-engineering

#6028 (v6) Fix app access websockets support
  go.mod
  go.sum
  integration/app_integration_test.go
  integration/integration_test.go
  lib/reversetunnel/transport.go
  lib/srv/app/session.go
  lib/srv/app/transport.go
  lib/utils/fakeconn.go
  lib/utils/fakeconn_test.go
  lib/web/app/session.go
  lib/web/app/transport.go
  vendor/github.com/gravitational/oxy/forward/fwd.go
  vendor/modules.txt
Labels: application-access, backport-required

#5920 Enforces valid UTF8 keys on data backends
  lib/backend/backend.go
  lib/backend/dynamo/README.md
  lib/backend/dynamo/dynamodbbk_test.go
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
  lib/backend/test/suite.go
Labels: backport-required

#6072 (7.0) Fix app access websockets support
  go.mod
  go.sum
  integration/app_integration_test.go
  integration/integration_test.go
  lib/reversetunnel/transport.go
  lib/srv/app/session.go
  lib/srv/app/transport.go
  lib/utils/fakeconn.go
  lib/utils/fakeconn_test.go
  lib/web/app/session.go
  lib/web/app/transport.go
  vendor/github.com/gravitational/oxy/forward/fwd.go
  vendor/modules.txt
Labels: application-access

#6089 (6.1) App access cli flow
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/events.go
  api/types/session.go
  api/types/types.pb.go
  api/types/types.proto
  integration/app_integration_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/client/api.go
  lib/client/client.go
  lib/client/interfaces.go
  lib/client/keystore.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/service.go
  lib/services/server.go
  lib/srv/app/server_test.go
  lib/tlsca/ca.go
  lib/web/apiserver.go
  lib/web/app/handler.go
  lib/web/apps.go
  tool/tsh/app.go
  tool/tsh/tsh.go
Labels: application-access

#5918 (7.0) App access client cert auth
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/events.go
  api/types/session.go
  api/types/types.pb.go
  api/types/types.proto
  integration/app_integration_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/client/api.go
  lib/client/client.go
  lib/client/interfaces.go
  lib/client/keystore.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/service.go
  lib/services/server.go
  lib/srv/app/server_test.go
  lib/tlsca/ca.go
  lib/web/apiserver.go
  lib/web/app/handler.go
  lib/web/apps.go
  tool/tsh/app.go
  tool/tsh/tsh.go
Labels: application-access, backport-required

#5941 (7.0) Add Postgres Cloud SQL support
  api/types/databaseserver.go
  api/types/types.pb.go
  api/types/types.proto
  go.mod
  go.sum
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/services/databaseserver.go
  lib/srv/db/aws.go
  lib/srv/db/common/auth.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/server.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/doc.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/iam_credentials_client.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/common.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/iamcredentials.pb.go
  vendor/honnef.co/go/tools/pattern/match.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/honnef.co/go/tools/version/version.go
  vendor/modules.txt
Labels: backport-required, database-access

#6090 (6.1) Add Postgres Cloud SQL support
  api/types/databaseserver.go
  api/types/types.pb.go
  api/types/types.proto
  go.mod
  go.sum
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/services/databaseserver.go
  lib/srv/db/aws.go
  lib/srv/db/common/auth.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/server.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/doc.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/iam_credentials_client.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/common.pb.go
  vendor/google.golang.org/genproto/googleapis/iam/credentials/v1/iamcredentials.pb.go
  vendor/honnef.co/go/tools/pattern/match.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/honnef.co/go/tools/version/version.go
  vendor/modules.txt
Labels: database-access

#6106 drone: Add ARM/ARM64 package builds
  .drone.yml
  dronegen/tag.go
Labels: release-engineering

#6044 Backport Getting started with Kubernetes
  docs/pages/kubernetes-access/getting-started.mdx
Labels: documentation

#6055 (6.1) Update application access docs
  docs/config.json
  docs/pages/application-access.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/api-access.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/jwt.mdx
  docs/pages/application-access/reference.mdx
Labels: application-access, backport-required, documentation

#5441 Custom Approval Conditions
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/go.mod
  api/go.sum
  api/types/access_request.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/client/interfaces.go
  lib/events/api.go
  lib/events/codes.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/local/dynamic_access.go
  lib/services/parser.go
  lib/services/role.go
  lib/services/services.go
  lib/utils/cli.go
  tool/tctl/common/access_request_command.go
  tool/tctl/common/resource_command.go
  tool/tsh/access_request.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: c-ju

#6136 go mod conflict fix - API dependency fix
  api/go.mod
  api/go.sum
  api/types/access_request.go
  lib/services/access_request.go
Labels: bug

#6122 Profile credentials dialer fix
  api/client/client.go
  api/client/credentials.go
  api/client/credentials_test.go
Labels: bug

#5566 Added RFD for Cluster Routing.
  rfd/0021-cluster-routing.md
Labels: rfd

#6067 gRPC conversions - OIDCConnector
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/constants/constants.go
  api/types/oidc.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/services/access_request.go
  lib/services/oidc_test.go
  lib/services/types.go
Labels: documentation

#6137 Update application access docs forward-port
  docs/config.json
  docs/pages/application-access.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/api-access.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/jwt.mdx
  docs/pages/application-access/reference.mdx
Labels: application-access, documentation

#6190 GitLab Instructions for SSO
  docs/img/sso/gitlab/gitlab-oidc-0.png
  docs/img/sso/gitlab/gitlab-oidc-1.png
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/ssh-sso.mdx
Labels: documentation, sso

#6174 Fix uacc nil slice index bug and handle unexpected address formats correctly
  lib/srv/uacc/uacc_linux.go
  lib/srv/uacc/uacc_utils.go
Labels: backport-required, bug

#5938 Cache per-cluster SSH certificates under ~/.tsh
  api/client/profile.go
  integration/helpers.go
  integration/integration_test.go
  lib/client/api.go
  lib/client/api_test.go
  lib/client/client.go
  lib/client/identityfile/identity_test.go
  lib/client/interfaces.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/keystore.go
  lib/client/keystore_test.go
  lib/kube/kubeconfig/kubeconfig.go
  tool/tctl/common/tctl.go
  tool/tsh/access_request.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: documentation

#6158 Allow custom environment variables in PAM with SSO interpolation
  build.assets/pam/pam_teleport.c
  build.assets/pam/policy/teleport-custom-env
  constants.go
  docs/pages/features/ssh-pam.mdx
  docs/testplan.md
  integration/integration_test.go
  lib/config/fileconf.go
  lib/pam/config.go
  lib/srv/ctx.go
  lib/srv/reexec.go
Labels: PAM, backport-required, feature-request

#6208 mfa: fix gRPC unimplemented check in cert reissue
  lib/client/client.go
Labels: backport-required

#6169 Add `lint-api` target and fix lint errors
  Makefile
  api/client/client.go
  api/client/credentials_test.go
  api/types/access_request.go
Labels: release-engineering

#6231 Ensure webassets are present when running 'make full' on a fresh clone
  Makefile
Labels: backport-required, release-engineering

#6262 Forward-port "GitLab Instructions for SSO (#6190)"
  docs/img/sso/gitlab/gitlab-oidc-0.png
  docs/img/sso/gitlab/gitlab-oidc-1.png
  docs/pages/enterprise/sso/ssh-sso.mdx
Labels: documentation

#6197 dronegen: add buildboxes
  .drone.yml
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/main.go
  dronegen/push.go
  dronegen/tag.go
  dronegen/tests.go
Labels: release-engineering
