Repository gravitational/teleport, pull requests merged in 2021-01, with the labels that each got.

#5199 Added --with-secrets parameter to backup instructions in admin guide
  docs/4.2/admin-guide.md
  docs/4.3/admin-guide.md
  docs/4.4/admin-guide.md
  docs/5.0/admin-guide.md
Labels: documentation

#5222 Forward-port CHANGELOG for 5.1
  CHANGELOG.md
Labels: release-engineering

#5220 Update Makefile version on master branch
  Makefile
  version.go
Labels: release-engineering

#5215 Fix submodule cloning on Drone exec runners
  .drone.yml
Labels: backport-required, release-engineering

#5239 [4.3] Backport "Fix submodule cloning on Drone exec runners (#5215)"
  .drone.yml
Labels: release-engineering

#5238 [4.4] Backport "Fix submodule cloning on Drone exec runners (#5215)"
  .drone.yml
Labels: release-engineering

#5231 [auto] Update AMI IDs for 5.1.0
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#5233 Add teleport-kube-agent chart and remove unwanted charts
  .drone.yml
  examples/chart/index.html
  examples/chart/teleport-kube-agent/README.md
Labels: release-engineering

#5237 [5.0] Backport "Fix submodule cloning on Drone exec runners (#5215)"
  .drone.yml
Labels: release-engineering

#5221 Update versions built by docker-cron for 5.1
  .drone.yml
Labels: release-engineering

#5228 RFD 18: RFDs
  rfd/0000-rfds.md
  rfd/0001-testing-guidelines.md
  rfd/0002-streaming.md
  rfd/0003-extended-approval-workflows.md
  rfd/0005-kubernetes-service.md
  rfd/0007-rbac-oss.md
  rfd/0008-application-access.md
  rfd/0011-database-access.md
  rfd/0012-teleport-versioning.md
Labels: rfd

#5193 Add username in Okta SSO Docs config
  docs/5.0/enterprise/sso/ssh-okta.md
  docs/5.0/img/sso/okta/setup-redirection.png
Labels: documentation, sso

#5273 Added notes and corrected cat useradd command for pam docs
  docs/5.0/features/ssh-pam.md
Labels: documentation

#5283 Replace hardcoded instances of teleport with DRONE_REPO_NAME
  .drone.yml
Labels: release-engineering

#5292 Add Drone builds on push to branch
  .drone.yml
Labels: release-engineering

#5223 Address post-release checklist items for 5.1
  docker/teleport-ent-quickstart.yml
  docker/teleport-quickstart.yml
  docs/5.0.yaml
  examples/chart/teleport-auto-trustedcluster/Chart.yaml
  examples/chart/teleport-auto-trustedcluster/values.yaml
  examples/chart/teleport-daemonset/Chart.yaml
  examples/chart/teleport-daemonset/values.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/values.yaml
Labels: documentation

#5341 Update CentOS 6 buildboxes to use vault packages
  build.assets/Dockerfile
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
Labels: release-engineering

#5359 Rename database role to db
  lib/defaults/defaults.go
  roles.go
  tool/tctl/common/db_command.go
Labels: database-access

#5380 Fix tsh login issue
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/tsh.go
Labels: database-access

#5319 Refactor postgres service file handling, add db config command
  lib/client/db/postgres/servicefile.go
  lib/client/db/postgres/servicefile_test.go
  lib/client/db/profile.go
  lib/client/db/profile/profile.go
  tool/tsh/db.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: database-access

#5325 Refactor db proxy/engine for easier reuse
  lib/multiplexer/multiplexer.go
  lib/srv/db/audit.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/doc.go
  lib/srv/db/common/interfaces.go
  lib/srv/db/common/session.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
Labels: database-access

#5307 Add database access getting started guide
  docs/5.0/preview/database-access.md
  docs/5.0/preview/releases-table.md
Labels: database-access

#5348 Combined Helm chart for kube, app and db services
  docs/5.0/kubernetes-access.md
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, kubernetes

#5407 teleport-kube-agent: Check whether Teleport version is >=6 before setting db_service key
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
Labels: helm

#5408 teleport-helm-cron: Copy and index all previous Helm chart versions
  .drone.yml
Labels: helm, release-engineering

#5125 RFD 14: per-session 2FA
  rfd/0014-session-2FA.md
Labels: rfd

#5423 Release 5.1.1
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#5425 Backport: Update CentOS 6 buildboxes to use vault packages (#5341)
  build.assets/Dockerfile
  build.assets/Dockerfile-centos6
  build.assets/Dockerfile-centos6-fips
  build.assets/Dockerfile-fips
Labels: release-engineering

#5421 Refactor db access audit logger for better reuse
  lib/srv/db/common/audit.go
  lib/srv/db/common/session.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/server.go
  lib/srv/db/streamer.go
Labels: database-access

#5426 Release 5.1.2
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#5422 Allows specifying different public addresses for ssh, tunnel and k8s
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/templates/config.yaml
  examples/chart/teleport/values.yaml
Labels: examples, kubernetes

#5434 Add tctl users reset to cli docs
  docs/5.0/cli-docs.md
Labels: documentation
