Repository gravitational/teleport, pull requests merged in 2021-02, with the labels that each got.

#5227 Update RFD 12 with image tagging scheme
  rfd/0012-teleport-versioning.md
Labels: rfd

#5450 Add webhook to deploy docs on push
  .drone.yml
Labels: release-engineering

#5345 Test flakes: use fake clock to avoid time skews
  lib/events/auditlog_test.go
Labels: flaky tests

#5332 Test flakes: fix reported data races in lib/backend unit tests.
  lib/backend/etcdbk/etcd_test.go
  lib/backend/firestore/firestorebk_test.go
  lib/backend/lite/lite_test.go
  lib/backend/lite/litemem_test.go
  lib/backend/memory/memory_test.go
  lib/backend/test/suite.go
  lib/session/session_test.go
Labels: flaky tests

#4746 RFD 10: Proposes client and API refactoring
  rfd/0010-api.md
Labels: rfd

#5412 docs: Update BCC/BPF tools install instructions
  docs/5.0/features/enhanced-session-recording.md
Labels: documentation

#5370 Test flakes: use fake clock to avoid off by 1 error
  lib/auth/auth_test.go
  lib/auth/init_test.go
Labels: flaky tests

#5469 Various docs fixes
  docs/5.0/admin-guide.md
  docs/5.0/features/enhanced-session-recording.md
  docs/5.0/gcp-guide.md
  docs/5.0/ibm-cloud-guide.md
Labels: documentation

#5460 Backport "Add webhook to deploy docs on push (#5450)"
  .drone.yml
Labels: release-engineering

#5276 Web UI disconnects
  api/client/events.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/client/proto/proto.go
  api/client/sessions.go
  api/client/streamwatcher.go
  api/defaults/defaults.go
  api/types/constants.go
  api/types/events.go
  api/types/session.go
  api/types/types.pb.go
  api/types/types.proto
  constants.go
  lib/auth/api.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/github.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/oidc.go
  lib/auth/password.go
  lib/auth/permissions.go
  lib/auth/saml.go
  lib/auth/sessions.go
  lib/auth/tls_test.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/defaults/defaults.go
  lib/reversetunnel/srv.go
  lib/service/service.go
  lib/service/service_test.go
  lib/services/identity.go
  lib/services/local/events.go
  lib/services/local/session.go
  lib/services/local/users.go
  lib/services/resource.go
  lib/services/services.go
  lib/services/session.go
  lib/services/suite/suite.go
  lib/services/types.go
  lib/srv/heartbeat.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/apps.go
  lib/web/cookie.go
  lib/web/saml.go
  lib/web/sessions.go
  lib/web/static.go
  lib/web/static_test.go
  lib/web/terminal.go
Labels: backport-required

#5492 update enterprise quick start role example to 5.0 version
  docs/5.0/enterprise/quickstart-enterprise.md
Labels: documentation

#5494 New Teleport Demo Video
  docs/5.0/index.md
Labels: documentation

#5495 Add linting for Helm charts with example values
  Makefile
  build.assets/Dockerfile
  examples/chart/teleport-cluster/.lint/lint-values.yaml
  examples/chart/teleport-cluster/templates/psp.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-all-v5.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-all-v6.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-backwards-compatibility.yaml
  examples/chart/teleport-kube-agent/.lint/lint-values-db.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport/templates/service.yaml
  examples/chart/teleport/values.yaml
Labels: release-engineering

#5490 Add kubernetes_service option to teleport helm chart
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/templates/config.yaml
  examples/chart/teleport/values.yaml
Labels: examples, helm, kubernetes

#5452 Change to handle cert sync logic in AMIs when running in all-in-one mode
  assets/aws/files/bin/teleport-check-cert
Labels: terraform

#5135 RFD 15: 2FA device management
  rfd/0015-2fa-management.md
Labels: rfd

#5526 [4.4] Backport "Change to handle cert sync logic in AMIs when running in all-in-one mode (#5452)"
  assets/aws/files/bin/teleport-check-cert
Labels: release-engineering

#5479 [auto] Update AMI IDs for 5.1.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#5525 [5.0] Backport "Change to handle cert sync logic in AMIs when running in all-in-one mode (#5452)"
  assets/aws/files/bin/teleport-check-cert
Labels: release-engineering

#5528 [4.4] Backport 'Upgrade pip to fix installation issues in AMI (#5514)'
  assets/aws/files/bin/teleport-get-cert
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/install.sh
Labels: release-engineering

#5529 [5.0] Backport 'Upgrade pip to fix installation issues in AMI (#5514)'
  assets/aws/files/bin/teleport-get-cert
  assets/aws/files/bin/teleport-renew-cert
  assets/aws/files/install.sh
Labels: release-engineering

#5541 Fix typo in ssh-pam.md
  docs/5.0/pages/features/ssh-pam.md
Labels: documentation

#5547 Pull base buildbox to speed up ARM push builds
  .drone.yml
Labels: release-engineering

#5548 Drone tweaks to pull base buildboxes in more places to speed up ARM builds
  .drone.yml
Labels: release-engineering

#5472 Add mysql functional/integration tests
  api/types/databaseserver.go
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/helpers.go
  integration/integration_test.go
  integration/kube_integration_test.go
  lib/srv/db/common/test.go
  lib/srv/db/db_test.go
  lib/srv/db/mysql/test.go
  lib/srv/db/postgres/test.go
  lib/srv/db/server_test.go
Labels: database-access

#5491 Implement utmp/wtmp support
  .drone.yml
  Makefile
  build.assets/Makefile
  integration/integration_test.go
  integration/utmp_integration_test.go
  lib/srv/ctx.go
  lib/srv/exec_test.go
  lib/srv/forward/sshserver.go
  lib/srv/reexec.go
  lib/srv/regular/sshserver.go
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
  lib/srv/uacc/uacc_stub.go
  lib/srv/uacc/uacc_utils.go
Labels: R3, c-ju, c-pa

#5483 Add TELEPORT_CONFIG_FILE variable to disable reading Teleport config from disk
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  tool/tctl/common/tctl.go
Labels: tctl

#5589 Document supported storage backends
  docs/5.0/pages/admin-guide.md
Labels: documentation

#5555 Added recording type, session lockout and https key pair settings for teleport helm chart
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/templates/config.yaml
  examples/chart/teleport/values.yaml
Labels: examples, kubernetes

#5565 Relax app session cookie same-site policy
  lib/web/app/fragment.go
Labels: application-access, backport-required

#5614 Fix docs which are failing tests
  docs/5.0/pages/admin-guide.md
Labels: documentation

#5623 Add .mdx files to test skipping logic
  .drone.yml
Labels: documentation, release-engineering

#5618 Fix for HA auth configmap in teleport helm chart
  examples/chart/teleport/templates/config.yaml
Labels: examples, kubernetes

#5147 RFD 16: Dynamic Configuration
  rfd/0016-dynamic-configuration.md
Labels: rfd

#5545 Updated info and configuration for easier enterprise quick start doc
  docs/5.0/pages/enterprise/quickstart-enterprise.mdx
Labels: documentation, enterprise

#5633 Add Kubernetes listener to HA Terraform
  Makefile
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-ssm-publish-tokens
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/ha-autoscale-cluster/auth_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/node_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/proxy_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy_network.tf
  examples/aws/terraform/ha-autoscale-cluster/route53.tf
  examples/aws/terraform/ha-autoscale-cluster/vars.tf
Labels: terraform

#5689 Update CHANGELOG.md for 6.0.0-rc.1
  CHANGELOG.md
Labels: backport-required, documentation

#5693 utmp fix for symlinked paths
  integration/utmp_integration_test.go
  lib/srv/ctx.go
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
Labels: backport-required, bug, c-pa, c-pu, test-plan-problem

#5664 Add database access manual test plan
  docs/testplan.md
Labels: testplan

#5732 Backport #5693 to v6
  integration/utmp_integration_test.go
  lib/srv/ctx.go
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
Labels: test-plan-problem

#5734 Adds public_addr when using ACME
  lib/config/fileconf.go
Labels: backport-required, test-plan-problem

#5721 Update old proxy version
  lib/reversetunnel/srv.go
Labels: test-plan-problem

#5475 RFD 18: Agent loading.
  rfd/0018-agent-loading.md
Labels: rfd

#5692 Fixed a typo in GCP documentation
  docs/5.0/pages/gcp-guide.mdx
Labels: documentation

#5731 [tctl] Don't explicitly set value for config path and preserve backwards compatibility
  lib/config/configuration.go
  lib/service/service_test.go
  lib/utils/utils.go
  tool/tctl/common/tctl.go
Labels: backport-required, tctl, test-plan-problem

#5746 [branch/v6] Backport "[tctl] Don't explicitly set value for config path and preserve backwards compatibility (#5731)"
  lib/config/configuration.go
  lib/service/service_test.go
  lib/utils/utils.go
  tool/tctl/common/tctl.go
Labels: test-plan-problem

#5744 Correct label example and provide sample
  docs/pages/cli-docs.mdx
Labels: documentation

#5760 Release 5.2.1
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#5761 Adds docs-test-whitespace Makefile target needed for docs tests
  Makefile
Labels: release-engineering

#5766 Fix last output timestamps on some systems
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
Labels: test-plan-problem

#5767 Backport #5766 to v6
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
Labels: test-plan-problem
