Repository gravitational/teleport, pull requests merged in 2021-04, with the labels that each got.

#6251 Delete obsolete stored keys in LocalKeyAgent.AddKey
  lib/client/keyagent.go
Labels: backport-required

#6257 tsh: handle missing cluster name in profile
  api/client/profile.go
  api/client/profile_test.go
  lib/client/api.go
  tool/tsh/tsh.go
Labels: backport-required

#6297 Close leaky directClient
  lib/service/connect.go
Labels: backport-required

#6258 Remove unused * from Roles output in tsh
  tool/tsh/tsh.go
Labels: tsh

#6256 Handle LXC container edge cases in uacc code
  lib/srv/reexec.go
  lib/srv/uacc/uacc.h
  lib/srv/uacc/uacc_linux.go
Labels: backport-required, bug, c-rs

#6260 Backport branch/v6: Removed * from roles output in tsh
  tool/tsh/tsh.go
Labels: tsh

#6283 [auto] Update AMI IDs for 6.0.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, terraform

#6304 Propogate user not found error from authenticater.
  lib/auth/grpcserver.go
Labels: backport-required

#6326 Set AuditLog to discard instead of nil in file session implementation
  lib/events/filesessions/fileasync.go
Labels: backport-required, c-cr

#6336 tctl profile loading fix
  tool/tctl/common/tctl.go
Labels: backport-required, c-cr

#6301 Add DialOpts and CallOpts to API client.
  api/client/auditstreamer.go
  api/client/client.go
  api/client/keepaliver.go
  api/client/sessions.go
  api/client/streamwatcher.go
Labels: backport-required

#6330 helm: Improve linting and add log level override
  Makefile
  build.assets/Dockerfile
  examples/chart/teleport-cluster/.lint/lint-acme.yaml
  examples/chart/teleport-cluster/.lint/lint-no-acme.yaml
  examples/chart/teleport-cluster/.lint/lint-versionoverride.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/psp.yaml
  examples/chart/teleport-cluster/templates/pvc.yaml
  examples/chart/teleport-cluster/templates/service.yaml
  examples/chart/teleport-cluster/values.yaml
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, release-engineering

#6285 docs: document per-session MFA feature
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/access-controls/introduction.mdx
  docs/pages/admin-guide.mdx
  docs/pages/config-reference.mdx
Labels: backport-required, documentation

#6358 Modify RFD 18 and set status to implemented
  rfd/0018-agent-loading.md
Labels: rfd

#6417 Forward-port 6.1.1 CHANGELOG
  CHANGELOG.md
Labels: release-engineering

#6359 RFD 24: DynamoDB Audit Event Overflow Handling
  rfd/0024-dynamo-event-overflow.md
Labels: rfd

#6416 Release 6.1.1
  CHANGELOG.md
  Makefile
  version.go
Labels: release-engineering

#6427 Update docs on oidc prompt logic for 6.1+.
  api/types/oidc.go
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/oidc.mdx
Labels: backport-required, documentation

#5071 RFD 26 - Custom Approval Conditions
  rfd/0026-custom-approval-conditions.md
Labels: rfd

#5621 Added reverse tunnel port info to teleport-kube-agent readme
  examples/chart/teleport-kube-agent/README.md
Labels: examples, kubernetes

#6415 correct Teleport version in access control examples
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/application-access/guides/jwt.mdx
Labels: documentation

#6303 Capture postgres extended protocol queries in audit log
  api/constants/constants.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/utils/sshutils/chconn.go
  constants.go
  lib/events/api.go
  lib/events/filesessions/filestream.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/common/session.go
  lib/srv/db/common/statements.go
  lib/srv/db/common/statements_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
Labels: backport-required, database-access

#6420 Moves license_file to the correct section and adds unit test
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/tests/starter-cluster-acm-fips.bats
  assets/aws/files/tests/starter-cluster-acm.bats
  assets/aws/files/tests/starter-cluster-fips.bats
  assets/aws/files/tests/starter-cluster.bats
Labels: release-engineering

#6275 Phrase review the main README.md file
  README.md
Labels: documentation

#6300 [branch/v6.0] Update getting started for cloud
  docs/img/cloud/addserver-2.png
  docs/img/cloud/completed-script-4.png
  docs/img/cloud/homepage-1.png
  docs/img/cloud/online-session-5.png
  docs/img/cloud/runscript-3.png
  docs/pages/cloud/faq.mdx
  docs/pages/cloud/getting-started.mdx
Labels: cloud, documentation

#6453 (6.2) Capture postgres extended protocol messages in audit log
  api/constants/constants.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/utils/sshutils/chconn.go
  constants.go
  lib/events/api.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/common/session.go
  lib/srv/db/common/statements.go
  lib/srv/db/common/statements_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
Labels: database-access

#6387 RFD 25: Hardware security module (HSM) support
  rfd/0025-hsm.md
Labels: rfd

#6468 RFD 0: elaborate the deprecated state
  rfd/0000-rfds.md
Labels: rfd

#6282 Update region list for AWS AMI publishing
  assets/aws/Makefile
  assets/aws/README.md
Labels: release-engineering

#6168 RFD-0022: Key Agent Forwarding
  rfd/0022-ssh-agent-forwarding.md
Labels: rfd

#5342 Test flakes: terminate key agent consistently between tests
  lib/client/keyagent_test.go
  lib/utils/errors.go
Labels: flaky tests

#6388 Refactor api package to improve pkg.go.dev experience.
  api/client/README.md
  api/client/client.go
  api/client/contextdialer.go
  api/client/credentials.go
  api/client/credentials_test.go
  api/client/doc.go
  api/client/doc_test.go
  api/client/events.go
  api/client/streamwatcher.go
  api/client/webclient/webclient.go
  api/identityfile/identityfile.go
  api/identityfile/identityfile_test.go
  api/profile/profile.go
  api/profile/profile_test.go
  api/utils/delegator.go
  docs/config.json
  docs/pages/api-reference.mdx
  docs/pages/application-access/guides/api-access.mdx
  docs/pages/kubernetes-access/guides/cicd.mdx
  docs/pages/reference/api.mdx
  docs/pages/reference/api/architecture.mdx
  docs/pages/reference/api/getting-started.mdx
  docs/pages/reference/api/introduction.mdx
  examples/go-client/.gitignore
  examples/go-client/README.md
  integration/integration_test.go
  lib/auth/auth.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/permissions.go
  lib/benchmark/benchmark.go
  lib/client/api.go
  lib/client/identityfile/identity.go
  lib/client/interfaces.go
  lib/client/keystore.go
  lib/service/connect.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  tool/tctl/common/tctl.go
  tool/tsh/tsh_test.go
Labels: backport-required

#6464 Missing $ in kube agent install example for variable
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
Labels: documentation, kubernetes

#6526 [v6.1] correct reference to slack dir in plugin source instrs
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
Labels: documentation

#6528 [v6.2] correct reference to slack dir in plugin source instrs
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
Labels: documentation

#6527 [v7] correct reference to slack dir in plugin source instrs
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
Labels: documentation

#6520 Enforce strict teleport.yaml validation
  lib/config/fileconf.go
  tool/teleport/common/teleport.go
Labels: ux

#6543 docs: fix typos in sample roles in MFA guide
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: backport-required, documentation

#6426 Add postgres_public_addr and mysql_public_addr
  api/client/webclient/webclient.go
  api/profile/profile.go
  lib/client/api.go
  lib/client/api_test.go
  lib/client/db/profile.go
  lib/client/db/profile_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
  tool/tsh/db.go
Labels: backport-required, database-access

#6544 [v6.1] Editorial Pass/Review - Home
  CHANGELOG.md
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/admin-guide.mdx
  docs/pages/adopters.mdx
  docs/pages/faq.mdx
  docs/pages/getting-started.mdx
  docs/pages/index.mdx
  docs/pages/installation.mdx
  docs/pages/production.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#6562 Backport v6: docs: fix typos in sample roles in MFA guide
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation

#6555 Update Go version requirement in README
  README.md
Labels: documentation

#6564 [v7.0] Backport of editorial changes from v6.1
  CHANGELOG.md
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/faq.mdx
  docs/pages/getting-started.mdx
  docs/pages/index.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/federation.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#6563 Backport v6.1: docs: fix typos in sample roles in MFA guide
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation

#6546 (6.2) Adding postgres_public_addr and mysql_public_addr
  api/client/webclient/webclient.go
  api/profile/profile.go
  lib/client/api.go
  lib/client/api_test.go
  lib/client/db/profile.go
  lib/client/db/profile_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
  tool/tsh/db.go
Labels: database-access

#6569 [v6.2] edit pass - app + kub access
  CHANGELOG.md
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/faq.mdx
  docs/pages/index.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/federation.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#6568 [v6.1] edit pass - app + kub access
  CHANGELOG.md
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/faq.mdx
  docs/pages/index.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/federation.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#6571 [v6.1] Merge style guide into docs
  docs/pages/docs.mdx
  docs/pages/docs/best-practices.mdx
Labels: documentation

#6343 Improve error message for timeout errors
  lib/httplib/httplib.go
Labels: ux

#6479 Add support for Redshift IAM authentication
  api/types/databaseserver.go
  api/types/types.pb.go
  api/types/types.proto
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/services/databaseserver.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/aws.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/test.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
  lib/srv/db/server.go
  lib/srv/db/server_test.go
  tool/tsh/tsh.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/api.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/doc.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/errors.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/service.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/waiters.go
  vendor/modules.txt
Labels: backport-required, database-access

#6580 [v6.2] update changes from v6.1
  CHANGELOG.md
Labels: documentation

#6577 [v7.0] Merge style guide into docs
  docs/pages/docs.mdx
  docs/pages/docs/best-practices.mdx
Labels: documentation

#6576 [v6.2] Merge style guide into docs
  docs/pages/docs.mdx
  docs/pages/docs/best-practices.mdx
Labels: documentation

#5762 Update descriptions for labels and diag-addr parameters for Teleport
  tool/teleport/common/teleport.go
  tool/teleport/common/usage.go
Labels: cli, ux

#6596 (6.2) Adding redshift support
  api/types/databaseserver.go
  api/types/types.pb.go
  api/types/types.proto
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/services/databaseserver.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/aws.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/test.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
  lib/srv/db/server.go
  lib/srv/db/server_test.go
  tool/tsh/tsh.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/api.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/doc.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/errors.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/service.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/waiters.go
  vendor/modules.txt
Labels: database-access

#6463 RFD 16: Specify RBAC verbs needed for the tctl operations
  rfd/0016-dynamic-configuration.md
Labels: rfd, ux

#5818 Handle `tctl get`'s input ref more strictly
  api/types/trust.go
  lib/services/resource.go
  tool/tctl/common/resource_command.go
Labels: ux

#6608 Fix test requiring gcp credentials
  lib/srv/db/access_test.go
  lib/srv/db/server.go
Labels: backport-required

#6567 mfa: better OTP registration flow on CLI
  api/types/authentication.go
  lib/auth/resetpasswordtoken.go
  tool/tsh/mfa.go
Labels: backport-required, mfa, ux

#6620 [v6.1] access requests from workflows
  docs/config.json
  docs/pages/access-controls/reference.mdx
  docs/pages/api-reference.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/docs.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation

#6585 mfa: prevent the user from deleting the last MFA device
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
Labels: backport-required

#6629 [v7.0] reword docs [fwdport]
  docs/pages/admin-guide.mdx
  docs/pages/architecture/nodes.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/ibm-cloud-guide.mdx
  docs/pages/production.mdx
  docs/pages/trustedclusters.mdx
Labels: documentation

#6627 [v.6.1] reword docs
  docs/pages/admin-guide.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/ibm-cloud-guide.mdx
  docs/pages/trustedclusters.mdx
Labels: documentation

#6628 [v.6.2] reword docs [fwdport]
  docs/pages/admin-guide.mdx
  docs/pages/architecture/nodes.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/ibm-cloud-guide.mdx
  docs/pages/production.mdx
  docs/pages/trustedclusters.mdx
Labels: documentation

#5505 Teleport opt-in adoption survey
  build.assets/install
Labels: blocker, documentation

#6599 [v6] Add `tctl create cap` for dynamically configuring cluster auth preference
  api/types/authentication.go
  api/types/constants.go
  api/types/resource.go
  lib/auth/apiserver.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/services/suite/suite.go
  rfd/0016-dynamic-configuration.md
  tool/tctl/common/resource_command.go
Labels: backport

#6540 Propagate external traits to leaf clusters
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/integration_test.go
  integration/kube_integration_test.go
  lib/auth/permissions.go
  lib/services/role.go
  lib/srv/authhandlers.go
Labels: backport-required

#6639 [Backport v6] Add ability to switchback to default roles/expiry
  api/types/session.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/github.go
  lib/auth/methods.go
  lib/auth/oidc.go
  lib/auth/saml.go
  lib/auth/sessions.go
  lib/auth/tls_test.go
  lib/services/session.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
Labels: backport

#5677 k8s: add merge-kubeconfigs.sh script
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  examples/k8s-auth/.gitignore
  examples/k8s-auth/README.md
  examples/k8s-auth/get-kubeconfig.sh
  examples/k8s-auth/merge-kubeconfigs.sh
Labels: documentation

#6542 mfa: cancel TOTP prompt if U2F was used
  lib/client/identityfile/identity.go
  lib/client/keyagent.go
  lib/client/mfa.go
  lib/utils/prompt/confirmation.go
  lib/utils/prompt/stdin.go
  lib/utils/prompt/stdin_test.go
  tool/tsh/mfa.go
Labels: backport-required

#6640 [v6] Handle `tctl get`'s input ref more strictly
  api/types/trust.go
  lib/services/resource.go
  tool/tctl/common/resource_command.go
Labels: backport

#6652 docs: bump 6.2 release date to May 21st
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, launch

#6626 docs: add a version disclaimer to per-session MFA guide
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation

#6519 kube: handle large number of trusted clusters in mTLS handshake
  lib/auth/auth.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
Labels: backport-required

#6594 Proxy line support for mysql
  lib/multiplexer/multiplexer.go
  lib/multiplexer/testproxy.go
  lib/multiplexer/wrappers.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/proxy_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server_test.go
  lib/utils/errors.go
Labels: backport-required, database-access

#6674 (6.2) Proxy line support for mysql
  lib/multiplexer/multiplexer.go
  lib/multiplexer/testproxy.go
  lib/multiplexer/wrappers.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/proxy_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server_test.go
  lib/utils/errors.go
Labels: backport

#6473 Draft account lifecycle
  rfd/0029-account-lifecycle.md
Labels: rfd

#6618 [v7.0] docs: correct tables [fwdport]
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/features/enhanced-session-recording.mdx
Labels: bug, documentation

#6623 [v6.2] access requests from workflows [fwdport]
  docs/config.json
  docs/pages/access-controls/reference.mdx
  docs/pages/architecture/users.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/docs.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/quickstart-enterprise.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/quickstart-docker.mdx
Labels: documentation

#6617 [v6.2] docs: correct tables [fwdport]
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/features/enhanced-session-recording.mdx
Labels: bug, documentation

#6616 Correct Helm Chart
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
Labels: documentation

#6649 (6.2) Propagate external traits to leaf clusters
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/integration_test.go
  integration/kube_integration_test.go
  lib/auth/permissions.go
  lib/services/role.go
  lib/srv/authhandlers.go
Labels: backport

#6624 [v7.0] access requests from workflows [fwdport]
  docs/config.json
  docs/pages/access-controls/reference.mdx
  docs/pages/architecture/users.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/docs.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/quickstart-enterprise.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/quickstart-docker.mdx
Labels: documentation

#6676 (6.1) Proxy line support for mysql
  lib/multiplexer/multiplexer.go
  lib/multiplexer/testproxy.go
  lib/multiplexer/wrappers.go
  lib/srv/db/access_test.go
  lib/srv/db/db_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/proxy_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server_test.go
  lib/utils/errors.go
Labels: backport, database-access
