Repository gravitational/teleport, pull requests merged in 2021-07, with the labels that each got.

#7393 [v7.0] docs: readme fixes
  README.md
Labels: documentation

#7373 [v7.0] docs: port of edit pass 6/9
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/cli-docs.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/ssh-kubernetes-fedramp.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/ssh-sso.mdx
  docs/pages/faq.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
Labels: backport, documentation

#7394 [v7.0] docs: update steps 2
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/setup/guides/terraform-provider.mdx
Labels: backport, documentation

#7399 [v7.0] docs: port of 7321
  docs/pages/config-reference.mdx
  lib/config/fileconf.go
Labels: backport, documentation

#7401 [v7.0] docs: port of edit pass 7/9
  docs/config.json
  docs/pages/aws-terraform-guide.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/kubernetes-access/guides/cicd.mdx
  docs/pages/kubernetes-access/guides/federation.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/kubernetes-access/helm/guides/migration.mdx
  docs/pages/kubernetes-access/helm/includes/helm-install.mdx
  docs/pages/kubernetes-access/helm/includes/kubernetes-externaladdress.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: backport, documentation

#7415 Paginated rpcs - Replace GetNodes with ListNodes
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/defaults/defaults.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/backend/backend.go
  lib/cache/cache.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
Labels: P0, backport-required, bug, regression

#7428 Docs 6.2 - Video guide for server access
  docs/pages/server-access/getting-started.mdx
Labels: documentation

#7007 [v6.2] Edit Pass #8
  docs/config.json
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/cli-docs.mdx
  docs/pages/cloud/architecture.mdx
  docs/pages/cloud/faq.mdx
  docs/pages/database-access/architecture.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/guides/gui-clients.mdx
  docs/pages/database-access/guides/mysql-aws.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-aws.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/database-access/reference.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/enterprise/sso/ssh-google-workspace.mdx
  docs/pages/includes/soc2.mdx
  docs/pages/index.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/kubernetes-access/helm/guides.mdx
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/kubernetes-access/helm/guides/migration.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
  docs/pages/preview/upcoming-releases.mdx
  docs/pages/pro/architecture.mdx
  docs/pages/pro/faq.mdx
  docs/pages/pro/getting-started.mdx
  docs/pages/pro/introduction.mdx
  docs/pages/setup/guides.mdx
Labels: backport-required, documentation

#6843 Update admin-guide.mdx
  docs/pages/admin-guide.mdx
Labels: documentation

#7232 [branch/v6.2] docs: Update teleport chart reference to teleport-cluster
  docs/pages/installation.mdx
  examples/chart/teleport-auto-trustedcluster/README.md
  examples/chart/teleport-cluster/README.md
  examples/chart/teleport-daemonset/README.md
  examples/chart/teleport/README.md
Labels: backport-required, documentation

#7018 [v6.2] Edit Pass #9
  docs/config.json
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/architecture/authentication.mdx
  docs/pages/architecture/overview.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/architecture/users.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/aws-terraform-guide.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/quickstart-enterprise.mdx
  docs/pages/enterprise/ssh-kubernetes-fedramp.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/ssh-adfs.mdx
  docs/pages/enterprise/sso/ssh-azuread.mdx
  docs/pages/enterprise/sso/ssh-google-workspace.mdx
  docs/pages/enterprise/sso/ssh-okta.mdx
  docs/pages/enterprise/sso/ssh-one-login.mdx
  docs/pages/enterprise/sso/ssh-sso.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/faq.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/ibm-cloud-guide.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/pro/introduction.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: backport-required, documentation

#7447 integration: Add teletest namespace and instructions for Kubernetes tests
  fixtures/ci-teleport-rbac/README.md
  fixtures/ci-teleport-rbac/ci-teleport.yaml
Labels: release-engineering

#7287 allow overrides of the AWS config for the service in the helm chart
  examples/chart/teleport-cluster/templates/service.yaml
Labels: helm

#7541 [v6.2] docs: Add CertificateFile to OpenSSH user manual
  docs/pages/user-manual.mdx
Labels: documentation

#7552 docker: Add libelf1 as a dependency for building Teleport container images
  build.assets/Dockerfile-cron
  build.assets/charts/Dockerfile
  build.assets/charts/Dockerfile-fips
Labels: release-engineering

#6769 Address security design review.
  rfd/0029-account-lifecycle.md
Labels: rfd

#6469 RFD 27: mtls metrics
  rfd/0027-mtls-metrics.md
Labels: rfd

#7575 Include O in MongoDB certs and improve some errors
  lib/reversetunnel/localsite.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
Labels: database-access, ux

#7616 (v7) Fix web listener
  lib/multiplexer/multiplexer_test.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/service/service.go
  lib/srv/db/access_test.go
  lib/srv/db/proxy_test.go
  lib/tlsca/parsegen.go
Labels: blocker, regression, test-plan-problem

#7648 [Backport v6] Removes double quotes from acme examples in docs
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/config-reference.mdx
Labels: backport, documentation

#7650 [backport v6.2] Removes double quotes from acme examples in docs
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/config-reference.mdx
Labels: backport, documentation

#7642 Removes double quotes from acme examples in docs
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/config-reference.mdx
Labels: backport-required, documentation

#7658 Add MongoDB Compass GUI client guide
  docs/img/database-access/compass-hostname@2x.png
  docs/img/database-access/compass-more-options@2x.png
  docs/img/database-access/compass-new-connection@2x.png
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation

#7590 AWS console access
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/constants/constants.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/role.go
  api/types/server.go
  api/types/session.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/app/cloud.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
  lib/srv/app/session.go
  lib/srv/app/transport.go
  lib/tlsca/ca.go
  lib/utils/aws.go
  lib/utils/aws_test.go
  lib/web/app/fragment.go
  lib/web/app/middleware.go
  lib/web/apps.go
  lib/web/sessions.go
  lib/web/ui/app.go
Labels: application-access

#7640 Add AWS console guide
  docs/config.json
  docs/img/application-access/aws-trusted-entities@2x.png
  docs/img/application-access/cloud-trail.png
  docs/img/application-access/federated-login@2x.png
  docs/img/application-access/iam-role-selector.png
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/application-access/introduction.mdx
Labels: documentation

#7692 docker: Automatically build teleport-lab image nightly based on latest Teleport version
  .drone.yml
  docker/sshd/Dockerfile
  docker/teleport-lab.yml
  docs/postrelease.md
Labels: release-engineering

#7666 [branch/v6.2] aws: Add s3:ListBucketMultipartUploads permissions to IAM policies
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
Labels: documentation, release-engineering

#7664 aws: Add s3:ListBucketMultipartUploads permissions to IAM policies
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
Labels: documentation, release-engineering

#7676 [branch/v7] aws: Add s3:ListBucketMultipartUploads permissions to IAM policies
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
Labels: documentation, release-engineering

#7706 Mark RFD 28 (ClusterConfig reorg) as implemented
  rfd/0028-cluster-config-resources.md
Labels: rfd

#7645 ImplicitRole doesn't have wildcard labels
  lib/auth/auth_with_roles_test.go
  lib/services/role.go
Labels: backport-required, bug

#6328 Updated 4.4 CODEOWNERS.
  .github/CODEOWNERS
Labels: documentation

#6418 clarity around ansible config for teleport
  docs/pages/admin-guide.mdx
Labels: documentation

#7570 Fix helm scripts of agent application labels
  docs/pages/kubernetes-access/helm/reference.mdx
Labels: helm

#7720 [Backport v7] Update the GCP+GKE+Helm guide
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
Labels: documentation

#7166 Mount teleport-tls to the init container for the teleport-cluster helm chart
  examples/chart/teleport-cluster/templates/deployment.yaml
Labels: helm

#7286 RFD 9: Locking
  rfd/0009-locking.md
Labels: rfd

#7672 [Backport v7] Update DNS instructions in the AWS+EKS+Helm guide
  docs/pages/kubernetes-access/helm/guides/aws.mdx
Labels: documentation

#7719 Update PAM page
  docs/img/motd/teleport-no-MOTD.png
  docs/img/motd/teleport-with-MOTD.png
  docs/img/motd/teleport-with-updated-MOTD.png
  docs/pages/server-access/guides/ssh-pam.mdx
Labels: documentation

#7715 be more explicit about non-root user
  docs/pages/includes/permission-warning.mdx
Labels: c-ib, documentation

#7673 Add Restricted Session docs
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/restricted-session.mdx
Labels: documentation

#7503 Reference docs for AuthPreference
  docs/pages/setup/reference/terraform-provider.mdx
Labels: documentation

#7671 Update Okta and SSO screenshots
  docs/config.json
  docs/img/gsuite/gsuite-5-copy-client-id.png
  docs/img/gsuite/gsuite-5f-download-json.png
  docs/img/gsuite/pngout.png
  docs/img/sso/okta/obtain-okta-xml.png
  docs/img/sso/okta/okta-saml-0.png
  docs/img/sso/okta/okta-saml-1.png
  docs/img/sso/okta/okta-saml-2.png
  docs/img/sso/okta/okta-saml-3.1.png
  docs/img/sso/okta/okta-saml-5.png
  docs/img/sso/okta/setup-redirection.png
  docs/img/sso/okta/switch-to-classic.gif
  docs/pages/access-controls/getting-started.mdx
  docs/pages/admin-guide.mdx
  docs/pages/application-access/controls.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/enterprise/fedramp.mdx
  docs/pages/enterprise/getting-started.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/adfs.mdx
  docs/pages/enterprise/sso/azuread.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
  docs/pages/faq.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
  docs/pages/setup/deployments/gcp.mdx
Labels: documentation
