Repository gravitational/teleport, pull requests merged in 2021-09, with the labels that each got.

#7957 Dynamically register/unregister databases
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/client/streamwatcher.go
  api/types/database.go
  api/types/databaseserver.go
  api/types/databaseserver_test.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  api/types/types.pb.go
  api/types/types.proto
  integration/db_integration_test.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/client/api.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/reversetunnel/srv.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/service/service.go
  lib/services/database.go
  lib/services/local/events.go
  lib/services/role.go
  lib/services/selector.go
  lib/services/selector_test.go
  lib/services/server.go
  lib/services/watcher.go
  lib/services/watcher_test.go
  lib/srv/db/access_test.go
  lib/srv/db/ca_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/common/session.go
  lib/srv/db/ha_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
  lib/srv/db/server_test.go
  lib/srv/db/streamer.go
  lib/srv/db/watcher.go
  lib/srv/db/watcher_test.go
  lib/web/servers.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command_test.go
  tool/tsh/tsh.go
Labels: database-access

#8128 [v7] Correctly validate JWT CA on bootstrap
  lib/auth/init.go
  lib/auth/init_test.go
Labels: backport

#8168 correct port number example for gcp cloud mysql
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, backport-required, database-access

#8140 Add app server and app resources
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/client/streamwatcher.go
  api/types/app.go
  api/types/appserver.go
  api/types/constants.go
  api/types/events.go
  api/types/server.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/api.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/client/api.go
  lib/client/client.go
  lib/service/acme.go
  lib/service/service.go
  lib/services/app.go
  lib/services/app_test.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
  lib/services/role.go
  lib/services/role_test.go
  lib/services/server.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
  lib/srv/app/session.go
  lib/srv/db/server.go
  lib/srv/heartbeat.go
  lib/srv/heartbeat_test.go
  lib/web/apiserver_test.go
  lib/web/app/match.go
  lib/web/app/session.go
  lib/web/app/transport.go
  lib/web/apps.go
  lib/web/ui/app.go
  tool/tctl/common/app_command.go
  tool/tctl/common/collection.go
  tool/tsh/app.go
  tool/tsh/tsh.go
Labels: application-access

#8127 Expanded AWS Console examples
  docs/img/application-access/attach-security-role.png
  docs/img/application-access/create-role-example-readonly-1.png
  docs/img/application-access/create-role-example-readonly-2.png
  docs/img/application-access/create-role-example-readonly-3.png
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
Labels: documentation, ux, aws, backport-required

#8093 Expand error message on tctl for enterprise version needed
  tool/tctl/common/resource_command.go
Labels: ux, backport-required

#8199 Auth server examples change to single address
  docs/pages/admin-guide.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport-required

#8188 Correct License file name in K8s Cluster Getting started
  docs/pages/kubernetes-access/getting-started/cluster.mdx
Labels: documentation, kubernetes

#7950 Db access gui client improvements
  docs/config.json
  docs/img/database-access/dbeaver-add-server.png
  docs/img/database-access/dbeaver-configure-server.png
  docs/img/database-access/dbeaver-configure-user.png
  docs/img/database-access/dbeaver-driver-settings.png
  docs/img/database-access/dbeaver-select-driver.png
  docs/img/database-access/dbeaver-ssl.png
  docs/img/database-access/dbeaver-tls-settings.png
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation

#8130 New video banners for BPF work
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/restricted-session.mdx
Labels: documentation

#8129 Update the index.mdx file for Access Controls
  docs/pages/enterprise/workflow/index.mdx
Labels: documentation, ux

#7788 SOC2 Doc Update
  docs/config.json
  docs/pages/enterprise/soc2.mdx
  docs/pages/setup/guides.mdx
  docs/pages/setup/guides/ec2-tags.mdx
Labels: documentation

#7280 RFD 39: SNI and ALPN telepot proxy routing
  rfd/0039-sni-alpn-teleport-proxy-routing.md
Labels: rfd

#8181 [firestore] Ensure descending index is always created
  api/go.mod
  go.mod
  go.sum
  lib/backend/firestore/firestorebk.go
  lib/events/firestoreevents/firestoreevents.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
  vendor/golang.org/x/tools/go/analysis/passes/inspect/inspect.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/internal/cgo/cgo.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface10.go
  vendor/golang.org/x/tools/go/internal/gcimporter/newInterface11.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/loader/loader.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_fileno.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_ino.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_bsd.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_linux.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode_string.go
  vendor/modules.txt
Labels: backport-required, gcp

#8234 [5.0] Rotate Mac signing certificates
  build.assets/build-package.sh
Labels: mac, release-engineering, backport

#8230 Rotate Mac signing certificates
  build.assets/build-package.sh
Labels: mac, release-engineering

#8242 correct role mapping in gitlab docs
  docs/pages/enterprise/sso/gitlab.mdx
Labels: documentation, sso, backport-required

#8220 Add documentation for the nowait flag.
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/setup/reference/cli.mdx
Labels: documentation

#8225 (v7) Support custom paths for AWS roles in console access
  lib/utils/aws.go
  lib/utils/aws_test.go
Labels: application-access

#8085 [branch/v7] helm: Set correct fsGroup in teleport-kube-agent chart when using persistent storage (#7804)
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
Labels: helm

#8233 [v6.2] Rotate Mac signing certificates
  build.assets/build-package.sh
Labels: mac, release-engineering, backport

#8235 [4.4] Rotate Mac signing certificates
  build.assets/build-package.sh
Labels: mac, release-engineering, backport

#8224 Support custom paths for AWS roles in console access
  lib/utils/aws.go
  lib/utils/aws_test.go
Labels: application-access

#8198 [backport branch/v7] Expanded AWS Console examples
  docs/img/application-access/attach-security-role.png
  docs/img/application-access/create-role-example-readonly-1.png
  docs/img/application-access/create-role-example-readonly-2.png
  docs/img/application-access/create-role-example-readonly-3.png
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation, application-access, backport

#8196 [backport v7] Expand error message on tctl for enterprise version needed
  tool/tctl/common/resource_command.go
Labels: backport

#8183 Add mysql port to config and service in Teleport Cluster Helm Chart
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/service.yaml
Labels: helm, backport-required, database-access

#8169 [backport branch v7] correct port number example for gcp cloud mysql
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, database-access, backport

#8280 Update role-templates.mdx
  docs/pages/access-controls/guides/role-templates.mdx
Labels: documentation

#7292 RFD 41: Simplified Node Joining for AWS
  rfd/0041-aws-node-join.md
Labels: rfd

#8277 [branch/v7] Add mysql port to config and service in Teleport Cluster Helm Chart
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/service.yaml
Labels: helm, database-access, backport, db/mysql

#8241 Improve performance, reliability of firestore backend
  lib/backend/firestore/firestorebk.go
  lib/events/firestoreevents/firestoreevents.go
Labels: gcp

#8083 ignore concurrent updates during tc load
  lib/auth/trustedcluster.go
Labels: c-q7j

#8185 Add API and CLI for managing application resources
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/client/streamwatcher.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/init.go
  lib/auth/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/service/service.go
  lib/services/app.go
  lib/services/local/apps.go
  lib/services/local/apps_test.go
  lib/services/local/events.go
  lib/services/resource.go
  lib/services/role.go
  lib/services/services.go
  tool/tctl/common/app_command.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: application-access

#8327 [auto] Update AMI IDs for 7.1.3
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#8319 Allow login over plain http in restricted situations (#7835)
  api/client/webclient/webclient.go
  api/client/webclient/webclient_test.go
  api/utils/addr.go
  api/utils/addr_test.go
  lib/client/api.go
  lib/client/https_client.go
  lib/client/weblogin.go
  lib/client/weblogin_test.go
  lib/utils/addr.go
  lib/utils/addr_test.go
Labels: backport

#8359 (buddy) Set flush interval when forwarding application http requests
  integration/app_integration_test.go
  lib/srv/app/session.go
  lib/web/app/session.go
Labels: backport-required, application-access

#8412 [auto] Update AMI IDs for 7.2.0
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#8422 correct app name example
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport-required, application-access

#8423 [branch/v7] correct app name example
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, application-access, backport

#8436 Update U2F App ID guidance in documentation (#8434)
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/cloud/guides/u2f.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/reference/authentication.mdx
  docs/pages/setup/reference/config.mdx
  docs/pages/setup/reference/terraform-provider.mdx
Labels: backport
