Repository gravitational/teleport, pull requests merged in 2021-12, with the labels that each got.

#9001 docs: Fixes for pam_exec user creation script
  docs/pages/server-access/guides/ssh-pam.mdx
Labels: documentation, PAM

#9054 [branch/v7] [pr-buddy-8414] Add priority class name
  docs/pages/kubernetes-access/helm/reference.mdx
  examples/chart/teleport-cluster/.lint/priority-class-name.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: helm

#9152 Enhance LDAP desktop discovery
  api/types/desktop.go
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/reference.mdx
  lib/config/configuration.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/services/reconciler.go
  lib/services/reconciler_test.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/ldap.go
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
Labels: documentation, backport-required, desktop-access

#9098 simplify connection establishment
  lib/backend/backend.go
  lib/web/apiserver.go
  lib/web/desktop.go
Labels: backport-required, desktop-access

#9081 Do not prompt for hardware MFA using `tsh` on Windows
  lib/auth/webauthncli/platform_other.go
  lib/auth/webauthncli/platform_windows.go
  lib/client/mfa.go
Labels: backport-required

#9198 Do not prompt for hardware MFA using `tsh` on Windows (#9081)
  lib/auth/webauthncli/platform_other.go
  lib/auth/webauthncli/platform_windows.go
  lib/client/mfa.go
Labels: backport

#9249 [v8] Fix tsh ssh proxy for OpenSSH client
  lib/srv/alpnproxy/local_proxy.go
  tool/tsh/config.go
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
Labels: backport

#9100 simplify desktop access getting started guide
  docs/img/desktop-access/apply-gpo.png
  docs/img/desktop-access/ca.png
  docs/img/desktop-access/create-and-link-gpo.png
  docs/img/desktop-access/deny-interactive-login.png
  docs/img/desktop-access/disable.png
  docs/img/desktop-access/firewall.png
  docs/img/desktop-access/rdp.png
  docs/img/desktop-access/remove-authenticated.png
  docs/img/desktop-access/smartcard.png
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/troubleshooting.mdx
  lib/srv/desktop/README.md
Labels: documentation, backport-required, desktop-access

#9275 [v6.2] Trigger Assign workflow on opened and ready_for_review events.
  .github/workflows/assign.yaml
  .github/workflows/check.yaml
Labels: backport

#9274 [v7] Trigger Assign workflow on opened and ready_for_review events.
  .github/workflows/assign.yaml
  .github/workflows/check.yaml
Labels: backport

#9140 Improve docs for per-session MFA
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation

#9299 Fix the CRL distribution point in Windows certs
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
Labels: desktop-access

#9313 Disable drone triggers
  .drone.yml
  dronegen/common.go
  dronegen/drone_cli.go
  dronegen/main.go
  dronegen/tests.go
Labels: backport-required

#9338 [branch/v8] Backport #9193
  integration/integration_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: backport

#9194 Add ability to run Mongo proxy on separate listener
  api/client/webclient/webclient.go
  api/profile/profile.go
  integration/db_integration_test.go
  integration/helpers.go
  integration/ports.go
  lib/client/api.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/listeners.go
  lib/service/proxy_settings.go
  lib/service/service.go
  lib/srv/db/proxyserver.go
Labels: database-access, db/mongo

#9005 Post Release 1/4
  docs/config.json
  docs/pages/faq.mdx
Labels: documentation

#9340 Doc update mongo postgres separate listeners
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation

#9341 [v8] Add ability to run Postgres and Mongo proxy on separate listeners
  api/client/webclient/webclient.go
  api/profile/profile.go
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/setup/reference/config.mdx
  integration/db_integration_test.go
  integration/helpers.go
  integration/ports.go
  lib/client/api.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/defaults/defaults.go
  lib/multiplexer/multiplexer.go
  lib/service/cfg.go
  lib/service/listeners.go
  lib/service/proxy_settings.go
  lib/service/service.go
  lib/srv/db/access_test.go
  lib/srv/db/proxyserver.go
Labels: backport

#9390 Add WebAuthn and Active Session docs
  docs/config.json
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/access-controls/introduction.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/architecture/users.mdx
  docs/pages/cloud/guides.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/index.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/reference/authentication.mdx
  docs/pages/setup/reference/cli.mdx
  docs/pages/setup/reference/config.mdx
  docs/pages/setup/reference/terraform-provider.mdx
Labels: documentation, backport

#9396 [v8] Update AWS CLI application access docs ref (#8634)
  docs/pages/application-access/guides/aws-console.mdx
Labels: backport

#9312 [v6.2] Add `synchronize` Event to Check
  .github/workflows/check.yaml
Labels: backport

#9239 [5.0] Disable drone deb repo publishing
  .drone.yml
Labels: backport

#9189 Create a blast radius reduction guide
  docs/config.json
  docs/pages/setup/security.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#9346 Clarify the Linux Getting Started guide
  docs/pages/getting-started/linux-server.mdx
Labels: documentation

#9394 [v8] Fix NO_PROXY addr logic
  integration/proxy_helpers_test.go
  integration/proxy_test.go
  lib/reversetunnel/transport.go
Labels: backport

#9334 update doc examples to change from admin role to editor,access
  docs/pages/api/getting-started.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
Labels: documentation, backport-required

#9326 Fix flaky TestWebsocketPingLoop test
  lib/web/apiserver_test.go
Labels: flaky tests

#9404 [v7] Prevent infinite dialing to Auth
  lib/auth/clt.go
  lib/auth/clt_test.go
Labels: backport

#9403 [v8] Prevent infinite dialing to Auth
  lib/auth/clt.go
  lib/auth/clt_test.go
Labels: backport

#9378 Update README.md
  README.md
Labels: documentation

#9374 Add Videos to Teleport Desktop Access [backport]
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/introduction.mdx
Labels: documentation, backport

#9328 [v6.2] Clear terminal when session ends
  lib/client/session.go
  lib/modules/modules.go
Labels: backport

#9166 [Backport] Google CloudBuild support + build fixes (#9090)
  .cloudbuild/ci/doc-tests.yaml
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/lint.yaml
  .cloudbuild/ci/unit-tests.yaml
  Makefile
  api/client/client.go
  api/defaults/defaults.go
  api/types/networking.go
  integration/helpers.go
  integration/integration_test.go
  integration/kube_integration_test.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/kube/proxy/server.go
  lib/service/service.go
  lib/services/server.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
  lib/srv/db/server.go
  lib/srv/monitor.go
  lib/srv/regular/sshserver.go
  lib/srv/uacc/uacc_linux.go
  lib/utils/loadbalancer.go
  lib/utils/pipenetconn.go
Labels: backport

#9339 [branch/v7] Backport #9193
  integration/integration_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: backport

#9442 [V7] Exclude Jitter from being marshaled in JSON logging
  lib/utils/retry.go
Labels: backport

#9457 [v6.2] Escape access request and access resolution reasons in tctl (#9381)
  tool/tctl/common/access_request_command.go
Labels: backport

#9458 (v8) Add "ListResources" gRPC call
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/client/proto/types.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/backend/backend.go
  lib/cache/cache.go
  lib/client/client.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
Labels: backport

#9459 [v8] Fix app server goroutine leak
  lib/srv/app/listener.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
  lib/utils/conn.go
Labels: backport

#9433 [v8] Fix CryptoRandomHex function
  lib/utils/rand.go
Labels: backport

#9480 Update aws-console.mdx
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation

#9481 Update aws-console.mdx
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation

#9476 Session locking tweaks
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/enterprise/fedramp.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#9447 [V8] Add support f or using `tsh play -f json <ID>`
  lib/client/api.go
  tool/tsh/tsh.go
Labels: backport

#9456 [v7] Escape access request and access resolution reasons in tctl (#9381)
  tool/tctl/common/access_request_command.go
Labels: backport

#9418 Fix initKube: broadcast KubeReady event
  integration/helpers.go
  integration/integration_test.go
  lib/service/kubernetes.go
Labels: backport-required

#9444 [v8] Fix initKube: broadcast KubeReady event
  integration/helpers.go
  integration/integration_test.go
  lib/service/kubernetes.go
Labels: backport

#9503 [helm] Re-add space after type in service definition
  examples/chart/teleport-cluster/templates/service.yaml
Labels: helm

#9477 Update aws-console.mdx
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation

#9455 [v8] Escape access request and access resolution reasons in tctl (#9381)
  tool/tctl/common/access_request_command.go
Labels: backport

#9428 [v8] Use t.Setenv in tests (#9154)
  api/client/webclient/webclient_test.go
  integration/integration_test.go
  integration/proxy_test.go
  lib/auth/keystore/testhelpers.go
  lib/client/keyagent_test.go
  lib/service/service_test.go
  lib/utils/proxy/proxy_test.go
  tool/tsh/proxy_test.go
Labels: backport

#9195 removes experimental note from example config
  docs/pages/setup/reference/config.mdx
Labels: documentation

#9452 [v7] Prevent Linear Retry from converging on Max
  lib/utils/retry.go
  lib/utils/retry_test.go
Labels: backport

#9344 Update rdp-rs
  lib/srv/desktop/rdp/rdpclient/Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: backport-required, desktop-access

#9449 [v8] Prevent Linear Retry from converging on Max
  lib/utils/retry.go
  lib/utils/retry_test.go
Labels: backport

#9510 [v8] Skip tests on a docs-only PR (#9416)
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
  .cloudbuild/scripts/cmd/integration-tests/main.go
  .cloudbuild/scripts/cmd/unit-tests/main.go
  .cloudbuild/scripts/go.mod
  .cloudbuild/scripts/go.sum
  .cloudbuild/scripts/internal/changes/changes.go
  .cloudbuild/scripts/internal/etcd/start.go
Labels: backport

#9512 [v6.2] Skip tests on a docs-only PR (#9416)
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
  .cloudbuild/scripts/cmd/integration-tests/main.go
  .cloudbuild/scripts/cmd/unit-tests/main.go
  .cloudbuild/scripts/go.mod
  .cloudbuild/scripts/go.sum
  .cloudbuild/scripts/internal/changes/changes.go
  .cloudbuild/scripts/internal/etcd/start.go
Labels: backport

#9511 [v7] Skip tests on a docs-only PR (#9416)
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
  .cloudbuild/scripts/cmd/integration-tests/main.go
  .cloudbuild/scripts/cmd/unit-tests/main.go
  .cloudbuild/scripts/go.mod
  .cloudbuild/scripts/go.sum
  .cloudbuild/scripts/internal/changes/changes.go
  .cloudbuild/scripts/internal/etcd/start.go
Labels: backport

#9196 Fix tsh db connect mongo dbuser logic
  tool/tsh/db.go
  tool/tsh/db_test.go
Labels: database-access, db/mongo

#9445 [v8] Fix tsh db connect mongo dbuser logic
  tool/tsh/db.go
  tool/tsh/db_test.go
Labels: backport

#9479 docs: update cloud roadmap and faq
  docs/pages/cloud/architecture.mdx
  docs/pages/cloud/faq.mdx
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#9525 Fix the UI to correctly determine if a user has access to a resource (#9473)
  lib/services/role.go
  lib/services/role_test.go
  lib/web/ui/usercontext.go
Labels: backport

#9518 [v8] backport #9220
  lib/client/api.go
  lib/client/db/profile.go
  lib/client/db/profile_test.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/keystore.go
  lib/client/keystore_test.go
  tool/teleport/common/teleport.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: backport

#9527 v7 backport 9195
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport

#9526 v8 backport 9195
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport

#9575 Emit the correct session ID for SessionLeave events
  integration/integration_test.go
  lib/srv/sess.go
Labels: bug, backport-required, server-access

#9573 Add the `windows_desktop_service` section to the meta `teleport.yaml`
  docs/pages/desktop-access/reference.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport-required

#9599 fixes mdx comment style
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/reference.mdx
Labels: documentation

#9594 Improve TestTwoClustersTunnel troubleshooting
  integration/helpers.go
  integration/integration_test.go
  lib/utils/testlog/log.go
Labels: flaky tests
