Repository gravitational/teleport, pull requests merged in 2021-05, with the labels that each got.

#6656 mfa: only reject last device deletion of correct type
  lib/auth/grpcserver.go
Labels: backport-required

#6654 Backport: k8s: add merge-kubeconfigs.sh script
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  examples/k8s-auth/.gitignore
  examples/k8s-auth/README.md
  examples/k8s-auth/get-kubeconfig.sh
  examples/k8s-auth/merge-kubeconfigs.sh
Labels: documentation

#6735 Backport #6692 to v6.
  lib/defaults/defaults.go
  lib/multiplexer/tls.go
Labels: backport

#6736 Backport #6692 to v6.1.
  lib/defaults/defaults.go
  lib/multiplexer/tls.go
Labels: backport

#6668 Backport v4.4: kube: handle large number of trusted clusters in mTLS handshake
  lib/auth/auth.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
Labels: backport

#6670 Backport 4.2: kube: handle large number of trusted clusters in mTLS handshake
  lib/auth/auth.go
  lib/kube/proxy/server.go
Labels: backport

#6741 ami: Update InfluxDB version to 1.8.5
  assets/aws/Makefile
Labels: release-engineering

#6733 [Backport 6.2] Fix non-interactive ssh output in teleport log
  lib/srv/exec.go
Labels: backport

#6732 [Backport 6.1] Fix non-interactive ssh output in teleport log
  lib/srv/exec.go
Labels: backport

#6650 Fixes teleport cli doc definition --insecure-no-tls
  docs/pages/cli-docs.mdx
Labels: backport-required, documentation

#6718 Backport: Add various prometheus metrics
  docs/pages/metrics-logs-reference.mdx
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/sessions.go
  lib/services/local/configuration.go
  lib/services/server.go
  lib/srv/authhandlers.go
  lib/srv/regular/proxy.go
  lib/srv/regular/sshserver.go
  lib/sshutils/server.go
  metrics.go
Labels: backport

#6720 Backport: Add Additional Prometheus metrics
  docs/pages/metrics-logs-reference.mdx
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/sessions.go
  lib/services/local/configuration.go
  lib/services/server.go
  lib/srv/authhandlers.go
  lib/srv/regular/proxy.go
  lib/srv/regular/sshserver.go
  lib/sshutils/server.go
  metrics.go
Labels: backport

#6715 Backport v6: mfa: only reject last device deletion of correct type
  lib/auth/grpcserver.go
Labels: backport

#6748 [branch/v6.1] Backport "ami: Update InfluxDB version to 1.8.5 (#6741)"
  assets/aws/Makefile
Labels: release-engineering

#6747 [branch/v6] Backport "ami: Update InfluxDB version to 1.8.5 (#6741)"
  assets/aws/Makefile
Labels: release-engineering

#6667 Backport v5: kube: handle large number of trusted clusters in mTLS handshake
  fixtures/certs/ca.pem
  lib/auth/auth.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
Labels: backport

#6722 Clarify node connection debug logs.
  lib/service/connect.go
Labels: backport-required

#6749 [v6.1] Broken Images and Links in Docs
  docs/pages/enterprise/sso/ssh-one-login.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
Labels: backport-required, documentation

#6583 Implement RFD 24 for alternative DynamoDB event indexing
  CHANGELOG.md
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  rfd/0024-dynamo-event-overflow.md
Labels: aws, backport-required

#6078 Fix error in docs (#6070)
  docs/pages/enterprise/sso/ssh-one-login.mdx
Labels: documentation

#6518 RFD 12: clarify that the versioning scheme is not strict
  rfd/0012-teleport-versioning.md
Labels: rfd

#6744 [branch/v6] Backport "Update region list for AWS AMI publishing (#6282)"
  assets/aws/Makefile
  assets/aws/README.md
Labels: release-engineering

#6601 Add app access headers rewrite
  api/types/types.pb.go
  api/types/types.proto
  constants.go
  integration/app_integration_test.go
  lib/auth/sessions.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/service.go
  lib/services/access_request.go
  lib/services/role.go
  lib/services/server.go
  lib/srv/app/session.go
  lib/srv/app/transport.go
Labels: application-access, backport-required

#6558 Handle missing IdP trait in PAM interpolation.
  lib/srv/ctx.go
Labels: PAM, backport-required, c-xa

#6763 (6.2) Add app access headers rewrite
  api/types/types.pb.go
  api/types/types.proto
  constants.go
  integration/app_integration_test.go
  lib/auth/sessions.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/service.go
  lib/services/access_request.go
  lib/services/role.go
  lib/services/server.go
  lib/srv/app/session.go
  lib/srv/app/transport.go
Labels: application-access, backport

#6754 [Backport v6] db/kube handler and check cloud feature
  lib/service/connect.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/apps.go
  lib/web/servers.go
  lib/web/ui/app.go
  lib/web/ui/server.go
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: backport

#6755 [Backport v6.1] Check cloud feature before setting billing access for web
  lib/service/connect.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: backport

#6200 Update test plan for access request, mfa, switchback banner
  docs/testplan.md
Labels: documentation

#6525 Implements RFD-0022 - OpenSSH-compatible Agent Forwarding
  integration/helpers.go
  lib/client/api.go
  lib/client/session.go
  lib/web/terminal.go
  tool/tsh/options.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: ux

#6721 Stop changing kube context by default on tsh login
  CHANGELOG.md
  lib/kube/kubeconfig/kubeconfig.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: ux

#6645 [Backport v6] CLI opt-in adoption survey
  build.assets/install
Labels: backport

#6711 Align atomics to prevent segmentation faults on ARMv7
  lib/events/auditwriter.go
  lib/events/emitter_test.go
Labels: bug

#6653 docs: update merge-kubeconfigs.sh reference to master
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
Labels: documentation

#6018 Generate MinClientVersion based on server Version
  constants.go
  lib/client/api.go
  lib/utils/ver.go
Labels: documentation

#6779 mfa: fix startup crash when SSO users with MFA expire
  lib/services/local/resource.go
  lib/services/local/resource_test.go
Labels: backport-required

#6728 Gives inline info for Google Service account for SSO
  docs/pages/enterprise/sso/ssh-google-workspace.mdx
  docs/pages/gcp-guide.mdx
  examples/resources/gworkspace-connector-inline.yaml
Labels: documentation

#6729 [Backport 6.1] google workspace sso doc changes
  docs/img/gsuite/gsuite-6-manage-api-access.png
  docs/img/gsuite/gsuite-6a-manage-access.png
  docs/img/gsuite/gsuite-7-loginwithgsuite.png
  docs/img/gsuite/gsuite-8-oidc-with-service-account.png
  docs/pages/admin-guide.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/ssh-google-workspace.mdx
  docs/pages/enterprise/sso/ssh-sso.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/kubernetes-access/controls.mdx
  examples/resources/gsuite-connector.yaml
  examples/resources/gworkspace-connector-inline.yaml
  examples/resources/gworkspace-connector.yaml
Labels: backport, documentation

#6798 Removes "demonstration purposes only" comment from locks.tf
  examples/aws/terraform/ha-autoscale-cluster/locks.tf
Labels: terraform

#6327 Updated 5.0 CODEOWNERS.
  .github/CODEOWNERS
Labels: documentation

#6730 [Backport 6.2] google workspace sso doc changes
  docs/img/gsuite/gsuite-6-manage-api-access.png
  docs/img/gsuite/gsuite-6a-manage-access.png
  docs/img/gsuite/gsuite-7-loginwithgsuite.png
  docs/img/gsuite/gsuite-8-oidc-with-service-account.png
  docs/pages/admin-guide.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/ssh-google-workspace.mdx
  docs/pages/enterprise/sso/ssh-sso.mdx
  docs/pages/gcp-guide.mdx
  docs/pages/kubernetes-access/controls.mdx
  examples/resources/gsuite-connector.yaml
  examples/resources/gworkspace-connector-inline.yaml
  examples/resources/gworkspace-connector.yaml
Labels: backport, documentation

#5817 YAML formatting
  docs/pages/enterprise/workflow/index.mdx
Labels: c-ju, documentation

#6844 Update admin-guide.mdx
  docs/pages/admin-guide.mdx
Labels: documentation

#6842 Update admin-guide.mdx Teleport Upgrade section
  docs/pages/admin-guide.mdx
Labels: documentation

#6810 [v6.2] docs: update version in install and getting started guides
  docs/pages/aws-oss-guide.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/getting-started.mdx
Labels: backport-required, documentation

#6808 [v6.2] Docs: add acme to yaml
  docs/pages/config-reference.mdx
Labels: backport-required, documentation

#6699 [v6.2] docs: update certbot section
  docs/pages/aws-oss-guide.mdx
Labels: backport, documentation

#6824 client: set TLS certificate usage for k8s/app/db certs
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  lib/client/api.go
  lib/client/client.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: backport-required

#6603 Add sudo to systemd examples commands
  examples/systemd/README.md
Labels: backport-required, documentation, examples

#6390 docs: Add Helm guides
  docs/config.json
  docs/img/helm/gcp/1-roles@1.5x.png
  docs/img/helm/gcp/10-serviceaccountdetails@1.5x.png
  docs/img/helm/gcp/11-createkey.png
  docs/img/helm/gcp/12-privatekey@1.5x.png
  docs/img/helm/gcp/13-dns-createrole@1.5x.png
  docs/img/helm/gcp/14-dns-permissions-create@1.5x.png
  docs/img/helm/gcp/2-createrole@1.5x.png
  docs/img/helm/gcp/3-addpermissions@1.5x.png
  docs/img/helm/gcp/4-storagebucketscreate@1.5x.png
  docs/img/helm/gcp/5-select@1.5x.png
  docs/img/helm/gcp/6-createrole@1.5x.png
  docs/img/helm/gcp/7-serviceaccounts@1.5x.png
  docs/img/helm/gcp/8-createserviceaccount@1.5x.png
  docs/img/helm/gcp/9-addroles@1.5x.png
  docs/pages/kubernetes-access/helm/guides.mdx
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/kubernetes-access/helm/guides/migration.mdx
  docs/pages/kubernetes-access/helm/includes/helm-install.mdx
  docs/pages/kubernetes-access/helm/includes/kubernetes-externaladdress.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
Labels: documentation, helm, release-engineering

#6344 helm: Adds 'aws', 'gcp', 'standalone' and ‘custom’ modes to `teleport-cluster` chart
  Makefile
  examples/chart/.lint-config.yaml
  examples/chart/teleport-auto-trustedcluster/Chart.yaml
  examples/chart/teleport-auto-trustedcluster/templates/service.yaml
  examples/chart/teleport-cluster/.lint/acme-off.yaml
  examples/chart/teleport-cluster/.lint/acme-on.yaml
  examples/chart/teleport-cluster/.lint/acme-uri-staging.yaml
  examples/chart/teleport-cluster/.lint/affinity.yaml
  examples/chart/teleport-cluster/.lint/annotations.yaml
  examples/chart/teleport-cluster/.lint/aws-ha-acme.yaml
  examples/chart/teleport-cluster/.lint/aws-ha-antiaffinity.yaml
  examples/chart/teleport-cluster/.lint/aws-ha.yaml
  examples/chart/teleport-cluster/.lint/aws.yaml
  examples/chart/teleport-cluster/.lint/gcp-ha-acme.yaml
  examples/chart/teleport-cluster/.lint/gcp-ha-antiaffinity.yaml
  examples/chart/teleport-cluster/.lint/gcp-ha.yaml
  examples/chart/teleport-cluster/.lint/gcp.yaml
  examples/chart/teleport-cluster/.lint/initcontainers.yaml
  examples/chart/teleport-cluster/.lint/resources.yaml
  examples/chart/teleport-cluster/.lint/standalone-customsize.yaml
  examples/chart/teleport-cluster/.lint/standalone-existingpvc.yaml
  examples/chart/teleport-cluster/.lint/tolerations.yaml
  examples/chart/teleport-cluster/.lint/version-override.yaml
  examples/chart/teleport-cluster/.lint/volumes.yaml
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/templates/NOTES.txt
  examples/chart/teleport-cluster/templates/certificate.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/templates/pvc.yaml
  examples/chart/teleport-cluster/templates/service.yaml
  examples/chart/teleport-cluster/templates/serviceaccount.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
  examples/chart/teleport-daemonset/Chart.yaml
  examples/chart/teleport-daemonset/templates/service.yaml
  examples/chart/teleport-kube-agent/.lint/affinity.yaml
  examples/chart/teleport-kube-agent/.lint/all-v5.yaml
  examples/chart/teleport-kube-agent/.lint/all-v6.yaml
  examples/chart/teleport-kube-agent/.lint/annotations.yaml
  examples/chart/teleport-kube-agent/.lint/backwards-compatibility.yaml
  examples/chart/teleport-kube-agent/.lint/db.yaml
  examples/chart/teleport-kube-agent/.lint/initcontainers.yaml
  examples/chart/teleport-kube-agent/.lint/resources.yaml
  examples/chart/teleport-kube-agent/.lint/tolerations.yaml
  examples/chart/teleport-kube-agent/.lint/volumes.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
  examples/chart/teleport/Chart.yaml
  examples/chart/teleport/templates/service.yaml
  examples/chart/teleport/templates/serviceaccount.yaml
  version.mk
Labels: backport-required, helm, release-engineering

#6835 RFD 21 (Cluster Routing): Mark as implemented
  rfd/0021-cluster-routing.md
Labels: rfd

#6228 docs: Don't pull docsbox image if it's already present
  build.assets/Makefile
Labels: backport-required, documentation

#6891 helm: Fixes for Linux/Mac interoperability
  Makefile
  version.mk
Labels: backport-required, release-engineering

#6856 [v6.2] Add ACME to YAML
  docs/pages/config-reference.mdx
Labels: backport, documentation

#6904 Fix typo in trusted clusters docs
  docs/pages/trustedclusters.mdx
Labels: documentation

#6636 (6.2) App/db access 6.2 docs updates
  docs/config.json
  docs/img/database-access/guides/redshift/cluster-endpoint@2x.png
  docs/img/database-access/guides/redshift/cluster-id@2x.png
  docs/img/database-access/guides/redshift/cluster-user-db@2x.png
  docs/pages/application-access/controls.mdx
  docs/pages/config-reference.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/guides/mysql-aws.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-aws.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/database-access/reference.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/preview/upcoming-releases.mdx
  docs/pages/trustedclusters.mdx
Labels: application-access, backport, database-access, documentation

#6932 Application and database access documentation updates
  docs/config.json
  docs/img/database-access/guides/redshift/cluster-endpoint@2x.png
  docs/img/database-access/guides/redshift/cluster-id@2x.png
  docs/img/database-access/guides/redshift/cluster-user-db@2x.png
  docs/pages/application-access/controls.mdx
  docs/pages/config-reference.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/guides/mysql-aws.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-aws.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/database-access/reference.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
  docs/pages/preview/upcoming-releases.mdx
  docs/pages/trustedclusters.mdx
Labels: documentation

#6694 [v6.2] Server Access Section
  docs/config.json
  docs/img/server-access/getting-started-diagram.svg
  docs/img/server-access/openssh-proxy.svg
  docs/img/server-access/subdomains.png
  docs/img/server-access/teleport_ui.png
  docs/pages/admin-guide.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/getting-started.mdx
  docs/pages/index.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  docs/pages/server-access/introduction.mdx
Labels: backport-required, documentation

#6948 mfa: strip trailing newline when reading TOTP codes
  lib/utils/prompt/confirmation.go
  lib/utils/prompt/confirmation_test.go
Labels: backport-required

#6913 [branch/v6.1] docs: Update docker tags to use latest 6.x version tag
  docs/config.json
Labels: documentation, release-engineering

#6911 docs: Update docker tags to use latest 7.x version tag
  docs/config.json
Labels: documentation, release-engineering

#6912 [branch/v6] docs: Update docker tags to use latest 6.x version tag
  docs/config.json
Labels: documentation, release-engineering

#6862 Backport: Ensure session end after upload completer uploads
  lib/events/api.go
  lib/events/complete.go
Labels: backport

#6899 docker: Override GOMODCACHE to always use a writable location
  Makefile
  build.assets/Makefile
Labels: release-engineering

#6854 [v7.0] Add acme to YAML
  docs/pages/config-reference.mdx
Labels: backport, documentation

#6852 [v6.1] docs: update version in install and getting started guides
  docs/pages/aws-oss-guide.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/getting-started.mdx
Labels: backport, documentation

#6853 [v7.0] docs: update version in install and getting started guides #6810
  docs/pages/aws-oss-guide.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/getting-started.mdx
Labels: backport, documentation

#6698 [v6.1] docs: update certbot section
  docs/pages/aws-oss-guide.mdx
Labels: backport, documentation

#6697 [v7.0] docs: update certbot section
  docs/pages/aws-oss-guide.mdx
Labels: backport, documentation

#6855 [v6.1] Add acme to YAML
  docs/pages/config-reference.mdx
Labels: backport, documentation

#6944 helm: Fix antiAffinity in teleport-cluster
  examples/chart/teleport-cluster/templates/deployment.yaml
Labels: helm

#6886 [branch/v6] Backport "docs: Add Helm guides (#6390)"
  docs/config.json
  docs/img/helm/gcp/1-roles@1.5x.png
  docs/img/helm/gcp/10-serviceaccountdetails@1.5x.png
  docs/img/helm/gcp/11-createkey.png
  docs/img/helm/gcp/12-privatekey@1.5x.png
  docs/img/helm/gcp/13-dns-createrole@1.5x.png
  docs/img/helm/gcp/14-dns-permissions-create@1.5x.png
  docs/img/helm/gcp/2-createrole@1.5x.png
  docs/img/helm/gcp/3-addpermissions@1.5x.png
  docs/img/helm/gcp/4-storagebucketscreate@1.5x.png
  docs/img/helm/gcp/5-select@1.5x.png
  docs/img/helm/gcp/6-createrole@1.5x.png
  docs/img/helm/gcp/7-serviceaccounts@1.5x.png
  docs/img/helm/gcp/8-createserviceaccount@1.5x.png
  docs/img/helm/gcp/9-addroles@1.5x.png
  docs/pages/kubernetes-access/helm/guides.mdx
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/kubernetes-access/helm/guides/migration.mdx
  docs/pages/kubernetes-access/helm/includes/helm-install.mdx
  docs/pages/kubernetes-access/helm/includes/kubernetes-externaladdress.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
Labels: documentation

#6874 Backport: Add `session_recording` field to session start and end events
  api/types/events/events.pb.go
  api/types/events/events.proto
  lib/events/api.go
  lib/kube/proxy/forwarder.go
  lib/srv/sess.go
Labels: backport

#6472 RFD 28: Cluster configuration related resources
  rfd/0028-cluster-config-resources.md
Labels: rfd, ux

#6809 [v7.0] Docs: update docs best practices
  docs/pages/docs.mdx
  docs/pages/docs/best-practices.mdx
Labels: backport-required, documentation

#6975 mfa: user server instead of log context.Context for audit events
  lib/auth/grpcserver.go
Labels: backport-required

#6771 Update tctl docs to include new global flags and remote functionality.
  docs/pages/cli-docs.mdx
  tool/tctl/common/tctl.go
Labels: documentation

#6980 Fix tclt --auth-servers flag panic.
  tool/tctl/common/tctl.go
Labels: backport-required, bug

#6996 docs: delay 6.2 release on upcoming releases page
  docs/pages/preview/upcoming-releases.mdx
Labels: backport-required

#6792 [v6.1] docs: icon fix
  docs/pages/enterprise/sso/ssh-one-login.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
Labels: bug, documentation

#6973 Variable exporting fix on AWS Terraform Guide
  docs/pages/aws-terraform-guide.mdx
Labels: documentation, external

#6990 Resolve test issues and event driver bugs
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/firestoreevents/firestoreevents_test.go
  lib/events/test/suite.go
Labels: backport-required

#6901 docker: Restore Firestore emulator
  build.assets/Dockerfile
  build.assets/Makefile
Labels: backport-required, release-engineering

#6902 helm: Don't package/update old teleport chart
  .drone.yml
  examples/chart/index.html
  examples/chart/teleport-cluster/README.md
Labels: helm, release-engineering

#6873 [v6.2] docs: improve go API example
  docs/pages/reference/api/getting-started.mdx
Labels: backport-required, documentation

#7024 Check resource permission when generating database certs
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/permissions.go
  lib/services/presets.go
  lib/services/role.go
Labels: backport-required, database-access

#7025 (v6) Allow users impersonating database service generate database certs
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/permissions.go
  lib/services/presets.go
  lib/services/role.go
Labels: backport

#7038 (v6.2) Allow users impersonating database service generate database certs
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/permissions.go
  lib/services/presets.go
  lib/services/role.go
Labels: backport

#6786 Stop registering Kube cluster named after Teleport cluster
  CHANGELOG.md
  integration/kube_integration_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/kube/proxy/auth.go
  lib/kube/proxy/auth_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/server.go
  lib/service/cfg.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: ux

#7026 [branch/v6.2] docker: Restore Firestore emulator (#6901)
  build.assets/Dockerfile
  build.assets/Makefile
Labels: release-engineering

#7048 [v6] Fix support for insecure etcd mode
  examples/etcd/start-etcd-insecure.sh
  lib/backend/etcdbk/etcd.go
Labels: backport

#7033 [branch/v6.2] Update version numbers in docs config
  docs/config.json
Labels: documentation

#7049 [v6.2] Fix support for insecure etcd mode
  examples/etcd/start-etcd-insecure.sh
  lib/backend/etcdbk/etcd.go
Labels: backport

#7028 [branch/v6] docker: Restore Firestore emulator (#6901)
  build.assets/Dockerfile
  build.assets/Makefile
  examples/chart/teleport-cluster/test-config.yaml
  examples/chart/teleport-cluster/test-issuer-aws-prod.yaml
  examples/chart/teleport-cluster/test-issuer-aws-staging.yaml
  examples/chart/teleport-cluster/test-issuer-gcp-prod.yaml
  examples/chart/teleport-cluster/test-issuer-gcp-staging.yaml
  examples/chart/teleport-cluster/test-values-aws.yaml
  examples/chart/teleport-cluster/test-values-gcp.yaml
Labels: release-engineering

#7037 Update AMI IDs for 6.2.0
  assets/aws/Makefile
  assets/aws/files/make-amis-public.sh
  assets/aws/update-ami-ids.sh
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: automated, backport-required, terraform

#7060 teleport-kube-agent: Add support for annotations.serviceAccount
  docs/pages/kubernetes-access/helm/reference.mdx
  examples/chart/teleport-kube-agent/.lint/annotations.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: backport-required, helm

#7061 [v6.2] docs: correct query
  docs/pages/server-access/getting-started.mdx
Labels: bug, documentation

#6936 [v7.0] Port of 6.2 Server Access Section
  docs/config.json
  docs/img/server-access/getting-started-diagram.svg
  docs/img/server-access/openssh-proxy.svg
  docs/img/server-access/subdomains.png
  docs/img/server-access/teleport_ui.png
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  docs/pages/server-access/introduction.mdx
Labels: backport, documentation

#7019 [v6.2] Fix URLs
  docs/config.json
Labels: documentation

#7012 Improve RFD 24 Dynamo migration efficiency and performance
  lib/auth/init.go
  lib/backend/helpers.go
  lib/backend/test/suite.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/events/test/suite.go
  lib/service/service.go
  lib/service/service_test.go
  lib/utils/retry.go
Labels: backport-required

#7077 docs: Improve label documentation for db_service via teleport-kube-agent
  docs/pages/kubernetes-access/helm/reference.mdx
Labels: backport-required, documentation, helm

#6871 [v6.2] Docs: correct logging and console outputs
  lib/config/configuration.go
  lib/fixtures/keys.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service.go
  lib/utils/certs.go
  lib/utils/tls.go
Labels: backport-required, documentation

#7056 docs: Update post-release checklist
  docs/postrelease.md
Labels: documentation, release-engineering

#7080 rpm: Don't include build-id artifacts in packages
  Makefile
  build.assets/build-package.sh
  build.assets/rpm-sign/rpmmacros
  build.assets/rpm/rpmmacros
Labels: release-engineering

#7097 Fix a variable shadowing error causing uneeded tries during event migration
  lib/events/dynamoevents/dynamoevents.go
Labels: backport-required
