Repository gravitational/teleport, pull requests merged in 2021-10, with the labels that each got.

#8431 [branch/v7] k8s misspelling in error message
  lib/kube/proxy/forwarder.go
Labels: backport

#8339 Auto-configure IAM for RDS databases
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  api/types/types.proto
  lib/cloud/identity.go
  lib/cloud/identity_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/db.go
  lib/srv/db/access_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/cloud/meta.go
  lib/srv/db/cloud/meta_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/cloud/rds.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/cloud.go
  lib/srv/db/common/errors.go
  lib/srv/db/common/policy.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/server.go
  lib/srv/db/watcher.go
  tool/teleport/common/teleport.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/doc.go
  vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/iam/service.go
  vendor/github.com/aws/aws-sdk-go/service/iam/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/rds/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/rds/doc.go
  vendor/github.com/aws/aws-sdk-go/service/rds/doc_custom.go
  vendor/github.com/aws/aws-sdk-go/service/rds/errors.go
  vendor/github.com/aws/aws-sdk-go/service/rds/rdsiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/rds/service.go
  vendor/github.com/aws/aws-sdk-go/service/rds/waiters.go
  vendor/modules.txt
Labels: database-access

#8459 [branch v7] Removes double quotes from acme examples in docs
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/setup/reference/config.mdx
Labels: backport

#8348 Auto-configure IAM for Redshift databases
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  api/types/types.proto
  lib/srv/db/access_test.go
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/cloud/meta.go
  lib/srv/db/cloud/meta_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/cloud.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  vendor/github.com/aws/aws-sdk-go/service/redshift/redshiftiface/interface.go
  vendor/modules.txt
Labels: database-access

#8308 Adds OIDC logic for Ping Provider
  go.mod
  go.sum
  lib/auth/oidc.go
  lib/auth/oidc_test.go
  vendor/github.com/coreos/go-oidc/oauth2/oauth2.go
  vendor/modules.txt
Labels: sso, backport-required

#8302 Update Github SSO Video [ v7 backport ]
  docs/pages/setup/admin/github-sso.mdx
Labels: backport

#8496 teleport-kube-agent: postgresql -> postgres in README
  examples/chart/teleport-kube-agent/README.md
Labels: docs-required

#8668 [auto] Update AMI IDs for 7.3.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated
