Repository gravitational/teleport, pull requests merged in 2022-08, with the labels that each got.

#14781 Create and List Connection Diagnostics
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/connection_diagnostic.go
  api/types/constants.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/services/connection_diagnostic.go
  lib/services/local/connection_diagnostic.go
  lib/services/presets.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/servers.go
  lib/web/ui/server.go
Labels: backport, backport/branch/v10, discover

#14526 Download mTLS files from Web
  api/identityfile/identityfile.go
  api/types/constants.go
  lib/auth/auth_with_roles.go
  lib/auth/permissions.go
  lib/client/db/database_certificates.go
  lib/client/identityfile/inmemory_config_writer.go
  lib/client/identityfile/inmemory_config_writer_test.go
  lib/services/presets.go
  lib/services/provisioning.go
  lib/utils/archive.go
  lib/utils/archive_test.go
  lib/utils/inmemory_fs.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sign.go
  tool/tctl/common/auth_command.go
Labels: backport, backport/branch/v10, discover

#14712 Proxy Protocol support for Proxy SSH listener
  api/utils/sshutils/ssh.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/service/service.go
  lib/sshutils/server.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#14852 Edit the Slack access request plugin guide
  docs/img/request-access.png
  docs/img/review-request.png
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/api/introduction.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/resource-requests.mdx
  docs/pages/enterprise/workflow/role-requests.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/impersonations.mdx
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#14807 [OSS-fuzz] Fix FuzzMongoRead
  lib/srv/db/mongodb/protocol/fuzz_test.go
  lib/srv/db/mongodb/protocol/opcompressed.go
  lib/srv/db/mongodb/protocol/opinsert.go
  lib/srv/db/mongodb/protocol/opmsg.go
  lib/srv/db/mongodb/protocol/opreply.go
Labels: database-access

#15081 [V10] Download mTLS files from Web (#14526)
  api/identityfile/identityfile.go
  api/types/constants.go
  lib/auth/auth_with_roles.go
  lib/auth/permissions.go
  lib/client/db/database_certificates.go
  lib/client/identityfile/inmemory_config_writer.go
  lib/client/identityfile/inmemory_config_writer_test.go
  lib/services/presets.go
  lib/services/provisioning.go
  lib/utils/archive.go
  lib/utils/archive_test.go
  lib/utils/inmemory_fs.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sign.go
  tool/tctl/common/auth_command.go
Labels: tctl

#15036 Backport [v9] Add error messages to SFTP audit events
  api/types/events/events.pb.go
  api/types/events/events.proto
  tool/teleport/common/sftp.go
Labels: audit-log

#15067 Release 10.1.1
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm

#14598 Move Access Requests guides to Access Controls
  CHANGELOG.md
  docs/config.json
  docs/pages/access-controls/access-request-plugins/index.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/access-controls/access-requests.mdx
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/api/introduction.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/includes/access-request-integrations.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation, backport/branch/v10

#15063 [v9] Apply forScopes feature to articles
  docs/config.json
Labels: documentation

#14902 [v9] Add a version to the role in the GitHub CA guide
  docs/pages/setup/guides/ssh-key-extensions.mdx
Labels: documentation

#15104 Release 10.1.2
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#15105 Release 9.3.14
  CHANGELOG.md
Labels: backport

#14552 `tctl` - Add --set flags for every trait
  tool/tctl/common/helpers_test.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
Labels: tctl, backport/branch/v10

#15107 Release 9.3.14
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm, backport

#15112 Amend 10.1.2 changelog
  CHANGELOG.md
Labels: backport

#14416 Fix session join requirements documentation
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/use-teleport/tsh.mdx
Labels: documentation, backport-required, backport/branch/v10

#14992 [v10] Backport #14564
  api/types/events/events.pb.go
  api/types/events/events.proto
  integration/integration_test.go
  lib/auth/auth_with_roles.go
  lib/events/api.go
  lib/events/fields.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/remotesite.go
  lib/srv/ctx.go
  lib/srv/forward/sshserver.go
  lib/srv/mock.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
Labels: audit-log

#14899 Skip cache during CreateBot RPC
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/clt.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/auth/oidc_test.go
  lib/auth/saml_test.go
  lib/services/access.go
  lib/services/local/access.go
Labels: backport/branch/v10

#13808 helm: configure dynamoDB autoscaling in teleport-cluster
  docs/pages/setup/helm-deployments/aws.mdx
  docs/pages/setup/reference/backends.mdx
  examples/chart/teleport-cluster/.lint/aws-dynamodb-autoscaling.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/config_test.yaml.snap
  examples/chart/teleport-cluster/tests/config_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport/branch/v10

#14978 Add docs for TCP apps access
  docs/config.json
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/tcp.mdx
  docs/pages/application-access/introduction.mdx
Labels: documentation, backport/branch/v10

#15099 docs: Change "SOC2" to "SOC 2"
  docs/config.json
  docs/pages/enterprise/soc2.mdx
  docs/pages/faq.mdx
  docs/pages/includes/soc2.mdx
Labels: documentation

#15052 [v10] fix help output for --access-request flag.
  tool/tctl/common/access_request_command.go
Labels: tctl

#15054 [v9] fix help output for --access-request flag.
  tool/tctl/common/access_request_command.go
Labels: tctl

#15125 [v10] Add docs for TCP apps access
  docs/config.json
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/tcp.mdx
  docs/pages/application-access/introduction.mdx
Labels: documentation, backport

#15013 Fix the behavior of `tsh mfa add --allow-passwordless`
  lib/auth/webauthncli/fido2.go
  tool/tsh/mfa.go
Labels: tsh, backport/branch/v10

#14900 Add calls to action for Teleport Cloud
  docs/pages/getting-started/kubernetes-cluster.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/deployments/digitalocean.mdx
  docs/pages/setup/deployments/gcp.mdx
  docs/pages/setup/deployments/ibm.mdx
  docs/pages/setup/helm-deployments/aws.mdx
  docs/pages/setup/helm-deployments/digitalocean.mdx
  docs/pages/setup/helm-deployments/gcp.mdx
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/operations/scaling.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15108 [v10] `tctl` - Add --set flags for every trait (#14552)
  tool/tctl/common/helpers_test.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
Labels: tctl, backport

#13746 [v9] Refine the organization of /docs/getting-started
  docs/config.json
  docs/pages/getting-started.mdx
  docs/pages/index.mdx
  docs/pages/setup/deployments.mdx
  docs/pages/setup/deployments/digitalocean.mdx
Labels: documentation

#14673 [v10] Clarify when HTTP_PROXY applies
  docs/pages/setup/reference/networking.mdx
Labels: documentation

#15131 Remove erroneous section
  docs/pages/use-teleport/tsh.mdx
Labels: documentation

#15074 Add handshake timeout to RDP connections
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access

#14907 [docs] AWS external ID support
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/application-access/reference.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15003 [v10] helm: configure session recording in teleport-cluster
  docs/pages/setup/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/.lint/session-recording.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/config_test.yaml.snap
  examples/chart/teleport-cluster/tests/config_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm

#13671 helm: Add support for mounting existing TLS root CA
  docs/pages/setup/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/existing-tls-secret-with-ca.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport/branch/v10

#15132 [v10]Update docs version
  docs/config.json
Labels: documentation, backport

#15160 Don't reset eventID to 0 when out of events in the Postgres backend
  lib/backend/postgres/tx.go
Labels: backport/branch/v9, backport/branch/v10

#15157 [auto] Update AMI IDs for 10.1.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#14984 [v10] backport #14698 (embed auth.Cache in auth.Server)
  integration/integration_test.go
  lib/auth/access.go
  lib/auth/accountrecovery.go
  lib/auth/accountrecovery_test.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/db.go
  lib/auth/github.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/auth/kube.go
  lib/auth/methods.go
  lib/auth/moderated_sessions_test.go
  lib/auth/oidc.go
  lib/auth/oidc_test.go
  lib/auth/password.go
  lib/auth/password_test.go
  lib/auth/rotate.go
  lib/auth/saml.go
  lib/auth/saml_test.go
  lib/auth/sessions.go
  lib/auth/sso_diag_context.go
  lib/auth/tls_test.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
  lib/auth/user.go
  lib/auth/usertoken.go
  lib/auth/usertoken_test.go
  lib/cache/cache.go
  lib/service/service.go
  lib/services/local/desktops.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/web/apiserver_test.go
Labels: backport

#13288 AWS session audit log
  api/types/events/events.pb.go
  api/types/events/events.proto
  lib/srv/app/aws/handler.go
  lib/srv/app/aws/handler_test.go
  lib/srv/app/common/session.go
  lib/srv/app/server.go
  lib/srv/app/session.go
  lib/tlsca/ca.go
Labels: aws, application-access, backport/branch/v10

#15118 [v9] add backport workflow
  .github/workflows/backport.yaml
Labels: backport

#15122 [v10] helm: configure dynamoDB autoscaling in teleport-cluster
  docs/pages/setup/helm-deployments/aws.mdx
  docs/pages/setup/reference/backends.mdx
  examples/chart/teleport-cluster/.lint/aws-dynamodb-autoscaling.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/config_test.yaml.snap
  examples/chart/teleport-cluster/tests/config_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport

#15137 [v10] Fix the behavior of `tsh mfa add --allow-passwordless`
  lib/auth/webauthncli/fido2.go
  tool/tsh/mfa.go
Labels: tsh, backport

#15085 Actually use the cache for Snowflake sessions
  lib/cache/cache.go
Labels: backport/branch/v10

#15165 [v10] Don't reset eventID to 0 when out of events in the Postgres backend
  lib/backend/postgres/tx.go
Labels: backport

#15166 [v9] Don't reset eventID to 0 when out of events in the Postgres backend
  lib/backend/postgres/tx.go
Labels: backport

#15116 [v10] Skip cache during CreateBot RPC
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/clt.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/auth/oidc_test.go
  lib/auth/saml_test.go
  lib/services/access.go
  lib/services/local/access.go
Labels: backport

#15197 Add custom unmarshal for second_type factor (#10203)
  api/constants/constants.go
  lib/config/fileconf_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15161 [v10] [docs] AWS external ID support
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/application-access/reference.mdx
Labels: documentation, backport

#15163 [v9] [docs] AWS external ID support
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/application-access/reference.mdx
Labels: documentation, backport

#14898 [doc] Remove "tsh db login" from database guides
  docs/pages/database-access/architecture.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/gui-clients.mdx
  docs/pages/database-access/guides/ha.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-aws.mdx
  docs/pages/database-access/guides/snowflake.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/includes/database-access/redis-connect.mdx
  docs/pages/includes/database-access/sql-server-local-proxy.mdx
Labels: documentation, backport/branch/v10

#15207 [v10] AWS session audit log (#13288)
  api/types/events/events.pb.go
  api/types/events/events.proto
  lib/srv/app/aws/handler.go
  lib/srv/app/aws/handler_test.go
  lib/srv/app/common/session.go
  lib/srv/app/server.go
  lib/srv/app/session.go
  lib/tlsca/ca.go
Labels: application-access, backport

#14947 fix peer addr for in-memory control stream
  api/client/inventory.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  integration/integration_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/service/connect.go
  lib/service/service.go
Labels: backport/branch/v10

#15191 docs: Add security warning to BPF-based enhanced session recording about known issues
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation

#15212 Use `waitForError` instead of `require.Eventually` in SessionRecordingModes integration tests
  integration/integration_test.go
Labels: flaky tests

#13630 Windows Desktop Directory Sharing
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/flags.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
  lib/srv/desktop/tdp/proto.go
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#14901 [v10] Add a version to the role in the GitHub CA guide
  docs/pages/setup/guides/ssh-key-extensions.mdx
Labels: documentation

#14871 Add FAQ and Troubleshooting docs for Machine ID
  docs/config.json
  docs/pages/machine-id/faq.mdx
  docs/pages/machine-id/troubleshooting.mdx
Labels: documentation, machine-id, backport/branch/v9, backport/branch/v10

#15208 Added 08/04 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#15230 forScopes changed to array
  docs/config.json
Labels: documentation, backport

#15195 Detect M1/M2 ARM CPUs when using the install script
  lib/web/scripts/node-join/install.sh
Labels: backport/branch/v10

#15193 [v10] Actually use the cache for Snowflake sessions
  lib/cache/cache.go
Labels: backport

#14999 [v8] `tsh ssh` `--forward` and `--dynamic-forward`: graceful error handling
  lib/client/api.go
  lib/client/client.go
  lib/client/client_test.go
Labels: backport

#15130 [v10] Fix session join requirements documentation (#14416)
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/use-teleport/tsh.mdx
Labels: documentation, backport

#15120 Fix missing cluster name on session.upload via Upload Completer (#9794)
  lib/events/complete.go
  lib/events/complete_test.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: audit-log, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15203 [v8] Add custom unmarshal for second_type factor
  api/constants/constants.go
  lib/config/fileconf_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport

#14456 [v10] Backport #13507
  integration/helpers.go
  integration/integration_test.go
  lib/client/kubesession.go
  lib/client/session.go
  tool/tsh/kube.go
Labels: tsh

#14457 [v9] Backport #13507
  integration/helpers.go
  integration/integration_test.go
  lib/client/kubesession.go
  lib/client/session.go
  tool/tsh/kube.go
Labels: tsh

#15201 [v10] Add custom unmarshal for second_type factor
  api/constants/constants.go
  lib/config/fileconf_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport

#15075 Fix data race on shutdown
  lib/service/service.go
Labels: backport-required, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15180 desktop access: try using system DNS resolver first
  lib/srv/desktop/discovery.go
Labels: backport-required, desktop-access, backport/branch/v9, backport/branch/v10

#14759 Add passwordless logins to teleterm
  .github/ISSUE_TEMPLATE/testplan.md
  lib/auth/webauthncli/api.go
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
  lib/auth/webauthncli/prompt.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/weblogin.go
  lib/client/weblogin_test.go
  lib/teleterm/api/proto/v1/auth_settings.proto
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/auth_settings.pb.go
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/auth_settings_pb.d.ts
  lib/teleterm/api/protogen/js/v1/auth_settings_pb.js
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/cluster_auth_test.go
Labels: backport/branch/v10

#15248 [v10] Fix data race on shutdown
  lib/service/service.go
Labels: backport

#15241 Try to fix flaky TestProxyClientDisconnectDueToIdleConnection UT
  lib/srv/db/access_test.go
  lib/srv/db/server.go
Labels: flaky tests, database-access

#15259 Backport #15191 to branch/v8
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#15258 Backport #15191 to branch/v9
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#15257 Backport #15191 to branch/v10
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#15260 Backport #15099 to branch/v10
  docs/config.json
  docs/pages/enterprise/soc2.mdx
  docs/pages/faq.mdx
  docs/pages/includes/soc2.mdx
Labels: documentation, backport

#15084 Backport #14852 to branch/v10
  docs/img/request-access.png
  docs/img/review-request.png
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/api/introduction.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/resource-requests.mdx
  docs/pages/enterprise/workflow/role-requests.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/impersonations.mdx
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#15217 Fix incorrect config.json URLs
  docs/config.json
Labels: documentation

#15232 Minor updates to FedRAMP documentation
  docs/pages/enterprise/fedramp.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#12858 Fix link in Authentication options docs
  docs/pages/setup/reference/authentication.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15071 [v10] Update instructions on checking version
  docs/pages/setup/admin/upgrading-the-teleport-binary.mdx
Labels: documentation

#15072 [v9] Update instructions on checking version
  docs/pages/setup/admin/upgrading-the-teleport-binary.mdx
Labels: documentation

#15263 Backport #12815 to branch/v8
  .github/workflows/terraform-lint.yaml
Labels: backport

#15109 ci: Implement code scanning with CodeQL
  .github/workflows/codeql-analysis.yml
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#15219 [v10] Remove incorrect URLs from config.json
  docs/config.json
Labels: documentation, backport

#15196 Machine ID docs: Trusted Cluster support
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15261 Backport #12815 to branch/v10
  .github/workflows/terraform-lint.yaml
Labels: backport

#15262 Backport #12815 to branch/v9
  .github/workflows/terraform-lint.yaml
Labels: backport

#15267 VSCode remote ssh extension settings
  docs/img/vscode/settings.png
  docs/pages/server-access/guides/vscode.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15273 [v10] Minor updates to FedRAMP documentation
  docs/pages/enterprise/fedramp.mdx
Labels: documentation, backport

#15110 ci: Implement CIFuzz for fuzzing pull requests and pushes
  .github/workflows/cifuzz.yml
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#14267 `UnixPath` and `WindowsPath`
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_nop.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/path.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#15183 docs: add a note about desktop session recording RBAC
  docs/pages/desktop-access/reference/sessions.mdx
Labels: documentation, backport-required, backport/branch/v9, backport/branch/v10

#15256 [v9] desktop access: try using system DNS resolver first
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access

#15229 [v10] Revert "Use high CPU pool for unit & integration (#13875)"
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
Labels: backport

#15233 [v10] Detect M1/M2 ARM CPUs when using the install script
  lib/web/scripts/node-join/install.sh
Labels: backport

#15199 Adjust Machine ID generated ssh cert path to align with convention
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/ssh_config.golden
  lib/tbot/identity/artifact.go
  lib/tbot/identity/identity.go
  lib/tbot/renew.go
Labels: machine-id, backport/branch/v10

#15226 [v10] Add FAQ and Troubleshooting docs for Machine ID
  docs/config.json
  docs/pages/machine-id/faq.mdx
  docs/pages/machine-id/troubleshooting.mdx
Labels: documentation, backport

#15240 [v10] [doc] Remove "tsh db login" from database guides
  docs/pages/database-access/architecture.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/gui-clients.mdx
  docs/pages/database-access/guides/ha.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-aws.mdx
  docs/pages/database-access/guides/snowflake.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/includes/database-access/redis-connect.mdx
  docs/pages/includes/database-access/sql-server-local-proxy.mdx
Labels: documentation, backport

#15239 [v10] Fix missing cluster name on session.upload via Upload Completer
  lib/events/complete.go
  lib/events/complete_test.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: audit-log, backport

#15216 [v9] Remove inaccurate URLs from config.json
  docs/config.json
Labels: documentation, backport

#15255 [v10] desktop access: try using system DNS resolver first
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access

#15141 [v9] Add calls to action for Teleport Cloud
  docs/pages/getting-started/kubernetes-cluster.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/deployments/digitalocean.mdx
  docs/pages/setup/deployments/gcp.mdx
  docs/pages/setup/deployments/ibm.mdx
  docs/pages/setup/helm-deployments/aws.mdx
  docs/pages/setup/helm-deployments/digitalocean.mdx
  docs/pages/setup/helm-deployments/gcp.mdx
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/operations/scaling.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport

#15139 [v10] Add calls to action for Teleport Cloud
  docs/pages/getting-started/kubernetes-cluster.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/deployments/digitalocean.mdx
  docs/pages/setup/deployments/gcp.mdx
  docs/pages/setup/deployments/ibm.mdx
  docs/pages/setup/helm-deployments/aws.mdx
  docs/pages/setup/helm-deployments/digitalocean.mdx
  docs/pages/setup/helm-deployments/gcp.mdx
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/operations/scaling.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport

#14954 Attempt to connect to other proxies on failure
  lib/proxy/client.go
  lib/proxy/client_test.go
  lib/proxy/helpers_test.go
  lib/proxy/server_test.go
Labels: backport/branch/v10, proxy-peering

#15291 [v9] docs: add a note about desktop session recording RBAC
  docs/pages/desktop-access/reference/sessions.mdx
Labels: documentation, backport

#15290 [v10] docs: add a note about desktop session recording RBAC
  docs/pages/desktop-access/reference/sessions.mdx
Labels: documentation, backport

#13531 Add more general information to our SSO guide
  docs/pages/enterprise/sso.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15294 docs: Add additional known issues to BPF-based enhanced session recording security warning
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15138 [v10] Move Access Requests guides to Access Controls
  CHANGELOG.md
  docs/config.json
  docs/pages/access-controls/access-request-plugins/index.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/access-controls/access-requests.mdx
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/api/introduction.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/includes/access-request-integrations.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation, backport

#15114 Add Suggested Labels to Provision Tokens
  api/types/constants.go
  api/types/provisioning.go
  api/types/types.pb.go
  api/types/types.proto
  lib/web/apiserver_test.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/node-join/install.sh
Labels: backport/branch/v10, discover

#14653 [v10] Add directory sharing to the ACL
  lib/services/role.go
  lib/srv/desktop/dir_sharing_disabled.go
  lib/srv/desktop/dir_sharing_enabled.go
  lib/srv/desktop/windows_server.go
  lib/web/ui/usercontext.go
Labels: desktop-access

#15220 desktop access: send full websocket messages to the browser
  lib/web/desktop.go
Labels: backport-required, desktop-access, backport/branch/v9, backport/branch/v10

#15315 [v9] desktop access: send full websocket messages to the browser
  lib/web/desktop.go
Labels: backport, desktop-access

#15280 [v9] ci: Implement code scanning with CodeQL
  .github/workflows/codeql-analysis.yml
Labels: backport

#15314 [v10] desktop access: send full websocket messages to the browser
  lib/web/desktop.go
Labels: backport, desktop-access

#15310 [v8] docs: Add additional known issues to BPF-based enhanced session recording security warning
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#15307 [v10] Add more general information to our SSO guide
  docs/pages/enterprise/sso.mdx
Labels: documentation, backport

#15309 [v9] docs: Add additional known issues to BPF-based enhanced session recording security warning
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#15308 [v10] docs: Add additional known issues to BPF-based enhanced session recording security warning
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#14997 [v9] Shutdown TCP socket on Go-side close
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access

#15279 [v10] ci: Implement code scanning with CodeQL
  .github/workflows/codeql-analysis.yml
Labels: backport

#15295 [v10] Machine ID docs: Trusted Cluster support
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport

#14965 Document teleport-operator
  docs/config.json
  docs/pages/setup/guides.mdx
  docs/pages/setup/guides/teleport-operator.mdx
  docs/pages/setup/helm-reference/teleport-cluster.mdx
Labels: documentation, backport/branch/v10

#14996 [v10] Shutdown TCP socket on Go-side close
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access

#13059 Add "RDP connection fail" section to desktop access troubleshooting docs
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10

#15124 Add support for variable playback speed for Desktop Access recordings
  lib/web/desktop/playback.go
Labels: desktop-access, backport/branch/v9, backport/branch/v10

#15221 [v10] Use `waitForError` instead of `require.Eventually` in SessionRecordingModes integration tests
  integration/integration_test.go
Labels: backport

#15319 [v10] Add Suggested Labels to Provision Tokens (#15114)
  api/types/constants.go
  api/types/provisioning.go
  api/types/types.pb.go
  api/types/types.proto
  lib/web/apiserver_test.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/node-join/install.sh
Labels: backport

#15265 [v10] Add passwordless login capabilities to teleterm
  lib/auth/webauthncli/api.go
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
  lib/auth/webauthncli/prompt.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/weblogin.go
  lib/client/weblogin_test.go
  lib/teleterm/api/proto/v1/auth_settings.proto
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/auth_settings.pb.go
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/auth_settings_pb.d.ts
  lib/teleterm/api/protogen/js/v1/auth_settings_pb.js
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/cluster_auth_test.go
Labels: backport

#15227 [v9] Add FAQ and Troubleshooting docs for Machine ID
  docs/config.json
  docs/pages/machine-id/faq.mdx
  docs/pages/machine-id/troubleshooting.mdx
Labels: documentation, backport

#15080 [v10] Create and List Connection Diagnostics (#14781)
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/connection_diagnostic.go
  api/types/constants.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/services/connection_diagnostic.go
  lib/services/local/connection_diagnostic.go
  lib/services/presets.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/servers.go
  lib/web/ui/server.go
Labels: discover

#15202 [v9] Add custom unmarshal for second_type factor
  api/constants/constants.go
  lib/config/fileconf_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport

#15115 Connect docs: Add section about insecure mode
  docs/pages/use-teleport/teleport-connect.mdx
Labels: documentation, backport/branch/v10

#12763 tsh: tctl: Add basic session ls functionality
  lib/client/api.go
  lib/client/client.go
  lib/defaults/defaults.go
  lib/defaults/defaults_test.go
  tool/common/common.go
  tool/tctl/common/recordings_command.go
  tool/tctl/main.go
  tool/tsh/help.go
  tool/tsh/kube.go
  tool/tsh/mfa.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, tctl, c-bi, backport/branch/v10

#15324 [v10] Add "RDP connection fail" section to desktop access troubleshooting docs
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport

#15325 [v9] Add "RDP connection fail" section to desktop access troubleshooting docs
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport

#15348 auditlog: fix panic during concurrent streams of the same session
  lib/events/auditlog.go
  lib/events/auditlog_test.go
  lib/events/complete.go
Labels: audit-log, backport

#14080 Use a getter/setter for reading the token value from the config
  docs/pages/setup/reference/config.mdx
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/ec2_test.go
  integration/helpers/instance.go
  integration/hsm/hsm_test.go
  integration/integration_test.go
  integration/proxy_helpers_test.go
  integration/proxy_tunnel_strategy_test.go
  lib/client/api_login_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service_test.go
  tool/teleport/common/teleport_test.go
  tool/tsh/db_test.go
  tool/tsh/tsh_test.go
Labels: tsh, backport/branch/v9, backport/branch/v10

#15344 Pick correct cert when signing Connect
  .drone.yml
  dronegen/mac.go
Labels: backport/branch/v10

#15373 [v9] Use a getter/setter for reading the token value from the config
  docs/pages/setup/reference/config.mdx
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/ec2_test.go
  integration/helpers.go
  integration/hsm/hsm_test.go
  integration/integration_test.go
  integration/proxy_helpers_test.go
  lib/client/api_login_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/service/cfg.go
  lib/service/connect.go
  tool/teleport/common/teleport_test.go
  tool/tsh/db_test.go
  tool/tsh/tsh_test.go
Labels: documentation, tsh, backport

#15372 [v10] Use a getter/setter for reading the token value from the config
  docs/pages/setup/reference/config.mdx
  integration/app_integration_test.go
  integration/db_integration_test.go
  integration/ec2_test.go
  integration/helpers.go
  integration/hsm/hsm_test.go
  integration/integration_test.go
  integration/proxy_helpers_test.go
  integration/proxy_tunnel_strategy_test.go
  lib/client/api_login_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service_test.go
  tool/teleport/common/teleport_test.go
  tool/tsh/db_test.go
  tool/tsh/tsh_test.go
Labels: documentation, tsh, backport

#15365 Update last report date for SOC 2 report
  docs/config.json
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#15340 [v10] Connect docs: Add section about insecure mode
  docs/pages/use-teleport/teleport-connect.mdx
Labels: documentation, backport

#15362 IP Address cloud faq update
  docs/pages/cloud/faq.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#14319 Documentation for AWS DynamoDB guide
  docs/config.json
  docs/img/database-access/guides/dynamodb-create-role-1.png
  docs/img/database-access/guides/dynamodb-create-role-2.png
  docs/img/database-access/guides/dynamodb-create-role-3.png
  docs/img/database-access/guides/dynamodb-federated-login.png
  docs/img/database-access/guides/dynamodb-select-iam-role.png
  docs/img/database-access/guides/dynamodb_cloud.png
  docs/img/database-access/guides/dynamodb_selfhosted.png
  docs/pages/database-access/guides/dynamodb.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, aws, backport/branch/v10

#15296 [v9] Machine ID docs: Trusted Cluster support
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport

#15270 [v10] backport #15012 (Add `teleport install systemd` command)
  lib/config/systemd.go
  lib/config/systemd_test.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
  tool/teleport/common/usage.go
Labels: backport, backport/branch/v10
