Repository gravitational/teleport, pull requests merged in 2022-11, with the labels that each got.

#17531 Move SAML connection validation after auth checks
  lib/auth/auth_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/saml.go
  lib/auth/saml_test.go
  lib/services/saml_test.go
Labels: security

#17940 Add file based locking to TBot
  lib/tbot/bot/destination.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_directory_test.go
  lib/tbot/config/destination_memory.go
  lib/tbot/tbot.go
Labels: machine-id, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17626 CircleCI Secure Joining
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  lib/auth/auth.go
  lib/auth/bot.go
  lib/auth/join.go
  lib/auth/join_circleci.go
  lib/auth/join_circleci_test.go
  lib/auth/join_github.go
  lib/auth/join_github_test.go
  lib/auth/register.go
  lib/circleci/circleci.go
  lib/circleci/token_source.go
  lib/circleci/token_source_test.go
  lib/circleci/token_validator.go
  lib/circleci/token_validator_test.go
  lib/githubactions/token_validator_test.go
  lib/service/service.go
  lib/system/signal.go
  lib/tbot/config/config.go
  lib/tbot/renew.go
  rfd/0050-join-methods.md
Labels: rfd, machine-id, backport/branch/v11

#17942 [v11] Remove reference to Ctrl+A prefix mode from FAQ
  docs/pages/faq.mdx
Labels: documentation, backport

#17988 docs spell fixes
  docs/pages/access-controls/guides/hardware-key-support.mdx
  docs/pages/database-access/guides/elastic.mdx
  docs/pages/machine-id/guides/host-certificate.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11

#17886 Proritize HTTP/1.1 over HTTP/2.
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#18002 [v11] Prioritize HTTP/1.1 over HTTP/2.
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
Labels: backport

#17992 Update CentOS 7 build to pull OpenSSL from GitHub instead of openssl.org
  build.assets/Dockerfile-centos7
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#17896 Add DeviceEvent and supporting constants
  api/proto/buf.yaml
  api/proto/teleport/legacy/types/events/devicetrust.proto
  api/types/constants.go
  api/types/events/devicetrust.pb.go
  lib/events/api.go
  lib/events/codes.go
Labels: audit-log

#18004 [v10] spell fixes
  docs/pages/database-access/guides/elastic.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport

#18003 [v11] docs spell fixes
  docs/pages/access-controls/guides/hardware-key-support.mdx
  docs/pages/database-access/guides/elastic.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport

#17984 [v9] Test `scard.rs` (#16606)
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/session_tracker.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/events/complete_test.go
  lib/services/local/sessiontracker.go
  lib/services/local/sessiontracker_test.go
  lib/services/sessiontracker.go
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/sessiontracker_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/servers.go
Labels: rdp, audit-log, backport, desktop-access

#17985 [v10] Test `scard.rs` (#16606)
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
Labels: rdp, backport, desktop-access

#17986 [v11] Test `scard.rs` (#16606)
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
Labels: rdp, backport, desktop-access

#17991 [v11] Handle private key policy errors for the web UI (#17928)
  api/client/proto/authservice.pb.go
  api/client/webclient/webconfig.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/utils/keys/policy.go
  api/utils/keys/policy_test.go
  lib/auth/password.go
  lib/modules/test.go
  lib/web/apiserver.go
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/ui/accountrecovery.go
  lib/web/ui/usertoken.go
Labels: backport

#16413 RFD 89: Merge Webapps into Teleport
  rfd/0089-merge-webapps.md
Labels: rfd

#18001 [v10] Prioritize HTTP/1.1 over HTTP/2.
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
Labels: backport

#18005 [v9] Prioritize HTTP/1.1 over HTTP/2.
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
Labels: backport

#17859 Fix msteams access plugin systemd unit
  examples/systemd/plugins/teleport-msteams.service
Labels: backport/branch/v10, backport/branch/v11

#18017 [v10] Backporting GCB test fixes into v10.
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/lint.yaml
  .cloudbuild/ci/unit-tests.yaml
Labels: backport

#17693 Azure AD user managed identity authentication for SQL server documentation
  docs/config.json
  docs/img/database-access/guides/sqlserver/azure-attach-managed-identity-vm.png
  docs/img/database-access/guides/sqlserver/azure-set-ad-admin.png
  docs/img/database-access/guides/sqlserver/azure-user-managed-identity.png
  docs/img/database-access/guides/sqlserver/cloud-sql-aad.png
  docs/img/database-access/guides/sqlserver/sql-aad.png
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport/branch/v11

#18018 [v9] Backporting GCB test fixes into v9.
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
Labels: backport

#17458 Add new audit event for DynamoDB protos
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
Labels: backport/branch/v11

#17978 [v11] Fix race condition in TestProxySSHJumpHost
  lib/auth/trustedcluster.go
Labels: backport

#17999 [11] Backport 17940 - TBot locking
  lib/tbot/bot/destination.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_directory_test.go
  lib/tbot/config/destination_memory.go
  lib/tbot/tbot.go
Labels: machine-id

#17996 [11] Backport 17626 - CircleCI Joining
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  lib/auth/auth.go
  lib/auth/bot.go
  lib/auth/join.go
  lib/auth/join_circleci.go
  lib/auth/join_circleci_test.go
  lib/auth/join_github.go
  lib/auth/join_github_test.go
  lib/auth/register.go
  lib/circleci/circleci.go
  lib/circleci/token_source.go
  lib/circleci/token_source_test.go
  lib/circleci/token_validator.go
  lib/circleci/token_validator_test.go
  lib/githubactions/token_validator_test.go
  lib/service/service.go
  lib/system/signal.go
  lib/tbot/config/config.go
  lib/tbot/renew.go
  rfd/0050-join-methods.md
Labels: rfd, backport, machine-id

#18045 [v11] Database access AWS RDS Proxy support (#17005)
  api/proto/teleport/legacy/types/types.proto
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  api/utils/aws/endpoint.go
  api/utils/aws/endpoint_test.go
  lib/config/database.go
  lib/config/database_test.go
  lib/configurators/databases/aws.go
  lib/configurators/databases/aws_test.go
  lib/configurators/databases/databases.go
  lib/services/database.go
  lib/services/database_test.go
  lib/services/matchers.go
  lib/srv/db/ca.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/cloud/meta.go
  lib/srv/db/cloud/meta_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/cloud/watchers/rds_proxy.go
  lib/srv/db/cloud/watchers/watcher.go
  lib/srv/db/cloud/watchers/watcher_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/auth_test.go
  lib/srv/db/common/errors.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh_test.go
Labels: tsh, database-access, backport

#17960 [v10] Standardize systemd LimitNOFILE
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
  assets/monitoring/teleport.service
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  examples/systemd/fips/teleport.service
  examples/systemd/machine-id/machine-id.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  vagrant/teleport.service
Labels: documentation, backport

#17949 RFD 91: streaming session playback
  lib/auth/clt.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/writer.go
  lib/web/desktop/playback.go
  rfd/0091-session-streaming.md
Labels: audit-log, rfd

#18042 [v11] Documentation for Azure Cache for Redis (Database Access) (#17387)
  docs/config.json
  docs/img/database-access/guides/azure/redis-cloud.png
  docs/img/database-access/guides/azure/redis-create-role-from-json.png
  docs/img/database-access/guides/azure/redis-self-hosted.png
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/azure-redis.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/includes/database-access/azure-assign-service-principal.mdx
  docs/pages/includes/database-access/azure-configure-service-principal.mdx
  docs/pages/includes/database-access/database-config.yaml
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport

#17699 [v11] [docs] Fix troubleshooting path to NTAuthCertificates
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport

#18006 Add callouts to docs and Helm values for Kubernetes 1.23+ on EKS
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport/branch/v10, backport/branch/v11

#17977 [v10] Fix race condition in TestProxySSHJumpHost
  lib/auth/trustedcluster.go
Labels: backport

#17965 Updates clipboard docs and test plan
  .github/ISSUE_TEMPLATE/testplan.md
  docs/pages/desktop-access/reference/clipboard.mdx
Labels: documentation, backport/branch/v11

#18066 Release 10.3.6
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#18039 Correct the guide to use correct `--format` value.
  docs/pages/database-access/guides/elastic.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11

#18067 [v11] For config v3, improve the error message when failing to connect to the auth service
  lib/service/connect.go
Labels: backport

#18033 [v11] Azure AD user managed identity authentication for SQL server documentation
  docs/config.json
  docs/img/database-access/guides/sqlserver/azure-attach-managed-identity-vm.png
  docs/img/database-access/guides/sqlserver/azure-set-ad-admin.png
  docs/img/database-access/guides/sqlserver/azure-user-managed-identity.png
  docs/img/database-access/guides/sqlserver/cloud-sql-aad.png
  docs/img/database-access/guides/sqlserver/sql-aad.png
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport

#17654 terraform cloud address example update
  examples/resources/terraform/terraform-user-role-cloud.tf
Labels: backport/branch/v10, backport/branch/v11

#16718 [v9] Fix logic on including GCP secret in Teleport-Cluster helm chart
  examples/chart/teleport-cluster/templates/deployment.yaml
Labels: helm, backport

#12298 Add some info about s3 arguments
  docs/pages/reference/backends.mdx
Labels: documentation, backport, backport/branch/v9, inactive, backport/branch/v10, backport/branch/v11

#17961 [v11] Standardize systemd LimitNOFILE
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
  assets/monitoring/teleport.service
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  examples/systemd/fips/teleport.service
  examples/systemd/machine-id/machine-id.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  vagrant/teleport.service
Labels: documentation, backport

#15507 Fix typo in fluentd guide
  docs/pages/management/guides/fluentd.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18083 [v11] terraform cloud address example update
  examples/resources/terraform/terraform-user-role-cloud.tf
Labels: backport

#18097 Fix caching of client credentials when users re-login to incorporate new attributes
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport/branch/v9, backport/branch/v8, backport/branch/v10, backport/branch/v11

#18084 [v10] terraform cloud address example update
  examples/resources/terraform/terraform-user-role-cloud.tf
Labels: backport

#18026 [v10] Make `scard::Client.ioctl` return an `Encode` (#16862)
  lib/srv/desktop/rdp/rdpclient/src/errors.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tests.rs
Labels: rdp, backport, desktop-access

#17170 Allow `tctl create` for nodes
  tool/tctl/common/resource_command.go
Labels: tctl

#18082 Helm repo add updates for k8s docs
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/management/guides/fluentd.mdx
  docs/pages/management/guides/teleport-operator.mdx
  docs/pages/try-out-teleport/local-kubernetes.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11

#18121 Mention responding to feedack in docs contributing guide
  docs/pages/contributing/documentation/how-to-contribute.mdx
Labels: documentation

#18111 Added 11/03 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#15704 Use camelcase for tctl sso configure github info
  tool/tctl/sso/configure/github.go
Labels: tctl, backport/branch/v10, backport/branch/v11

#18110 [v10] Fix caching of client credentials when users re-login to incorporate new attributes
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport

#18109 [v11] Fix caching of client credentials when users re-login to incorporate new attributes
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport

#18077 Fixes `TestListKube` when running in GitHub Actions
  lib/kube/proxy/testing/kube_server/kube_mock.go
  tool/tsh/kube_test.go
  tool/tsh/tsh_helper_test.go
Labels: kubernetes-access, tsh, backport/branch/v11

#18112 [v9] Fix caching of client credentials when users re-login to incorporate new attributes
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport

#18128 [v11] Helm repo add updates for k8s docs
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/management/guides/fluentd.mdx
  docs/pages/management/guides/teleport-operator.mdx
  docs/pages/try-out-teleport/local-kubernetes.mdx
Labels: documentation, backport

#18106 Bump cloud version to 10.3.6
  docs/config.json
Labels: documentation, backport/branch/v10, backport/branch/v11

#17798 Machine ID GitHub Actions guide
  docs/config.json
  docs/img/machine-id/github-actions.png
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport/branch/v11

#18081 [v11] Add callouts to docs and Helm values for Kubernetes 1.23+ on EKS
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport

#18135 [v11] Fixes TestListKube when running in Github Actions (#18077)
  lib/kube/proxy/testing/kube_server/kube_mock.go
  tool/tsh/kube_test.go
  tool/tsh/tsh_helper_test.go
Labels: kubernetes-access, tsh, backport

#17653 Install script for database agents
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/types.pb.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/install_node.go
  lib/web/scripts/install_node_test.go
  lib/web/scripts/node-join/install.sh
Labels: discover, backport/branch/v11

#18086 Add a comment to the configure-ad script warning the user about extra whitespace
  lib/web/scripts/desktop/configure-ad.ps1
Labels: backport/branch/v10, backport/branch/v11

#18059 Get new CA for upcoming Azure Postgres CA rotation
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/auth_test.go
  lib/srv/db/server.go
Labels: database-access, db/postgres, azure, merge-for-v9, backport/branch/v8, merge-for-v10, merge-for-v11

#18028 [v11] Fix msteams access plugin systemd unit
  examples/systemd/plugins/teleport-msteams.service
Labels: backport

#17956 Run GCI as make fix-imports
  Makefile
  build.assets/Dockerfile
  build.assets/Makefile
  examples/go-client/main.go
  examples/workflows/main.go
  lib/auth/state_windows.go
  lib/auth/touchid/api_darwin.go
  lib/auth/webauthnwin/webauthn_windows.go
  lib/backend/dynamo/configure_test.go
  lib/bpf/bpf.go
  lib/bpf/bpf_test.go
  lib/bpf/command.go
  lib/bpf/disk.go
  lib/bpf/helper.go
  lib/bpf/network.go
  lib/client/terminal/terminal_windows.go
  lib/events/s3sessions/s3handler_test.go
  lib/pam/pam.go
  lib/restrictedsession/audit.go
  lib/restrictedsession/restricted.go
  lib/restrictedsession/restricted_test.go
  lib/restrictedsession/watcher.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/utils/agentconn/agent_windows.go
Labels: rdp, bpf, audit-log, desktop-access

#17970 Add note that 'tsh scp' always uses the SFTP protocol
  docs/pages/connect-your-client/tsh.mdx
Labels: documentation, backport/branch/v11

#16983 [V10] Backport #16876
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/serviceaccount_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, backport/branch/v9

#18108 adds note about ad cs
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18136 [v11] Bump cloud version to 10.3.6
  docs/config.json
Labels: documentation, backport

#17953 [v10] [Docs] Update to user.spec.roles
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/includes/role-spec.mdx
Labels: documentation, backport

#17954 [v11] [Docs] Update to user.spec.roles
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/includes/role-spec.mdx
Labels: documentation, backport

#17546 Remove the Jira Server Access Plugin guide
  CHANGELOG.md
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/includes/access-request-integrations.mdx
  docs/pages/reference/helm-reference/teleport-plugin-jira.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18141 [v11] Machine ID GitHub Actions guide
  docs/config.json
  docs/img/machine-id/github-actions.png
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport

#17096 [v10] Add documentation for Slack Helm chart
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/reference/helm-reference.mdx
  docs/pages/reference/helm-reference/teleport-plugin-slack.mdx
  examples/resources/plugins/teleport-slack-helm.yaml
Labels: documentation, backport

#17921 [v11] [Docs] remove apostrophe on non-possesive 'IDs'
  examples/resources/plugins/teleport-msteams.toml
  lib/web/apiserver_test.go
Labels: backport

#18180 Update previews page
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#17552 Allow users to specify default values for Kubernetes impersonated user, groups and namespace
  lib/kube/kubeconfig/kubeconfig.go
  lib/kube/kubeconfig/kubeconfig_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: kubernetes-access, tsh, backport/branch/v11

#18185 [v11] Allow users to specify default values for Kubernetes impersonated user, groups and namespace
  lib/kube/kubeconfig/kubeconfig.go
  lib/kube/kubeconfig/kubeconfig_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: kubernetes-access, tsh, backport

#17436 Add in app access connection monitoring.
  integration/appaccess/appaccess_test.go
  integration/appaccess/fixtures.go
  integration/appaccess/pack.go
  integration/helpers/usercreds.go
  lib/service/service.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
Labels: application-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17891 Update proxy db message to give other option for connecting
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: tsh, database-access, backport/branch/v10, backport/branch/v11

#18107 docs: mention that port is required in ldap addr
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18075 [v11] Correct the guide to use correct `--format` value.
  docs/pages/database-access/guides/elastic.mdx
Labels: documentation, backport

#18029 [v10] Fix msteams access plugin systemd unit
  examples/systemd/plugins/teleport-msteams.service
Labels: backport

#18126 [v11] fix test alpn proxy http proxy basic auth dial flakiness
  integration/helpers/instance.go
  integration/helpers/proxy.go
  integration/proxy/proxy_test.go
Labels: backport

#18148 [v10] Add a comment to the configure-ad script warning the user about extra whitespace
  lib/web/scripts/desktop/configure-ad.ps1
Labels: backport

#18088 [v11] Add some info about s3 arguments
  docs/pages/reference/backends.mdx
Labels: documentation, backport

#18192 [v11] Update proxy db message to give other option for connecting
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: tsh, backport

#18191 [v10] Update proxy db message to give other option for connecting
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: tsh, backport

#17922 [v10] [Docs] remove apostrophe on non-possesive 'IDs'
  examples/resources/plugins/teleport-msteams.toml
  lib/web/apiserver_test.go
Labels: backport

#18178 [v11] Remove the Jira Server Access Plugin guide
  CHANGELOG.md
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/includes/access-request-integrations.mdx
  docs/pages/reference/helm-reference/teleport-plugin-jira.mdx
Labels: documentation, backport

#18177 [v10] Remove the Jira Server Access Plugin guide
  CHANGELOG.md
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/includes/access-request-integrations.mdx
  docs/pages/reference/helm-reference/teleport-plugin-jira.mdx
Labels: documentation, backport

#18198 [v9] docs: mention that port is required in ldap addr
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#18172 [v11] Get new CA for upcoming Azure Postgres CA rotation (#18059)
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/auth_test.go
  lib/srv/db/server.go
Labels: database-access, backport

#18200 [v10] docs: mention that port is required in ldap addr
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#18196 [v11] adds note about ad cs
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#18024 Update the version support table
  docs/pages/faq.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18197 [v9] adds note about ad cs
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#18023 [v11] Fix links in the teleport-cluster reference
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport

#18173 [v10] Get new CA for upcoming Azure Postgres CA rotation (#18059)
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/server.go
Labels: database-access, backport

#18174 [v9] Get new CA for upcoming Azure Postgres CA rotation (#18059)
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/server.go
Labels: database-access, backport

#18147 [v11] Add a comment to the configure-ad script warning the user about extra whitespace
  lib/web/scripts/desktop/configure-ad.ps1
Labels: backport

#18175 [v8] Get new CA for upcoming Azure Postgres CA rotation (#18059)
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/server.go
Labels: database-access, backport

#18096 [v9] Fix typo in fluentd guide
  docs/pages/setup/guides/fluentd.mdx
Labels: documentation, backport

#18095 [v11] Fix typo in fluentd guide
  docs/pages/management/guides/fluentd.mdx
Labels: documentation, backport

#18089 [v10] Add some info about s3 arguments
  docs/pages/reference/backends.mdx
Labels: documentation, backport

#18091 [v9] Add some info about s3 arguments
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport

#18094 [v10] Fix typo in fluentd guide
  docs/pages/management/guides/fluentd.mdx
Labels: documentation, backport

#18190 Remove references to party initiated limits for SAML
  docs/pages/access-controls/sso/adfs.mdx
  docs/pages/access-controls/sso/okta.mdx
  docs/pages/access-controls/sso/one-login.mdx
  examples/resources/adfs-connector.yaml
  examples/resources/onelogin-connector.yaml
Labels: documentation, backport/branch/v10, backport/branch/v11

#18085 [v10] update v10 docs version
  docs/config.json
Labels: documentation, backport

#18134 Restore the Ansible Server Access guide
  docs/config.json
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/ansible.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18218 [v11] Update the version support table
  docs/pages/faq.mdx
Labels: documentation, backport

#18087 [v9] Update 9 docs version
  docs/config.json
Labels: documentation, backport

#18132 [v10] Use camelcase for tctl sso configure github info
  tool/tctl/sso/configure/github.go
Labels: tctl, backport

#17628 [docs] EKS & AKS auto-discovery docs
  docs/config.json
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/includes/kubernetes-access/kubernetes-config.yaml
  docs/pages/kubernetes-access/discovery.mdx
  docs/pages/kubernetes-access/discovery/aws.mdx
  docs/pages/kubernetes-access/discovery/azure.mdx
  docs/pages/kubernetes-access/discovery/includes/step-description.mdx
  docs/pages/kubernetes-access/discovery/includes/troubleshooting.mdx
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/reference/config.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport/branch/v11

#18133 [v11] Use camelcase for tctl sso configure github info
  tool/tctl/sso/configure/github.go
Labels: tctl, backport

#18239 Fix flaky basic auth dialer test
  integration/helpers/proxy.go
  integration/helpers/trustedclusters.go
  integration/proxy/proxy_test.go
Labels: backport/branch/v10, backport/branch/v11

#18236 Skip SSH tracing if backend doesn't support it
  api/observability/tracing/ssh/client.go
  api/observability/tracing/ssh/client_test.go
  api/observability/tracing/ssh/ssh_test.go
Labels: backport/branch/v10, backport/branch/v11

#18243 [v11] [docs] EKS & AKS auto-discovery docs
  docs/config.json
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/includes/kubernetes-access/kubernetes-config.yaml
  docs/pages/kubernetes-access/discovery.mdx
  docs/pages/kubernetes-access/discovery/aws.mdx
  docs/pages/kubernetes-access/discovery/azure.mdx
  docs/pages/kubernetes-access/discovery/includes/step-description.mdx
  docs/pages/kubernetes-access/discovery/includes/troubleshooting.mdx
  docs/pages/kubernetes-access/guides.mdx
  docs/pages/reference/config.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport

#18201 [v9] Add option to disable the `ServiceAccount` creation for `teleport-kube-agent chart` (#16876) (#16983)
  docs/pages/setup/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport

#17833 Add Cassandra and ScyllaDB docs
  docs/config.json
  docs/img/database-access/guides/cassandra_cloud.png
  docs/img/database-access/guides/cassandra_keyspaces_cloud.png
  docs/img/database-access/guides/cassandra_keyspaces_slefhosted.png
  docs/img/database-access/guides/cassandra_selfhosted.png
  docs/img/database-access/guides/keyspaces/create-role-step1.png
  docs/img/database-access/guides/keyspaces/create-role-step2.png
  docs/img/database-access/guides/keyspaces/create-role-step3.png
  docs/pages/database-access/guides/aws-cassandra-keyspaces.mdx
  docs/pages/database-access/guides/cassandra-self-hosted.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, db/cassandra, backport/branch/v11

#17660 Connect: Set up tshd-initiated communication
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/proto/v1/tshd_events_service.proto
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/golang/v1/service_grpc.pb.go
  lib/teleterm/api/protogen/golang/v1/tshd_events_service.pb.go
  lib/teleterm/api/protogen/golang/v1/tshd_events_service_grpc.pb.go
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.js
  lib/teleterm/apiserver/apiserver.go
  lib/teleterm/apiserver/config.go
  lib/teleterm/apiserver/handler/handler_tshd_events.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/grpccredentials.go
  lib/teleterm/teleterm.go
Labels: backport/branch/v11

#17783 Create and Update database http endpoints
  api/types/database.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/databases.go
  lib/web/databases_test.go
  lib/web/ui/server.go
Labels: discover, backport/branch/v11

#18232 [v10] Remove references to party initiated limits for SAML
  docs/pages/access-controls/sso/adfs.mdx
  docs/pages/access-controls/sso/okta.mdx
  docs/pages/access-controls/sso/one-login.mdx
  examples/resources/adfs-connector.yaml
  examples/resources/onelogin-connector.yaml
Labels: documentation, backport

#18231 [v11] Remove references to party initiated limits for SAML
  docs/pages/access-controls/sso/adfs.mdx
  docs/pages/access-controls/sso/okta.mdx
  docs/pages/access-controls/sso/one-login.mdx
  examples/resources/adfs-connector.yaml
  examples/resources/onelogin-connector.yaml
Labels: documentation, backport

#18250 [v11] Add Cassandra and ScyllaDB docs (#17833)
  docs/config.json
  docs/img/database-access/guides/cassandra_cloud.png
  docs/img/database-access/guides/cassandra_keyspaces_cloud.png
  docs/img/database-access/guides/cassandra_keyspaces_slefhosted.png
  docs/img/database-access/guides/cassandra_selfhosted.png
  docs/img/database-access/guides/keyspaces/create-role-step1.png
  docs/img/database-access/guides/keyspaces/create-role-step2.png
  docs/img/database-access/guides/keyspaces/create-role-step3.png
  docs/pages/database-access/guides/aws-cassandra-keyspaces.mdx
  docs/pages/database-access/guides/cassandra-self-hosted.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport

#18219 [v9] Update the version support table
  docs/pages/faq.mdx
Labels: documentation, backport

#18195 [v10] adds note about ad cs
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#15530 Add Auditd docs
  docs/config.json
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/auditd.mdx
Labels: documentation, backport/branch/v10, merge-for-v11, backport/branch/v11

#17968 [v10] [Docs] Machine ID Host Certificate Support
  docs/config.json
  docs/pages/machine-id/guides/host-certificate.mdx
  docs/pages/machine-id/reference/configuration.mdx
Labels: documentation, backport

#18248 [v11] Skip SSH tracing if backend doesn't support it
  api/observability/tracing/ssh/client.go
  api/observability/tracing/ssh/client_test.go
  api/observability/tracing/ssh/ssh_test.go
Labels: backport

#18025 [v9] Make `scard::Client.ioctl` return an `Encode` (#16862)
  lib/srv/desktop/rdp/rdpclient/src/errors.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tests.rs
Labels: rdp, backport, desktop-access

#17969 [v11] [Docs] Machine ID Host Certificate Support
  docs/config.json
  docs/pages/machine-id/guides/host-certificate.mdx
  docs/pages/machine-id/reference/configuration.mdx
Labels: documentation, backport

#18160 Document in-page edits
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18257 [v11] Minor tweaks for GitHub Machine ID integration docs
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/faq.mdx
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport

#18270 [v11] Add Auditd docs
  docs/config.json
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/auditd.mdx
Labels: documentation, backport

#18247 [v10] Skip SSH tracing if backend doesn't support it
  api/observability/tracing/ssh/client.go
  api/observability/tracing/ssh/client_test.go
  api/observability/tracing/ssh/ssh_test.go
Labels: backport

#18280 Fix flaky Azure watcher test
  lib/services/matchers.go
  lib/srv/server/azure_watcher_test.go
Labels: backport/branch/v11

#18022 [v10] Simplifies logic of desktopIsActive (#17938)
  lib/web/servers.go
Labels: backport

#18233 Make TestTCP* tests in appaccess more deterministic.
  integration/appaccess/appaccess_test.go
  integration/appaccess/fixtures.go
  integration/appaccess/pack.go
  integration/helpers/instance.go
  lib/service/cfg.go
  lib/service/service.go
  lib/srv/app/server.go
  lib/srv/monitor.go
Labels: application-access

#18244 [v9] Block SFTP connections when moderated sessions are enforced
  lib/srv/ctx.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
Labels: backport

#18217 [v10] Update the version support table
  docs/pages/faq.mdx
Labels: documentation, backport

#18187 [v11] Add in app access connection monitoring.
  integration/appaccess/appaccess_test.go
  integration/appaccess/fixtures.go
  integration/appaccess/pack.go
  integration/helpers/instance.go
  integration/helpers/usercreds.go
  lib/service/cfg.go
  lib/service/service.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
  lib/srv/monitor.go
Labels: application-access, backport

#18281 Fix cron jobs updating teleport operator on v9
  .drone.yml
  dronegen/container_image_products.go
  dronegen/container_images_release_version.go
Labels: bug

#18249 Remove unused uid from session.upload event
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
Labels: backport/branch/v10, backport/branch/v11

#17635 Web API for getting database IAM policy
  api/types/database.go
  lib/cloud/aws/policy.go
  lib/cloud/aws/policy_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/errors.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/common/iam/aws_test.go
  lib/web/apiserver.go
  lib/web/databases.go
  lib/web/databases_test.go
Labels: database-access, discover, backport/branch/v11

#18253 [v11] Connect: Set up tshd-initiated communication
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/proto/v1/tshd_events_service.proto
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/golang/v1/tshd_events_service.pb.go
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.js
  lib/teleterm/apiserver/apiserver.go
  lib/teleterm/apiserver/config.go
  lib/teleterm/apiserver/handler/handler_tshd_events.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/grpccredentials.go
  lib/teleterm/teleterm.go
Labels: backport

#18204 Enable HTTPS_PROXY support in `tsh proxy ssh`
  api/constants/constants.go
  tool/tsh/proxy.go
Labels: tsh, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18292 Fix kernel version parsing on WSL2
  lib/utils/kernel.go
  lib/utils/kernel_test.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#18276 [v11] Document in-page edits
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation, backport
