Repository gravitational/teleport, pull requests merged in 2022-09, with the labels that each got.

#15918 [v8] Use regional STS endpoints for IAM join method
  docs/pages/setup/guides/joining-nodes-aws.mdx
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/register.go
  lib/auth/valid_sts_endpoints.go
  lib/cloud/aws/errors.go
  lib/utils/ec2.go
Labels: backport

#15755 [v10] NodeJoin script: fix when no labels are provided
  lib/web/scripts/node-join/install.sh
Labels: backport, discover

#15566 Add architecture guide for Machine ID
  docs/config.json
  docs/pages/machine-id/architecture.mdx
  docs/pages/machine-id/introduction.mdx
Labels: documentation, machine-id, backport/branch/v10

#16010 [v10] Fix a flaky operator test
  operator/controllers/resources/role_controller_test.go
  operator/controllers/resources/user_controller_test.go
Labels: backport

#16003 Restrict Google JSON credentials to the `service_account` type.
  lib/auth/oidc_google.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#15938 [v10] Remove deprecated upsert password endpoint (#15855)
  lib/auth/apiserver.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/tls_test.go
Labels: backport

#16020 [v10] Update on-prem/cloud version to 10.1.9
  docs/config.json
Labels: documentation, backport

#16011 [v10] Avoid wrongly filtering Yubikey4 devices
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport

#15987 Add support for `FileNamesInformation`
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#15669 ALPN connection upgrade for MySQL behind ALB
  constants.go
  integration/proxy_helpers_test.go
  integration/proxy_test.go
  lib/config/configuration.go
  lib/service/service.go
  lib/srv/alpnproxy/conn_upgrade.go
  lib/srv/alpnproxy/conn_upgrade_test.go
  lib/srv/alpnproxy/dialer.go
  lib/srv/alpnproxy/helpers_test.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
  lib/srv/db/mysql/test.go
  lib/utils/certs.go
  lib/utils/certs_test.go
  lib/web/apiserver.go
  lib/web/conn_upgrade.go
  lib/web/conn_upgrade_test.go
  tool/tsh/db.go
  tool/tsh/proxy.go
Labels: tsh, database-access, tls-routing, backport/branch/v9, backport/branch/v10

#16036 [v10] Add architecture guide for Machine ID
  docs/config.json
  docs/pages/machine-id/architecture.mdx
  docs/pages/machine-id/introduction.mdx
Labels: documentation, backport

#16022 Add an `is_empty` field to `FileSystemObject`
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/tdp/proto.go
  rfd/0067-desktop-access-file-system-sharing.md
Labels: rdp, rfd, desktop-access, backport/branch/v9, backport/branch/v10

#15962 [v10] backport #15653 (Add Access Request ID to response for UserContext )
  api/proto/teleport/legacy/types/types.proto
  api/types/session.go
  api/types/types.pb.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
  lib/web/ui/usercontext.go
Labels: backport

#15992 [v10] azure mysql postgres auto discovery watchers
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/db/cloud/users/memorydb.go
  lib/srv/db/cloud/watchers/azure.go
  lib/srv/db/cloud/watchers/elasticache.go
  lib/srv/db/cloud/watchers/memorydb.go
  lib/srv/db/cloud/watchers/rds.go
  lib/srv/db/cloud/watchers/redshift.go
  lib/srv/db/cloud/watchers/watcher.go
  lib/srv/db/cloud/watchers/watcher_test.go
  lib/srv/db/common/cloud.go
  lib/srv/db/common/constants.go
  lib/srv/db/server.go
  lib/srv/db/watcher.go
Labels: database-access, backport

#16017 [v10] Backport TLS routing Ping connection
  api/proto/teleport/legacy/types/types.proto
  api/types/networking.go
  api/types/types.pb.go
  integration/proxy_test.go
  lib/auth/middleware.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/defaults/defaults.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/alpnproxy/conn.go
  lib/srv/alpnproxy/conn_test.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
  lib/srv/db/common/interfaces.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/sqlserver/proxy.go
  lib/utils/tls.go
  rfd/0081-tls-ping.md
  tool/tsh/proxy.go
Labels: tsh, rfd, database-access, backport

#16055 Added 09/01 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#15972 Correct links to tracks
  docs/pages/try-out-teleport/browser-labs.mdx
Labels: documentation, backport/branch/v10

#16054 [v10] Add support for `FileNamesInformation`
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
Labels: rdp, backport, desktop-access

#16059 [v10] Add an `is_empty` field to `FileSystemObject`
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/tdp/proto.go
  rfd/0067-desktop-access-file-system-sharing.md
Labels: rdp, rfd, backport, desktop-access

#15947 Add retries on operation denied in fido2
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport/branch/v10

#15959 Add support for `--browser none` to `tctl sso test`.
  tool/tctl/sso/tester/command.go
Labels: tctl, backport-required, backport/branch/v10

#15413 ConnectionDiagnostics: SSH Tester
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/connection_diagnostic.go
  api/types/types.pb.go
  constants.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/native/native.go
  lib/auth/permissions.go
  lib/client/api.go
  lib/client/conntest/connection_tester.go
  lib/client/conntest/ssh.go
  lib/services/authority.go
  lib/services/connection_diagnostic.go
  lib/services/local/connection_diagnostic.go
  lib/services/role.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/web/apiserver_test.go
  lib/web/connection_diagnostic.go
  lib/web/ui/server.go
Labels: backport/branch/v10, discover

#16045 Make `tctl bots add` display the proxy address
  tool/tbot/main.go
  tool/tctl/common/bots_command.go
Labels: tctl, machine-id, backport/branch/v10

#15894 [v10] dronegen: Enable verbose logs for electron tooling on macOS
  .drone.yml
  dronegen/mac.go
Labels: backport

#16082 Add comment and import cycle proto linters
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/client/proto/joinservice.proto
  lib/teleterm/api/proto/buf.yaml
  proto/buf.yaml
Labels: backport/branch/v10

#16070 [v8] App Access: Support AWS Console for US GovCloud Partition (#13442)
  api/constants/constants.go
  api/types/app.go
  api/types/app_test.go
  lib/srv/app/cloud.go
  lib/srv/app/cloud_test.go
Labels: application-access, backport

#16069 [v9] App Access: Support AWS Console for US GovCloud Partition (#13442)
  api/constants/constants.go
  api/types/app.go
  api/types/app_test.go
  lib/srv/app/cloud.go
  lib/srv/app/cloud_test.go
Labels: application-access, backport

#16058 Forward flags to "tsh ssh" and "tsh aws"
  go.mod
  go.sum
  tool/tsh/aws.go
  tool/tsh/aws_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh

#16078 [v10] Correct links to tracks
  docs/pages/try-out-teleport/browser-labs.mdx
Labels: documentation, backport

#16092 [v10] Add comment and import cycle proto linters
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/client/proto/joinservice.proto
  lib/teleterm/api/proto/buf.yaml
  proto/buf.yaml
Labels: backport

#16099 Drop libudev-dev from buildbox dependencies
  build.assets/Dockerfile
Labels: backport/branch/v10

#16077 [v10] Fix username in example
  docs/pages/server-access/guides/host-user-creation.mdx
Labels: documentation, backport

#16102 [v10] Drop libudev-dev from buildbox dependencies
  build.assets/Dockerfile
Labels: backport

#15825 Fix outdated CHANGELOG links
  CHANGELOG.md
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#15851 Docs: Update Contributing Page
  docs/pages/contributing/documentation/how-to-contribute.mdx
Labels: documentation, backport/branch/v10

#15916 [v9] Use regional STS endpoints for IAM join method
  docs/pages/setup/guides/joining-nodes-aws-iam.mdx
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/register.go
  lib/auth/valid_sts_endpoints.go
  lib/utils/ec2.go
Labels: documentation, backport

#16030 [v10] Update Library for new systemd install
  docs/pages/deploy-a-cluster/open-source.mdx
  docs/pages/deploy-a-cluster/teleport-enterprise/getting-started.mdx
  docs/pages/management/admin/daemon.mdx
Labels: documentation, backport

#15915 [v10] Use regional STS endpoints for IAM join method
  docs/pages/management/guides/joining-nodes-aws-iam.mdx
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/register.go
  lib/auth/valid_sts_endpoints.go
  lib/utils/ec2.go
Labels: documentation, backport

#16110 [v10] Fix outdated CHANGELOG links
  CHANGELOG.md
Labels: backport

#16033 [v9] Update library for new systemd install (#15800)
  docs/pages/enterprise/getting-started.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/setup/admin/daemon.mdx
Labels: documentation, backport

#16089 [v10] Make `tctl bots add` display the proxy address
  tool/tbot/main.go
  tool/tctl/common/bots_command.go
Labels: tctl, backport, machine-id

#16101 Improve `TestPingConnection/ConcurrentReads` timeout handling
  lib/srv/alpnproxy/conn_test.go
Labels: backport/branch/v10

#16119 ran new images through trimage
  docs/img/database-access/guides/cockroachdb_cloud.png
  docs/img/database-access/guides/cockroachdb_selfhosted.png
Labels: documentation

#15434 Update user traits when renew session
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/tls_test.go
  lib/web/apiserver.go
  lib/web/sessions.go
Labels: backport/branch/v10

#16067 [v10] App Access: Support AWS Console for US GovCloud Partition (#13442)
  api/constants/constants.go
  api/types/app.go
  api/types/app_test.go
  lib/srv/app/cloud.go
  lib/srv/app/cloud_test.go
Labels: application-access, backport

#16094 [v10] Forward flags to "tsh ssh" and "tsh aws" (#16058)
  go.mod
  go.sum
  tool/tsh/aws.go
  tool/tsh/aws_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport

#16087 [v10] ConnectionDiagnostics: SSH Tester (#15413)
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/joinservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/connection_diagnostic.go
  api/types/types.pb.go
  constants.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/native/native.go
  lib/auth/permissions.go
  lib/client/api.go
  lib/client/conntest/connection_tester.go
  lib/client/conntest/ssh.go
  lib/services/authority.go
  lib/services/connection_diagnostic.go
  lib/services/local/connection_diagnostic.go
  lib/services/role.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/web/apiserver_test.go
  lib/web/connection_diagnostic.go
  lib/web/ui/server.go
Labels: backport

#16114 fix flaky TestProxyMakeConnectionHandler
  lib/srv/alpnproxy/proxy_test.go
Labels: flaky tests

#16086 [v10] Add support for `--browser none` to `tctl sso test`.
  tool/tctl/sso/tester/command.go
Labels: tctl, backport

#16129 Fix flaky TestHandlerConnectionUpgrade
  lib/web/conn_upgrade_test.go
Labels: flaky tests

#15768 Elasticsearch support
  go.mod
  go.sum
  lib/client/db/dbcmd/dbcmd.go
  lib/defaults/defaults.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/access_test.go
  lib/srv/db/common/role/role.go
  lib/srv/db/elasticsearch/engine.go
  lib/srv/db/elasticsearch/test.go
  lib/srv/db/elasticsearch_test.go
  lib/srv/db/server.go
  tool/tsh/db.go
  tool/tsh/proxy.go
Labels: tsh, database-access

#16041 [v9] Restrict Google JSON credentials to the `service_account` type.
  lib/auth/oidc_google.go
Labels: backport

#16042 [v10] Restrict Google JSON credentials to the `service_account` type.
  lib/auth/oidc_google.go
Labels: backport

#14948 Auditd integration
  go.mod
  go.sum
  lib/auditd/auditd.go
  lib/auditd/auditd_linux.go
  lib/auditd/auditd_test.go
  lib/auditd/common.go
  lib/service/service.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/srv/termhandlers.go
  lib/sshutils/server.go
Labels: backport/branch/v10

#16081 implements `IRP_MJ_LOCK_CONTROL`
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#16085 [v10] Add retries on operation denied in fido2
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport

#16056 bumps rust to 1.63.0, fixes linting errors
  build.assets/Makefile
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#15641 Fix running ssh command on multiple nodes with mfa per session
  lib/client/api.go
  lib/client/client.go
  lib/client/export.go
  lib/client/mfa.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport/branch/v9, backport/branch/v10

#15996 Add section on teleport.cluster.local
  docs/pages/management/admin/troubleshooting.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16120 Docs Spell fixes
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/machine-id/architecture.mdx
  docs/pages/management/guides/teleport-operator.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16115 [v10] Docs: Update Contributing Page
  docs/pages/contributing/documentation/how-to-contribute.mdx
Labels: documentation, backport

#15726 [v9] Update buildbox to push to amazon ECR
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/lint.yaml
  .cloudbuild/ci/unit-tests.yaml
  .drone.yml
  build.assets/Dockerfile-arm
  build.assets/Dockerfile-arm-fips
  build.assets/Dockerfile-teleterm
  build.assets/Makefile
  docker/Dockerfile
  dronegen/buildbox.go
Labels: backport

#15719 [v10] Update teleport plugin docs for Amazon ECR Public
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/management/guides/fluentd.mdx
Labels: documentation, backport

#15720 [v9] Update teleport plugin docs for Amazon ECR Public
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/setup/guides/fluentd.mdx
Labels: documentation, backport

#16122 [v10] Update user traits when renew session
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/tls_test.go
  lib/web/apiserver.go
  lib/web/sessions.go
Labels: backport

#15725 [v10] Update buildbox to push to ECR
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/lint.yaml
  .cloudbuild/ci/unit-tests.yaml
  .drone.yml
  build.assets/Dockerfile-arm
  build.assets/Dockerfile-arm-fips
  build.assets/Dockerfile-teleterm
  build.assets/Makefile
  docker/Dockerfile
  dronegen/buildbox.go
Labels: backport

#16155 [v9] Add section on teleport.cluster.local
  docs/pages/setup/admin/troubleshooting.mdx
Labels: documentation, backport

#16153 [v10] Add section on teleport.cluster.local
  docs/pages/management/admin/troubleshooting.mdx
Labels: documentation, backport

#16141 [v10] Add OS compatibility checker
  .cloudbuild/ci/os-compatibility-test.yaml
  Makefile
  build.assets/Dockerfile-centos7
  build.assets/build-test-compat.sh
Labels: backport

#16140 [v10] Auditd integration
  go.mod
  go.sum
  lib/auditd/auditd.go
  lib/auditd/auditd_linux.go
  lib/auditd/auditd_test.go
  lib/auditd/common.go
  lib/service/service.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/srv/termhandlers.go
  lib/sshutils/server.go
Labels: backport

#16173 [v10] Rename web JSON field names and wrap traits (#14611)
  lib/web/ui/user.go
  lib/web/users.go
  lib/web/users_test.go
Labels: backport

#15713 [v10] Replace quay.io with amazon ECR where appropriate
  .cloudbuild/ci/doc-tests.yaml
  README.md
  assets/loadtest/Makefile
  assets/loadtest/k8s/Makefile
  build.assets/Makefile
  docker/sshd/Dockerfile
  docker/teleport-ent-quickstart.yml
  docker/teleport-lab.yml
  docker/teleport-quickstart.yml
  docs/config.json
  docs/pages/deploy-a-cluster/teleport-enterprise/getting-started.mdx
  docs/pages/includes/enterprise/docker-images.mdx
  docs/pages/installation.mdx
  docs/pages/management/guides/docker.mdx
  docs/preflight.md
  operator/README.md
Labels: documentation, backport

#15890 [v10] Generalize private keys in tsh (PIV integration)
  api/client/credentials_test.go
  api/identityfile/identityfile.go
  api/profile/profile.go
  api/utils/keypaths/keypaths.go
  api/utils/keys/privatekey.go
  api/utils/keys/privatekey_test.go
  api/utils/keys/signer.go
  api/utils/sshutils/ppk/ppk.go
  api/utils/sshutils/ppk/ppk_test.go
  api/utils/sshutils/ssh.go
  integration/helpers.go
  integration/integration_test.go
  lib/auth/auth_with_roles_test.go
  lib/auth/init.go
  lib/auth/native/native.go
  lib/auth/testauthority/testauthority.go
  lib/client/api.go
  lib/client/client.go
  lib/client/conntest/ssh.go
  lib/client/db/database_certificates.go
  lib/client/identityfile/identity.go
  lib/client/identityfile/identity_test.go
  lib/client/interfaces.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/keystore.go
  lib/client/keystore_test.go
  lib/client/weblogin_test.go
  lib/kube/kubeconfig/kubeconfig.go
  lib/kube/kubeconfig/kubeconfig_test.go
  lib/srv/db/access_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/test.go
  lib/srv/db/proxyserver.go
  lib/tbot/config/configtemplate.go
  lib/tbot/config/configtemplate_cockroach.go
  lib/tbot/config/configtemplate_identity.go
  lib/tbot/config/configtemplate_kubernetes.go
  lib/tbot/config/configtemplate_mongo.go
  lib/tbot/config/configtemplate_tls.go
  lib/tbot/identity/identity.go
  lib/teleterm/apiserver/apiserver.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/gateway/gateway.go
  lib/tlsca/parsegen.go
  lib/web/desktop.go
  lib/web/terminal.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
  tool/tctl/sso/tester/command.go
  tool/tsh/app.go
  tool/tsh/db_test.go
  tool/tsh/kube.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: kubernetes-access, tsh, tctl, database-access, backport, desktop-access, machine-id

#15593 RFD 83: Host cert support in Machine ID
  rfd/0083-machine-id-host-certs.md
Labels: rfd

#16180 [v10] upgrade notifications
  api/types/cluster_alert.go
  lib/auth/auth.go
  lib/auth/init.go
  lib/client/api.go
  lib/client/client.go
  lib/services/local/status.go
  lib/services/status.go
  lib/utils/retry.go
  lib/versioncontrol/github/github.go
  lib/versioncontrol/github/github_test.go
  lib/versioncontrol/versioncontrol.go
  lib/versioncontrol/versioncontrol_test.go
  tool/tctl/common/alert_command.go
  tool/tsh/tsh.go
Labels: tsh, tctl, backport

#15978 Update the CockroachDB logo in our guide
  docs/img/database-access/guides/cockroachdb_cloud.png
  docs/img/database-access/guides/cockroachdb_selfhosted.png
Labels: documentation, backport/branch/v10

#16172 Release 10.2.0
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#16186 Update Helm snapshots when updating version
  Makefile
Labels: backport/branch/v10

#15932 [v10] Add a guide to Desktop Access Directory Sharing
  docs/config.json
  docs/img/desktop-access/share.png
  docs/img/desktop-access/shared-dir.png
  docs/pages/desktop-access/directory-sharing.mdx
  docs/pages/desktop-access/rbac.mdx
Labels: documentation, backport

#16057 Add serialization of writes to `known_hosts` file.
  go.mod
  go.sum
  lib/client/keystore.go
  lib/client/keystore_test.go
Labels: tsh, backport/branch/v9, backport/branch/v10

#16157 Remove the "." from the end of the auth token generated by "tctl tokens add" command
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
Labels: tctl, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16148 [v10] Fix running ssh command on multiple nodes with mfa per session
  lib/client/api.go
  lib/client/client.go
  lib/client/export.go
  lib/client/mfa.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport

#15770 [v9] backports for 13630 14267 14959 15289 15364 15743 (directory sharing)
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_nop.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/flags.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/path.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
  lib/srv/desktop/tdp/proto.go
  lib/srv/desktop/windows_server.go
  rfd/0067-desktop-access-file-system-sharing.md
Labels: rdp, rfd, backport, desktop-access

#16152 [v10] bumps rust to 1.63.0, fixes linting errors (#16056)
  build.assets/Makefile
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
Labels: rdp, backport, desktop-access

#16136 removes `rdpdr/mod.rs` in favor of `rdpdr.rs`
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10

#16183 Reduce the severity of the upgrade alert to 'info'
  lib/auth/auth.go
Labels: backport/branch/v10

#16194 [v10] Update the CockroachDB logo in our guide
  docs/img/database-access/guides/cockroachdb_cloud.png
  docs/img/database-access/guides/cockroachdb_selfhosted.png
Labels: documentation, backport

#16212 [v9] Add serialization of writes to `known_hosts` file.
  go.mod
  go.sum
  lib/client/keystore.go
  lib/client/keystore_test.go
Labels: tsh, backport

#16203 [v10] Add serialization of writes to `known_hosts` file.
  go.mod
  go.sum
  lib/client/keystore.go
  lib/client/keystore_test.go
Labels: tsh, backport

#16127 fixup untrusted cert errors
  lib/reversetunnel/transport.go
  lib/service/connect.go
  lib/utils/errors.go
  tool/tctl/common/tctl.go
Labels: tctl, error-msg

#16221 changelog: fix moderated sessions typo
  CHANGELOG.md
Labels: backport/branch/v10

#14809 Change "yml" to "yaml"
  docs/pages/server-access/guides/host-user-creation.mdx
Labels: documentation, docs-minor-tweak

#13728 Add documentation for MatterMost Helm chart
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/reference/helm-reference.mdx
  docs/pages/reference/helm-reference/teleport-plugin-mattermost.mdx
  examples/resources/plugins/teleport-mattermost-helm-cloud.yaml
  examples/resources/plugins/teleport-mattermost-helm-self.yaml
Labels: documentation

#16192 Correct cluster auth preference dynamic example
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
Labels: documentation, backport/branch/v10

#16246 [v10] Correct cluster auth preference dynamic example
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
Labels: documentation, backport

#16015 [v10] Add validation for hostname read from EC2
  lib/service/service.go
  lib/utils/utils.go
  lib/utils/utils_test.go
Labels: backport

#16016 [v9] Add validation for hostname read from EC2
  lib/service/service.go
  lib/utils/utils.go
  lib/utils/utils_test.go
Labels: backport

#16130 fix tctl auth server flag
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
  tool/tsh/tctl_test.go
Labels: bug, tsh, tctl, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16249 Added 09/08 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#16256 [v10] Calculate shasums of TCon Linux OS packages
  .drone.yml
  dronegen/tag.go
Labels: backport

#16255 [v10] fix tctl auth server flag
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
  tool/tsh/tctl_test.go
Labels: tsh, tctl, backport

#16240 [v8] Backport #16157
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
Labels: tctl, backport

#16260 [v9] fix tctl auth server flag
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
  tool/tsh/tctl_test.go
Labels: tsh, tctl, backport

#16177 [v10] Change base image for os compatibility check.
  .cloudbuild/ci/os-compatibility-test.yaml
Labels: backport

#16262 [v9] Add OS compatibility checker (#16141)
  .cloudbuild/ci/os-compatibility-test.yaml
  Makefile
  build.assets/Dockerfile-centos7
  build.assets/build-test-compat.sh
Labels: backport

#16189 [v10] Update Helm snapshots when updating version
  Makefile
Labels: backport

#16227 adds `test_scard_ioctl_accessstartedevent`
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
Labels: rdp, desktop-access

#16238 [v10] Backport #16157
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
Labels: tctl, backport

#16239 [v9] Backport #16157
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
Labels: tctl, backport

#16272 [v10] Categorize Teleport Connect linux builds correctly
  .drone.yml
  dronegen/tag.go
Labels: backport

#15903 [v9] docs: Add missing commands key to dynamic labels in reference
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport

#16113 Wrap `desktopplayback` endpoint with `WithClusterAuth` rather than `WithAuth`
  lib/web/apiserver.go
  lib/web/desktop_playback.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#15921 [v10] Add documentation for Jira Helm chart
  docs/config.json
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-cloud.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/reference/helm-reference/teleport-plugin-jira.mdx
  examples/resources/plugins/teleport-jira-helm-cloud.yaml
  examples/resources/plugins/teleport-jira-helm-self.yaml
Labels: documentation, backport

#16211 [v10] Reduce the severity of the upgrade alert to 'info'
  lib/auth/auth.go
Labels: backport

#14073 Update sso.mdx
  docs/pages/access-controls/sso.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16271 Unhide tctl alert create
  tool/tctl/common/alert_command.go
Labels: tctl, backport/branch/v10

#16283 Release 10.2.1
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#16214 [v9] backport #15987 #16022 #16056 #16081 #16136
  build.assets/Makefile
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/tdp/proto.go
  rfd/0067-desktop-access-file-system-sharing.md
Labels: rdp, rfd, backport, desktop-access

#16298 [auto] Update AMI IDs for 10.2.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#16300 Tweak TestAgentForward
  lib/srv/regular/sshserver_test.go
Labels: backport/branch/v10

#16222 [v10] changelog: fix moderated sessions typo
  CHANGELOG.md
Labels: backport

#16304 [v10] Tweak TestAgentForward
  lib/srv/regular/sshserver_test.go
Labels: backport

#16313 Update on-prem docs version
  docs/config.json
Labels: documentation, backport

#16294 [v10] docs: Add missing commands key to dynamic labels in reference
  docs/pages/reference/config.mdx
Labels: documentation, backport

#15906 [v8] Update docs Teleport version
  docs/config.json
Labels: documentation

#16166 [v10] spell fixes
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/machine-id/architecture.mdx
  docs/pages/management/guides/teleport-operator.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport

#14780 Remove SSH from Teleport SystemD description
  examples/systemd/teleport.service
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#16277 Adds warning about directories blocked from being shared
  docs/pages/desktop-access/directory-sharing.mdx
Labels: documentation, backport/branch/v10

#14908 Clarify access denied due to Teleport role permission
  lib/services/role.go
Labels: database-access, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16075 Add /webapi/sites/:site/alerts endpoint to the apiserver
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport/branch/v10

#16331 [v10] Clarify access denied due to Teleport role permission
  lib/services/role.go
Labels: backport

#16219 Change caching resolver to return a copy of cached data
  lib/reversetunnel/resolver.go
  lib/reversetunnel/resolver_test.go
Labels: bug

#16269 operator: Fix flaky drift tests (#15815)
  operator/controllers/resources/role_controller_test.go
  operator/controllers/resources/suite_test.go
  operator/controllers/resources/user_controller_test.go
Labels: flaky tests, backport/branch/v10

#16321 [v9] Fix clippy warnings in roletester
  lib/datalog/roletester/build.rs
  lib/datalog/roletester/src/role_tester.rs
Labels: backport

#16328 [v10] Adds warning about directories blocked from being shared
  docs/pages/desktop-access/directory-sharing.mdx
Labels: documentation, backport

#16243 helm: support Kubernetes 1.25
  examples/chart/teleport-cluster/templates/psp.yaml
  examples/chart/teleport-cluster/values.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, backport/branch/v10

#16273 [v9] Categorize Teleport Connect linux builds correctly
  .drone.yml
  dronegen/tag.go
Labels: backport

#16292 [v10] Wrap `desktopplayback` endpoint with `WithClusterAuth` rather than `WithAuth`
  lib/web/apiserver.go
  lib/web/desktop_playback.go
Labels: backport

#16302 Rephrase docs on moderated sessions backward compatibility
  docs/pages/access-controls/guides/moderated-sessions.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16293 [v9] Wrap desktopplayback endpoint with WithClusterAuth rather than WithAuth
  lib/web/apiserver.go
  lib/web/desktop_playback.go
Labels: backport

#16213 [v10] backport #16136 and #16151
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
Labels: rdp, backport, desktop-access

#16123 Nodes use FIPS STS endpoints for IAM join method when in FIPS mode
  lib/auth/join_iam.go
  lib/auth/register.go
  lib/auth/sts_endpoints.go
  lib/auth/valid_sts_endpoints.go
  lib/service/connect.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#11675 Update install-linux.mdx for AWS Linux
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport/branch/v10

#16362 [v10] Fix TestTokenGeneration flakiness
  lib/web/apiserver_test.go
Labels: backport

#16320 Remove unused `backend` var in `dynamoevents.go`
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/service/service.go
  lib/service/service_test.go
Labels: audit-log

#16340 updates changelog to document when rdp licensing negotiation was added
  CHANGELOG.md
Labels: backport

#16254 Document `tbot configure`
  docs/pages/machine-id/reference/cli.mdx
Labels: documentation, machine-id, backport/branch/v10

#16373 [v10] Document `tbot configure`
  docs/pages/machine-id/reference/cli.mdx
Labels: documentation, backport

#16303 IAM join method docs improvements
  docs/pages/management/guides/joining-nodes-aws-iam.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16355 [v8] Change caching resolver to return a copy of cached data
  lib/reversetunnel/resolver.go
  lib/reversetunnel/resolver_test.go
Labels: backport
