Repository gravitational/teleport, pull requests merged in 2022-02, with the labels that each got.

#9990 Documentation update for Redshift auto discovery support
  docs/img/database-access/guides/redshift/cluster-endpoint@2x.png
  docs/img/database-access/guides/redshift/cluster-id@2x.png
  docs/img/database-access/guides/redshift/cluster-user-db@2x.png
  docs/img/database-access/iam@2x.png
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/reference/aws.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/database-access/attach-iam-policies.mdx
  docs/pages/setup/reference/config.mdx
  docs/testplan.md
Labels: documentation

#9998 backport #9609 to branch/v8
  integration/integration_test.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/services/authority.go
  lib/services/trust.go
  lib/services/watcher.go
  lib/services/watcher_test.go
Labels: backport

#9999 [v7]backport #9609
  integration/integration_test.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/services/authority.go
  lib/services/trust.go
  lib/services/watcher.go
  lib/services/watcher_test.go
Labels: backport

#9885 Updated the description of the location of the built binaries
  README.md
Labels: documentation

#10060 Clarify token.file usage in server access getting started guide.
  docs/pages/server-access/getting-started.mdx
Labels: documentation

#10005 [v8] Enable canned ACL for S3 (#9042)
  constants.go
  docs/pages/setup/reference/backends.mdx
  lib/events/s3sessions/s3handler.go
  lib/events/s3sessions/s3handler_test.go
  lib/events/s3sessions/s3stream.go
Labels: backport

#10004 [v8] Respect errors from UserInfo (#9951)
  lib/auth/oidc.go
  lib/auth/oidc_test.go
Labels: backport

#10074 Refactor database engines registration
  lib/srv/db/common/engines.go
  lib/srv/db/common/engines_test.go
  lib/srv/db/mongodb/engine.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/server.go
Labels: database-access

#9729 Add guide for Azure Postgres/MySQL database access
  docs/config.json
  docs/img/database-access/guides/azure/app-registrations@2x.png
  docs/img/database-access/guides/azure/created-identity@2x.png
  docs/img/database-access/guides/azure/managed-identities@2x.png
  docs/img/database-access/guides/azure/new-identity@2x.png
  docs/img/database-access/guides/azure/registered-app-secrets@2x.png
  docs/img/database-access/guides/azure/registered-app@2x.png
  docs/img/database-access/guides/azure/set-ad-admin@2x.png
  docs/img/database-access/guides/azure/vm-identity@2x.png
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/introduction.mdx
Labels: documentation, unlocks-potential

#10003 [v7] Respect errors from UserInfo (#9951)
  lib/auth/oidc.go
  lib/auth/oidc_test.go
Labels: backport

#10096 (v8) Add guide for Azure Postgres/MySQL database access
  docs/config.json
  docs/img/database-access/guides/azure/app-registrations@2x.png
  docs/img/database-access/guides/azure/created-identity@2x.png
  docs/img/database-access/guides/azure/managed-identities@2x.png
  docs/img/database-access/guides/azure/new-identity@2x.png
  docs/img/database-access/guides/azure/registered-app-secrets@2x.png
  docs/img/database-access/guides/azure/registered-app@2x.png
  docs/img/database-access/guides/azure/set-ad-admin@2x.png
  docs/img/database-access/guides/azure/vm-identity@2x.png
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/introduction.mdx
Labels: documentation, backport

#9709 Fix docker-compose Getting Started guide issues
  docker/sshd/scripts/generate-certs.sh
  docs/pages/getting-started/docker-compose.mdx
  docs/pages/includes/insecure-certificate.mdx
Labels: documentation

#10106 [v8] Modify verbiage on AWS CLI
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation, aws, backport

#10029 Modify verbiage on AWS CLI
  docs/pages/application-access/guides/aws-console.mdx
Labels: documentation, aws, backport-required, application-access

#9749 Add metric tracking number of Teleport agents joined to cluster
  docs/pages/setup/reference/metrics.mdx
  lib/auth/auth.go
  lib/defaults/defaults.go
  metrics.go
Labels: documentation

#10046 backport #9316 to branch/v6.2
  lib/auth/rotate.go
Labels: backport

#9698 Add teleport_reverse_tunnels_connected Prometheus metric
  docs/pages/setup/reference/metrics.mdx
  lib/reversetunnel/localsite.go
  metrics.go
Labels: documentation

#10073 [v7] Update S3 Canned ACL Docs
  docs/pages/setup/reference/backends.mdx
Labels: backport

#10072 Update S3 Canned ACL Docs
  docs/pages/setup/reference/backends.mdx
Labels: documentation

#10048 backport #9316 to branch/v8
  lib/auth/rotate.go
Labels: backport

#9812 [v8] Backport "helm: Allow setting issuer group for certificate in teleport-cluster (#9138)"
  docs/pages/kubernetes-access/helm/reference.mdx
  examples/chart/teleport-cluster/.lint/cert-manager.yaml
  examples/chart/teleport-cluster/templates/certificate.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: helm, backport

#9958 Dynamically resolve reverse tunnel address
  integration/restart_test.go
  lib/cache/cache.go
  lib/reversetunnel/agent.go
  lib/reversetunnel/agentpool.go
  lib/reversetunnel/rc_manager.go
  lib/reversetunnel/rc_manager_test.go
  lib/reversetunnel/resolver.go
  lib/reversetunnel/resolver_test.go
  lib/reversetunnel/track/tracker.go
  lib/reversetunnel/track/tracker_test.go
  lib/reversetunnel/transport.go
  lib/service/connect.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/utils/addr.go
  lib/utils/fncache.go
  lib/utils/fncache_test.go
  lib/utils/timed_counter.go
  lib/utils/workpool/workpool.go
  lib/utils/workpool/workpool_test.go
  tool/tctl/common/tctl.go
Labels: tctl, robustness

#10057 Remove broken links to /admin-guide/#public-addr
  docs/pages/setup/reference/config.mdx
Labels: documentation

#10009 RFD 51: X11 forwarding
  rfd/0051-x11-forwarding.md
Labels: tsh, rfd

#10122 Backward compatible kubernetes_labels behaviour for v3 and v4 roles
  lib/services/role.go
  lib/services/role_test.go
Labels: kubernetes, backport-required

#10128 [v7] Backward compatible kubernetes_labels behaviour for v3 and v4 roles
  lib/services/role.go
  lib/services/role_test.go
Labels: backport

#9868 RFD 49: desktop access clipboard
  rfd/0049-desktop-clipboard.md
Labels: rfd, desktop-access, needs-product-decision

#10127 [v8] Backward compatible kubernetes_labels behaviour for v3 and v4 roles
  lib/services/role.go
  lib/services/role_test.go
Labels: backport

#10118 Update version-check paths
  .drone.yml
Labels: backport-required

#10092 Update Documentation for GCP Cloud SQL Client Authentication
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
Labels: documentation, database-access

#10144 [auto] Update AMI IDs for 8.1.3
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#10117 Fixes DocTest CI
  .cloudbuild/ci/doc-tests.yaml
  CHANGELOG.md
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation

#9523 Add role option for record_desktop_session
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/services/presets.go
  lib/services/role.go
  lib/services/role_test.go
  lib/web/resources_test.go
Labels: desktop-access

#10151 [v6.2] Fix Doctests (#10117)
  .cloudbuild/ci/doc-tests.yaml
  CHANGELOG.md
Labels: documentation, backport

#9669 docs: Add extra commands and reference for AWS Managed AD to Desktop Access docs
  docs/img/desktop-access/aws-managed-ad.png
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, windows, aws, backport-required, desktop-access

#10139 backport #9958 to branch/v8
  integration/restart_test.go
  lib/cache/cache.go
  lib/reversetunnel/agent.go
  lib/reversetunnel/agentpool.go
  lib/reversetunnel/rc_manager.go
  lib/reversetunnel/rc_manager_test.go
  lib/reversetunnel/resolver.go
  lib/reversetunnel/resolver_test.go
  lib/reversetunnel/track/tracker.go
  lib/reversetunnel/track/tracker_test.go
  lib/reversetunnel/transport.go
  lib/service/connect.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/utils/addr.go
  lib/utils/fncache.go
  lib/utils/fncache_test.go
  lib/utils/timed_counter.go
  lib/utils/workpool/workpool.go
  lib/utils/workpool/workpool_test.go
  tool/tctl/common/tctl.go
Labels: backport

#10114 Modified FedRamp to FedRAMP in docs for proper acronym
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/adopters.mdx
  docs/pages/faq.mdx
Labels: documentation

#9400 Update Docker image tags in docs
  docs/pages/enterprise/getting-started.mdx
  docs/pages/includes/image.mdx
  docs/pages/installation.mdx
Labels: documentation, docs-minor-tweak

#9537 Document docs labels
  docs/pages/docs/best-practices.mdx
Labels: documentation

#9897 x11 forwarding
  .cloudbuild/scripts/cmd/unit-tests/main.go
  build.assets/Makefile
  lib/client/api.go
  lib/client/session.go
  lib/client/x11_session.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/forward/sshserver.go
  lib/srv/reexec.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/forward.go
  lib/sshutils/x11/auth.go
  lib/sshutils/x11/auth_test.go
  lib/sshutils/x11/conn.go
  lib/sshutils/x11/display.go
  lib/sshutils/x11/display_test.go
  lib/sshutils/x11/forward.go
  lib/sshutils/x11/forward_test.go
  tool/tsh/options.go
  tool/tsh/options_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, audit-log

#10165 Add desktop_clipboard role option
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/services/role.go
  lib/services/role_test.go
  lib/web/resources_test.go
Labels: desktop-access

#9976 Desktop Access: clipboard support
  Makefile
  lib/datalog/roletester/src/role_tester.rs
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/vchan.rs
  lib/srv/desktop/tdp/proto.go
  rfd/0049-desktop-clipboard.md
Labels: rdp, desktop-access

#10198 Backport #9907 to branch/v8
  docs/img/googleoidc/clientid-creation.png
  docs/img/googleoidc/clientid-data.png
  docs/img/googleoidc/consent-screen-1.png
  docs/img/googleoidc/consent-screen-2.png
  docs/img/googleoidc/domainwidedelegation.png
  docs/img/googleoidc/new-project.png
  docs/img/googleoidc/serviceacct-creation.png
  docs/img/googleoidc/serviceacct-key.png
  docs/img/googleoidc/serviceacct-uniqueid.png
  docs/pages/enterprise/sso/google-workspace.mdx
  examples/resources/gworkspace-connector-inline.yaml
  examples/resources/gworkspace-connector.yaml
Labels: backport

#10113 Update MariaDB docs
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/testplan.md
Labels: documentation

#8409 Clarify `tsh config` usage on Windows
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/vscode.mdx
Labels: documentation

#10183 Reconnect broken LDAP connections
  lib/services/reconciler.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/ldap.go
  lib/srv/desktop/windows_server.go
Labels: backport-required, desktop-access

#10150 [v7] Fix Doctests CI (#10117)
  .cloudbuild/ci/doc-tests.yaml
  CHANGELOG.md
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
Labels: documentation, backport

#10207 Add `Clipboard` to `userACL`
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: desktop-access

#10218 Expand cloud in production usage faq question
  docs/pages/cloud/faq.mdx
Labels: documentation, backport-required, cloud, docs-minor-tweak

#10221 [v8] Expand cloud in production usage faq question
  docs/pages/cloud/faq.mdx
Labels: documentation, backport

#10149 [v8] Fix Doctests CI (#10117)
  .cloudbuild/ci/doc-tests.yaml
  CHANGELOG.md
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/setup/reference/config.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation, backport

#10181 Remove Teleport DB Users only message for tctl users ls
  tool/tctl/common/user_command.go
Labels: tctl, backport-required

#10116 [v8] Modified FedRamp to FedRAMP in docs for proper acronym
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/adopters.mdx
  docs/pages/faq.mdx
Labels: documentation, backport

#10240 [v8] Remove Teleport DB Users only message for tctl users ls
  tool/tctl/common/user_command.go
Labels: backport

#10232 Clean up desktop session error logging
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/web/desktop.go
Labels: rdp, error-msg, desktop-access

#10219 docs: add steps for joining Windows Desktop Service to a cloud cluster
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, desktop-access

#9402 [v8 backport] Update Docker image tags in docs
  docs/pages/enterprise/getting-started.mdx
  docs/pages/includes/image.mdx
  docs/pages/installation.mdx
Labels: documentation

#9401 [v7 backport] Update Docker image tags in docs
  docs/pages/enterprise/getting-started.mdx
  docs/pages/includes/image.mdx
  docs/pages/installation.mdx
Labels: documentation

#10084 Use an apt-key alternative in install instructions
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/installation.mdx
  docs/pages/server-access/getting-started.mdx
Labels: documentation

#10155 Make our docs guidance discoverable
  docs/config.json
  docs/pages/contributing/documentation.mdx
  docs/pages/contributing/documentation/how-to-contribute.mdx
  docs/pages/contributing/documentation/issues.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/contributing/documentation/style-guide.mdx
  docs/pages/docs.mdx
  docs/pages/docs/best-practices.mdx
Labels: documentation

#10187 [6.1] Fix/remove dead links
  CHANGELOG.md
  docs/pages/admin-guide.mdx
Labels: documentation

#10186 [6.0] Fix/remove dead links
  CHANGELOG.md
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/admin-guide.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/production.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#10185 [5.0] Fix/remove dead links
  CHANGELOG.md
  docs/pages/admin-guide.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/production.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#10184 [4.4] Fix/remove dead links
  docs/pages/admin-guide.mdx
  docs/pages/aws-oss-guide.mdx
  docs/pages/index.mdx
  docs/pages/preview/teleport-application-access.mdx
  docs/pages/preview/teleport-database-access.mdx
  docs/pages/production.mdx
  docs/pages/user-manual.mdx
Labels: documentation

#10262 [auto] Update AMI IDs for 8.2.0
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#9925 Replace `testify/assert` with `testify/require`
  lib/backend/firestore/firestorebk_test.go
  lib/services/local/perf_test.go
  lib/srv/db/server_test.go
  lib/web/ui/perf_test.go
Labels: cloud, database-access

#10247 Add github teams to available traits [backport #9604]
  api/types/github.go
  constants.go
  lib/auth/github.go
  lib/auth/github_test.go
Labels: backport

#10248 [v8] Backport #9671 and #9589
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: backport

#10227 Document desktop role options for Teleport 9
  docs/pages/access-controls/reference.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/setup/reference/resources.mdx
Labels: documentation, desktop-access

#9618 Add "create database agent configuration" CLI command
  lib/config/database.go
  lib/config/database_test.go
  tool/tctl/common/db_command.go
  tool/teleport/common/teleport.go
  tool/teleport/common/usage.go
Labels: cli

#10172 [v7 backport] Document docs labels (#9537)
  docs/pages/docs/best-practices.mdx
Labels: documentation

#10189 Authentication options docs: wrap `on` in quotes
  docs/pages/setup/reference/authentication.mdx
Labels: documentation

#10152 Add missing DatabasesReady event
  integration/helpers.go
  lib/service/service.go
Labels: bug, backport-required

#9385 Improve node labels example in roles docs
  docs/pages/access-controls/reference.mdx
Labels: documentation, cloud

#10272 Trusted clusters doc: Use wildcard for spec.allow.cluster_labels.env
  docs/pages/setup/admin/trustedclusters.mdx
Labels: documentation

#10254 Don't return `nil, nil` in (*AuditWriter).tryResumeStream
  lib/events/auditwriter.go
Labels: audit-log

#9425 Add documentation for moderated sessions
  docs/config.json
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/api/architecture.mdx
  docs/pages/application-access/controls.mdx
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/azuread.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/getting-started/docker-compose.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
  docs/pages/kubernetes-access/guides/cicd.mdx
  docs/pages/kubernetes-access/guides/migration.mdx
  docs/pages/server-access/guides/restricted-session.mdx
  docs/pages/setup/admin/trustedclusters.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/guides/fluentd.mdx
  docs/pages/setup/guides/terraform-provider.mdx
  docs/pages/setup/reference/resources.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#9296 RFD 52/53/54: Passwordless
  rfd/0052-passwordless.md
  rfd/0053-passwordless-fido2.md
  rfd/0054-passwordless-macos.md
Labels: rfd

#9681 Add Teleport Cloud instructions to 3 guides
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/includes/database-access/start-auth-proxy.mdx
  docs/pages/includes/database-access/token.mdx
Labels: documentation

#9826 Add Prometheus metrics cache events and stale events
  docs/pages/setup/reference/metrics.mdx
  lib/cache/cache.go
  metrics.go
Labels: documentation, cloud

#10310 [Backport v8] Add docs for IAM join method
  docs/pages/setup/guides/joining-nodes-aws.mdx
Labels: backport

#9864 RFD 48: Desktop Session Recording
  rfd/0048-desktop-access-session-recording.md
Labels: audit-log, rfd, desktop-access

#9583 Desktop session recording/playback
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/client/api.go
  lib/config/fileconf.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/auditwriter.go
  lib/events/auditwriter_test.go
  lib/events/emitter.go
  lib/events/events_test.go
  lib/events/filesessions/fileasync.go
  lib/events/playback.go
  lib/service/cfg.go
  lib/service/desktop.go
  lib/service/service.go
  lib/services/role.go
  lib/services/sessionrecording.go
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_test.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/tdp/conn.go
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
  lib/web/apiserver.go
  lib/web/desktop/playback.go
  lib/web/desktop/playback_test.go
  lib/web/desktop_playback.go
  rfd/0048-desktop-access-session-recording.md
Labels: rdp, audit-log, desktop-access

#10330 Fix fake streamer implementation to match the real one
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/filelog.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/writer.go
  lib/web/desktop/playback.go
  lib/web/desktop/playback_test.go
Labels: audit-log, flaky tests, desktop-access

#10133 Expose reverse tunnel address to web ui
  lib/web/apiserver.go
  lib/web/ui/webconfig.go
Labels: cloud

#10222 [v8] backport #9822 (`cert.create` event)
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/auth/auth.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/tlsca/ca.go
Labels: backport

#9919 Generate/validate a PIN for our virtual smartcard
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/scard.rs
  lib/srv/desktop/tdp/conn.go
  lib/srv/desktop/tdp/conn_test.go
  lib/srv/desktop/windows_server.go
Labels: rdp, backport-required, desktop-access

#10225 [v7] backport #9822 (`cert.create` event)
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/auth/auth.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/tlsca/ca.go
Labels: backport

#10226 [v6.2] backport #9822 (`cert.create` event)
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/auth/auth.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/tlsca/ca.go
Labels: backport

#10317 [v8] Sync cloud preview plans
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#10318 Sync Teleport preview plans with branch/v8
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#10168 [v7 backport] Fix docker-compose Getting Started guide issues (#9709)
  docker/sshd/scripts/generate-certs.sh
  docs/pages/getting-started/docker-compose.mdx
  docs/pages/includes/insecure-certificate.mdx
Labels: documentation

#10348 Don't open clipboard static channel when clipboard is disabled
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, desktop-access

#10355 Fix Flaky TestProcessKubeCSR
  lib/auth/desktop_test.go
  lib/auth/helpers.go
  lib/auth/kube_test.go
Labels: flaky tests

#10325 Return desktop events in SearchSessionEvents
  lib/events/dynamoevents/dynamoevents.go
  lib/events/filelog.go
  lib/events/filelog_test.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/writer.go
Labels: audit-log, desktop-access

#8773 DigitalOcean 1-click Droplet and Kubernetes getting started guides
  docs/config.json
  docs/img/helm/digitalocean/create-k8s.png
  docs/img/helm/digitalocean/edit-user.png
  docs/img/helm/digitalocean/fqdn.png
  docs/img/helm/digitalocean/setup-k8s.png
  docs/img/helm/digitalocean/setup-user.png
  docs/img/helm/digitalocean/update-role.png
  docs/img/helm/digitalocean/view-activity.png
  docs/img/quickstart/digitalocean/1click-droplet-page.png
  docs/img/quickstart/digitalocean/create-droplet.png
  docs/img/quickstart/digitalocean/fqdn.png
  docs/img/quickstart/digitalocean/setup-user.png
  docs/img/quickstart/digitalocean/webui.png
  docs/pages/getting-started/digitalocean.mdx
  docs/pages/kubernetes-access/helm/guides/digitalocean.mdx
Labels: documentation, docs-new

#10297 Fix tctl insecure flag when TLS Routing is enabled
  lib/reversetunnel/agent.go
  lib/reversetunnel/transport.go
  lib/service/connect.go
  lib/srv/alpnproxy/local_proxy.go
  lib/utils/proxy/proxy.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/resource_command_test.go
  tool/tctl/common/tctl.go
Labels: tctl

#10361 [v8] Fix tctl insecure flag when TLS Routing is enabled
  lib/reversetunnel/agent.go
  lib/reversetunnel/transport.go
  lib/service/connect.go
  lib/srv/alpnproxy/local_proxy.go
  lib/utils/proxy/proxy.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/resource_command_test.go
  tool/tctl/common/tctl.go
Labels: backport

#10349 Fix db configure
  lib/config/database.go
Labels: bug, cli, database-access

#9580 Clarify Kubernetes Getting Started guide
  docs/pages/kubernetes-access/getting-started/cluster.mdx
Labels: documentation

#10250 Attempt to deflake TestFnCacheSanity
  lib/utils/fncache_test.go
Labels: flaky tests

#10353 Ensure docs nav titles use title case consistently
  docs/config.json
Labels: documentation

#10369 Add TestModules
  integration/hsm/hsm_test.go
  lib/auth/accountrecovery_test.go
  lib/auth/desktop_test.go
  lib/auth/helpers.go
  lib/auth/keystore/keystore_test.go
  lib/auth/keystore/testhelpers.go
  lib/auth/kube_test.go
  lib/auth/tls_test.go
  lib/modules/modules_test.go
  lib/modules/test.go
  lib/srv/db/access_test.go
  lib/web/apiserver_test.go
Labels: flaky tests, database-access

#10368 Fix Reverse Tunnels Not Properly reconnecting
  integration/helpers.go
  integration/integration_test.go
  lib/reversetunnel/agentpool.go
Labels: backport-required

#10334 Label active directory domain controllers
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
Labels: desktop-access

#10258 docs: add warning about auditor role + session RBAC
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport-required

#10382 [v8] Adds session read, list rule for access role for user's sessions
  lib/services/presets.go
Labels: backport

#10053 Add Redis integration
  go.mod
  go.sum
  lib/client/identityfile/identity.go
  lib/config/configuration.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/role/role.go
  lib/srv/db/common/test.go
  lib/srv/db/proxy_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/proxyserver_test.go
  lib/srv/db/redis/cmds.go
  lib/srv/db/redis/connection.go
  lib/srv/db/redis/connection_test.go
  lib/srv/db/redis/doc.go
  lib/srv/db/redis/engine.go
  lib/srv/db/redis/protocol/resp2.go
  lib/srv/db/redis/test.go
  lib/srv/db/server_test.go
  lib/utils/errors.go
  tool/tctl/common/auth_command.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/dbcmd.go
  tool/tsh/proxy.go
Labels: tsh, tctl, database-access, c-gy, c-cv

#10407 Fix TestHandleConnection directory not empty error
  lib/srv/app/server_test.go
Labels: application-access

#10283 MySQL prepared statement support
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/events/events_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/events.go
  lib/srv/db/mysql/protocol/packet.go
  lib/srv/db/mysql/protocol/packet_test.go
  lib/srv/db/mysql/protocol/read.go
  lib/srv/db/mysql/protocol/statement.go
Labels: audit-log, database-access, db/mysql

#9603 Add teleport_connected_resources metric
  docs/pages/setup/reference/metrics.mdx
  lib/auth/grpcserver.go
  metrics.go
Labels: documentation, cloud

#10312 [v8] Backport Add Prometheus metrics cache events and stale events (#9826)
  docs/pages/setup/reference/metrics.mdx
  lib/cache/cache.go
  metrics.go
Labels: cloud

#10243 Implement resource sorter for server, appserver, dbserver
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/app_test.go
  api/types/appserver.go
  api/types/constants.go
  api/types/databaseserver.go
  api/types/databaseserver_test.go
  api/types/resource.go
  api/types/server.go
  api/types/server_test.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver_test.go
  lib/backend/backend.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
Labels: application-access, database-access

#10097 SQL server support
  api/types/database.go
  api/types/types.pb.go
  api/types/types.proto
  go.mod
  go.sum
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/access_test.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/interfaces.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/sqlserver/auth.go
  lib/srv/db/sqlserver/connect.go
  lib/srv/db/sqlserver/engine.go
  lib/srv/db/sqlserver/protocol/constants.go
  lib/srv/db/sqlserver/protocol/fixtures/packets.go
  lib/srv/db/sqlserver/protocol/login7.go
  lib/srv/db/sqlserver/protocol/packet.go
  lib/srv/db/sqlserver/protocol/prelogin.go
  lib/srv/db/sqlserver/protocol/protocol_test.go
  lib/srv/db/sqlserver/protocol/stream.go
  lib/srv/db/sqlserver/proxy.go
  lib/srv/db/sqlserver/test.go
  tool/teleport/common/teleport.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/dbcmd.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: tsh, database-access

#10376 Adds session read, list rule for access role for user's sessions
  lib/services/presets.go
Labels: ux, rbac, backport-required

#10390 Fix HSM flaky integration tests
  integration/hsm/hsm_test.go
  integration/integration_test.go
Labels: flaky tests

#10395 [v8] docs: add warning about auditor role (#10258)
  docs/pages/access-controls/reference.mdx
Labels: backport

#10437 Update teleport V8 docs to use 8.3.0 version
  docs/config.json
Labels: documentation

#10433 IAM Joining Docs: Set join_method in token.yaml
  docs/pages/setup/guides/joining-nodes-aws.mdx
Labels: documentation

#10435 [Backport v8] IAM Joining Docs: Set join_method in token.yaml
  docs/pages/setup/guides/joining-nodes-aws.mdx
Labels: backport

#9558 Add a prominent warning to the config reference
  docs/pages/setup/reference/config.mdx
Labels: documentation

#10429 [v8] Backport: "docs: Updated path to tctl/tsh for Enterprise binaries"
  docs/pages/kubernetes-access/getting-started/cluster.mdx
Labels: documentation, backport

#10428 docs: Updated path to tctl/tsh for Enterprise binaries
  docs/pages/kubernetes-access/getting-started/cluster.mdx
Labels: documentation, backport-required

#9989 Mention Teleport Cloud in some of our guides
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/setup/guides/ec2-tags.mdx
Labels: documentation

#9962 Address Cloud users in guides
  docs/pages/enterprise/hsm.mdx
  docs/pages/enterprise/sso/azuread.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/restricted-session.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/guides/docker.mdx
  docs/pages/setup/operations/scaling.mdx
Labels: documentation

#10306 [v8] Add missing DatabasesReady event to DB proxy
  integration/helpers.go
  lib/service/service.go
Labels: backport

#10101 Add support for windows desktop services proxying different desktops
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/desktop.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/api.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/services/desktop.go
  lib/services/local/desktops.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/services/presence.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/windows_server.go
  lib/web/desktop.go
  lib/web/servers.go
  tool/tctl/common/resource_command.go
Labels: tctl, desktop-access

#10307 [v7] Add missing DatabasesReady event to DB proxy
  integration/helpers.go
  lib/service/service.go
Labels: backport

#10439 Add MFA message to TDP
  lib/srv/desktop/tdp/proto.go
  lib/web/desktop.go
  lib/web/mfa_codec.go
  lib/web/mfajson/mfajson.go
  lib/web/terminal.go
  rfd/0037-desktop-access-protocol.md
Labels: rfd, desktop-access

#10344 helm: Add AWS database auto-discovery to teleport-kube-agent
  docs/pages/kubernetes-access/helm/reference.mdx
  examples/chart/teleport-cluster/templates/psp.yaml
  examples/chart/teleport-kube-agent/.lint/aws-databases.yaml
  examples/chart/teleport-kube-agent/.lint/db.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport-required

#9134 Add audit_emit_event prometheus metric
  docs/pages/setup/reference/metrics.mdx
  lib/events/auditlog.go
  lib/events/emitter.go
Labels: cloud

#10380 Fix server compare to check expiry last
  lib/services/server.go
  lib/services/servers_test.go
Labels: cloud

#10469 Re-sign .drone.yml
  .drone.yml
Labels: merge-for-v9

#10422 Add missing action VerbRead to ListResources
  api/client/proto/types.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver_test.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
Labels: merge-for-v9

#10416 Move *auth.Server methods out of auth_with_roles.go
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
Labels: merge-for-v9

#10397 Client changes for tbot IoT joining
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/authclient/authclient.go
  lib/auth/bot.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/join.go
  lib/auth/join_test.go
  lib/auth/usertoken.go
  tool/tbot/auth.go
  tool/tbot/config/configtemplate.go
  tool/tbot/config/configtemplate_ssh.go
  tool/tbot/identity/identity.go
  tool/tbot/main.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
Labels: tctl

#10360 Backend changes for tbot IoT and AWS joining
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/provisioning.go
  api/types/register.go
  api/types/system_role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/authclient/authclient.go
  lib/auth/bot.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/join.go
  lib/auth/join_iam.go
  lib/auth/join_test.go
  lib/auth/register.go
  lib/auth/tls_test.go
  lib/auth/trustedcluster.go
  lib/auth/usertoken.go
  lib/service/connect.go
  tool/tbot/auth.go
  tool/tbot/config/configtemplate.go
  tool/tbot/config/configtemplate_ssh.go
  tool/tbot/identity/identity.go
  tool/tbot/main.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
Labels: merge-for-v9

#9145 AWS database access configurator
  api/types/database.go
  lib/cloud/aws/errors.go
  lib/cloud/aws/identity.go
  lib/cloud/aws/identity_test.go
  lib/cloud/aws/policy.go
  lib/cloud/aws/policy_test.go
  lib/configurators/databases/aws.go
  lib/configurators/databases/aws_test.go
  lib/configurators/databases/databases.go
  lib/srv/db/common/errors.go
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
Labels: database-access, merge-for-v9

#10472 Reduce concurrent connections in TestRedisTransaction
  lib/srv/db/access_test.go
Labels: database-access, merge-for-v9

#10271 Add MFA for Windows Desktop web access
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/client/client.go
  lib/client/interfaces.go
  lib/client/keystore.go
  lib/srv/desktop/tdp/proto.go
  lib/srv/desktop/tdp/proto_test.go
  lib/srv/desktop/windows_server.go
  lib/web/apiserver_test.go
  lib/web/desktop.go
  lib/web/mfa_codec.go
  lib/web/mfajson/mfajson.go
  lib/web/terminal.go
  rfd/0037-desktop-access-protocol.md
Labels: desktop-access, merge-for-v9

#10470 Concurrent X11 sessions fix
  lib/srv/regular/sshserver_test.go
  lib/sshutils/x11/conn.go
  lib/sshutils/x11/display.go
Labels: bug, merge-for-v9

#10365 Adds a `DesktopSessionRecording` flag to the ACL
  lib/web/apiserver.go
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: desktop-access, merge-for-v9

#10020 CertAuthority watcher filtering
  api/types/authority.go
  api/types/events.go
  lib/auth/grpcserver.go
  lib/auth/rotate.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/service/connect.go
  lib/services/local/trust.go
Labels: merge-for-v9

#10492 [auto] Update AMI IDs for 8.3.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#10508 Release 9.0.0-beta.1
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#10510 Bump version to v10-dev
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#10468 [v7 backport] Fix server compare to check expiry last
  lib/services/server.go
  lib/services/servers_test.go
Labels: cloud

#10406 Update desktop access docs for 9.0
  docs/config.json
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/introduction.mdx
  docs/pages/desktop-access/rbac.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/desktop-access/reference/audit.mdx
  docs/pages/desktop-access/reference/cli.mdx
  docs/pages/desktop-access/reference/configuration.mdx
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport-required, desktop-access

#10417 TF provider configuration environment variables
  docs/pages/setup/reference/terraform-provider.mdx
Labels: documentation, terraform, backport-required, c-cv

#10495 docs: fix code block
  docs/pages/kubernetes-access/helm/reference.mdx
Labels: documentation, backport-required
