Repository gravitational/teleport, pull requests merged in 2022-12, with the labels that each got.

#18957 Release 11.1.1.
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#18953 (buddy) Implicitly set go version in prepare-workspace
  .github/actions/prepare-workspace/action.yml
  .github/workflows/build-ci-buildbox-images.yaml
  .github/workflows/build-ci-service-images.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/lint.yaml
  .github/workflows/os-compatibility-test.yaml
  .github/workflows/unit-tests-helm.yaml
  .github/workflows/unit-tests-operator.yaml
  .github/workflows/unit-tests-rust.yaml
  api/client/events.go
  examples/chart/teleport-cluster/values.yaml
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
Labels: rdp, helm, desktop-access

#18161 [v10] Add Terraform provider links to Terraform module README
  examples/aws/terraform/README.md
Labels: backport

#18900 [v11] Connect: Set TeleportClient.AuthConnector before logging in
  lib/teleterm/clusters/cluster_auth.go
Labels: backport

#18876 Remove legacy heartbeat from Kubernetes Service
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/types/constants.go
  api/types/kubernetes_server.go
  api/types/server.go
  api/types/types.pb.go
  integration/ec2_test.go
  lib/auth/auth_with_roles.go
  lib/cache/cache.go
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
  lib/kube/proxy/utils_test.go
  lib/kube/utils/utils.go
Labels: kubernetes-access

#18852 [v11] Connect: Check db cert before using it for local proxy
  lib/srv/alpnproxy/local_proxy.go
  lib/teleterm/api/uri/uri.go
  lib/teleterm/api/uri/uri_test.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/dbcmd_cli_command_provider_test.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/gateway/gateway.go
  lib/teleterm/gateway/gateway_test.go
  lib/teleterm/gatewaytest/helpers.go
Labels: backport

#18962 [v10] Properly check err from EmitAuditEvent.
  lib/auth/auth.go
Labels: backport

#18651 AWS Redshift Serverless engine support
  api/proto/teleport/legacy/types/types.proto
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  api/utils/aws/endpoint.go
  api/utils/aws/endpoint_test.go
  lib/cloud/clients.go
  lib/cloud/test/redshift_serverless.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/services/database.go
  lib/srv/db/access_test.go
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
  lib/srv/db/cloud/meta.go
  lib/srv/db/cloud/meta_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/auth_test.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/postgres/engine.go
  tool/tsh/tsh_test.go
Labels: tsh, aws, database-access, db/postgres

#18956 Fix dir path in Enterprise install instructions
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18943 Typo Corrections, and Replace non-example nouns
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  docs/img/database-access/guides/cassandra_keyspaces_selfhosted.png
  docs/pages/connect-your-client/introduction.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/database-access/guides/aws-cassandra-keyspaces.mdx
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18937 [v9] Update go crypto
  go.mod
  go.sum
  integration/integration_test.go
  lib/auth/init_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg_test.go
  lib/sshutils/authority.go
Labels: backport

#18946 [v9] spell fixes
  docs/pages/desktop-access/getting-started.mdx
Labels: documentation, backport

#18924 [v11] [Docs] Update EC2 Discovery guide for bootstrapping.
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport

#18942 Downgrade DNS errors to a warning log when creating MongoDB databases
  lib/services/database.go
  lib/services/database_test.go
Labels: database-access, backport/branch/v11

#18966 [v10] Fix dir path in Enterprise install instructions
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport

#18968 [v9] Fix dir path in Enterprise install instructions
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport

#18948 Backport #18883 to branch/v10
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/management/guides/fluentd.mdx
  docs/pages/management/guides/teleport-operator.mdx
  docs/pages/try-out-teleport/local-kubernetes.mdx
Labels: documentation, backport

#18582 Add a guide to GKE Auto-Discovery
  docs/config.json
  docs/pages/includes/kubernetes-access/rbac.mdx
  docs/pages/kubernetes-access/discovery.mdx
  docs/pages/kubernetes-access/discovery/google-cloud.mdx
  docs/pages/kubernetes-access/discovery/includes/step-description.mdx
Labels: documentation, backport/branch/v11

#18950 [v11] Improve the Kubernetes Dynamic Registration guide
  docs/pages/kubernetes-access/guides/dynamic-registration.mdx
Labels: documentation, backport

#18967 [v11] Fix dir path in Enterprise install instructions
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport

#18980 [Docs] Hotfix: Broken download link on Intro to Teleport Clients
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18975 Added 12/01 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#18987 [auto] Update AMI IDs for 11.1.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#18986 [v11] Add a guide to GKE Auto-Discovery
  docs/config.json
  docs/pages/includes/kubernetes-access/rbac.mdx
  docs/pages/kubernetes-access/discovery.mdx
  docs/pages/kubernetes-access/discovery/google-cloud.mdx
  docs/pages/kubernetes-access/discovery/includes/step-description.mdx
Labels: documentation, backport

#18982 Fix unknown group error issue
  lib/srv/reexec.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: regression, backport/branch/v10, backport/branch/v11

#18963 [v11] Properly check err from EmitAuditEvent.
  lib/auth/auth.go
Labels: backport

#18961 [v9] Properly check err from EmitAuditEvent.
  lib/auth/auth.go
Labels: backport

#18997 [v11] update docs version
  docs/config.json
Labels: documentation, backport

#18998 [v11] fix heading level for 11.0.1 release
  CHANGELOG.md
Labels: backport

#18779 Ensure `tctl windows_desktops ls` produces expected output
  tool/tctl/common/collection.go
  tool/tctl/common/desktop_command.go
Labels: tctl, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19013 Release 10.3.9
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#19014 [v9] Ensure `tctl windows_desktops ls` produces expected output
  tool/tctl/common/collection.go
  tool/tctl/common/desktop_command.go
Labels: tctl, backport

#18659 Kubernetes joinMethod
  .github/ISSUE_TEMPLATE/testplan.md
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  lib/auth/auth.go
  lib/auth/join.go
  lib/auth/join_kubernetes.go
  lib/auth/join_kubernetes_test.go
  lib/auth/register.go
  lib/kubernetestoken/token_source.go
  lib/kubernetestoken/token_source_test.go
  lib/kubernetestoken/token_validator.go
  lib/kubernetestoken/token_validator_test.go
  lib/service/service.go
  tool/teleport/common/teleport.go
Labels: kubernetes-access, machine-id

#19017 [v11] Add clarification as to the purpose of Metrics endpoint.
  docs/pages/reference/metrics.mdx
Labels: documentation, backport

#18831 Create a partial for adding a role to a user
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/database-access/guides/dynamodb.mdx
  docs/pages/desktop-access/directory-sharing.mdx
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/includes/add-role-to-user.mdx
  docs/pages/includes/kubernetes-access/rbac.mdx
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/kubernetes-access/guides/dynamic-registration.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/guides/elastic-stack.mdx
  docs/pages/management/guides/fluentd.mdx
  docs/pages/management/guides/ssh-key-extensions.mdx
  docs/pages/management/guides/terraform-provider.mdx
  docs/pages/server-access/guides/host-user-creation.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18716 [v9] [Docs] Amend Vars reference documentation.
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation, backport

#19004 [v11] [Docs] Hotfix: Broken download link on Intro to Teleport Clients
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport

#19001 Re-add the section about EC2 instances including the AmazonSSMManagedInstanceCore
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19005 [v10] [Docs] Hotfix: Broken download link on Intro to Teleport Clients
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport

#18990 [v11] Fix unknown group error issue
  lib/srv/reexec.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: backport

#18991 [v10] Fix unknown group error issue
  lib/srv/reexec.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: backport

#13682 Expand internal.logins def in Access Controls ref
  docs/pages/access-controls/reference.mdx
Labels: documentation, inactive, backport/branch/v10, backport/branch/v11

#18952 [v11] docs: clean up per-session MFA page
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation, backport

#18993 BUGFIX | Teleport ALPN Proxy doesn't respect HTTP CONNECT Proxy
  lib/srv/alpnproxy/conn_upgrade.go
  lib/srv/alpnproxy/conn_upgrade_test.go
  lib/srv/alpnproxy/dialer.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#18875 [v10] Cache static desktop labels
  lib/config/configuration.go
  lib/service/cfg.go
  lib/service/cfg_test.go
Labels: backport

#18873 [v9] Cache static desktop labels
  lib/config/configuration.go
  lib/service/cfg.go
  lib/service/cfg_test.go
Labels: backport

#18562 Add separation between keys when exporting CAs
  docs/pages/reference/cli.mdx
  lib/client/ca_export.go
  lib/client/ca_export_test.go
  tool/tctl/common/auth_command.go
Labels: release-notes

#19015 [v10] Ensure `tctl windows_desktops ls` produces expected output
  tool/tctl/common/collection.go
  tool/tctl/common/desktop_command.go
Labels: tctl, backport

#19040 [v11] Move corrupted uploads to separate directory
  integration/utmp_integration_test.go
  lib/auth/helpers.go
  lib/events/auditlog.go
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/filestream.go
  lib/events/filesessions/fileuploader.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/utils_test.go
  lib/service/service.go
  lib/srv/app/server_test.go
  lib/srv/app/session.go
  lib/srv/db/streamer.go
  lib/srv/desktop/windows_server.go
  lib/srv/mock.go
  lib/srv/regular/sshserver_test.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/web/apiserver_test.go
Labels: kubernetes-access, audit-log, application-access, database-access, backport, desktop-access

#19038 [v11] BUGFIX | Teleport ALPN Proxy doesn't respect HTTP CONNECT Proxy
  lib/srv/alpnproxy/conn_upgrade.go
  lib/srv/alpnproxy/conn_upgrade_test.go
  lib/srv/alpnproxy/dialer.go
Labels: backport

#19026 [v11] Create a partial for adding a role to a user
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/application-access/guides/aws-console.mdx
  docs/pages/database-access/guides/dynamodb.mdx
  docs/pages/desktop-access/directory-sharing.mdx
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/includes/add-role-to-user.mdx
  docs/pages/includes/kubernetes-access/rbac.mdx
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/kubernetes-access/guides/dynamic-registration.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/guides/elastic-stack.mdx
  docs/pages/management/guides/fluentd.mdx
  docs/pages/management/guides/ssh-key-extensions.mdx
  docs/pages/management/guides/terraform-provider.mdx
  docs/pages/server-access/guides/host-user-creation.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport

#18823 docs: Add warnings about using layer 7 LBs with TLS routing
  docs/pages/architecture/tls-routing.mdx
  docs/pages/includes/tls-multiplexing-warnings.mdx
  docs/pages/management/admin/troubleshooting.mdx
  docs/pages/management/operations/tls-routing.mdx
Labels: documentation, time-to-value, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18971 Fix `teleport-kube-agent` v9 bug, generating invalid join_params config
  examples/chart/teleport-kube-agent/templates/config.yaml
Labels: bug, helm, backport

#19039 [v10] BUGFIX | Teleport ALPN Proxy doesn't respect HTTP CONNECT Proxy
  lib/srv/alpnproxy/conn_upgrade.go
  lib/srv/alpnproxy/conn_upgrade_test.go
  lib/srv/alpnproxy/dialer.go
Labels: backport

#18142 Add a new usage reporter
  Makefile
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/usageevents/v1/usageevents.proto
  api/types/constants.go
  api/types/license.go
  constants.go
  go.mod
  go.sum
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/events/usageevents/usageevents.go
  lib/prehog/bin/protoc-gen-connect-go
  lib/prehog/bin/protoc-gen-go
  lib/prehog/buf.gen.yaml
  lib/prehog/buf.work.yaml
  lib/prehog/gen/prehog/v1alpha/prehogv1alphaconnect/teleport.connect.go
  lib/prehog/gen/prehog/v1alpha/teleport.pb.go
  lib/prehog/proto/prehog/buf.yaml
  lib/prehog/proto/prehog/v1alpha/teleport.proto
  lib/service/cfg.go
  lib/service/service.go
  lib/services/local/usagereporter.go
  lib/services/local/usagereporter_test.go
  lib/services/role.go
  lib/services/usagereporter.go
  lib/utils/anonymizer.go
  lib/web/apiserver.go
  lib/web/userevent.go
  metrics.go
Labels: audit-log

#19059 [v11] Add a new usage reporter (#18142)
  Makefile
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/usageevents/v1/usageevents.proto
  api/types/constants.go
  api/types/license.go
  constants.go
  go.mod
  go.sum
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/events/usageevents/usageevents.go
  lib/prehog/bin/protoc-gen-connect-go
  lib/prehog/bin/protoc-gen-go
  lib/prehog/buf.gen.yaml
  lib/prehog/buf.work.yaml
  lib/prehog/gen/prehog/v1alpha/prehogv1alphaconnect/teleport.connect.go
  lib/prehog/gen/prehog/v1alpha/teleport.pb.go
  lib/prehog/proto/prehog/buf.yaml
  lib/prehog/proto/prehog/v1alpha/teleport.proto
  lib/service/cfg.go
  lib/service/service.go
  lib/services/local/usagereporter.go
  lib/services/local/usagereporter_test.go
  lib/services/role.go
  lib/services/usagereporter.go
  lib/utils/anonymizer.go
  lib/web/apiserver.go
  lib/web/userevent.go
  metrics.go
Labels: audit-log, backport

#18964 helm: use new helm-unittest plugin
  .cloudbuild/ci/unit-tests.yaml
  .github/workflows/unit-tests-helm.yaml
  BUILD_macos.md
  Makefile
  build.assets/Makefile
  examples/chart/CONTRIBUTING.md
  examples/chart/teleport-cluster/tests/README.md
  examples/chart/teleport-cluster/tests/__snapshot__/psp_test.yaml.snap
  examples/chart/teleport-cluster/tests/deployment_test.yaml
  examples/chart/teleport-cluster/tests/psp_test.yaml
  examples/chart/teleport-kube-agent/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/tests/README.md
  examples/chart/teleport-kube-agent/tests/__snapshot__/psp_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/psp_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
Labels: helm

#19061 [v10] docs: Add warnings about using layer 7 LBs with TLS routing
  docs/pages/architecture/tls-routing.mdx
  docs/pages/includes/tls-multiplexing-warnings.mdx
  docs/pages/management/admin/troubleshooting.mdx
  docs/pages/management/operations/tls-routing.mdx
Labels: documentation, backport

#19062 [v9] docs: Add warnings about using layer 7 LBs with TLS routing
  docs/pages/architecture/tls-routing.mdx
  docs/pages/includes/tls-multiplexing-warnings.mdx
  docs/pages/setup/admin/troubleshooting.mdx
  docs/pages/setup/operations/tls-routing.mdx
Labels: documentation, backport

#19020 Fixed container images dockerfile download using hardcoded repo name
  .drone.yml
  dronegen/container_image_products.go
Labels: bug, backport-required, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18884 [v9] Disable MongoDB server selection in tests
  go.mod
  go.sum
  lib/srv/db/mongodb/test.go
Labels: database-access, backport

#19071 Release 9.3.23
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm, backport

#19057 [v11] docs: fix tsh --cert-format reference
  docs/pages/reference/cli.mdx
Labels: documentation, backport

#17950 Connect: Detect & reissue expired db certs
  integration/helpers/usercreds.go
  integration/proxy/proxy_test.go
  integration/proxy/teleterm_test.go
  lib/teleterm/api/proto/v1/tshd_events_service.proto
  lib/teleterm/api/protogen/golang/v1/tshd_events_service.pb.go
  lib/teleterm/api/protogen/golang/v1/tshd_events_service_grpc.pb.go
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/tshd_events_service_pb.js
  lib/teleterm/api/uri/uri.go
  lib/teleterm/api/uri/uri_test.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/daemon/gateway_cert_reissuer.go
  lib/teleterm/daemon/gateway_cert_reissuer_test.go
  lib/teleterm/gateway/local_proxy_middleware.go
Labels: backport/branch/v11

#19009 add --apply-on-startup flag
  docs/pages/reference/cli.mdx
  lib/auth/init.go
  lib/auth/init_test.go
  lib/client/api_login_test.go
  lib/config/configuration.go
  lib/service/cfg.go
  lib/service/service.go
  lib/services/resource.go
  tool/teleport/common/teleport.go
  tool/teleport/common/teleport_test.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
Labels: documentation, tsh

#19065 docs: mention additional GPO that must be configured for desktop auth
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#18976 [v11] Typo Corrections, and Replace non-example nouns
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  docs/img/database-access/guides/cassandra_keyspaces_selfhosted.png
  docs/pages/connect-your-client/introduction.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/database-access/guides/aws-cassandra-keyspaces.mdx
Labels: documentation, backport

#18949 Backport #18842 to branch/v11
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira-server.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/deploy-a-cluster/deployments/gcp.mdx
  docs/pages/deploy-a-cluster/deployments/ibm.mdx
  docs/pages/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/try-out-teleport/docker-compose.mdx
Labels: documentation, backport

#19063 [Discover] Add ons for database flow
  lib/services/presets.go
  lib/web/apiserver_test.go
  lib/web/databases.go
  lib/web/databases_test.go
  lib/web/ui/server.go
  lib/web/ui/server_test.go
  lib/web/ui/usercontext.go
Labels: backport/branch/v11

#19090 [v11] Fixed container images dockerfile download using hardcoded repo name
  .drone.yml
  dronegen/container_image_products.go
Labels: backport

#19092 [v9] Fixed container images dockerfile download using hardcoded repo name
  .drone.yml
  dronegen/container_image_products.go
Labels: backport

#19117 Release 11.1.2
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#13376 RFD 98: Kubernetes clusters Auto-Discovery
  rfd/0098-kubernetes-access-cluster-discovery.md
Labels: rfd

#19091 [v10] Fixed container images dockerfile download using hardcoded repo name
  .drone.yml
  dronegen/container_image_products.go
Labels: backport

#19105 Edit the Database Access introduction
  docs/pages/database-access/introduction.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19130 [auto] Update AMI IDs for 11.1.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#18959 Displays Server Disconnect reason to the user
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19101 Update `examples/systemd/machine-id` to use best practices!
  examples/systemd/machine-id/README.md
  examples/systemd/machine-id/machine-id.service
Labels: backport/branch/v11

#18985 Make bitmaps opaque in Desktop Access
  lib/srv/desktop/rdp/rdpclient/client.go
Labels: bug, rdp, desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19103 [v10] docs: mention additional GPO that must be configured for desktop auth
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport

#19095 Fix typo in integration/db.SetupDatabaseTest
  integration/db/fixture.go
Labels: backport/branch/v11

#19139 Dependency updates
  Cargo.lock
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, desktop-access

#18607 Fixes dissonance between `disconnect_expired_cert` vs `require_session_mfa`
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  constants.go
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/keygen/keygen.go
  lib/auth/permissions.go
  lib/auth/test/suite.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/services/authority.go
  lib/srv/app/server.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/db/proxyserver.go
  lib/srv/desktop/windows_server.go
  lib/srv/monitor.go
  lib/srv/monitor_test.go
  lib/sshca/sshca.go
  lib/tlsca/ca.go
Labels: kubernetes-access, application-access, database-access, desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19150 Update Docs Vars for 11.1.2
  docs/config.json
Labels: documentation, backport

#19110 Fix a link with a long redirect chain
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19154 [v9] Displays Server Disconnect reason to the user (#18959)
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, backport, desktop-access

#19108 Add the `tsh device enroll` command
  tool/tsh/device.go
  tool/tsh/tsh.go
Labels: tsh

#18763 [v10] Added logging for audit stream creation.
  lib/auth/grpcserver.go
Labels: backport

#19151 [v11] Displays Server Disconnect reason to the user
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, backport, desktop-access

#19160 [v11] Fix a link with a long redirect chain
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport

#19159 [v10] Fix a link with a long redirect chain
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, backport

#18764 [v11] Added logging for audit stream creation.
  lib/auth/grpcserver.go
Labels: backport

#18978 Eventually require connection failure in TestTCPCertExpiration tests.
  integration/appaccess/appaccess_test.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#18765 [v9] Added logging for audit stream creation.
  lib/auth/grpcserver.go
Labels: backport

#19162 Bump Buf to v1.10.0
  build.assets/Dockerfile
Labels: backport/branch/v10, backport/branch/v11

#18984 [v11] Downgrade DNS errors to a warning log when creating MongoDB databases
  lib/services/database.go
  lib/services/database_test.go
Labels: backport

#19153 [v10] Displays Server Disconnect reason to the user (#18959)
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, backport, desktop-access

#19097 Optimize trait loop evaluation
  lib/services/suite/presence_test.go
  lib/services/traits.go
  lib/services/user_test.go
  lib/utils/replace.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#19170 [v11] Optimize trait loop evaluation
  lib/services/suite/presence_test.go
  lib/services/traits.go
  lib/services/user_test.go
  lib/utils/replace.go
Labels: backport, size/md

#19148 Properly escape maps in log entries
  lib/utils/formatter.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#19132 errors.go: Update link in error message for self signed cert setup
  lib/utils/errors.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#18791 Kubernetes Portforward via Websockets
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/portforward_spdy.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/portforward_websocket.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/utils_test.go
  lib/kube/proxy/websocket_client_test.go
Labels: kubernetes-access, backport/branch/v10, backport/branch/v11

#19179 [v11] Fix typo in integration/db.SetupDatabaseTest
  integration/db/fixture.go
Labels: backport, size/sm

#19100 Azure SQL Server auto-discovery documentation
  docs/img/database-access/guides/sqlserver/create-role-from-json.png
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
Labels: documentation, backport/branch/v11

#19187 Organized machine-id docs menu to match other protocols
  docs/config.json
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19169 Attempt to deflake TestDatabaseAccess/AgentState
  integration/db/db_integration_test.go
  integration/db/fixture.go
  integration/helpers/helpers.go
Labels: flaky tests, database-access, size/sm

#19197 [v11] Organized machine-id docs menu to match other protocols
  docs/config.json
Labels: documentation, backport, size/sm

#19183 [v10] Optimize trait loop evaluation
  lib/services/github_test.go
  lib/services/license_test.go
  lib/services/local/resource_test.go
  lib/services/map_test.go
  lib/services/saml_test.go
  lib/services/servers_test.go
  lib/services/services_test.go
  lib/services/suite/presence_test.go
  lib/services/traits.go
  lib/services/user_test.go
  lib/services/usertoken_test.go
  lib/services/wrappers_test.go
  lib/utils/replace.go
Labels: backport, size/md

#18792 Add listing and playing recorded interactive sessions to tsh docs
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11

#19199 [v11] Bump cloud version to 11.1.2
  docs/config.json
Labels: documentation, backport, size/sm

#19193 [v9] Properly escape maps in log entries
  lib/utils/formatter.go
Labels: backport, size/sm

#19178 [v11] Fixes dissonance between `disconnect_expired_cert` vs `require_session_mfa`
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  constants.go
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/native/native.go
  lib/auth/permissions.go
  lib/auth/test/suite.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/services/authority.go
  lib/srv/app/server.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/db/proxyserver.go
  lib/srv/desktop/windows_server.go
  lib/srv/monitor.go
  lib/srv/monitor_test.go
  lib/sshca/sshca.go
  lib/tlsca/ca.go
Labels: kubernetes-access, application-access, database-access, backport, desktop-access, size/md

#16762 Add a glossary of Teleport terms
  docs/config.json
  docs/pages/access-controls/compliance-frameworks/soc2.mdx
  docs/pages/architecture/authentication.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/architecture/nodes.mdx
  docs/pages/architecture/overview.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/core-concepts.mdx
  docs/pages/database-access/architecture.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19195 [v11] Properly escape maps in log entries
  lib/utils/formatter.go
Labels: backport, size/sm

#19165 Include Teleport Connect reference in installation docs page
  docs/pages/installation.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19188 Fix Kubernetes version detection on EKS
  lib/auth/join_kubernetes.go
  lib/kubernetestoken/token_validator.go
  lib/kubernetestoken/token_validator_test.go
Labels: bug, kubernetes-access, size/sm

#19173 [v11] errors.go: Update link in error message for self signed cert setup
  lib/utils/errors.go
Labels: backport, size/sm

#19215 [v11] Add listing and playing recorded interactive sessions to tsh docs
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/md

#19186 Update connect your client for Idp and other minor items
  docs/pages/connect-your-client/introduction.mdx
  docs/pages/connect-your-client/tsh.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm

#19224 CodeQL: Set a timeout limit to ensure jobs don't hang
  .github/workflows/codeql.yml
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19223 Drop usage events after too many retries
  lib/services/local/usagereporter.go
  lib/services/local/usagereporter_test.go
Labels: backport/branch/v11, size/sm

#19182 [v9] Optimize trait loop evaluation
  lib/services/suite/presence_test.go
  lib/services/traits.go
  lib/services/user_test.go
  lib/utils/replace.go
Labels: backport, size/md

#19221 Update docs with new location of setup GitHub Action
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, machine-id, backport/branch/v11, size/sm

#19003 Fix desktop access setup docs
  docs/pages/desktop-access/manual-setup.mdx
  lib/web/scripts/desktop/install-ad-cs.ps1
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#19210 [v11] Add `license` and `download` verbs to user context ACL and default editor role (#19049)
  api/types/constants.go
  lib/services/presets.go
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: backport, size/sm

#19161 [v11] Add recovery codes flag to modules and web config (#19046)
  api/client/proto/authservice.pb.go
  api/client/webclient/webconfig.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/accountrecovery.go
  lib/auth/accountrecovery_test.go
  lib/modules/modules.go
  lib/plugin/registry.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  tool/tsh/tsh_test.go
Labels: tsh, backport

#19203 [v11] Bump Buf to v1.10.0 and protoc to 3.20.3
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/webauthn/webauthn.proto
  build.assets/Dockerfile
  build.assets/Makefile
  lib/prehog/proto/prehog/v1alpha/teleport.proto
Labels: backport, size/sm

#19166 Add `tsh device` debug commands
  lib/devicetrust/native/api.go
  lib/devicetrust/native/device_darwin.go
  lib/devicetrust/native/others.go
  lib/devicetrust/native/status_error.go
  tool/tsh/device.go
  tool/tsh/tsh.go
Labels: tsh, size/sm

#19206 [v10] Bump Buf to v1.10.0 and protoc to 3.20.3
  .cloudbuild/scripts/cmd/integration-tests/main.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/webauthn/webauthn.proto
  api/types/types.pb.go
  build.assets/Dockerfile
  build.assets/Makefile
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/app_pb.js
  lib/teleterm/api/protogen/js/v1/auth_settings_pb.js
  lib/teleterm/api/protogen/js/v1/cluster_pb.js
  lib/teleterm/api/protogen/js/v1/database_pb.js
  lib/teleterm/api/protogen/js/v1/gateway_pb.js
  lib/teleterm/api/protogen/js/v1/kube_pb.js
  lib/teleterm/api/protogen/js/v1/label_pb.js
  lib/teleterm/api/protogen/js/v1/server_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.js
Labels: backport, size/sm

#19194 [v10] Properly escape maps in log entries
  lib/utils/formatter.go
Labels: backport, size/sm

#19235 Remove ignored user parameter for non-local auth connector examples
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19229 [v11] Terraform code git clone to use branch, not master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
Labels: documentation, backport, size/sm

#19207 [v11] Add a glossary of Teleport terms
  docs/config.json
  docs/pages/access-controls/compliance-frameworks/soc2.mdx
  docs/pages/architecture/authentication.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/architecture/nodes.mdx
  docs/pages/architecture/overview.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/core-concepts.mdx
  docs/pages/database-access/architecture.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#19201 [v10] Eventually require connection failure in TestTCPCertExpiration tests.
  integration/app_integration_test.go
Labels: backport, size/sm

#19230 [v11] Update docs with new location of setup GitHub Action
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport, size/sm

#19213 deps: update gravitational/predicate to v1.3.0
  go.mod
  go.sum
Labels: backport/branch/v11, size/sm

#19200 [v11] Eventually require connection failure in TestTCPCertExpiration tests.
  integration/appaccess/appaccess_test.go
Labels: backport, size/sm

#19202 [v9] Eventually require connection failure in TestWSSCertExpiration tests.
  integration/app_integration_test.go
Labels: backport, size/sm

#19228 [v10] Terraform code git clone to use branch, not master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
Labels: documentation, backport, size/sm

#19219 [v11] feat: add login rule protobuf type
  api/gen/proto/go/teleport/loginrule/v1/loginrule.pb.go
  api/proto/teleport/loginrule/v1/loginrule.proto
Labels: backport, size/sm

#19250 [v11] deps: update gravitational/predicate to v1.3.0
  go.mod
  go.sum
Labels: backport, size/sm

#19242 [v9] CodeQL: Set a timeout limit to ensure jobs don't hang
  .github/workflows/codeql.yml
Labels: backport, size/sm

#19184 [v10] Kubernetes Portforward via Websockets
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/portforward_spdy.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/portforward_websocket.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/utils_test.go
  lib/kube/proxy/websocket_client_test.go
Labels: kubernetes-access, backport, size/lg

#19244 [v11] CodeQL: Set a timeout limit to ensure jobs don't hang
  .github/workflows/codeql.yml
Labels: backport, size/sm

#19243 [v10] CodeQL: Set a timeout limit to ensure jobs don't hang
  .github/workflows/codeql.yml
Labels: backport, size/sm

#19181 [v11] Kubernetes Portforward via Websockets
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/portforward_spdy.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/portforward_websocket.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/utils_test.go
  lib/kube/proxy/websocket_client_test.go
Labels: kubernetes-access, backport, size/lg

#19248 [v11] Remove ignored user parameter for non-local auth connector examples
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#19255 [v11] Drop usage events after too many retries
  lib/services/local/usagereporter.go
  lib/services/local/usagereporter_test.go
Labels: backport, size/sm

#18974 AWS Redshift Serverless auto-discovery
  lib/cloud/aws/tags_helpers.go
  lib/cloud/aws/tags_helpers_test.go
  lib/config/database.go
  lib/config/database_test.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/configurators/common.go
  lib/services/database.go
  lib/services/database_test.go
  lib/services/matchers.go
  lib/srv/db/cloud/watchers/memorydb.go
  lib/srv/db/cloud/watchers/rds_proxy.go
  lib/srv/db/cloud/watchers/redshift_serverless.go
  lib/srv/db/cloud/watchers/watcher.go
  lib/srv/db/cloud/watchers/watcher_test.go
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
Labels: aws, database-access, db/postgres

#19249 [v10] Remove ignored user parameter for non-local auth connector examples
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm
