Repository gravitational/teleport, pull requests merged in 2022-06, with the labels that each got.

#12709 Manage ElastiCache Users
  api/types/database.go
  api/types/types.pb.go
  api/types/types.proto
  lib/cloud/aws/tags.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/configurators/databases/aws.go
  lib/configurators/databases/aws_test.go
  lib/service/cfg.go
  lib/service/db.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/cloud/users/elasticache.go
  lib/srv/db/cloud/users/helpers.go
  lib/srv/db/cloud/users/helpers_test.go
  lib/srv/db/cloud/users/user.go
  lib/srv/db/cloud/users/user_test.go
  lib/srv/db/cloud/users/users.go
  lib/srv/db/cloud/users/users_test.go
  lib/srv/db/common/cloud.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/interfaces.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/cmds.go
  lib/srv/db/redis/engine.go
  lib/srv/db/secrets/aws_mocks.go
  lib/srv/db/secrets/aws_secrets_manager.go
  lib/srv/db/secrets/aws_secrets_manager_test.go
  lib/srv/db/secrets/secrets.go
  lib/srv/db/secrets/secrets_test.go
  lib/srv/db/server.go
  tool/tsh/db.go
  tool/tsh/tsh_test.go
Labels: feature-request, tsh, database-access, db/redis

#13047 [v9] Automatically import EC2 tags (#12593)
  api/types/appserver.go
  api/types/constants.go
  api/types/databaseserver.go
  api/types/desktop.go
  api/types/resource.go
  api/types/server.go
  docs/img/aws/allow-tags.png
  docs/img/aws/instance-settings.png
  docs/img/aws/launch-instance-advanced-options.png
  docs/pages/setup/guides/ec2-tags.mdx
  integration/ec2_test.go
  integration/helpers.go
  integration/utmp_integration_test.go
  lib/cloud/aws/errors.go
  lib/cloud/aws/imds.go
  lib/kube/proxy/forwarder.go
  lib/labels/ec2/ec2.go
  lib/labels/ec2/ec2_test.go
  lib/labels/labels.go
  lib/labels/labels_test.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/services/server.go
  lib/services/watcher.go
  lib/srv/app/server.go
  lib/srv/db/server.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/teleterm/apiserver/handler/handler_servers.go
  lib/utils/ec2.go
  lib/web/ui/server.go
Labels: documentation, application-access, database-access, backport, kubernetes

#13004 [v9] docs version update to 9.3.0
  docs/config.json
Labels: documentation

#12855 Refactor tbot
  lib/tbot/botfs/botfs.go
  lib/tbot/botfs/botfs_test.go
  lib/tbot/botfs/fs_linux.go
  lib/tbot/botfs/fs_other.go
  lib/tbot/config/config.go
  lib/tbot/config/config_destination.go
  lib/tbot/config/config_storage.go
  lib/tbot/config/config_test.go
  lib/tbot/config/configtemplate.go
  lib/tbot/config/configtemplate_cockroach.go
  lib/tbot/config/configtemplate_identity.go
  lib/tbot/config/configtemplate_mongo.go
  lib/tbot/config/configtemplate_ssh_client.go
  lib/tbot/config/configtemplate_ssh_client_test.go
  lib/tbot/config/configtemplate_tls.go
  lib/tbot/config/configtemplate_tls_cas.go
  lib/tbot/config/destination.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_memory.go
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/known_hosts.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/ssh_config.golden
  lib/tbot/configtemplate_test.go
  lib/tbot/destination/destination.go
  lib/tbot/identity/artifact.go
  lib/tbot/identity/identity.go
  lib/tbot/identity/kinds.go
  lib/tbot/identity_test.go
  lib/tbot/renew.go
  lib/tbot/renew_test.go
  lib/tbot/tbot.go
  lib/tbot/testhelpers/srv.go
  lib/tbot/tshwrap/wrap.go
  lib/tbot/tshwrap/wrap_test.go
  tool/tbot/db.go
  tool/tbot/init.go
  tool/tbot/init_test.go
  tool/tbot/main.go
  tool/tbot/proxy.go
Labels: machine-id, backport/branch/v9, backport/branch/v8, backport/branch/v7

#12753 Add labels to output of 'tsh kube ls'
  lib/kube/utils/utils.go
  tool/tsh/kube.go
  tool/tsh/tsh_test.go
Labels: tsh, kubernetes

#12642 Backport #12038 to branch/v9
  docs/config.json
  docs/pages/setup/admin.mdx
  docs/pages/setup/admin/daemon.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
Labels: documentation

#12544 Flesh out CAP instructions
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/reference/authentication.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#12504 Make the Adding Nodes guide more usable
  docs/pages/setup/admin/adding-nodes.mdx
Labels: documentation

#12426 Opportunistically match inputs with detectProto
  lib/multiplexer/multiplexer.go
  lib/multiplexer/wrappers.go
Labels: refactoring

#12779 Update Rust to 1.61.0
  build.assets/Makefile
  lib/datalog/roletester/src/role_tester.rs
Labels: rdp, desktop-access

#12894 [v9] Docs Backports
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/faq.mdx
  docs/pages/server-access/guides/tsh.mdx
Labels: documentation

#13082 [v9] Fix EC2 labels concurrent write (#13072)
  integration/ec2_test.go
  lib/labels/ec2/ec2.go
Labels: backport

#13055 Extend `editor` with RW access to SSO requests.
  lib/services/presets.go
Labels: security

#13064 Cloud customers should use port 443 when configuring agents
  docs/pages/application-access/getting-started.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/database-access/reference/cli.mdx
Labels: documentation

#13066 [v9] Cloud customer auth servers use port 443
  docs/pages/application-access/getting-started.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/database-access/reference/cli.mdx
Labels: documentation, backport

#13106 Simplify reexec on linux
  lib/srv/reexec_linux.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v7

#13128 [v9] Add disabled imds client by default for integration tests (#13109)
  integration/helpers.go
  integration/integration_test.go
Labels: backport

#12612 (v9) Add JWT auth guide for ElasticSearch
  docs/config.json
  docs/pages/application-access/controls.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/application-access/jwt.mdx
  docs/pages/application-access/jwt/elasticsearch.mdx
  docs/pages/application-access/jwt/introduction.mdx
Labels: documentation

#12834 fix(teleport/db-create): Use --proxy instead of --auth-server in example command
  tool/tctl/common/db_command.go
Labels: tctl

#13138 [v9] Filter out invalid EC2 tag keys (#13131)
  lib/labels/ec2/ec2.go
  lib/labels/ec2/ec2_test.go
Labels: backport

#13093 [Search-based access requests] Nicer ResourceID strings
  api/types/constants.go
  api/types/resource_ids.go
  api/types/resource_ids_test.go
  tool/tctl/common/access_request_command.go
  tool/tsh/access_request.go
  tool/tsh/tsh.go
Labels: tsh, tctl

#12903 [v9] Change tsh to only print non exit errors on exit
  tool/tsh/tsh.go
Labels: tsh

#13094 SQLServer event add missing conversion
  lib/events/dynamic.go
  lib/srv/db/sqlserver/engine_test.go
  lib/srv/db/sqlserver/protocol/fixtures/packets.go
Labels: audit-log, database-access

#12953 Backport #12838 to branch/v9
  docs/pages/older-versions.mdx
Labels: documentation

#13110 Backport #12544 to branch/v9
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/reference/authentication.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation

#13137 Add JWT auth guide for ElasticSearch (#12612)
  docs/config.json
  docs/pages/application-access/controls.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/guides.mdx
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/application-access/jwt.mdx
  docs/pages/application-access/jwt/elasticsearch.mdx
  docs/pages/application-access/jwt/introduction.mdx
Labels: documentation

#13136 attempt to fix flaky TestProxyClientDisconnectDueToLockInForce
  lib/srv/monitor.go
Labels: flaky tests

#10025 Implement "tsh proxy aws"
  api/utils/keypaths/keypaths.go
  lib/client/api.go
  lib/srv/alpnproxy/forward_proxy.go
  lib/srv/alpnproxy/forward_proxy_test.go
  lib/srv/alpnproxy/helpers_test.go
  lib/srv/alpnproxy/listener.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/local_proxy_test.go
  lib/srv/app/aws/endpoints.go
  lib/srv/app/aws/endpoints_test.go
  lib/tlsca/ca.go
  lib/tlsca/ca_test.go
  lib/tlsca/parsegen.go
  lib/utils/aws/aws.go
  tool/tsh/app.go
  tool/tsh/aws.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: feature-request, tsh, application-access, c-th

#10746 RFD 58: Package Distribution
  .drone.yml
  build.assets/tooling/cmd/build-apt-repos/apt_repo_tool.go
  build.assets/tooling/cmd/build-apt-repos/aptly.go
  build.assets/tooling/cmd/build-apt-repos/config.go
  build.assets/tooling/cmd/build-apt-repos/main.go
  build.assets/tooling/cmd/build-apt-repos/repo.go
  build.assets/tooling/cmd/build-apt-repos/s3logger.go
  build.assets/tooling/cmd/build-apt-repos/s3manager.go
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  dronegen/common.go
  dronegen/main.go
  dronegen/misc.go
  rfd/0058-package-distribution.md
Labels: rfd

#12998 [v9] Update SSO prereqs for consistency and include Teleport Cloud
  docs/config.json
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/adfs.mdx
  docs/pages/enterprise/sso/azuread.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
  docs/pages/setup/admin/github-sso.mdx
  examples/resources/okta-connector.yaml
Labels: documentation, backport

#13134 Expand --mfa-mode and disable stdin hijack by default
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/mfa.go
  lib/client/weblogin.go
  tool/tsh/tsh.go
Labels: tsh

#13051 [Search-based access requests] Implement "tsh ssh --request user@node"
  tool/tsh/access_request.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh

#13153 [auto] Update AMI IDs for 9.3.2
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#13150 fix typo in RBAC guides.mdx
  docs/pages/access-controls/guides.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8

#13162 Fix flaky TestProxyClientDisconnectDueToIdleConnection
  lib/srv/monitor.go
  lib/srv/monitor_test.go
Labels: flaky tests

#12352 Fix Audit Event max event size flow
  api/types/events/events.go
  api/types/events/events_test.go
  integration/db_integration_test.go
  lib/auth/grpcserver.go
  lib/events/auditwriter.go
  lib/events/auditwriter_test.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/events/filelog.go
  lib/events/filelog_test.go
  lib/reversetunnel/remotesite.go
Labels: audit-log, database-access

#13078 [v9] Edit tctl instructions to clarify remote login
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/guides/dynamic-registration.mdx
  docs/pages/application-access/reference.mdx
  docs/pages/architecture/overview.mdx
  docs/pages/architecture/users.mdx
  docs/pages/database-access/guides/gui-clients.mdx
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/reference/cli.mdx
  docs/pages/desktop-access/troubleshooting.mdx
  docs/pages/enterprise/hsm.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/includes/user-client-prereqs.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/guides/cicd.mdx
  docs/pages/machine-id/getting-started.mdx
  docs/pages/setup/guides/ssh-key-extensions.mdx
  docs/pages/setup/reference/cli.mdx
Labels: documentation

#12183 Make the OpenSSH guide more usable
  docs/pages/architecture/tls-routing.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/vscode.mdx
  docs/pages/setup/operations/tls-routing.mdx
Labels: documentation

#13062 Reorganize the docs homepage menu
  docs/pages/index.mdx
Labels: documentation

#13154 Aurora serverless v2 support
  docs/pages/database-access/guides/rds.mdx
  lib/services/database.go
Labels: documentation, backport/branch/v9, backport/branch/v8

#13172 [v9] fix typo in RBAC guides.mdx
  docs/pages/access-controls/guides.mdx
Labels: documentation

#12564 Snowflake integration
  api/client/client.go
  api/client/events.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/constants.go
  api/types/jwt.go
  api/types/session.go
  go.mod
  go.sum
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/db.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/sessions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/client/identityfile/identity.go
  lib/defaults/defaults.go
  lib/jwt/jwt.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
  lib/services/identity.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/services/local/session.go
  lib/services/role.go
  lib/services/services.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/access_test.go
  lib/srv/db/server.go
  lib/srv/db/snowflake/cache.go
  lib/srv/db/snowflake/constants.go
  lib/srv/db/snowflake/engine.go
  lib/srv/db/snowflake/engine_test.go
  lib/srv/db/snowflake/http.go
  lib/srv/db/snowflake/models.go
  lib/srv/db/snowflake/test.go
  lib/srv/db/snowflake_test.go
  lib/teleterm/clusters/cluster_gateways.go
  tool/tctl/common/auth_command.go
  tool/tsh/db.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: tsh, tctl, database-access, merge-for-v10

#13142 Fix resource kinds for search
  api/types/constants.go
  lib/services/access_checker.go
  tool/tsh/access_request.go
Labels: tsh, merge-for-v10

#12916 SSH Session recording modes
  api/constants/constants.go
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  integration/integration_test.go
  lib/events/api.go
  lib/events/auditwriter.go
  lib/events/auditwriter_test.go
  lib/events/filesessions/filestream.go
  lib/events/filesessions/filestream_test.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
  lib/events/stream_test.go
  lib/services/access_checker.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/exec_test.go
  lib/srv/mock.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/utils/fs.go
  lib/web/resources_test.go
Labels: audit-log, merge-for-v10

#11631 RFD 68: Session recording modes
  rfd/0068-session-recording-modes.md
Labels: rfd

#13217 lib/events: remove no-op WaitForDelivery method
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/discard.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/filelog.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/writer.go
Labels: audit-log

#13002 Make `TestDefaultTemplateRendering` less failure prone
  lib/tbot/testhelpers/srv.go
Labels: backport/branch/v9

#12848 Implement proxy templates
  api/client/contextdialer.go
  api/client/webclient/webclient.go
  api/client/webclient/webclient_test.go
  api/defaults/defaults.go
  lib/client/api.go
  lib/client/keyagent.go
  lib/service/proxy_settings.go
  lib/web/apiserver.go
  rfd/0062-tsh-proxy-template.md
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
  tool/tsh/tshconfig.go
  tool/tsh/tshconfig_test.go
Labels: documentation, tsh, backport-required, rfd, merge-for-v10

#13132 Remove more deprecated code
  lib/auth/helpers.go
  lib/cache/collections.go
  lib/client/api.go
  lib/client/client_test.go
  lib/client/session.go
  lib/services/local/desktops.go
  lib/session/session.go
  lib/srv/db/access_test.go
  lib/srv/db/proxyserver_test.go
  lib/tlsca/ca.go
Labels: database-access

#13141 Move branching instructions to preflight checklist
  docs/postrelease.md
  docs/preflight.md
Labels: documentation

#13213 Add S3:AbortMultipartUpload to AWS IAM policies
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v7

#13028 Label desktops based on the content of LDAP attributes
  docs/pages/desktop-access/rbac.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/service/cfg.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/windows_server.go
Labels: documentation, desktop-access, backport/branch/v9

#12827 Fix help string for "tctl version"
  docs/pages/setup/reference/cli.mdx
  tool/tbot/main.go
  tool/tctl/common/tctl.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh.go
Labels: documentation, tctl, backport/branch/v9, backport/branch/v8, backport/branch/v7

#13208 Fix liveness probe endpoint
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
Labels: helm

#13247 Backport #13062 to branch/v9
  docs/pages/index.mdx
Labels: documentation

#13067 docs: Fix proxy config for GCP
  docs/pages/setup/deployments/gcp.mdx
Labels: documentation, gcp, backport/branch/v9

#13238 [v9] Label desktops based on the content of LDAP attributes
  docs/pages/desktop-access/rbac.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/service/cfg.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/windows_server.go
Labels: documentation, desktop-access

#13014 Buddy merge for #12182
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, backport/branch/v9

#13259 [v9] docs: Fix proxy config for GCP
  docs/pages/setup/deployments/gcp.mdx
Labels: documentation, gcp

#13235 [v9] Add S3:AbortMultipartUpload to AWS IAM policies
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/starter-cluster/cluster_iam.tf
Labels: documentation

#13044 Add short flag -c for --cluster in tsh
  tool/tsh/tsh.go
Labels: tsh

#12943 Remove outdated MySQL DBeaver note
  docs/config.json
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation, backport/branch/v9

#13016 Buddy merge for #11939
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
  examples/chart/CONTRIBUTING.md
  examples/chart/teleport-cluster/.lint/security-context-empty.yaml
  examples/chart/teleport-cluster/.lint/security-context.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/deployment_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport/branch/v9

#12288 Bump to libbpfgo v0.2.5
  go.mod
  go.sum
  lib/bpf/helper.go
  lib/restrictedsession/network.go
  lib/restrictedsession/restricted.go
Labels: bpf

#13237 Add missing flags to "tctl auth sign" docs
  docs/pages/setup/reference/cli.mdx
Labels: documentation, backport/branch/v9

#10456 Modernize role mapping in github connectors
  api/types/github.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/github.go
  lib/auth/github_test.go
  lib/auth/oidc.go
  lib/auth/oidc_test.go
  lib/auth/saml.go
  lib/auth/saml_test.go
  lib/services/github_test.go
  lib/web/resources_test.go
Labels: tctl, merge-for-v10

#13279 [v9] Add missing flags to "tctl auth sign" docs
  docs/pages/setup/reference/cli.mdx
Labels: documentation

#13177 Fix tctl Database CA compatibility with v9 cluster
  tool/tctl/common/auth_command.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/status_command.go
Labels: tctl, merge-for-v10

#13301 (v9) Security fixes
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  integration/agent_forwarding_test.go
  integration/app_integration_test.go
  integration/helpers.go
  lib/auth/apiserver_test.go
  lib/auth/grpcserver.go
  lib/httplib/httplib.go
  lib/httplib/httplib_test.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/srv/regular/sshserver.go
  lib/srv/termmanager.go
  lib/srv/termmanager_test.go
  lib/teleagent/agent.go
  lib/utils/fs.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
  lib/web/users_test.go
  tool/tsh/proxy_test.go
Labels: tsh

#13298 Security fixes
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  integration/agent_forwarding_test.go
  integration/app_integration_test.go
  integration/helpers.go
  lib/auth/apiserver_test.go
  lib/auth/grpcserver.go
  lib/httplib/httplib.go
  lib/httplib/httplib_test.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/srv/regular/sshserver.go
  lib/srv/termmanager.go
  lib/srv/termmanager_test.go
  lib/teleagent/agent.go
  lib/utils/fs.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
  lib/web/users_test.go
  tool/tsh/proxy_test.go
Labels: merge-for-v10

#13248 Backport #12183 to branch/v9
  docs/pages/architecture/tls-routing.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/vscode.mdx
  docs/pages/setup/operations/tls-routing.mdx
Labels: documentation

#12934 `tsh` list resources accross proxies and clusters
  integration/helpers.go
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
  lib/utils/errors.go
  tool/tsh/db.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: tsh, merge-for-v10

#13296 Use teams_to_roles in examples for GitHub SSO
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/reference/terraform-provider.mdx
Labels: documentation, merge-for-v10

#13289 Remove rdpclient Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.lock
Labels: rdp, desktop-access, merge-for-v10

#13220 Explicitly confirm or rollback Touch ID registrations
  lib/auth/touchid/api.go
  lib/auth/touchid/api_darwin.go
  lib/auth/touchid/api_other.go
  lib/auth/touchid/api_test.go
  lib/auth/touchid/credential_info.h
  lib/auth/touchid/credentials.h
  lib/auth/touchid/credentials.m
  tool/tsh/mfa.go
  tool/tsh/touchid.go
Labels: tsh, merge-for-v10

#13290 [v9] Remove rdpclient's Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.lock
Labels: rdp, desktop-access

#13243 IP-based validation for SSH
  api/types/types.pb.go
  api/types/types.proto
  integration/helpers.go
  integration/integration_test.go
  integration/proxy_helpers_test.go
  lib/auth/auth.go
  lib/auth/methods.go
  lib/auth/native/native.go
  lib/client/api.go
  lib/services/access_checker.go
  lib/services/authority.go
  lib/services/role.go
  lib/sshutils/server.go
  lib/web/resources_test.go
  tool/tctl/sso/tester/format_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: merge-for-v10

#13315 Release 9.3.4
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#13209 Added prerelease check to new APT promotion pipeline
  .drone.yml
  dronegen/misc.go
Labels: merge-for-v10

#13322 Update passwordless RFDs and mark as implemented
  rfd/0052-passwordless.md
  rfd/0053-passwordless-fido2.md
  rfd/0054-passwordless-macos.md
Labels: rfd

#13339 [v9] Update to 9.3.4 for self-hosted in docs
  docs/config.json
Labels: documentation

#13166 Deflake TestAgentForward
  lib/auth/helpers.go
  lib/events/stream.go
  lib/srv/regular/sshserver_test.go
Labels: audit-log, flaky tests, backport/branch/v9, backport/branch/v8

#13345 Fix AuditWriter tryResumeStream checking nil error
  lib/events/auditwriter.go
Labels: audit-log

#13311 [v9] Implement proxy templates
  api/client/contextdialer.go
  api/client/webclient/webclient.go
  api/client/webclient/webclient_test.go
  api/defaults/defaults.go
  lib/client/api.go
  lib/client/keyagent.go
  lib/service/proxy_settings.go
  lib/web/apiserver.go
  rfd/0062-tsh-proxy-template.md
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
  tool/tsh/tshconfig.go
  tool/tsh/tshconfig_test.go
Labels: tsh, rfd, backport/branch/v9

#13344 Update upcoming-releases.mdx
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#13352 [auto] Update AMI IDs for 9.3.4
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#13227 Fix file descriptor leaks in `tbot`
  lib/tbot/renew.go
  lib/tbot/tbot.go
Labels: machine-id, backport/branch/v9

#13337 SQLServer add suport for SSMS client
  lib/srv/db/sqlserver/connect.go
  lib/srv/db/sqlserver/engine.go
  lib/srv/db/sqlserver/protocol/login7.go
  lib/srv/db/sqlserver/protocol/packet.go
Labels: database-access

#12891 Add unicode clipboard support for Desktop Access
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
Labels: rdp, desktop-access, backport/branch/v9

#13255 [v9] Fix help string for "tctl version"
  docs/pages/setup/reference/cli.mdx
  tool/tbot/main.go
  tool/tctl/common/tctl.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh.go
Labels: documentation, tsh, tctl

#13286 [v9] Backport #13016 (Buddy merge for #11939)
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
  examples/chart/CONTRIBUTING.md
  examples/chart/teleport-cluster/.lint/security-context-empty.yaml
  examples/chart/teleport-cluster/.lint/security-context.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm

#13323 Prune roles for Resource Access Requests
  api/types/access_request.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tctl/common/access_request_command.go
  tool/tsh/tsh.go
Labels: tsh, tctl

#13326 Make tsh ssh --request the default
  lib/utils/utils.go
  rfd/0059-search-based-access-requests.md
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh

#13382 Restore terminal state on interrupt or exit
  lib/utils/prompt/context_reader.go
  lib/utils/prompt/context_reader_test.go
  lib/utils/prompt/stdin.go
  tool/tsh/tsh.go
Labels: tsh, backport-required

#13355 Deflake TestSessionRecordingModes
  lib/srv/sess_test.go
Labels: flaky tests

#13349 Forward kubernetes errors to user when running in remote exec mode
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/remotecommand.go
  lib/kube/proxy/sess.go
Labels: kubernetes-access, kubernetes, backport/branch/v9

#13358 [v9] Deflake TestAgentForward (#13166)
  lib/auth/helpers.go
  lib/events/stream.go
  lib/srv/regular/sshserver_test.go
Labels: audit-log

#12492 Add brief Q&A about how to setup recovery codes
  docs/pages/cloud/faq.mdx
Labels: documentation

#12931 Include Mac Enterprise tctl package.
  docs/pages/cloud/downloads.mdx
Labels: documentation, tsh, cloud, backport/branch/v9

#13372 SQLServer add suport for SSMS client
  lib/srv/db/sqlserver/connect.go
  lib/srv/db/sqlserver/protocol/login7.go
Labels: database-access

#13400 [v9] Forward kubernetes errors to user when running in remote exec mode
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/remotecommand.go
  lib/kube/proxy/sess.go
Labels: kubernetes

#13402 [v8] backport #13310 (use `auth_servers` when proxying)
  lib/reversetunnel/agent.go
  lib/reversetunnel/agentpool.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/localsite_test.go
  lib/reversetunnel/rc_manager.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/transport.go
  lib/service/service.go
  lib/srv/alpnproxy/auth/auth_proxy.go
  lib/srv/alpnproxy/auth/auth_proxy_test.go
  lib/srv/regular/sshserver_test.go
  lib/utils/utils.go
  lib/web/apiserver_test.go
Labels: backport

#13399 [v9] backport #13310 (use `auth_servers` when proxying)
  lib/reversetunnel/agent.go
  lib/reversetunnel/agentpool.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/localsite_test.go
  lib/reversetunnel/rc_manager.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/transport.go
  lib/service/service.go
  lib/srv/alpnproxy/auth/auth_proxy.go
  lib/srv/alpnproxy/auth/auth_proxy_test.go
  lib/srv/regular/sshserver_test.go
  lib/utils/utils.go
  lib/web/apiserver_test.go
Labels: backport

#13081 [v9] Add a more complete Teleport Cloud introduction
  docs/pages/cloud/introduction.mdx
Labels: documentation

#12828 Add port information for Cloud users
  docs/pages/cloud/faq.mdx
  docs/pages/setup/reference/networking.mdx
Labels: documentation

#13151 Rephrase the Teleport Cloud introduction
  docs/pages/cloud/introduction.mdx
Labels: documentation

#13356 Improve wording around regex example on resources documentation
  docs/pages/setup/reference/resources.mdx
Labels: documentation

#12950 Backport #12682 to branch/v9
  docs/pages/kubernetes-access/getting-started/agent.mdx
Labels: documentation

#12888 [v9] Backport docs PRs related to scoped visibility
  docs/config.json
  docs/pages/enterprise/fedramp.mdx
  docs/pages/enterprise/getting-started.mdx
  docs/pages/enterprise/hsm.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/license.mdx
  docs/pages/enterprise/soc2.mdx
  docs/pages/enterprise/workflow/index.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
  docs/pages/kubernetes-access/helm/guides.mdx
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/guides/digitalocean.mdx
  docs/pages/kubernetes-access/helm/guides/gcp.mdx
  docs/pages/kubernetes-access/helm/guides/migration.mdx
  docs/pages/kubernetes-access/helm/includes/teleport-cluster-cloud-warning.mdx
  docs/pages/kubernetes-access/helm/reference.mdx
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation

#12886 Backport #12742 to branch/v9
  docs/config.json
  docs/pages/setup/deployments.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/deployments/gcp.mdx
  docs/pages/setup/deployments/ibm.mdx
  docs/pages/setup/guides.mdx
  docs/pages/setup/guides/joining-nodes-aws-ec2.mdx
  docs/pages/setup/operations.mdx
  docs/pages/setup/operations/scaling.mdx
  docs/pages/setup/reference.mdx
  docs/pages/setup/reference/backends.mdx
Labels: documentation

#12882 Backport #12718 to branch/v9
  docs/config.json
  docs/pages/getting-started.mdx
  docs/pages/getting-started/digitalocean.mdx
  docs/pages/getting-started/docker-compose.mdx
  docs/pages/getting-started/linux-server.mdx
Labels: documentation

#13269 [v9] CamelCase GitHub
  docs/pages/access-controls/introduction.mdx
  docs/pages/application-access/jwt/introduction.mdx
  docs/pages/architecture/users.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/enterprise/fedramp.mdx
  docs/pages/enterprise/getting-started.mdx
  docs/pages/enterprise/introduction.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/faq.mdx
  docs/pages/getting-started/docker-compose.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/reference/authentication.mdx
  docs/pages/setup/reference/cli.mdx
  docs/pages/setup/reference/config.mdx
  docs/pages/setup/reference/resources.mdx
  docs/pages/setup/reference/terraform-provider.mdx
  docs/testplan.md
Labels: documentation

#13336 Deflake TestNoReadWhenOff
  lib/srv/termmanager.go
  lib/srv/termmanager_test.go
Labels: backport-required, flaky tests, backport/branch/v9

#13196 Backport of #10746 to v8
  .drone.yml
  build.assets/tooling/cmd/build-apt-repos/apt_repo_tool.go
  build.assets/tooling/cmd/build-apt-repos/aptly.go
  build.assets/tooling/cmd/build-apt-repos/config.go
  build.assets/tooling/cmd/build-apt-repos/main.go
  build.assets/tooling/cmd/build-apt-repos/repo.go
  build.assets/tooling/cmd/build-apt-repos/s3logger.go
  build.assets/tooling/cmd/build-apt-repos/s3manager.go
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  rfd/0058-package-distribution.md
Labels: rfd

#12880 Backport #12708 to branch/v9
  docs/config.json
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/moderated-sessions.mdx
Labels: documentation

#12881 Backport #12712 to branch/v9
  docs/config.json
Labels: documentation

#13373 Access request compatibility for servers without v2 api
  api/client/client.go
Labels: backport-required, backport/branch/v9, backport/branch/v8

#12685 Add de-duplicating apps, dbs, and desktops when sorting/totalCount is needed
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/app.go
  api/types/desktop.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver_test.go
  lib/cache/cache_test.go
  lib/services/local/desktops.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/matchers.go
  lib/services/matchers_test.go
  lib/web/apps.go
  lib/web/resources.go
  lib/web/resources_test.go
  lib/web/servers.go
Labels: backport-required, merge-for-v10

#13199 Backport of #13124 into v9
  build.assets/charts/Dockerfile
  build.assets/charts/Dockerfile-fips
Labels: backport/branch/v9

#13287 fix moderated sessions setter and getter
  api/types/license.go
  api/types/license_test.go
Labels: moderated-sessions

#13198 Backport of #13124 into v8
  build.assets/charts/Dockerfile
  build.assets/charts/Dockerfile-fips
Labels: backport/branch/v8

#13444 Upgrade Rust dependencies
  Cargo.lock
  lib/datalog/roletester/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, desktop-access

#13460 Remove uneeded GitHub mapping length check
  lib/auth/github.go
Labels: merge-for-v10

#13391 [v9] Backport #12891
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
Labels: rdp, desktop-access

#13463 Adjust `tctl sso` commands to new `teams_to_roles` field.
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/github.go
  tool/tctl/sso/configure/github.go
  tool/tctl/sso/configure/teams_to_roles.go
  tool/tctl/sso/configure/teams_to_roles_test.go
  tool/tctl/sso/tester/github.go
Labels: tctl, merge-for-v10

#13266 Add `sshLogins` to nodes endpoint on webapi (`GET /nodes`)
  lib/services/role.go
  lib/services/role_test.go
  lib/web/apiserver.go
  lib/web/ui/server.go
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
Labels: helm

#13203 [v9] Aurora serverless v2 support
  docs/pages/database-access/guides/rds.mdx
  lib/services/database.go
Labels: documentation, backport

#13422 Backport #13151 to branch/v9
  docs/pages/cloud/introduction.mdx
Labels: documentation

#13468 Update docs bash blocks to code
  docs/pages/enterprise/fedramp.mdx
  docs/pages/enterprise/getting-started.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/adfs.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
Labels: documentation, backport/branch/v9

#12407 Update SSO prereqs for consistency and include Teleport Cloud
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/adfs.mdx
  docs/pages/enterprise/sso/azuread.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
  docs/pages/setup/admin/github-sso.mdx
Labels: documentation, backport-required

#13214 [v8] Aurora serverless v2 support
  docs/pages/database-access/guides/rds.mdx
  lib/services/database.go
Labels: documentation, backport

#13459 Check for unimplemented error during stream receive in Client.GetAccessRequests
  api/client/client.go
  api/client/client_test.go
Labels: backport-required, backport/branch/v9

#13477 Deflake TestX11Forward
  lib/srv/regular/sshserver_test.go
Labels: backport-required, flaky tests, backport/branch/v9, backport/branch/v8

#13452 Drop rdpsnd messages
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access, backport/branch/v9

#13489 Fix CLI reference for the tsh --ttl flag
  docs/pages/setup/reference/cli.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v7

#12405 TDP Shared Directory Announce and Acknowledge
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/errors.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/flags.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
  lib/srv/desktop/tdp/proto.go
  lib/web/desktop/playback.go
Labels: rdp, desktop-access

#13500 Release 9.3.6
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#13486 [v9] Update docs bash blocks to code
  docs/pages/enterprise/fedramp.mdx
  docs/pages/enterprise/getting-started.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/sso/adfs.mdx
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/enterprise/sso/okta.mdx
  docs/pages/enterprise/sso/one-login.mdx
Labels: documentation, backport

#13205 Add webapi routes for fetching session trackers
  api/types/session_tracker.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport/branch/v9, merge-for-v10, backport/branch/v10

#13497 Release 10.0.0-alpha.1
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm

#13504 Improve HSM test reliability
  integration/hsm/hsm_test.go
  lib/auth/keystore/hsm.go
Labels: flaky tests, backport/branch/v9, backport/branch/v10

#13261 Add libbpf and Clang to Centos 7 image
  build.assets/Dockerfile-centos7
  build.assets/Makefile
Labels: bpf, server-access, backport/branch/v10

#13431 [v9] Include Mac Enterprise tctl package.
  docs/pages/cloud/downloads.mdx
Labels: documentation

#12006 RFD75: Snowflake Integration - Database Access
  rfd/0075-snowflake-support.md
Labels: rfd

#13532 Use `make release-windows` on Drone, make it similar to `make release`
  .drone.yml
  build.assets/Makefile
  dronegen/common.go
Labels: backport-required

#12346 Enterprise docker getting started fixes
  docs/pages/enterprise/getting-started.mdx
Labels: documentation, backport-required, backport/branch/v9, backport/branch/v10

#13528 Update versions to 11
  Makefile
  api/version.go
  build.assets/Makefile
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm

#13540 [v10] Use `make release-windows` on Drone, make it similar to `make release` (#13532)
  .drone.yml
  build.assets/Makefile
  dronegen/common.go
Labels: backport

#13392 Add MachineID and Resource Access Requests license features
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/license.go
  lib/modules/modules.go
  lib/services/license_test.go
Labels: backport/branch/v10

#12399 Clarify S3 get params
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10
