Repository gravitational/teleport, pull requests merged in 2022-04, with the labels that each got.

#11649 Release 9.0.3
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#11621 Remove references to authentication type 'false' from docs
  docs/pages/setup/reference/config.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport-required

#11387 Default to synchronous `FULL` for the sqlite backend
  lib/backend/lite/lite.go
Labels: backport-required, robustness

#9788 Fix kubernetes_service nil ptr dereference
  lib/kube/proxy/auth.go
  lib/kube/proxy/auth_test.go
Labels: kubernetes-access

#11603 fix tsh config test
  tool/tsh/tshconfig_test.go
Labels: tsh

#11658 [v9] backport #11386 #11387 (in-memory cache and sqlite sync)
  integration/helpers.go
  lib/backend/lite/lite.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/service.go
Labels: robustness, backport

#11660 [v7] backport #11386 #11387 (in-memory cache and sqlite sync)
  integration/helpers.go
  lib/backend/lite/lite.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/service.go
Labels: robustness, backport

#11659 [v8] backport #11386 #11387 (in-memory cache and sqlite sync)
  integration/helpers.go
  lib/backend/lite/lite.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/service.go
Labels: robustness, backport

#11629 [backport v9] Add metric to track number ssh connect attempts (#11240)
  docs/pages/setup/reference/metrics.mdx
  lib/srv/regular/proxy.go
  metrics.go
Labels: documentation

#11653 [auto] Update AMI IDs for 9.0.3
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#11586 [v9] Backport "docs: add note about user CA rotation + desktop access" (#10126)
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/setup/operations/ca-rotation.mdx
Labels: documentation

#11590 Spread out `UploadCompleter` load
  lib/events/complete.go
Labels: audit-log

#11638 Backport #11626 to branch/v9
  docs/pages/contributing/documentation/how-to-contribute.mdx
  docs/pages/contributing/documentation/issues.mdx
Labels: documentation

#11632 Backport #11477 to branch/v9
  docs/pages/includes/database-access/start-auth-proxy.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/setup/guides/fluentd.mdx
Labels: documentation

#11642 [v9 backport] Edit two guides for Cloud users
  docs/config.json
  docs/pages/architecture/tls-routing.mdx
  docs/pages/includes/tctl.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/recording-proxy-mode.mdx
  docs/pages/setup/operations/tls-routing.mdx
Labels: documentation

#11645 [v7 backport] Edit two guides for Cloud users
  docs/config.json
  docs/pages/includes/tctl.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/recording-proxy-mode.mdx
Labels: cloud-docs

#11635 Backport #11527 to branch/v9
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#11641 [v9] Minor edit for Reach Out on docs home page
  docs/pages/index.mdx
Labels: documentation, backport

#11295 helm: Add support for mounting existing TLS secrets with optional root CA
  examples/chart/teleport-cluster/.lint/existing-tls-secret-with-ca.yaml
  examples/chart/teleport-cluster/.lint/existing-tls-secret.yaml
  examples/chart/teleport-cluster/.lint/extra-env.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/config_test.yaml
  examples/chart/teleport-cluster/tests/deployment_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
Labels: helm, backport-required

#11306 docs: Add Helm docs for tls.existingSecretName
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
Labels: documentation, helm, backport-required

#11654 [forward-port] docs: Add Helm docs for tls.existingSecretName
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
Labels: documentation

#11616 Abstract-out chunked read logic
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/vchan.rs
Labels: rdp, desktop-access

#11656 [v9] backport #10386 : Add documentation for ssh key extensions with github
  docs/config.json
  docs/pages/access-controls/reference.mdx
  docs/pages/setup/guides.mdx
  docs/pages/setup/guides/ssh-key-extensions.mdx
Labels: documentation

#11650 Updates minimum terraform version to 1.0
  docs/config.json
Labels: documentation

#11651 [v9] Updates minimum terraform version to 1.0
  docs/config.json
Labels: documentation

#11614 [v9] backport #9788
  lib/kube/proxy/auth.go
  lib/kube/proxy/auth_test.go
Labels: kubernetes

#11682 New Getting started video for Teleport 9
  docs/pages/getting-started/linux-server.mdx
Labels: documentation

#11661 Broadcast controls keys if session is moderated
  lib/kube/proxy/sess.go
  lib/srv/sess.go
Labels: kubernetes

#11657 [v9] Backport: fix tsh config test (#11603)
  tool/tsh/tshconfig_test.go
Labels: tsh

#11663 [v9] Add support for backward compatible API Client behavior
  api/profile/profile.go
  api/utils/keypaths/keypaths.go
  lib/client/keystore.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
Labels: tsh, backport

#11689 Support building for amd64 windows on arm64 hosts
  Makefile
Labels: release-engineering

#11534 Add grpc server and client metrics to Teleport
  go.mod
  go.sum
  lib/auth/middleware.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service.go
  lib/utils/prometheus.go
  metrics.go
Labels: observability, cloud

#11647 Fix session leave + termination deadlock
  lib/srv/sess.go
Labels: backport-required

#10785 Generate database access credentials with tctl auth sign command
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
Labels: tctl

#11708 Kube agent instructions on matching to server version
  docs/pages/includes/tctl.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
Labels: documentation, cloud, kubernetes

#11711 [v9] Kube agent instructions on matching to server version
  docs/pages/includes/tctl.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
Labels: documentation, backport

#11702 [v9] Split Redis docs
  docs/config.json
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
  docs/pages/includes/database-access/guides.mdx
  docs/pages/includes/database-access/redis-connect.mdx
  docs/pages/includes/database-access/redis-create-users.mdx
Labels: documentation, backport

#11684 Support proxy protocol v2
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/multiplexer/proxyline.go
Labels: enhancement, networking

#11693 helm: Buddy merge for #11493
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/deployment_test.yaml
Labels: helm, backport-required

#11531 Add documentation for the tsh config file
  docs/pages/setup/reference/cli.mdx
Labels: documentation

#11696 [branch/v7] Spread out `UploadCompleter` load (#11590)
  lib/events/complete.go
Labels: backport

#11706 [branch/v8] Clean up remoteSites with no active tunnels (#11435)
  lib/reversetunnel/api.go
  lib/reversetunnel/fake.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/peer.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/srv/db/access_test.go
Labels: backport

#11698 [branch/v9] Spread out `UploadCompleter` load (#11590)
  lib/events/complete.go
Labels: audit-log, backport

#11726 update teleport 9 and cloud versions in docs
  docs/config.json
Labels: documentation

#11732 [v9] Updated cloud-config example due to install failures
  docs/pages/getting-started/linux-server.mdx
Labels: documentation, backport

#11705 [branch/v7] Clean up remoteSites with no active tunnels (#11435)
  lib/reversetunnel/api.go
  lib/reversetunnel/fake.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/peer.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/srv/db/access_test.go
Labels: backport

#11707 [branch/v9] Clean up remoteSites with no active tunnels (#11435)
  lib/reversetunnel/api.go
  lib/reversetunnel/fake.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/peer.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/srv/db/access_test.go
Labels: database-access, backport

#11700 Updated cloud-config example due to install failures
  docs/pages/getting-started/linux-server.mdx
Labels: documentation

#11722 [branch/v9] Support proxy protocol v2 (#11684)
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/multiplexer/proxyline.go
Labels: backport

#11697 [branch/v8] Spread out `UploadCompleter` load (#11590)
  lib/events/complete.go
Labels: backport

#9593 Create Database CA
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/authority.go
  api/types/trust.go
  docs/pages/includes/database-access/rotation-note.mdx
  integration/db_integration_test.go
  integration/helpers.go
  integration/integration_test.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/db.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/auth/middleware.go
  lib/auth/rotate.go
  lib/auth/rotate_test.go
  lib/auth/state.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
  lib/cache/collections.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/srv.go
  lib/service/desktop.go
  lib/service/service.go
  lib/services/authority.go
  lib/services/watcher.go
  lib/services/watcher_test.go
  lib/srv/app/server.go
  lib/srv/db/access_test.go
  lib/srv/db/ca_test.go
  lib/srv/db/common/test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
  lib/utils/ver.go
  lib/utils/ver_test.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/status_command.go
Labels: tctl, database-access

#11685 Install script changes and sudo command updates for Teleport install and configure
  docs/pages/includes/acme.mdx
  docs/pages/includes/install-linux.mdx
Labels: documentation, ux, backport-required

#11750 [v9] Install script changes and sudo command updates for Teleport install and configure
  docs/pages/includes/acme.mdx
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport

#10899 Add client cert in insecure mode
  lib/srv/db/access_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/test.go
Labels: backport-required, database-access

#10707 Release automation improvements
  .drone.yml
  dronegen/common.go
  dronegen/mac.go
  dronegen/mac_pkg.go
  dronegen/tag.go
Labels: cloud

#11667 Backport SQL Backend to v9
  go.mod
  go.sum
  lib/backend/backend.go
  lib/backend/backend_test.go
  lib/backend/dynamo/dynamodbbk.go
  lib/backend/etcdbk/etcd.go
  lib/backend/firestore/firestorebk.go
  lib/backend/lite/lite.go
  lib/backend/memory/memory.go
  lib/backend/postgres/backend.go
  lib/backend/postgres/backend_test.go
  lib/backend/postgres/doc.go
  lib/backend/postgres/driver.go
  lib/backend/postgres/migrate.go
  lib/backend/postgres/schema.go
  lib/backend/postgres/tx.go
  lib/backend/report.go
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
  lib/backend/sqlbk/backend.go
  lib/backend/sqlbk/backend_test.go
  lib/backend/sqlbk/background.go
  lib/backend/sqlbk/config.go
  lib/backend/sqlbk/doc.go
  lib/backend/sqlbk/driver.go
  lib/backend/sqlbk/test.go
  lib/backend/test/suite.go
  lib/backend/wrap.go
  lib/config/configuration.go
  lib/service/service.go
  lib/srv/db/postgres/test.go
Labels: database-access

#11422 Document limitations with the Google OIDC connector and transitive group memberships
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
Labels: documentation

#11768 Bump rdp-rs
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access

#11771 Fix `data_dir` comment referencing link that doesn't exist
  docs/pages/setup/reference/config.mdx
Labels: documentation

#11737 Fix race condition in TestIntegrations - Disconnection
  lib/srv/sess.go
Labels: moderated-sessions

#11742 [v9] Add Cloud instructions to five guides
  docs/pages/database-access/architecture.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
Labels: documentation

#11741 Move Cloud download binaries into tables
  docs/pages/cloud/downloads.mdx
Labels: documentation

#11785 Release 9.0.4
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#11778 [v8] backport #11422 (Google OIDC docs update)
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
Labels: documentation, backport

#11777 [v9] backport #11422 (Google OIDC docs update)
  docs/pages/enterprise/sso/gitlab.mdx
  docs/pages/enterprise/sso/google-workspace.mdx
  docs/pages/enterprise/sso/oidc.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
Labels: documentation, backport

#11789 update docs 9 release version to 9.0.4
  docs/config.json
Labels: documentation

#11721 Mark RFD 63 as implemented, update details
  rfd/0063-teleport-terminal.md
Labels: rfd

#11609 Fix key principals not being used when identity files are being used
  lib/client/api.go
  lib/client/api_test.go
  tool/tsh/tsh.go
Labels: tsh

#11249 Ensure stateOK is reported only when all components have sent updates
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/service/state_test.go
  lib/srv/heartbeat.go
Labels: cloud

#11793 [v9] backport #11609
  lib/client/api.go
  lib/client/api_test.go
  tool/tsh/tsh.go
Labels: tsh

#11773 [backport v9] Add grpc server and client metrics to Teleport
  go.mod
  go.sum
  lib/auth/middleware.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service.go
  lib/utils/prometheus.go
  metrics.go
Labels: backport

#11720 Add "tunnel" mode to tsh proxy db
  lib/client/db/postgres/connstring.go
  lib/client/db/postgres/connstring_test.go
  lib/srv/db/access_test.go
  lib/srv/db/local_proxy_test.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/sqlserver/proxy.go
  lib/teleterm/gateway/gateway.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/dbcmd.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: tsh, database-access, teleterm-backport

#11442 Backport #10880 to branch/v9
  docs/pages/setup/reference/metrics.mdx
Labels: documentation

#11776 [backport v8] Add grpc server and client metrics to Teleport (#11534)
  go.mod
  go.sum
  lib/auth/middleware.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/connect.go
  lib/service/service.go
  lib/utils/prometheus.go
  metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/client_interceptor.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/client_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/constants.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/server_interceptor.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/openmetrics/v2/server_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go
  vendor/modules.txt
Labels: backport

#11772 [v9] Fix session leave + termination deadlock
  lib/srv/sess.go
Labels: backport

#11803 [v9] Moderated Sessions rollup backport
  docs/pages/access-controls/guides/moderated-sessions.mdx
  integration/integration_test.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/session_access.go
  lib/kube/proxy/sess.go
  lib/srv/sess.go
  lib/srv/termmanager.go
  lib/srv/termmanager_test.go
  lib/web/terminal.go
Labels: documentation, kubernetes

#11808 (v9) Add auth'd tunnel mode to tsh proxy db command
  lib/client/db/postgres/connstring.go
  lib/client/db/postgres/connstring_test.go
  lib/srv/db/access_test.go
  lib/srv/db/local_proxy_test.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/sqlserver/proxy.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/dbcmd.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: tsh, database-access, backport

#11800 Return error message if supplied auth connector name doesn't match registered names.
  api/client/webclient/webclient.go
  lib/web/apiserver.go
  tool/tsh/tsh.go
Labels: tsh

#11787 [auto] Update AMI IDs for 9.0.4
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#11804 Mention scoped Admonitions
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#11668 Edit Database Access guides for Cloud users
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/guides-next-steps.mdx
  docs/pages/includes/database-access/start-auth-proxy.mdx
  docs/pages/includes/database-access/tctl-auth-sign.mdx
  docs/pages/includes/database-access/token.mdx
  docs/pages/includes/database-access/ttl-note.mdx
  docs/pages/includes/user-client-prereqs.mdx
Labels: documentation, cloud-docs

#11716 RFD: Passwordless cluster settings
  rfd/0052-passwordless.md
  rfd/0053-passwordless-fido2.md
  rfd/0054-passwordless-macos.md
Labels: rfd

#11781 Make relogin attempts use the strongest auth method
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/client.go
  lib/client/mfa.go
  lib/client/presence.go
  lib/client/weblogin.go
  tool/tsh/mfa.go
Labels: tsh

#11758 [v9] Add client cert in insecure mode
  lib/srv/db/access_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/test.go
Labels: database-access, backport

#11551 Replace session upload grace period with session tracker
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/session_tracker.go
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/auditlog_test.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/mock.go
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/filestream.go
  lib/events/filesessions/fileuploader.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/services/local/sessiontracker.go
  lib/srv/regular/sshserver_test.go
  lib/srv/sess.go
Labels: audit-log, backport-required

#11761 [v9] Access Control, K8s Cluster docs set scope and AWS first
  docs/pages/access-controls/getting-started.mdx
  docs/pages/includes/dns.mdx
  docs/pages/kubernetes-access/getting-started/cluster.mdx
Labels: documentation, backport

#11760 include cloud scope for access control getting started
  docs/pages/access-controls/getting-started.mdx
Labels: documentation, backport-required

#11764 Terraform Ref: add base64 to provider options
  docs/pages/setup/reference/terraform-provider.mdx
Labels: documentation

#11848 [v8] Make relogin attempts use the strongest auth method (#11781)
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/client.go
  lib/client/mfa.go
  lib/client/weblogin.go
  tool/tsh/mfa.go
Labels: backport

#11869 [v9] update golang version in docs config to 1.17
  docs/config.json
Labels: documentation

#11864 Add bullet to k8s access intro on deploying teleport within k8s
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation, kubernetes-access, backport-required

#11874 [v9] Add bullet to k8s access intro on deploying teleport within k8s
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation, kubernetes-access, backport

#11847 [v9] Make relogin attempts use the strongest auth method (#11781)
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/client.go
  lib/client/mfa.go
  lib/client/presence.go
  lib/client/weblogin.go
  tool/tsh/mfa.go
Labels: tsh, backport

#11843 Quote postgres connection string for printing to terminals
  lib/client/db/postgres/connstring.go
  lib/client/db/postgres/connstring_test.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/dbcmd.go
Labels: tsh, backport-required

#11846 [v9] Edit Database Access guides for Cloud users
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/guides-next-steps.mdx
  docs/pages/includes/database-access/start-auth-proxy.mdx
  docs/pages/includes/database-access/tctl-auth-sign.mdx
  docs/pages/includes/database-access/token.mdx
  docs/pages/includes/database-access/ttl-note.mdx
  docs/pages/includes/user-client-prereqs.mdx
Labels: documentation

#11853 [v9] Replace session upload grace period with session tracker
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/session_tracker.go
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/filestream.go
  lib/events/filesessions/fileuploader.go
  lib/events/gcssessions/gcsstream.go
  lib/events/mock.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/services/local/sessiontracker.go
  lib/srv/regular/sshserver_test.go
  lib/srv/sess.go
Labels: audit-log, backport

#11870 update golang version in docs config to 1.17
  docs/config.json
Labels: documentation

#11528 Add tsh proxy templates RFD
  rfd/0062-tsh-proxy-template.md
Labels: rfd

#11447 Add tsh aliases RFD
  rfd/0061-tsh-aliases.md
Labels: rfd

#11828 Display elapsed time in render-tests output
  build.assets/tooling/cmd/render-tests/main.go
Labels: release-engineering

#11710 Extract tabbed Prerequisites into a partial
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/restricted-session.mdx
  docs/pages/server-access/guides/vscode.mdx
  docs/pages/setup/admin/adding-nodes.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/admin/labels.mdx
  docs/pages/setup/admin/users.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/guides/fluentd.mdx
  docs/pages/setup/guides/joining-nodes-aws-iam.mdx
  docs/pages/setup/guides/terraform-provider.mdx
  docs/pages/setup/operations/ca-rotation.mdx
Labels: documentation, cloud-docs

#11889 [v9] NO_PROXY port support + special case for proxying via localhost
  api/client/contextdialer.go
  api/client/noproxy.go
  api/client/proxy.go
  api/client/proxy/proxy.go
  api/client/proxy/proxy_test.go
  api/client/proxy_test.go
  api/client/webclient/webclient.go
  integration/helpers.go
  integration/integration_test.go
  integration/proxy_helpers_test.go
  integration/proxy_test.go
  lib/client/https_client.go
  lib/utils/proxy/proxy.go
Labels: backport

#11882 SQL Backend Documentation
  docs/pages/setup/reference/backends.mdx
Labels: documentation

#11421 Forward-port "helm: Add details on AWS ACM to AWS guide (#10857)"
  docs/pages/kubernetes-access/helm/guides/aws.mdx
  docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
Labels: documentation, helm

#11735 Updated RFD 000: RFDs
  rfd/0000-rfds.md
Labels: rfd

#11822 Align atomics on ARM32
  lib/backend/memory/memory.go
  lib/reversetunnel/conn.go
  lib/srv/keepalive_test.go
  lib/utils/conn.go
Labels: backport-required

#11885 [v8] Return error message if supplied auth connector name doesn't match registered names. (#11800)
  api/client/webclient/webclient.go
  lib/web/apiserver.go
  tool/tsh/tsh.go
Labels: backport

#10801 Edit three guides to support Cloud users
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference/authentication.mdx
Labels: documentation, cloud-docs

#11838 Edit four Access Controls guides for Cloud users
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/includes/plugins/rbac.mdx
Labels: documentation, cloud-docs

#11801 Edit the Database Access GUI guide for Cloud users
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation, cloud-docs

#11839 Backport #11741 to branch/v9
  docs/pages/cloud/downloads.mdx
Labels: documentation

#11617 Update teleport-plugin guides to reference docker images for downloads
  docs/config.json
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/setup/guides/fluentd.mdx
Labels: documentation

#10996 Prepare more Setup guides for Cloud users
  docs/pages/setup/deployments/gcp.mdx
  docs/pages/setup/deployments/ibm.mdx
  docs/pages/setup/operations/tls-routing.mdx
  docs/pages/setup/reference/cli.mdx
  docs/pages/setup/reference/resources.mdx
  docs/pages/setup/security/reduce-blast-radius.mdx
Labels: documentation, cloud-docs

#11714 reuse `vchan::Client` to add the general header and break messages into chunks
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
  lib/srv/desktop/rdp/rdpclient/src/vchan.rs
Labels: rdp, desktop-access

#11886 [v7] Return error message if supplied auth connector name doesn't match registered names. (#11800)
  api/client/webclient/webclient.go
  lib/web/apiserver.go
  tool/tsh/tsh.go
Labels: backport

#11897 Backport v9: SQL Backend Documentation
  docs/pages/setup/reference/backends.mdx
Labels: documentation

#11731 Edit Redis guides for Cloud users
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
Labels: documentation, cloud-docs

#11934 [branch/v9] Update teleport-plugin guides to reference docker images for downloads
  docs/pages/enterprise/workflow/ssh-approval-jira-cloud.mdx
  docs/pages/enterprise/workflow/ssh-approval-jira-server.mdx
  docs/pages/enterprise/workflow/ssh-approval-mattermost.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/setup/guides/fluentd.mdx
Labels: documentation

#11718 Fix Okta OIDC
  constants.go
  go.mod
  go.sum
  lib/auth/oidc.go
Labels: release-notes, docs-required, backport-required

#10458 Make `tsh db ls` lists available db users.
  lib/services/role.go
  lib/services/role_test.go
  tool/tsh/db.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, teleterm-backport

#11912 [v9] Change bash blocks to code
  docs/pages/api/architecture.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/includes/database-access/sql-server-local-proxy.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
  docs/pages/kubernetes-access/getting-started/local.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/reference/cli.mdx
Labels: documentation, backport

#11910 Change bash blocks to code
  docs/pages/api/architecture.mdx
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/enterprise/sso.mdx
  docs/pages/enterprise/workflow/ssh-approval-pagerduty.mdx
  docs/pages/includes/database-access/sql-server-local-proxy.mdx
  docs/pages/includes/enterprise/oidcauthentication.mdx
  docs/pages/includes/enterprise/samlauthentication.mdx
  docs/pages/kubernetes-access/getting-started/local.mdx
  docs/pages/kubernetes-access/helm/guides/custom.mdx
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/reference/cli.mdx
Labels: documentation, backport-required, cli

#11381 Add Teleport Cloud instructions to two guides
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/restricted-session.mdx
Labels: documentation, cloud-docs

#11884 [v9] Return error message if supplied auth connector name doesn't match registered names. (#11800)
  api/client/webclient/webclient.go
  lib/web/apiserver.go
  tool/tsh/tsh.go
Labels: tsh, backport

#10738 Edit four docs guides for Cloud users
  docs/pages/setup/admin/graceful-restarts.mdx
  docs/pages/setup/admin/labels.mdx
  docs/pages/setup/admin/troubleshooting.mdx
  docs/pages/setup/admin/users.mdx
Labels: documentation, cloud-docs

#11949 [v9] Add audit logging for more MySQL commands (#11914)
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/events.go
  lib/srv/db/mysql/protocol/command.go
  lib/srv/db/mysql/protocol/packet.go
  lib/srv/db/mysql/protocol/packet_test.go
  lib/srv/db/mysql/protocol/response.go
  lib/srv/db/mysql/protocol/statement.go
Labels: audit-log, database-access, backport

#11953 04/14 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#11977 [v9] Edit four Access Controls guides for Cloud users
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/moderated-sessions.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/includes/plugins/rbac.mdx
Labels: documentation

#11971 Backport #10738 to branch/v9
  docs/pages/setup/admin/graceful-restarts.mdx
  docs/pages/setup/admin/labels.mdx
  docs/pages/setup/admin/troubleshooting.mdx
  docs/pages/setup/admin/users.mdx
Labels: documentation

#11900 Backport #11804 to branch/v9
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#9875 Run TestAccessMongoDB in parallel
  lib/srv/db/access_test.go
  lib/srv/db/mongodb/test.go
Labels: database-access

#11851 [v9] Fix race condition in (*sess). broadcastResult()
  lib/srv/sess.go
Labels: backport

#11836 Implement "tsh request search"
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/types/constants.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/events/oneof.go
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/permissions.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/services/role.go
  tool/tsh/access_request.go
  tool/tsh/tsh.go
Labels: tsh, audit-log

#11938 Add ap-south-1 (Mumbai) as a cloud proxy region
  docs/pages/cloud/architecture.mdx
Labels: documentation

#11922 [v9] helm: Add support for mounting existing TLS secrets with optional root CA (#11295)
  examples/chart/teleport-cluster/.lint/existing-tls-secret-with-ca.yaml
  examples/chart/teleport-cluster/.lint/existing-tls-secret.yaml
  examples/chart/teleport-cluster/.lint/extra-env.yaml
  examples/chart/teleport-cluster/templates/config.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
Labels: helm, backport

#11940 docs: Don't lint external links
  build.assets/Makefile
Labels: backport-required

#11923 [v9] helm: Set default second factor to "otp" in values (#11034)
  examples/chart/teleport-cluster/values.yaml
Labels: helm, backport

#11956 (v9) Delete app sessions on logout
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  integration/app_integration_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/client/client.go
  lib/services/identity.go
  lib/services/local/session.go
  lib/services/local/session_test.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
Labels: backport

#11924 [v9] Remove references to authentication type 'false' from docs (#11621)
  docs/pages/setup/reference/config.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport

#11948 Document Okta OIDC provider workaround
  docs/pages/enterprise/sso.mdx
Labels: documentation, backport-required

#11944 [v9] Backport Okta OIDC Fixes
  constants.go
  go.mod
  go.sum
  lib/auth/oidc.go
Labels: backport

#11965 Backport #11801 to branch/v9
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation

#11960 [v9] Extract tabbed Prerequisites into a partial
  docs/pages/access-controls/getting-started.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/access-controls/guides/impersonation.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/kubernetes-access/getting-started/agent.mdx
  docs/pages/kubernetes-access/guides/multiple-clusters.mdx
  docs/pages/kubernetes-access/guides/standalone-teleport.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/guides/restricted-session.mdx
  docs/pages/server-access/guides/vscode.mdx
  docs/pages/setup/admin/adding-nodes.mdx
  docs/pages/setup/admin/github-sso.mdx
  docs/pages/setup/admin/labels.mdx
  docs/pages/setup/admin/users.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/guides/fluentd.mdx
  docs/pages/setup/guides/joining-nodes-aws-iam.mdx
  docs/pages/setup/guides/terraform-provider.mdx
  docs/pages/setup/operations/ca-rotation.mdx
Labels: documentation

#11998 [v9] Backport "Document Okta OIDC provider workaround" (#11948)
  docs/pages/enterprise/sso.mdx
Labels: documentation

#11982 [v9] Prepare five guides for Cloud users
  docs/pages/enterprise/getting-started.mdx
  docs/pages/includes/enterprise/docker-images.mdx
  docs/pages/includes/image.mdx
  docs/pages/setup/guides/docker.mdx
  docs/pages/setup/guides/ec2-tags.mdx
  docs/pages/setup/reference/audit.mdx
  docs/pages/setup/reference/backends.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation

#11996 [v9] Backport: docs: Don't lint external links (#11940)
  build.assets/Makefile
Labels: backport

#7986 RFD 64: Bot for certificate renewals (Machine ID)
  rfd/0064-bot-for-cert-renewals.md
Labels: rfd

#11903 Mention ScopedBlock in the UI reference
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#12003 [v8] Backport: docs: Don't lint external links (#11940)
  build.assets/Makefile
Labels: backport

#11964 Backport #10801 to branch/v9
  docs/pages/setup/operations/backup-restore.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference/authentication.mdx
Labels: documentation
