Repository gravitational/teleport, pull requests merged in 2022-05, with the labels that each got.

#12334 [v7] Specify the `NodeName` in `auth.ReRegister`
  integration/integration_test.go
  lib/service/connect.go
Labels: backport

#12332 [v8] Specify the `NodeName` in `auth.ReRegister`
  integration/integration_test.go
  lib/service/connect.go
Labels: backport

#12333 [v9] Specify the `NodeName` in `auth.ReRegister`
  integration/integration_test.go
  lib/service/connect.go
Labels: backport

#12347 Fix Windows build
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
  lib/srv/db/dbutils/constants.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/proxyserver.go
Labels: database-access

#11526 File Transfer RFD
  rfd/0058-desktop-file-transfer.md
Labels: rfd

#12096 Harden SQLite permissions
  lib/backend/lite/lite.go
Labels: backport-required

#12353 moved status page cloud question up in order
  docs/pages/cloud/faq.mdx
Labels: documentation, backport-required

#12275 Limit Kubernetes connections
  api/types/semaphore.go
  api/types/types.pb.go
  api/types/types.proto
  integration/kube_integration_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/sess.go
  lib/services/role.go
Labels: kubernetes

#12295 Handle DynamoDB pay-per-request mode correctly
  lib/events/dynamoevents/dynamoevents.go
Labels: audit-log

#12344 Add MySQL ALPN proto to 'tsh proxy db'
  lib/srv/db/server.go
  tool/tsh/db.go
  tool/tsh/proxy.go
Labels: tsh

#12339 [v9] backport #12262 (Improve error message for resource predicate query)
  lib/services/matchers.go
  lib/services/parser.go
  lib/utils/cli.go
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
  tool/tsh/db.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: tsh, tctl, backport

#11987 Backport #11985 to branch/v9
  docs/pages/setup/operations/scaling.mdx
Labels: documentation

#12307 Support creation of search-based access requests
  api/types/access_request.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/tls_test.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/web/apiserver.go
  lib/web/sessions.go
  tool/tsh/access_request.go
  tool/tsh/tsh.go
Labels: tsh

#12340 [v9] Advertise correct MySQL server version
  api/types/database.go
  api/types/database_test.go
  api/types/events/api.go
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/database-access/database-config.yaml
  go.mod
  go.sum
  integration/proxy_helpers_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/cfg_test.go
  lib/service/db.go
  lib/service/service.go
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/local_proxy_test.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
  lib/srv/db/access_test.go
  lib/srv/db/dbutils/constants.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/engine_test.go
  lib/srv/db/mysql/protocol/version.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/mysql/test.go
  lib/srv/db/proxy_test.go
  lib/srv/db/proxyserver.go
  lib/srv/db/proxyserver_test.go
  lib/srv/db/server.go
  lib/teleterm/gateway/gateway.go
  tool/tsh/aws.go
  tool/tsh/db.go
  tool/tsh/proxy.go
  tool/tsh/tsh_test.go
Labels: documentation, tsh, database-access

#12361 Never use `--tlsUseSystemCA` and `--tlsCAFile` together with `mongosh`
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
Labels: tsh, backport-required, backport, backport/branch/v9

#12343 Release 9.1.3
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#12302 Fix lingerAndDie race condition
  lib/srv/sess.go
  lib/srv/sess_test.go
Labels: backport-required

#12364 Updated release dates in Machine ID documentation.
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/ansible.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/introduction.mdx
Labels: documentation, backport/branch/v9

#12377 [auto] Update AMI IDs for 9.1.3
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#12374 [v9] Updated release dates in Machine ID documentation.
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/ansible.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/introduction.mdx
Labels: documentation

#12314 Updates terraform docs for provider
  docs/pages/setup/guides/terraform-provider.mdx
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation

#12354 [v9] moved status page cloud question up in order
  docs/pages/cloud/faq.mdx
Labels: documentation, backport

#12355 Show Proxy version when `tsh version` is called
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh

#12360 [v9] Rollup backport
  api/types/semaphore.go
  api/types/types.pb.go
  api/types/types.proto
  integration/kube_integration_test.go
  lib/auth/oidc.go
  lib/backend/lite/lite.go
  lib/events/dynamoevents/dynamoevents.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/sess.go
  lib/services/role.go
Labels: audit-log, kubernetes

#12384 (v9) Update DBeaver guides to use authenticated local proxy.
  docs/img/database-access/dbeaver-configure-server.png
  docs/img/database-access/dbeaver-pg-configure-server.png
  docs/img/database-access/dbeaver-ssl.png
  docs/img/database-access/dbeaver-tls-settings.png
  docs/img/database-access/guides/sqlserver/dbeaver-connection@2x.png
  docs/pages/database-access/guides/gui-clients.mdx
Labels: documentation, backport

#12376 [v9] Fix lingerAndDie race condition
  lib/srv/sess.go
  lib/srv/sess_test.go
Labels: flaky tests

#12273 Add a UI reference entry for code blocks
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#12385 cloud version in user prereq was using current self-hosted
  docs/pages/includes/user-client-prereqs.mdx
Labels: documentation, backport-required

#12386 [v9] cloud version in user prereq was using current self-hosted
  docs/pages/includes/user-client-prereqs.mdx
Labels: documentation, backport

#12382 [v9] Update docs version to 9.1.3 self-hosted, 9.1.2 for cloud
  docs/config.json
Labels: documentation

#12380 Fix tunnel mode for CockroachDB
  lib/srv/db/proxyserver.go
Labels: database-access, backport/branch/v9

#12392 use t.TempDir for all tsh tests
  tool/tsh/proxy_test.go
Labels: tsh

#12401 Deflake TestTSHSSH
  tool/tsh/tsh_helper_test.go
Labels: tsh, flaky tests

#12402 [v9] Deflake TestTSHSSH
  lib/srv/app/server_test.go
  tool/tsh/tsh_helper_test.go
Labels: tsh

#12400 [v9] Fix tunnel mode for CockroachDB
  lib/srv/db/proxyserver.go
Labels: database-access

#11508 Changes for `tctl sso test`, `tctl sso configure` commands [SAML]
  api/go.mod
  api/go.sum
  api/types/assertion_info.go
  api/types/assertion_info_test.go
  api/types/traits.go
  api/types/types.pb.go
  api/types/types.proto
  go.mod
  lib/auth/apiserver.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/saml.go
  lib/auth/saml_test.go
  lib/auth/sso_diag_context.go
  lib/auth/sso_diag_context_test.go
  lib/client/api.go
  lib/client/redirect.go
  lib/client/weblogin.go
  lib/events/codes.go
  lib/services/identity.go
  lib/services/identity_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  lib/services/saml.go
  lib/services/saml_test.go
  lib/teleterm/clusters/cluster_auth.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/saml.go
Labels: sso, audit-log

#11320 Database agents to share same IAM policy
  api/types/database.go
  lib/services/semaphore_test.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/server.go
Labels: database-access, backport/branch/v9

#12074 Make the Troubleshooting guide more usable
  docs/pages/setup/admin/troubleshooting.mdx
Labels: documentation, cloud-docs

#12395 lib/events: Remove Legacy (Teleport 4.4) upload handler
  lib/events/auditlog.go
  lib/events/auditlog_test.go
  lib/service/service.go
Labels: audit-log

#12427 Release 9.2.0
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#11963 Add hint message when removing access requests.
  tool/tctl/common/access_request_command.go
Labels: tctl

#12442 [v9] Update docs version to 9.2.0
  docs/config.json
Labels: documentation

#11868 Fix RDS Redshift dynamic resources registration logic
  api/types/constants.go
  lib/srv/db/watcher.go
  lib/srv/db/watcher_test.go
Labels: backport-required, database-access, backport/branch/v9, backport/branch/v8

#12445 Add nil check for billing mode in AWS DynamoDB events driver
  lib/events/dynamic.go
  lib/events/dynamic_test.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/events/test/suite.go
Labels: audit-log, backport-required, backport/branch/v9

#12461 [v9] Add nil check for billing mode in AWS DynamoDB events driver
  lib/events/dynamic.go
  lib/events/dynamic_test.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
  lib/events/test/suite.go
Labels: audit-log

#12435 [v9] Add hint message when removing access requests. (#11963)
  tool/tctl/common/access_request_command.go
Labels: tctl

#12462 Only acquire semaphore lease if maxconnections is configured
  integration/kube_integration_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/services/semaphore.go
  lib/services/suite/suite.go
  lib/srv/regular/sshserver.go
Labels: backport-required, kubernetes, backport/branch/v9

#12458 Add roles needed in dynamic reg app and db docs
  docs/pages/application-access/guides/dynamic-registration.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
Labels: documentation, backport-required, application-access, database-access

#12469 [v9] Add roles needed in dynamic reg app and db docs
  docs/pages/application-access/guides/dynamic-registration.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
Labels: documentation, backport

#12468 [v9] Only acquire semaphore lease if maxconnections is configured
  integration/kube_integration_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/services/semaphore.go
  lib/services/suite/suite.go
  lib/srv/regular/sshserver.go
Labels: kubernetes

#11144 Don't enforce standard k8s and ssh auth mechanisms when joining sessions
  api/types/session_tracker.go
  constants.go
  integration/kube_integration_test.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/session_access.go
  lib/auth/tls_test.go
  lib/client/api.go
  lib/client/client.go
  lib/client/kubesession.go
  lib/client/session.go
  lib/kube/proxy/forwarder.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/forward/sshserver.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
  lib/srv/termhandlers.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: kubernetes-access, tsh, backport-required, moderated-sessions

#12457 [v9] Database agents to share same IAM policy (#11320)
  api/types/database.go
  lib/services/semaphore_test.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/server.go
Labels: database-access, backport

#12472 Release 9.2.1
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#12378 Add Q&A about moving from cloud to self-hosted/etc
  docs/pages/cloud/faq.mdx
Labels: documentation, cloud-docs

#12476 [v9] Update docs version to 9.2.1
  docs/config.json
Labels: documentation

#12451 [v9] Fix RDS Redshift dynamic resources registration logic
  api/types/constants.go
  lib/srv/db/watcher.go
  lib/srv/db/watcher_test.go
Labels: database-access, backport

#12431 Backport #12074 to branch/v9
  docs/pages/setup/admin/troubleshooting.mdx
Labels: documentation

#11802 Proxy restart fixes
  integration/integration_test.go
  lib/cache/cache.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/reversetunnel/remotesite.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/signals.go
  lib/service/supervisor.go
  lib/srv/alpnproxy/listener.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/app/listener.go
  lib/sshutils/server.go
  lib/utils/errors.go
  lib/utils/loadbalancer.go
Labels: robustness, backport/branch/v9, backport/branch/v8, backport/branch/v7

#12478 Upgrade gravitational/kingpin to latest master (8b7839c62700)
  go.mod
  go.sum
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v7

#12390 Desktop access: add teleport.dev/ou label
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
Labels: backport-required, desktop-access, backport/branch/v9, backport/branch/v8

#12502 [v9] Desktop access: add teleport.dev/ou label
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
Labels: desktop-access

#12475 Wire touch ID login and registration to tsh
  lib/auth/touchid/api.go
  lib/auth/touchid/attempt.go
  lib/auth/webauthncli/api.go
  lib/auth/webauthncli/u2f_login.go
  lib/client/api.go
  lib/client/client.go
  lib/client/mfa.go
  lib/client/presence.go
  lib/client/weblogin.go
  tool/tsh/mfa.go
  tool/tsh/tsh.go
Labels: tsh

#12499 `CGOError` --> `CGOErrCode`
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/errors.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access

#12471 Re-add grace period to Upload completer for backwards compatibility.
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/mock.go
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/filestream.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: audit-log, backport-required

#12531 shared directory build tag
  lib/srv/desktop/dir_sharing_disabled.go
  lib/srv/desktop/dir_sharing_enabled.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, desktop-access

#12530 Restructure `rdpdr.rs` into a multi file module
  lib/srv/desktop/dir_sharing_disabled.go
  lib/srv/desktop/dir_sharing_enabled.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/librdprs.h
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, desktop-access

#12497 Refactor non-interactive sessions out of proxy/sess.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/sess.go
Labels: refactoring, backport-required, kubernetes, backport/branch/v9

#12503 docs: mention new desktop label for OU
  docs/pages/desktop-access/rbac.mdx
Labels: documentation, backport/branch/v9

#12535 [v9] Re-add grace period to Upload completer for backwards compatibility
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/filestream.go
  lib/events/gcssessions/gcsstream.go
  lib/events/mock.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
  lib/service/db.go
  lib/service/kubernetes.go
  lib/service/service.go
Labels: audit-log

#11879 Use new TLS key to sign DB cert during rotation
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  lib/auth/db.go
  lib/auth/keystore/keystore.go
  lib/srv/db/auth_test.go
  tool/tctl/common/auth_command.go
Labels: tctl, database-access, backport/branch/v9

#12559 feat(helm): add priorityClassName and extraLabels to kube-agent
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/.lint/priority-class-name.yaml
  examples/chart/teleport-kube-agent/templates/clusterrole.yaml
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/pdb.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/secret.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/clusterrole_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/clusterrolebinding_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/config_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/pdb_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/psp_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/secret_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/serviceaccount_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/clusterrole_test.yaml
  examples/chart/teleport-kube-agent/tests/clusterrolebinding_test.yaml
  examples/chart/teleport-kube-agent/tests/config_test.yaml
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/pdb_test.yaml
  examples/chart/teleport-kube-agent/tests/psp_test.yaml
  examples/chart/teleport-kube-agent/tests/secret_test.yaml
  examples/chart/teleport-kube-agent/tests/serviceaccount_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport/branch/v9

#12414 Includes Audit Log into common sso Troubleshooting
  docs/pages/enterprise/sso.mdx
  docs/pages/includes/sso/loginerrortroubleshooting.mdx
Labels: documentation, backport-required

#12570 Re-add PAM build tag back to `tctl` build
  Makefile
Labels: backport-required, backport/branch/v9

#12568 feat(helm): add priorityClassName and extraLabels to kube-agent (#12559)
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/.lint/priority-class-name.yaml
  examples/chart/teleport-kube-agent/templates/clusterrole.yaml
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/config.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/pdb.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/secret.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm

#12428 Backport #12273 to branch/v9
  docs/pages/contributing/documentation/reference.mdx
Labels: documentation

#12369 [v9] Make the Installation guide more usable
  docs/config.json
  docs/pages/installation.mdx
Labels: documentation

#11747 Backports #11743
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
Labels: documentation, backport

#12585 Fix linter after Go 1.18 upgrade
  .golangci.yml
  build.assets/Dockerfile
  integration/integration_test.go
  lib/events/gcssessions/gcsstream_test.go
  lib/srv/regular/sshserver_test.go
  lib/web/apiserver_test.go
Labels: audit-log

#12567 App access JWT improvements
  constants.go
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/jwt.mdx
  integration/app_integration_test.go
  lib/jwt/jwt.go
  lib/jwt/jwt_test.go
  lib/services/role.go
  lib/srv/app/session.go
Labels: documentation, application-access, backport/branch/v9

#12528 Ports `docs` redirects from nginx-redirects.conf
  docs/config.json
Labels: documentation, backport-required

#11743 fixes duplicate meta description for SEO purposes
  docs/pages/kubernetes-access/helm/reference/teleport-kube-agent.mdx
Labels: documentation, backport-required

#12490 Scope requested resource IDs by cluster and resource kind
  api/types/access_request.go
  api/types/events/events.pb.go
  api/types/events/events.proto
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/access_request.go
  tool/tsh/tsh.go
Labels: tsh

#12565 [v9] Includes Audit Log into common sso Troubleshooting
  docs/pages/enterprise/sso.mdx
  docs/pages/includes/sso/loginerrortroubleshooting.mdx
Labels: documentation, backport

#12550 Add in example groups for k8s control role
  docs/pages/kubernetes-access/controls.mdx
Labels: documentation, kubernetes-access, backport-required

#12589 [v9] App access JWT improvements
  constants.go
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/application-access/guides/jwt.mdx
  integration/app_integration_test.go
  lib/jwt/jwt.go
  lib/jwt/jwt_test.go
  lib/services/role.go
  lib/srv/app/session.go
Labels: documentation, application-access

#12590 [v9] Adds optional deployment key for CI (#10506)
  .cloudbuild/ci/integration-tests.yaml
  .cloudbuild/ci/unit-tests.yaml
  .cloudbuild/scripts/cmd/integration-tests/args.go
  .cloudbuild/scripts/cmd/integration-tests/main.go
  .cloudbuild/scripts/cmd/unit-tests/main.go
  .cloudbuild/scripts/go.mod
  .cloudbuild/scripts/go.sum
  .cloudbuild/scripts/internal/git/configure.go
  .cloudbuild/scripts/internal/git/deploykey.go
  .cloudbuild/scripts/internal/git/knownhosts.go
  .cloudbuild/scripts/internal/git/unshallow.go
  .cloudbuild/scripts/internal/github/meta.go
  .cloudbuild/scripts/internal/secrets/fetch.go
Labels: backport

#12563 [v9] Add in example groups for k8s control role
  docs/pages/kubernetes-access/controls.mdx
Labels: documentation, backport

#12577 Remove legacy migration code from DynamoDB event driver
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log

#12592 [v9] Ignore HTTP_PROXY in reverse tunnels, part 2 (#12335)
  api/client/client.go
  api/client/contextdialer.go
  integration/proxy_test.go
  lib/auth/authclient/authclient.go
  lib/auth/clt.go
  lib/reversetunnel/resolver.go
  lib/service/connect.go
Labels: backport

#12304 Add Session tracker to DB, App, and Windows Desktop Sessions
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/defaults/defaults.go
  api/types/events/events.pb.go
  api/types/session_tracker.go
  api/types/types.pb.go
  api/types/types.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/moderated_sessions_test.go
  lib/defaults/defaults.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/kube/proxy/sess.go
  lib/services/local/sessiontracker.go
  lib/services/local/sessiontracker_test.go
  lib/services/sessiontracker.go
  lib/srv/app/server.go
  lib/srv/app/session.go
  lib/srv/db/access_test.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/sessiontracker.go
  lib/srv/sessiontracker_test.go
  tool/tsh/tsh_test.go
Labels: audit-log, backport-required, application-access, database-access, desktop-access, kubernetes

#12591 [v8] Ignore HTTP_PROXY in reverse tunnels, part 2 (#12335)
  api/client/client.go
  api/client/contextdialer.go
  integration/proxy_test.go
  lib/auth/authclient/authclient.go
  lib/auth/clt.go
  lib/reversetunnel/resolver.go
  lib/service/connect.go
Labels: backport

#12548 [v9] docs: mention new desktop label for OU
  docs/pages/desktop-access/rbac.mdx
Labels: documentation

#12358 Replace title-less Details boxes with ScopedBlocks
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/reference/cli.mdx
Labels: documentation

#12496 Update Teleport Cloud FAQ
  docs/pages/cloud/architecture.mdx
  docs/pages/cloud/faq.mdx
Labels: documentation

#12038 Make the Daemon guide easier to follow
  docs/config.json
  docs/pages/setup/admin.mdx
  docs/pages/setup/admin/daemon.mdx
  docs/pages/setup/deployments/aws-terraform.mdx
Labels: documentation

#12119 Make the Graceful Restarts guide more usable
  docs/config.json
  docs/pages/setup/admin.mdx
  docs/pages/setup/admin/graceful-restarts.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference.mdx
  docs/pages/setup/reference/signals.mdx
Labels: documentation

#12236 Make the Linux Server guide more usable
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/acme.mdx
  docs/pages/includes/dns.mdx
  docs/pages/includes/permission-warning.mdx
Labels: documentation

#12541 [v9] Refactor non-interactive sessions out of proxy/sess.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/sess.go
Labels: kubernetes

#12566 Link to Interactive Teleport Labs
  docs/img/application-access/app-access.mp4
  docs/img/application-access/app-access.webm
  docs/img/k8s/k8-access.mp4
  docs/img/k8s/k8-access.webm
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/getting-started.mdx
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8

#12611 [v9] Add Session tracker to DB, App, and Windows Desktop Sessions
  Makefile
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice.proto
  api/defaults/defaults.go
  api/types/session_tracker.go
  api/types/types.pb.go
  api/types/types.proto
  build.assets/gomod/print-import-path/main.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/moderated_sessions_test.go
  lib/defaults/defaults.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/kube/proxy/sess.go
  lib/services/local/sessiontracker.go
  lib/services/local/sessiontracker_test.go
  lib/services/sessiontracker.go
  lib/srv/app/server.go
  lib/srv/app/session.go
  lib/srv/db/access_test.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/sessiontracker.go
  lib/srv/sessiontracker_test.go
  tool/tsh/tsh_test.go
Labels: tsh, audit-log, application-access, database-access, desktop-access, kubernetes

#12604 05/12 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#12216 Update signup link in cloud getting started
  docs/pages/cloud/getting-started.mdx
Labels: documentation, backport-required

#12310 Add notes that master is a development branch in readme
  README.md
Labels: documentation

#12621 Release 9.2.2
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#12623 Release 9.2.3
  .drone.yml
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm

#12477 Fixes typo in Terraform provider docs
  docs/pages/setup/guides/terraform-provider.mdx
Labels: documentation

#12598 Implement global tsh config file: `/etc/tsh.yaml`
  docs/pages/setup/reference/cli.mdx
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
  tool/tsh/tshconfig.go
  tool/tsh/tshconfig_test.go
Labels: documentation, tsh, backport-required, backport/branch/v9, backport/branch/v8

#12546 [v7] Proxy restart fixes
  integration/integration_test.go
  lib/cache/cache.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/reversetunnel/remotesite.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/signals.go
  lib/service/supervisor.go
  lib/srv/app/listener.go
  lib/srv/app/server_test.go
  lib/sshutils/server.go
  lib/utils/errors.go
  lib/utils/loadbalancer.go
Labels: backport

#12557 Client timeout fixes
  api/client/webclient/webclient.go
  lib/utils/proxy/proxy.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v7

#12209 ElastiCache support - the basics
  .github/ISSUE_TEMPLATE/testplan.md
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  api/types/types.proto
  api/utils/aws/endpoint.go
  api/utils/aws/endpoint_test.go
  api/utils/aws/region.go
  api/utils/aws/region_test.go
  lib/config/configuration.go
  lib/config/database.go
  lib/config/fileconf.go
  lib/configurators/databases/aws.go
  lib/configurators/databases/aws_test.go
  lib/configurators/databases/databases.go
  lib/service/cfg.go
  lib/service/db.go
  lib/services/database.go
  lib/services/database_test.go
  lib/services/matchers.go
  lib/srv/db/ca.go
  lib/srv/db/cloud/meta.go
  lib/srv/db/cloud/meta_test.go
  lib/srv/db/cloud/mocks.go
  lib/srv/db/cloud/watchers/elasticache.go
  lib/srv/db/cloud/watchers/rds.go
  lib/srv/db/cloud/watchers/redshift.go
  lib/srv/db/cloud/watchers/watcher.go
  lib/srv/db/cloud/watchers/watcher_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/cloud.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/connection.go
  lib/srv/db/redis/engine.go
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh_test.go
Labels: feature-request, database-access

#12632 [v9] Client timeout fixes
  api/client/webclient/webclient.go
  lib/utils/proxy/proxy.go
Labels: backport

#12633 [v8] Client timeout fixes
  api/client/webclient/webclient.go
  lib/utils/proxy/proxy.go
Labels: backport

#12634 [v7] Client timeout fixes
  api/client/webclient/webclient.go
Labels: backport

#12620 [v9] Link to Interactive Teleport Labs
  docs/img/application-access/app-access.mp4
  docs/img/application-access/app-access.webm
  docs/img/k8s/k8-access.mp4
  docs/img/k8s/k8-access.webm
  docs/pages/application-access/getting-started.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/getting-started.mdx
  docs/pages/kubernetes-access/introduction.mdx
Labels: documentation

#12631 [v9] update docs version to 9.2.3
  docs/config.json
Labels: documentation

#12626 [v9] Implement global tsh config file: `/etc/tsh.yaml` (#12598)
  docs/pages/setup/reference/cli.mdx
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
  tool/tsh/tshconfig.go
  tool/tsh/tshconfig_test.go
Labels: documentation, tsh

#12418 Adds key resources to `Teleport resources` section
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport/branch/v9

#12372 ssh: Ignore PuTTY-specific channel requests
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/req.go
Labels: backport/branch/v9

#12486 tctl: Respect TELEPORT_HOME value when grabbing profile
  lib/client/api.go
  tool/tctl/common/tctl.go
  tool/tsh/tctl_test.go
Labels: tctl

#12488 [v9] Proxy restart fixes
  integration/integration_test.go
  lib/cache/cache.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/reversetunnel/remotesite.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/signals.go
  lib/service/supervisor.go
  lib/srv/alpnproxy/listener.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/app/listener.go
  lib/sshutils/server.go
  lib/utils/errors.go
  lib/utils/loadbalancer.go
Labels: backport

#12608 Backport #12358 to branch/v9
  docs/pages/includes/plugins/rbac.mdx
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/reference/cli.mdx
Labels: documentation

#11719 RFD 66: IP-based validation
  rfd/0066-ip-based-validation.md
Labels: rfd

#12669 [v9] Optionally skip unshallowing step (#10978)
  .cloudbuild/scripts/cmd/integration-tests/args.go
  .cloudbuild/scripts/cmd/integration-tests/main.go
  .cloudbuild/scripts/cmd/unit-tests/main.go
Labels: backport

#12595 [v9] Updates terraform docs for provider (#12314)
  docs/pages/setup/guides/terraform-provider.mdx
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation, backport

#12540 Listener hygiene
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/service/service.go
  lib/service/signals.go
  lib/srv/alpnproxy/listener.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v7

#12694 [v7] Listener hygiene
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/service/service.go
  lib/service/signals.go
Labels: backport

#12693 [v8] Listener hygiene
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
  lib/multiplexer/wrappers.go
  lib/service/service.go
  lib/service/signals.go
  lib/srv/alpnproxy/listener.go
Labels: backport

#12684 RBAC for directory sharing
  api/types/role.go
  api/types/types.pb.go
  api/types/types.proto
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/desktop/windows_server.go
  lib/web/resources_test.go
Labels: docs-required, desktop-access

#12519 Changes for `tctl sso test`, `tctl sso configure` commands [OIDC]
  api/types/oidc_external.go
  api/types/oidc_external_test.go
  api/types/types.pb.go
  api/types/types.proto
  constants.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/oidc.go
  lib/auth/oidc_google.go
  lib/auth/oidc_test.go
  lib/auth/saml.go
  lib/services/identity.go
  lib/services/identity_test.go
  lib/services/local/users.go
  lib/services/oidc.go
  lib/services/oidc_test.go
  lib/web/apiserver.go
  rfd/0070-tctl-sso-configure-command.md
  tool/tsh/tsh_test.go
Labels: rfd

#11715 RFD 67 - Redis database access in AWS ElastiCache and MemoryDB
  rfd/0067-database-access-aws-redis
Labels: rfd

#12655 Backports redirects from #12528, adds indexing page
  docs/config.json
  docs/pages/older-versions.mdx
Labels: documentation

#12656 adds enterprise/sso redirect from teleport app
  docs/config.json
Labels: documentation

#12728 [v9] Fix session tracker backwards compatibility.
  .gitignore
  lib/events/complete.go
  lib/srv/app/session.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
Labels: audit-log, application-access, database-access, desktop-access

#12663 Update Teleport Cloud FAQ (#12496)
  docs/pages/cloud/architecture.mdx
  docs/pages/cloud/faq.mdx
Labels: documentation

#12667 Upgrade MySQL driver to v1.5.0
  go.mod
  go.sum
  integration/db_integration_test.go
  lib/srv/db/access_test.go
  lib/srv/db/common/errors.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/protocol/packet.go
  lib/srv/db/mysql/protocol/statement.go
  lib/srv/db/mysql/protocol/version.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/mysql/test.go
  lib/srv/db/server_test.go
Labels: database-access, backport/branch/v9, backport/branch/v8

#12726 [v8] Backport add ExactKey function to create absolute storage paths
  lib/backend/backend.go
  lib/services/local/presence.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  lib/services/local/usertoken.go
Labels: backport

#12732 Add Video Banner for Installing Teleport page
  docs/pages/installation.mdx
Labels: documentation, backport/branch/v9

#12740 Ensure h2 has precedence over http/1.1
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
Labels: backport/branch/v9, backport/branch/v8

#12648 Backport #12236 to branch/v9
  docs/pages/getting-started/linux-server.mdx
  docs/pages/includes/acme.mdx
  docs/pages/includes/dns.mdx
  docs/pages/includes/permission-warning.mdx
Labels: documentation

#12645 Backport #12119 to branch/v9
  docs/config.json
  docs/pages/setup/admin.mdx
  docs/pages/setup/admin/graceful-restarts.mdx
  docs/pages/setup/operations/upgrading.mdx
  docs/pages/setup/reference.mdx
  docs/pages/setup/reference/signals.mdx
Labels: documentation

#12768 Adds `/older-versions` index page
  docs/pages/older-versions.mdx
Labels: documentation, backport/branch/v8, backport/branch/v7

#10607 Update slack docs to reflect latest changes
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/enterprise/workflow/ssh-approval-slack.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/impersonations.mdx
  docs/pages/includes/plugins/rbac.mdx
  examples/resources/plugins/teleport-slack-configure.toml
  examples/resources/plugins/teleport-slack-proxy.toml
  examples/resources/plugins/teleport-slack.toml
Labels: documentation

#12765 05/19 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation

#12775 Add hostlogin to proxy config for windows desktop
  lib/auth/middleware.go
  lib/utils/tlsdial.go
  lib/web/desktop.go
Labels: desktop-access, backport/branch/v9

#12690 Set MULTI_RESULTS and MULTI_STATEMENTS MySQL client CAP
  lib/srv/db/mysql/engine.go
Labels: database-access, backport/branch/v9, backport/branch/v8

#12776 Remove non-https facets from documentation
  docs/pages/access-controls/guides/u2f.mdx
  docs/pages/setup/reference/config.mdx
Labels: documentation, backport-required

#12781 [v9] Add hostlogin to proxy config for windows desktop
  lib/auth/middleware.go
  lib/utils/tlsdial.go
  lib/web/desktop.go
Labels: desktop-access

#12734 [v9] Upgrade MySQL driver to v1.5.0 and set missing mysql client cap
  go.mod
  go.sum
  integration/db_integration_test.go
  lib/srv/db/access_test.go
  lib/srv/db/common/errors.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/protocol/packet.go
  lib/srv/db/mysql/protocol/statement.go
  lib/srv/db/mysql/protocol/version.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/mysql/test.go
  lib/srv/db/server_test.go
Labels: database-access, backport

#12556 Update our list of support databases
  docs/pages/database-access/introduction.mdx
Labels: documentation

#12788 Release 9.2.4
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-kube-agent/Chart.yaml
  version.go
Labels: helm
