Repository gravitational/teleport, pull requests merged in 2022-10, with the labels that each got.

#16868 [v10] Fix client idle timeout ending sessions too early
  lib/reversetunnel/srv.go
  lib/srv/ctx.go
  lib/srv/forward/sshserver.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/ctx.go
  lib/sshutils/server.go
Labels: backport

#16924 [auto] Update AMI IDs for 10.3.1
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated

#16875 Fix background database local proxy termination by SIGINT signal
  tool/tsh/db.go
Labels: tsh, database-access, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16896 Remove Apache license headers from BPF modules
  bpf/enhancedrecording/command.bpf.c
  bpf/enhancedrecording/counter_test.bpf.c
  bpf/enhancedrecording/disk.bpf.c
  bpf/enhancedrecording/network.bpf.c
  bpf/restrictedsession/restricted.bpf.c
Labels: bpf

#16926 [v10] Fixes Dismiss Stale Workflows Runs GitHub Actions
  .github/workflows/dismiss.yaml
Labels: backport

#16928 [v9] Fixes Dismiss Stale Workflows Runs GitHub Actions
  .github/workflows/dismiss.yaml
Labels: backport

#16876 Add option to disable the `ServiceAccount` creation for `teleport-kube-agent chart`
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/rolebinding.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/serviceaccount_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm

#16911 V11 prep: compare and swap hb & begin explicit namespace deprecation
  lib/service/service.go
  lib/services/local/presence.go
Labels: merge-for-v11

#16886 [v9] bump cloud version
  docs/config.json
Labels: documentation, backport

#16770 [Docs] Update 'Using Teleport Connect' for Linux & Windows
  docs/img/use-teleport/connect-cluster.png
  docs/img/use-teleport/connect-ui-overview.png
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport/branch/v10

#16755 Azure Cache for Redis auto discovery
  .github/ISSUE_TEMPLATE/testplan.md
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  api/utils/azure/fuzz_test.go
  api/utils/azure/location.go
  api/utils/azure/location_test.go
  lib/cloud/azure/db_server.go
  lib/cloud/azure/interfaces.go
  lib/cloud/azure/mocks.go
  lib/cloud/azure/redis.go
  lib/cloud/azure/redis_enterprise.go
  lib/cloud/azure/redis_enterprise_test.go
  lib/cloud/azure/redis_test.go
  lib/cloud/azure/subscriptions.go
  lib/cloud/azure/subscriptions_test.go
  lib/cloud/clients.go
  lib/config/database.go
  lib/services/database.go
  lib/services/database_test.go
  lib/services/matchers.go
  lib/srv/db/cloud/watchers/azure.go
  lib/srv/db/cloud/watchers/azure_dbserver.go
  lib/srv/db/cloud/watchers/azure_redis.go
  lib/srv/db/cloud/watchers/azure_redis_enterprise.go
  lib/srv/db/cloud/watchers/watcher.go
  lib/srv/db/cloud/watchers/watcher_test.go
  lib/srv/db/common/auth_test.go
  lib/srv/db/redis/engine.go
  tool/teleport/common/teleport.go
  tool/tsh/tsh_test.go
Labels: feature-request, database-access, azure, db/redis, merge-for-v11

#16945 [v10] [Docs] Update 'Using Teleport Connect' for Linux & Windows
  docs/img/use-teleport/connect-cluster.png
  docs/img/use-teleport/connect-ui-overview.png
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport

#16857 [Docs] Update and Align Metric Reference
  docs/pages/reference/metrics.mdx
Labels: documentation, backport/branch/v10

#16939 Improve BPF tests
  lib/bpf/bpf_test.go
Labels: bpf, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16811 [v10] docs: mention that WindowsDesktop now supports EC2 join
  docs/pages/management/guides/joining-nodes-aws-ec2.mdx
Labels: documentation, backport

#16902 Use hostname for resource kind server with predicate query by name
  docs/pages/reference/predicate-language.mdx
  lib/services/access_request.go
  lib/services/parser.go
  lib/services/parser_test.go
  tool/tsh/tsh.go
Labels: documentation, backport/branch/v9, backport/branch/v10

#10690 Upgrade System RFD (v2)
  rfd/0090-upgrade-system.md
Labels: rfd

#14794 Add message for "certificate has expired" error on database connect
  docs/config.json
  docs/pages/database-access/introduction.mdx
  docs/pages/database-access/troubleshooting.mdx
  lib/srv/db/common/errors.go
  lib/srv/db/redis/engine.go
Labels: tsh, database-access, merge-for-v11

#16943 Refactor TestResolveEndpoints to avoid test failure when AWS SDK changes
  lib/srv/app/aws/endpoints_test.go
Labels: application-access

#16897 [v10] Add docs for IdP-initiated SSO
  docs/img/azuread/azuread-5-turnoffuserassign.png
  docs/img/azuread/azuread-8-entityandreplyurl.png
  docs/img/sso/okta/setup-redirection.png
  docs/pages/access-controls/sso.mdx
  docs/pages/access-controls/sso/azuread.mdx
  docs/pages/access-controls/sso/okta.mdx
  docs/pages/includes/sso/idp-initiated.mdx
  examples/resources/saml-connector.yaml
Labels: documentation, backport

#15790 First pass on proxy peering docs
  docs/config.json
  docs/img/architecture/proxy-peering@1.2x.svg
  docs/pages/architecture/proxy-peering.mdx
  docs/pages/management/operations.mdx
  docs/pages/management/operations/proxy-peering.mdx
  docs/pages/reference/config.mdx
  docs/pages/reference/networking.mdx
Labels: documentation

#16848 [Docs] Correct protocol name
  docs/pages/architecture/tls-routing.mdx
  rfd/0039-sni-alpn-teleport-proxy-routing.md
Labels: documentation, rfd, backport/branch/v9, backport/branch/v8, backport/branch/v10

#16947 Delete deprecated code related to ListResources
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/types/app.go
  api/types/appserver.go
  lib/auth/api.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/usertoken.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/client/client.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
  lib/services/suite/suite.go
  lib/srv/app/server_test.go
  lib/srv/heartbeat.go
  lib/srv/heartbeat_test.go
  tool/tctl/common/app_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/node_command.go
  tool/tsh/app.go
  tool/tsh/db.go
  tool/tsh/kube.go
Labels: tsh, tctl, application-access

#16997 [v9] [Docs] Correct protocol name
  docs/pages/architecture/tls-routing.mdx
  rfd/0039-sni-alpn-teleport-proxy-routing.md
Labels: documentation, rfd, backport

#16995 [v10] [Docs] Correct protocol name
  docs/pages/architecture/tls-routing.mdx
  rfd/0039-sni-alpn-teleport-proxy-routing.md
Labels: documentation, rfd, backport

#17013 correct plugin name reference
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  examples/resources/plugins/teleport-msteams.toml
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#17000 Ensure operator tests are run when Go dependencies change
  .cloudbuild/scripts/internal/changes/changes.go
Labels: backport/branch/v10

#17019 [v10] correct plugin name reference
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  examples/resources/plugins/teleport-msteams.toml
Labels: documentation, backport

#17036 Missing spaces in on/offboarding section
  docs/pages/index.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#17007 Revert change from PKCS1 to PKCS8
  lib/auth/native/native.go
  lib/auth/native/native_test.go
Labels: backport/branch/v10

#17035 Remove [direct] dependency on go.uber.org/atomic
  .golangci.yml
  go.mod
  go.sum
  lib/cache/cache.go
  lib/client/keystore_test.go
  lib/events/auditwriter.go
  lib/events/auditwriter_test.go
  lib/events/filesessions/fileasync_chaos_test.go
  lib/events/filesessions/fileasync_test.go
  lib/events/filesessions/fileuploader_test.go
  lib/events/gcssessions/gcsstream_test.go
  lib/events/stream.go
  lib/inventory/store.go
  lib/services/fanout.go
  lib/srv/app/server_test.go
  lib/utils/fncache_test.go
  lib/utils/interval/interval_test.go
  lib/utils/workpool/workpool.go
  tool/tsh/tsh_test.go
Labels: tsh, audit-log, application-access

#16988 [v9] Refactor TestResolveEndpoints to avoid test failure when AWS SDK changes
  lib/srv/app/aws/endpoints_test.go
Labels: application-access, backport

#16980 Simplify curl interpolation in tsh output.
  tool/tsh/app.go
Labels: tsh

#17039 [v10] Missing spaces in on/offboarding section
  docs/pages/index.mdx
Labels: documentation, backport

#16870 Fix test-go-root make target and tbot init tests
  Makefile
  tool/tbot/init_test.go
Labels: machine-id

#16938 GitHub Actions joining
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/types.pb.go
  go.mod
  go.sum
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/bot.go
  lib/auth/join.go
  lib/auth/join_github.go
  lib/auth/join_github_test.go
  lib/auth/register.go
  lib/githubactions/githubactions.go
  lib/githubactions/token_source.go
  lib/githubactions/token_source_test.go
  lib/githubactions/token_validator.go
  lib/githubactions/token_validator_test.go
  lib/service/service.go
  lib/tbot/config/config.go
  lib/tbot/renew.go
  tool/tbot/main.go
Labels: machine-id, merge-for-v11

#16977 Add a legacy Heartbeat to Kubernetes clusters to maintain support for older clients
  integration/ec2_test.go
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
  lib/kube/proxy/utils_test.go
  lib/srv/heartbeat.go
Labels: kubernetes-access, merge-for-v11

#17048 fix: data race in NodeSession.runCommand
  lib/client/session.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v7, backport/branch/v10

#17040 [v9] Missing spaces in on/offboarding section
  docs/pages/index.mdx
Labels: documentation, backport

#17030 Address U2F sunset TODOs
  api/constants/constants.go
  api/proto/teleport/legacy/types/types.proto
  api/types/authentication.go
  api/types/authentication_authpreference_test.go
  lib/auth/init_test.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/services/local/resource.go
  operator/crdgen/testdata/protofiles/types.proto
Labels: merge-for-v11

#17076 [v7] fix: data race in NodeSession.runCommand
  lib/client/session.go
Labels: backport

#17065 [v9] Finalize CI release API integration
  .drone.yml
  dronegen/mac.go
  dronegen/mac_pkg.go
  dronegen/relcli.go
  dronegen/tag.go
Labels: backport

#17091 [v10] Update on-prem version in docs
  docs/config.json
Labels: documentation, backport

#17075 [v8] fix: data race in NodeSession.runCommand
  lib/client/session.go
Labels: backport

#17018 AWS Terraform App Access, DB listeners variables
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10

#17104 Bump version in master to 12.0.0-dev
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm

#17103 Release 11.0.0-alpha.1
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#17107 Release 11.0.0-alpha.2
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  operator/Dockerfile
  version.go
Labels: helm, backport

#17114 Set RFD83 status to implemented (v10.3.0)
  rfd/0083-machine-id-host-certs.md
Labels: rfd

#16879 Move webauthncli validation to common place
  lib/auth/touchid/api.go
  lib/auth/webauthn/messages.go
  lib/auth/webauthn/messages_test.go
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: tsh, backport/branch/v10, backport/branch/v11

#17129 Added 10/06 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport

#17110 Update RFD number in RFD text body
  rfd/0090-upgrade-system.md
Labels: rfd

#16944 Fix X11 forwarding for non-root users
  lib/srv/reexec.go
  lib/srv/regular/sshserver_test.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10

#17045 [v10] Revert change from PKCS1 to PKCS8
  api/utils/keys/signer.go
  lib/auth/native/native.go
  lib/auth/native/native_test.go
Labels: backport

#16982 [v8] Remove cacert flag from curl output during tsh app login.
  tool/tsh/app.go
  tool/tsh/app_test.go
Labels: backport

#17120 [v11] Correct `tctl proxy ls` command help
  tool/tctl/common/proxy_command.go
Labels: tctl, backport

#16984 [v9] Remove cacert flag from curl output during tsh app login.
  tool/tsh/app.go
  tool/tsh/app_test.go
Labels: tsh, backport

#17047 v11 deprecation
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/oidc.go
  api/types/types.pb.go
  lib/auth/apiserver.go
  lib/auth/grpcserver.go
  lib/srv/app/session.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
Labels: application-access, database-access, desktop-access, backport/branch/v11

#17137 [v11] v11 deprecation
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/oidc.go
  api/types/types.pb.go
  lib/auth/apiserver.go
  lib/auth/grpcserver.go
  lib/srv/app/session.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
Labels: application-access, database-access, backport, desktop-access

#16360 RFD 0088: Passwordless for windows CLI
  rfd/0052-passwordless.md
  rfd/0088-passwordless-windows.md
  rfd/assets/0088-login-choice-multi.png
Labels: rfd, backport/branch/v10, backport/branch/v11

#17057 Remove the SQL backend
  .github/ISSUE_TEMPLATE/testplan.md
  docs/pages/reference/backends.mdx
  lib/backend/backend.go
  lib/backend/backend_test.go
  lib/backend/postgres/azure.go
  lib/backend/postgres/backend.go
  lib/backend/postgres/backend_test.go
  lib/backend/postgres/doc.go
  lib/backend/postgres/driver.go
  lib/backend/postgres/migrate.go
  lib/backend/postgres/schema.go
  lib/backend/postgres/tx.go
  lib/backend/sqlbk/backend.go
  lib/backend/sqlbk/backend_test.go
  lib/backend/sqlbk/background.go
  lib/backend/sqlbk/config.go
  lib/backend/sqlbk/doc.go
  lib/backend/sqlbk/driver.go
  lib/backend/sqlbk/test.go
  lib/config/configuration.go
  lib/service/service.go
Labels: azure, merge-for-v11, backport/branch/v11

#14414 RFD 79: OIDC Joining
  rfd/0079-oidc-joining.md
Labels: rfd

#17055 Remove Azure Blob Storage session backend
  constants.go
  go.mod
  go.sum
  lib/events/azsessions/azsessions.go
  lib/events/azsessions/azsessions_test.go
  lib/events/azsessions/utils.go
  lib/service/service.go
Labels: audit-log, azure, merge-for-v11, backport/branch/v11

#17124 Drain errChan in `api.client/connect`
  api/client/client.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#17121 Fix setting an incorrect port when generating a Teleport config
  assets/aws/files/bin/teleport-generate-config
Labels: backport/branch/v11

#17161 [v11] Fix setting an incorrect port when generating a Teleport config
  assets/aws/files/bin/teleport-generate-config
Labels: backport

#17159 [v10] Drain errChan in `api.client/connect`
  api/client/client.go
Labels: backport

#16932 [v10] Fix background database local proxy termination by SIGINT signal
  tool/tsh/db.go
Labels: tsh, backport

#17063 [v9] Fix background database local proxy termination by SIGINT signal
  tool/tsh/proxy.go
Labels: tsh, backport

#17151 [v11] Bump Cloud Version
  docs/config.json
Labels: documentation, backport

#17150 [v10] Bump Cloud Version
  docs/config.json
Labels: documentation, backport

#17157 [v11] Remove Azure Blob Storage session backend
  constants.go
  go.mod
  go.sum
  lib/events/azsessions/azsessions.go
  lib/events/azsessions/azsessions_test.go
  lib/events/azsessions/utils.go
  lib/service/service.go
Labels: audit-log, backport, merge-for-v11

#17175 desktop clipboard: prevent integer underflow
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
Labels: rdp, desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17178 [v11] desktop clipboard: prevent integer underflow
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
Labels: rdp, backport, desktop-access

#17179 [v10] desktop clipboard: prevent integer underflow
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
Labels: rdp, backport, desktop-access

#17177 [v9] desktop clipboard: prevent integer underflow
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
Labels: rdp, backport, desktop-access

#17088 Improve desktop connection error handling
  lib/web/desktop.go
Labels: desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17032 [v10] Ensure operator tests are run when Go dependencies change
  .cloudbuild/scripts/internal/changes/changes.go
Labels: backport

#17138 Refactor OpenSSH config generation
  integration/helpers/helpers.go
  lib/client/api.go
  lib/client/api_test.go
  lib/client/client.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/session.go
  lib/config/openssh.go
  lib/config/openssh_test.go
  lib/config/testdata/TestSSHConfig_GetSSHConfig/legacy_OpenSSH_-_single_cluster.golden
  lib/config/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_multiple_clusters.golden
  lib/config/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_single_cluster.golden
  lib/sshutils/ctx.go
  lib/tbot/config/config_test.go
  lib/tbot/config/configtemplate_ssh_client.go
  lib/tbot/config/configtemplate_ssh_client_test.go
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/latest_OpenSSH/known_hosts.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/latest_OpenSSH/ssh_config.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/legacy_OpenSSH/known_hosts.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/legacy_OpenSSH/ssh_config.golden
  lib/teleagent/agent.go
  lib/web/sessions.go
  tool/tsh/config.go
  tool/tsh/config_test.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh_test.go
Labels: tsh, machine-id, merge-for-v11

#17158 [v9] Drain errChan in `api.client/connect`
  api/client/client.go
Labels: backport

#17156 [v11] Remove the SQL backend
  .github/ISSUE_TEMPLATE/testplan.md
  docs/pages/reference/backends.mdx
  lib/backend/backend.go
  lib/backend/backend_test.go
  lib/backend/postgres/azure.go
  lib/backend/postgres/backend.go
  lib/backend/postgres/backend_test.go
  lib/backend/postgres/doc.go
  lib/backend/postgres/driver.go
  lib/backend/postgres/migrate.go
  lib/backend/postgres/schema.go
  lib/backend/postgres/tx.go
  lib/backend/sqlbk/backend.go
  lib/backend/sqlbk/backend_test.go
  lib/backend/sqlbk/background.go
  lib/backend/sqlbk/config.go
  lib/backend/sqlbk/doc.go
  lib/backend/sqlbk/driver.go
  lib/backend/sqlbk/test.go
  lib/config/configuration.go
  lib/service/service.go
Labels: documentation, backport, merge-for-v11

#17193 Remove `tsh` dependency on `lib/config` - build fix
  lib/config/openssh/openssh.go
  lib/config/openssh/openssh_test.go
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/legacy_OpenSSH_-_single_cluster.golden
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_multiple_clusters.golden
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_single_cluster.golden
  lib/tbot/config/configtemplate_ssh_client.go
  tool/tsh/config.go
  tool/tsh/config_test.go
Labels: tsh, machine-id

#16958 support proxy db tunnel mfa access
  integration/helpers/instance.go
  integration/proxy/proxy_test.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/local_proxy_middleware.go
  lib/client/mfa.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/local_proxy_test.go
  lib/tlsca/ca.go
  lib/utils/certs.go
  tool/tsh/db.go
  tool/tsh/kube.go
  tool/tsh/proxy.go
Labels: feature-request, tsh, database-access, c-jm, backport/branch/v11

#17182 [v11] Improve desktop connection error handling
  lib/web/desktop.go
Labels: backport, desktop-access

#17160 [v11] Drain errChan in `api.client/connect`
  api/client/client.go
Labels: backport

#17034 [v8] Fetch tags when promoting rpm/deb
  .drone.yml
Labels: backport

#17031 [v10] Fetch tags when promoting rpm/deb
  .drone.yml
  dronegen/common.go
Labels: backport

#17033 [v9] Fetch tags when promoting rpm/deb
  .drone.yml
  dronegen/common.go
Labels: backport

#17194 [v11] Refactor OpenSSH config generation
  integration/helpers/helpers.go
  lib/client/api.go
  lib/client/api_test.go
  lib/client/client.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/session.go
  lib/config/openssh/openssh.go
  lib/config/openssh/openssh_test.go
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/legacy_OpenSSH_-_single_cluster.golden
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_multiple_clusters.golden
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_single_cluster.golden
  lib/sshutils/ctx.go
  lib/tbot/config/config_test.go
  lib/tbot/config/configtemplate_ssh_client.go
  lib/tbot/config/configtemplate_ssh_client_test.go
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/latest_OpenSSH/known_hosts.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/latest_OpenSSH/ssh_config.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/legacy_OpenSSH/known_hosts.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/legacy_OpenSSH/ssh_config.golden
  lib/teleagent/agent.go
  lib/web/sessions.go
  tool/tsh/config.go
  tool/tsh/config_test.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, machine-id

#17145 Tweak wording of joining nodes blurb.
  docs/pages/architecture/nodes.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#15895 Add Cassandra/Scylla database support
  api/proto/teleport/legacy/types/events/events.proto
  api/types/database.go
  api/types/database_test.go
  api/types/events/events.pb.go
  api/types/events/oneof.go
  api/utils/aws/endpoint.go
  api/utils/aws/endpoint_test.go
  go.mod
  go.sum
  integration/db/db_integration_test.go
  integration/db/fixture.go
  lib/client/db/database_certificates.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/client/identityfile/identity.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/service/cfg.go
  lib/service/db.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/access_test.go
  lib/srv/db/ca.go
  lib/srv/db/cassandra/conv.go
  lib/srv/db/cassandra/engine.go
  lib/srv/db/cassandra/handshake.go
  lib/srv/db/cassandra/protocol/conn.go
  lib/srv/db/cassandra/protocol/conn_test.go
  lib/srv/db/cassandra/protocol/fuzz_test.go
  lib/srv/db/cassandra/protocol/packet.go
  lib/srv/db/cassandra/test.go
  lib/srv/db/cassandra_test.go
  lib/srv/db/common/role/role.go
  lib/srv/db/server.go
  tool/tctl/common/auth_command.go
  tool/tsh/db.go
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: database-access, db/cassandra, merge-for-v11

#16880 Add file transfer support to Connect
  lib/client/api.go
  lib/sshutils/sftp/sftp.go
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/apiserver/handler/handler_file_transfer.go
  lib/teleterm/clusters/cluster_file_transfer.go
  lib/teleterm/daemon/daemon.go
Labels: merge-for-v11, backport/branch/v11

#17209 [v11] Add file transfer support to Connect
  lib/client/api.go
  lib/sshutils/sftp/sftp.go
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/apiserver/handler/handler_file_transfer.go
  lib/teleterm/clusters/cluster_file_transfer.go
  lib/teleterm/daemon/daemon.go
Labels: backport

#17210 Fix tsh Cassandra pass condition
  tool/tsh/proxy.go
Labels: tsh

#17207 [v11] Add Cassandra/Scylla database support
  api/proto/teleport/legacy/types/events/events.proto
  api/types/database.go
  api/types/database_test.go
  api/types/events/events.pb.go
  api/types/events/oneof.go
  api/utils/aws/endpoint.go
  api/utils/aws/endpoint_test.go
  go.mod
  go.sum
  integration/db/db_integration_test.go
  integration/db/fixture.go
  lib/client/db/database_certificates.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/client/identityfile/identity.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/defaults/defaults.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/service/cfg.go
  lib/service/db.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/access_test.go
  lib/srv/db/ca.go
  lib/srv/db/cassandra/conv.go
  lib/srv/db/cassandra/engine.go
  lib/srv/db/cassandra/handshake.go
  lib/srv/db/cassandra/protocol/conn.go
  lib/srv/db/cassandra/protocol/conn_test.go
  lib/srv/db/cassandra/protocol/fuzz_test.go
  lib/srv/db/cassandra/protocol/packet.go
  lib/srv/db/cassandra/test.go
  lib/srv/db/cassandra_test.go
  lib/srv/db/common/role/role.go
  lib/srv/db/server.go
  tool/tctl/common/auth_command.go
  tool/tsh/db.go
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: tsh, tctl, audit-log, database-access, backport

#17003 Fix broken links
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport/branch/v9, backport/branch/v8, backport/branch/v10

#17181 [v11] Fix X11 forwarding for non-root users
  lib/srv/reexec.go
  lib/srv/regular/sshserver_test.go
Labels: backport

#17130 [v10] Fix X11 forwarding for non-root users
  lib/srv/reexec.go
  lib/srv/regular/sshserver_test.go
Labels: backport

#17106 [v9] AWS Terraform App Access, DB listeners variables
  docs/pages/setup/deployments/aws-terraform.mdx
Labels: documentation, backport

#16899 Add Kubernetes Cluster Connection Tester
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/client/conntest/connection_tester.go
  lib/client/conntest/kube.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/connection_diagnostic.go
Labels: backport/branch/v11

#17226 [v10] Remove `installer`, `app` and `database` watchers for remote proxies
  lib/cache/cache.go
Labels: backport

#17212 Remove expected `kube_server`, `app`, `database` and `installer` watchers for remote proxies
  lib/cache/cache.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/srv_test.go
Labels: merge-for-v11, backport/branch/v11

#17231 [v11] Remove expected `kube_server`, `app`, `database` and `installer` watchers for remote proxies
  lib/cache/cache.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/srv_test.go
Labels: backport

#17141 Add traits to JWT payload.
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/types/jwt.go
  integration/appaccess/jwt.go
  integration/appaccess/pack.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/auth/tls_test.go
  lib/jwt/jwt.go
  lib/jwt/jwt_test.go
  lib/srv/app/session.go
Labels: application-access, backport/branch/v11

#17225 [v11]Fix flaky TestHostCertVerification
  lib/client/keyagent_test.go
Labels: backport

#17105 [v10] AWS Terraform App Access, DB listeners variables
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
Labels: documentation, backport

#17180 docs: add Kubernetes instructions for Teleport Connect
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11

#17215 [v10] Tweak wording of joining nodes blurb.
  docs/pages/architecture/nodes.mdx
Labels: documentation, backport

#17214 [v11] Tweak wording of joining nodes blurb.
  docs/pages/architecture/nodes.mdx
Labels: documentation, backport

#17131 [v9] Fix X11 forwarding for non-root users
  lib/srv/reexec.go
  lib/srv/regular/sshserver_test.go
Labels: backport

#16976 docs: add CLI section for tctl alert create
  docs/pages/reference/cli.mdx
  tool/tctl/common/alert_command.go
Labels: documentation, tctl, backport/branch/v10, backport/branch/v11

#17237 [v11] Refactor Drone Pipelines to use AWS role assumption
  .drone.yml
  build.assets/windows/build.ps1
  dronegen/apt.go
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/mac.go
  dronegen/mac_pkg.go
  dronegen/os_repos.go
  dronegen/promote.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/windows.go
  dronegen/yum.go
Labels: backport

#17236 Update test plan for desktop access
  .github/ISSUE_TEMPLATE/testplan.md
Labels: documentation

#17244 [v10] Refactor Drone Pipelines to use AWS role assumption
  .drone.yml
  build.assets/windows/build.ps1
  dronegen/apt.go
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/mac.go
  dronegen/mac_pkg.go
  dronegen/os_repos.go
  dronegen/promote.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/windows.go
  dronegen/yum.go
Labels: backport

#17238 Update JWT docs to reflect new traits in payload.
  docs/pages/application-access/jwt/introduction.mdx
  examples/jwt/verify-jwt.go
Labels: documentation, backport/branch/v11

#17122 Use Teleport's standard buildbox
  build.assets/Makefile
  build.assets/images.mk
  docker/Dockerfile
  docker/Makefile
  operator/Dockerfile
  operator/Makefile
Labels: backport/branch/v10, backport/branch/v11

#17239 [v11] Add traits to JWT payload.
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/types/jwt.go
  docs/pages/application-access/jwt/introduction.mdx
  examples/jwt/verify-jwt.go
  integration/appaccess/jwt.go
  integration/appaccess/pack.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/auth/tls_test.go
  lib/jwt/jwt.go
  lib/jwt/jwt_test.go
  lib/srv/app/session.go
Labels: application-access, backport

#17222 Include Rust/Cargo in Dependabot updates
  .github/dependabot.yml
Labels: backport/branch/v11

#16182 docs: add self signed certs guide
  docs/config.json
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/deploy-a-cluster/open-source.mdx
  docs/pages/deploy-a-cluster/teleport-enterprise/getting-started.mdx
  docs/pages/includes/tls-certificate-setup.mdx
  docs/pages/management/admin.mdx
  docs/pages/management/admin/self-signed-certs.mdx
Labels: documentation, backport/branch/v11

#17200 [v11] support proxy db tunnel mfa access
  integration/helpers/instance.go
  integration/proxy/proxy_test.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/local_proxy_middleware.go
  lib/client/mfa.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/local_proxy_test.go
  lib/tlsca/ca.go
  lib/utils/certs.go
  tool/tsh/db.go
  tool/tsh/kube.go
  tool/tsh/proxy.go
Labels: tsh, backport

#17296 [v10] Add AWS Roles to the buildbox pipeline
  .drone.yml
  dronegen/buildbox.go
  dronegen/tag.go
Labels: backport

#17299 [v11] Add self signed certs guide
  docs/config.json
  docs/pages/application-access/guides/connecting-apps.mdx
  docs/pages/deploy-a-cluster/open-source.mdx
  docs/pages/deploy-a-cluster/teleport-enterprise/getting-started.mdx
  docs/pages/includes/acme.mdx
  docs/pages/includes/tls-certificate-setup.mdx
  docs/pages/management/admin.mdx
  docs/pages/management/admin/self-signed-certs.mdx
Labels: documentation, backport

#17304 [v10] Fix FIPS docker publishing AWS credentials
  .drone.yml
Labels: backport

#17298 [v11] Add AWS Roles to the buildbox pipeline
  .drone.yml
  dronegen/buildbox.go
  dronegen/tag.go
Labels: backport

#17308 [v11] revert compare-and-swap node hbs
  lib/services/local/presence.go
Labels: backport

#17303 Release 10.3.2
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport

#16694 [connect] access requests for Teleport Connect
  api/types/sortby.go
  api/types/sortby_test.go
  lib/teleterm/api/proto/v1/access_request.proto
  lib/teleterm/api/proto/v1/cluster.proto
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/access_request.pb.go
  lib/teleterm/api/protogen/golang/v1/cluster.pb.go
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/access_request_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/access_request_pb.d.ts
  lib/teleterm/api/protogen/js/v1/access_request_pb.js
  lib/teleterm/api/protogen/js/v1/cluster_pb.d.ts
  lib/teleterm/api/protogen/js/v1/cluster_pb.js
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/api/uri/uri.go
  lib/teleterm/apiserver/handler/handler_access_requests.go
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/apiserver/handler/handler_databases.go
  lib/teleterm/apiserver/handler/handler_kubes.go
  lib/teleterm/apiserver/handler/handler_servers.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/teleterm/clusters/cluster_servers.go
  lib/teleterm/daemon/daemon.go
  lib/web/resources.go
Labels: merge-for-v11

#17232 User proper leaf address in docs
  docs/pages/management/admin/trustedclusters.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17229 [v11] Add Kubernetes Cluster Connection Tester (#16899)
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/client/conntest/connection_tester.go
  lib/client/conntest/kube.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/connection_diagnostic.go
Labels: backport

#17155 [v11] Move webauthncli validation to common place
  lib/auth/touchid/api.go
  lib/auth/webauthn/messages.go
  lib/auth/webauthn/messages_test.go
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_common.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport

#17263 Fix tctl auth sign call for Snowflake in trusted clusters env
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
Labels: tctl, backport/branch/v10, backport/branch/v11

#17270 Set `AuthServer` instead of `AuthServers` during `teleport configure`
  lib/config/fileconf.go
  lib/config/fileconf_test.go
Labels: backport/branch/v11

#16665 Fix FuzzMongoRead
  lib/srv/db/mongodb/protocol/fuzz_test.go
  lib/srv/db/mongodb/protocol/opmsg.go
  lib/srv/db/mongodb/protocol/util.go
Labels: database-access, db/mongo

#17328 [v11] Set `AuthServer` instead of `AuthServers` during `teleport configure`
  lib/config/fileconf.go
  lib/config/fileconf_test.go
Labels: backport

#17322 [v9] User proper leaf address in docs
  docs/pages/setup/admin/trustedclusters.mdx
Labels: documentation, backport

#17320 [v10] User proper leaf address in docs
  docs/pages/management/admin/trustedclusters.mdx
Labels: documentation, backport

#17128 Neaten up the config comments for config v2 and above, remove config changelog
  docs/pages/reference/config.mdx
Labels: documentation, backport/branch/v11

#17321 [v11] User proper leaf address in docs
  docs/pages/management/admin/trustedclusters.mdx
Labels: documentation, backport

#16965 Add X-Forwarded-SSL and X-Forwarded-Port to appaccess.
  go.mod
  go.sum
  integration/appaccess/fixtures.go
  integration/appaccess/pack.go
  lib/srv/app/common/header.go
  lib/srv/app/common/header_rewriter.go
  lib/srv/app/common/header_rewriter_test.go
  lib/srv/app/server_test.go
  lib/srv/app/session.go
  lib/web/app/session.go
  lib/web/app/transport.go
Labels: application-access, backport/branch/v11

#17218 Set the default proxy listen addrs even if a file config isn't present
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: backport/branch/v9, backport/branch/v8, backport/branch/v10, backport/branch/v11

#17343 [v10] Set the default proxy listen addrs even if a file config isn't present
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: backport

#17269 Fix BPF
  lib/bpf/bpf.go
  lib/bpf/bpf_test.go
  lib/bpf/common.go
  lib/bpf/helper.go
  lib/restrictedsession/audit.go
  lib/restrictedsession/manager.go
  lib/restrictedsession/restricted.go
  lib/restrictedsession/restricted_test.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/exec_linux_test.go
  lib/srv/exec_test.go
  lib/srv/forward/sshserver.go
  lib/srv/mock.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
  lib/srv/sess_test.go
Labels: testplan, bpf, server-access, backport/branch/v11

#17335 [v10] Fix yum repo cleanup
  .drone.yml
  dronegen/os_repos.go
Labels: backport

#17346 [v9] Set the default proxy listen addrs even if a file config isn't present
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: backport

#17333 [v11] Fix the version yaml in `configure-ad.ps1`
  lib/web/scripts/desktop/configure-ad.ps1
Labels: backport

#17342 [v11] Add X-Forwarded-SSL and X-Forwarded-Port to appaccess.
  go.mod
  go.sum
  integration/appaccess/fixtures.go
  integration/appaccess/pack.go
  lib/srv/app/common/header.go
  lib/srv/app/common/header_rewriter.go
  lib/srv/app/common/header_rewriter_test.go
  lib/srv/app/server_test.go
  lib/srv/app/session.go
  lib/web/app/session.go
  lib/web/app/transport.go
Labels: application-access, backport

#17354 [v11] Move enterprise key before Connect binary conditional in mac drone pipe
  .drone.yml
  dronegen/mac.go
Labels: backport

#17351 Updates the clipboard UX documentation for the new system
  docs/pages/desktop-access/reference/clipboard.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11

#17313 [v11] [connect] access requests for Teleport Connect (#16694)
  api/types/sortby.go
  api/types/sortby_test.go
  lib/teleterm/api/proto/v1/access_request.proto
  lib/teleterm/api/proto/v1/cluster.proto
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/protogen/golang/v1/access_request.pb.go
  lib/teleterm/api/protogen/golang/v1/cluster.pb.go
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/js/v1/access_request_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/access_request_pb.d.ts
  lib/teleterm/api/protogen/js/v1/access_request_pb.js
  lib/teleterm/api/protogen/js/v1/cluster_pb.d.ts
  lib/teleterm/api/protogen/js/v1/cluster_pb.js
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/api/uri/uri.go
  lib/teleterm/apiserver/handler/handler_access_requests.go
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/apiserver/handler/handler_databases.go
  lib/teleterm/apiserver/handler/handler_kubes.go
  lib/teleterm/apiserver/handler/handler_servers.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/teleterm/clusters/cluster_servers.go
  lib/teleterm/daemon/daemon.go
  lib/web/resources.go
Labels: backport

#17356 Instructions updates for EC2 Auto Discovery
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11
