Repository gravitational/teleport, pull requests merged in 2023-11, with the labels that each got.

#34102 fix: Use octal mode for Windows TPM files
  lib/devicetrust/native/device_windows.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#33969 Fix an issue auto-provisioned PostgreSQL user may keep old roles indefinitely
  lib/srv/db/postgres/sql/activate-user.sql
  lib/srv/db/postgres/sql/deactivate-user.sql
  lib/srv/db/postgres/sql/delete-user.sql
Labels: security, database-access, size/sm, backport/branch/v13, changelog, backport/branch/v14

#33750 RFD 0152: Database Automatic User Provisioning for MongoDB
  rfd/0152-automatic-database-users-mongodb.md
Labels: rfd, database-access, db/mongo, size/md, no-changelog

#32974 Access Plugins: Support dynamic credential reloading
  api/client/credentials.go
  integrations/access/common/app.go
  integrations/access/common/config.go
  integrations/access/discord/config.go
  integrations/access/jira/app.go
  integrations/access/opsgenie/app.go
  integrations/access/pagerduty/app.go
  integrations/access/servicenow/app.go
  integrations/lib/config.go
Labels: size/sm, backport/branch/v14

#34079 [v14] Access Plugins: Support dynamic credential reloading
  api/client/credentials.go
  integrations/access/common/app.go
  integrations/access/common/config.go
  integrations/access/discord/config.go
  integrations/access/jira/app.go
  integrations/access/opsgenie/app.go
  integrations/access/pagerduty/app.go
  integrations/access/servicenow/app.go
  integrations/lib/config.go
Labels: backport, size/sm

#34006 Support Redshift auto provisioned user deletion
  lib/srv/db/postgres/sql/redshift-delete-user.sql
  lib/srv/db/postgres/users.go
Labels: database-access, size/sm, changelog

#34048 chore: Bump golangci-lint to v1.55.1
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34074 [docs] troubleshooting for AWS Access SSM sessions
  docs/pages/application-access/cloud-apis/aws-console.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34064 [v14] Show alert about insufficient permissions in Connect My Computer setup tab
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/DocumentConnectMyComputer.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/ProgressBar.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.test.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Status.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Status.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/index.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/access.test.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/access.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/permissions.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
Labels: ui, backport, size/md

#22530 Consolidate context usage for client src/dst addresses into authz package
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/join_azure.go
  lib/auth/join_azure_test.go
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/middleware.go
  lib/auth/middleware_test.go
  lib/auth/transport_credentials.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/client/api.go
  lib/kube/proxy/server.go
  lib/service/service.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/app/server.go
  lib/utils/net.go
  lib/web/addr.go
  lib/web/addr_test.go
  lib/web/app/transport.go
  lib/web/desktop.go
  lib/web/sessions.go
Labels: kubernetes-access, application-access, desktop-access, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#32919 terraform: Add/restore support for TELEPORT_AUTH_TYPE
  docs/pages/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx
  docs/pages/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx
  examples/aws/terraform/ha-autoscale-cluster/Makefile
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/ha-autoscale-cluster/auth-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/auth_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/vars.tf
  examples/aws/terraform/starter-cluster/Makefile
  examples/aws/terraform/starter-cluster/README.md
  examples/aws/terraform/starter-cluster/cluster.tf
  examples/aws/terraform/starter-cluster/data.tpl
  examples/aws/terraform/starter-cluster/vars.tf
Labels: documentation, terraform-deployment-examples, size/sm, terraform, backport/branch/v14

#34091 Add Access List owners to suggested reviewers.
  lib/auth/access_request_test.go
  lib/auth/auth.go
Labels: size/md, backport/branch/v13, backport/branch/v14

#34124 [v14] terraform: Add/restore support for TELEPORT_AUTH_TYPE
  docs/pages/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx
  docs/pages/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx
  examples/aws/terraform/ha-autoscale-cluster/Makefile
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/ha-autoscale-cluster/auth-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/auth_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/vars.tf
  examples/aws/terraform/starter-cluster/Makefile
  examples/aws/terraform/starter-cluster/README.md
  examples/aws/terraform/starter-cluster/cluster.tf
  examples/aws/terraform/starter-cluster/data.tpl
  examples/aws/terraform/starter-cluster/vars.tf
Labels: documentation, backport, size/sm

#34008 Expose ServerInfo resource in `tctl`
  api/types/server_info.go
  lib/auth/server_info.go
  lib/auth/server_info_test.go
  lib/services/resource.go
  lib/srv/server/ec2_watcher.go
  lib/srv/server/ec2_watcher_test.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, size/md, changelog, backport/branch/v14

#34114 [v13] fix: Use octal mode for Windows TPM files
  lib/devicetrust/native/device_windows.go
Labels: backport, size/sm

#34113 [v14] fix: Use octal mode for Windows TPM files
  lib/devicetrust/native/device_windows.go
Labels: backport, size/sm

#33272 BYOB: Bootstrap Athena Infrastructure
  api/types/externalcloudaudit/externalcloudaudit.go
  lib/integrations/externalcloudaudit/bootstrap.go
  lib/integrations/externalcloudaudit/bootstrap_test.go
  lib/services/local/externalcloudaudit_test.go
  tool/teleport/common/teleport.go
Labels: size/lg, backport/branch/v13, backport/branch/v14, no-changelog

#34129 [v12] chore: Bump golangci-lint to v1.55.1
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm

#34128 [v13] chore: Bump golangci-lint to v1.55.1
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm

#34127 [v14] chore: Bump golangci-lint to v1.55.1
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm

#34089 Special case the subsystems handled by `teleport exec`
  lib/srv/reexec.go
  lib/srv/regular/sftp.go
  lib/sshutils/sftp/sftp.go
  tool/teleport/common/teleport.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34039 Installer Scripts: use bash instead of sh
  api/types/installers/installer.sh.tmpl
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#34112 [TAG] Add access graph to the user ACL & feature flags
  web/packages/teleport/src/mocks/contexts.ts
  web/packages/teleport/src/services/user/makeAcl.ts
  web/packages/teleport/src/services/user/types.ts
  web/packages/teleport/src/services/user/user.test.ts
  web/packages/teleport/src/stores/storeUserContext.ts
  web/packages/teleport/src/teleportContext.tsx
  web/packages/teleport/src/types.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog

#34117 [v13] [docs] troubleshooting for AWS Access SSM sessions
  docs/pages/application-access/cloud-apis/aws-console.mdx
Labels: documentation, backport, size/sm, no-changelog

#34116 [v12] [docs] troubleshooting for AWS Access SSM sessions
  docs/pages/application-access/cloud-apis/aws-console.mdx
Labels: documentation, backport, size/sm, no-changelog

#34118 [v14] [docs] troubleshooting for AWS Access SSM sessions
  docs/pages/application-access/cloud-apis/aws-console.mdx
Labels: documentation, backport, size/sm, no-changelog

#34143 [v13] Installer Scripts: use bash instead of sh
  api/types/installers/installer.sh.tmpl
Labels: backport, size/sm

#34136 docs: add join token in MySQL CloudSQL config
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34145 Discover Kube Agent: use automatic upgrades version
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14

#34144 [v14] Installer Scripts: use bash instead of sh
  api/types/installers/installer.sh.tmpl
Labels: backport, size/sm

#28690 Create a guide to using Teleport with Spacelift
  docs/config.json
  docs/cspell.json
  docs/img/management/spacelift/apply-success.png
  docs/img/management/spacelift/id-file.png
  docs/img/management/spacelift/newstack.png
  docs/img/management/spacelift/pr-run.png
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/dynamic-resources/spacelift.mdx
Labels: documentation, size/md, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34106 Fix links in the Predicate Language guide
  docs/pages/reference/predicate-language.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34133 Refactor device TPM logic to better support Linux
  lib/devicetrust/native/device_windows.go
  lib/devicetrust/native/tpm_device.go
Labels: size/sm, no-changelog

#34105 Bump `rdp-rs` for `boring` upgrade
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, desktop-access, size/sm, no-changelog

#34151 Set Connect My Computer RFD status to implemented
  rfd/0133-connect-my-computer.md
Labels: rfd, size/sm, no-changelog

#34158 [v13] Discover Kube Agent: use automatic upgrades version (#34145)
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, size/sm

#34157 [v14] Discover Kube Agent: use automatic upgrades version (#34145)
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, size/sm

#34159 [v12] docs: add join token in MySQL CloudSQL config
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, backport, size/sm

#34156 [v13] docs: add join token in MySQL CloudSQL config
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, backport, size/sm

#34155 [v14] docs: add join token in MySQL CloudSQL config
  docs/pages/database-access/guides/mysql-cloudsql.mdx
Labels: documentation, backport, size/sm

#34131 [v14] Add Access List owners to suggested reviewers.
  lib/auth/access_request_test.go
  lib/auth/auth.go
Labels: backport, size/md

#34130 [v13] Add Access List owners to suggested reviewers.
  lib/auth/access_request_test.go
  lib/auth/auth.go
Labels: backport, size/md

#34169 [13] Consolidate context usage for client src/dst addresses into authz package
  lib/auth/grpcserver.go
  lib/auth/join_azure.go
  lib/auth/join_azure_test.go
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/middleware.go
  lib/auth/middleware_test.go
  lib/auth/transport_credentials.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/client/api.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/server.go
  lib/service/service.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/app/server.go
  lib/utils/net.go
  lib/web/addr.go
  lib/web/addr_test.go
  lib/web/app/transport.go
  lib/web/desktop.go
  lib/web/sessions.go
Labels: kubernetes-access, application-access, backport, desktop-access, size/sm

#34063 Fix Teleport update reconciliation on `status` updates
  integrations/operator/controllers/resources/role_controller.go
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/utils.go
  integrations/operator/crdgen/ignored.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#33949 oci: Parameterize Debian OCI Dockerfile for multiarch
  build.assets/charts/Dockerfile
Labels: backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34146 Return enum value from getPlatform
  web/packages/design/src/platform.ts
  web/packages/design/src/theme/fonts.js
  web/packages/design/src/theme/utils/getPlatform.tsx
  web/packages/design/src/theme/utils/index.js
  web/packages/teleport/src/Console/DocumentSsh/Terminal/Terminal.tsx
  web/packages/teleport/src/Console/DocumentSsh/TerminalAssist/utils.ts
  web/packages/teleport/src/Console/useKeyboardNav.ts
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.story.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Player/Xterm/Xterm.tsx
  web/packages/teleterm/src/ui/ThemeProvider/globals.ts
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#34065 Remove old resource tables from Connect
  web/packages/teleterm/src/ui/DocumentCluster/ClusterNavButton/ClusterNavButton.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterNavButton/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/ClusterResources.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/DarkenWhileDisabled.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/Kubes.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/useKubes.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/Servers.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/useServers.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/SideNav/SideNav.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/SideNav/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/getEmptyTableText.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/index.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/renderLabelCell.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/useServerSideResources.test.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/useServerSideResources.ts
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
  web/packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
Labels: ui, size/sm, no-changelog

#34168 [14] Consolidate context usage for client src/dst addresses into authz package
  lib/auth/grpcserver.go
  lib/auth/join_azure.go
  lib/auth/join_azure_test.go
  lib/auth/join_iam.go
  lib/auth/join_iam_test.go
  lib/auth/middleware.go
  lib/auth/middleware_test.go
  lib/auth/transport_credentials.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/client/api.go
  lib/kube/proxy/server.go
  lib/service/service.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/app/server.go
  lib/utils/net.go
  lib/web/addr.go
  lib/web/addr_test.go
  lib/web/app/transport.go
  lib/web/desktop.go
  lib/web/sessions.go
Labels: kubernetes-access, application-access, backport, desktop-access, size/sm

#34049 Move bulk actions to Filter Panel
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.story.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/services/agents/types.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, backport-required, size/sm, backport/branch/v14, no-changelog

#34195 [v13] Return enum value from getPlatform
  web/packages/design/src/platform.ts
  web/packages/design/src/theme/fonts.js
  web/packages/design/src/theme/utils/getPlatform.tsx
  web/packages/design/src/theme/utils/index.js
  web/packages/teleport/src/Console/DocumentSsh/Terminal/Terminal.tsx
  web/packages/teleport/src/Console/DocumentSsh/TerminalAssist/utils.ts
  web/packages/teleport/src/Console/useKeyboardNav.ts
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.story.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Player/Xterm/Xterm.tsx
  web/packages/teleterm/src/ui/ThemeProvider/globals.ts
Labels: ui, backport, size/sm

#34197 [v12] Fix Teleport update reconciliation on `status` updates
  operator/apis/resources/v2/user_types.go
  operator/controllers/resources/role_controller.go
  operator/controllers/resources/teleport_reconciler.go
  operator/controllers/resources/user_controller.go
  operator/controllers/resources/utils.go
  operator/crdgen/ignored.go
Labels: backport, size/md

#34196 [v13] Fix Teleport update reconciliation on `status` updates
  integrations/operator/controllers/resources/role_controller.go
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/utils.go
  integrations/operator/crdgen/ignored.go
Labels: backport, size/md

#34160 [v14] Fix links in the Predicate Language guide
  docs/pages/reference/predicate-language.mdx
Labels: documentation, backport, size/sm

#34194 [v14] Fix Teleport update reconciliation on `status` updates
  integrations/operator/controllers/resources/role_controller.go
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/utils.go
  integrations/operator/crdgen/ignored.go
Labels: backport, size/md

#33846 docs: Update the CMVP certificate used for BoringCrypto's FIPS 140-2 compliance
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34138 include state of access request after review in audit log description
  web/packages/teleport/src/services/audit/makeEvent.ts
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#34163 Fix headless login timing out prematurely
  lib/auth/auth.go
  lib/auth/auth_login_test.go
  lib/auth/auth_with_roles.go
  lib/auth/methods.go
  lib/auth/middleware.go
  lib/authz/permissions.go
  lib/client/weblogin.go
  lib/defaults/defaults.go
  lib/service/service.go
  lib/srv/alpnproxy/kube.go
  lib/teleterm/daemon/daemon_headless.go
  lib/web/apiserver.go
Labels: size/sm, headless-sso, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#34206 [v14] Move bulk actions to Filter Panel
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.story.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/services/agents/types.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, backport, size/sm

#34140 [v12] Special case the subsystems handled by `teleport exec`
  constants.go
  lib/srv/reexec.go
  lib/srv/regular/sftp.go
  lib/srv/regular/sshserver.go
  lib/sshutils/sftp/sftp.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#34141 [v13] Special case the subsystems handled by `teleport exec`
  lib/srv/reexec.go
  lib/srv/regular/sftp.go
  lib/sshutils/sftp/sftp.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#34162 [v12] Fix links in the Predicate Language guide
  docs/pages/reference/predicate-language.mdx
Labels: documentation, backport, size/sm

#34161 [v13] Fix links in the Predicate Language guide
  docs/pages/reference/predicate-language.mdx
Labels: documentation, backport, size/sm

#34198 Remove nodeCount from Web server and UI
  lib/web/apiserver_test.go
  lib/web/ui/cluster.go
  lib/web/ui/perf_test.go
  web/packages/teleport/src/Clusters/fixtures/index.ts
  web/packages/teleport/src/Main/fixtures/index.ts
  web/packages/teleport/src/mocks/contexts.ts
  web/packages/teleport/src/services/clusters/clusters.test.ts
  web/packages/teleport/src/services/clusters/makeCluster.ts
  web/packages/teleport/src/services/clusters/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34172 use upgradeEnrollAlertID in error logs
  lib/auth/auth.go
Labels: size/sm, backport/branch/v14, no-changelog

#34174 fix step number in aws-discovery docs guide
  docs/pages/database-access/guides/aws-discovery.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#34215 [v12] include state of access request after review in audit log description
  web/packages/teleport/src/services/audit/makeEvent.ts
Labels: ui, backport, size/sm

#34213 [v14] include state of access request after review in audit log description
  web/packages/teleport/src/services/audit/makeEvent.ts
Labels: ui, backport, size/sm

#34214 [v13] include state of access request after review in audit log description
  web/packages/teleport/src/services/audit/makeEvent.ts
Labels: ui, backport, size/sm

#34142 [v14] Special case the subsystems handled by `teleport exec`
  lib/srv/reexec.go
  lib/srv/regular/sftp.go
  lib/sshutils/sftp/sftp.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#34225 [v14] fix step number in aws-discovery docs guide
  docs/pages/database-access/guides/aws-discovery.mdx
Labels: documentation, backport, size/sm

#34218 [v12] Remove nodeCount from Web server and UI
  lib/web/apiserver_test.go
  lib/web/ui/cluster.go
  lib/web/ui/perf_test.go
  web/packages/teleport/src/Clusters/fixtures/index.ts
  web/packages/teleport/src/Main/fixtures/index.ts
  web/packages/teleport/src/mocks/contexts.ts
  web/packages/teleport/src/services/clusters/clusters.test.ts
  web/packages/teleport/src/services/clusters/makeCluster.ts
  web/packages/teleport/src/services/clusters/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, backport, size/sm, no-changelog

#34217 [v13] Remove nodeCount from Web server and UI
  lib/web/apiserver_test.go
  lib/web/ui/cluster.go
  lib/web/ui/perf_test.go
  web/packages/teleport/src/Clusters/fixtures/index.ts
  web/packages/teleport/src/Main/fixtures/index.ts
  web/packages/teleport/src/mocks/contexts.ts
  web/packages/teleport/src/services/clusters/clusters.test.ts
  web/packages/teleport/src/services/clusters/makeCluster.ts
  web/packages/teleport/src/services/clusters/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, backport, size/sm, no-changelog

#34216 [v14] Remove nodeCount from Web server and UI
  lib/web/apiserver_test.go
  lib/web/ui/cluster.go
  lib/web/ui/perf_test.go
  web/packages/teleport/src/Clusters/fixtures/index.ts
  web/packages/teleport/src/Main/fixtures/index.ts
  web/packages/teleport/src/mocks/contexts.ts
  web/packages/teleport/src/services/clusters/clusters.test.ts
  web/packages/teleport/src/services/clusters/makeCluster.ts
  web/packages/teleport/src/services/clusters/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, backport, size/sm, no-changelog

#34245 docs: update Server SSH getting started to SSH video
  docs/cspell.json
  docs/pages/server-access/getting-started.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#33938 Support MariaDB auto provisioned user deletion
  lib/srv/db/autousers_test.go
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/sql/mariadb_delete_user.sql
Labels: database-access, size/sm, changelog

#34250 [v12] docs: update Server SSH getting started to SSH video
  docs/cspell.json
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#34249 [v13] docs: update Server SSH getting started to SSH video
  docs/cspell.json
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#34251 Link to version-specific docs pages from the support page
  web/packages/teleport/src/Support/Support.story.tsx
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#34219 [v14] use upgradeEnrollAlertID in error logs
  lib/auth/auth.go
Labels: backport, size/sm, no-changelog

#34090 [v12] Fix authorization rules to the Assistant and UserPreferences service
  lib/ai/testutils/http.go
  lib/auth/assist/assistv1/service.go
  lib/auth/assist/assistv1/service_test.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/authz/permissions.go
  lib/web/apiserver_test.go
  lib/web/assistant_test.go
  lib/web/command.go
  lib/web/command_test.go
Labels: backport, size/md, no-changelog

#34164 Fix `UserCertificateIssuedEvent.private_key_policy` field in PreHog
  lib/usagereporter/teleport/types.go
Labels: size/sm, backport/branch/v14, no-changelog

#34248 [v14] docs: update Server SSH getting started to SSH video
  docs/cspell.json
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#34165 Tidy up pointer/value receivers in tbot
  lib/tbot/config/config_test.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_memory.go
  lib/tbot/config/output_application.go
  lib/tbot/config/output_database.go
  lib/tbot/config/output_identity.go
  lib/tbot/config/output_kubernetes.go
  lib/tbot/config/output_ssh_host.go
Labels: machine-id, size/sm, backport/branch/v14, no-changelog

#34202 Fix Machine ID selection of Kubernetes Access address/port
  docs/pages/includes/machine-id/kubernetes-machineidnote.mdx
  docs/pages/machine-id/access-guides/kubernetes.mdx
  docs/pages/machine-id/troubleshooting.mdx
  lib/tbot/config/bot_test.go
  lib/tbot/config/template_kubernetes.go
  lib/tbot/config/template_kubernetes_test.go
  lib/tbot/config/testdata/TestTemplateKubernetesRender/absolute_path/kubeconfig.yaml.golden
  lib/tbot/config/testdata/TestTemplateKubernetesRender/relative_path/kubeconfig.yaml.golden
  lib/tbot/testhelpers/srv.go
Labels: documentation, machine-id, size/sm, backport/branch/v14

#34177 Filter dangerous environment variables before reexec
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/utils/environment_test.go
  lib/utils/envutils/environment.go
  lib/utils/envutils/environment_test.go
Labels: size/md, backport/branch/v12, backport/branch/v13, backport/branch/v14

#34264 [v14] Fix `UserCertificateIssuedEvent.private_key_policy` field in PreHog
  lib/usagereporter/teleport/types.go
Labels: backport, size/sm

#34078 Add Connect My Computer tile to Discover
  web/packages/design/src/ResourceIcon/assets/laptop.svg
  web/packages/design/src/ResourceIcon/index.tsx
  web/packages/teleport/src/Discover/Discover.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Discover/Shared/ResourceKind.ts
Labels: ui, size/lg, backport/branch/v14, no-changelog

#34193 [v14] Return enum value from getPlatform
  web/packages/design/src/platform.ts
  web/packages/design/src/theme/fonts.js
  web/packages/design/src/theme/utils/getPlatform.tsx
  web/packages/design/src/theme/utils/index.js
  web/packages/teleport/src/Console/DocumentSsh/Terminal/Terminal.tsx
  web/packages/teleport/src/Console/DocumentSsh/TerminalAssist/utils.ts
  web/packages/teleport/src/Console/useKeyboardNav.ts
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.story.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Player/Xterm/Xterm.tsx
  web/packages/teleterm/src/ui/ThemeProvider/globals.ts
Labels: ui, backport, size/sm, no-changelog

#34269 [v14] Tidy up pointer/value receivers in tbot
  lib/tbot/config/config_test.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_memory.go
  lib/tbot/config/output_application.go
  lib/tbot/config/output_database.go
  lib/tbot/config/output_identity.go
  lib/tbot/config/output_kubernetes.go
  lib/tbot/config/output_ssh_host.go
Labels: backport, machine-id, size/sm

#34267 [v13] Link to version-specific docs pages from the support page
  web/packages/teleport/src/Support/Support.story.tsx
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm, backport/branch/v12

#34261 [v14] Link to version-specific docs pages from the support page
  web/packages/teleport/src/Support/Support.story.tsx
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#34258 Fix MySQL/MariaDB delete user when quotes are required and make sure all-in-one role is removed
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/sql/mariadb_delete_user.sql
  lib/srv/db/mysql/sql/mysql_delete_user.sql
Labels: database-access, backport, size/sm, changelog, backport/branch/v14

#34153 Remove cloud only warning for jira plugin
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#34081 Make cluster error states more pretty, add a reconnect button for leaf clusters
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#34265 integrations/operator: propagate revision + fix tests
  integrations/operator/apis/resources/v1/loginrule_types.go
  integrations/operator/controllers/resources/role_controller.go
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/user_controller_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34120 [v13] Fix an issue auto-provisioned PostgreSQL user may keep old roles indefinitely
  lib/srv/db/postgres/activate-user.sql
  lib/srv/db/postgres/deactivate-user.sql
  lib/srv/db/postgres/users.go
Labels: security, database-access, backport, size/sm, changelog

#34121 [v14] Fix an issue auto-provisioned PostgreSQL user may keep old roles indefinitely
  lib/srv/db/postgres/sql/activate-user.sql
  lib/srv/db/postgres/sql/deactivate-user.sql
  lib/srv/db/postgres/sql/delete-user.sql
Labels: security, database-access, backport, size/sm, changelog

#34309 [v13] chore: Bump Go to v1.20.11
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#34308 [v14] chore: Bump Go to v1.21.4
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#34307 chore: Bump Go to v1.21.4
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: size/sm

#33784 tsh: split large desktop recordings into multiple files
  tool/tsh/common/recording_export.go
  tool/tsh/common/recording_export_test.go
Labels: tsh, size/sm, backport/branch/v13, backport/branch/v14

#34276 [v12] Filter dangerous environment variables before reexec
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/utils/environment_test.go
  lib/utils/envutils/environment.go
  lib/utils/envutils/environment_test.go
Labels: backport, size/md

#34275 [v13] Filter dangerous environment variables before reexec
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/utils/environment_test.go
  lib/utils/envutils/environment.go
  lib/utils/envutils/environment_test.go
Labels: backport, size/md

#34274 [v14] Filter dangerous environment variables before reexec
  lib/srv/ctx.go
  lib/srv/reexec.go
  lib/utils/environment_test.go
  lib/utils/envutils/environment.go
  lib/utils/envutils/environment_test.go
Labels: backport, size/md

#34270 integrations/operator: remove require checks from Eventually funcs
  integrations/operator/controllers/resources/role_controller_test.go
  integrations/operator/controllers/resources/suite_test.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go
  integrations/operator/controllers/resources/user_controller_test.go
Labels: bug, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34312 Document workload ID for AKS for the helm guide
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
Labels: documentation, support-load, size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#34050 integrations/operator: re-use the teleport client instead of creating a new one
  integrations/operator/controllers/resources/github_connector_controller.go
  integrations/operator/controllers/resources/login_rule_controller.go
  integrations/operator/controllers/resources/oidc_connector_controller.go
  integrations/operator/controllers/resources/okta_import_rule_controller.go
  integrations/operator/controllers/resources/provision_token_controller.go
  integrations/operator/controllers/resources/role_controller.go
  integrations/operator/controllers/resources/saml_connector_controller.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/user_controller.go
  integrations/operator/main.go
  integrations/operator/sidecar/syncclient.go
  integrations/operator/sidecar/tbot.go
  integrations/operator/sidecar/tbot_test.go
  lib/tbot/config/destination_memory.go
Labels: bug, size/md, backport/branch/v12, kube-operator, backport/branch/v13, changelog, backport/branch/v14

#34287 [v14] Add Connect My Computer tile to Discover
  web/packages/design/src/ResourceIcon/assets/laptop.svg
  web/packages/design/src/ResourceIcon/index.tsx
  web/packages/teleport/src/Discover/Discover.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Discover/Shared/ResourceKind.ts
Labels: ui, backport, size/lg

#34150 [v12] Installer Scripts: use bash instead of sh (#34039)
  api/types/installers/installer.sh.tmpl
Labels: backport, size/sm

#34288 Add first step of guided flow for Connect My Computer in Discover
  web/packages/design/src/Card/Card.jsx
  web/packages/design/src/Card/Card.story.tsx
  web/packages/design/src/CardError/CardError.story.jsx
  web/packages/design/src/CardSuccess/CardSuccess.story.jsx
  web/packages/design/src/buttons.story.jsx
  web/packages/shared/components/MenuAction/MenuActionButton.tsx
  web/packages/shared/components/OverrideUserAgent/index.tsx
  web/packages/shared/deepLinks.ts
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.story.tsx
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.tsx
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/index.ts
  web/packages/teleport/src/Discover/ConnectMyComputer/index.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.tsx
  web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/ConnectionDiagnosticResult.tsx
  web/packages/teleport/src/Discover/Shared/StyledBox.ts
  web/packages/teleport/src/Discover/Shared/index.ts
  web/packages/teleport/src/Discover/flow.tsx
  web/packages/teleport/src/Discover/resourceViewConfigs.ts
  web/packages/teleterm/src/deepLinks.test.ts
  web/packages/teleterm/src/deepLinks.ts
  web/packages/teleterm/src/main.ts
Labels: ui, size/md, backport/branch/v14, no-changelog

#34256 [v14] Added Database Automatic User Provisioning support for MariaDB
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/database.go
  api/types/types.pb.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/servicecfg/database.go
  lib/srv/db/autousers_test.go
  lib/srv/db/common/autousers.go
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/autousers_test.go
  lib/srv/db/mysql/sql/mariadb_activate_user.sql
  lib/srv/db/mysql/sql/mariadb_deactivate_user.sql
  lib/srv/db/mysql/sql/mariadb_delete_user.sql
  lib/srv/db/mysql/sql/mariadb_revoke_roles.sql
  lib/srv/db/mysql/sql/mysql_activate_user.sql
  lib/srv/db/mysql/sql/mysql_deactivate_user.sql
  lib/srv/db/mysql/sql/mysql_delete_user.sql
  lib/srv/db/mysql/sql/mysql_revoke_roles.sql
  lib/srv/db/postgres/users.go
  tool/tsh/common/db.go
Labels: tsh, database-access, backport, size/md, changelog

#34311 Support applying Users and Roles on startup
  docs/pages/reference/cli/teleport.mdx
  lib/auth/init.go
  lib/auth/init_test.go
  tool/teleport/common/teleport.go
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#34318 Use maps.{Clone,Copy} instead of manual loops
  lib/backend/etcdbk/etcd_test.go
  lib/config/configuration.go
  lib/events/dynamoevents/dynamoevents.go
  lib/kube/proxy/server.go
  lib/kube/proxy/watcher_test.go
  lib/labels/cloud.go
  lib/service/servicecfg/windows.go
  lib/services/reconciler_test.go
  lib/srv/app/watcher_test.go
  lib/srv/regular/sshserver.go
  tool/common/common_test.go
  tool/tctl/common/collection_test.go
  tool/tsh/common/tsh.go
Labels: kubernetes-access, tsh, tctl, audit-log, application-access, size/sm, no-changelog

#34331 docs: add team scope to automatic updates
  docs/config.json
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34338 [v12] chore: Bump golangci-lint to v1.55.2
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#34336 [v14] chore: Bump golangci-lint to v1.55.2
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#33614 Deflake HTTP_PROXY tests
  api/client/webclient/webclient_test.go
  api/testhelpers/proxy.go
  integration/helpers/helpers.go
  integration/integration_test.go
  integration/proxy/proxy_test.go
  lib/client/https_client_test.go
  tool/tsh/common/resolve_default_addr_test.go
Labels: tsh, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34302 Connect My Computer: Derive agent label from username in main process
  gen/proto/go/teleport/lib/teleterm/v1/service.pb.go
  gen/proto/js/teleport/lib/teleterm/v1/service_grpc_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/service_grpc_pb.js
  gen/proto/js/teleport/lib/teleterm/v1/service_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/service_pb.js
  integration/teleterm_test.go
  lib/teleterm/apiserver/handler/handler_connectmycomputer.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/services/connectmycomputer/connectmycomputer.go
  proto/teleport/lib/teleterm/v1/service.proto
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.test.ts
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/mainProcessClient.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/services/connectMyComputer/connectMyComputerService.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog

#33937 MemoryDB IAM auth support
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/srv/db/access_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/errors.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/common/iam/aws_test.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/engine.go
Labels: aws, database-access, db/redis, size/md, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#34335 [v14] Add first step of guided flow for Connect My Computer in Discover
  web/packages/design/src/Card/Card.jsx
  web/packages/design/src/Card/Card.story.tsx
  web/packages/design/src/CardError/CardError.story.jsx
  web/packages/design/src/CardSuccess/CardSuccess.story.jsx
  web/packages/design/src/buttons.story.jsx
  web/packages/shared/components/MenuAction/MenuActionButton.tsx
  web/packages/shared/components/OverrideUserAgent/index.tsx
  web/packages/shared/deepLinks.ts
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.story.tsx
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.tsx
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/index.ts
  web/packages/teleport/src/Discover/ConnectMyComputer/index.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.tsx
  web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/ConnectionDiagnosticResult.tsx
  web/packages/teleport/src/Discover/Shared/StyledBox.ts
  web/packages/teleport/src/Discover/Shared/index.ts
  web/packages/teleport/src/Discover/flow.tsx
  web/packages/teleport/src/Discover/resourceViewConfigs.ts
  web/packages/teleterm/src/deepLinks.test.ts
  web/packages/teleterm/src/deepLinks.ts
  web/packages/teleterm/src/main.ts
Labels: ui, backport, size/md, no-changelog

#34257 Store original roles with user login state.
  api/gen/proto/go/teleport/userloginstate/v1/userloginstate.pb.go
  api/proto/teleport/userloginstate/v1/userloginstate.proto
  api/types/userloginstate/convert/v1/user_login_state.go
  api/types/userloginstate/convert/v1/user_login_state_test.go
  api/types/userloginstate/user_login_state.go
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
  lib/auth/userloginstate/service_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#33841 [v14] event fanout rework
  api/types/watch_status.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/backend/etcdbk/etcd.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/services/fanoutv2.go
  lib/services/fanoutv2_test.go
  lib/utils/fanoutbuffer/buffer.go
  lib/utils/fanoutbuffer/buffer_test.go
  lib/utils/roundrobin.go
  lib/utils/roundrobin_test.go
  tool/tctl/common/loadtest_command.go
Labels: tctl, backport, size/lg

#34322 [v13] Document workload ID for AKS for the helm guide
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
Labels: documentation, backport, size/sm, no-changelog

#34254 Add a Usage Reporting and Billing page
  docs/config.json
  docs/pages/usage-billing.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34323 [v14] Document workload ID for AKS for the helm guide
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
Labels: documentation, backport, size/sm, no-changelog

#34344 [v13] docs: add team scope to automatic updates
  docs/config.json
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, backport, size/sm

#34343 [v14] docs: add team scope to automatic updates
  docs/config.json
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, backport, size/sm

#34366 Move TAG proto back to gen/
  gen/proto/go/accessgraph/v1alpha/query.pb.go
  gen/proto/go/accessgraph/v1alpha/query_grpc.pb.go
  proto/accessgraph/v1alpha/query.proto
  proto/buf.lock
  proto/buf.yaml
Labels: size/sm

#34337 [v13] chore: Bump golangci-lint to v1.55.2
  .github/workflows/lint.yaml
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#34330 Release 13.4.6
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm

#34109 Add AccessGraph service to user roles and ACLs
  api/types/constants.go
  lib/services/presets.go
  lib/services/useracl.go
Labels: size/sm, no-changelog

#33737 assist: emit action events on tool usage
  lib/web/assistant.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#34369 Fix floating error box in Unified View
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
Labels: ui, backport-required, size/sm, backport/branch/v14, no-changelog

#34348 [v14] MemoryDB IAM auth support
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/srv/db/access_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/errors.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/common/iam/aws_test.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/engine.go
Labels: database-access, backport, size/md, changelog

#34357 [v13] MemoryDB IAM auth support
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/srv/db/access_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/errors.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/common/iam/aws_test.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/engine.go
Labels: database-access, backport, size/md, changelog

#34132 [refactor] deprecate db/common/role.DatabaseRoleMatchers
  lib/srv/db/cassandra/engine.go
  lib/srv/db/clickhouse/engine.go
  lib/srv/db/common/role/role.go
  lib/srv/db/common/role/role_test.go
  lib/srv/db/dynamodb/engine.go
  lib/srv/db/elasticsearch/engine.go
  lib/srv/db/mongodb/engine.go
  lib/srv/db/opensearch/engine.go
  lib/srv/db/redis/client.go
  lib/srv/db/redis/cmds.go
  lib/srv/db/redis/engine.go
  lib/srv/db/snowflake/engine.go
Labels: refactoring, database-access, size/md, no-changelog

#34293 [TAG] Add privilege management section to nav, move user roles to that
  web/packages/teleport/src/Navigation/categories.ts
  web/packages/teleport/src/features.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#34385 [v14] Connect My Computer: Derive agent label from username in main process
  gen/proto/go/teleport/lib/teleterm/v1/service.pb.go
  gen/proto/js/teleport/lib/teleterm/v1/service_grpc_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/service_grpc_pb.js
  gen/proto/js/teleport/lib/teleterm/v1/service_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/service_pb.js
  integration/teleterm_test.go
  lib/teleterm/apiserver/handler/handler_connectmycomputer.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/services/connectmycomputer/connectmycomputer.go
  proto/teleport/lib/teleterm/v1/service.proto
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.test.ts
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/mainProcessClient.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/services/connectMyComputer/connectMyComputerService.ts
Labels: ui, backport, size/sm, no-changelog

#34363 [v12] Add a Usage Reporting and Billing page
  docs/config.json
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm

#34362 [v13] Add a Usage Reporting and Billing page
  docs/config.json
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm

#34361 [v14] Add a Usage Reporting and Billing page
  docs/config.json
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm

#34290 Machine ID: More rules to `gitlab` joining and add globby matching to some fields
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/types.pb.go
  docs/config.json
  docs/pages/machine-id/reference/gitlab.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml
  lib/auth/join_gitlab.go
  lib/auth/join_gitlab_test.go
  lib/auth/join_iam.go
  lib/gitlab/gitlab.go
Labels: documentation, helm, size/md, backport/branch/v12, backport/branch/v13, backport/branch/v14

#33415 Introduce scaffolding for access list Slack notification.
  integrations/access/accesslist/app.go
  integrations/access/accesslist/app_test.go
  integrations/access/accesslist/bot.go
  integrations/access/accessrequest/app.go
  integrations/access/accessrequest/bot.go
  integrations/access/accessrequest/message.go
  integrations/access/accessrequest/plugindata.go
  integrations/access/accessrequest/plugindata_test.go
  integrations/access/common/app.go
  integrations/access/common/bot.go
  integrations/access/common/config.go
  integrations/access/common/teleport/client.go
  integrations/access/discord/bot.go
  integrations/access/discord/config.go
  integrations/access/discord/discord_test.go
  integrations/access/discord/helpers_test.go
  integrations/access/jira/app.go
  integrations/access/mattermost/bot.go
  integrations/access/mattermost/config.go
  integrations/access/mattermost/helper_test.go
  integrations/access/mattermost/mattermost_test.go
  integrations/access/opsgenie/app.go
  integrations/access/opsgenie/bot.go
  integrations/access/pagerduty/app.go
  integrations/access/servicenow/app.go
  integrations/access/servicenow/bot.go
  integrations/access/slack/bot.go
  integrations/access/slack/helpers_test.go
  integrations/access/slack/slack_test.go
  integrations/lib/plugindata/access_list.go
  integrations/lib/plugindata/access_list_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/init.go
  lib/services/access_request.go
  lib/services/local/dynamic_access.go
  lib/services/local/plugin_data.go
  lib/services/plugin_data.go
  lib/utils/interval/interval.go
Labels: size/md, backport/branch/v13, backport/branch/v14

#34374 [v14] Fix floating error box in Unified View
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
Labels: ui, backport, size/sm, no-changelog

#34352 Update working on tctl nodes add usage
  tool/tctl/common/usage.go
Labels: tctl, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#34087 Make MFA prompt client agnostic
  api/client/client.go
  api/client/mfa.go
  api/client/mfa_test.go
  api/mfa/prompt.go
  api/utils/grpc/interceptors/mfa.go
  api/utils/grpc/interceptors/mfa_test.go
  lib/auth/authclient/authclient.go
  lib/client/api.go
  lib/client/client.go
  lib/client/cluster_client.go
  lib/client/kubesession.go
  lib/client/local_proxy_middleware.go
  lib/client/mfa.go
  lib/client/mfa/cli.go
  lib/client/mfa/prompt.go
  lib/client/mfa_test.go
  lib/client/presence.go
  lib/client/weblogin.go
  lib/teleterm/clusters/cluster_auth.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/desktop.go
  lib/web/terminal.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/tctl.go
  tool/tsh/common/kube_proxy.go
  tool/tsh/common/mfa.go
Labels: tsh, tctl, desktop-access, size/sm, no-changelog

#34350 Fix default piv key slot to match comments and docs
  api/utils/keys/yubikey.go
  docs/pages/access-controls/guides/hardware-key-support.mdx
  rfd/0080-hardware-key-support.md
Labels: size/sm, backport/branch/v14, no-changelog

#34238 Prevent duplicate node entries in the unified cache
  lib/services/unified_resource.go
  lib/services/unified_resource_test.go
  lib/services/watcher_test.go
Labels: backport-required, size/sm, backport/branch/v14, no-changelog

#33941 desktop access: soften the disconnect error
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#34388 Allow using cluster_networking_config and auth_pref with --bootstrap
  lib/services/local/resource.go
  lib/services/resource.go
Labels: size/sm, backport/branch/v13, backport/branch/v14
