Repository gravitational/teleport, pull requests merged in 2023-09, with the labels that each got.

#31275 Preserve query params in cross-cluster app redirect.
  lib/web/app/transport.go
  lib/web/app/transport_test.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#31338 [v14] fix: Downgrade github.com/fxamacker/cbor/v2 to v2.4.0
  go.mod
  go.sum
  lib/auth/webauthn/register_test.go
Labels: backport, size/sm, merge-for-v14

#31067 Add database access resources for load testing
  assets/loadtest/Makefile
  assets/loadtest/control-plane/Makefile
  assets/loadtest/control-plane/README.md
  assets/loadtest/control-plane/monitoring/create-database-agents.sh
  assets/loadtest/databases/rds/Makefile
  assets/loadtest/databases/rds/README.md
  assets/loadtest/databases/rds/main.tf
  assets/loadtest/databases/rds/outputs.tf
  assets/loadtest/databases/rds/variables.tf
  assets/loadtest/databases/rds/versions.tf
Labels: size/lg

#31209 AWS OIDC EICE: fix connection set up
  api/types/server.go
  api/types/server_test.go
  lib/integrations/awsoidc/eice_opentunnel.go
  lib/integrations/awsoidc/eice_opentunnel_test.go
  lib/integrations/awsoidc/eice_sendsshpublickey.go
  lib/integrations/awsoidc/eice_sendsshpublickey_test.go
  lib/integrations/awsoidc/issuer.go
  lib/integrations/awsoidc/issuer_test.go
  lib/integrations/awsoidc/opentunnelec2_keys.go
  lib/reversetunnel/localsite.go
  lib/srv/forward/sshserver.go
Labels: discover, size/md, backport/branch/v13, backport/branch/v14

#31293 [v14] docs: add prompt field definition for OIDC auth connector
  docs/pages/access-controls/sso/oidc.mdx
  docs/pages/database-access/getting-started.mdx
Labels: documentation, backport, size/sm

#30918 [TAG] Initial integration
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/client/profile.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/kube/proxy/forwarder_test.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/srv.go
  lib/service/service.go
  lib/service/servicecfg/config.go
  lib/services/access_checker.go
  lib/services/access_checker_predicate.go
  lib/srv/app/server.go
  lib/srv/authhandlers.go
  lib/srv/ctx_test.go
  lib/srv/forward/sshserver.go
  lib/srv/mock.go
  lib/srv/regular/sshserver.go
  lib/web/sessions.go
Labels: application-access, size/md

#31343 Fix plugin screen not wrapping tiles
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31331 [v13] Web: return user traits with getUser request
  lib/web/ui/user.go
  web/packages/teleport/src/services/user/makeUser.ts
  web/packages/teleport/src/services/user/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, backport, size/sm

#31362 [v13] AWS OIDC EICE: fix connection set up
  api/types/server.go
  api/types/server_test.go
  lib/integrations/awsoidc/eice_opentunnel.go
  lib/integrations/awsoidc/eice_opentunnel_test.go
  lib/integrations/awsoidc/eice_sendsshpublickey.go
  lib/integrations/awsoidc/eice_sendsshpublickey_test.go
  lib/integrations/awsoidc/issuer.go
  lib/integrations/awsoidc/issuer_test.go
  lib/integrations/awsoidc/opentunnelec2_keys.go
  lib/reversetunnel/localsite.go
  lib/srv/forward/sshserver.go
Labels: backport, size/md

#31355 Make access list membership check fn public
  lib/services/access_list.go
Labels: size/sm

#31332 [v14] Web: return user traits with getUser request
  lib/web/ui/user.go
  web/packages/teleport/src/services/user/makeUser.ts
  web/packages/teleport/src/services/user/types.ts
  web/packages/teleport/src/services/user/user.test.ts
Labels: ui, backport, size/sm

#31365 [v13] Fix plugin screen not wrapping tiles
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
Labels: ui, backport, size/sm

#31364 [v12] Fix plugin screen not wrapping tiles
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
Labels: ui, backport, size/sm

#31336 [v13] docs: describe dedicated account dashboard for ent
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/license.mdx
  docs/pages/database-access/getting-started.mdx
Labels: documentation, backport, size/sm

#31318 [v13] Remove note about canceled requests not being supported
  docs/pages/database-access/faq.mdx
Labels: documentation, backport, size/sm

#31337 [v12] docs: describe dedicated account dashboard for ent
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/license.mdx
Labels: documentation, backport, size/sm

#31335 [v14] docs: describe dedicated account dashboard for ent
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/license.mdx
Labels: documentation, backport, size/sm

#31296 improve ControlMaster error reporting 2
  integration/integration_test.go
Labels: size/sm

#31366 [v14] Fix plugin screen not wrapping tiles
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
Labels: ui, backport, size/sm

#31368 Tweak passwordless and device trust testplan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#31377 [v11] Preserve query params in cross-cluster app redirect.
  lib/web/app/transport.go
  lib/web/app/transport_test.go
Labels: backport, size/sm

#31272 [v13] AWS OIDC: List Security Groups
  lib/integrations/awsoidc/list_security_groups.go
  lib/integrations/awsoidc/list_security_groups_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: backport, size/md

#31380 [v14] Preserve query params in cross-cluster app redirect.
  lib/web/app/transport.go
  lib/web/app/transport_test.go
Labels: backport, size/sm

#31273 [v14] AWS OIDC: List Security Groups
  lib/integrations/awsoidc/list_security_groups.go
  lib/integrations/awsoidc/list_security_groups_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: backport, size/md

#31351 Rename Kubernetes Role resource to prevent overlap with Teleport Role
  api/types/constants.go
Labels: size/sm, backport/branch/v14

#31358 pgbk: schema version 2, more robust change feed parsing
  lib/backend/pgbk/background.go
  lib/backend/pgbk/common/utils.go
  lib/backend/pgbk/pgbk.go
  lib/events/pgevents/pgevents.go
Labels: audit-log, size/sm, changelog, backport/branch/v14, merge-for-v14

#31360 fix: Skip known bad asset tags on Windows
  lib/devicetrust/native/device_windows.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, merge-for-v14

#31227 desktop discovery: unmap IPv6 addresses
  lib/srv/desktop/discovery.go
Labels: desktop-access, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31407 Fix webauthnwin c types size
  lib/auth/webauthnwin/ctypes.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14, merge-for-v14

#31374 Update product change log link
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31421 [v14] Fix webauthnwin c types size
  lib/auth/webauthnwin/ctypes.go
Labels: backport, size/sm

#31420 [v13] Fix webauthnwin c types size
  lib/auth/webauthnwin/ctypes.go
Labels: backport, size/sm

#31330 [v14] Fix JSON marshalling for Audit struct
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
Labels: backport, size/sm

#31315 [v12] docs: update db getting started and mongodb atlas
  docs/pages/database-access/getting-started.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#31356 docs: use branch link instead of master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/kubernetes-access/register-clusters/static-kubeconfig.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/azure-discovery.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
  docs/pages/server-access/guides/gcp-discovery.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31415 AWS OIDC - List EC2: add AWS EC2 Instance ID as label
  lib/integrations/awsoidc/listec2_test.go
  lib/services/server.go
  lib/services/server_test.go
Labels: discover, size/sm, backport/branch/v13, backport/branch/v14

#31398 [v14] Rename Kubernetes Role resource to prevent overlap with Teleport Role
  api/types/constants.go
Labels: backport, size/sm

#31424 [v13] Update product change log link
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#31423 [v14] Update product change log link
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#31436 [v13] AWS OIDC - List EC2: add AWS EC2 Instance ID as label
  lib/integrations/awsoidc/listec2_test.go
  lib/services/server.go
  lib/services/server_test.go
Labels: backport, size/sm

#31164 [v13] Periodically refresh Azure cloud credentials
  lib/cloud/azure/client_map.go
  lib/cloud/azure/client_map_test.go
  lib/cloud/clients.go
  lib/srv/server/azure_watcher.go
Labels: backport, size/sm

#31328 [v13] Update device trust docs
  docs/config.json
  docs/img/access-controls/device-trust/hosted-jamf.png
  docs/img/access-controls/device-trust/select-jamf.png
  docs/pages/access-controls/device-trust.mdx
  docs/pages/access-controls/device-trust/auto-enrollment.mdx
  docs/pages/access-controls/device-trust/device-management.mdx
  docs/pages/access-controls/device-trust/enforcing-device-trust.mdx
  docs/pages/access-controls/device-trust/guide.mdx
  docs/pages/access-controls/device-trust/jamf-integration.mdx
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/includes/device-trust/enroll-troubleshooting.mdx
Labels: documentation, backport, size/md

#31402 [v13] MySQL: avoid tiny writes to improve performance in read-heavy scenarios
  lib/srv/db/mysql/engine.go
Labels: database-access, backport, size/sm

#31418 Fix `tsh kube login` when creds are expired or doesn't exist
  tool/tsh/common/kube.go
Labels: tsh, size/sm, backport/branch/v14

#31412 [v13] fix: Skip known bad asset tags on Windows
  lib/devicetrust/native/device_windows.go
Labels: backport, size/sm, changelog

#31433 [v12] desktop discovery: unmap IPv6 addresses
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access, size/sm

#31432 [v11] desktop discovery: unmap IPv6 addresses
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access, size/sm

#31325 [v14] Use protocol specific icons on unified resource database cards
  web/packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
  web/packages/teleport/src/Databases/fixtures/index.ts
  web/packages/teleport/src/UnifiedResources/ResourceCard.tsx
Labels: ui, backport, size/md

#31411 [v14] fix: Skip known bad asset tags on Windows
  lib/devicetrust/native/device_windows.go
Labels: backport, size/sm, changelog

#31409 TestPlan: remove OpenSSH nodes tests
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#31434 [v13] desktop discovery: unmap IPv6 addresses
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access, size/sm

#31435 [v14] desktop discovery: unmap IPv6 addresses
  lib/srv/desktop/discovery.go
Labels: backport, desktop-access, size/sm

#31301 Added 08/31 Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#31439 [v14] Fix `tsh kube login` when creds are expired or doesn't exist
  tool/tsh/common/kube.go
Labels: tsh, backport, size/sm

#31178 Use app specific icons for unified resource app cards
  web/packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
  web/packages/teleport/src/Apps/fixtures/index.ts
  web/packages/teleport/src/UnifiedResources/ResourceCard.tsx
  web/packages/teleport/src/services/apps/apps.test.ts
  web/packages/teleport/src/services/apps/makeApps.ts
  web/packages/teleport/src/services/apps/types.ts
Labels: ui, backport-required, size/sm, backport/branch/v14

#31427 docs: include ent cloud version for faq question on sso
  docs/pages/faq.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31438 Perform rate limiting on all user-initiated LLM calls in assist
  lib/web/assistant.go
Labels: size/sm, backport/branch/v13, assist, backport/branch/v14

#31430 docs: Fix typo in JSON
  docs/pages/server-access/guides/azure-discovery.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14

#31426 pgbk: parse wal2json messages on the client side
  lib/backend/pgbk/background.go
  lib/backend/pgbk/pgbk.go
  lib/backend/pgbk/utils.go
  lib/backend/pgbk/wal2json.go
  lib/backend/pgbk/wal2json_test.go
Labels: size/md, backport/branch/v14, merge-for-v14

#31455 [v13] docs: include ent cloud version for faq question on sso
  docs/pages/faq.mdx
Labels: documentation, backport, size/sm

#31456 [v12] docs: include ent cloud version for faq question on sso
  docs/pages/faq.mdx
Labels: documentation, backport, size/sm

#31454 [v14] docs: include ent cloud version for faq question on sso
  docs/pages/faq.mdx
Labels: documentation, backport, size/sm

#31452 [v13] docs: Fix typo in JSON
  docs/pages/server-access/guides/azure-discovery.mdx
Labels: documentation, backport, size/sm

#31453 [v14] docs: Fix typo in JSON
  docs/pages/server-access/guides/azure-discovery.mdx
Labels: documentation, backport, size/sm

#31311 Clarify the docs test plan
  .github/ISSUE_TEMPLATE/test-plan-docs.md
Labels: size/sm

#31465 [v12] docs: include sudo for example commands
  docs/pages/deploy-a-cluster/deployments/ibm.mdx
  docs/pages/includes/database-access/db-configure-start.mdx
  docs/pages/management/admin/self-signed-certs.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#31463 [v13] docs: include sudo for example commands
  docs/pages/access-controls/device-trust/jamf-integration.mdx
  docs/pages/deploy-a-cluster/deployments/ibm.mdx
  docs/pages/includes/database-access/db-configure-start.mdx
  docs/pages/management/admin/self-signed-certs.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#31470 [v12] docs: use branch link instead of master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/kubernetes-access/register-clusters/static-kubeconfig.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/azure-discovery.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport, size/sm

#31467 [v13] docs: use branch link instead of master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/kubernetes-access/register-clusters/static-kubeconfig.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/azure-discovery.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
  docs/pages/server-access/guides/gcp-discovery.mdx
Labels: documentation, backport, size/sm

#31468 docs: correct branch version on file link
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, size/sm

#31466 [v14] docs: use branch link instead of master
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/kubernetes-access/register-clusters/static-kubeconfig.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides/azure-discovery.mdx
  docs/pages/server-access/guides/ec2-discovery.mdx
  docs/pages/server-access/guides/gcp-discovery.mdx
Labels: documentation, backport, size/sm

#31471 Deny tj/assert and golang.design
  .golangci.yml
Labels: size/sm

#31462 [v14] docs: include sudo for example commands
  docs/pages/access-controls/device-trust/jamf-integration.mdx
  docs/pages/deploy-a-cluster/deployments/ibm.mdx
  docs/pages/includes/database-access/db-configure-start.mdx
  docs/pages/management/admin/self-signed-certs.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#31397 Add default GitHub API URLs to SSO connector
  api/types/github.go
  docs/pages/access-controls/sso/github-sso.mdx
  tool/tctl/sso/configure/github.go
Labels: documentation, tctl, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31022 update ToolTipNoPermBadge component
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.story.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.test.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/index.ts
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14

#31297 [v14] Deprecated Restricted Sessions for SSH
  docs/pages/server-access/guides/restricted-session.mdx
  lib/config/configuration.go
Labels: documentation, backport, size/sm

#31478 Use localstorage package instead of default
  web/packages/teleport/src/Desktops/Desktops.tsx
Labels: ui, backport-required, size/sm, backport/branch/v14

#31451 [v14] pgbk: parse wal2json messages on the client side
  lib/backend/pgbk/background.go
  lib/backend/pgbk/pgbk.go
  lib/backend/pgbk/utils.go
  lib/backend/pgbk/wal2json.go
  lib/backend/pgbk/wal2json_test.go
Labels: backport, size/md, merge-for-v14

#31449 [v13] pgbk: partial backports #31358 #31426
  lib/backend/pgbk/background.go
  lib/backend/pgbk/common/utils.go
  lib/backend/pgbk/pgbk.go
  lib/backend/pgbk/utils.go
  lib/backend/pgbk/wal2json.go
  lib/backend/pgbk/wal2json_test.go
  lib/events/pgevents/pgevents.go
Labels: backport, size/md

#31437 [v14] AWS OIDC - List EC2: add AWS EC2 Instance ID as label
  lib/integrations/awsoidc/listec2_test.go
  lib/services/server.go
  lib/services/server_test.go
Labels: backport, size/sm

#31268 [v13] AWS OIDC - DeployService: add optional Security Groups
  lib/cloud/aws/policy_statements.go
  lib/integrations/awsoidc/deployservice.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: backport, size/sm

#31400 Add access graph layouting dependencies
  web/packages/e-imports/package.json
  web/packages/teleport/src/types.ts
  yarn.lock
Labels: ui, size/xl

#31445 Wraps go-redis internal logger and logs at TRACE level.
  lib/srv/db/redis/engine.go
Labels: database-access, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31269 [v14] AWS OIDC - DeployService: add optional Security Groups
  lib/cloud/aws/policy_statements.go
  lib/integrations/awsoidc/deployservice.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: backport, size/sm

#31309 Remove enterprise specific download link
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31214 Update test plan with unified resource tasks
  .github/ISSUE_TEMPLATE/webtestplan.md
Labels: size/sm

#31431 Edit Server Access intro guide architecture info
  docs/pages/server-access/getting-started.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#29962 Azure HA Teleport deployment guide
  docs/config.json
  docs/cspell.json
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, size/md, backport/branch/v13, backport/branch/v14

#31444 Add AccessList with member upserting functionality
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/types/accesslist/convert/v1/member.go
  lib/services/access_list.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/md, backport/branch/v13, backport/branch/v14

#31461 test plan: remove restricted sessions
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#26033 Add environment leak test to bloat test CI
  .github/workflows/bloat.yaml
  Makefile
Labels: security, size/sm

#31491 [v12] Update download links on support page
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#31492 [v13] Update download links on support page
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#31490 [v14] Remove enterprise specific download link
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm

#31484 [v14] Use localstorage package instead of default
  web/packages/teleport/src/Desktops/Desktops.tsx
Labels: ui, backport, size/sm

#31473 [auto] docs: Update version to v13.3.8
  docs/config.json
Labels: documentation, backport, size/sm

#30586 docs: minor updates to aws opensearch and azure sql server guides
  docs/pages/database-access/guides/aws-opensearch.mdx
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31489 Fix typo in teleport-kube-agent Chart Reference
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31506 [v13] chore: Bump Go to v1.20.8
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#31334 docs: Remove version warnings for versions under v11
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/architecture/proxy-peering.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/elastic.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
  docs/pages/database-access/guides/snowflake.mdx
  docs/pages/desktop-access/active-directory.mdx
  docs/pages/includes/database-access/rotation-note.mdx
Labels: documentation, size/sm, backport/branch/v14

#31475 Ensures the canvas stays at a fixed size
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
Labels: ui, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31511 [v14] chore: Bump Go to 1.21.1
  .drone.yml
  .github/workflows/build-api.yaml
  build.assets/Dockerfile-grpcbox
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#31509 [v11] chore: Bump Go to v1.20.8
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#31501 [v13] Azure HA Teleport deployment guide
  docs/config.json
  docs/cspell.json
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/md

#31540 Adds link to patch for desktop access warnings/errors test
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#31493 [v13] Edit Server Access intro guide architecture info
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#31494 [v14] Edit Server Access intro guide architecture info
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#31542 Add ARM64 toolchain to Dockerfile-arm
  build.assets/Dockerfile-arm
Labels: size/sm

#31543 Release 11.3.23
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#31488 [v13] update ToolTipNoPermBadge component
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.story.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.test.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/index.ts
Labels: ui, backport, size/sm

#31520 [v14] docs: Remove version warnings for versions under v11
  docs/pages/access-controls/guides/locking.mdx
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/architecture/proxy-peering.mdx
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/elastic.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/redis-cluster.mdx
  docs/pages/database-access/guides/redis.mdx
  docs/pages/database-access/guides/snowflake.mdx
  docs/pages/desktop-access/active-directory.mdx
  docs/pages/includes/database-access/rotation-note.mdx
Labels: documentation, backport, size/sm

#31487 [v14] update ToolTipNoPermBadge component
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.story.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.test.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/index.ts
Labels: ui, backport, size/sm

#31503 [v13] Align auth connector tiles
  web/packages/teleport/src/AuthConnectors/styles/LockedFeatureContainer.styles.ts
Labels: ui, backport, size/sm

#31504 [v14] Align auth connector tiles
  web/packages/teleport/src/AuthConnectors/styles/LockedFeatureContainer.styles.ts
Labels: ui, backport, size/sm

#31535 Improve logging for the upload completer
  lib/events/complete.go
  lib/events/s3sessions/s3stream.go
Labels: audit-log, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#31502 [v14] Azure HA Teleport deployment guide
  docs/config.json
  docs/cspell.json
  docs/pages/deploy-a-cluster/helm-deployments/azure.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/md

#31560 [TAG] Add missing theme values
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
Labels: ui, size/md

#31551 [v13] Bump cloud version
  docs/config.json
Labels: documentation, backport, size/sm

#31558 [v11] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#31562 [v13] docs: update docker image versions
  docs/config.json
Labels: documentation, backport, size/sm

#31485 [v14] Wraps go-redis internal logger and logs at TRACE level.
  lib/srv/db/redis/engine.go
Labels: database-access, backport, size/sm

#31550 [v14] Bump cloud version
  docs/config.json
Labels: documentation, backport, size/sm

#31548 [v12] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#31499 post-release: specify base branch for docs PR
  .github/workflows/post-release.yaml
Labels: size/sm, backport/branch/v13

#31547 Web: Fix not being able to search for locks in table
  web/packages/teleport/src/LocksV2/Locks/Locks.test.tsx
  web/packages/teleport/src/LocksV2/Locks/Locks.tsx
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14

#31563 Use lib/cloud/aws instead of db errors for ec2 discovery
  lib/srv/server/ec2_watcher.go
Labels: size/sm, backport/branch/v14

#31581 [v13] Web: Fix not being able to search for locks in table
  web/packages/teleport/src/LocksV2/Locks/Locks.test.tsx
  web/packages/teleport/src/LocksV2/Locks/Locks.tsx
Labels: ui, backport, size/sm

#31578 Add awsroles to app resource card
  lib/web/ui/app.go
Labels: backport-required, size/sm, backport/branch/v14

#31582 [v14] Web: Fix not being able to search for locks in table
  web/packages/teleport/src/LocksV2/Locks/Locks.test.tsx
  web/packages/teleport/src/LocksV2/Locks/Locks.tsx
Labels: ui, backport, size/sm

#31448 [v14] Use app specific icons for unified resource app cards
  web/packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
  web/packages/teleport/src/Apps/fixtures/index.ts
  web/packages/teleport/src/UnifiedResources/ResourceCard.tsx
  web/packages/teleport/src/services/apps/apps.test.ts
  web/packages/teleport/src/services/apps/makeApps.ts
  web/packages/teleport/src/services/apps/types.ts
Labels: ui, backport, size/md

#31576 [Web] Fix terminal resizing
  lib/web/terminal.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#31583 [v14] Add awsroles to app resource card
  lib/web/ui/app.go
Labels: backport, size/sm

#31124 Make `TestIntegrations/ReconcileLabels` a unit test
  integration/integration_test.go
  lib/auth/server_info_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#31474 Add tooltip for truncated text and click to copy
  web/packages/teleport/src/UnifiedResources/ResourceCard.tsx
Labels: ui, backport-required, size/md, backport/branch/v14

#31580 Deflake `TestIntegrations/Discovery`
  integration/integration_test.go
  lib/reversetunnel/peer.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#31522 [v11] Ensures the canvas stays at a fixed size
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
Labels: ui, backport, size/sm, changelog

#31524 [v13] Ensures the canvas stays at a fixed size
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
Labels: ui, backport, size/sm, changelog

#31567 [v13] Perform rate limiting on all user-initiated LLM calls in assist
  lib/web/assistant.go
Labels: backport, size/sm

#31523 [v12] Ensures the canvas stays at a fixed size
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
Labels: ui, backport, size/sm, changelog

#31566 [v14] Perform rate limiting on all user-initiated LLM calls in assist
  lib/web/assistant.go
Labels: backport, size/sm

#31344 [Web] Fix Unified Resources Empty States
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/UnifiedResources/FilterPanel.tsx
  web/packages/teleport/src/UnifiedResources/Resources.tsx
  web/packages/teleport/src/components/Empty/Empty.tsx
  web/packages/teleport/src/services/localStorage/localStorage.ts
Labels: ui, size/sm, backport/branch/v14

#31529 [v12] docs: minor update azure sql server guides
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
Labels: documentation, backport, size/sm

#31531 [v13] docs: minor updates to aws opensearch and azure sql server guides
  docs/pages/database-access/guides/aws-opensearch.mdx
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
Labels: documentation, backport, size/sm

#31536 [v13] Fix typo in teleport-kube-agent Chart Reference
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport, size/sm

#31525 [v14] Ensures the canvas stays at a fixed size
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
Labels: ui, backport, size/sm, changelog

#31537 [v14] Fix typo in teleport-kube-agent Chart Reference
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport, size/sm

#31534 [v14] docs: minor updates to aws opensearch and azure sql server guides
  docs/pages/database-access/guides/aws-opensearch.mdx
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
Labels: documentation, backport, size/sm

#31596 [v14] Deflake `TestIntegrations/Discovery`
  integration/integration_test.go
  lib/reversetunnel/peer.go
Labels: backport, size/sm

#31586 [v13] [Web] Fix terminal resizing
  lib/web/terminal.go
Labels: backport, size/sm

#31585 [v14] [Web] Fix terminal resizing
  lib/web/terminal.go
Labels: backport, size/sm
