Repository gravitational/teleport, pull requests merged in 2023-03, with the labels that each got.

#22421 [v10] sshserver: Correctly handle PuTTY winadj channel requests
  lib/srv/forward/sshserver.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/req.go
Labels: backport, size/sm

#22161 Fix pickDefaultAddr not respecting HTTPS_PROXY
  tool/tsh/resolve_default_addr.go
  tool/tsh/resolve_default_addr_test.go
Labels: tsh, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22340 [v11] Always include webassets_embed when building teleport
  Makefile
Labels: backport, size/sm

#22407 Backport #22281 to branch/v11
  tool/tsh/tsh.go
Labels: tsh, backport, size/sm

#22449 bump cloud version
  docs/config.json
Labels: documentation, size/sm

#22418 [v12] docs: use approved terminology for desktop access w/ local users
  docs/pages/desktop-access/active-directory-manual.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/introduction.mdx
Labels: documentation, backport, size/sm

#22430 chore: Bump Buf to v1.15.0
  build.assets/Dockerfile
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22306 Allow devices writes with resource-like semantics
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service.pb.go
  api/proto/teleport/devicetrust/v1/devicetrust_service.proto
Labels: size/sm, backport/branch/v12

#22412 [v12] Use developer-friendly and precise technical language in docs
  docs/pages/index.mdx
Labels: documentation, backport, backport/branch/v10, backport/branch/v11, size/sm

#22463 Add docs steps to create machine-id data dir and systemd enablement
  docs/pages/includes/machine-id/machine-id-init-bot-data.mdx
  docs/pages/includes/machine-id/machine-id-service.mdx
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22348 [v11] Enable xterm links and clean up MFA modal
  web/packages/teleport/package.json
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx
  web/packages/teleport/src/lib/term/terminal.ts
  yarn.lock
Labels: ui, backport, size/sm

#22312 [v11] Remove non-applicable roles from teleport start --roles reference
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#22479 [v10] Add docs steps to create machine-id data dir and systemd enablement
  docs/pages/includes/machine-id/machine-id-init-bot-data.mdx
  docs/pages/includes/machine-id/machine-id-service.mdx
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
Labels: documentation, backport, size/sm

#22477 [v12] Add docs steps to create machine-id data dir and systemd enablement
  docs/pages/includes/machine-id/machine-id-init-bot-data.mdx
  docs/pages/includes/machine-id/machine-id-service.mdx
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
Labels: documentation, backport, size/sm

#22446 Add known STS endpoint for ap-southeast-4
  lib/auth/sts_endpoints.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22422 [v12] Add static and dynamic web ui configuration options
  api/client/client.go
  api/client/events.go
  api/client/proto/authservice.pb.go
  api/client/webclient/webconfig.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/types.pb.go
  api/types/ui_config.go
  lib/auth/api.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/service.go
  lib/services/configuration.go
  lib/services/local/configuration.go
  lib/services/local/events.go
  lib/services/presets.go
  lib/services/resource.go
  lib/services/role.go
  lib/services/ui_config.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/lib/term/terminal.ts
Labels: ui, tctl, backport, size/lg

#22425 Use `curl -fsS` when downloading libbpf
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
  build.assets/Dockerfile-fips
Labels: size/sm, backport/branch/v12

#22368 [v12] Automatically parse entity ID from SAML SP during CLI creation.
  api/go.mod
  api/go.sum
  api/types/saml_idp_service_provider.go
  api/types/saml_idp_service_provider_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/sm

#20246 Server Access RBAC Docs page
  docs/config.json
  docs/pages/server-access/rbac.mdx
Labels: documentation, ssh, backport/branch/v10, backport/branch/v11, size/md, backport/branch/v12

#22485 Move makefile BPF to common.mk
  Makefile
  common.mk
Labels: size/sm, backport/branch/v12

#22388 Improve `tsh kube credentials` read operations
  api/utils/keys/privatekey.go
  lib/client/api.go
  lib/client/client_store.go
  lib/teleterm/clusters/storage.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: tsh, backport/branch/v10, backport/branch/v11, size/md, backport/branch/v12

#22208 SAML IdP audit events.
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, audit-log, size/md, backport/branch/v12

#22434 Okta local service.
  lib/services/local/okta.go
  lib/services/local/okta_test.go
Labels: size/md, backport/branch/v12

#22431 [v12] Initial Okta objects.
  api/constants/constants.go
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/okta.go
  api/types/types.pb.go
  lib/services/okta.go
  lib/services/okta_test.go
Labels: backport, size/lg

#22473 [v11] chore: Bump Buf to v1.15.0
  build.assets/Dockerfile
Labels: backport, size/sm

#22427 [v11] feat: add LoginRule methods to api/client
  api/client/client.go
Labels: backport, size/sm

#22470 [v12] Allow devices writes with resource-like semantics
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service.pb.go
  api/proto/teleport/devicetrust/v1/devicetrust_service.proto
Labels: backport, size/sm

#22499 Teleport 12 Videos
  docs/pages/access-controls/guides/device-trust.mdx
  docs/pages/index.mdx
Labels: documentation, size/sm, backport/branch/v12

#22472 [v12] chore: Bump Buf to v1.15.0
  build.assets/Dockerfile
Labels: backport, size/sm

#22475 [v10] chore: Bump Buf to v1.15.0
  build.assets/Dockerfile
Labels: backport, size/sm

#22489 Webapp yarn updates
  yarn.lock
Labels: security, dependencies, size/sm

#21649 Refresh the Access Controls menu
  docs/config.json
  docs/pages/access-controls/introduction.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#21087 Add auto-joining for Azure VMs
  api/types/constants.go
  api/types/installers/installer.sh.tmpl
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/join.go
  lib/cloud/azure/vm.go
  lib/cloud/clients.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/defaults/defaults.go
  lib/services/matchers.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/server/azure_installer.go
  lib/srv/server/azure_watcher.go
Labels: tctl, size/md, backport/branch/v12

#22501 [v11] Server Access RBAC Docs page
  docs/config.json
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/md

#22513 [v12] Okta local service.
  lib/services/local/okta.go
  lib/services/local/okta_test.go
Labels: backport, size/md

#22500 [v12] Server Access RBAC Docs page
  docs/config.json
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/md

#22502 [v10] Server Access RBAC Docs page
  docs/config.json
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/md

#22515 [v11] Remove test keys
  lib/auth/native/native.go
  lib/auth/testauthority/testauthority.go
  lib/client/identityfile/identity_test.go
Labels: backport, size/sm

#22486 [v12] Add known STS endpoint for ap-southeast-4
  lib/auth/sts_endpoints.go
Labels: backport, size/sm

#22487 [v11] Add known STS endpoint for ap-southeast-4
  lib/auth/sts_endpoints.go
Labels: backport, size/sm

#22442 [v12] Make curl fail on server error when downloading binaries in buildbox (#22380)
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
Labels: backport, size/sm

#22445 [v10] Make curl fail on server error when downloading binaries in buildbox (#22380)
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
Labels: backport, size/sm

#22488 [v10] Add known STS endpoint for ap-southeast-4
  lib/auth/sts_endpoints.go
Labels: backport, size/sm

#21860 Distroless dockerfile and smoke tests for same
  build.assets/charts/Dockerfile-distroless
  build.assets/charts/fetch-debs
  build.assets/charts/smoke_tests/00_simple_start/test.sh
  build.assets/charts/smoke_tests/01_pam/config.yaml
  build.assets/charts/smoke_tests/01_pam/test.sh
  build.assets/charts/smoke_tests/README.md
  build.assets/charts/smoke_tests/run
Labels: size/md

#22512 [v12] `lib/usagereporter` refactor and consolidation
  lib/auth/auth.go
  lib/auth/init.go
  lib/events/usageevents/usageevents.go
  lib/service/cfg.go
  lib/services/usagereporter.go
  lib/teleterm/daemon/daemon.go
  lib/usagereporter/daemon/usagereporter.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/types_discover.go
  lib/usagereporter/teleport/usagereporter.go
  lib/usagereporter/teleport/usagereporter_test.go
  lib/usagereporter/web/userevent.go
  lib/usagereporter/web/userevent_discover.go
  lib/usagereporter/web/userevent_discover_test.go
  lib/usagereporter/web/userevent_test.go
  lib/web/userevent.go
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, audit-log, backport, size/md

#22520 [v11] `lib/usagereporter` refactor and consolidation
  lib/auth/auth.go
  lib/auth/init.go
  lib/events/usageevents/usageevents.go
  lib/service/cfg.go
  lib/services/local/usagereporter.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/types_discover.go
  lib/usagereporter/teleport/usagereporter.go
  lib/usagereporter/teleport/usagereporter_test.go
  lib/usagereporter/usagereporter.go
  lib/usagereporter/usagereporter_test.go
  lib/usagereporter/web/userevent.go
  lib/usagereporter/web/userevent_discover.go
  lib/usagereporter/web/userevent_discover_test.go
  lib/usagereporter/web/userevent_test.go
  lib/web/userevent.go
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, audit-log, backport, size/md

#22539 Update SAML IdP auth attempt code variable name.
  lib/events/codes.go
Labels: audit-log, size/sm

#22510 [v12] SAML IdP audit events.
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, audit-log, backport, size/lg

#22304 Add GCP Service Account parameter to tctl users add reference
  docs/pages/reference/cli.mdx
Labels: documentation, size/sm, backport/branch/v12

#22508 [v12] Improve `tsh kube credentials` read operations
  api/utils/keys/privatekey.go
  lib/client/api.go
  lib/client/client_store.go
  lib/teleterm/clusters/storage.go
  tool/tsh/kube.go
  tool/tsh/tsh.go
Labels: tsh, backport, size/md

#22522 Webapp Yarn Updates 2
  yarn.lock
Labels: size/sm

#19261 RFD 98: Registered OpenSSH Nodes
  rfd/0098-registered-openssh-nodes.md
Labels: rfd, size/sm

#22518 [v12] Set `create_as_resource` in device-related `tctl` RPCs
  tool/tctl/common/device/resource.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm

#22492 [v12] Fix pickDefaultAddr not respecting HTTPS_PROXY
  tool/tsh/resolve_default_addr.go
  tool/tsh/resolve_default_addr_test.go
Labels: tsh, backport, size/sm

#22495 [v12] Unify x86/ARM64 build process
  .github/workflows/build-centos7-assets.yaml
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-assets
  build.assets/Makefile
Labels: backport, size/sm

#22308 Add Kubernetes Access tracing
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, size/md

#22545 SAML Grafana guide
  docs/config.json
  docs/pages/access-controls/idps.mdx
  docs/pages/access-controls/idps/saml-grafana.mdx
Labels: documentation, size/md

#22491 [v11] Fix pickDefaultAddr not respecting HTTPS_PROXY
  tool/tsh/resolve_default_addr.go
  tool/tsh/resolve_default_addr_test.go
Labels: tsh, backport, size/sm

#22521 [v12] Add Azure auto-joining
  api/types/constants.go
  api/types/installers/installer.sh.tmpl
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/join.go
  lib/cloud/azure/vm.go
  lib/cloud/clients.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/defaults/defaults.go
  lib/services/matchers.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/server/azure_installer.go
  lib/srv/server/azure_watcher.go
Labels: backport, size/lg

#22350 Headless login: add headless authentication resource type
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/headlessauthn.go
  api/types/types.pb.go
  lib/services/headlessauthn.go
Labels: size/sm

#22560 Spellfix access control intro
  docs/pages/access-controls/introduction.mdx
Labels: documentation, size/sm

#22527 Teleport 12 Videos [v12 Backport]
  docs/pages/access-controls/guides/device-trust.mdx
  docs/pages/index.mdx
Labels: documentation, backport, size/sm

#22550 [v12] Enable BPF on ARM64
  Makefile
  bpf/arm64/vmlinux.h
  bpf/enhancedrecording/disk.bpf.c
  bpf/vmlinux.h
  bpf/x86/vmlinux.h
  common.mk
  lib/bpf/disk.go
Labels: bpf, backport, size/xl

#22547 Added 03/02 Upcoming Releases Update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#22283 Add Telnet into docker to test connectivity for cloud getting started
  docs/pages/choose-an-edition/teleport-cloud/getting-started.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12

#22523 [v12] Refresh the Access Controls menu
  docs/config.json
  docs/pages/access-controls/introduction.mdx
Labels: documentation, backport, size/sm

#22481 Move IP pinning RFD from private repo.
  rfd/0110-ip-pinning-and-propagation.md
Labels: rfd, size/md

#22455 Refresh remote cluster connection status periodically
  lib/auth/auth.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
Labels: bug, scale, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22569 [v12] Fix compilation on ARM
  Makefile
Labels: backport, size/sm

#22458 RFD 01111 - Support connection testers when per-session MFA is enabled
  rfd/0111-support-connection-testers-with-per-session-mfa.md
Labels: rfd, size/sm

#22461 Allow all alert severities to be acknowledged
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
Labels: backport/branch/v11, size/sm, backport/branch/v12

#22465 [v12] Backport #22336
  e_imports.go
  go.mod
  go.sum
Labels: backport, size/md

#22582 [v12] Allow all alert severities to be acknowledged
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
Labels: backport, size/sm

#22193 Connect: Prepare keyboard shortcuts configuration
  web/packages/teleterm/src/services/config/configService.ts
  web/packages/teleterm/src/ui/Documents/KeyboardShortcutsPanel.tsx
  web/packages/teleterm/src/ui/QuickInput/useQuickInput.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.tsx
  web/packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
  web/packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
  web/packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
  web/packages/teleterm/src/ui/TopBar/Clusters/Clusters.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsIcon/ConnectionsIcon.tsx
  web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
  web/packages/teleterm/src/ui/services/keyboardShortcuts/keyboardShortcutsService.test.ts
  web/packages/teleterm/src/ui/services/keyboardShortcuts/keyboardShortcutsService.ts
  web/packages/teleterm/src/ui/services/keyboardShortcuts/types.ts
  web/packages/teleterm/src/ui/services/keyboardShortcuts/useKeyboardShortcutFormatters.ts
  web/packages/teleterm/src/ui/services/keyboardShortcuts/useKeyboardShortcuts.test.tsx
  web/packages/teleterm/src/ui/services/keyboardShortcuts/useKeyboardShortcuts.ts
Labels: ui, size/sm, backport/branch/v12

#22583 [v11] Allow all alert severities to be acknowledged
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
Labels: backport, size/sm

#22570 [v12] Add Telnet into docker to test connectivity for cloud getting started
  docs/pages/choose-an-edition/teleport-cloud/getting-started.mdx
Labels: documentation, backport, size/sm

#22543 [v12] Add GCP Service Account parameter to tctl users add reference
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#22584 NodeJoin Script: clear yum repo cache
  lib/web/scripts/node-join/install.sh
Labels: size/sm, backport/branch/v12

#22571 [v11] Add Telnet into docker to test connectivity for cloud getting started
  docs/pages/choose-an-edition/teleport-cloud/getting-started.mdx
Labels: documentation, backport, size/sm

#22549 Skip building webassets in CI
  .github/workflows/flaky-tests.yaml
  .github/workflows/integration-tests-non-root.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/os-compatibility-test.yaml
  .github/workflows/unit-tests-code.yaml
  Makefile
  integration/integration_test.go
  lib/httplib/httplib_test.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#21938 Preform RBAC checks before connecting to registered OpenSSH nodes
  api/types/constants.go
  lib/proxy/router.go
  lib/proxy/router_test.go
  lib/reversetunnel/api.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/remotesite.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  lib/srv/forward/sshserver.go
  lib/srv/forward/sshserver_test.go
Labels: size/md, backport/branch/v12

#21490 node hb and watcher scalability improvements
  integration/proxy/proxy_helpers.go
  lib/cache/cache.go
  lib/defaults/defaults.go
  lib/services/watcher.go
  lib/srv/heartbeatv2.go
  lib/srv/heartbeatv2_test.go
  lib/srv/regular/sshserver.go
  lib/utils/retry.go
Labels: size/sm

#22562 [v12] Add in SAML IdP service provider session metadata to auth attempts.
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#21495 [v12] node hb and watcher scalability improvements
  integration/proxy/proxy_helpers.go
  lib/cache/cache.go
  lib/defaults/defaults.go
  lib/services/watcher.go
  lib/srv/heartbeatv2.go
  lib/srv/heartbeatv2_test.go
  lib/srv/regular/sshserver.go
  lib/utils/retry.go
Labels: backport, size/sm

#22600 [v12] Add SAML IdP service providers to default allow rules.
  lib/services/presets.go
Labels: backport, size/sm

#22443 [v11] Make curl fail on server error when downloading binaries in buildbox (#22380)
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
Labels: backport, size/sm

#22599 Release 12.0.5
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#22554 [v11] Use developer-friendly and precise technical language in docs
  docs/pages/index.mdx
Labels: documentation, backport, size/sm

#22577 Add SAML IdP service providers to default allow rules.
  lib/services/presets.go
Labels: size/sm, backport/branch/v12

#22579 SCP - Change file attrs only when requested
  lib/sshutils/scp/scp.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22552 [v12] fix typo in image (#22138)
  docs/img/architecture/x509-cert@2x.svg
Labels: documentation, backport, backport/branch/v10, backport/branch/v11, size/sm

#22145 Docs: test keyword frontmatter
  docs/pages/reference/config.mdx
Labels: documentation, size/sm

#22542 [v12] bump cloud version
  docs/config.json
Labels: documentation, backport, backport/branch/v10, backport/branch/v11, size/sm

#22607 Flaky tests detector tweaks
  .github/workflows/flaky-tests.yaml
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22606 Examples spell fixes and discord helm example fix
  examples/aws/terraform/ha-autoscale-cluster/auth_network.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/node_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/node_network.tf
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/gke-auth/get-kubeconfig.sh
  examples/load-tests/node-agent/values.yaml
  examples/resources/plugins/teleport-discord-helm.yaml
Labels: helm, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22605 Resolve dependabot CVE issues
  .prettierrc
  package.json
  web/packages/build/package.json
  web/packages/design/src/StepSlider/StepSlider.tsx
  web/packages/design/src/index.ts
  web/packages/shared/components/FileTransfer/FileTransferContextProvider.tsx
  web/packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterConnect.tsx
  web/packages/teleterm/src/ui/Documents/workspaceContext.tsx
  web/packages/teleterm/src/ui/TopBar/Clusters/Clusters.tsx
  web/packages/teleterm/src/ui/components/KeyboardArrowsNavigation/KeyboardArrowsNavigation.tsx
  yarn.lock
Labels: security, ui, dependencies, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22284 Update access request enterprise description
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22414 SAML identity provider docs.
  docs/config.json
  docs/img/access-controls/saml-idp/samltestid-0-successful-upload.png
  docs/img/access-controls/saml-idp/samltestid-1-test-idp.png
  docs/img/access-controls/saml-idp/samltestid-2-successful-login.png
  docs/pages/access-controls/idps.mdx
  docs/pages/access-controls/idps/saml-grafana.mdx
  docs/pages/access-controls/idps/saml-guide.mdx
  docs/pages/access-controls/idps/saml-reference.mdx
  docs/pages/includes/config-reference/proxy-service.yaml
  docs/pages/includes/role-spec.mdx
Labels: documentation, size/md, backport/branch/v12

#22619 [v11] Examples spell fixes and discord helm example fix
  examples/aws/terraform/ha-autoscale-cluster/auth_network.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/node_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/node_network.tf
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/gke-auth/get-kubeconfig.sh
  examples/resources/plugins/teleport-discord-helm.yaml
Labels: helm, backport, size/sm

#22568 temporarily disable TestHSMDualAuthRotation
  integration/hsm/hsm_test.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22174 Machine ID Agent Anonymous Analytics
  gen/proto/go/prehog/v1alpha/tbot.pb.go
  gen/proto/go/prehog/v1alpha/v1alphaconnect/tbot.connect.go
  gen/proto/js/prehog/v1alpha/tbot_grpc_pb.d.ts
  gen/proto/js/prehog/v1alpha/tbot_grpc_pb.js
  gen/proto/js/prehog/v1alpha/tbot_pb.d.ts
  gen/proto/js/prehog/v1alpha/tbot_pb.js
  proto/prehog/v1alpha/tbot.proto
  tool/tbot/anonymous_telemetry.go
  tool/tbot/anonymous_telemetry_test.go
  tool/tbot/main.go
Labels: machine-id, size/md, backport/branch/v12

#22070 refactor: audit interface
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/complete.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/filelog.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/test/suite.go
  lib/events/writer.go
  lib/service/service.go
  lib/service/service_test.go
  lib/sshutils/scp/http.go
  lib/sshutils/scp/scp.go
Labels: audit-log, size/sm

#22541 Machine ID telemetry docs
  docs/config.json
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/circleci.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/github-actions-kubernetes.mdx
  docs/pages/machine-id/guides/github-actions.mdx
  docs/pages/machine-id/guides/host-certificate.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  docs/pages/machine-id/reference.mdx
  docs/pages/machine-id/reference/telemetry.mdx
Labels: documentation, size/md, backport/branch/v12

#22657 Fix broken Teleterm stories
  web/.storybook/preview.js
Labels: ui, size/sm, backport/branch/v12

#22617 [v12] Examples spell fixes and discord helm example fix
  examples/aws/terraform/ha-autoscale-cluster/auth_network.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/node_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/node_network.tf
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-kube-agent/README.md
  examples/gke-auth/get-kubeconfig.sh
  examples/resources/plugins/teleport-discord-helm.yaml
Labels: helm, size/sm

#22665 [v12] Fix broken Teleterm stories
  web/.storybook/preview.js
Labels: ui, backport, size/sm

#22610 [v11] SCP - Change file attrs only when requested
  lib/sshutils/scp/scp.go
Labels: backport, size/sm

#22609 [v12] SCP - Change file attrs only when requested
  lib/sshutils/scp/scp.go
Labels: backport, size/sm

#22656 Add MaxRetryPeriod for cachePolicy config to use in tests
  integration/integration_test.go
  lib/service/cfg.go
  lib/service/service.go
Labels: size/sm

#22589 Improve tctl auth export docs/help
  docs/pages/reference/cli.mdx
  tool/tctl/common/auth_command.go
Labels: documentation, tctl, size/sm, backport/branch/v12

#22660 [v12] Machine ID telemetry docs (#22541)
  docs/config.json
  docs/pages/machine-id/getting-started.mdx
  docs/pages/machine-id/guides/applications.mdx
  docs/pages/machine-id/guides/circleci.mdx
  docs/pages/machine-id/guides/databases.mdx
  docs/pages/machine-id/guides/github-actions-kubernetes.mdx
  docs/pages/machine-id/guides/github-actions.mdx
  docs/pages/machine-id/guides/host-certificate.mdx
  docs/pages/machine-id/guides/jenkins.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  docs/pages/machine-id/reference.mdx
  docs/pages/machine-id/reference/telemetry.mdx
Labels: documentation, backport, size/md

#22628 Update node listing troubleshooting
  docs/pages/includes/node-logins.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22666 [v12] Docs: test keyword frontmatter
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm

#22615 Make it easier to create registered openssh nodes with 'tctl'
  api/go.mod
  api/go.sum
  api/types/constants.go
  api/types/server.go
  api/types/server_test.go
  lib/services/suite/suite.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  tool/tctl/common/resource_command.go
Labels: tctl, server-access, size/sm, backport/branch/v12

#22658 [v12] Machine ID Agent Anonymous Analytics
  gen/proto/go/prehog/v1alpha/tbot.pb.go
  gen/proto/go/prehog/v1alpha/v1alphaconnect/tbot.connect.go
  gen/proto/js/prehog/v1alpha/tbot_grpc_pb.d.ts
  gen/proto/js/prehog/v1alpha/tbot_grpc_pb.js
  gen/proto/js/prehog/v1alpha/tbot_pb.d.ts
  gen/proto/js/prehog/v1alpha/tbot_pb.js
  proto/prehog/v1alpha/tbot.proto
  tool/tbot/anonymous_telemetry.go
  tool/tbot/anonymous_telemetry_test.go
  tool/tbot/main.go
Labels: backport, machine-id, size/md

#22621 [v12] Update access request enterprise description
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
Labels: documentation, helm, backport, size/sm

#22622 [v11] Update enterprise access request description
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
Labels: documentation, backport, size/sm

#21212 [Web] Fix box for roles not growing to match user roles
  web/packages/shared/components/FormPassword/__snapshots__/FormPassword.test.tsx.snap
  web/packages/shared/components/Select/Select.tsx
  web/packages/teleport/src/Account/ManageDevices/AddDevice/__snapshots__/AddDevice.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
  web/packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
  web/packages/teleport/src/components/ReAuthenticate/__snapshots__/ReAuthenticate.story.test.tsx.snap
Labels: ui, size/sm

#22678 [v12] Update node listing troubleshooting
  docs/pages/includes/node-logins.mdx
Labels: documentation, backport, size/sm

#22682 [v12] temporarily disable TestHSMDualAuthRotation
  integration/hsm/hsm_test.go
Labels: backport, size/sm

#22692 [12] Add MaxRetryPeriod for cachePolicy config to use in tests
  integration/integration_test.go
  lib/service/cfg.go
  lib/service/service.go
Labels: backport, size/sm

#22683 [v11] temporarily disable TestHSMDualAuthRotation
  integration/hsm/hsm_test.go
Labels: backport, size/sm

#22679 [v11] Update node listing troubleshooting
  docs/pages/includes/node-logins.mdx
Labels: documentation, backport, size/sm

#22694 Release 12.1.0
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#22690 Fix flaky test detetion for updater
  Makefile
  integrations/kube-agent-updater/version.go
  version.mk
Labels: size/sm

#22071 Remove GetSessionEvents from external loggers
  integration/integration_test.go
  lib/auth/apiserver.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/client/api.go
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/discard.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/filelog.go
  lib/events/firestoreevents/firestoreevents.go
  lib/events/multilog.go
  lib/events/test/suite.go
  lib/events/writer.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/terminal.go
Labels: audit-log, size/sm

#22572 Allow node to handle old and new way of client IP propagation on the same listener
  api/constants/constants.go
  api/observability/tracing/ssh/ssh.go
  api/utils/sshutils/ssh.go
  integration/integration_test.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/multiplexer/proxyline.go
  lib/multiplexer/proxyline_test.go
  lib/reversetunnel/emit_conn.go
  lib/service/service.go
  lib/srv/regular/proxy.go
  lib/srv/regular/sshserver.go
  lib/sshutils/server.go
  lib/sshutils/server_test.go
Labels: networking, size/md, backport/branch/v12

#22538 Connect: Generate json schema for app config
  web/packages/teleterm/package.json
  web/packages/teleterm/src/main.ts
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/services/config/configService.test.ts
  web/packages/teleterm/src/services/config/configService.ts
  web/packages/teleterm/src/services/config/configStore.test.ts
  web/packages/teleterm/src/services/config/configStore.ts
  web/packages/teleterm/src/services/config/index.ts
  web/packages/teleterm/src/services/config/keyboardShortcutSchema.test.ts
  web/packages/teleterm/src/services/config/keyboardShortcutSchema.ts
  web/packages/teleterm/src/services/fileStorage/fileStorage.ts
  web/packages/teleterm/src/services/fileStorage/fileStorageClient.ts
  web/packages/teleterm/src/services/fileStorage/fixtures/mocks.ts
  yarn.lock
Labels: ui, size/md, backport/branch/v12

#22681 [v12] Improve tctl auth export docs/help
  docs/pages/reference/cli.mdx
  tool/tctl/common/auth_command.go
Labels: documentation, tctl, backport, size/sm

#22585 [v12] NodeJoin Script: clear yum repo cache
  lib/web/scripts/node-join/install.sh
Labels: backport, size/sm

#22668 The SAML IdP CA will be handled during auth.Init.
  lib/auth/init.go
  lib/auth/init_test.go
Labels: size/sm, backport/branch/v12

#22352 Refactor cache collections.
  lib/cache/collections.go
Labels: size/sm

#22684 [v10] temporarily disable TestHSMDualAuthRotation
  integration/hsm/hsm_test.go
Labels: backport, size/sm

#22718 [auto] Update AMI IDs for 12.1.0
  assets/aws/Makefile
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated, size/sm

#22464 Use the teleport-ent package on enterprise clusters in the discovery installer
  api/types/installers/agentless-installer.sh.tmpl
  api/types/installers/installer.sh.tmpl
  api/types/installers/installers.go
  lib/web/apiserver.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22553 Headless Login: add backend
  api/types/headlessauthn.go
  lib/services/headlessauthn.go
  lib/services/local/headlessauthn.go
  lib/services/local/headlessauthn_test.go
Labels: size/md

#22676 Swap out `select` for `poll`
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22712 Docs: Fix AWS Terraform Snippets
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22724 Docs: Provide macOS-compatible grep command.
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22271 [v12] Reorganize the config reference
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/desktop-access/reference/configuration.mdx
  docs/pages/includes/config-reference/app-service.yaml
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/config-reference/desktop-config.yaml
  docs/pages/includes/config-reference/instance-wide.yaml
  docs/pages/includes/config-reference/kubernetes-config.yaml
  docs/pages/includes/config-reference/proxy-service.yaml
  docs/pages/includes/config-reference/ssh-service.yaml
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm

#19641 Improve error messages for tsh login connectivity and ssh port
  lib/client/api.go
  tool/tsh/tsh.go
Labels: ux, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#21689 update rfd/0090-db-mfa-sessions
  rfd/0090-db-mfa-sessions.md
Labels: rfd, size/sm

#22735 Docs: Fix leave session command
  docs/pages/access-controls/guides/moderated-sessions.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22716 Don't allow different tcp version IP addresses in signed PROXY headers
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
Labels: size/sm

#22586 Always return unauthorized if the user doesn't have access to the cert.
  lib/auth/auth_with_roles.go
  lib/auth/tls_test.go
Labels: size/sm, backport/branch/v12

#22736 [docs] Add documentation for static and dynamic ui_config
  docs/pages/includes/config-reference/proxy-service.yaml
  docs/pages/includes/ui-config-spec.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport-required, size/sm, backport/branch/v12

#22746 Loop for `poll`
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#22763 [v12] Improve error messages for tsh login connectivity and ssh port
  lib/client/api.go
  tool/tsh/tsh.go
Labels: tsh, backport, size/sm

#22764 [v11] Improve error messages for tsh login connectivity and ssh port
  lib/client/api.go
  tool/tsh/tsh.go
Labels: tsh, backport, size/sm

#22721 [v12] The SAML IdP CA will be handled during auth.Init.
  lib/auth/init.go
  lib/auth/init_test.go
Labels: backport, size/sm
