Repository gravitational/teleport, pull requests merged in 2023-01, with the labels that each got.

#19762 Turn on allowing no db CLI for db proxy
  tool/tsh/proxy.go
Labels: tsh, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19771 [v11] Turn on allowing no db CLI for tsh proxy db
  tool/tsh/proxy.go
Labels: tsh, backport, size/sm

#19773 [v9] Turn on allowing no db CLI for tsh proxy db
  tool/tsh/proxy.go
Labels: tsh, backport, size/sm

#19757 Fix Azure hosted CA download error
  lib/srv/db/ca.go
  lib/srv/db/ca_test.go
Labels: database-access, size/sm

#19565 Add ListReleases and GetLicense endpoints
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/types.pb.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/release/release.go
  lib/release/release_test.go
  lib/utils/utils.go
  lib/utils/utils_test.go
Labels: backport/branch/v11, size/md

#19626 Add an access request watcher.
  api/types/access_request.go
  lib/services/access_request.go
  lib/services/watcher.go
  lib/services/watcher_test.go
Labels: size/md

#19763 [v11] backport #19695 and #19732
  go.mod
  go.sum
  integration/kube_integration_test.go
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/moderated_sessions_test.go
  lib/kube/proxy/remotecommand.go
  lib/kube/proxy/sess.go
  lib/kube/proxy/streamproto/proto.go
  lib/kube/proxy/watcher.go
  lib/kube/proxy/websocket_client_test.go
  tool/tsh/kube.go
Labels: kubernetes-access, tsh, backport, size/md

#19659 Enable Authorizer-based device authorization
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/helpers.go
  lib/auth/permissions.go
  lib/auth/permissions_test.go
  lib/auth/sessions.go
  lib/kube/proxy/utils_test.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/srv/app/server_test.go
  lib/srv/db/access_test.go
  lib/web/apiserver_test.go
Labels: kubernetes-access, application-access, database-access, size/md

#17964 Fix issue where gcp.credentialSecretName isn't needed
  examples/chart/teleport-cluster/.lint/gcp-ha-workload.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/deployment_test.yaml
  examples/chart/teleport-cluster/values.schema.json
Labels: helm, c-ay

#19466 [Connect] Add SuggestedReviewers and RequestableRoles to LoggedInUser
  lib/teleterm/api/proto/v1/cluster.proto
  lib/teleterm/api/protogen/golang/v1/cluster.pb.go
  lib/teleterm/api/protogen/js/v1/cluster_pb.d.ts
  lib/teleterm/api/protogen/js/v1/cluster_pb.js
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/daemon/daemon.go
Labels: size/sm

#19796 Fix listing all nodes in tsh
  tool/tsh/db.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: bug, tsh, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19710 [v11] docs: correct script path (#19607)
  docs/pages/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport, backport/branch/v10, size/sm

#19800 Initialize fanout before creating watcher
  lib/services/watcher.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19784 Moves GHA docker invocation from action to Makefile
  build.assets/Makefile
Labels: size/sm

#19769 [v10] Update Rust to 1.66.0 (#19605) (#19643)
  build.assets/Makefile
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
Labels: rdp, backport, desktop-access, size/sm

#19770 [v9] Update Rust to 1.66.0 (#19605) (#19643)
  build.assets/Makefile
  lib/datalog/roletester/src/role_tester.rs
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
Labels: rdp, backport, desktop-access, size/sm

#19658 [v11] Add t.Parallel() to tsh tests
  tool/tsh/aliases_test.go
  tool/tsh/app_test.go
  tool/tsh/config_test.go
  tool/tsh/kube_test.go
  tool/tsh/options_test.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh_test.go
  tool/tsh/tshconfig_test.go
Labels: tsh, backport, size/sm

#19804 Backport #17964 to branch/v10
  examples/chart/teleport-cluster/.lint/gcp-ha-workload.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/deployment_test.yaml
  examples/chart/teleport-cluster/values.schema.json
Labels: helm, backport, size/sm

#19797 chore: Bump libcbor from v0.9.0 to v0.10.1
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
Labels: backport/branch/v10, backport/branch/v11, size/sm

#19821 [v11] Fix listing all nodes in tsh
  tool/tsh/db.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm

#19809 Backport #17964 to branch/v9
  examples/chart/teleport-cluster/.lint/gcp-ha-workload.yaml
  examples/chart/teleport-cluster/templates/deployment.yaml
  examples/chart/teleport-cluster/values.schema.json
Labels: helm

#19750 Correctly marshal role options to string
  api/types/role.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19816 [DOCS] Reverse suggested install tool for RHEL
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19841 [v9] [DOCS] Reverse suggested install tool for RHEL
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport, size/sm

#19839 [v11] [DOCS] Reverse suggested install tool for RHEL
  docs/pages/includes/install-linux.mdx
Labels: documentation, backport, size/sm

#19843 Fix flaky tsh test 'TestList'
  tool/tsh/proxy_test.go
Labels: tsh, flaky tests, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19802 Remove unused yaml tags
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
Labels: size/sm

#19848 [v9] Fix flaky tsh test 'TestList'
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#19850 [v11] Fix flaky tsh test 'TestList'
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#19593 Add rate limiting to unauthenticated routes
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19579 Switch golang.org/x/crypto to gravitational fork
  .github/dependabot.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  lib/config/openssh/openssh.go
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_multiple_clusters.golden
  lib/config/openssh/testdata/TestSSHConfig_GetSSHConfig/modern_OpenSSH_-_single_cluster.golden
  lib/tbot/config/testdata/TestTemplateSSHClient_Render/latest_OpenSSH/ssh_config.golden
  tool/tsh/config_test.go
Labels: tsh, machine-id, size/sm

#19836 Remove versions from URL paths in docs links
  CHANGELOG.md
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19851 [v11] Update doc reference
  docs/pages/includes/database-access/database-config.yaml
Labels: documentation, backport, size/sm

#19849 [v10] Fix flaky tsh test 'TestList'
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#19748 docs: document tctl edit command
  docs/pages/reference/cli.mdx
Labels: documentation, size/sm

#19874 [v9] Remove versions from URL paths in docs links
  CHANGELOG.md
Labels: backport, size/sm

#19873 [v10] Remove versions from URL paths in docs links
  CHANGELOG.md
Labels: backport, size/sm

#19855 Fix unknown status type `ACTIVE` for Redshift Serverless Endpoint
  lib/services/database.go
Labels: aws, database-access, size/sm

#19872 [v11] Remove versions from URL paths in docs links
  CHANGELOG.md
Labels: backport, size/sm

#19744 Update etcd backend docs to include recommendations
  docs/pages/reference/backends.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19852 [v10] Correctly marshal role options to string
  api/types/role.go
Labels: backport, size/sm

#19878 Fixes `TestModeratedSessions` flaky test
  lib/kube/proxy/utils_test.go
Labels: kubernetes-access, backport/branch/v10, backport/branch/v11, size/sm

#19883 Bump cloud version to 11.1.4
  docs/config.json
Labels: documentation, backport/branch/v11, size/sm

#19888 [v9] Update etcd backend docs to include recommendations
  docs/pages/setup/reference/backends.mdx
Labels: documentation, backport, size/sm

#19753 [v11] misc backports
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  lib/events/playback.go
Labels: documentation, audit-log, backport, backport/branch/v9, backport/branch/v10, size/sm

#19889 Include `active_requests` in Kube Proxy credential cache key
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport/branch/v10, backport/branch/v11, size/sm

#19853 [v11] Correctly marshal role options to string
  api/types/role.go
Labels: backport, size/sm

#19892 Update webapi/sessions route
  integration/appaccess/appaccess_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport/branch/v10, backport/branch/v11, size/sm

#19882 [v10] chore: Bump libcbor, libfido2 and OpenSSL
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libfido2-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libfido2-static.pc
Labels: backport, size/sm

#19846 [v11] [Connect] Add SuggestedReviewers and RequestableRoles to LoggedInUser
  lib/teleterm/api/proto/v1/cluster.proto
  lib/teleterm/api/protogen/golang/v1/cluster.pb.go
  lib/teleterm/api/protogen/js/v1/cluster_pb.d.ts
  lib/teleterm/api/protogen/js/v1/cluster_pb.js
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/daemon/daemon.go
Labels: backport, size/sm

#19824 [Discover] Database related tweaks
  api/types/database.go
  lib/web/apiserver_test.go
  lib/web/servers.go
  lib/web/ui/server.go
Labels: backport/branch/v11, size/sm

#19910 [v11] Remove watcher for DatabaseService for RemoteProxy
  lib/cache/cache.go
Labels: backport, size/sm

#19893 Add 1/4/23 upcoming releases update
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#19912 [v11] Include `active_requests` in Kube Proxy credential cache key
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport, size/sm

#19775 Update documentation for GitHub joining to use actions
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport/branch/v11, size/sm

#19837 Update azuread federation data xml warning
  docs/pages/access-controls/sso/azuread.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19879 [v11] chore: Bump libcbor and OpenSSL
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
Labels: backport, size/sm

#19923 Enable device authorization for k8s access
  lib/service/kubernetes.go
  lib/service/service.go
Labels: size/sm

#19890 [v10] Fixes `TestModeratedSessions` flaky test
  lib/kube/proxy/utils_test.go
Labels: kubernetes-access, backport, size/sm

#19553 Add redirects to the new Audit Events section
  docs/config.json
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19926 [v11] Update documentation for GitHub joining to use actions
  docs/pages/machine-id/guides/github-actions.mdx
Labels: documentation, backport, size/sm

#19930 Fix panic when printing ascii table while running in debugger
  lib/asciitable/table.go
Labels: backport/branch/v10, backport/branch/v11, size/sm

#18717 docs: add overview of session recording
  docs/config.json
  docs/pages/architecture/session-recording.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/md

#19908 [v10] misc backports
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/server-access/guides/ssh-pam.mdx
  lib/events/playback.go
Labels: documentation, audit-log, backport, size/sm

#19891 [v11] Fixes `TestModeratedSessions` flaky test
  lib/kube/proxy/utils_test.go
Labels: kubernetes-access, backport, size/sm

#19808 [v9] backport #17870, #18021, #18286, part of #18299, and #19340
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/auth/desktop.go
  lib/auth/windows/certificate_authority.go
  lib/auth/windows/ldap.go
  lib/auth/windows/objectsid.go
  lib/auth/windows/windows.go
  lib/auth/windows/windows_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/desktop.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/ldap.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
Labels: documentation, rdp, backport, desktop-access, size/md

#19420 Client store generalization
  api/identityfile/identityfile.go
  api/identityfile/identityfile_test.go
  api/profile/profile.go
  api/utils/keypaths/keypaths.go
  api/utils/slices.go
  api/utils/slices_test.go
  api/utils/sshutils/ssh.go
  api/utils/sshutils/ssh_test.go
  fixtures/certs/identities/key-cert-ca.pem
  integration/helpers/helpers.go
  integration/helpers/kube.go
  integration/proxy/teleterm_test.go
  lib/auth/methods.go
  lib/auth/testauthority/testauthority.go
  lib/benchmark/benchmark.go
  lib/client/api.go
  lib/client/ca_export.go
  lib/client/client_store.go
  lib/client/client_store_test.go
  lib/client/conntest/ssh.go
  lib/client/db/database_certificates.go
  lib/client/identityfile/identity.go
  lib/client/identityfile/identity_test.go
  lib/client/interfaces.go
  lib/client/keyagent.go
  lib/client/keyagent_test.go
  lib/client/keystore.go
  lib/client/keystore_test.go
  lib/client/local_proxy_middleware.go
  lib/client/profile.go
  lib/client/profile_test.go
  lib/client/trusted_certs_store.go
  lib/client/trusted_certs_store_test.go
  lib/kube/kubeconfig/kubeconfig_test.go
  lib/sshutils/marshal.go
  lib/sshutils/marshal_test.go
  lib/tbot/config/configtemplate.go
  lib/tbot/config/configtemplate_ssh_host_cert.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/storage.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/tctl.go
  tool/tsh/app.go
  tool/tsh/aws.go
  tool/tsh/azure.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: kubernetes-access, tsh, tctl, machine-id, size/lg

#19917 [v11] [Discover] Database related tweaks
  api/types/database.go
  lib/web/apiserver_test.go
  lib/web/servers.go
  lib/web/ui/server.go
Labels: backport, size/sm

#19932 [v11] Fix panic when printing ascii table while running in debugger
  lib/asciitable/table.go
Labels: backport, size/sm

#19918 Fix connections to desktops in leaf clusters where w_d_s is connected via reverse tunnel
  lib/web/desktop.go
Labels: desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19913 [v10] Include `active_requests` in Kube Proxy credential cache key
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
Labels: kubernetes-access, backport, size/sm

#19603 [v11] Reorganize early-stage docs sections
  docs/config.json
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/api/getting-started.mdx
  docs/pages/application-access/getting-started.mdx
  docs/pages/choose-an-edition/introduction.mdx
  docs/pages/choose-an-edition/teleport-cloud/architecture.mdx
  docs/pages/choose-an-edition/teleport-cloud/downloads.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/choose-an-edition/teleport-cloud/getting-started.mdx
  docs/pages/choose-an-edition/teleport-cloud/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/gcp-kms.mdx
  docs/pages/choose-an-edition/teleport-enterprise/getting-started.mdx
  docs/pages/choose-an-edition/teleport-enterprise/hsm.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/license.mdx
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/core-concepts.mdx
  docs/pages/deploy-a-cluster/deployments.mdx
  docs/pages/deploy-a-cluster/introduction.mdx
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/faq.mdx
  docs/pages/getting-started.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-comparison.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/user-client-prereqs.mdx
  docs/pages/index.mdx
  docs/pages/installation.mdx
  docs/pages/management/admin/self-signed-certs.mdx
  docs/pages/management/admin/troubleshooting.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/guides/joining-nodes-aws-ec2.mdx
  docs/pages/management/operations/proxy-peering.mdx
  docs/pages/server-access/guides/ansible.mdx
  docs/pages/server-access/guides/recording-proxy-mode.mdx
  docs/pages/try-out-teleport/digitalocean.mdx
  docs/pages/try-out-teleport/docker-compose.mdx
  docs/pages/try-out-teleport/introduction.mdx
  docs/pages/try-out-teleport/linux-server.mdx
Labels: documentation, backport, size/sm

#19819 [v11] Initialize fanout before creating watcher
  lib/services/watcher.go
Labels: backport, size/sm

#19869 [v11] Add rate limiting to unauthenticated routes
  integration/appaccess/appaccess_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#19944 docs: Flip sync/async in session recording reference
  docs/pages/architecture/session-recording.mdx
Labels: documentation, size/sm

#19927 [v11] Update azuread federation data xml warning
  docs/pages/access-controls/sso/azuread.mdx
Labels: documentation, backport, size/sm

#19928 [v10] Update azuread federation data xml warning
  docs/pages/access-controls/sso/azuread.mdx
Labels: documentation, backport, size/sm

#19929 [v9] Update azuread federation data xml warning
  docs/pages/enterprise/sso/azuread.mdx
Labels: documentation, backport, size/sm

#19935 [v10] docs: add overview of session recording
  docs/config.json
  docs/pages/architecture/session-recording.mdx
Labels: documentation, backport, size/md

#19737 [v11] backport #17870, #18021, #18286, part of #18299, and #19340
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/auth/desktop.go
  lib/auth/windows/certificate_authority.go
  lib/auth/windows/ldap.go
  lib/auth/windows/objectsid.go
  lib/auth/windows/windows.go
  lib/auth/windows/windows_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/desktop.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/ldap.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
  lib/web/scripts/desktop/configure-ad.ps1
Labels: documentation, rdp, backport, desktop-access, size/md

#19541 Adds `show_desktop_wallpaper` flag, disables Windows wallpaper by default
  Cargo.lock
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/desktop.go
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/windows_server.go
Labels: documentation, release-notes, rdp, desktop-access, size/sm

#19870 [v10] Add rate limiting to unauthenticated routes
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#19940 [v11] Revert DatabaseService Heartbeat
  api/client/client.go
  api/client/events.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/databaseservice.go
  api/types/resource.go
  api/types/types.pb.go
  integration/conntest/database_test.go
  integration/db/database_service_test.go
  integration/helpers/helpers.go
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/init.go
  lib/auth/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/service/service.go
  lib/services/databaseservice.go
  lib/services/databaseservice_test.go
  lib/services/local/databaseservice.go
  lib/services/local/databaseservice_test.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/services/matchers.go
  lib/services/matchers_test.go
  lib/services/presence.go
  lib/services/presets.go
  lib/services/resource.go
  lib/services/role.go
  lib/services/server.go
  lib/services/servers_test.go
  lib/services/services.go
  lib/srv/db/server.go
  lib/srv/db/server_test.go
  lib/srv/heartbeat.go
  lib/srv/heartbeat_test.go
  lib/web/apiserver.go
  lib/web/databases_test.go
  lib/web/servers.go
  lib/web/ui/server.go
  tool/tctl/common/collection.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, database-access, backport, size/sm

#19939 [Discover] Fix yaml formatting with yaml lists for db join token request
  lib/web/apiserver_test.go
  lib/web/databases.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/install_node.go
  lib/web/scripts/install_node_test.go
Labels: backport/branch/v11, size/sm

#19958 [v11] [Discover] Fix yaml formatting with yaml lists for db join token request
  lib/web/apiserver_test.go
  lib/web/databases.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/install_node.go
  lib/web/scripts/install_node_test.go
Labels: backport, size/sm

#19838 Access requests implement ResourceWithLabels.
  api/types/access_request.go
  api/types/access_request_test.go
Labels: size/sm

#19950 [v11] Add rate limiter to saml/oidc routes
  lib/web/apiserver.go
Labels: backport, size/sm

#19820 [v9] Initialize fanout before creating watcher
  lib/services/watcher.go
Labels: backport, size/sm

#19914 Minor docs fixes
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/management/admin/adding-nodes.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19969 Release 11.2.0
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#19774 Use one Buf workspace instead of three
  Makefile
  buf.work.yaml
  build.assets/genproto.sh
  lib/prehog/buf.gen.yaml
  lib/prehog/buf.work.yaml
  lib/prehog/proto/buf.yaml
  lib/teleterm/buf.gen.yaml
  lib/teleterm/buf.work.yaml
Labels: backport/branch/v10, backport/branch/v11, size/sm

#19902 Make Connect's --insecure flag easier to find in docs
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/management/admin/self-signed-certs.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm

#19414 Rename Policy related resource items to AccessPolicy
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/access_policy.go
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/predicate/access_test.go
  lib/auth/predicate/predicate.go
  lib/services/access.go
  lib/services/access_policy.go
  lib/services/local/access.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
Labels: tctl, do-not-merge, size/sm, predicate

#19990 [v11] Use one Buf workspace instead of three
  Makefile
  buf.work.yaml
  build.assets/genproto.sh
  lib/prehog/buf.gen.yaml
  lib/prehog/buf.work.yaml
  lib/prehog/proto/buf.yaml
  lib/teleterm/api/protogen/golang/v1/access_request.pb.go
  lib/teleterm/buf.gen.yaml
  lib/teleterm/buf.work.yaml
Labels: backport, size/sm

#19989 Fix version.go/gitref.go code generation mark
  api/version.go
  version.go
  version.mk
Labels: size/sm

#19993 [v10] Use one Buf workspace instead of three
  Makefile
  buf.work.yaml
  build.assets/genproto.sh
  lib/teleterm/buf.gen.yaml
  lib/teleterm/buf.work.yaml
Labels: backport, size/sm

#19972 [auto] Update AMI IDs for 11.2.0
  assets/aws/Makefile
  examples/aws/cloudformation/ent.yaml
  examples/aws/cloudformation/oss.yaml
  examples/aws/terraform/AMIS.md
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/starter-cluster/README.md
Labels: terraform, automated, size/sm

#19999 Fix Machine ID Certificate TTL on IAM join
  lib/auth/register.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19903 Add Connect docs about linking tsh
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport/branch/v11, size/sm

#19991 [v11] Make Connect's --insecure flag easier to find in docs
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/management/admin/self-signed-certs.mdx
Labels: documentation, backport, size/sm

#20001 [v11] Fix Machine ID Certificate TTL on IAM join
  lib/auth/register.go
Labels: backport, size/sm

#20000 [v10] Fix Machine ID Certificate TTL on IAM join
  lib/auth/register.go
Labels: backport, size/sm

#20002 [v9] Fix Machine ID Certificate TTL on IAM join
  lib/auth/register.go
Labels: backport, size/sm

#19936 Fix bot IAM joining
  lib/auth/join_iam.go
Labels: backport/branch/v11, size/sm, c-uh

#19801 [v10] backport #17870, #18021, #18286, part of #18299, and #19340
  docs/pages/desktop-access/manual-setup.mdx
  docs/pages/includes/desktop-access/desktop-config.yaml
  lib/auth/desktop.go
  lib/auth/windows/certificate_authority.go
  lib/auth/windows/ldap.go
  lib/auth/windows/objectsid.go
  lib/auth/windows/windows.go
  lib/auth/windows/windows_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/cfg.go
  lib/service/desktop.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/ldap.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
  lib/web/scripts/desktop/configure-ad.ps1
Labels: documentation, rdp, backport, desktop-access, size/md

#19970 Add `is_flexi_server` to database Azure proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: size/sm

#19971 docs: update version to 11.2.0
  docs/config.json
Labels: documentation, backport, size/sm

#20008 Optimize types.CertAuthority comparison
  lib/services/authority.go
  lib/services/authority_test.go
Labels: size/sm

#20005 Change "name" to "sAMAccountName"
  lib/auth/windows/ldap.go
  lib/srv/desktop/windows_server.go
Labels: desktop-access, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#20011 [v11] Fix bot IAM joining
  lib/auth/join_iam.go
Labels: backport, size/sm

#19931 [v10] Fix panic when printing ascii table while running in debugger
  lib/asciitable/table.go
Labels: backport, size/sm

#20022 [v11] Change "name" to "sAMAccountName"
  lib/auth/windows/ldap.go
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/sm

#19966 Skip device authentication based on Ping
  api/client/webclient/webclient.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/export_test.go
  lib/web/apiserver.go
  lib/web/apiserver_ping_test.go
Labels: size/md

#20027 Unbundle and unhack TestAppInvalidateAppSessionsOnLogout
  integration/appaccess/appaccess_test.go
Labels: size/sm

#20021 [v9] Change "name" to "sAMAccountName"
  lib/auth/windows/ldap.go
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/sm

#20023 [v10] Change "name" to "sAMAccountName"
  lib/auth/windows/ldap.go
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/sm

#19996 Periodically reload proxy certificates
  docs/pages/reference/config.mdx
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/certreloader.go
  lib/service/certreloader_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/md

#19277 Add hidden cli command: wait-no-resolve
  constants.go
  tool/teleport/common/teleport.go
  tool/teleport/common/wait.go
Labels: size/md

#20037 [v11] Unbundle TestAppInvalidateAppSessionsOnLogout
  integration/appaccess/appaccess_test.go
Labels: backport, size/sm

#19898 [v9] BUGFIX | Teleport ALPN Proxy doesn't respect HTTP CONNECT Proxy
  lib/srv/alpnproxy/local_proxy.go
Labels: backport, size/sm

#19564 Report Connect usage events
  Makefile
  lib/prehog/buf-teleterm.gen.yaml
  lib/prehog/gen-js/prehog/v1alpha/connect_grpc_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/connect_grpc_pb.js
  lib/prehog/gen-js/prehog/v1alpha/connect_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/connect_pb.js
  lib/prehog/gen-js/prehog/v1alpha/teleport_grpc_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/teleport_grpc_pb.js
  lib/prehog/gen-js/prehog/v1alpha/teleport_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/teleport_pb.js
  lib/prehog/gen/prehog/v1alpha/connect.pb.go
  lib/prehog/gen/prehog/v1alpha/prehogv1alphaconnect/connect.connect.go
  lib/prehog/proto/prehog/v1alpha/connect.proto
  lib/prehog/proto/prehog/v1alpha/teleport.proto
  lib/teleterm/api/proto/v1/service.proto
  lib/teleterm/api/proto/v1/usage_events.proto
  lib/teleterm/api/protogen/golang/v1/service.pb.go
  lib/teleterm/api/protogen/golang/v1/service_grpc.pb.go
  lib/teleterm/api/protogen/golang/v1/usage_events.pb.go
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/service_pb.d.ts
  lib/teleterm/api/protogen/js/v1/service_pb.js
  lib/teleterm/api/protogen/js/v1/usage_events_grpc_pb.d.ts
  lib/teleterm/api/protogen/js/v1/usage_events_grpc_pb.js
  lib/teleterm/api/protogen/js/v1/usage_events_pb.d.ts
  lib/teleterm/api/protogen/js/v1/usage_events_pb.js
  lib/teleterm/apiserver/handler/handler_usage_events.go
  lib/teleterm/config.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/usagereporter.go
  lib/teleterm/teleterm.go
  lib/teleterm/teleterm_test.go
  tool/tsh/daemon.go
  tool/tsh/tsh.go
Labels: size/md

#20033 [v11] Remove RW on `license` and `download` from preset editor role (#19997)
  lib/services/presets.go
Labels: backport, size/sm

#19713 capture additional prehog events
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  lib/prehog/gen/prehog/v1alpha/prehogv1alphaconnect/teleport.connect.go
  lib/prehog/gen/prehog/v1alpha/teleport.pb.go
  lib/prehog/proto/prehog/v1alpha/teleport.proto
  lib/services/usagereporter.go
  lib/web/userevent.go
Labels: size/sm

#20041 [v10] Periodically reload proxy certificates
  docs/pages/reference/config.mdx
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/certreloader.go
  lib/service/certreloader_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
Labels: documentation, backport, size/md

#19649 AWS Athena ODBC driver support for App Access
  lib/utils/aws/signing.go
  tool/tsh/app.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: feature-request, tsh, aws, application-access, size/sm

#20040 [v11] Periodically reload proxy certificates
  docs/pages/reference/config.mdx
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/certreloader.go
  lib/service/certreloader_test.go
  lib/service/cfg.go
  lib/service/service.go
  lib/service/service_test.go
Labels: documentation, backport, size/md

#20012 [v10] Minor docs fixes (#19914)
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/management/admin/adding-nodes.mdx
Labels: documentation, backport, size/sm

#20007 [v9] Minor docs fixes
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/setup/admin/adding-nodes.mdx
Labels: documentation, backport, size/sm

#20003 Pass context to reverse tunnel server
  lib/reversetunnel/api.go
  lib/reversetunnel/srv.go
  lib/service/service.go
Labels: size/sm

#20049 Fix CertificateInvalidError in formatCertError
  lib/utils/cli.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19967 Fix RFD link in the Directory Sharing guide
  docs/pages/desktop-access/directory-sharing.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm

#20062 [v11] Fix RFD link in the Directory Sharing guide
  docs/pages/desktop-access/directory-sharing.mdx
Labels: documentation, backport, size/sm

#20061 [v10] Fix RFD link in the Directory Sharing guide
  docs/pages/desktop-access/directory-sharing.mdx
Labels: documentation, backport, size/sm

#19766 Set extra proxy headers in all `tsh` HTTP requests
  api/client/proxy/proxy.go
  api/client/proxy/proxy_test.go
  api/client/webclient/webclient.go
  lib/client/api.go
  lib/client/https_client.go
  lib/client/https_client_test.go
  lib/client/redirect.go
  lib/client/weblogin.go
  lib/client/weblogin_test.go
Labels: backport/branch/v9, backport/branch/v10, backport/branch/v11

#19785 GCP CLI support: API changes
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/app.go
  api/types/events/events.pb.go
  api/types/session.go
  api/types/types.pb.go
Labels: size/sm

#19978 Update MongoDB Atlas config example
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport/branch/v9, backport/branch/v10, backport/branch/v11, size/sm

#19787 GCP CLI support: CA changes
  lib/tlsca/ca.go
  lib/tlsca/ca_test.go
Labels: size/sm

#19788 GCP CLI support: auth changes
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
Labels: size/sm

#18274 RFD 0096: Helm chart revamp
  rfd/0096-helm-chart-revamp.md
Labels: rfd

#19790 GCP CLI support: `tsh` and `tctl` changes
  api/client/client.go
  lib/client/profile.go
  lib/srv/alpnproxy/auth_checker_middleware.go
  lib/srv/alpnproxy/auth_checker_middleware_test.go
  lib/srv/alpnproxy/forward_proxy.go
  lib/srv/alpnproxy/forward_proxy_test.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
  tool/tsh/app.go
  tool/tsh/app_test.go
  tool/tsh/gcp.go
  tool/tsh/gcp_test.go
  tool/tsh/proxy.go
  tool/tsh/tsh.go
Labels: tsh, tctl, size/lg

#20070 Changes from `make grpc` and `make grpc-teleterm` missing from master
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  lib/prehog/gen-js/prehog/v1alpha/teleport_grpc_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/teleport_grpc_pb.js
  lib/prehog/gen-js/prehog/v1alpha/teleport_pb.d.ts
  lib/prehog/gen-js/prehog/v1alpha/teleport_pb.js
  lib/prehog/gen/prehog/v1alpha/teleport.pb.go
Labels: size/sm

#20093 [v11] revert docs plugin version
  docs/config.json
Labels: documentation, backport, size/sm

#20092 [v9] Update MongoDB Atlas config example
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#20091 [v10] Update MongoDB Atlas config example
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#20076 [v11] Update MongoDB Atlas config example
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#19764 [v10] backport #19695, #17004 and #19732
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_users.yaml
  go.mod
  go.sum
  integration/kube_integration_test.go
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/moderated_sessions_test.go
  lib/kube/proxy/remotecommand.go
  lib/kube/proxy/sess.go
  lib/kube/proxy/streamproto/proto.go
  lib/kube/proxy/websocket_client_test.go
  operator/apis/resources/v2/groupversion_info.go
  operator/apis/resources/v5/groupversion_info.go
  operator/config/crd/bases/resources.teleport.dev_roles.yaml
  operator/config/crd/bases/resources.teleport.dev_users.yaml
  operator/crdgen/Makefile
  operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  operator/crdgen/testdata/golden/resources.teleport.dev_users.yaml
  tool/tsh/kube.go
Labels: kubernetes-access, tsh, backport, size/sm

#20006 [v11] Minor docs fixes
  docs/pages/includes/desktop-access/desktop-config.yaml
  docs/pages/management/admin/adding-nodes.mdx
Labels: documentation, backport, size/sm

#20047 feat: add login rule service proto definition
  api/gen/proto/go/teleport/loginrule/v1/loginrule_service.pb.go
  api/gen/proto/go/teleport/loginrule/v1/loginrule_service_grpc.pb.go
  api/proto/teleport/loginrule/v1/loginrule_service.proto
  api/types/constants.go
Labels: backport/branch/v11, size/sm

#20014 Add device mode to RoleOptions
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service.pb.go
  api/gen/proto/go/teleport/loginrule/v1/loginrule_service_grpc.pb.go
  api/proto/teleport/devicetrust/v1/devicetrust_service.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: size/sm

#20096 helm: support dnsConfig in `teleport-kube-agent` chart
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/dnsconfig.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, backport/branch/v10, backport/branch/v11, size/sm
