Repository gravitational/teleport, pull requests merged in 2023-07, with the labels that each got.

#28111 Improve copy on the integrations page
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13

#28182 [v13] athena audit logs - add migration script
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
Labels: audit-log, backport, size/xl

#28346 Connect My Computer: check permissions before showing in the UI
  gen/proto/go/teleport/lib/teleterm/v1/cluster.pb.go
  gen/proto/js/teleport/lib/teleterm/v1/cluster_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/cluster_pb.js
  lib/teleterm/apiserver/handler/handler_clusters.go
  proto/teleport/lib/teleterm/v1/cluster.proto
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerSetup/DocumentConnectMyComputerSetup.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerSetup/DocumentConnectMyComputerSetup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenuIcon.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/index.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/permissions.test.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/permissions.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/ClusterResources.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/SideNav/SideNav.tsx
  web/packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
  web/packages/teleterm/src/ui/TopBar/ConnectMyComputer/index.ts
  web/packages/teleterm/src/ui/TopBar/TopBar.tsx
Labels: ui, size/md

#28519 dynamodbbk: don't delete non-expired items on Get
  lib/backend/dynamo/dynamodbbk.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28517 [v13] Add light & dark themes to YAML editor
  web/packages/design/src/theme/darkTheme.ts
  web/packages/design/src/theme/lightTheme.ts
  web/packages/shared/components/TextEditor/StyledTextEditor.jsx
  web/packages/shared/components/TextEditor/TextEditor.jsx
  web/packages/teleport/src/Discover/Database/ConnectAwsAccount/ConnectAwsAccount.tsx
  web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Shared/SetupAccess/AccessInfo.tsx
  web/packages/teleport/src/Discover/Shared/SetupAccess/SetupAccessWrapper.story.tsx
  web/packages/teleport/src/Discover/Shared/YAML.tsx
  web/packages/teleport/src/Discover/Shared/index.ts
Labels: ui, backport, size/md

#28598 [v11] dynamodbbk: don't delete non-expired items on Get
  lib/backend/dynamo/dynamodbbk.go
Labels: backport, size/sm

#28599 [v12] dynamodbbk: don't delete non-expired items on Get
  lib/backend/dynamo/dynamodbbk.go
Labels: backport, size/sm

#28600 [v13] dynamodbbk: don't delete non-expired items on Get
  lib/backend/dynamo/dynamodbbk.go
Labels: backport, size/sm

#28422 User groups in access requests will expand list of applications.
  lib/auth/auth.go
  lib/auth/auth_with_roles_test.go
Labels: size/md, backport/branch/v13

#28597 [v13] AWS OIDC - DeployService: configure IAM (#28088)
  go.mod
  go.sum
  lib/cloud/aws/errors.go
  lib/cloud/aws/errors_test.go
  lib/cloud/aws/policy.go
  lib/cloud/aws/policy_statements.go
  lib/cloud/aws/policy_test.go
  lib/config/configuration.go
  lib/configurators/aws/aws.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_config.go
  lib/integrations/awsoidc/deployservice_iam_config_test.go
  lib/integrations/awsoidc/tags.go
  lib/integrations/awsoidc/tags_test.go
  lib/utils/aws/aws.go
  lib/utils/aws/aws_test.go
  tool/teleport/common/teleport.go
Labels: backport, size/lg

#27893 [Assist] Provide interactive updates during agent execution
  lib/ai/chat.go
  lib/ai/chat_test.go
  lib/ai/embeddings.go
  lib/ai/model/agent.go
  lib/ai/model/messages.go
  lib/ai/model/prompt.go
  lib/ai/testutils/http.go
  lib/assist/assist.go
  lib/assist/assist_test.go
  lib/web/assistant.go
  lib/web/assistant_test.go
  lib/web/command_test.go
  web/packages/teleport/src/Assist/context/AssistContext.tsx
  web/packages/teleport/src/Assist/service.ts
  web/packages/teleport/src/Assist/types.ts
Labels: ui, size/md, assist

#28328 Posthog event for onboarding questionnaire submit
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  lib/usagereporter/teleport/types.go
  lib/usagereporter/web/userevent.go
  web/packages/teleport/src/Welcome/Questionnaire/Questionnaire.story.tsx
  web/packages/teleport/src/Welcome/Questionnaire/Questionnaire.test.tsx
  web/packages/teleport/src/Welcome/Questionnaire/Questionnaire.tsx
  web/packages/teleport/src/Welcome/Questionnaire/types.ts
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, size/sm

#28607 Remove console.log in AssistContext
  web/packages/teleport/src/Assist/context/AssistContext.tsx
Labels: ui, size/sm

#28385 Introduce the Access List object.
  api/gen/proto/go/accesslist/v1/accesslist.pb.go
  api/gen/proto/go/header/v1/metadata.pb.go
  api/gen/proto/go/header/v1/resourceheader.pb.go
  api/gen/proto/go/trait/v1/trait.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/proto/teleport/header/v1/metadata.proto
  api/proto/teleport/header/v1/resourceheader.proto
  api/proto/teleport/trait/v1/trait.proto
Labels: size/md

#28470 Add t.Parallel() to several tsh tests
  tool/tsh/common/app_azure_test.go
  tool/tsh/common/app_cloud_test.go
  tool/tsh/common/app_gcp_test.go
  tool/tsh/common/db_test.go
  tool/tsh/common/recording_export_test.go
  tool/tsh/common/tshconfig_test.go
Labels: tsh, size/sm, backport/branch/v13

#28583 [v12] Web: Improve no access message and remove hard coded color
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
Labels: ui, backport, size/sm

#28545 [v13] Web related tweaks for access request user groups
  lib/web/apiserver_test.go
  lib/web/apps.go
  web/packages/shared/components/FieldInput/__snapshots__/FieldInput.test.tsx.snap
  web/packages/shared/components/ToolTip/ToolTip.story.tsx
  web/packages/shared/components/ToolTip/ToolTip.tsx
  web/packages/teleport/src/Apps/AppList/AppList.test.tsx
  web/packages/teleport/src/services/apps/types.ts
Labels: ui, backport, size/sm

#28612 [v12] Improve copy on the integrations page
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, backport, size/sm

#28560 Athena Migration Script: Add additional migration options
  examples/dynamoathenamigration/migration.go
Labels: size/sm

#28611 [v13] Improve copy on the integrations page
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, backport, size/sm

#28550 [v13] Web: Improve no access message and remove hard coded color
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
Labels: ui, backport, size/sm

#28552 improve startup with empty db or discovery config
  lib/service/service.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, discovery

#28596 Add custom component prop type for react-select
  web/packages/shared/components/Select/types.ts
Labels: ui, size/sm, backport/branch/v13

#28617 [v13] Add custom component prop type for react-select
  web/packages/shared/components/Select/types.ts
Labels: ui, backport, size/sm

#27924 WebDiscover: Partially implement auto deploy database server view
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.story.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/index.tsx
  web/packages/teleport/src/Discover/Database/DeployService/DeployService.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/ManualDeploy.story.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/ManualDeploy.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/index.ts
  web/packages/teleport/src/Discover/Database/DeployService/index.ts
  web/packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.story.tsx
  web/packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.test.ts
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.story.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.test.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Discover/Database/common.test.ts
  web/packages/teleport/src/Discover/Database/common.tsx
  web/packages/teleport/src/Discover/Database/index.tsx
  web/packages/teleport/src/Discover/Database/util.ts
  web/packages/teleport/src/Discover/Shared/ActionButtons.tsx
  web/packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
  web/packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.ts
  web/packages/teleport/src/Discover/Shared/index.ts
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/databases/databases.test.ts
  web/packages/teleport/src/services/databases/makeDatabase.ts
  web/packages/teleport/src/services/databases/types.ts
  web/packages/teleport/src/services/integrations/integrations.ts
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, size/md, backport/branch/v13

#28619 Move database validation to gRPC methods
  lib/auth/grpcserver.go
  lib/cache/cache_test.go
  lib/services/local/databases.go
  lib/services/local/databases_test.go
Labels: backport/branch/v11, size/md, backport/branch/v12, backport/branch/v13

#28641 [v11] Move database validation to gRPC methods
  lib/auth/grpcserver.go
  lib/cache/cache_test.go
  lib/services/local/databases.go
  lib/services/local/databases_test.go
Labels: backport, size/md

#28640 [v12] Move database validation to gRPC methods
  lib/auth/grpcserver.go
  lib/cache/cache_test.go
  lib/services/local/databases.go
  lib/services/local/databases_test.go
Labels: backport, size/md

#28436 Script to configure IAM for the DeployService
  api/types/database_test.go
  api/utils/aws/identifiers.go
  api/utils/aws/identifiers_test.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/join_tokens.go
  lib/web/scripts/install_node.go
Labels: discover, size/md, backport/branch/v13

#28432 [v13] Add option to allow for host users not to be deleted
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  lib/services/access_checker.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
  lib/utils/host/hostusers.go
  lib/web/resources_test.go
  tool/tctl/sso/tester/format_test.go
Labels: documentation, tctl, backport, size/md

#28058 [Docs] Add IdP-initiated SSO instructions to Grafana SAML guide
  docs/pages/access-controls/idps/saml-grafana.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28604 docs: correct docker installation table
  docs/pages/installation.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28539 `tsh db connect` should prefer mongosh
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28466 [v13] Teleport Proxy Behind ALB support for IP Pinning
  api/client/alpn.go
  api/client/contextdialer.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/httplib/httplib.go
  lib/limiter/limiter.go
  lib/limiter/limiter_test.go
  lib/reversetunnel/transport.go
  lib/service/service.go
  lib/service/servicecfg/proxy.go
  lib/utils/conn.go
  lib/utils/conn_test.go
  lib/utils/http.go
  lib/utils/http_test.go
  lib/utils/net.go
  lib/web/addr.go
  lib/web/addr_test.go
  lib/web/apiserver.go
  lib/web/conn_upgrade_test.go
Labels: backport, tls-routing, size/md, ip-pinning

#28638 [v13] Move database validation to gRPC methods
  lib/auth/grpcserver.go
  lib/cache/cache_test.go
  lib/services/local/databases.go
  lib/services/local/databases_test.go
Labels: backport, size/md

#27933 [v11] feat: adds motd to the ui
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/Login/Login.story.tsx
  web/packages/teleport/src/Login/Login.test.tsx
  web/packages/teleport/src/Login/Login.tsx
  web/packages/teleport/src/Login/Motd/Motd.tsx
  web/packages/teleport/src/Login/Motd/index.ts
  web/packages/teleport/src/Login/useLogin.ts
  web/packages/teleport/src/config.ts
Labels: ui, backport, size/md

#28662 lib/teleterm: Remove misleading error log after LocalAgent.GetKey
  lib/teleterm/clusters/storage.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28643 [v13] Script to configure IAM for the DeployService (#28436)
  api/types/database_test.go
  api/utils/aws/identifiers.go
  api/utils/aws/identifiers_test.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/join_tokens.go
  lib/web/scripts/install_node.go
Labels: backport, size/md

#28669 [v11] `tsh db connect` should prefer mongosh
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
Labels: backport, size/sm

#28623 [v12] improve startup with empty db or discovery config
  lib/service/service.go
Labels: backport, size/sm

#28624 [v11] improve startup with empty db or discovery config
  lib/service/service.go
Labels: backport, size/sm

#24328 docs: edits to the headless webauthn guide
  docs/pages/access-controls/guides/headless.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28649 Rename `database_labels` to `db_labels`
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28682 [v13] Update agentless mode description
  docs/pages/faq.mdx
Labels: documentation, backport, size/sm

#28633 Fix Machine ID guide index and adjust FAQ
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/faq.mdx
Labels: backport/branch/v11, backport/branch/v12, backport/branch/v13

#13440 Teleport discover RFD
  rfd/0073-discover.md
Labels: rfd

#28610 [Assist] Clear the refresh websocket timeout when closing Assist
  web/packages/teleport/src/Assist/context/AssistContext.tsx
Labels: ui, size/sm

#28691 Make dependabot ignore go-tpm updates
  .github/dependabot.yml
Labels: size/sm

#28438 docs: openssh updates
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28685 [v11] Rename `database_labels` to `db_labels`
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport, size/sm

#28687 [v13] Rename `database_labels` to `db_labels`
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport, size/sm

#28686 [v12] Rename `database_labels` to `db_labels`
  docs/pages/access-controls/guides/role-templates.mdx
  docs/pages/access-controls/reference.mdx
Labels: documentation, backport, size/sm

#28700 [v13] Fix Machine ID guide index and adjust FAQ
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport, size/sm

#28701 [v12] Fix Machine ID guide index and adjust FAQ
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport, size/sm

#28696 Release 13.2.0
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm

#28603 [v13] User groups in access requests will expand list of applications.
  lib/auth/auth.go
  lib/auth/auth_with_roles_test.go
Labels: backport, size/md

#28595 Update assist docs
  docs/pages/ai-assist.mdx
Labels: documentation, size/sm, backport/branch/v13, assist

#28653 [v12] docs: correct docker installation table
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm

#28734 [v12] docs: edits to the headless webauthn guide
  docs/pages/access-controls/guides/headless.mdx
Labels: documentation, backport, size/sm

#28733 [v13] docs: edits to the headless webauthn guide
  docs/pages/access-controls/guides/headless.mdx
Labels: documentation, backport, size/sm

#28407 [v13] Connect: Add docs for theme
  docs/pages/connect-your-client/teleport-connect.mdx
  web/packages/teleterm/src/services/config/appConfigSchema.ts
Labels: documentation, ui, backport, size/sm

#28666 [v11] lib/teleterm: Remove misleading error log after LocalAgent.GetKey
  lib/teleterm/clusters/storage.go
Labels: backport, size/sm

#28665 [v12] lib/teleterm: Remove misleading error log after LocalAgent.GetKey
  lib/teleterm/clusters/storage.go
Labels: backport, size/sm

#28702 Fix theme not loading on first login & overflowing command result summary
  web/packages/teleport/src/Assist/Conversation/CommandResultEntry.tsx
  web/packages/teleport/src/Assist/Conversation/CommandResultSummaryEntry.tsx
  web/packages/teleport/src/Assist/shared/MonospacedOutput.tsx
  web/packages/teleport/src/User/UserContext.tsx
  web/packages/teleport/src/services/localStorage/localStorage.ts
  web/packages/teleport/src/services/userPreferences/types.ts
Labels: ui, size/sm, backport/branch/v13

#28479 Introduce Access List internal object.
  api/types/access_list.go
  api/types/common/common.go
  api/types/common/common_test.go
  api/types/common/constants.go
  api/types/constants.go
  api/types/header/header.go
  api/types/resource.go
  api/types/traits/traits.go
Labels: size/lg

#28524 [v13] Docs: Specify enterprise in commercial prereq cloud tab.
  docs/pages/includes/commercial-prereqs-tabs.mdx
Labels: documentation, backport, size/sm

#28663 Machine ID: GCP Delegated Joining support
  lib/auth/bot.go
  lib/auth/join.go
  lib/tbot/config/config.go
Labels: machine-id, size/sm, backport/branch/v13

#28693 [v13] Docs: Update GitLab SSO docs
  docs/cspell.json
  docs/img/sso/gitlab/gitlab-oidc-0.png
  docs/img/sso/gitlab/gitlab-oidc-1.png
  docs/img/sso/teleportauditlogssofailed.png
  docs/pages/access-controls/sso/gitlab.mdx
Labels: documentation, backport, size/sm

#28752 Fix imports on non-linting files
  integrations/operator/main.go
  lib/utils/registry/registry_windows.go
  tool/tsh/common/putty_config_windows.go
Labels: tsh, size/sm, backport/branch/v13

#28554 Use more restrictive S3 object permissions
  docs/pages/includes/s3-iam-policy.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28415 [v13] Document Jamf `exit_on_sync` toggle
  docs/pages/includes/config-reference/jamf-service.yaml
Labels: documentation, backport, size/sm

#28759 [v13] Support GCP joining when `google` claim is not present
  lib/auth/join_gcp.go
  lib/gcp/token_validator.go
  lib/gcp/token_validator_test.go
Labels: backport, size/md

#28757 [v11] Fix Machine ID guide index and adjust FAQ
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/faq.mdx
Labels: documentation, backport, size/sm

#27096 Extend Teleport RBAC to support Kubernetes Verbs
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/kube_integration_test.go
  integration/proxy/proxy_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/resource_filters.go
  lib/kube/proxy/resource_filters_test.go
  lib/kube/proxy/resource_rbac_test.go
  lib/kube/proxy/self_subject_reviews.go
  lib/kube/proxy/self_subject_reviews_test.go
  lib/kube/proxy/url.go
  lib/kube/proxy/url_test.go
  lib/kube/proxy/utils_testing.go
  lib/services/access_checker.go
  lib/services/access_checker_test.go
  lib/services/presets.go
  lib/services/role.go
  lib/services/role_test.go
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: kubernetes-access, sales-onboarding, size/md

#28645 [v13] [Docs] Add IdP-initiated SSO instructions to Grafana SAML guide
  docs/pages/access-controls/idps/saml-grafana.mdx
Labels: documentation, backport, size/sm

#28644 [v12] [Docs] Add IdP-initiated SSO instructions to Grafana SAML guide
  docs/pages/access-controls/idps/saml-grafana.mdx
Labels: documentation, backport, size/sm

#28674 Edit playbook user in the Ansible guide
  docs/pages/machine-id/guides/ansible.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28678 Minor clarifications in the Azure AD guide
  docs/pages/access-controls/sso/azuread.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28688 docs: use -o file instead of sudo tee for teleport configure example
  docs/pages/includes/tls-certificate-setup.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28732 [v13] Update assist docs
  docs/pages/ai-assist.mdx
Labels: documentation, backport, size/sm

#28613 [v13] Add t.Parallel() to several tsh tests
  tool/tsh/app_azure_test.go
  tool/tsh/app_cloud_test.go
  tool/tsh/app_gcp_test.go
  tool/tsh/db_test.go
  tool/tsh/recording_export_test.go
  tool/tsh/tshconfig_test.go
Labels: tsh, backport, size/sm

#28774 Fix Okta docs that mentioned "Application Service"
  docs/pages/application-access/okta/guide.mdx
Labels: documentation, size/sm, backport/branch/v13

#28721 [Docs]: Minor wording change
  docs/pages/core-concepts.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28639 [v13] document create_host_users_mode
  docs/pages/access-controls/reference.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/server-access/guides/host-user-creation.mdx
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/sm

#28694 [v12] update attributes to roles
  docs/cspell.json
  docs/pages/access-controls/sso/adfs.mdx
Labels: documentation, backport, size/sm

#28695 [v13] update attributes to roles
  docs/cspell.json
  docs/pages/access-controls/sso/adfs.mdx
Labels: documentation, backport, size/sm

#28779 Increased the gh-trigger-workflow polling period
  build.assets/tooling/cmd/gh-trigger-workflow/main.go
  build.assets/tooling/lib/github/workflows.go
Labels: backport-required, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28537 DeployService: auto upsert IAM Join Token
  api/types/provisioning.go
  lib/integrations/awsoidc/clients.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_jointoken.go
  lib/integrations/awsoidc/deployservice_iam_jointoken_test.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/fixtures/without_account_id.yaml
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: discover, size/lg, backport/branch/v13

#28784 [v11] Increased the gh-trigger-workflow polling period
  build.assets/tooling/lib/github/workflows.go
Labels: backport, size/sm

#28785 [v12] Increased the gh-trigger-workflow polling period
  build.assets/tooling/cmd/gh-trigger-workflow/main.go
  build.assets/tooling/lib/github/workflows.go
Labels: backport, size/sm

#28783 [v13] Increased the gh-trigger-workflow polling period
  build.assets/tooling/cmd/gh-trigger-workflow/main.go
  build.assets/tooling/lib/github/workflows.go
Labels: backport, size/sm

#28681 [v12] Change signup links to mention Teleport Team
  docs/pages/choose-an-edition/teleport-cloud/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/operations/tls-routing.mdx
Labels: documentation, backport, size/sm

#28796 Added 07/03 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#28797 [v11] Fixed CPIO digest mismatch on RHEL 8
  build.assets/build-package.sh
Labels: backport, size/sm

#28792 [v13] Fix Okta docs that mentioned "Application Service"
  docs/pages/application-access/okta/guide.mdx
Labels: documentation, backport, size/sm

#28795 [v12] Fixed CPIO digest mismatch on RHEL 8
  build.assets/build-package.sh
Labels: backport, size/sm

#28753 [Docs] Add missing 'resources' config field to application service docs
  docs/pages/includes/config-reference/app-service.yaml
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28433 [v12] Add option to allow for host users not to be deleted
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/types.pb.go
  docs/pages/access-controls/reference.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/server-access/guides/host-user-creation.mdx
  docs/pages/server-access/rbac.mdx
  integration/hostuser_test.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/regular/sshserver.go
  lib/srv/sess.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
  lib/utils/host/hostusers.go
  lib/web/resources_test.go
  tool/tctl/sso/tester/format_test.go
Labels: documentation, tctl, backport, size/md

#28435 Fix `tsh kube credentials` lock when no-login is required
  lib/client/api.go
  lib/client/api_login_test.go
  lib/utils/fs.go
  tool/tsh/common/kube.go
Labels: tsh, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28718 Access list backend service and marshal/unmarshal.
  api/types/access_list.go
  api/types/access_list_test.go
  api/types/resource.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/lg

#28804 removed cloud warning
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, size/sm, backport/branch/v13

#28680 [v13] Change signup links to mention Teleport Team
  docs/pages/choose-an-edition/teleport-cloud/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/operations/tls-routing.mdx
Labels: documentation, backport, size/sm

#28692 [v12] Docs: Update GitLab SSO docs
  docs/cspell.json
  docs/img/sso/gitlab/gitlab-oidc-0.png
  docs/img/sso/gitlab/gitlab-oidc-1.png
  docs/img/sso/teleportauditlogssofailed.png
  docs/pages/access-controls/sso/gitlab.mdx
Labels: documentation, backport, size/sm

#28813 Update keep_alive comments auth-service.yaml
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28765 [v13] Use more restrictive S3 object permissions
  docs/pages/includes/s3-iam-policy.mdx
Labels: documentation, backport, size/sm

#28764 [v12] Use more restrictive S3 object permissions
  docs/pages/includes/s3-iam-policy.mdx
Labels: documentation, backport, size/sm

#28790 [v12] Edit playbook user in the Ansible guide
  docs/pages/machine-id/guides/ansible.mdx
Labels: documentation, backport, size/sm

#28789 [v11] Edit playbook user in the Ansible guide
  docs/pages/machine-id/guides/ansible.mdx
Labels: documentation, backport, size/sm

#28791 [v13] Edit playbook user in the Ansible guide
  docs/pages/machine-id/guides/ansible.mdx
Labels: documentation, backport, size/sm

#28812 [v12] Fix `tsh kube credentials` lock when no-login is required
  lib/client/api.go
  lib/client/api_login_test.go
  lib/utils/fs.go
  tool/tsh/kube.go
Labels: tsh, backport, size/md

#28824 docs: openssh instructions updates
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, size/sm

#28815 [v13] removed cloud warning
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, backport, size/sm

#28788 [v13] docs: bump cloud to 13.2.0
  docs/config.json
Labels: documentation, backport, size/sm

#28786 [v12] docs: bump cloud to 13.2.0
  docs/config.json
Labels: documentation, backport, size/sm

#28767 Docs: typo correction in Teleport Cluster page
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28755 Makes custom CORS logic a middleware
  lib/web/app/handler.go
  lib/web/app/middleware.go
Labels: size/sm

#28820 [v13] Update keep_alive comments auth-service.yaml
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, backport, size/sm

#28827 [v13] Docs: typo correction in Teleport Cluster page
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm

#28829 [v11] Docs: typo correction in Teleport Cluster page
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm

#28822 [v13] Add redirects introduced by docs reorganization
  docs/config.json
Labels: documentation, backport, size/sm

#28821 [v12] Update keep_alive comments auth-service.yaml
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, backport, size/sm

#28828 [v12] Docs: typo correction in Teleport Cluster page
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm

#28819 teleport-connect.mdx: Fix typo (you with -> you wish)
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28776 docs: bump cloud to 13.2.0
  docs/config.json
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28777 [v12] [Docs]: Minor wording change
  docs/pages/core-concepts.mdx
Labels: documentation, backport, size/sm

#28778 [v13] [Docs]: Minor wording change
  docs/pages/core-concepts.mdx
Labels: documentation, backport, size/sm

#28798 [v11] docs: Minor wording change
  docs/pages/core-concepts.mdx
Labels: documentation, backport, size/sm

#28349 Report failures if Windows build fails
  .github/workflows/build-windows.yaml
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27895 rework instance hbs to be more scalable and to track upgraders
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/instance_test.go
  api/types/types.pb.go
  integration/integration_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/inventory/controller.go
  lib/inventory/controller_test.go
  lib/inventory/helpers.go
  lib/inventory/helpers_test.go
  lib/inventory/inventory.go
  lib/services/inventory.go
  lib/services/local/inventory.go
  lib/services/local/inventory_test.go
  lib/services/presets.go
  tool/tctl/common/inventory_command.go
Labels: tctl, size/md

#28810 DeployService: use correct version when auto-upgrades are enabled
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/web/integrations_awsoidc.go
Labels: discover, size/sm, backport/branch/v13

#28832 [v13] Support specifying `assume_role_arn` for Kube cluster matchers
  lib/cloud/clients.go
  lib/cloud/mocks/aws.go
  lib/cloud/mocks/azure.go
  lib/cloud/mocks/gcp.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/kube_creds.go
  lib/kube/proxy/kube_creds_test.go
  lib/kube/proxy/watcher.go
Labels: kubernetes-access, backport, size/lg

#28673 Add IDToken attributes to GCP join audit event
  lib/auth/join.go
  lib/auth/join_gcp.go
Labels: size/sm, backport/branch/v13

#28312 Connect Kube gateway part 1: lib/teleterm/gateway
  integration/proxy/proxy_helpers.go
  lib/srv/alpnproxy/forward_proxy.go
  lib/srv/alpnproxy/kube.go
  lib/srv/alpnproxy/local_proxy.go
  lib/teleterm/api/uri/uri.go
  lib/teleterm/api/uri/uri_test.go
  lib/teleterm/gateway/config.go
  lib/teleterm/gateway/db_middleware.go
  lib/teleterm/gateway/db_middleware_test.go
  lib/teleterm/gateway/gateway.go
  lib/teleterm/gateway/gateway_db.go
  lib/teleterm/gateway/gateway_kube.go
  lib/teleterm/gateway/gateway_kube_test.go
  lib/teleterm/gateway/kube_cert_reissuer.go
  lib/teleterm/gatewaytest/helpers.go
  lib/utils/fs.go
  tool/tsh/common/app.go
  tool/tsh/common/kube_proxy.go
Labels: tsh, tls-routing, kubernetes, teleport-connect, size/lg

#27731 Add more details about specifying a CA pin
  docs/pages/includes/config-reference/instance-wide.yaml
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28648 docs: Add clarification on event types in enhanced recording mode
  docs/cspell.json
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, sales-onboarding, size/md, backport/branch/v13

#28847 [v13] rework instance hbs to be more scalable and to track upgraders
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/instance_test.go
  api/types/types.pb.go
  integration/integration_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/inventory/controller.go
  lib/inventory/controller_test.go
  lib/inventory/helpers.go
  lib/inventory/helpers_test.go
  lib/inventory/inventory.go
  lib/services/inventory.go
  lib/services/local/inventory.go
  lib/services/local/inventory_test.go
  lib/services/presets.go
  tool/tctl/common/inventory_command.go
Labels: tctl, backport, size/md

#28646 Machine ID: Add guides to the Enroll Integration page
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  proto/prehog/v1alpha/teleport.proto
  web/packages/design/src/SVGIcon/Ansible.tsx
  web/packages/design/src/SVGIcon/CircleCI.tsx
  web/packages/design/src/SVGIcon/GitHub.tsx
  web/packages/design/src/SVGIcon/GitLab.tsx
  web/packages/design/src/SVGIcon/Jenkins.tsx
  web/packages/design/src/SVGIcon/index.ts
  web/packages/teleport/src/Integrations/Enroll/IntegrationEnroll.tsx
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport/branch/v11, size/md, backport/branch/v12, backport/branch/v13

#28877 [v11] teleport-connect.mdx: Fix typo (you with -> you wish)
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport, size/sm

#28875 [v13] teleport-connect.mdx: Fix typo (you with -> you wish)
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport, size/sm

#28876 [v12] teleport-connect.mdx: Fix typo (you with -> you wish)
  docs/pages/connect-your-client/teleport-connect.mdx
Labels: documentation, backport, size/sm

#28773 [v11] docs: use -o file instead of sudo tee for teleport configure example
  docs/pages/includes/tls-certificate-setup.mdx
Labels: documentation, backport, size/sm

#28772 [v12] docs: use -o file instead of sudo tee for teleport configure example
  docs/pages/includes/tls-certificate-setup.mdx
Labels: documentation, backport, size/sm

#28882 [v13] Add IDToken attributes to GCP join audit event (#28673)
  lib/auth/join.go
  lib/auth/join_gcp.go
Labels: backport, size/sm

#28888 [v13] Machine ID: Add guides to the Enroll Integration page (#28646)
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  proto/prehog/v1alpha/teleport.proto
  web/packages/design/src/SVGIcon/Ansible.tsx
  web/packages/design/src/SVGIcon/CircleCI.tsx
  web/packages/design/src/SVGIcon/GitHub.tsx
  web/packages/design/src/SVGIcon/GitLab.tsx
  web/packages/design/src/SVGIcon/Jenkins.tsx
  web/packages/design/src/SVGIcon/index.ts
  web/packages/teleport/src/Integrations/Enroll/IntegrationEnroll.tsx
  web/packages/teleport/src/Integrations/Enroll/MachineIDIntegrationSection.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport, size/md

#28816 chore: Bump Buf to v1.23.1
  build.assets/Makefile
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28621 WebDiscover: Finish auto deploy screen (iam configure script)
  web/packages/teleport/src/Discover/Database/ConnectAwsAccount/ConnectAwsAccount.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.story.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.test.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/ManualDeploy.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.test.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Discover/Database/index.tsx
  web/packages/teleport/src/Discover/Shared/useShowHint.ts
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/instructions/Instructions.story.tsx
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/instructions/SeventhStageInstructions.tsx
  web/packages/teleport/src/config.test.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/integrations/integrations.ts
Labels: ui, size/sm, backport/branch/v13

#28893 [v13] docs: Add clarification on event types in enhanced recording mode
  docs/cspell.json
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/md

#28808 tctl alert ls: Always show alert ID
  tool/tctl/common/alert_command.go
Labels: tctl, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28073 add Athena URL parameter to configure AWS region
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
Labels: audit-log, size/sm, backport/branch/v13

#28896 [v11] chore: Bump Buf to v1.23.1
  build.assets/Makefile
Labels: backport, size/sm
