Repository gravitational/teleport, pull requests merged in 2023-06, with the labels that each got.

#27139 Update cloud version to 12.4.5
  docs/config.json
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27176 [v12] helm: Switch custom deployment guide to standalone rather than scratch
  docs/pages/deploy-a-cluster/helm-deployments/custom.mdx
Labels: documentation, backport, size/sm

#27177 [v13] helm: Switch custom deployment guide to standalone rather than scratch
  docs/pages/deploy-a-cluster/helm-deployments/custom.mdx
Labels: documentation, backport, size/sm

#27107 [v11] Close clients when done.
  lib/client/api.go
  lib/client/client.go
Labels: backport, size/sm

#26614 Implement leaf app access: `tsh app login --cluster=leaf`
  tool/tsh/access_request_test.go
  tool/tsh/app.go
  tool/tsh/app_test.go
  tool/tsh/db_test.go
  tool/tsh/kube_test.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport/branch/v11, size/md, backport/branch/v12, backport/branch/v13

#27198 integrations/updater: bump dependencies
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  integrations/kube-agent-updater/go.mod
  integrations/kube-agent-updater/go.sum
Labels: size/sm, backport/branch/v13

#26790 Docs: Update GitHub SSO
  docs/img/login-success.jpg
  docs/img/login-success.png
  docs/img/sso/github-app-vars.png
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27006 [v13] [Docs] Add section for `username_claim` in OIDC docs
  docs/pages/access-controls/sso/oidc.mdx
Labels: documentation, backport, size/sm

#27007 [v12] [Docs] Add section for `username_claim` in OIDC docs
  docs/pages/access-controls/sso/oidc.mdx
Labels: documentation, backport, size/sm

#27008 [v11] [Docs] Add section for `username_claim` in OIDC docs
  docs/pages/access-controls/sso/oidc.mdx
Labels: documentation, backport, size/sm

#27093 [v13] Add docs for shell completion
  docs/cspell.json
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27179 Add static credentials reference to plugin credentials.
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/plugins/v1/plugin_service.proto
  api/types/plugin.go
  api/types/plugin_test.go
  api/types/types.pb.go
Labels: size/sm, backport/branch/v13

#27193 Updated Cloud SQL guides with more info about 'Allow only SSL connections' option
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/includes/database-access/cloudsql-ssl.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#25721 [v13] return an error if a moderated session is created for an agentless node
  lib/srv/forward/sshserver.go
Labels: backport, size/sm

#27203 [v12] docs: update fluentd output and correct docs link
  docs/pages/includes/configure-event-handler.mdx
Labels: documentation, backport, size/sm

#27039 Improve Device Trust Ceremony mocking for tests
  lib/client/api.go
  lib/devicetrust/authn/authn.go
  lib/devicetrust/authn/authn_test.go
  lib/devicetrust/authn/export_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13

#27166 [v12] Add information about the cert-format flag
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27213 [v12] Update cloud version to 12.4.5
  docs/config.json
Labels: documentation, backport, size/sm

#27167 [v13] Add information about the cert-format flag
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27214 [v13] Update cloud version to 12.4.5
  docs/config.json
Labels: documentation, backport, size/sm

#27136 Fix headless server access requests
  lib/client/api.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, size/sm, backport/branch/v12, backport/branch/v13

#27224 [v13] Updated Cloud SQL guides with more info about 'Allow only SSL connections' option
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/includes/database-access/cloudsql-ssl.mdx
Labels: documentation, backport, size/sm

#27188 [v13] Add elasticache:Connect AWS permission to auto-IAM
  lib/cloud/mocks/aws.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/srv/db/cloud/aws.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/srv/db/common/iam/aws.go
  lib/srv/db/common/iam/aws_test.go
  lib/srv/db/redis/engine.go
  lib/web/databases_test.go
Labels: database-access, backport, size/md

#27040 [v12] Update title for proxy peering architecture
  docs/pages/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
Labels: documentation, backport, size/sm

#27202 [v13] docs: update fluentd output and correct docs link
  docs/pages/includes/configure-event-handler.mdx
Labels: documentation, backport, size/sm

#27223 [v12] Updated Cloud SQL guides with more info about 'Allow only SSL connections' option
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/includes/database-access/cloudsql-ssl.mdx
Labels: documentation, backport, size/sm

#27225 [v13] Add static credentials reference to plugin credentials.
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/plugins/v1/plugin_service.proto
  api/types/plugin.go
  api/types/plugin_test.go
  api/types/types.pb.go
Labels: backport, size/sm

#27222 [v11] Updated Cloud SQL guides with more info about 'Allow only SSL connections' option
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/includes/database-access/cloudsql-ssl.mdx
Labels: documentation, backport, size/sm

#27196 Ignore ENOENT error on group check
  lib/srv/usermgmt.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27226 [v13] Docs: update access controls table
  docs/pages/includes/edition-comparison.mdx
Labels: documentation, backport, size/sm

#27165 [v11] Add information about the cert-format flag
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27117 docs: add troubleshooting step for standard RDP security
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, desktop-access, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27160 docs: mention locking as an alternative to CA rotation for revoking a…
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27227 [v12] Docs: update access controls table
  docs/pages/includes/edition-comparison.mdx
Labels: documentation, backport, size/sm

#27234 [v13] tncon.c: Switch all size variables to `size_t`
  lib/client/tncon/tncon.c
Labels: backport, size/sm

#27233 [v12] tncon.c: Switch all size variables to `size_t`
  lib/client/tncon/tncon.c
Labels: backport, size/sm

#27241 [v13] Fix headless server access requests
  lib/client/api.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm

#27246 [v12] docs: add troubleshooting step for standard RDP security
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm

#27245 [v13] docs: add troubleshooting step for standard RDP security
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm

#27248 [v13] docs: mention locking as an alternative to CA rotation for revoking a…
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport, size/sm

#27237 [v13] lib/kube/proxy/server.go: Fix potential mutex deadlock on error
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
Labels: kubernetes-access, backport, size/sm

#27236 [v12] lib/kube/proxy/server.go: Fix potential mutex deadlock on error
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
Labels: kubernetes-access, backport, size/sm

#26555 (v13) Add support for automatic database users for Postgres
  Makefile
  api/constants/constants.go
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/constants.go
  api/types/database.go
  api/types/events/events.pb.go
  api/types/role.go
  api/types/types.pb.go
  api/types/user.go
  constants.go
  go.mod
  lib/auth/auth.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/servicecfg/database.go
  lib/services/access_checker.go
  lib/services/database.go
  lib/services/presets.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/db/access_test.go
  lib/srv/db/autousers_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/common/autousers.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/interfaces.go
  lib/srv/db/common/role/role.go
  lib/srv/db/common/session.go
  lib/srv/db/postgres/activate-user.sql
  lib/srv/db/postgres/deactivate-user.sql
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
  lib/srv/db/postgres/users.go
  lib/srv/db/server.go
  lib/web/resources_test.go
  tool/tctl/common/resource_command_test.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
  tool/tctl/sso/tester/format_test.go
  tool/tsh/db.go
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, tsh, tctl, database-access, backport, size/lg

#27232 [v11] tncon.c: Switch all size variables to `size_t`
  lib/client/tncon/tncon.c
Labels: backport, size/sm

#27247 [v11] docs: add troubleshooting step for standard RDP security
  docs/pages/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm

#27235 [v11] lib/kube/proxy/server.go: Fix potential mutex deadlock on error
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
Labels: kubernetes-access, backport, size/sm

#27229 [v11] Ignore ENOENT error on group check
  lib/srv/usermgmt.go
Labels: backport, size/sm

#27231 [v13] Ignore ENOENT error on group check
  lib/srv/usermgmt.go
Labels: backport, size/sm

#27230 [v12] Ignore ENOENT error on group check
  lib/srv/usermgmt.go
Labels: backport, size/sm

#27218 [v13] docs: device trust and okta provider
  docs/cspell.json
  docs/pages/reference/terraform-provider.mdx
Labels: documentation, backport, size/md

#27205 [v11] docs: update fluentd output and correct docs link
  docs/pages/management/export-audit-events/fluentd.mdx
Labels: documentation, backport, size/sm

#27140 [v13] Fix TeleportClient.ConnectToProxy logic error with closed context.
  lib/client/api.go
  lib/client/api_test.go
Labels: backport, size/sm

#27148 [v12] Fix TeleportClient.ConnectToProxy logic error with closed context.
  lib/client/api.go
  lib/client/api_test.go
Labels: backport, size/sm

#27264 Pin golangci-lint to `v1.53.1` and upgrade `depguard` config to `v2`
  .golangci.yml
  build.assets/Dockerfile
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27221 Reply with a user-friendly message on verification errors
  lib/auth/webauthn/register.go
  lib/auth/webauthn/register_test.go
Labels: support-load, passwordless, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27250 [v13] tctl: allow creating desktops from YAML file
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm

#27251 [v12] tctl: allow creating desktops from YAML file
  tool/tctl/common/resource_command.go
Labels: tctl, backport, backport/branch/v11, size/sm

#27261 [v13] Speedup OpenSSL build
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-multiarch
Labels: backport, size/sm

#27026 Add endpoints to export AuditEvents as unstructured data
  api/client/client.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog.pb.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog_grpc.pb.go
  api/proto/buf.yaml
  api/proto/teleport/auditlog/v1/auditlog.proto
  api/types/events/events.go
  lib/auth/grpcserver.go
Labels: size/md, backport/branch/v13

#27209 Build change for when go caching should be used
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/build-api.yaml
  .github/workflows/build-macos.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/check.yaml
  .github/workflows/codeql.yml
  .github/workflows/dismiss.yaml
  .github/workflows/label.yaml
Labels: go, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27268 Allow overriding docker in `make grpc`
  build.assets/Dockerfile-grpcbox
  build.assets/grpcbox.mk
Labels: size/sm

#26987 Add docs for database auto user provisioning
  docs/config.json
  docs/cspell.json
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/database-access/rbac/configuring-access.mdx
  docs/pages/database-access/rbac/configuring-auto-user-provisioning.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/role-spec.mdx
Labels: documentation, size/md, backport/branch/v13

#27059 Fix `NewHeadlessAuthenticationWatcher` prevents Auth initialization when the backend is unavailable
  lib/auth/helpers.go
  lib/services/local/headlessauthn_watcher.go
  lib/services/local/headlessauthn_watcher_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13

#27255 Add plugin static credentials getter.
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/proto/teleport/plugins/v1/plugin_service.proto
Labels: size/sm, backport/branch/v13

#26989 Add IAM auth info to ElastiCache guide
  docs/img/database-access/guides/redis/redis-aws-iam-user@2x.png
  docs/pages/database-access/guides/redis-aws.mdx
Labels: documentation, size/sm, backport/branch/v13

#27217 Use the proper check for the SAML IdP session.
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/sessions.go
Labels: size/sm, backport/branch/v12, backport/branch/v13

#27305 Disable GHA cache
  .github/actions/prepare-workspace/action.yml
  .github/workflows/unit-tests-rust.yaml
Labels: size/sm

#27293 [v13] Pin golangci-lint to `v1.53.1` and upgrade `depguard` config to `v2`
  .golangci.yml
  build.assets/Dockerfile
Labels: backport, size/sm

#27292 [v12] Pin golangci-lint to `v1.53.1` and upgrade `depguard` config to `v2`
  .golangci.yml
  build.assets/Dockerfile
Labels: backport, size/sm

#27291 [v11] Pin golangci-lint to `v1.53.1` and upgrade `depguard` config to `v2`
  .golangci.yml
  build.assets/Dockerfile
Labels: backport, size/sm

#27297 [v12] Web: Fix local storage clearing
  web/packages/teleport/src/services/localStorage/localStorage.test.ts
  web/packages/teleport/src/services/localStorage/localStorage.ts
Labels: ui, backport, size/sm

#27299 [v12] Fix `NewHeadlessAuthenticationWatcher` prevents Auth initialization when the backend is unavailable
  lib/auth/helpers.go
  lib/services/local/headlessauthn_watcher.go
  lib/services/local/headlessauthn_watcher_test.go
Labels: backport, size/sm

#27315 [v13] Disable GHA cache
  .github/actions/prepare-workspace/action.yml
  .github/workflows/unit-tests-rust.yaml
Labels: backport, size/sm

#27324 [v11] fix github url formatting backport
  lib/auth/github.go
  lib/auth/github_test.go
Labels: backport, size/sm

#27296 [v13] Web: Fix local storage clearing
  web/packages/teleport/src/services/localStorage/localStorage.test.ts
  web/packages/teleport/src/services/localStorage/localStorage.ts
Labels: ui, backport, size/sm

#27300 Release 12.4.6
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#26969 Update Proxy Template docs
  docs/pages/reference/cli.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#27238 [v12] Improve Device Trust Ceremony mocking for tests
  lib/client/api.go
  lib/devicetrust/authn/authn.go
  lib/devicetrust/authn/authn_test.go
  lib/devicetrust/authn/export_test.go
Labels: backport, size/sm

#27240 [v12] Fix headless server access requests
  lib/client/api.go
  tool/tsh/tsh.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm

#27239 [v13] Improve Device Trust Ceremony mocking for tests
  lib/client/api.go
  lib/devicetrust/authn/authn.go
  lib/devicetrust/authn/authn_test.go
  lib/devicetrust/authn/export_test.go
Labels: backport, size/sm

#27317 [v12] Disable GHA cache
  .github/actions/prepare-workspace/action.yml
  .github/workflows/unit-tests-rust.yaml
Labels: backport, size/sm

#27259 removes now irrelevant webpackChunkName comments
  web/packages/teleport/src/Integrations/Enroll/IntegrationRoute.tsx
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/boot.tsx
  web/packages/teleport/src/features.tsx
Labels: ui, size/sm

#27257 cache parsed role template expressions
  lib/services/label_expressions.go
  lib/services/role_test.go
  lib/utils/parse/parse.go
  lib/utils/typical/cached_parser.go
  lib/utils/typical/cached_parser_test.go
Labels: size/sm, backport/branch/v13

#27298 [v13] Fix `NewHeadlessAuthenticationWatcher` prevents Auth initialization when the backend is unavailable
  lib/auth/helpers.go
  lib/services/local/headlessauthn_watcher.go
  lib/services/local/headlessauthn_watcher_test.go
Labels: backport, size/sm

#27249 [v12] docs: mention locking as an alternative to CA rotation for revoking access
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport, backport/branch/v11, size/sm

#27274 [v13] flaky test detector: override skipped tests
  .github/workflows/flaky-tests.yaml
  build.assets/tooling/cmd/difftest/main.go
Labels: backport, size/sm

#27262 Vendors the `pagerduty` plugin source into `teleport`
  go.mod
  go.sum
  integrations/access/pagerduty/app.go
  integrations/access/pagerduty/client.go
  integrations/access/pagerduty/config.go
  integrations/access/pagerduty/fake_pagerduty_test.go
  integrations/access/pagerduty/pagerduty_test.go
  integrations/access/pagerduty/plugindata.go
  integrations/access/pagerduty/plugindata_test.go
  integrations/access/pagerduty/types.go
  integrations/access/pagerduty/version.go
  integrations/lib/testing/integration/integration.go
Labels: size/xl

#27277 [v11] Docs: Update GitHub SSO
  docs/img/login-success.jpg
  docs/img/login-success.png
  docs/img/sso/github-app-vars.png
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27276 [v12] Docs: Update GitHub SSO
  docs/img/login-success.jpg
  docs/img/login-success.png
  docs/img/sso/github-app-vars.png
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27092 [v12] Add docs for shell completion
  docs/cspell.json
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27266 Assist bug fixes
  web/packages/shared/package.json
  web/packages/teleport/src/Assist/Chat/ChatItem/Action/RunAction.tsx
  web/packages/teleport/src/Assist/contexts/messages.test.ts
  web/packages/teleport/src/Assist/contexts/messages.tsx
  web/packages/teleport/src/Navigation/NavigationSwitcher.tsx
  yarn.lock
Labels: ui, size/sm, backport/branch/v13

#27294 [v13] Get locks in tctl get all
  lib/services/local/resource.go
  lib/services/local/resource_test.go
  lib/services/resource.go
Labels: backport, size/sm

#27295 [v12] Get locks in tctl get all
  lib/services/local/resource.go
  lib/services/local/resource_test.go
  lib/services/resource.go
Labels: backport, size/sm

#27328 docs: update enrollment steps for active dir
  docs/pages/desktop-access/active-directory.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#27352 [v12] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#27356 [v13] Assist bug fixes
  web/packages/shared/package.json
  web/packages/teleport/src/Assist/Chat/ChatItem/Action/RunAction.tsx
  web/packages/teleport/src/Assist/contexts/messages.test.ts
  web/packages/teleport/src/Assist/contexts/messages.tsx
  web/packages/teleport/src/Navigation/NavigationSwitcher.tsx
  yarn.lock
Labels: ui, backport, size/sm

#27362 [v13] Get fresh cluster features to `config.js` (#26785)
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#27361 [v12] Get fresh cluster features to `config.js` (#26785)
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#26102 Add kube credentials lockfile to prevent possibility of excessive login attempts
  api/utils/keypaths/keypaths.go
  lib/client/keystore.go
  lib/utils/fs_windows.go
  tool/tsh/kube.go
  tool/tsh/tsh_test.go
Labels: tsh, size/md, backport/branch/v12, backport/branch/v13

#27313 [v12] Use the proper check for the SAML IdP session.
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/sessions.go
Labels: backport, size/md

#27366 [v13] Add kube credentials lockfile to prevent possibility of excessive login attempts
  api/utils/keypaths/keypaths.go
  lib/client/keystore.go
  lib/utils/fs_windows.go
  tool/tsh/kube.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/md

#27273 [v13] Docs: Update GitHub SSO
  docs/img/login-success.jpg
  docs/img/login-success.png
  docs/img/sso/github-app-vars.png
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#27269 WebPublicAddr includes user specified port.
  lib/service/servicecfg/config_test.go
  lib/service/servicecfg/proxy.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27310 docs: Formatting/grammar fixes for TLS routing
  docs/pages/architecture/tls-routing.mdx
Labels: documentation, size/sm, backport/branch/v13

#27290 [v13] Add endpoints to export AuditEvents as unstructured data
  api/client/client.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog.pb.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog_grpc.pb.go
  api/proto/buf.yaml
  api/proto/teleport/auditlog/v1/auditlog.proto
  api/types/events/events.go
  lib/auth/grpcserver.go
Labels: backport, size/md

#27357 [v13] docs: update enrollment steps for active dir
  docs/pages/desktop-access/active-directory.mdx
Labels: documentation, backport, size/sm

#27260 [v13] Assist docs
  docs/config.json
  docs/cspell.json
  docs/img/assist/architecture-diagram.png
  docs/img/assist/assist-example.png
  docs/img/assist/assist-screen.png
  docs/img/assist/main-screen.png
  docs/pages/ai-assist.mdx
  docs/pages/core-concepts.mdx
Labels: documentation, backport, size/md

#27270 [v13] Reply with a user-friendly message on verification errors
  lib/auth/webauthn/register.go
  lib/auth/webauthn/register_test.go
Labels: backport, size/sm

#27272 [v11] Reply with a user-friendly message on verification errors
  lib/auth/webauthn/register.go
  lib/auth/webauthn/register_test.go
Labels: backport, size/sm

#27271 [v12] Reply with a user-friendly message on verification errors
  lib/auth/webauthn/register.go
  lib/auth/webauthn/register_test.go
Labels: backport, size/sm

#27370 [v12] Add kube credentials lockfile to prevent possibility of excessive login attempts
  api/utils/keypaths/keypaths.go
  lib/client/keystore.go
  lib/utils/fs_windows.go
  tool/tsh/kube.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/md

#27378 [v11] WebPublicAddr includes user specified port.
  lib/service/cfg.go
  lib/service/cfg_test.go
Labels: backport, size/sm

#27326 [v13] cache parsed role template expressions
  lib/services/label_expressions.go
  lib/services/role_test.go
  lib/utils/parse/parse.go
  lib/utils/typical/cached_parser.go
  lib/utils/typical/cached_parser_test.go
Labels: backport, size/md

#27178 Create api handler specifically for FormData
  web/packages/teleport/src/services/api/api.js
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13

#27253 [v13] Minor updates to Server Access Getting Started
  docs/pages/server-access/getting-started.mdx
Labels: documentation, backport, size/sm

#27267 chore: Bump Buf to v1.20.0
  build.assets/Makefile
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27191 RFD 0130: Autogenerate the Teleport Resource Reference
  rfd/0130-autogenerate-resource-reference.md
Labels: rfd, size/lg

#27384 [v11] tncon: Remove unused return variables
  lib/client/tncon/tncon.c
Labels: backport, size/sm

#27386 [v13] tncon: Remove unused return variables
  lib/client/tncon/tncon.c
Labels: backport, size/sm

#27391 [v13] docs: Formatting/grammar fixes for TLS routing
  docs/pages/architecture/tls-routing.mdx
Labels: documentation, backport, size/sm

#27200 Edit the docs test plan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#22066 Adds info on exporting requirements for impersonated certs
  docs/pages/includes/plugins/identity-export.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27281 [v11] Docs: patch Enhanced Session recording
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#27279 [v13] Docs: patch Enhanced Session recording
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#27280 [v12] Docs: patch Enhanced Session recording
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm

#27350 [v13] Update Proxy Template docs
  docs/pages/reference/cli.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport, size/sm

#27306 [v13] Add IAM auth info to ElastiCache guide
  docs/img/database-access/guides/redis/redis-aws-iam-user@2x.png
  docs/pages/database-access/guides/redis-aws.mdx
Labels: documentation, backport, size/sm

#27194 WebDiscover: Check for RDS length before setting a limit for listing DBs
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/AwsRegionSelector.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.story.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.test.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
Labels: ui, size/md, backport/branch/v12, backport/branch/v13

#27351 [v12] Update Proxy Template docs
  docs/pages/reference/cli.mdx
  docs/pages/server-access/guides/openssh.mdx
Labels: documentation, backport, size/sm

#27402 [v11] chore: Bump Buf to v1.20.0
  build.assets/Makefile
Labels: backport, size/sm

#27400 [v13] chore: Bump Buf to v1.20.0
  build.assets/Makefile
Labels: backport, size/sm

#27058 Correctly set `SSH_SESSION_WEBPROXY_ADDR` in Web UI ssh sessions
  lib/client/client.go
  lib/web/apiserver.go
  lib/web/terminal.go
Labels: size/sm

#27398 Update RFD 9 - Locking
  rfd/0009-locking.md
Labels: rfd, size/sm

#27403 [v13] Adds info on exporting requirements for impersonated certs
  docs/pages/includes/plugins/identity-export.mdx
Labels: documentation, backport, size/sm

#27404 [v12] Adds info on exporting requirements for impersonated certs
  docs/pages/includes/plugins/identity-export.mdx
Labels: documentation, backport, size/sm

#27405 [v11] Adds info on exporting requirements for impersonated certs
  docs/pages/includes/plugins/identity-export.mdx
Labels: documentation, backport, size/sm

#27413 Add Assist to the access role
  lib/auth/init_test.go
  lib/services/presets.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, assist

#27381 chore: Bump golangci-lint to v1.53.2
  build.assets/Dockerfile
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27424 [v13] Add Assist to the access role
  lib/auth/init_test.go
  lib/services/presets.go
Labels: backport, size/sm

#27396 Document new Okta import rule regexes.
  docs/pages/includes/okta-import-rule.mdx
Labels: documentation, size/sm, backport/branch/v13

#27394 Add prometheus endpoint to tbot
  lib/tbot/tbot.go
Labels: machine-id, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#27431 [Assist] Do not parse event data is there is none
  web/packages/teleport/src/Assist/contexts/messages.tsx
Labels: ui, size/sm, backport/branch/v13, assist

#27435 [v13] [Assist] Do not parse event data is there is none
  web/packages/teleport/src/Assist/contexts/messages.tsx
Labels: ui, backport, size/sm

#27418 Release 13.1.0
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm

#27308 docs: add install to fluentd linux install
  docs/pages/includes/configure-event-handler.mdx
  docs/pages/includes/install-event-handler.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
Labels: documentation, size/sm, backport/branch/v13

#27289 [v13] Add docs for database auto user provisioning
  docs/config.json
  docs/cspell.json
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/database-access/rbac/configuring-access.mdx
  docs/pages/database-access/rbac/configuring-auto-user-provisioning.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/role-spec.mdx
Labels: documentation, backport, size/md

#27425 [v12] Add Assist to the access role
  lib/auth/init_test.go
  lib/services/presets.go
Labels: backport, size/sm

#27275 Document lack of stability of lib/teleterm gRPC API
  gen/proto/js/teleport/lib/teleterm/v1/service_grpc_pb.js
  proto/teleport/lib/teleterm/v1/service.proto
Labels: size/sm

#27432 [v13] Add prometheus endpoint to tbot
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm

#27433 [v12] Add prometheus endpoint to tbot
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm
