Repository gravitational/teleport, pull requests merged in 2023-08, with the labels that each got.

#29798 Vendors Discord plugin source into Teleport
  integrations/access/discord/app.go
  integrations/access/discord/bot.go
  integrations/access/discord/config.go
  integrations/access/discord/discord_test.go
  integrations/access/discord/fake_discord_test.go
  integrations/access/discord/helpers_test.go
  integrations/access/discord/types.go
Labels: size/lg, backport/branch/v13

#29838 [v13] Fix flaky test `TestServer_Authenticate_headless/OK_approved`
  lib/auth/auth_login_test.go
  lib/services/local/headlessauthn_watcher.go
Labels: backport, size/sm

#29837 [v12] Fix flaky test `TestServer_Authenticate_headless/OK_approved`
  lib/auth/auth_login_test.go
  lib/services/local/headlessauthn_watcher.go
Labels: backport, size/sm

#29241 Add a way to construct Teleport app from Kubernetes service
  api/types/constants.go
  lib/services/app.go
  lib/services/app_test.go
  lib/services/matchers.go
Labels: kubernetes-access, size/lg

#29233 [v13] Update `AD` configuration validation requirement for SQL Server RDS proxy databases
  lib/services/database.go
  lib/services/database_test.go
Labels: backport, size/md

#29841 [v13] Vendors Discord plugin source into Teleport
  integrations/access/discord/app.go
  integrations/access/discord/bot.go
  integrations/access/discord/config.go
  integrations/access/discord/discord_test.go
  integrations/access/discord/fake_discord_test.go
  integrations/access/discord/helpers_test.go
  integrations/access/discord/types.go
Labels: backport, size/lg

#29810 Postgres: reduce logging level for individual messages.
  lib/srv/db/postgres/engine.go
Labels: database-access, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, changelog

#29800 [v11] Link to example Login Rules from Login Rules guide
  docs/pages/access-controls/login-rules.mdx
Labels: documentation, backport, size/sm

#29801 [v12] Link to example Login Rules from Login Rules guide
  docs/pages/access-controls/login-rules.mdx
Labels: documentation, backport, size/sm

#29802 [v13] Link to example Login Rules from Login Rules guide
  docs/pages/access-controls/login-rules.mdx
Labels: documentation, backport, size/sm

#29809 lib/teleterm TestStart: Increase timeout, improve error handling
  lib/teleterm/teleterm_test.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29632 Add Kubernetes Access FAQ and Troubleshooting docs
  docs/config.json
  docs/pages/kubernetes-access/faq.mdx
  docs/pages/kubernetes-access/troubleshooting.mdx
Labels: documentation, size/md, backport/branch/v13

#29829 [v13] ALPN upgrade with custom X-Teleport-Upgrade header
  api/client/alpn_conn_upgrade.go
  api/client/alpn_conn_upgrade_test.go
  api/constants/constants.go
  lib/web/conn_upgrade.go
  lib/web/conn_upgrade_test.go
Labels: backport, tls-routing, size/sm

#29732 Listen on "localhost" for tests
  api/client/client_test.go
  integration/teleterm_test.go
  lib/kube/proxy/server_test.go
  lib/srv/regular/sshserver_test.go
  lib/sshutils/x11/forward_test.go
Labels: kubernetes-access, size/sm

#29752 Bump github.com/gravitational/go-libfido2 to `0b44d4f35e28`
  go.mod
  go.sum
Labels: size/sm

#29535 add oss support for partial onboard survey
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Welcome/NewCredentials/NewCredentials.tsx
  web/packages/teleport/src/Welcome/NewCredentials/types.ts
Labels: ui, size/sm

#29853 kube: Split list and deletecollection handlers into seperate files
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/resource_deletecollection.go
  lib/kube/proxy/resource_list.go
Labels: kubernetes-access, size/sm

#29393 Add docs on how to impersonate Kubernetes ServiceAccounts
  docs/pages/kubernetes-access/controls.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29763 allow the default editor role to create nodes
  lib/services/presets.go
Labels: size/sm

#29850 [v11] lib/teleterm TestStart: Increase timeout, improve error handling
  lib/teleterm/teleterm_test.go
Labels: backport, size/sm

#29851 [v12] lib/teleterm TestStart: Increase timeout, improve error handling
  lib/teleterm/teleterm_test.go
Labels: backport, size/sm

#29852 [v13] lib/teleterm TestStart: Increase timeout, improve error handling
  lib/teleterm/teleterm_test.go
Labels: backport, size/sm

#29839 propagate tctl verbose flag
  tool/tctl/common/app_command.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/collection.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/db_command.go
  tool/tctl/common/desktop_command.go
  tool/tctl/common/kube_command.go
  tool/tctl/common/node_command.go
  tool/tctl/common/proxy_command.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/sm, backport/branch/v13

#29746 Machine ID: Kubernetes Secret Destination
  docs/pages/machine-id/reference/configuration.mdx
  integrations/operator/sidecar/tbot.go
  lib/tbot/bot/destination.go
  lib/tbot/bot_identity.go
  lib/tbot/config/config.go
  lib/tbot/config/config_test.go
  lib/tbot/config/destination_directory.go
  lib/tbot/config/destination_kubernetes_secret.go
  lib/tbot/config/destination_kubernetes_secret_test.go
  lib/tbot/config/destination_memory.go
  lib/tbot/config/output.go
  lib/tbot/config/output_application.go
  lib/tbot/config/output_database.go
  lib/tbot/config/output_identity.go
  lib/tbot/config/output_kubernetes.go
  lib/tbot/config/output_ssh_host.go
  lib/tbot/config/output_test.go
  lib/tbot/config/template.go
  lib/tbot/config/template_cockroach.go
  lib/tbot/config/template_identity.go
  lib/tbot/config/template_kubernetes.go
  lib/tbot/config/template_mongo.go
  lib/tbot/config/template_ssh_client.go
  lib/tbot/config/template_ssh_host_cert.go
  lib/tbot/config/template_ssh_host_cert_test.go
  lib/tbot/config/template_tls.go
  lib/tbot/config/template_tls_cas.go
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestDestinationKubernetesSecret_YAML/full.golden
  lib/tbot/identity/identity.go
  lib/tbot/identity_test.go
  lib/tbot/impersonated_identity.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  tool/tbot/init.go
  tool/tbot/kube.go
Labels: documentation, machine-id, size/md, changelog

#29862 Replace custom test renderer with gotestsum
  Makefile
  build.assets/Dockerfile
Labels: size/sm

#29097 Teleport Connect headless approval
  lib/cache/collections.go
  lib/services/local/events.go
  lib/teleterm/clusters/cluster_headless.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_headless.go
  lib/teleterm/daemon/daemon_test.go
  web/packages/teleterm/src/services/tshd/createClient.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptWebauthn/PromptWebauthn.tsx
  web/packages/teleterm/src/ui/HeadlessAuthn/HeadlessAuthentication.tsx
  web/packages/teleterm/src/ui/HeadlessAuthn/HeadlessPrompt/HeadlessPrompt.story.tsx
  web/packages/teleterm/src/ui/HeadlessAuthn/HeadlessPrompt/HeadlessPrompt.tsx
  web/packages/teleterm/src/ui/HeadlessAuthn/HeadlessPrompt/index.ts
  web/packages/teleterm/src/ui/HeadlessAuthn/index.ts
  web/packages/teleterm/src/ui/ModalsHost/ModalsHost.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/services/headlessAuthn/headlessAuthnService.ts
  web/packages/teleterm/src/ui/services/modals/modalsService.ts
  web/packages/teleterm/src/ui/services/relogin/reloginService.ts
  web/packages/teleterm/src/ui/services/tshdNotifications/tshdNotificationService.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, teleport-connect, size/md, headless-sso

#29868 [v13] Add docs on how to impersonate Kubernetes ServiceAccounts
  docs/pages/kubernetes-access/controls.mdx
Labels: documentation, backport, size/sm

#29880 Fix flaky test `TestImportantModalSemaphore`
  integration/proxy/teleterm_test.go
  integration/teleterm_test.go
  lib/teleterm/daemon/daemon_test.go
Labels: size/sm

#29873 Add gotestsum to devbox
  .github/workflows/check-devbox.yaml
  devbox.json
  devbox.lock
Labels: size/sm

#29665 Adds `tctl auth sign --tar` docs to Docker Installation Guide
  docs/pages/installation.mdx
Labels: documentation, size/sm, backport/branch/v13

#29835 docs: add client tools download section
  docs/pages/choose-an-edition/teleport-cloud/downloads.mdx
Labels: documentation, size/sm, backport/branch/v13

#29845 [v11] Postgres: reduce logging level for individual messages.
  lib/srv/db/postgres/engine.go
Labels: database-access, backport, size/sm

#29847 [v13] Postgres: reduce logging level for individual messages.
  lib/srv/db/postgres/engine.go
Labels: database-access, backport, size/sm

#29846 [v12] Postgres: reduce logging level for individual messages.
  lib/srv/db/postgres/engine.go
Labels: database-access, backport, size/sm

#29892 web: Ignore .swc directory when computing web SHA
  build.assets/build-webassets-if-changed.sh
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29876 chore: Bump openssl to 3.0.10
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-multiarch
  build.assets/build-fido2-macos.sh
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29877 Replace custom test render with gotestsum - part II
  Makefile
Labels: size/sm

#29881 chore: Bump Go to 1.20.7
  .drone.yml
  build.assets/Makefile
Labels: size/sm

#29906 [v12] chore: Bump Go to 1.20.7
  .drone.yml
  build.assets/Makefile
Labels: backport, size/sm

#29904 [v13] chore: Bump Go to 1.20.7
  .drone.yml
  build.assets/Makefile
Labels: backport, size/sm

#29907 [v11] chore: Bump Go to 1.20.7
  .drone.yml
  build.assets/Makefile
Labels: backport, size/sm

#29688 Postgres and Azure Blob Storage backend docs
  docs/cspell.json
  docs/pages/reference/backends.mdx
Labels: documentation, backport-required, size/md, backport/branch/v13

#29908 [v13] chore: Bump openssl to 3.0.10
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-multiarch
  build.assets/build-fido2-macos.sh
Labels: backport, size/sm

#29909 [v12] chore: Bump openssl to 3.0.10
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
Labels: backport, size/sm

#29912 [v13] Postgres and Azure Blob Storage backend docs
  docs/cspell.json
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/md

#29884 [v13] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#27899 Add Kubernetes/Helm instructions to the RDS guide
  docs/cspell.json
  docs/pages/database-access/guides/rds.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
  docs/pages/includes/database-access/aws-troubleshooting.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, backport/branch/v11, size/md, backport/branch/v12, backport/branch/v13

#29910 [v11] chore: Bump openssl to 3.0.10
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
Labels: backport, size/sm

#29900 terraform-agent-pool: Fix token provisioning, enable HTTP endpoint, add expiry time
  examples/agent-pool-terraform/agent-pool.tf
Labels: sales-onboarding, time-to-value, size/sm, backport/branch/v13

#29870 [v13] propagate tctl verbose flag
  tool/tctl/common/app_command.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/collection.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/db_command.go
  tool/tctl/common/desktop_command.go
  tool/tctl/common/kube_command.go
  tool/tctl/common/node_command.go
  tool/tctl/common/proxy_command.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm

#29921 fix: Bump libcrypto version in pkgconfig files
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29891 [v13] docs: add client tools download section
  docs/pages/choose-an-edition/teleport-cloud/downloads.mdx
Labels: documentation, backport, size/sm

#29147 Hardware Key Support docs - additional troubleshooting info
  docs/pages/access-controls/guides/hardware-key-support.mdx
  lib/client/api.go
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29721 Use enum to describe `IAMPolicyStatus` instead of a bool
  api/proto/teleport/legacy/types/types.proto
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/web/apiserver_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, database-access, size/sm, backport/branch/v13

#29918 Fuzz Test Improvements
  fuzz/oss-fuzz-build.sh
  lib/services/fuzz_test.go
  lib/srv/db/cassandra/protocol/fuzz_test.go
  lib/srv/db/elasticsearch/fuzz_test.go
  lib/srv/db/mysql/protocol/fuzz_test.go
  lib/srv/db/sqlserver/protocol/fuzz_test.go
  lib/sshutils/sftp/parse_test.go
  lib/sshutils/x11/display_test.go
  lib/sshutils/x11/fuzz_test.go
Labels: database-access, size/md

#29931 Update Rust to 1.71.0
  Makefile
  build.assets/Makefile
Labels: size/sm

#29949 [v11] fix: Bump libcrypto version in pkgconfig files
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport, size/sm

#29947 [v13] fix: Bump libcrypto version in pkgconfig files
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport, size/sm

#29948 [v12] fix: Bump libcrypto version in pkgconfig files
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport, size/sm

#29943 [v13] terraform-agent-pool: Fix token provisioning, enable HTTP endpoint, add expiry time
  examples/agent-pool-terraform/agent-pool.tf
Labels: backport, size/sm

#29844 Support Kube CustomResources RBAC
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: size/sm

#29481 Fix authorization rules to the Assistant and UserPreferences service
  api/gen/proto/go/userpreferences/v1/userpreferences.pb.go
  api/proto/teleport/userpreferences/v1/userpreferences.proto
  lib/auth/assist/assistv1/service.go
  lib/auth/assist/assistv1/service_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/userpreferences/userpreferencesv1/service.go
  lib/auth/userpreferences/userpreferencesv1/service_test.go
  lib/authz/permissions.go
  lib/services/local/userpreferences.go
  lib/services/local/userpreferences_test.go
  lib/services/userpreferences.go
  lib/web/assistant_test.go
  lib/web/command_test.go
  lib/web/userpreferences.go
Labels: size/lg, backport/branch/v12, backport/branch/v13

#29765 Move client functionality into client
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
Labels: rdp, desktop-access, size/sm

#29951 [v13] Use enum to describe IAMPolicyStatus instead of a bool #29721
  api/proto/teleport/legacy/types/types.proto
  api/types/database.go
  api/types/database_test.go
  api/types/types.pb.go
  lib/srv/db/cloud/iam.go
  lib/srv/db/cloud/iam_test.go
  lib/web/apiserver_test.go
  tool/tsh/tsh_test.go
Labels: tsh, database-access, backport, size/md

#29956 [v13] Hardware Key Support docs - additional troubleshooting info
  docs/pages/access-controls/guides/hardware-key-support.mdx
  lib/client/api.go
Labels: documentation, backport, size/sm

#29958 [v12] Hardware Key Support docs - additional troubleshooting info
  docs/pages/access-controls/guides/hardware-key-support.mdx
  lib/client/api.go
Labels: documentation, backport, size/sm

#29874 Update testplan with GCP/Azure auto-discovery
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#29959 [v11] Hardware Key Support docs - additional troubleshooting info
  docs/pages/access-controls/guides/hardware-key-support.mdx
  lib/client/api.go
Labels: documentation, backport, size/sm

#29799 Remove returning Teleport version on dialing a host
  api/utils/sshutils/conn.go
  integration/integration_test.go
  lib/proxy/router.go
  lib/proxy/router_test.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnel/transport.go
  lib/reversetunnelclient/api.go
  lib/srv/regular/proxy.go
  lib/srv/transport/transportv1/transport.go
  lib/srv/transport/transportv1/transport_test.go
  lib/utils/ver.go
  lib/web/terminal.go
Labels: refactoring, size/sm, ip-pinning

#29562 Create automatic resource access requests on `tsh kube login`
  tool/tsh/common/kube.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/tsh.go
Labels: tsh, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29479 Connect My Computer: Join cluster
  jest.config.js
  web/packages/teleterm/package.json
  web/packages/teleterm/src/mainProcess/agentDownloader/agentDownloader.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.test.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentTestProcess.mjs
  web/packages/teleterm/src/mainProcess/agentRunner/index.ts
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.test.ts
  web/packages/teleterm/src/mainProcess/createAgentConfigFile.ts
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/mainProcessClient.ts
  web/packages/teleterm/src/mainProcess/runtimeSettings.ts
  web/packages/teleterm/src/mainProcess/terminateWithTimeout/index.ts
  web/packages/teleterm/src/mainProcess/terminateWithTimeout/terminateWithTimeout.test.ts
  web/packages/teleterm/src/mainProcess/terminateWithTimeout/terminateWithTimeout.ts
  web/packages/teleterm/src/mainProcess/terminateWithTimeout/testProcess.mjs
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerSetup/DocumentConnectMyComputerSetup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.test.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/index.ts
  web/packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
  web/packages/teleterm/src/ui/services/connectMyComputer/connectMyComputerService.ts
  yarn.lock
Labels: ui, size/lg

#29894 Add a DynamoDB billing mode changes to the changelog
  CHANGELOG.md
Labels: size/sm

#29971 Register join metrics into prometheus default registry
  lib/kube/proxy/prometheus.go
Labels: kubernetes-access, size/sm

#29965 pgbk: ensure TOASTed values in the change feed
  lib/backend/pgbk/pgbk.go
  lib/backend/test/suite.go
Labels: size/sm, backport/branch/v13

#29724 [WebDiscover] Determine if IAM policy setup step can be skipped
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.test.tsx
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/Discover/Database/IamPolicy/IamPolicy.tsx
  web/packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.story.tsx
  web/packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.tsx
  web/packages/teleport/src/Discover/Database/common.tsx
  web/packages/teleport/src/Discover/Kubernetes/SetupAccess/SetupAccess.story.tsx
  web/packages/teleport/src/Discover/Server/SetupAccess/SetupAccess.story.tsx
  web/packages/teleport/src/Discover/Shared/ActionButtons.tsx
  web/packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.ts
  web/packages/teleport/src/services/databases/databases.test.ts
  web/packages/teleport/src/services/databases/makeDatabase.ts
  web/packages/teleport/src/services/databases/types.ts
Labels: ui, size/md, backport/branch/v13

#29717 Tighten discovery service permissions
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/authz/permissions.go
  lib/srv/discovery/discovery_test.go
Labels: security, kubernetes-access, database-access, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13, changelog

#28629 [v13] WebDiscover: Partially implement auto deploy database server view
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.story.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/index.tsx
  web/packages/teleport/src/Discover/Database/DeployService/DeployService.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/ManualDeploy.story.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/ManualDeploy.tsx
  web/packages/teleport/src/Discover/Database/DeployService/ManualDeploy/index.ts
  web/packages/teleport/src/Discover/Database/DeployService/index.ts
  web/packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.story.tsx
  web/packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.test.ts
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.story.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.test.tsx
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Discover/Database/common.test.ts
  web/packages/teleport/src/Discover/Database/common.tsx
  web/packages/teleport/src/Discover/Database/index.tsx
  web/packages/teleport/src/Discover/Database/util.ts
  web/packages/teleport/src/Discover/Shared/ActionButtons.tsx
  web/packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
  web/packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.ts
  web/packages/teleport/src/Discover/Shared/index.ts
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/databases/databases.test.ts
  web/packages/teleport/src/services/databases/makeDatabase.ts
  web/packages/teleport/src/services/databases/types.ts
  web/packages/teleport/src/services/integrations/integrations.ts
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/md

#29970 [v13] Add Prometheus metrics to Kubernetes Access
  api/observability/tracing/http/http.go
  docs/cspell.json
  docs/pages/includes/metrics.mdx
  lib/kube/proxy/auth.go
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/kube_creds.go
  lib/kube/proxy/prometheus.go
  lib/kube/proxy/transport.go
  lib/kube/proxy/watcher.go
Labels: documentation, kubernetes-access, backport, size/md

#27588 RFD 131: Administrative Actions MFA
  rfd/0131-adminitrative-actions-mfa.md
Labels: rfd, size/md

#29982 Backport #29003 to branch/v13
  examples/teleport-usage/README.md
  examples/teleport-usage/main.go
  examples/teleport-usage/main_test.go
Labels: backport, size/sm

#29981 Backport #29003 to branch/v12
  examples/teleport-usage/README.md
  examples/teleport-usage/main.go
  examples/teleport-usage/main_test.go
Labels: backport, size/sm

#29986 Release 12.4.13
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/admin_clusterrolebinding_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, size/sm

#29991 [v13] Added Prometheus counter for created access requests
  lib/auth/auth.go
  metrics.go
Labels: backport, size/sm, changelog

#29922 Ensure Helm deployment guides match the sidebar
  docs/pages/deploy-a-cluster/helm-deployments.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29993 Fix `tool.tsh.common.TestKube/list_kube` flaky test
  tool/tsh/common/proxy_test.go
Labels: tsh, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29889 [Mattermost] Lax requiring recipients and set raw recipients on cfg init
  api/types/plugin.go
  api/types/plugin_test.go
  integrations/access/common/config.go
  integrations/access/mattermost/bot.go
  integrations/access/mattermost/config.go
  integrations/access/mattermost/mattermost_test.go
Labels: size/sm, backport/branch/v13

#30000 [v11] Fix `tool.tsh.common.TestKube/list_kube` flaky test
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#29998 [v13] Fix `tool.tsh.common.TestKube/list_kube` flaky test
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#29999 [v12] Fix `tool.tsh.common.TestKube/list_kube` flaky test
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm

#30009 [v13] [Mattermost] Lax requiring recipients and set raw recipients on cfg init
  api/types/plugin.go
  api/types/plugin_test.go
  integrations/access/common/config.go
  integrations/access/mattermost/bot.go
  integrations/access/mattermost/config.go
  integrations/access/mattermost/mattermost_test.go
Labels: backport, size/sm

#29757 Feature recommendation
  web/packages/teleport/src/Navigation/NavigationItem.test.tsx
  web/packages/teleport/src/Navigation/NavigationItem.tsx
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/services/localStorage/localStorage.ts
  web/packages/teleport/src/services/localStorage/types.ts
  web/packages/teleport/src/stores/storeNav.ts
  web/packages/teleport/src/types.ts
Labels: ui, size/md, backport/branch/v13

#30014 Release 12.4.14
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, size/sm

#30016 Release 13.3.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  docs/cspell.json
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm

#29969 Icons adjustments
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsIcon/ConnectionsIcon.tsx
Labels: ui, size/sm

#29967 Stop piping child process output into logger only after close
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/services/logger/loggerService.ts
  web/packages/teleterm/src/services/logger/types.ts
Labels: ui, teleport-connect, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#30024 Deflake `TestListKube`
  tool/tsh/common/access_request.go
  tool/tsh/common/kube.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/tsh.go
Labels: tsh, size/sm, backport/branch/v12, backport/branch/v13

#29729 Changes to the Jira plugin required to run as a hosted integration
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/plugin_test.go
  api/types/types.pb.go
  integrations/access/common/teleport/client.go
  integrations/access/jira/app.go
  integrations/access/jira/client.go
  integrations/access/jira/config.go
  integrations/access/jira/jira_test.go
  integrations/lib/addr.go
Labels: size/md, backport/branch/v13

#29995 [v12] Tighten discovery service permissions
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/authz/permissions.go
  lib/srv/discovery/discovery_test.go
Labels: backport, size/md, discovery

#29864 Refactor database `DiscoveryResourceChecker`
  lib/srv/db/access_test.go
  lib/srv/db/cloud/resource_checker.go
  lib/srv/db/cloud/resource_checker_credentials.go
  lib/srv/db/cloud/resource_checker_test.go
  lib/srv/db/server.go
  lib/srv/db/watcher.go
  lib/srv/db/watcher_test.go
Labels: database-access, size/md

#30002 fix: Drop subtests from `addOneOfEachMFADevice` helper
  lib/auth/grpcserver_test.go
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#30004 [v12] Added IP pinning support for TLS routing behind ALB mode
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/httplib/httplib.go
  lib/limiter/limiter.go
  lib/limiter/limiter_test.go
  lib/reversetunnel/transport.go
  lib/service/cfg.go
  lib/service/service.go
  lib/utils/conn.go
  lib/utils/conn_test.go
  lib/utils/http.go
  lib/utils/http_test.go
  lib/utils/net.go
  lib/web/addr.go
  lib/web/addr_test.go
  lib/web/apiserver.go
  lib/web/conn_upgrade_test.go
Labels: backport, tls-routing, size/md, ip-pinning, changelog

#30038 [v11] fix: Drop subtests from `addOneOfEachMFADevice` helper
  lib/auth/grpcserver_test.go
Labels: backport, size/sm

#30037 [v12] fix: Drop subtests from `addOneOfEachMFADevice` helper
  lib/auth/grpcserver_test.go
Labels: backport, size/sm

#29997 chore: Bump Buf to v1.25.1
  build.assets/Makefile
Labels: backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#30036 [v13] fix: Drop subtests from `addOneOfEachMFADevice` helper
  lib/auth/grpcserver_test.go
Labels: backport, size/sm

#29983 [v13] add oss support for existing user onboard survey (#29535)
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Welcome/NewCredentials/NewCredentials.tsx
  web/packages/teleport/src/Welcome/NewCredentials/types.ts
Labels: ui, backport, size/sm

#29961 [v13] Fix authorization rules to the Assistant and UserPreferences service
  api/gen/proto/go/userpreferences/v1/userpreferences.pb.go
  api/proto/teleport/userpreferences/v1/userpreferences.proto
  lib/auth/assist/assistv1/service.go
  lib/auth/assist/assistv1/service_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/userpreferences/userpreferencesv1/service.go
  lib/auth/userpreferences/userpreferencesv1/service_test.go
  lib/authz/permissions.go
  lib/services/local/userpreferences.go
  lib/services/local/userpreferences_test.go
  lib/services/userpreferences.go
  lib/web/assistant_test.go
  lib/web/command_test.go
  lib/web/userpreferences.go
Labels: backport, size/lg

#30028 Improve backend `testKeepAlive`
  lib/backend/test/suite.go
Labels: size/sm, backport/branch/v12, backport/branch/v13

#30048 [v11] chore: Bump Buf to v1.25.1
  build.assets/Makefile
Labels: backport, size/sm

#30046 [v13] chore: Bump Buf to v1.25.1
  build.assets/Makefile
Labels: backport, size/sm

#30027 [v11] Stop piping child process output into logger only after close
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/services/logger/loggerService.ts
  web/packages/teleterm/src/services/logger/types.ts
Labels: ui, backport, size/sm

#30051 Release 11.3.20
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, size/sm

#30035 AWS configurator support for OpenSearch
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/configurators/common.go
  tool/teleport/common/configurator.go
Labels: database-access, size/md, backport/branch/v13

#30053 [v13] Improve backend `testKeepAlive`
  lib/backend/test/suite.go
Labels: backport, size/sm

#29887 handle discovery renaming when listing resource in `tctl` text format
  lib/asciitable/table.go
  tool/tctl/common/collection.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/db_command.go
  tool/tctl/common/kube_command.go
Labels: tctl, size/md, backport/branch/v13

#29293 docs: document browser env var for tsh
  docs/pages/reference/cli.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#28500 [Docs] Fix the table of contents and edit content
  docs/img/application-access/grafana-tutorial.png
  docs/img/application-access/grafana_cloud.png
  docs/img/application-access/grafana_selfhosted.png
  docs/pages/application-access/getting-started.mdx
  docs/pages/includes/dns-app-access.mdx
  docs/pages/includes/permission-warning.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#30061 [v11] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#30058 [v12] docs: document browser env var for tsh
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#30062 [v12] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#30057 [v13] docs: document browser env var for tsh
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#30059 [v11] docs: document browser env var for tsh
  docs/pages/reference/cli.mdx
Labels: documentation, backport, size/sm

#30015 [v13] Feature recommendation
  web/packages/teleport/src/Navigation/NavigationItem.test.tsx
  web/packages/teleport/src/Navigation/NavigationItem.tsx
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/services/localStorage/localStorage.ts
  web/packages/teleport/src/services/localStorage/types.ts
  web/packages/teleport/src/stores/storeNav.ts
  web/packages/teleport/src/types.ts
Labels: ui, backport, size/md

#30063 Disable MongoDB fuzzing in oss-fuzz
  fuzz/oss-fuzz-build.sh
Labels: size/sm

#30047 [v12] chore: Bump Buf to v1.25.1
  build.assets/Makefile
Labels: backport, size/sm

#30064 chore: Bump gravitational/trace to v1.3.0
  api/client/client.go
  api/client/inventory.go
  api/client/inventory_test.go
  api/go.mod
  api/go.sum
  api/internalutils/stream/stream.go
  assets/backport/go.mod
  assets/backport/go.sum
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  go.mod
  go.sum
  integration/integration_test.go
  integrations/kube-agent-updater/go.mod
  integrations/kube-agent-updater/go.sum
  integrations/lib/watcherjob/watcherjob.go
  lib/auth/grpcserver.go
  lib/events/session_writer.go
  lib/inventory/inventory.go
  lib/srv/sess.go
  lib/sshutils/server.go
  lib/teleterm/gatewaytest/helpers.go
  lib/utils/errors.go
Labels: size/sm

#30052 [v13] Add GCP auto-discovery docs
  docs/config.json
  docs/img/server-access/guides/gcp/assign-role-to-service-account@2x.png
  docs/img/server-access/guides/gcp/create-service-account@2x.png
  docs/img/server-access/guides/gcp/custom-role@2x.png
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/gcp-discovery.mdx
Labels: documentation, backport, size/md

#30042 List supported URI schemas in the audit error messages
  lib/service/service.go
Labels: size/sm, backport/branch/v13

#30011 Adjust max session duration in web sessions
  lib/auth/auth.go
  lib/auth/tls_test.go
Labels: size/md, backport/branch/v13

#29770 remove origin in cloud converters
  lib/auth/auth_with_roles_test.go
  lib/integrations/awsoidc/listdatabases_test.go
  lib/services/database.go
  lib/services/database_test.go
  lib/services/kubernetes.go
  lib/services/kubernetes_test.go
  lib/srv/discovery/common/watcher.go
  lib/srv/discovery/discovery_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, discovery

#30040 [v13] Changes to the Jira plugin required to run as a hosted integration
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/plugin_test.go
  api/types/types.pb.go
  integrations/access/common/teleport/client.go
  integrations/access/jira/app.go
  integrations/access/jira/client.go
  integrations/access/jira/config.go
  integrations/access/jira/jira_test.go
  integrations/lib/addr.go
Labels: backport, size/md

#29996 [v11] Tighten discovery service permissions
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver.go
  lib/auth/permissions.go
Labels: backport, size/sm, discovery

#29871 `tsh --ttl` takes an integer
  docs/pages/includes/plugins/identity-export.mdx
Labels: documentation, backport/branch/v11, size/sm, backport/branch/v12, backport/branch/v13

#29860 Remove note about canceled requests not being supported
  docs/pages/database-access/faq.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13

#28448 Update tctl help output
  tool/tctl/common/token_command.go
Labels: tctl, size/sm

#29627 Athena: migration tool with sorting events
  examples/dynamoathenamigration/cmd/main.go
  examples/dynamoathenamigration/migration.go
  examples/dynamoathenamigration/migration_test.go
Labels: size/md

#28150 Add metrics for database service
  lib/srv/db/access_test.go
  lib/srv/db/cassandra/engine.go
  lib/srv/db/common/audit.go
  lib/srv/db/common/auth.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/engines_test.go
  lib/srv/db/common/reporting.go
  lib/srv/db/dynamodb/engine.go
  lib/srv/db/elasticsearch/engine.go
  lib/srv/db/mongodb/engine.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/opensearch/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/proxyserver.go
  lib/srv/db/redis/engine.go
  lib/srv/db/server.go
  lib/srv/db/snowflake/engine.go
  lib/srv/db/sqlserver/engine.go
  lib/srv/db/sqlserver/engine_test.go
Labels: database-access, size/md, changelog

#29859 kube: Full namespace jail for custom resources
  integration/helpers/kube.go
  integration/proxy/proxy_helpers.go
  integration/proxy/proxy_test.go
  integration/proxy/teleterm_test.go
  lib/kube/grpc/grpc_test.go
  lib/kube/proxy/auth.go
  lib/kube/proxy/auth_test.go
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/resource_deletecollection.go
  lib/kube/proxy/resource_filters.go
  lib/kube/proxy/resource_filters_test.go
  lib/kube/proxy/resource_list.go
  lib/kube/proxy/resource_rbac_test.go
  lib/kube/proxy/scheme.go
  lib/kube/proxy/self_subject_reviews.go
  lib/kube/proxy/self_subject_reviews_test.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/url.go
  lib/kube/proxy/url_test.go
  lib/kube/proxy/watcher_test.go
Labels: kubernetes-access, size/lg

#30060 Fix flaky test `TestTeleterm/Test_headless_watcher`
  integration/helpers/internal.go
  integration/teleterm_test.go
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/daemon/daemon_headless.go
Labels: size/sm

#30128 [buddy] Add docs for the new Slack helm chart values
  docs/pages/reference/helm-reference/teleport-plugin-slack.mdx
Labels: documentation, size/sm, backport/branch/v13

#30121 Add DB metrics to the reference.
  docs/pages/includes/metrics.mdx
Labels: documentation, size/sm, no-changelog

#30127 collections.go: Fix Memory Aliasing in `getAll`
  lib/cache/collections.go
Labels: size/sm

#29406 Add in paginated access list endpoint.
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  lib/services/access_list.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/sm, backport/branch/v13

#30125 [buddy] Add imagePullSecrets to predeploy tests
  examples/chart/teleport-cluster/templates/auth/predeploy_job.yaml
  examples/chart/teleport-cluster/templates/proxy/predeploy_job.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/predeploy_test.yaml.snap
  examples/chart/teleport-cluster/tests/predeploy_test.yaml
Labels: bug, helm, size/sm, backport/branch/v12, backport/branch/v13, changelog

#30033 Connect My Computer: Add usage events
  gen/proto/go/prehog/v1alpha/connect.pb.go
  gen/proto/js/prehog/v1alpha/connect_pb.d.ts
  gen/proto/js/prehog/v1alpha/connect_pb.js
  lib/usagereporter/daemon/usagereporter.go
  proto/prehog/v1alpha/connect.proto
  web/packages/teleterm/src/services/tshd/mapUsageEvent.ts
  web/packages/teleterm/src/ui/services/usage/usageService.ts
Labels: ui, size/sm

#30130 [v13] [buddy] Add docs for the new Slack helm chart values
  docs/pages/reference/helm-reference/teleport-plugin-slack.mdx
Labels: documentation, backport, size/sm

#30135 Fix headless watcher goroutine leak in tests
  lib/auth/helpers.go
Labels: size/sm, backport/branch/v13

#30138 [v13] Fix headless watcher goroutine leak in tests
  lib/auth/helpers.go
Labels: backport, size/sm

#30007 [v13] Ensure Helm deployment guides match the sidebar
  docs/pages/deploy-a-cluster/helm-deployments.mdx
Labels: documentation, backport, size/sm

#30005 [v11] Ensure Helm deployment guides match the sidebar
  docs/pages/deploy-a-cluster/helm-deployments.mdx
Labels: documentation, backport, size/sm
