Repository gravitational/teleport, pull requests merged in 2023-12, with the labels that each got.

#35104 [v12] Continue completing uploads on not found errors
  lib/events/complete.go
Labels: audit-log, backport, size/sm

#35233 Remove extra characters from discovery script.
  docs/pages/server-access/guides/gcp-discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#35218 Release 14.2.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/changelog.py
  build.assets/changelog.sh
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm, no-changelog

#35190 [v12] Run Storybook smoke tests in CI
  .github/workflows/lint-ui.yaml
  package.json
  web/.storybook/main.js
  web/.storybook/mocks/README.md
  web/.storybook/mocks/e-teleterm/ui/DocumentAccessRequests/DocumentAccessRequests.tsx
Labels: ui, backport, size/sm, no-changelog

#35191 [v13] Run Storybook smoke tests in CI
  .github/workflows/lint-ui.yaml
  package.json
  web/.storybook/main.js
  web/.storybook/mocks/README.md
  web/.storybook/mocks/e-teleterm/ui/DocumentAccessRequests/DocumentAccessRequests.tsx
Labels: ui, backport, size/sm, no-changelog

#35203 [v14] [docs] clarify database name override label
  docs/pages/database-access/guides/aws-discovery.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-aws.mdx
  docs/pages/database-access/guides/redshift-serverless.mdx
  docs/pages/database-access/reference/labels.mdx
Labels: documentation, backport, size/sm, no-changelog

#35254 [v12] docs: clarify app access header rewrites
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm, no-changelog

#35253 [v13] docs: clarify app access header rewrites
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm, no-changelog

#35252 [v14] docs: clarify app access header rewrites
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm, no-changelog

#35256 [v13] Adjust GetAccessRequest to only require DynamicAccessCore.
  lib/services/access_request.go
Labels: backport, size/sm, no-changelog

#35172 Web: Audit use of `isUsageBasedBilling` flag
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles.tsx
  web/packages/teleport/src/Sessions/Sessions.story.test.tsx
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Sessions/useSessions.ts
  web/packages/teleport/src/Support/Support.story.test.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.test.tsx
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/sales/index.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#35263 [v13] Clarify error message for host user lookup timeouts
  api/utils/user.go
Labels: backport, size/sm, no-changelog

#35237 [v13] Correctly clone RoleV6 when downgrading
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
Labels: backport, size/sm

#35204 Support piecemeal names and descriptions for Okta apps and user groups.
  api/types/constants.go
  api/types/resource.go
  api/types/resource_test.go
  lib/web/ui/app.go
  lib/web/ui/user_groups.go
  web/packages/shared/components/UnifiedResources/shared/viewItemsFactory.ts
  web/packages/shared/components/UnifiedResources/types.ts
Labels: ui, size/sm, backport/branch/v14

#35234 [v14] Add ProductType to features and add IGS checks with access request verify limit
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/types/license.go
  lib/auth/auth.go
  lib/auth/usage_test.go
  lib/modules/modules.go
Labels: backport, size/md, no-changelog

#35017 [v12] docs: add troubleshooting operator ns
  docs/pages/management/guides/teleport-operator.mdx
Labels: documentation, backport, size/sm, no-changelog

#35270 README: update to AGPL 3.0
  README.md
Labels: size/sm, no-changelog

#35267 Fixed "fix-license" makefile target for AGPL-v3 change
  Makefile
Labels: size/sm, no-changelog

#35184 Clean up debug logs
  lib/auth/grpcserver.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35242 [v12] build: Copy release artifacts to release directory
  Makefile
Labels: backport, size/sm, no-changelog

#35261 [v14] Web: Audit use of `isUsageBasedBilling` flag
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles.tsx
  web/packages/teleport/src/Sessions/Sessions.story.test.tsx
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Sessions/useSessions.ts
  web/packages/teleport/src/Support/Support.story.test.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.test.tsx
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/sales/index.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, size/sm, no-changelog

#35272 reduce variable duration test flake
  lib/utils/interval/multi_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#35264 [v12] Clarify error message for host user lookup timeouts
  api/utils/user.go
Labels: backport, size/sm, no-changelog

#35262 [v14] Clarify error message for host user lookup timeouts
  api/utils/user.go
Labels: backport, size/sm, no-changelog

#34135 Teleport Connect MFA prompt
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service_grpc.pb.go
  gen/proto/js/teleport/lib/teleterm/v1/tshd_events_service_grpc_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/tshd_events_service_grpc_pb.js
  gen/proto/js/teleport/lib/teleterm/v1/tshd_events_service_pb.d.ts
  gen/proto/js/teleport/lib/teleterm/v1/tshd_events_service_pb.js
  lib/client/api.go
  lib/client/mfa.go
  lib/client/mfa/cli.go
  lib/client/mfa/prompt.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/mfaprompt.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/services/tshdEvents/index.ts
Labels: ui, tsh, tctl, desktop-access, size/md, no-changelog

#33717 Database Automatic User Provisioning support for self-hosted MongoDB
  api/types/database.go
  lib/srv/db/access_test.go
  lib/srv/db/autousers_test.go
  lib/srv/db/mongodb/autousers.go
  lib/srv/db/mongodb/autousers_admin.go
  lib/srv/db/mongodb/autousers_admin_test.go
  lib/srv/db/mongodb/autousers_test.go
  lib/srv/db/mongodb/connect.go
  lib/srv/db/mongodb/engine.go
  lib/srv/db/mongodb/test.go
Labels: database-access, db/mongo, size/lg

#35247 [v14] Break coupling of auth.ServerWithRoles with auth.ClientI #35068
  lib/auth/apiserver.go
  lib/auth/apiserver_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/utils/grpc.go
Labels: backport, size/sm, no-changelog

#35000 TAG: Add protobuf for resource definition for Kube, App, DB and Windows
  gen/proto/go/accessgraph/v1alpha/resources.pb.go
  proto/accessgraph/v1alpha/resources.proto
Labels: size/sm, backport/branch/v14, no-changelog

#35129 [v14] Strip context at API client for EmitAuditEvent
  api/client/client.go
  api/internal/context121/go121_context_compat.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/events/athena/athena.go
  lib/events/athena/publisher.go
  lib/events/auditlog.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/emitter.go
  lib/events/pgevents/pgevents.go
  lib/events/usageevents/usageevents.go
  lib/internal/context121/go121_context_compat.go
Labels: no-changelog

#35103 [v13] Continue completing uploads on not found errors
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/uploader.go
  lib/events/stream_test.go
Labels: audit-log, backport, size/sm

#35207 [v14] Make Opsgenie plugin update statussink on healthcheck
  integrations/access/opsgenie/client.go
Labels: backport, size/sm, no-changelog

#33439 RFD 0150 - SSH connection resumption
  rfd/0150-ssh-connection-resumption.md
Labels: rfd, size/md, no-changelog

#35289 charts/kube-agent: configurable podSecurityContext
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#35283 fix: External Audit Storage bootstrap in us-east-1
  lib/integrations/externalauditstorage/bootstrap.go
  lib/integrations/externalauditstorage/bootstrap_test.go
Labels: size/sm, backport/branch/v14

#35274 feat!: Apply role device mode to App Access
  lib/auth/helpers.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/devicetrust/authz/authz.go
  lib/devicetrust/authz/authz_test.go
  lib/service/desktop.go
  lib/service/service.go
  lib/services/role.go
  lib/srv/app/server.go
  lib/srv/app/server_test.go
Labels: application-access, size/md

#35293 [v13] [docs] AWS management console duration troubleshoot, DB fixes
  docs/cspell.json
  docs/pages/application-access/cloud-apis/aws-console.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/snowflake.mdx
Labels: documentation, backport, size/sm, no-changelog

#35294 [v12] [docs] AWS management console duration troubleshoot, DB fixes
  docs/cspell.json
  docs/pages/application-access/cloud-apis/aws-console.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/snowflake.mdx
Labels: documentation, backport, size/sm, no-changelog

#35311 [v14] TAG: Add protobuf for resource definition for Kube, App, DB and Windows
  gen/proto/go/accessgraph/v1alpha/resources.pb.go
  proto/accessgraph/v1alpha/resources.proto
Labels: backport, size/sm, no-changelog

#35292 [v14] [docs] AWS management console duration troubleshoot, DB fixes
  docs/cspell.json
  docs/pages/application-access/cloud-apis/aws-console.mdx
  docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
  docs/pages/database-access/guides/mongodb-atlas.mdx
  docs/pages/database-access/guides/mongodb-self-hosted.mdx
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/mysql-self-hosted.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/postgres-self-hosted.mdx
  docs/pages/database-access/guides/snowflake.mdx
Labels: documentation, backport, size/sm, no-changelog

#35315 [v14] Restore `teleport-spacelift-runner` build process (#35122)
  .drone.yml
  dronegen/promote.go
  dronegen/tag.go
Labels: backport, size/md, no-changelog

#35312 Add `cluster_auth_preferences` to shortcuts for `cluster_auth_preference`
  lib/services/resource.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#35324 [v14] fix: External Audit Storage bootstrap in us-east-1
  lib/integrations/externalauditstorage/bootstrap.go
  lib/integrations/externalauditstorage/bootstrap_test.go
Labels: backport, size/sm

#35143 Update diagrams in the docs
  docs/img/agent-pool-diagram.png
  docs/img/application-access/grafana-tutorial.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.svg
  docs/img/architecture/proxy-tunnel@1.2x.png
  docs/img/architecture/proxy-tunnel@1.2x.svg
  docs/img/architecture/proxy-web-to-resource@1.2x.png
  docs/img/architecture/proxy-web-to-resource@1.2x.svg
  docs/img/database-access/guides/azure/redis-cloud.png
  docs/img/database-access/guides/azure/redis-self-hosted.png
  docs/img/database-access/sql-server-ad-1.png
  docs/img/database-access/sql-server-ad-2.png
  docs/img/doc-submodules.png
  docs/img/dynamic-resources.png
  docs/img/enterprise/plugins/discord.png
  docs/img/enterprise/plugins/email.png
  docs/img/enterprise/plugins/fluentd-diagram.png
  docs/img/enterprise/plugins/mattermost/diagram.png
  docs/img/enterprise/plugins/msteams.png
  docs/img/enterprise/plugins/pagerduty/diagram.png
  docs/img/enterprise/plugins/slack/diagram.png
  docs/img/ha-diagram.png
  docs/img/linux-server-diagram.png
  docs/img/management/datadog-diagram.png
  docs/img/okta-diagram.png
  docs/img/spacelift.png
  docs/img/team-diagram.png
  docs/img/tf-agent-diagram.png
  docs/img/trusted-clusters/simplified-trusted-cluster-role-mapping.png
  docs/img/trusted-clusters/simplified-trusted-cluster.png
  docs/img/trusted-clusters/trusted-cluster-service-interaction.png
  docs/pages/access-controls/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/agents/deploy-agents-terraform.mdx
  docs/pages/agents/introduction.mdx
  docs/pages/application-access/okta/architecture.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/choose-an-edition/teleport-team.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/contributing/documentation/reviewing-docs.mdx
  docs/pages/database-access/guides/sql-server-ad-pkinit.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/deploy-a-cluster/high-availability.mdx
  docs/pages/includes/plugins/diagram.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/dynamic-resources/spacelift.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35338 Add Apache-2.0 license to `api/`
  api/LICENSE
Labels: size/md, no-changelog

#35304 Default desktop port to 3389 if not specified
  lib/srv/desktop/windows_server.go
Labels: desktop-access, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#35107 Adds Membership field for AccessListMember values
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/member_test.go
  api/types/accesslist/member.go
  api/types/accesslist/member_test.go
  lib/services/access_list_test.go
Labels: size/sm, no-changelog

#34746 `ServerDriveQueryDirectoryRequest` and `SharedDirectoryListRequest/Response`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/md, no-changelog

#35345 [v12] Default desktop port to 3389 if not specified
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/sm

#35344 [v13] Default desktop port to 3389 if not specified
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/sm

#34871 `ServerDriveQueryVolumeInformationRequest` and `ClientDriveQueryVolumeInformationResponse`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
  web/packages/teleport/src/ironrdp/src/lib.rs
Labels: ui, rdp, desktop-access, size/md, no-changelog

#34898 `DeviceControlRequest`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/sm, no-changelog

#34914 `Read`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/md, no-changelog

#34919 `Write`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/md, no-changelog

#35092 `SetInformation`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/md, no-changelog

#35146 `LockControl`
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/sm, no-changelog

#35306 Stack pr feedback and other cleanup
  build.assets/versions.mk
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/ssl.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
Labels: rdp, desktop-access, size/sm, no-changelog

#34999 Metrics: add running services metric
  lib/service/supervisor.go
  metrics.go
Labels: discover, size/sm, backport/branch/v14

#35351 Remove mentions of the Team plan from Connect My Computer RFD
  rfd/0133-connect-my-computer.md
Labels: rfd, size/sm, no-changelog

#35213 External Audit Storage: add variable to show or hide CTA
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#35128 [v13] Strip context at API client for EmitAuditEvent
  api/client/client.go
  api/internal/context121/go121_context_compat.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/events/athena/athena.go
  lib/events/athena/publisher.go
  lib/events/auditlog.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/emitter.go
  lib/events/pgevents/pgevents.go
  lib/events/usageevents/usageevents.go
  lib/internal/context121/go121_context_compat.go
Labels: audit-log, backport, size/sm, no-changelog

#35320 [v14] charts/kube-agent: configurable podSecurityContext
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/sm

#34874 [v14] Fixes crash when writing kubeconfig with `tctl auth sign --tar`
  lib/client/identityfile/identity.go
  lib/client/identityfile/identity_test.go
  lib/client/identityfile/inmemory_config_writer.go
  lib/kube/kubeconfig/kubeconfig.go
  lib/tbot/config/template.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/tarwriter.go
  tool/tctl/common/tarwriter_test.go
Labels: kubernetes-access, tctl, backport, machine-id, size/md

#35349 [v14] Adds Membership field for AccessListMember values
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/member_test.go
  api/types/accesslist/member.go
  api/types/accesslist/member_test.go
  lib/services/access_list_test.go
Labels: backport, size/md, no-changelog

#35313 Always use fresh state in `useKeyBasedPagination.fetch`
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
  web/packages/shared/hooks/useInfiniteScroll/useKeyBasedPagination.test.ts
  web/packages/shared/hooks/useInfiniteScroll/useKeyBasedPagination.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog

#35332 [v13] Always prefer multiplex port if Kube Proxy endpoint is specified
  lib/client/api.go
  tool/tsh/kubectl.go
Labels: tsh, backport, size/sm, no-changelog

#35333 [v14] Always prefer multiplex port if Kube Proxy endpoint is specified
  lib/client/api.go
  tool/tsh/common/kubectl.go
Labels: tsh, backport, size/sm, no-changelog

#35321 [v13] charts/kube-agent: configurable podSecurityContext
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/sm

#35093 Fix the IsAssistEnabled response
  lib/auth/assist/assistv1/service.go
  lib/web/apiserver_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#35323 [v13] Make EKS fetcher to lazy initialize AWS EKS client
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/fetchers/eks.go
  lib/srv/discovery/fetchers/eks_test.go
Labels: backport, size/md, discovery

#35319 [v14] Make EKS fetcher to lazy initialize AWS EKS client
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/fetchers/eks.go
  lib/srv/discovery/fetchers/eks_test.go
Labels: backport, size/md, discovery

#35357 [v14] External Audit Storage: add variable to show or hide CTA (#35213)
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, size/sm, no-changelog

#35152 ec2discovery: Use a random name for the install script
  lib/configurators/aws/ec2discovery.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35335 Document Device Trust App Access support
  docs/cspell.json
  docs/pages/access-controls/device-trust.mdx
  docs/pages/access-controls/device-trust/device-management.mdx
  docs/pages/access-controls/device-trust/enforcing-device-trust.mdx
  docs/pages/access-controls/device-trust/guide.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
Labels: documentation, size/sm, no-changelog

#34268 Limit access list creation to 1 without IGS flag
  lib/auth/access_request_test.go
  lib/auth/userloginstate/generator_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.tsx
Labels: size/md, no-changelog

#35334 Prevent filesystem race in `make -j test-go test-sh test-api`
  Makefile
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35188 Include upgrader version in metrics and inventory
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/types.pb.go
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
  lib/automaticupgrades/config.go
  lib/inventory/inventory.go
  lib/service/service.go
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, helm, size/md, backport/branch/v13, backport/branch/v14

#35362 [v13] Fix the IsAssistEnabled response
  lib/auth/assist/assistv1/service.go
  lib/web/apiserver_test.go
Labels: backport, size/sm, no-changelog

#35363 [v14] Fix the IsAssistEnabled response
  lib/auth/assist/assistv1/service.go
  lib/web/apiserver_test.go
Labels: backport, size/sm, no-changelog

#35371 [v14] chore: Bump Go to v1.21.5
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#35370 chore: Bump Go to v1.21.5
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: size/sm, no-changelog

#35241 Define access monitoring max range limit field
  api/client/proto/authservice.pb.go
  api/client/webclient/webconfig.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/modules/modules.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/config.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog

#35367 Improve the upload completer's logging
  lib/events/complete.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
Labels: audit-log, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35374 [v13] Update diagrams in the docs
  docs/img/agent-pool-diagram.png
  docs/img/application-access/grafana-tutorial.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.svg
  docs/img/architecture/proxy-tunnel@1.2x.png
  docs/img/architecture/proxy-tunnel@1.2x.svg
  docs/img/architecture/proxy-web-to-resource@1.2x.png
  docs/img/architecture/proxy-web-to-resource@1.2x.svg
  docs/img/database-access/guides/azure/redis-cloud.png
  docs/img/database-access/guides/azure/redis-self-hosted.png
  docs/img/database-access/sql-server-ad-1.png
  docs/img/database-access/sql-server-ad-2.png
  docs/img/doc-submodules.png
  docs/img/dynamic-resources.png
  docs/img/enterprise/plugins/discord.png
  docs/img/enterprise/plugins/email.png
  docs/img/enterprise/plugins/fluentd-diagram.png
  docs/img/enterprise/plugins/mattermost/diagram.png
  docs/img/enterprise/plugins/msteams.png
  docs/img/enterprise/plugins/pagerduty/diagram.png
  docs/img/enterprise/plugins/slack/diagram.png
  docs/img/ha-diagram.png
  docs/img/linux-server-diagram.png
  docs/img/management/datadog-diagram.png
  docs/img/okta-diagram.png
  docs/img/spacelift.png
  docs/img/team-diagram.png
  docs/img/tf-agent-diagram.png
  docs/img/trusted-clusters/simplified-trusted-cluster-role-mapping.png
  docs/img/trusted-clusters/simplified-trusted-cluster.png
  docs/img/trusted-clusters/trusted-cluster-service-interaction.png
  docs/pages/access-controls/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/agents/deploy-agents-terraform.mdx
  docs/pages/agents/introduction.mdx
  docs/pages/application-access/okta/architecture.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/choose-an-edition/teleport-team.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/contributing/documentation/reviewing-docs.mdx
  docs/pages/database-access/guides/sql-server-ad-pkinit.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/deploy-a-cluster/high-availability.mdx
  docs/pages/includes/plugins/diagram.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
Labels: documentation, backport, size/sm

#35375 [v12] Update diagrams in the docs
  docs/img/agent-pool-diagram.png
  docs/img/application-access/grafana-tutorial.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.png
  docs/img/architecture/proxy-iap-to-resource@1.2x.svg
  docs/img/architecture/proxy-tunnel@1.2x.png
  docs/img/architecture/proxy-tunnel@1.2x.svg
  docs/img/architecture/proxy-web-to-resource@1.2x.png
  docs/img/architecture/proxy-web-to-resource@1.2x.svg
  docs/img/database-access/guides/azure/redis-cloud.png
  docs/img/database-access/guides/azure/redis-self-hosted.png
  docs/img/database-access/sql-server-ad-1.png
  docs/img/database-access/sql-server-ad-2.png
  docs/img/doc-submodules.png
  docs/img/dynamic-resources.png
  docs/img/enterprise/plugins/discord.png
  docs/img/enterprise/plugins/email.png
  docs/img/enterprise/plugins/fluentd-diagram.png
  docs/img/enterprise/plugins/mattermost/diagram.png
  docs/img/enterprise/plugins/msteams.png
  docs/img/enterprise/plugins/pagerduty/diagram.png
  docs/img/enterprise/plugins/slack/diagram.png
  docs/img/ha-diagram.png
  docs/img/linux-server-diagram.png
  docs/img/management/datadog-diagram.png
  docs/img/okta-diagram.png
  docs/img/spacelift.png
  docs/img/team-diagram.png
  docs/img/tf-agent-diagram.png
  docs/pages/access-controls/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/architecture/proxy.mdx
  docs/pages/choose-an-edition/teleport-team.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/contributing/documentation/reviewing-docs.mdx
  docs/pages/database-access/guides/sql-server-ad.mdx
  docs/pages/deploy-a-cluster/high-availability.mdx
  docs/pages/includes/plugins/diagram.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
Labels: documentation, backport, size/sm

#35382 [v14] Bump cloud version 14.2.1
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#35388 [v13] Improve the upload completer's logging
  lib/events/complete.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
Labels: audit-log, backport, size/sm, no-changelog

#35387 [v14] Improve the upload completer's logging
  lib/events/complete.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream.go
Labels: audit-log, backport, size/sm, no-changelog

#35384 [v12]: Bump cloud version 14.2.1
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#35383 [v13]: Bump cloud version 14.2.1
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#35373 [v12] chore: Bump Go to v1.20.12
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#35175 Add `insecure-drop` host user creation mode
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  lib/services/access_checker.go
  lib/srv/usermgmt.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#35399 Further enhance uploader logging
  lib/events/s3sessions/s3stream.go
Labels: audit-log, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35406 [v13] Further enhance uploader logging
  lib/events/s3sessions/s3stream.go
Labels: audit-log, backport, size/sm, no-changelog

#35407 [v14] Further enhance uploader logging
  lib/events/s3sessions/s3stream.go
Labels: audit-log, backport, size/sm, no-changelog

#35255 Handle clicking on a label inside `UnifiedResources`
  web/packages/shared/components/UnifiedResources/UnifiedResources.story.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/utils/advancedSearchLabelQuery.ts
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/ServerSideSupportedList.tsx
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#35328 [v13] Add `cluster_auth_preferences` to shortcuts for `cluster_auth_preference`
  lib/services/resource.go
Labels: backport, size/sm

#35410 Revert `onLabelClick` in `UnifiedResources`
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
Labels: ui, size/sm, no-changelog

#35329 [v14] Add `cluster_auth_preferences` to shortcuts for `cluster_auth_preference`
  lib/services/resource.go
Labels: backport, size/sm

#35327 [v12] Add `cluster_auth_preferences` to shortcuts for `cluster_auth_preference`
  lib/services/resource.go
Labels: backport, size/sm

#35216 Machine ID: Add Protos for Bot Resource and CRUD RPCs
  api/gen/proto/go/teleport/machineid/v1/bot.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_service.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_service_grpc.pb.go
  api/proto/teleport/machineid/v1/bot.proto
  api/proto/teleport/machineid/v1/bot_service.proto
Labels: size/md, backport/branch/v14, no-changelog

#35245 Upgrade Vite to v5
  tsconfig.json
  tsconfig.node.json
  web/packages/build/package.json
  web/packages/teleport/vite.config.mts
  yarn.lock
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#35411 Reduce amount of text in Connect My Computer setup & Discover flow
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#34959 integrations/operator: publish `teleport-operator` Helm chart
  .drone.yml
  examples/chart/index.html
  examples/chart/teleport-cluster/README.md
  examples/chart/teleport-cluster/charts/teleport-operator/README.md
Labels: helm, size/sm

#35422 [v14] Reduce amount of text in Connect My Computer setup & Discover flow
  web/packages/teleport/src/Discover/ConnectMyComputer/SetupConnect/SetupConnect.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
Labels: ui, backport, size/sm, no-changelog

#34801 docs: standalone Teleport operator
  build.assets/tooling/cmd/render-helm-ref/main.go
  build.assets/tooling/cmd/render-helm-ref/template.go
  build.assets/tooling/cmd/render-helm-ref/testdata/expected-output.mdx
  build.assets/tooling/cmd/render-helm-ref/testdata/values.yaml
  docs/config.json
  docs/pages/access-controls/login-rules/kubernetes.mdx
  docs/pages/includes/diagnostics/kubernetes-operator-troubleshooting.mdx
  docs/pages/management/dynamic-resources/teleport-operator-helm.mdx
  docs/pages/management/dynamic-resources/teleport-operator-standalone.mdx
  docs/pages/management/dynamic-resources/teleport-operator.mdx
  docs/pages/reference/helm-reference.mdx
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-operator.mdx
  docs/pages/reference/helm-reference/teleport-operator.mdx
  examples/chart/Makefile
  examples/chart/teleport-cluster/charts/teleport-operator/values.yaml
Labels: documentation, size/md, no-changelog

#35385 Simplify Event Handler guides
  docs/pages/includes/plugins/finish-event-handler-config.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/rbac-impersonate-event-handler.mdx
  docs/pages/includes/start-event-handler.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/elastic-stack.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
  docs/pages/management/export-audit-events/splunk.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35369 aws_test.go: Remove UUIDs from document contents since they are random
  lib/configurators/aws/aws_test.go
Labels: size/sm, no-changelog

#35379 [v12] Prevent filesystem race in `make -j test-go test-sh test-api`
  Makefile
Labels: backport, size/sm, no-changelog

#35378 [v13] Prevent filesystem race in `make -j test-go test-sh test-api`
  Makefile
Labels: backport, size/sm, no-changelog

#35364 [v12] ec2discovery: Use a random name for the install script
  lib/configurators/aws/aws_test.go
  lib/configurators/aws/ec2discovery.go
Labels: backport, size/sm, no-changelog

#35377 [v14] Prevent filesystem race in `make -j test-go test-sh test-api`
  Makefile
Labels: backport, size/sm, no-changelog

#35405 [v12] Add insecure drop mode (#35175)
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  lib/services/role.go
  lib/srv/usermgmt.go
Labels: backport, size/sm

#35404 [v13] Add insecure drop mode (#35175)
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  lib/services/access_checker.go
  lib/srv/usermgmt.go
Labels: backport, size/sm

#35403 [v14] Add insecure drop mode (#35175)
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  lib/services/access_checker.go
  lib/srv/usermgmt.go
Labels: backport, size/sm

#35421 [v14] [TAG] Allow the navigation to be hidden, add new icons
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ArrowLeft.tsx
  web/packages/design/src/Icon/Icons/ArrowsIn.tsx
  web/packages/design/src/Icon/Icons/ArrowsOut.tsx
  web/packages/design/src/Icon/Icons/Floppy.tsx
  web/packages/design/src/Icon/assets/ArrowLeft.svg
  web/packages/design/src/Icon/assets/ArrowsIn.svg
  web/packages/design/src/Icon/assets/ArrowsOut.svg
  web/packages/design/src/Icon/assets/Floppy.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/Navigation/Navigation.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/types.ts
Labels: ui, backport, size/md, no-changelog

#35431 Restrict IGS flag check to usage based plans only
  lib/auth/access_request_test.go
  lib/auth/usage_test.go
  lib/modules/modules.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/sm, no-changelog

#35380 [v13] Include upgrader version in metrics and inventory
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/types.pb.go
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
  lib/automaticupgrades/config.go
  lib/inventory/inventory.go
  lib/service/service.go
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, helm, backport, size/md

#35330 Check nil before returning cluster preferences
  lib/web/userpreferences.go
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
Labels: backport-required, size/sm, backport/branch/v14, no-changelog

#35381 [v14] Include upgrader version in metrics and inventory
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/types.pb.go
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
  lib/automaticupgrades/config.go
  lib/inventory/inventory.go
  lib/service/service.go
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, helm, backport, size/md

#35391 [v12] use rds proxy port instead of proxy target port
  docs/pages/database-access/reference/aws.mdx
  lib/cloud/mocks/aws.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy_test.go
Labels: documentation, backport, size/sm, discovery

#35390 [v13] use rds proxy port instead of proxy target port
  docs/pages/database-access/reference/aws.mdx
  lib/cloud/mocks/aws_rds.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/db/cloud/resource_checker_url_aws_test.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy_test.go
Labels: documentation, database-access, backport, size/sm, discovery

#35389 [v14] use rds proxy port instead of proxy target port
  docs/pages/database-access/reference/aws.mdx
  lib/cloud/mocks/aws_rds.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/db/cloud/resource_checker_url_aws_test.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy_test.go
Labels: documentation, database-access, backport, size/sm, discovery

#35341 Audit use of usageBased flag in backend
  lib/integrations/externalauditstorage/configurator.go
  lib/modules/modules.go
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.story.tsx
Labels: ui, rfd, size/sm, backport/branch/v14, no-changelog

#35392 Updates IronRDP to latest
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/piv.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/path.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  lib/srv/desktop/rdp/rdpclient/src/util.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/sm

#35402 fix: trim large events in Athena querier
  lib/events/athena/athena.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
  lib/events/athena/querier.go
  lib/events/athena/querier_test.go
Labels: audit-log, size/md, backport/branch/v14

#35458 Fix panic on nil value in `getPresetRoles()`
  lib/auth/init.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#35463 [v14] Fix panic on nil value in `getPresetRoles()`
  lib/auth/init.go
Labels: backport, size/sm

#35200 Dynamic AccessLists
  api/types/accesslist/accesslist.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: backport/branch/v14, no-changelog

#35414 Show advanced search toggle only when its props are defined in search bar
  web/packages/teleterm/src/ui/Search/pickers/ActionPicker.tsx
Labels: ui, size/sm, no-changelog

#34396 Use the proxy transport for `tsh proxy ssh`
  lib/srv/transport/transportv1/transport.go
  tool/tsh/common/proxy.go
  tool/tsh/common/proxy_test.go
Labels: tsh, size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#35472 [v14] Allow Connect My Computer agent removal if cluster is down
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.test.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
Labels: ui, backport, size/sm, no-changelog

#34935 Machine ID: Spacelift docs
  docs/config.json
  docs/pages/machine-id/deployment.mdx
  docs/pages/machine-id/deployment/spacelift.mdx
  docs/pages/machine-id/faq.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/dynamic-resources/spacelift.mdx
  docs/pages/management/dynamic-resources/terraform-provider.mdx
Labels: documentation, machine-id, size/sm, backport/branch/v14, no-changelog

#35478 Use automatic preset-react runtime in teleterm
  web/packages/teleterm/babel.config.js
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35481 [v12] Use automatic preset-react runtime in teleterm
  web/packages/teleterm/babel.config.js
Labels: ui, backport, size/sm, no-changelog

#35355 Connect kube proxy: Add minor error handling improvements
  lib/teleterm/clusters/cluster_gateways.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/teleterm/gateway/kube.go
  lib/teleterm/gateway/kube_cert_reissuer.go
Labels: size/sm, backport/branch/v14, no-changelog

#34403 Improve the upgrading documentation
  CHANGELOG.md
  docs/config.json
  docs/pages/architecture/agent-update-management.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/includes/compatibility.mdx
  docs/pages/includes/install-linux-oss.mdx
  docs/pages/includes/install-linux-self-hosted.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/server-access/custom-installer.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/helm/includes/helm-repo-add.mdx
  docs/pages/management/admin.mdx
  docs/pages/management/admin/daemon.mdx
  docs/pages/management/admin/upgrading-the-teleport-binary.mdx
  docs/pages/management/operations.mdx
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
  docs/pages/management/operations/self-hosted-automatic-agent-updates.mdx
  docs/pages/management/operations/tls-routing.mdx
  docs/pages/management/operations/upgrading.mdx
  docs/pages/upgrading.mdx
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/overview.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
  docs/pages/upgrading/self-hosted-linux.mdx
Labels: documentation, size/md, backport/branch/v14, no-changelog

#35488 [v12] Increase Table of Contents depth to include Configuration Sections on Config Reference
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm, no-changelog

#35489 [v13] Increase Table of Contents depth to include Configuration Sections on Config Reference
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm, no-changelog

#35490 [v14] Increase Table of Contents depth to include Configuration Sections on Config Reference
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm, no-changelog

#35424 EAS: Disable CTA if user is missing permissions
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.test.tsx
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#35494 [v14] Improve the upgrading documentation
  CHANGELOG.md
  docs/config.json
  docs/pages/architecture/agent-update-management.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/includes/compatibility.mdx
  docs/pages/includes/install-linux-oss.mdx
  docs/pages/includes/install-linux-self-hosted.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/server-access/custom-installer.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/helm/includes/helm-repo-add.mdx
  docs/pages/management/admin.mdx
  docs/pages/management/admin/daemon.mdx
  docs/pages/management/admin/upgrading-the-teleport-binary.mdx
  docs/pages/management/operations.mdx
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
  docs/pages/management/operations/self-hosted-automatic-agent-updates.mdx
  docs/pages/management/operations/tls-routing.mdx
  docs/pages/management/operations/upgrading.mdx
  docs/pages/upgrading.mdx
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/overview.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
  docs/pages/upgrading/self-hosted-linux.mdx
Labels: documentation, backport, size/md, no-changelog

#35154 Add "Access Graph" docs
  docs/config.json
  docs/img/access-graph/allow-action-node.png
  docs/img/access-graph/allow-path.png
  docs/img/access-graph/deny-action-node.png
  docs/img/access-graph/deny-path.png
  docs/img/access-graph/main-view.png
  docs/img/access-graph/resource-group-node.png
  docs/img/access-graph/resource-node.png
  docs/img/access-graph/show-access-path-resource.gif
  docs/img/access-graph/show-access-path.gif
  docs/img/access-graph/temporary-action-node.png
  docs/img/access-graph/temporary-resource-group-node.png
  docs/img/access-graph/temporary-user-group-node.png
  docs/img/access-graph/user-group-node.png
  docs/img/access-graph/user-node.png
  docs/pages/access-graph.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#35440 feat: add metrics for event sizes
  lib/events/athena/publisher.go
  lib/events/athena/querier.go
  lib/events/auditlog.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/emitter.go
  lib/events/filelog.go
Labels: audit-log, size/sm, backport/branch/v14

#35453 [v14] Limit access list + monitoring and audit backend usagebased flag
  api/client/proto/authservice.pb.go
  api/client/webclient/webconfig.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/access_request_test.go
  lib/auth/usage_test.go
  lib/auth/userloginstate/generator_test.go
  lib/integrations/externalauditstorage/configurator.go
  lib/modules/modules.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.story.tsx
Labels: ui, backport, size/md, no-changelog

#35495 remove double quotes in instance single starter example Makefile
  examples/aws/terraform/starter-cluster/Makefile
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#35475 Restrict Spacelift to Enterprise
  lib/auth/auth_with_roles.go
  lib/auth/join_spacelift.go
  lib/auth/join_spacelift_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#35352 [v14] Metrics: add running services metric
  lib/service/supervisor.go
  metrics.go
Labels: backport, size/sm

#35456 Don't include Stripe in CSP for enterprise usage-based products
  lib/httplib/httpheaders.go
  lib/httplib/httplib_test.go
Labels: size/sm, backport/branch/v14

#35500 [v14] Improve the Enterprise intro page
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#35506 [v14] Restrict Spacelift to Enterprise
  lib/auth/auth_with_roles.go
  lib/auth/join_spacelift.go
  lib/auth/join_spacelift_test.go
Labels: backport, size/sm, no-changelog
