Repository gravitational/teleport, pull requests merged in 2023-04, with the labels that each got.

#23957 Allow `make update-tag` to push to teleport-private
  Makefile
Labels: size/sm

#23958 [v12] Add Docker Hub login to Drone's Kubernetes pipelines
  .drone.yml
  Makefile
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/container_image_products.go
  dronegen/container_images_release_version.go
  dronegen/container_images_repos.go
  dronegen/gha.go
  dronegen/main.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/types.go
Labels: backport, size/lg

#23956 Add Docker Hub login to Drone's Kubernetes pipelines
  .drone.yml
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/container_image_products.go
  dronegen/container_images_release_version.go
  dronegen/container_images_repos.go
  dronegen/gha.go
  dronegen/main.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/types.go
Labels: size/lg

#23820 release: Update build for product signing
  Makefile
  build.assets/build-package.sh
  build.assets/build-pkg-tsh.sh
  build.assets/keychain-setup.sh
Labels: size/sm

#23959 [v11] Add Docker Hub login to Drone's Kubernetes pipelines
  .drone.yml
  Makefile
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/container_image_products.go
  dronegen/container_images_release_version.go
  dronegen/container_images_repos.go
  dronegen/gha.go
  dronegen/main.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/types.go
Labels: backport, size/lg

#23954 RFD Spell fixes
  rfd/0007-rbac-oss.md
  rfd/0008-application-access.md
  rfd/0010-api.md
  rfd/0011-database-access.md
  rfd/0015-2fa-management.md
  rfd/0016-dynamic-configuration.md
  rfd/0019-event-iteration-api.md
  rfd/0021-cluster-routing.md
  rfd/0024-dynamo-event-overflow.md
  rfd/0026-custom-approval-conditions.md
  rfd/0027-mtls-metrics.md
  rfd/0028-cluster-config-resources.md
  rfd/0029-account-lifecycle.md
  rfd/0034-desktop-access-windows.md
  rfd/0040-webauthn-support.md
  rfd/0041-aws-node-join.md
  rfd/0043-kubeaccess-multiparty.md
  rfd/0046-database-access-config.md
  rfd/0047-drop-vendor.md
  rfd/0048-desktop-access-session-recording.md
  rfd/0049-desktop-clipboard.md
  rfd/0055-webui-ss-paginate-filter.md
  rfd/0057-automatic-aws-server-discovery.md
  rfd/0057-automatic-user-provisioning.md
  rfd/0058-desktop-file-transfer.md
  rfd/0058-package-distribution.md
  rfd/0059-search-based-access-requests.md
  rfd/0065-distributed-tracing.md
  rfd/0067-database-access-aws-redis.md
  rfd/0067-desktop-access-file-system-sharing.md
  rfd/0069-proxy-peering.md
  rfd/0073-idp-initiated-login.md
  rfd/0073-public-image-registry.md
  rfd/0074-sftp-support.md
  rfd/0075-snowflake-support.md
  rfd/0078-login-rules.md
  rfd/0079-oidc-joining.md
  rfd/0080-hardware-key-support.md
  rfd/0081-tls-ping.md
  rfd/0083-machine-id-host-certs.md
  rfd/0087-access-request-notification-routing.md
  rfd/0088-passwordless-windows.md
  rfd/0089-merge-webapps.md
  rfd/0090-upgrade-system.md
  rfd/0091-session-streaming.md
  rfd/0094-discover-metrics.md
  rfd/0096-helm-chart-revamp.md
  rfd/0097-teleport-connect-usage-metrics.md
  rfd/0098-kubernetes-access-cluster-discovery.md
  rfd/0100-proxy-ssh-grpc.md
  rfd/0101-pod-rbac.md
  rfd/0105-headless-authentication.md
  rfd/0109-cloud-agent-upgrades.md
  rfd/0111-support-connection-testers-with-per-session-mfa.md
  rfd/0113-automatic-database-users.md
  rfd/0113-scalable-audit-logs.md
Labels: rfd, size/sm

#23972 [v10] Add Docker Hub login to Drone's Kubernetes pipelines
  .drone.yml
  Makefile
  dronegen/aws.go
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/container_image_products.go
  dronegen/container_images_release_version.go
  dronegen/container_images_repos.go
  dronegen/gha.go
  dronegen/main.go
  dronegen/push.go
  dronegen/relcli.go
  dronegen/tag.go
  dronegen/types.go
Labels: backport, size/lg

#22533 RFD: Forward User's Identity between Teleport Kubernetes services
  rfd/0117-kube-access-forward-identity.md
Labels: rfd, size/md

#23703 athena audit logs - config
  constants.go
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/service/service.go
Labels: audit-log, size/md

#23836 Fixes unsused flags from `tsh kube exec` command
  constants.go
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/moderated_sessions_test.go
  lib/kube/proxy/sess.go
  tool/tsh/kube.go
Labels: kubernetes-access, tsh, size/sm

#23645 [v10] Allow updating of trusted cluster role maps (#18168)
  api/types/trustedcluster.go
  integration/helpers.go
  integration/integration_test.go
  integration/trustedclusters.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
  lib/services/local/trust.go
  lib/services/trust.go
Labels: backport, size/lg

#23047 GitLab Delegated Joining docs
  docs/config.json
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/guides/github-actions.mdx
  docs/pages/machine-id/guides/gitlab.mdx
  docs/pages/machine-id/reference.mdx
  docs/pages/machine-id/reference/gitlab.mdx
  lib/gitlab/gitlab.go
Labels: documentation, size/md, backport/branch/v12

#23755 Enforce Kubernetes license when creating Kube resources
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/kube.go
  lib/kube/proxy/moderated_sessions_test.go
Labels: size/sm

#23560 Docs: prefer `curl .../auth/export` instead of `tctl auth export`
  docs/pages/desktop-access/active-directory-manual.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/troubleshooting.mdx
  docs/pages/management/guides/ssh-key-extensions.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/recording-proxy-mode.mdx
Labels: documentation, size/sm, backport/branch/v12

#23902 [v12] Metrics: add IsSSO to Discover Events
  api/types/user.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/tlsca/ca.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/types_discover.go
  lib/usagereporter/teleport/usagereporter_test.go
  lib/web/ui/user.go
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/md

#23979 ClusterItem: Remove usage of colors.secondary.lighter
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
Labels: ui, backport/branch/v11, size/sm, backport/branch/v12

#23912 Integration status: proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: discover, size/sm

#23892 [v12] Add Support for Oracle protocol
  api/types/database.go
  api/utils/keypaths/keypaths.go
  go.mod
  go.sum
  lib/client/db/database_certificates.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/client/db/oracle/config.go
  lib/client/db/oracle/oracle.go
  lib/client/identityfile/identity.go
  lib/client/interfaces.go
  lib/client/profile.go
  lib/defaults/defaults.go
  lib/service/service.go
  lib/service/service_test.go
  lib/services/database.go
  lib/srv/alpnproxy/common/protocols.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/enterprise/enterprise.go
  lib/srv/db/proxyserver.go
  lib/utils/fs.go
  tool/tctl/common/auth_command.go
  tool/tsh/app.go
  tool/tsh/db.go
  tool/tsh/db_test.go
  tool/tsh/proxy.go
  tool/tsh/proxy_test.go
Labels: tsh, tctl, database-access, backport, size/lg

#23981 [v12] GitLab Delegated Joining docs
  docs/config.json
  docs/pages/includes/machine-id/guides.mdx
  docs/pages/machine-id/guides/github-actions.mdx
  docs/pages/machine-id/guides/gitlab.mdx
  docs/pages/machine-id/reference.mdx
  docs/pages/machine-id/reference/gitlab.mdx
  lib/gitlab/gitlab.go
Labels: documentation, backport, size/md

#23674 Fix relaxed moderator joining for Kube Access
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/moderated_sessions_test.go
  lib/kube/proxy/sess.go
  lib/web/apiserver_test.go
Labels: kubernetes-access, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23860 Move ALPN dialer, ALPN conn upgrade, Ping conn to api
  api/client/alpn.go
  api/client/alpn_conn_upgrade.go
  api/client/alpn_conn_upgrade_test.go
  api/constants/constants.go
  api/fixtures/fixtures.go
  api/utils/pingconn/pingconn.go
  api/utils/pingconn/pingconn_test.go
  constants.go
  lib/client/api.go
  lib/fixtures/fixtures.go
  lib/srv/alpnproxy/conn.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/local_proxy_config_opt.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
  lib/web/conn_upgrade.go
Labels: size/sm

#23952 [v11] docs: Add advisory and troubleshooting on non-tls mode for machineid kube
  docs/pages/includes/machine-id/kubernetes-machineidnote.mdx
  docs/pages/machine-id/guides/github-actions-kubernetes.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  docs/pages/machine-id/troubleshooting.mdx
Labels: documentation, backport, size/sm

#23951 [v12] docs: Add advisory and troubleshooting on non-tls mode for machineid kube
  docs/pages/includes/machine-id/kubernetes-machineidnote.mdx
  docs/pages/machine-id/guides/github-actions-kubernetes.mdx
  docs/pages/machine-id/guides/kubernetes.mdx
  docs/pages/machine-id/troubleshooting.mdx
Labels: documentation, backport, size/sm

#23982 [v12] Docs: prefer `curl .../auth/export` instead of `tctl auth export`
  docs/pages/desktop-access/active-directory-manual.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/desktop-access/troubleshooting.mdx
  docs/pages/management/guides/ssh-key-extensions.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/recording-proxy-mode.mdx
Labels: documentation, backport, size/sm

#23988 [v12] docs: include enable teleport service in systemctl start
  docs/pages/includes/start-teleport.mdx
Labels: documentation, backport, size/sm

#23849 Release 10.3.15
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  integration/port_forwarding_test.go
  lib/client/api.go
  lib/client/client.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/reexec.go
  lib/srv/regular/sshserver.go
  lib/utils/proxyconn.go
  version.go
Labels: kubernetes-access, helm, backport, size/md

#23272 Headless Authn: documentation
  docs/config.json
  docs/pages/access-controls/guides/headless.mdx
  docs/pages/includes/access-control-guides.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/reference/cli.mdx
Labels: documentation, size/md

#23846 [v11] Docs: fix saml role addition partial.
  docs/pages/includes/add-role-to-user.mdx
  docs/pages/management/export-audit-events/splunk.mdx
Labels: documentation, backport, backport/branch/v10, size/sm

#23419 [v12] Allow getting client IP from ProxyHelloSignature for compatibility
  lib/sshutils/server.go
Labels: size/sm

#23984 [v12] tsh: Fix redundant error in PPK generation on relogin
  lib/client/keystore.go
Labels: backport, size/sm

#23360 [v12] Headless Login
  api/breaker/round_tripper.go
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/webclient/webclient.go
  api/constants/constants.go
  api/observability/tracing/http/http.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/authentication.go
  api/types/authentication_authpreference_test.go
  api/types/constants.go
  api/types/headlessauthn.go
  api/types/types.pb.go
  docs/config.json
  docs/pages/access-controls/guides/headless.mdx
  docs/pages/includes/access-control-guides.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/reference/cli.mdx
  lib/auth/auth.go
  lib/auth/auth_login_test.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/auth/http_client.go
  lib/auth/methods.go
  lib/auth/methods_test.go
  lib/auth/tls_test.go
  lib/client/api.go
  lib/client/weblogin.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/service/connect.go
  lib/service/service.go
  lib/services/headlessauthn.go
  lib/services/identity.go
  lib/services/local/headlessauthn.go
  lib/services/local/headlessauthn_test.go
  lib/services/local/headlessauthn_watcher.go
  lib/services/local/headlessauthn_watcher_test.go
  lib/utils/mlock/mlock_linux.go
  lib/utils/mlock/mlock_unsupported.go
  lib/web/apiserver.go
  lib/web/apiserver_ping_test.go
  lib/web/headless.go
  lib/web/sessions.go
  rfd/0105-headless-authentication.md
  tool/tsh/tsh.go
  web/packages/teleport/src/HeadlessRequest/Cards.tsx
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.test.tsx
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.tsx
  web/packages/teleport/src/HeadlessRequest/index.ts
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/components/HeadlessRequestDialog/HeadlessRequestDialog.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/auth/auth.ts
Labels: documentation, ui, tsh, rfd, backport, size/xl

#23947 [v11] reduce cache retry load
  api/utils/retryutils/retry_test.go
  api/utils/retryutils/retryv2.go
  integration/integration_test.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/defaults/defaults.go
  lib/service/cfg.go
  lib/service/service.go
Labels: backport, size/md

#23936 [v12] docs: add description of config versions
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm

#24011 Close auth clients in tctl tests
  tool/tctl/common/helpers_test.go
Labels: tctl, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23807 Use `teleport-internal-join` login when joining a Moderated Session from the UI
  lib/web/terminal.go
Labels: ui, moderated-sessions, backport/branch/v11, size/sm, backport/branch/v12

#23901 Define an explicit device resource as DeviceV1
  api/proto/buf.yaml
  api/proto/teleport/legacy/types/device.proto
  api/types/device.go
  api/types/device.pb.go
  api/types/device_test.go
  lib/devicetrust/friendly_enums.go
  tool/tctl/common/collection.go
  tool/tctl/common/device/resource.go
  tool/tctl/common/device/resource_test.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/md, backport/branch/v12

#23918 Add agentless items to test plan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm

#24022 operator: revert to old dockerfile and oci image build process
  integrations/operator/Dockerfile
  integrations/operator/Makefile
Labels: size/sm

#23986 [v11] tsh: Fix redundant error in PPK generation on relogin
  lib/client/keystore.go
Labels: backport, size/sm

#23908 [v10] docs: Add documentation page for IP pinning
  docs/config.json
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/ip-pinning.mdx
Labels: documentation, backport, size/md

#23913 Declare device resource CRUD methods
  api/client/client.go
Labels: size/sm

#23639 docs: device trust edits
  docs/pages/access-controls/guides/device-trust.mdx
Labels: documentation, size/sm, backport/branch/v12

#24014 [v12] Close auth clients in tctl tests
  tool/tctl/common/helpers_test.go
Labels: tctl, backport, size/sm

#24015 [v11] Close auth clients in tctl tests
  tool/tctl/common/helpers_test.go
Labels: tctl, backport, size/sm

#23985 [v10] tsh: Fix redundant error in PPK generation on relogin
  lib/client/keystore.go
Labels: backport, size/sm

#23940 GHA: Update path filters to include workflow files and Makefile
  .github/workflows/build-macos-bypass.yaml
  .github/workflows/build-macos.yaml
  .github/workflows/build-windows-bypass.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/integration-tests-non-root-bypass.yaml
  .github/workflows/integration-tests-non-root.yaml
  .github/workflows/integration-tests-root-bypass.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/lint-bypass.yaml
  .github/workflows/unit-tests-code-bypass.yaml
  .github/workflows/unit-tests-code.yaml
  .github/workflows/unit-tests-helm-bypass.yaml
  .github/workflows/unit-tests-helm.yaml
  .github/workflows/unit-tests-rust-bypass.yaml
  .github/workflows/unit-tests-rust.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  lib/reversetunnel/agentpool_test.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23903 Add conversation Web endpoint
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/services/identity.go
  lib/services/local/users.go
  lib/web/apiserver.go
  lib/web/assistant.go
Labels: size/md

#24013 Add missing `join_method` in azure joining docs
  docs/pages/management/guides/joining-nodes-azure.mdx
Labels: documentation, size/sm, backport/branch/v12

#23898 Connect: Collect protocol origin
  gen/proto/go/prehog/v1alpha/connect.pb.go
  gen/proto/js/prehog/v1alpha/connect_pb.d.ts
  gen/proto/js/prehog/v1alpha/connect_pb.js
  proto/prehog/v1alpha/connect.proto
  web/packages/teleterm/src/services/tshd/mapUsageEvent.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/useKubes.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/useServers.ts
  web/packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
  web/packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
  web/packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.test.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
  web/packages/teleterm/src/ui/QuickInput/useQuickInput.ts
  web/packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/useConnections.ts
  web/packages/teleterm/src/ui/commandLauncher.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
  web/packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
  web/packages/teleterm/src/ui/services/usage/usageService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, size/sm, backport/branch/v12

#24027 [v12] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#23980 Connect: Add SearchBar
  web/packages/design/src/Icon/Icon.jsx
  web/packages/shared/components/Highlight/Highlight.story.tsx
  web/packages/shared/components/Highlight/Highlight.tsx
  web/packages/shared/components/Highlight/index.ts
  web/packages/shared/hooks/useAsync.ts
  web/packages/shared/package.json
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/services/tshd/createClient.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/useKubes.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/useServers.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/useServerSideResources.ts
  web/packages/teleterm/src/ui/Documents/KeyboardShortcutsPanel.tsx
  web/packages/teleterm/src/ui/QuickInput/QuickInput.tsx
  web/packages/teleterm/src/ui/Search/SearchBar.test.tsx
  web/packages/teleterm/src/ui/Search/SearchBar.tsx
  web/packages/teleterm/src/ui/Search/SearchContext.tsx
  web/packages/teleterm/src/ui/Search/actions.tsx
  web/packages/teleterm/src/ui/Search/index.ts
  web/packages/teleterm/src/ui/Search/pickers/ActionPicker.story.tsx
  web/packages/teleterm/src/ui/Search/pickers/ActionPicker.tsx
  web/packages/teleterm/src/ui/Search/pickers/ParameterPicker.tsx
  web/packages/teleterm/src/ui/Search/pickers/ResultList.tsx
  web/packages/teleterm/src/ui/Search/pickers/pickers.tsx
  web/packages/teleterm/src/ui/Search/pickers/useSearchAttempts.ts
  web/packages/teleterm/src/ui/Search/searchResult.ts
  web/packages/teleterm/src/ui/Search/searchResultTestHelpers.ts
  web/packages/teleterm/src/ui/Search/useSearch.test.ts
  web/packages/teleterm/src/ui/Search/useSearch.ts
  web/packages/teleterm/src/ui/TabHost/index.ts
  web/packages/teleterm/src/ui/TabHost/useNewTabOpener.ts
  web/packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
  web/packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
  web/packages/teleterm/src/ui/TopBar/MoreOptions.tsx
  web/packages/teleterm/src/ui/TopBar/NavigationMenu/NavigationItem.tsx
  web/packages/teleterm/src/ui/TopBar/NavigationMenu/NavigationMenu.tsx
  web/packages/teleterm/src/ui/TopBar/TopBar.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/commandLauncher.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/keyboardShortcuts/keyboardShortcutsService.ts
  web/packages/teleterm/src/ui/services/quickInput/suggesters.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.test.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/types.ts
  web/packages/teleterm/src/ui/uri.ts
  yarn.lock
Labels: ui, size/xl

#24024 [v12] Define an explicit device resource as DeviceV1
  api/go.mod
  api/go.sum
  api/proto/buf.yaml
  api/proto/teleport/legacy/types/device.proto
  api/types/device.go
  api/types/device.pb.go
  api/types/device_test.go
  lib/devicetrust/friendly_enums.go
  tool/tctl/common/collection.go
  tool/tctl/common/device/resource.go
  tool/tctl/common/device/resource_test.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/md

#24039 [v12] Connect: Collect protocol origin
  gen/proto/go/prehog/v1alpha/connect.pb.go
  gen/proto/js/prehog/v1alpha/connect_pb.d.ts
  gen/proto/js/prehog/v1alpha/connect_pb.js
  proto/prehog/v1alpha/connect.proto
  web/packages/teleterm/src/services/tshd/mapUsageEvent.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/useKubes.ts
  web/packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/useServers.ts
  web/packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
  web/packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
  web/packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.test.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
  web/packages/teleterm/src/ui/QuickInput/useQuickInput.ts
  web/packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/useConnections.ts
  web/packages/teleterm/src/ui/commandLauncher.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
  web/packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
  web/packages/teleterm/src/ui/services/usage/usageService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, backport, size/sm

#24041 docs: correct mongodb atlas example config
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24025 [v12] docs: device trust edits
  docs/pages/access-controls/guides/device-trust.mdx
Labels: documentation, backport, size/sm

#24031 [v12] Add missing `join_method` in azure joining docs
  docs/pages/management/guides/joining-nodes-azure.mdx
Labels: documentation, backport, size/sm

#24045 [v11] docs: correct mongodb atlas example config
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#23931 [v11] Docs: expand user creation or update for MySQL/Mariadb
  docs/pages/database-access/guides/mysql-self-hosted.mdx
Labels: documentation, backport, size/sm

#24046 [v10] docs: correct mongodb atlas example config
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#23937 [v12] Recommend Proxy Service in event-handler guides
  docs/pages/access-controls/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/access-controls/guides/dual-authz.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/elastic-stack.mdx
  docs/pages/management/export-audit-events/splunk.mdx
Labels: documentation, backport, size/sm

#23944 [v12] Docs - Azure VM auto-discovery
  docs/config.json
  docs/img/azure/add-custom-role@2x.png
  docs/img/azure/app-registrations@2x.png
  docs/img/azure/managed-identities@2x.png
  docs/img/azure/registered-app-secrets@2x.png
  docs/img/server-access/guides/azure/create-role-assignment@2x.png
  docs/img/server-access/guides/azure/created-identity@2x.png
  docs/img/server-access/guides/azure/new-identity@2x.png
  docs/img/server-access/guides/azure/registered-app@2x.png
  docs/img/server-access/guides/azure/vm-create-role-from-json@2x.png
  docs/img/server-access/guides/azure/vm-identity@2x.png
  docs/pages/database-access/guides/azure-postgres-mysql.mdx
  docs/pages/database-access/guides/azure-redis.mdx
  docs/pages/database-access/guides/azure-sql-server-ad.mdx
  docs/pages/includes/database-access/azure-configure-service-principal.mdx
  docs/pages/includes/server-access/azure-assign-service-principal.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/azure-discovery.mdx
Labels: documentation, backport, size/md

#24044 [v12] docs: correct mongodb atlas example config
  docs/pages/database-access/guides/mongodb-atlas.mdx
Labels: documentation, backport, size/sm

#24049 v12 upcoming releases: Replace "Spotlight Search" with "Cross-Cluster Search"
  docs/pages/preview/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#23781 Introduce `tsh bench kube` tool
  examples/bench/example.go
  lib/benchmark/benchmark.go
  lib/benchmark/benchmark_suites.go
  lib/benchmark/linear.go
  lib/benchmark/linear_test.go
  tool/tsh/tsh.go
Labels: tsh, size/md

#24003 [v12] Add a guide to creating Teleport roles via the API
  docs/config.json
  docs/pages/api/introduction.mdx
  docs/pages/api/rbac.mdx
  examples/api-sync-roles/README.md
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  examples/api-sync-roles/main.go
Labels: documentation, backport, size/xl

#24054 helm: delete hook-related resource on re-apply
  examples/chart/teleport-cluster/templates/auth/predeploy_config.yaml
  examples/chart/teleport-cluster/templates/auth/predeploy_job.yaml
  examples/chart/teleport-cluster/templates/proxy/predeploy_config.yaml
  examples/chart/teleport-cluster/templates/proxy/predeploy_job.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/templates/hook.yaml
Labels: helm, size/sm, backport/branch/v12

#24059 [v11] revert db tls mode backend marshal
  api/types/database.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm

#24029 [v12] Fix listing of available participant modes in the UI for Moderated Sessions
  lib/auth/session_access.go
  lib/auth/session_access_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#24068 [v12] helm: delete hook-related resource on re-apply
  examples/chart/teleport-cluster/templates/auth/predeploy_config.yaml
  examples/chart/teleport-cluster/templates/auth/predeploy_job.yaml
  examples/chart/teleport-cluster/templates/proxy/predeploy_config.yaml
  examples/chart/teleport-cluster/templates/proxy/predeploy_job.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/templates/hook.yaml
Labels: helm, backport, size/sm

#24063 [v12] revert marshal database tls mode
  api/types/database.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm

#23856 update Makefile to use cargo sparse protocol in all cargo commands
  .github/workflows/build-macos.yaml
  Makefile
Labels: rdp, desktop-access, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24018 [v12] Use `teleport-internal-join` login when joining a Moderated Session from the UI
  lib/web/terminal.go
Labels: backport, size/sm

#24028 [v11] Fix listing of available participant modes in the UI for Moderated Sessions
  lib/auth/session_access.go
  lib/auth/session_access_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#24076 Bump Cloud SLA to 99.9%
  docs/config.json
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23997 Remove the Access Controls FAQ
  docs/config.json
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/faq.mdx
  docs/pages/access-controls/introduction.mdx
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23742 Discover: Add more database type event names
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  proto/prehog/v1alpha/teleport.proto
Labels: size/sm

#23999 Clarify how to decide undocumented style questions
  docs/pages/contributing/documentation/style-guide.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24056 Release 12.2.0
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm

#23935 [v12] Show the server name (instead of UUID) in errors
  lib/client/client.go
  lib/web/terminal.go
Labels: backport, backport/branch/v10, backport/branch/v11, size/sm

#23785 [v10] WebDiscover: Add support for connection testers with per-session MFA enabled (#22529)
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.story.tsx
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/useTestConnection.ts
  web/packages/teleport/src/Discover/Server/TestConnection/TestConnection.story.tsx
  web/packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Server/TestConnection/useTestConnection.ts
  web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/agents/agents.ts
  web/packages/teleport/src/services/agents/types.ts
  web/packages/teleport/src/services/auth/auth.ts
  web/packages/teleport/src/services/mfa/mfa.ts
  web/packages/teleport/src/services/mfa/types.ts
Labels: ui, backport, size/md

#24050 Remove deprecated web api routes
  lib/web/apiserver.go
Labels: size/sm

#24017 [v12] helm: Add support for imagePullSecrets to teleport-cluster chart
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/.lint/imagepullsecrets.yaml
  examples/chart/teleport-cluster/templates/auth/deployment.yaml
  examples/chart/teleport-cluster/templates/proxy/deployment.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/auth_deployment_test.yaml
  examples/chart/teleport-cluster/tests/proxy_deployment_test.yaml
  examples/chart/teleport-cluster/values.schema.json
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport, size/sm

#24078 [v11] Update gosaml2 to 0.9.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: backport, size/sm

#24092 [v11] Bump Cloud SLA to 99.9%
  docs/config.json
Labels: documentation, backport, size/sm

#24091 [v10] Bump Cloud SLA to 99.9%
  docs/config.json
Labels: documentation, backport, size/sm

#24093 [v12] Bump Cloud SLA to 99.9%
  docs/config.json
Labels: documentation, backport, size/sm

#24077 [v10] Update gosaml2 to 0.9.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: backport, size/sm

#23995 Add local guidance for Linux Server guide users
  docs/pages/try-out-teleport/linux-server.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23998 Add systemctl instructions to Connecting Apps
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23925 docs: Oracle Database Access
  docs/config.json
  docs/img/database-access/guides/oracle_selfhosted.png
  docs/img/database-access/guides/oracle_selfhosted_cloud.png
  docs/pages/database-access/guides/oracle-self-hosted.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, database-access, size/md, backport/branch/v12

#24079 [v12] Update gosaml2 to 0.9.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: backport, size/sm

#24073 Remove no longer used Teleport enterprise docker-compose example
  docker/teleport-ent-quickstart.yml
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24119 [v12] docs: Oracle Database Access
  docs/config.json
  docs/img/database-access/guides/oracle_selfhosted.png
  docs/img/database-access/guides/oracle_selfhosted_cloud.png
  docs/pages/database-access/guides/oracle-self-hosted.mdx
  docs/pages/includes/database-access/guides.mdx
Labels: documentation, backport, size/md

#22556 RFD 0119 - Integrate with AWS using OIDC
  rfd/0119-aws-api-integration-using-oidc.md
Labels: rfd, discover, size/md

#24103 Fix TestTerminal_KillUnderlyingShell
  lib/srv/term_test.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23375 Include year in cert rotate examples docs
  docs/pages/management/operations/ca-rotation.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24117 Fix flaky tests
  lib/auth/keystore/keystore_test.go
  lib/authz/permissions_test.go
  lib/modules/test.go
  lib/srv/session_control_test.go
  lib/web/apiserver_test.go
Labels: backport/branch/v11, size/sm, backport/branch/v12

#24055 Fix panic for when `/web/launch` is requested
  lib/web/apiserver.go
Labels: size/sm, backport/branch/v12

#24125 [v12] Fix TestTerminal_KillUnderlyingShell
  lib/srv/term_test.go
Labels: backport, size/sm

#24057 [V12] Integration resource: proto
  api/client/proto/authservice.pb.go
  api/gen/proto/go/teleport/integration/v1/integration_service.pb.go
  api/gen/proto/go/teleport/integration/v1/integration_service_grpc.pb.go
  api/proto/teleport/integration/v1/integration_service.proto
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  build.assets/genproto.sh
Labels: backport, size/md

#24124 [v11] Fix TestTerminal_KillUnderlyingShell
  lib/srv/term_test.go
Labels: backport, size/sm

#24126 [v12] Fix flaky tests
  lib/auth/keystore/keystore_test.go
  lib/authz/permissions_test.go
  lib/modules/test.go
  lib/srv/session_control_test.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#24090 Send tunnel reconnects before waiting for sessions to drain
  lib/reversetunnel/srv.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24109 Fix improper report of status on success
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/websocket_client_testing.go
Labels: kubernetes-access, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24043 drone: add updater release and promotion triggers
  .drone.yml
  dronegen/promote.go
  dronegen/tag.go
Labels: size/md

#24023 fix running non-interactive commands on agentless nodes
  integration/integration_test.go
  lib/srv/exec.go
Labels: server-access, size/sm, agentless

#24128 [v11] Fix flaky tests
  lib/auth/keystore/keystore_test.go
  lib/modules/test.go
  lib/srv/session_control_test.go
  lib/web/apiserver_test.go
Labels: backport, size/sm

#23916 usagereporter: on-prem dial home
  gen/proto/go/prehog/v1/prehogv1connect/teleport.connect.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/connect.pb.go
  gen/proto/go/prehog/v1alpha/prehogv1alphaconnect/connect.connect.go
  gen/proto/go/prehog/v1alpha/prehogv1alphaconnect/tbot.connect.go
  gen/proto/go/prehog/v1alpha/prehogv1alphaconnect/teleport.connect.go
  gen/proto/go/prehog/v1alpha/tbot.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1/teleport_grpc_pb.d.ts
  gen/proto/js/prehog/v1/teleport_grpc_pb.js
  gen/proto/js/prehog/v1/teleport_pb.d.ts
  gen/proto/js/prehog/v1/teleport_pb.js
  lib/service/service.go
  lib/usagereporter/daemon/usagereporter.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/aggregating/service.go
  lib/usagereporter/teleport/aggregating/service_test.go
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/types_discover.go
  lib/usagereporter/teleport/usagereporter.go
  lib/usagereporter/teleport/usagereporter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/connect.proto
  proto/prehog/v1alpha/tbot.proto
  proto/prehog/v1alpha/teleport.proto
  tool/tbot/anonymous_telemetry.go
  tool/tbot/anonymous_telemetry_test.go
Labels: size/lg

#24081 [v12] Remove the Access Controls FAQ
  docs/config.json
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/faq.mdx
  docs/pages/access-controls/introduction.mdx
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/sm

#24151 [v11] Remove no longer used Teleport enterprise docker-compose example
  docker/teleport-ent-quickstart.yml
Labels: backport, size/sm

#24150 [v12] Remove no longer used Teleport enterprise docker-compose example
  docker/teleport-ent-quickstart.yml
Labels: backport, size/sm

#23777 docs: update mfa docs
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24009 Bump cloud docs to 12.1.5
  docs/config.json
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#23917 Drop gRPC call options from api/client.Client
  api/client/auditstreamer.go
  api/client/client.go
  api/client/inventory.go
  api/client/keepaliver.go
  api/client/sessions.go
  api/client/streamwatcher.go
  integrations/access/common/config.go
Labels: size/sm

#24155 [v12] Fix improper report of status on success
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/websocket_client_testing.go
Labels: kubernetes-access, backport, size/sm

#24141 [v12] Send tunnel reconnects before waiting for sessions to drain
  lib/reversetunnel/srv.go
Labels: backport, size/sm

#23848 Release 11.3.10
  CHANGELOG.md
  Makefile
  api/version.go
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  integration/port_forwarding_test.go
  lib/auth/permissions.go
  lib/client/api.go
  lib/client/client.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/server.go
  lib/kube/proxy/watcher.go
  lib/services/kubernetes.go
  lib/services/watcher.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/reexec.go
  lib/srv/regular/sshserver.go
  lib/utils/proxyconn.go
  version.go
Labels: kubernetes-access, helm, backport, size/md

#24142 [v11] Send tunnel reconnects before waiting for sessions to drain
  lib/reversetunnel/srv.go
Labels: backport, size/sm

#24158 [v11] docs: update mfa docs
  docs/pages/access-controls/guides/per-session-mfa.mdx
Labels: documentation, backport, size/sm

#24154 [v11] Fix improper report of status on success
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/websocket_client_test.go
Labels: kubernetes-access, backport, size/sm

#24123 [v10] Fix TestTerminal_KillUnderlyingShell
  lib/srv/term_test.go
Labels: backport, size/sm

#24084 [v11] Clarify how to decide undocumented style questions
  docs/pages/contributing/documentation/style-guide.mdx
Labels: documentation, backport, size/sm

#24085 [v12] Clarify how to decide undocumented style questions
  docs/pages/contributing/documentation/style-guide.mdx
Labels: documentation, backport, size/sm

#24163 Remove unused code
  lib/utils/distro.go
  lib/utils/distro_test.go
Labels: size/sm

#24143 [v10] Send tunnel reconnects before waiting for sessions to drain
  lib/reversetunnel/srv.go
Labels: backport, size/sm

#24048 helm: Add updater support to `teleport-kube-agent` chart
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/updater.yaml
  examples/chart/teleport-kube-agent/templates/_config.tpl
  examples/chart/teleport-kube-agent/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/clusterrolebinding.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/templates/psp.yaml
  examples/chart/teleport-kube-agent/templates/rolebinding.yaml
  examples/chart/teleport-kube-agent/templates/serviceaccount.yaml
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/templates/updater/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/updater/deployment.yaml
  examples/chart/teleport-kube-agent/templates/updater/role.yaml
  examples/chart/teleport-kube-agent/templates/updater/rolebinding.yaml
  examples/chart/teleport-kube-agent/templates/updater/serviceaccount.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_role_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/updater_deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/updater_role_test.yaml
  examples/chart/teleport-kube-agent/tests/updater_rolebinding_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, size/lg

#23990 Update and rename 0113-scalable-audit-logs.md to 0118
  rfd/0118-scalable-audit-logs.md
Labels: rfd, size/sm

#24114 Connect: Do not include staging feedback address in prod CSP
  web/packages/teleterm/webpack.renderer.extend.js
Labels: ui, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24182 [v12] ClusterItem: Remove usage of colors.secondary.lighter
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
Labels: ui, backport, size/sm

#24160 [v10] Fix improper report of status on success (#24109)
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/websocket_client_test.go
Labels: kubernetes-access, backport, size/sm

#24082 Execute command Web API
  lib/client/client.go
  lib/reversetunnel/agent.go
  lib/web/apiserver.go
  lib/web/command.go
  lib/web/command_utils.go
  lib/web/terminal.go
Labels: size/lg

#24167 Split PingConn to PingConn and PingTLSConn
  api/utils/pingconn/pingconn.go
  api/utils/pingconn/pingconn_test.go
  api/utils/pingconn/tls.go
  lib/srv/alpnproxy/local_proxy.go
  lib/srv/alpnproxy/proxy.go
  lib/srv/alpnproxy/proxy_test.go
Labels: size/sm

#24188 Fix panic when incoming request is nil
  lib/sshutils/server.go
Labels: backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24168 Implement a basic conversation wrapper on top of ChatGPT
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  go.mod
  go.sum
  lib/ai/chat.go
  lib/ai/client.go
  lib/config/fileconf.go
  lib/web/assistant.go
Labels: size/md

#24137 [v12] Add systemctl instructions to Connecting Apps
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm

#24198 [v11] Fix panic when incoming request is nil
  lib/sshutils/server.go
Labels: backport, size/sm

#24101 Fix tctl test timeouts
  tool/tctl/common/helpers_test.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24175 [v11] Update docs version
  docs/config.json
Labels: documentation, backport, size/sm

#24172 [v11] Include year in cert rotate examples docs
  docs/pages/management/operations/ca-rotation.mdx
Labels: documentation, backport, size/sm

#24132 [v12] Fix panic for when `/web/launch` is requested
  lib/web/apiserver.go
Labels: backport, size/sm

#24199 [v12] Fix panic when incoming request is nil
  lib/sshutils/server.go
Labels: backport, size/sm

#24140 [v12] Add local guidance for Linux Server guide users
  docs/pages/try-out-teleport/linux-server.mdx
Labels: documentation, backport, size/sm

#24201 Make react-router-dom and @types versions consistent
  web/packages/build/package.json
  yarn.lock
Labels: ui, size/sm

#24149 Lowercase "Teleport Service"
  docs/pages/core-concepts.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/management/admin/uninstall-teleport.mdx
  docs/pages/management/guides/joining-nodes-azure.mdx
Labels: documentation, backport/branch/v10, backport/branch/v11, size/sm, backport/branch/v12

#24174 [v10] docs: update version
  docs/config.json
Labels: documentation, backport, size/sm

#24144 [v12]: Integrations service for CRUD operations (#23989)
  api/types/constants.go
  api/types/integration.go
  api/types/integration_test.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/integration/integrationv1/service_test.go
  lib/services/integration.go
  lib/services/integration_test.go
  lib/services/local/integrations.go
Labels: backport, size/lg

#24173 [v10] Include year in cert rotate examples docs
  docs/pages/management/operations/ca-rotation.mdx
Labels: documentation, backport, size/sm

#24207 [v11] Fix panic for when `/web/launch` is requested
  lib/web/apiserver.go
Labels: backport, size/sm

#23909 [v11] docs: Add documentation page for IP pinning
  docs/config.json
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/guides/ip-pinning.mdx
Labels: documentation, backport, size/md

#23897 [v12] [docs] Add documentation page for IP pinning
  docs/config.json
  docs/pages/access-controls/guides/ip-pinning.mdx
  docs/pages/includes/access-control-guides.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/server-access/rbac.mdx
Labels: documentation, backport, size/md
