Repository gravitational/teleport, pull requests merged in 2023-10, with the labels that each got.

#32815 [v14] [Web] Add usage events for EICE Discover Flow
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/types_discover.go
  lib/usagereporter/web/userevent.go
  lib/usagereporter/web/userevent_discover.go
  proto/prehog/v1alpha/teleport.proto
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
  web/packages/teleport/src/Discover/Server/CreateEc2Ice/CreateEc2Ice.tsx
  web/packages/teleport/src/Discover/Server/CreateEc2Ice/CreateEc2IceDialog.tsx
  web/packages/teleport/src/Discover/Server/EnrollEc2Instance/EnrollEc2Instance.tsx
  web/packages/teleport/src/Discover/Server/index.tsx
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport, size/md

#32719 [v14] DiscoveryConfig: add service with rbac support
  lib/auth/discoveryconfig/discoveryconfigv1/service.go
  lib/auth/discoveryconfig/discoveryconfigv1/service_test.go
Labels: backport, size/md

#32740 [v12] Add connection information to multiplexer logs so it's easier to investigate
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
Labels: backport, size/sm

#32738 [v14] Add connection information to multiplexer logs so it's easier to investigate
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
Labels: backport, size/sm

#32739 [v13] Add connection information to multiplexer logs so it's easier to investigate
  lib/multiplexer/multiplexer.go
  lib/multiplexer/tls.go
  lib/multiplexer/web.go
Labels: backport, size/sm

#32558 Use a context with a different scope for diagnostic trace upload
  lib/srv/db/server.go
Labels: database-access, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32836 [v12] Use a context with a different scope for diagnostic trace upload
  lib/srv/db/server.go
Labels: database-access, backport, size/sm

#32838 [v14] Use a context with a different scope for diagnostic trace upload
  lib/srv/db/server.go
Labels: database-access, backport, size/sm

#32837 [v13] Use a context with a different scope for diagnostic trace upload
  lib/srv/db/server.go
Labels: database-access, backport, size/sm

#32835 Remove Connect My Computer feature flag
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerStatus/DocumentConnectMyComputerStatus.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.test.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
Labels: ui, size/sm, backport/branch/v14

#32685 MySQL auto-user provisioning support for Aurora and version check
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/autousers_test.go
Labels: database-access, size/sm

#32800 [v14] Add support for Client ID in Azure VM auto-discovery
  api/proto/teleport/legacy/types/types.proto
  api/types/installers/installer.sh.tmpl
  api/types/installers/installers.go
  api/types/types.pb.go
  docs/pages/server-access/guides/azure-discovery.mdx
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/srv/discovery/discovery.go
  lib/srv/server/azure_installer.go
  lib/srv/server/azure_watcher.go
  lib/web/apiserver.go
  tool/teleport/common/teleport.go
Labels: documentation, backport, size/sm, discovery

#32805 Add new methods to AccessResourcesGetter interface
  lib/modules/modules.go
Labels: size/sm, backport/branch/v14

#32598 puttyconfig: Switch to string-based Validity format and deprecate MatchHosts
  docs/pages/connect-your-client/putty.mdx
  lib/puttyhosts/puttyhosts.go
  lib/puttyhosts/puttyhosts_test.go
  tool/tsh/common/putty_config_windows.go
Labels: tsh, size/md, backport/branch/v14

#32848 [v14] Prevent Kube proxy from set the default Kube impersonation headers
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/resource_deletecollection.go
  lib/kube/proxy/roundtrip.go
  lib/kube/proxy/sess.go
Labels: kubernetes-access, backport, size/sm

#32563 Add the internal access list review resource.
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  api/types/constants.go
Labels: size/md, backport/branch/v13, backport/branch/v14

#32763 docs: update tctl tsh version location in prereqs
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/management/admin/labels.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32853 Fixed integration test issue causing unnecessary runs
  .github/workflows/integration-tests-non-root.yaml
Labels: size/sm, no-changelog

#32852 [v12] Cut CI unit test runtime in half
  .github/workflows/unit-tests-code.yaml
Labels: backport, size/sm

#32448 BUILD_macos.md: Tidy and Update
  BUILD_macos.md
Labels: size/sm

#32809 docs: remove old versions ref
  docs/pages/architecture/tls-routing.mdx
  docs/pages/management/diagnostics/tracing.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32767 Rewrite `tsh mfa rm` using DeleteMFADeviceSync
  tool/tsh/common/mfa.go
Labels: tsh, size/sm

#31997 docs: Draft of troubleshooting topics for Server Access
  docs/cspell.json
  docs/pages/server-access/troubleshooting-server.mdx
Labels: documentation, size/md, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32773 Deprecate DeleteMFADevice and move tests to its "sync" variant
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/accountrecovery_test.go
  lib/auth/auth_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
Labels: size/sm

#32691 [v14] Sort cloud label names to the back in Unified Resource cards
  api/types/constants.go
  lib/web/ui/server.go
  lib/web/ui/server_test.go
Labels: backport, size/md

#32666 [v14] Convert `examples/teleport-usage` to use distroless image
  examples/teleport-usage/Dockerfile
Labels: backport, size/sm

#32866 [v13] docs: remove old versions ref
  docs/pages/architecture/tls-routing.mdx
  docs/pages/management/diagnostics/tracing.mdx
Labels: documentation, backport, size/sm

#32860 [v12] docs: update tctl tsh version location in prereqs
  docs/pages/includes/edition-prereqs-tabs.mdx
Labels: documentation, backport, size/sm

#32865 [v14] docs: remove old versions ref
  docs/pages/architecture/tls-routing.mdx
  docs/pages/management/diagnostics/tracing.mdx
Labels: documentation, backport, size/sm

#32858 [v14] docs: update tctl tsh version location in prereqs
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/management/admin/labels.mdx
Labels: documentation, backport, size/sm

#32523 update `--db-user` and `--db-name` docs
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/includes/db-user-name-flags.mdx
  docs/pages/reference/cli/tsh.mdx
  tool/tsh/common/tsh.go
Labels: documentation, tsh, size/sm, backport/branch/v14

#32861 [v14] Add the internal access list review resource.
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  api/types/constants.go
Labels: backport, size/lg

#32856 [v14] puttyconfig: Switch to string-based Validity format and deprecate MatchHosts
  docs/pages/connect-your-client/putty.mdx
  lib/puttyhosts/puttyhosts.go
  lib/puttyhosts/puttyhosts_test.go
  tool/tsh/common/putty_config_windows.go
Labels: documentation, tsh, backport, size/md

#32689 [v12] Add textTransform override for resource launch buttons
  web/packages/design/src/Button/Button.jsx
  web/packages/shared/components/MenuLogin/MenuLogin.test.tsx
  web/packages/shared/components/MenuLogin/MenuLogin.tsx
  web/packages/shared/components/MenuLogin/types.ts
  web/packages/teleport/src/Apps/AppList/AwsLaunchButton/AwsLaunchButton.tsx
  web/packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
  web/packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/components/AgentButtonAdd/AgentButtonAdd.tsx
  web/packages/teleport/src/components/AgentButtonAdd/__snapshots__/AgentButtonAdd.story.test.tsx.snap
Labels: ui, backport, size/md

#32840 MenuIcon: Support arbitrary icon through Icon prop
  web/packages/shared/components/MenuAction/MenuAction.story.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32841 Connect My Computer: Improve copy and UI consistency
  web/packages/teleterm/src/agentCleanupDaemon/agentCleanupDaemon.js
  web/packages/teleterm/src/mainProcess/agentDownloader/fileDownloader.test.ts
  web/packages/teleterm/src/mainProcess/agentDownloader/fileDownloader.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.test.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerSetup/DocumentConnectMyComputerSetup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerStatus/DocumentConnectMyComputerStatus.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
Labels: ui, size/sm, backport/branch/v14

#32784 Pin Teleport Terraform Provider to Teleport major version
  docs/cspell.json
  docs/pages/reference/terraform-provider.mdx
  examples/resources/terraform/terraform-login-rules.tf
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32859 [v13] docs: update tctl tsh version location in prereqs
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/management/admin/labels.mdx
Labels: documentation, backport, size/sm

#32867 [v12] docs: remove old versions ref
  docs/pages/architecture/tls-routing.mdx
  docs/pages/management/diagnostics/tracing.mdx
Labels: documentation, backport, size/sm

#32817 [v14] Fix max_duration when session TTL is short
  web/packages/teleport/src/AccessRequests/service.ts
  web/packages/teleport/src/AccessRequests/utils.test.ts
  web/packages/teleport/src/AccessRequests/utils.ts
Labels: ui, backport, size/md

#32864 [v13] Add the internal access list review resource.
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  api/types/constants.go
Labels: backport, size/lg

#32813 [v13] re-add agentless node manual installation docs
  docs/config.json
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/guides/openssh.mdx
  docs/pages/server-access/guides/openssh/openssh-manual-install.mdx
  docs/pages/server-access/guides/openssh/openssh.mdx
Labels: documentation, backport, size/md

#32897 [v13] Pin Teleport Terraform Provider to Teleport major version
  docs/pages/reference/terraform-provider.mdx
  examples/resources/terraform/terraform-login-rules.tf
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation, backport, size/sm

#32896 [v12] Pin Teleport Terraform Provider to Teleport major version
  docs/pages/reference/terraform-provider.mdx
  examples/resources/terraform/terraform-login-rules.tf
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation, backport, size/sm

#32898 [v14] Pin Teleport Terraform Provider to Teleport major version
  docs/cspell.json
  docs/pages/reference/terraform-provider.mdx
  examples/resources/terraform/terraform-login-rules.tf
  examples/resources/terraform/terraform-user-role-cloud.tf
  examples/resources/terraform/terraform-user-role-self-hosted.tf
Labels: documentation, backport, size/sm

#32818 Update error message on GitHub OSS
  lib/services/github.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32891 [v13] MenuIcon: Support arbitrary icon through Icon prop
  web/packages/shared/components/MenuAction/MenuAction.story.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
Labels: ui, backport, size/sm

#32892 [v12] MenuIcon: Support arbitrary icon through Icon prop
  web/packages/shared/components/MenuAction/MenuAction.story.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
Labels: ui, backport, size/sm

#32874 [v12] docs: Draft of troubleshooting topics for Server Access
  docs/cspell.json
  docs/pages/server-access/troubleshooting-server.mdx
Labels: documentation, backport, size/md

#32882 [v14] docs: Add how to verify the binaries are FIPS-compliant #32169
  docs/cspell.json
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/access-controls/compliance-frameworks/soc2.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm

#32905 [v12] Bump webpki from 0.22.0 to 0.22.2
  Cargo.lock
Labels: backport, size/sm

#32906 [v13] Bump webpki from 0.22.0 to 0.22.2
  Cargo.lock
Labels: backport, size/sm

#32907 [v14] Bump webpki from 0.22.0 to 0.22.2
  Cargo.lock
Labels: backport, size/sm

#32486 Update cloud docs to 13.4.0
  docs/config.json
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32879 [v13] Replace Access Plane with Access Platform
  CHANGELOG.md
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm

#32884 [v13] Change Open source and OSS to Teleport Community Edition
  docs/config.json
  docs/pages/access-controls/access-requests.mdx
  docs/pages/access-controls/access-requests/oss-role-requests.mdx
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/access-controls/idps/saml-grafana.mdx
  docs/pages/application-access/cloud-apis/azure.mdx
  docs/pages/choose-an-edition/introduction.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/faq.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/installation.mdx
  docs/pages/management/admin/uninstall-teleport.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm

#32875 [v13] docs: Draft of troubleshooting topics for Server Access
  docs/cspell.json
  docs/pages/server-access/troubleshooting-server.mdx
Labels: documentation, backport, size/md

#32878 [v14] Replace Access Plane with Access Platform
  CHANGELOG.md
  docs/pages/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm

#32877 [v14] docs: change open source/OSS references to community edition
  docs/config.json
  docs/pages/access-controls/access-requests.mdx
  docs/pages/access-controls/access-requests/oss-role-requests.mdx
  docs/pages/access-controls/access-requests/resource-requests.mdx
  docs/pages/access-controls/access-requests/role-requests.mdx
  docs/pages/access-controls/idps/saml-grafana.mdx
  docs/pages/application-access/cloud-apis/azure.mdx
  docs/pages/choose-an-edition/introduction.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/contributing/documentation/reference.mdx
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/faq.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/includes/ent-vs-community-faq.mdx
  docs/pages/installation.mdx
  docs/pages/machine-id/reference/v14-upgrade-guide.mdx
  docs/pages/management/admin/uninstall-teleport.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/reference/terraform-provider.mdx
Labels: documentation, backport, size/sm

#32530 remove db name checkers for protocols
  lib/srv/db/common/role/role.go
  lib/srv/db/snowflake_test.go
  tool/tsh/common/db.go
Labels: tsh, database-access, size/sm

#32862 [v14] Add new methods to AccessResourcesGetter interface
  lib/modules/modules.go
Labels: backport, size/sm

#32806 chore: Address crypto/elliptic package deprecations
  lib/auth/mocku2f/mocku2f.go
  lib/auth/webauthncli/u2f_register.go
Labels: size/sm, backport/branch/v14

#32917 [v13] Fix: Add access list field to web usercontext ACL
  lib/web/ui/usercontext.go
  lib/web/ui/usercontext_test.go
  web/packages/design/src/SVGIcon/UserList.tsx
Labels: backport, size/sm

#32843 Add in audit review recurrence presets.
  api/client/events_test.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  lib/auth/userloginstate/generator_test.go
  lib/cache/cache_test.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list_test.go
  lib/services/unified_resource_test.go
  tool/tctl/common/acl_command.go
Labels: size/md, backport/branch/v13, backport/branch/v14

#32922 Fix desktop listener PROXY mode setting
  lib/service/desktop.go
Labels: desktop-access, size/sm, backport/branch/v14

#32814 Beginnings of RdpdrBackend integration
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/client/global.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/consts.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tests.rs
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, rdp, desktop-access, size/lg

#32936 Upgrade etcd version used in integration tests to v3.5.9
  .github/services/Dockerfile.etcd
  Makefile
Labels: size/sm

#32943 Fix broken etcd-ci image
  .github/services/Dockerfile.etcd
Labels: size/sm

#32889 [v14] MenuIcon: Support arbitrary icon through Icon prop
  web/packages/shared/components/MenuAction/MenuAction.story.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
Labels: ui, backport, size/sm

#32890 [v14] Connect My Computer: Improve copy and UI consistency
  web/packages/teleterm/src/agentCleanupDaemon/agentCleanupDaemon.js
  web/packages/teleterm/src/mainProcess/agentDownloader/fileDownloader.test.ts
  web/packages/teleterm/src/mainProcess/agentDownloader/fileDownloader.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.test.ts
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerSetup/DocumentConnectMyComputerSetup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputerStatus/DocumentConnectMyComputerStatus.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
Labels: ui, backport, size/sm

#32741 Machine ID Docs Refactor: Ansible Access Guide
  docs/pages/machine-id/access-guides/ansible.mdx
Labels: documentation, size/sm

#32745 Machine ID Docs Refactor: Application Access
  docs/pages/machine-id/access-guides/applications.mdx
Labels: documentation, size/sm

#32735 Machine ID Docs Refactor: SSH Access guide
  docs/pages/machine-id/access-guides/ssh.mdx
Labels: documentation, size/md

#32870 Special case TestOpenFileLinks on macOS
  lib/utils/fs_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#32915 [v13] Update error message on GitHub OSS
  lib/services/github.go
Labels: backport, size/sm

#32914 [v14] Update error message on GitHub OSS
  lib/services/github.go
Labels: backport, size/sm

#32916 [v12] Update error message on GitHub OSS
  lib/services/github.go
Labels: backport, size/sm

#32857 DiscoveryMatchers: move checkandset to types package
  api/types/constants.go
  api/types/installers/installers.go
  api/types/matchers_aws.go
  api/types/matchers_aws_test.go
  api/types/matchers_azure.go
  api/types/matchers_azure_test.go
  api/types/matchers_gcp.go
  api/types/matchers_gcp_test.go
  api/types/matchers_kube.go
  api/types/matchers_kube_test.go
  api/utils/aws/identifiers.go
  api/utils/aws/identifiers_test.go
  e2e/aws/eks_test.go
  e2e/aws/rds_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/defaults/defaults.go
  lib/services/matchers.go
  lib/srv/db/watcher_test.go
  lib/srv/discovery/common/renaming.go
  lib/srv/discovery/common/renaming_test.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/fetchers/db/aws_elasticache_test.go
  lib/srv/discovery/fetchers/db/aws_memorydb_test.go
  lib/srv/discovery/fetchers/db/aws_opensearch_test.go
  lib/srv/discovery/fetchers/db/aws_rds_proxy_test.go
  lib/srv/discovery/fetchers/db/aws_rds_test.go
  lib/srv/discovery/fetchers/db/aws_redshift_serverless_test.go
  lib/srv/discovery/fetchers/db/aws_redshift_test.go
  lib/srv/discovery/fetchers/db/azure_dbserver.go
  lib/srv/discovery/fetchers/db/azure_dbserver_test.go
  lib/srv/discovery/fetchers/db/azure_mysql_flex_test.go
  lib/srv/discovery/fetchers/db/azure_postgres_flex_test.go
  lib/srv/discovery/fetchers/db/azure_redis_test.go
  lib/srv/discovery/fetchers/db/db.go
  lib/srv/discovery/fetchers/kube_services.go
  lib/srv/server/ec2_watcher.go
  lib/utils/aws/aws.go
Labels: database-access, discover, size/lg, discovery, backport/branch/v14

#32955 [v13] Bump zod from 3.21.2 to 3.22.3
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm

#32954 [v14] Bump zod from 3.21.2 to 3.22.3
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm

#32912 Fix `kubectl log` commands when they refer to deployment instead of pod
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14

#32957 [v14] Special case TestOpenFileLinks on macOS
  lib/utils/fs_test.go
Labels: backport, size/sm

#32956 [v12] Bump zod from 3.21.2 to 3.22.3
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm

#32948 `removeSecure()` should close the file before removing it on Windows
  lib/utils/fs.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#32895 Fix switch condition in Proxy listeners setup
  lib/service/service.go
Labels: size/sm, backport/branch/v14

#32965 [v12] `removeSecure()` should close the file before removing it on Windows
  lib/utils/fs.go
Labels: backport, size/sm, changelog

#32941 Web build: patch circular dep warnings
  web/packages/teleport/src/Discover/Discover.tsx
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14

#32964 [v13] `removeSecure()` should close the file before removing it on Windows
  lib/utils/fs.go
Labels: backport, size/sm, changelog

#32933 Yarn dependency upgrades
  package.json
  web/packages/build/package.json
  yarn.lock
Labels: ui, size/lg, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32939 Web: Create (re-use) step navigator for general use
  web/packages/teleport/src/Discover/Navigation/StepItem.tsx
  web/packages/teleport/src/components/StepNavigation/Bullet.tsx
  web/packages/teleport/src/components/StepNavigation/Shared.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.story.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.test.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.tsx
  web/packages/teleport/src/components/StepNavigation/index.ts
Labels: ui, size/md, backport/branch/v13, backport/branch/v14

#32923 Attempt to fix `TestShutdownWithActiveConnections` and `TestCloseWithActiveConnections` flakiness
  lib/srv/db/server_test.go
Labels: flaky tests, database-access, size/sm

#32963 [v14] `removeSecure()` should close the file before removing it on Windows
  lib/utils/fs.go
Labels: backport, size/sm, changelog

#32977 [v14] Yarn dependency upgrades
  package.json
  web/packages/build/package.json
  yarn.lock
Labels: ui, backport, size/md

#32968 Remove integration test bypass workflows
  .github/workflows/flaky-tests-merge-queue.yaml
  .github/workflows/integration-tests-root-bypass.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/kube-integration-tests-non-root-bypass.yaml
  .github/workflows/kube-integration-tests-non-root.yaml
Labels: size/sm

#32975 [v14] Web build: patch circular dep warnings
  web/packages/teleport/src/Discover/Discover.tsx
Labels: ui, backport, size/sm

#32976 [v13] Web build: patch circular dep warnings
  web/packages/teleport/src/Discover/Discover.tsx
Labels: ui, backport, size/sm

#32780 docs: Caveat for token permissions not scoped to any resource context
  docs/pages/access-controls/reference.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32432 docs: Reduce the use of capitalized trusted clusters and a few other fixes
  docs/pages/access-controls/guides/ip-pinning.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/agents/join-services-to-your-cluster/join-token.mdx
  docs/pages/architecture/session-recording.mdx
  docs/pages/architecture/tls-routing.mdx
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/core-concepts.mdx
  docs/pages/deploy-a-cluster/deployments/aws-terraform.mdx
  docs/pages/faq.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/kubernetes-access/manage-access.mdx
  docs/pages/kubernetes-access/manage-access/federation.mdx
  docs/pages/machine-id/faq.mdx
  docs/pages/management/admin.mdx
  docs/pages/management/operations/upgrading.mdx
  docs/pages/reference/cli/tctl.mdx
  docs/pages/server-access/guides/openssh/openssh-manual-install.mdx
  docs/pages/server-access/guides/openssh/openssh.mdx
  docs/pages/server-access/rbac.mdx
Labels: documentation, size/sm, backport/branch/v14

#32988 docs: Modify new security topic about privileged access
  docs/config.json
  docs/pages/management/security.mdx
  docs/pages/management/security/restrict-privileges.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32981 Added 10/04 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#32992 [v13] Web: fix passing in fill color into wrong field
  web/packages/design/src/SVGIcon/ArrowFatLinesUp.tsx
Labels: ui, backport, size/sm

#32979 [v14] Web: Create (re-use) step navigator for general use
  web/packages/teleport/src/Discover/Navigation/StepItem.tsx
  web/packages/teleport/src/components/StepNavigation/Bullet.tsx
  web/packages/teleport/src/components/StepNavigation/Shared.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.story.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.test.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.tsx
  web/packages/teleport/src/components/StepNavigation/index.ts
Labels: ui, backport, size/md

#32985 [v13] Web: Create (re-use) step navigator for general use (#32939)
  web/packages/teleport/src/Discover/Navigation/StepItem.tsx
  web/packages/teleport/src/components/StepNavigation/Bullet.tsx
  web/packages/teleport/src/components/StepNavigation/Shared.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.story.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.test.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.tsx
  web/packages/teleport/src/components/StepNavigation/index.ts
Labels: ui, backport, size/md

#32323 fanout buffer
  lib/utils/fanoutbuffer/buffer.go
  lib/utils/fanoutbuffer/buffer_test.go
Labels: size/lg

#32547 Add cost optimized pagination search for athena
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/querier.go
  lib/events/athena/querier_test.go
Labels: audit-log, size/lg, backport/branch/v13, backport/branch/v14

#32993 Add MFARequiredCheck to CreateAuthenticateChallenge
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
Labels: size/sm

#32982 Yarn replacement version bumps
  package.json
  yarn.lock
Labels: dependencies, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#33005 Fix --debug flag in Connect & enable devtools in debug mode
  docs/pages/connect-your-client/teleport-connect.mdx
  web/packages/teleterm/src/mainProcess/agentRunner/agentRunner.ts
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/runtimeSettings.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/mainProcess/windowsManager.ts
  web/packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
Labels: documentation, ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32888 [v14] update `--db-user` and `--db-name` docs
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/includes/db-user-name-flags.mdx
  docs/pages/reference/cli/tsh.mdx
  tool/tsh/common/tsh.go
Labels: documentation, tsh, backport, size/sm

#33010 Update cloud docs to 13.4.2
  docs/config.json
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#32709 Add sort index trees to unified resource cache
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/services/unified_resource.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport-required, size/sm, backport/branch/v14

#32233 RFD 147: private fork syncing and release branch security scanning
  rfd/0147-repo-mirror.md
Labels: rfd, size/sm

#32997 chore: Bump Buf to v1.27.0
  .github/workflows/lint.yaml
  build.assets/versions.mk
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#33027 [v14] Add sort index trees to unified resource cache
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/services/unified_resource.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/md

#32807 [v14] Improved reconnection reliability across service reloads
  integration/hsm/helpers.go
  integration/hsm/hsm_test.go
  integration/hsm/reload_test.go
  lib/service/connect.go
Labels: backport, size/md

#32998 Add helper for generating request TTL options
  web/packages/teleport/src/AccessRequests/utils.test.ts
  web/packages/teleport/src/AccessRequests/utils.ts
Labels: ui, size/md, backport/branch/v14

#32924 Add the Access List review backend.
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/utils/keys/yubikey_test.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/lg, backport/branch/v13, backport/branch/v14

#33003 fix backend range keys
  lib/services/local/access.go
  lib/services/local/apps.go
  lib/services/local/assistant.go
  lib/services/local/configuration.go
  lib/services/local/databases.go
  lib/services/local/databaseservice.go
  lib/services/local/desktops.go
  lib/services/local/dynamic_access.go
  lib/services/local/generic/generic.go
  lib/services/local/inventory.go
  lib/services/local/kube.go
  lib/services/local/plugins.go
  lib/services/local/presence.go
  lib/services/local/provisioning.go
  lib/services/local/session.go
  lib/services/local/sessiontracker.go
  lib/services/local/status.go
  lib/services/local/trust.go
  lib/services/local/users.go
  lib/services/local/usertoken.go
Labels: size/sm

#32961 [v13] Add in audit review recurrence presets.
  api/client/events_test.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  lib/auth/userloginstate/generator_test.go
  lib/cache/cache_test.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list_test.go
  tool/tctl/common/acl_command.go
Labels: tctl, backport, size/md

#33034 [v14] chore: Pin golangci-lint and buf, bump buf to v1.27.0
  .github/workflows/lint.yaml
  build.assets/Dockerfile
  build.assets/Dockerfile-grpcbox
  build.assets/Makefile
  build.assets/grpcbox.mk
  build.assets/versions.mk
  devbox.json
  devbox.lock
Labels: backport, size/sm

#33040 [v12] chore: Move golangci-lint and buf to GHA, bump versions
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  build.assets/Dockerfile
  build.assets/Dockerfile-grpcbox
  build.assets/grpcbox.mk
  build.assets/versions.mk
  lib/auth/touchid/api_darwin.go
  lib/srv/desktop/rdp/rdpclient/client.go
Labels: rdp, backport, desktop-access, size/sm

#33038 [v13] chore: Move golangci-lint and buf to GHA, bump versions
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  build.assets/Dockerfile
  build.assets/Dockerfile-grpcbox
  build.assets/grpcbox.mk
  build.assets/versions.mk
  lib/auth/touchid/api_darwin.go
  lib/srv/desktop/rdp/rdpclient/client.go
Labels: rdp, backport, desktop-access, size/sm

#32994 Implement MFA verification on CreateAuthenticateChallenge
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_login_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver_test.go
Labels: size/md

#32960 [v14] Add in audit review recurrence presets.
  api/client/events_test.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/convert/v1/review.go
  api/types/accesslist/convert/v1/review_test.go
  api/types/accesslist/review.go
  api/types/accesslist/review_test.go
  lib/auth/userloginstate/generator_test.go
  lib/cache/cache_test.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list_test.go
  lib/services/unified_resource_test.go
  tool/tctl/common/acl_command.go
Labels: tctl, backport, size/md

#33046 [v14] chore: Bump Go to v1.21.2
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#33052 [v13] Correct typo in Makefile.
  Makefile
Labels: backport, size/sm

#33044 chore: Bump Go to v1.21.2
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: size/sm

#33047 [v13] chore: Bump Go to v1.20.9
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#33048 [v12] chore: Bump Go to v1.20.9
  .drone.yml
  build.assets/versions.mk
Labels: backport, size/sm

#33011 Downgrade Electron to 25.9.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, changelog, backport/branch/v14

#32952 Remove unused permissions from App role
  lib/authz/permissions.go
Labels: size/sm

#32842 Deflake `TestInteractiveSessionsNoAuth` test
  lib/auth/helpers.go
  lib/kube/proxy/utils_testing.go
Labels: kubernetes-access, size/sm

#32962 [v14] Fix `kubectl log` commands when they refer to deployment instead of pod
  docs/pages/management/operations/enroll-agent-into-automatic-updates.mdx
Labels: documentation, backport, size/sm

#32966 [v14] Fix switch condition in Proxy listeners setup
  lib/service/service.go
Labels: backport, size/sm

#33060 [v12] Downgrade Electron to 25.9.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, changelog

#33058 [v14] Downgrade Electron to 25.9.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, changelog

#33059 [v13] Downgrade Electron to 25.9.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, changelog

#33017 docs: title zypper enterprise linux install tab
  docs/pages/includes/install-linux-ent-self-hosted.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14

#33009 docs: update fips docker address
  docs/pages/installation.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#33042 Update docker tag images to v15
  .drone.yml
  build.assets/images.mk
  dronegen/container_images.go
Labels: size/sm

#33062 Web: add link to CloudShell on EICE/EC2 Discover flow
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/Discover/Server/EnrollEc2Instance/Ec2InstanceList.tsx
Labels: ui, discover, size/sm, backport/branch/v13, backport/branch/v14

#33057 [v14] AWS OIDC - EICE: improve error when EC2 does not accept SSH connections
  lib/integrations/awsoidc/eice_opentunnel.go
  lib/integrations/awsoidc/eice_opentunnel_test.go
  lib/reversetunnel/localsite.go
Labels: backport, size/sm

#33029 [v13] Access request promotion
  api/client/accesslist/accesslist.go
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/access_request.go
  api/types/events/events.pb.go
  api/types/types.pb.go
  integrations/access/common/app.go
  integrations/access/jira/app.go
  integrations/access/jira/plugindata.go
  integrations/access/opsgenie/app.go
  integrations/access/opsgenie/plugindata.go
  integrations/access/pagerduty/app.go
  integrations/access/pagerduty/plugindata.go
  integrations/lib/plugindata/access_request.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/modules/modules.go
  lib/modules/test.go
  lib/services/access_list.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/local/access_list.go
  lib/services/local/dynamic_access.go
  lib/services/local/generic/generic.go
  lib/services/user_login_state.go
  tool/teleport/testenv/test_server.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/md

#33071 [v14] Update cloud docs to 13.4.2
  docs/config.json
Labels: documentation, backport, size/sm

#33073 [v12] Update cloud docs to 13.4.2
  docs/config.json
Labels: documentation, backport, size/sm

#33072 [v13] Update cloud docs to 13.4.2
  docs/config.json
Labels: documentation, backport, size/sm

#33070 [v14] Add the Access List review backend.
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: backport, size/lg

#33006 [v13] Add cost optimized pagination search for athena
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/querier.go
  lib/events/athena/querier_test.go
Labels: audit-log, backport, size/lg

#33007 [v14] Add cost optimized pagination search for athena
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/querier.go
  lib/events/athena/querier_test.go
Labels: audit-log, backport, size/lg

#32911 Reliability improvements for HSM tests
  integration/hsm/helpers.go
  integration/hsm/hsm_test.go
  lib/service/service.go
Labels: size/sm, backport/branch/v14
