Repository gravitational/teleport, pull requests merged in 2024-03, with the labels that each got.

#38804 [v15] Ignore the status field in access list operator tests.
  integrations/operator/controllers/resources/testlib/accesslist_controller_tests.go
Labels: backport, size/sm, no-changelog

#38793 Add RPCs for RemoteCluster transition to gRPC
  api/gen/proto/go/teleport/presence/v1/service.pb.go
  api/gen/proto/go/teleport/presence/v1/service_grpc.pb.go
  api/proto/teleport/presence/v1/service.proto
Labels: size/sm, no-changelog

#38803 [v15] Add a timeout to graceful shutdown and reload
  lib/service/signals.go
Labels: backport, size/sm

#38845 Fix missing error check
  api/types/events/events.go
  lib/config/configuration.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38834 [v15] Add note about auth and proxy services
  docs/pages/upgrading/cloud-linux.mdx
Labels: documentation, backport, size/sm

#38835 [v14] Add note about auth and proxy services (#38744)
  docs/pages/upgrading/cloud-linux.mdx
Labels: documentation, backport, size/sm

#38840 Update docs for `tbot-distroless` image
  docs/pages/installation.mdx
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38682 Simplify and fix Kubernetes Getting Started guide
  docs/pages/kubernetes-access/getting-started.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#38850 Properly check `AccessList.status` for nillness
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
Labels: size/sm, backport/branch/v15

#38483 [v14] Clarify on-prem usage reporting and trusted clusters
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#38848 Add a Discovery Service section
  CHANGELOG.md
  docs/config.json
  docs/pages/api/automatically-register-agents.mdx
  docs/pages/application-access/guides/dynamic-registration.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/auto-discovery/databases.mdx
  docs/pages/auto-discovery/introduction.mdx
  docs/pages/auto-discovery/kubernetes-applications.mdx
  docs/pages/auto-discovery/kubernetes-applications/architecture.mdx
  docs/pages/auto-discovery/kubernetes-applications/get-started.mdx
  docs/pages/auto-discovery/kubernetes-applications/reference.mdx
  docs/pages/auto-discovery/kubernetes.mdx
  docs/pages/auto-discovery/kubernetes/aws.mdx
  docs/pages/auto-discovery/kubernetes/azure.mdx
  docs/pages/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/auto-discovery/servers.mdx
  docs/pages/auto-discovery/servers/azure-discovery.mdx
  docs/pages/auto-discovery/servers/ec2-discovery.mdx
  docs/pages/auto-discovery/servers/gcp-discovery.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/documentation-overview.mdx
  docs/pages/includes/database-access/alternative-methods-join.mdx
  docs/pages/includes/database-access/aws-auto-discovery-prerequisite.mdx
  docs/pages/includes/database-access/guides.mdx
  docs/pages/includes/discovery/discovery-group.mdx
  docs/pages/includes/discovery/step-description.mdx
  docs/pages/includes/discovery/troubleshooting.mdx
  docs/pages/kubernetes-access/controls.mdx
  docs/pages/kubernetes-access/faq.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/kubernetes-access/register-clusters.mdx
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  docs/pages/server-access/guides.mdx
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#38838 [v15] Add in documentation for Okta access list synchronization.
  docs/img/enterprise/plugins/okta/okta-access-list-group-filtering.png
  docs/pages/application-access/okta/hosted-guide.mdx
  docs/pages/application-access/okta/sync-scim.mdx
Labels: documentation, backport, size/md, no-changelog

#38729 Add admin user in the `teleport-cluster` guide
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38749 Change CONTRIBUTING link for docs contributors
  CONTRIBUTING.md
Labels: size/sm, no-changelog

#38766 Add `tsh`/`tctl` instructions to upgrading guides
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
  docs/pages/upgrading/self-hosted-linux.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38784 docs: update usage based address to show as https
  docs/pages/usage-billing.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38867 [v15] Update docs for `tbot-distroless` image
  docs/pages/installation.mdx
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, backport, size/sm, no-changelog

#38750 [v14] Remove ScopedBlocks from the docs (#38698)
  docs/pages/database-access/guides/clickhouse-self-hosted.mdx
Labels: documentation, backport, size/sm, no-changelog

#38860 [v14] Simplify and fix Kubernetes Getting Started guide
  docs/pages/kubernetes-access/getting-started.mdx
Labels: documentation, backport, size/sm, no-changelog

#38832 [v14] Leverage the inventory control stream to report updater metrics (#38654)
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
Labels: backport, size/sm

#38831 [v15] Leverage the inventory control stream to report updater metrics
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
Labels: backport, size/sm

#38866 [v15] Bump github.com/dvsekhvalnov/jose2go to 1.6.0
  go.mod
  go.sum
Labels: go, backport, dependencies, size/sm, no-changelog

#38806 Move lib/web tests to new web login helpers
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38842 [v15] SSH connection hand-over
  lib/resumption/handover.go
  lib/resumption/handover_test.go
  lib/resumption/resumption_test.go
  lib/resumption/server_detect.go
  lib/resumption/server_exchange.go
  lib/service/service.go
Labels: backport, size/md

#38327 Introduce Notifications CRUD Service
  api/gen/proto/go/teleport/notifications/v1/notifications.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service_grpc.pb.go
  api/proto/teleport/notifications/v1/notifications.proto
  api/proto/teleport/notifications/v1/notifications_service.proto
  api/types/constants.go
  lib/services/local/generic/generic_wrapper.go
  lib/services/local/generic/generic_wrapper_test.go
  lib/services/local/notifications.go
  lib/services/local/notifications_test.go
  lib/services/notifications.go
  lib/services/notifications_test.go
Labels: size/lg, no-changelog, backport/branch/v15

#38874 [v15] Tweak docs to account for the timeout in SIGHUP/SIGQUIT
  docs/pages/management/admin/daemon.mdx
  docs/pages/reference/signals.mdx
Labels: documentation, backport, size/sm, no-changelog

#38685 Filter terminated sessions out of tsh sessions ls ouput
  tool/tsh/common/tsh.go
Labels: tsh, size/sm, backport/branch/v14, backport/branch/v15

#38877 [v13] docs: update usage based address to show port number
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#38875 [v15] docs: update usage based address to show port number
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#36425 RFD 0123 update: TLS routing conn upgrade with WebSocket support
  rfd/0123-tls-routing-behind-layer7-lb.md
Labels: rfd, size/sm, no-changelog

#38817 [v13] Fix relogin on hardware key policy errors
  lib/client/api.go
  lib/client/api_test.go
Labels: backport, size/sm

#38819 [v15] Fix relogin on hardware key policy errors
  lib/client/api.go
  lib/client/api_test.go
Labels: backport, size/sm

#38861 [v15] Properly check `AccessList.status` for nillness
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
Labels: backport, size/sm

#38896 Release 15.1.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#38886 [v14] Filter terminated sessions out of tsh sessions ls ouput
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm

#38887 [v15] Filter terminated sessions out of tsh sessions ls ouput
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm

#38343 [v15] Document the new screen_size field for windows desktops
  .github/ISSUE_TEMPLATE/testplan.md
  docs/pages/desktop-access/reference/configuration.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/sm, no-changelog

#38833 [v13] Leverage the inventory control stream to report updater metrics (#38654)
  lib/auth/auth.go
  lib/auth/periodic.go
  lib/auth/periodic_test.go
Labels: backport, size/sm

#38905 [v15] Adds a `Windows Desktop Service` section to scaling
  docs/pages/desktop-access/reference.mdx
  docs/pages/management/operations/scaling.mdx
Labels: documentation, backport, size/sm, no-changelog

#38854 [v14] Fix missing error check
  api/types/events/events.go
  lib/config/configuration.go
Labels: backport, size/sm, no-changelog

#38855 [v15] Fix missing error check
  api/types/events/events.go
  lib/config/configuration.go
Labels: backport, size/sm, no-changelog

#38844 Fix memory leak caused by `otelhttp`
  api/go.mod
  api/observability/tracing/http/http.go
  go.mod
  lib/observability/tracing/tracing.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38841 Skip auto-update blockmaps when building Connect
  web/packages/teleterm/electron-builder-config.js
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38761 [v13] Fix DynamoDB BatchWriteItemInput items limit
  lib/backend/dynamo/dynamodbbk.go
  lib/backend/test/suite.go
Labels: backport, size/sm

#38920 [v15] Skip auto-update blockmaps when building Connect
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm, no-changelog

#38872 [v14] Add admin user in the `teleport-cluster` guide
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
Labels: documentation, backport, size/sm, no-changelog

#38879 [v14] Add `tsh`/`tctl` instructions to upgrading guides
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
  docs/pages/upgrading/self-hosted-linux.mdx
Labels: documentation, backport, size/sm, no-changelog

#38398 Machine ID: Share a single bot identity auth client rather than creating multiple clients
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
Labels: machine-id, size/sm, backport/branch/v14, backport/branch/v15

#38880 [v15] Add `tsh`/`tctl` instructions to upgrading guides
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
  docs/pages/upgrading/self-hosted-linux.mdx
Labels: documentation, backport, size/sm, no-changelog

#38918 [v13] Skip auto-update blockmaps when building Connect
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm, no-changelog

#38928 [v15] Machine ID: Share a single bot identity auth client rather than creating multiple clients
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm

#38893 fix access request test cache sync
  lib/auth/access_request_test.go
Labels: size/sm, no-changelog

#38899 Remove 15.1.0, bump 15.1.1 to 15.2.2 from upcoming-releases
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#37808 Implement granular db permissions for Postgres (RFD 151)
  api/utils/slices.go
  api/utils/slices_test.go
  go.mod
  lib/auth/init.go
  lib/services/access_checker.go
  lib/services/role_test.go
  lib/srv/db/autousers_test.go
  lib/srv/db/common/permissions/calculation.go
  lib/srv/db/common/permissions/calculation_test.go
  lib/srv/db/common/permissions/import_rules.go
  lib/srv/db/common/permissions/import_rules_test.go
  lib/srv/db/common/permissions/presets.go
  lib/srv/db/common/permissions/presets_test.go
  lib/srv/db/common/state.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/schema.go
  lib/srv/db/postgres/sql/remove-permissions.sql
  lib/srv/db/postgres/sql/update-permissions.sql
  lib/srv/db/postgres/test.go
  lib/srv/db/postgres/users.go
  lib/srv/db/postgres/users_test.go
Labels: database-access, size/xl, backport/branch/v15

#38873 [v15] Add admin user in the `teleport-cluster` guide
  docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
Labels: documentation, backport, size/sm, no-changelog

#38528 Add missing redirects
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#38889 [v14] Move lib/web tests to new web login helpers
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: backport, size/md, no-changelog

#38885 [v15] Move lib/web tests to new web login helpers
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: backport, size/md, no-changelog

#38941 [v15] Clarify home directory creation in host user creation docs
  docs/pages/server-access/guides/host-user-creation.mdx
Labels: documentation, backport, size/sm, no-changelog

#38929 [v14] Machine ID: Share a single bot identity auth client rather than creating multiple clients
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm

#38926 AWS-OIDC: add `ListRolePolicies` and `ListAttachedRolePolicies`
  lib/cloud/aws/policy_statements.go
  lib/cloud/clients.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/fetchers/aws-sync/s3.go
Labels: size/sm, no-changelog

#38807 Allow password change with identity verification
  api/gen/proto/go/teleport/mfa/v1/mfa.pb.go
  api/proto/teleport/mfa/v1/mfa.proto
  lib/auth/accountrecovery_test.go
  lib/auth/auth_login_test.go
  lib/auth/auth_test.go
  lib/auth/methods.go
  lib/auth/password.go
  lib/auth/password_test.go
  lib/auth/webauthn/login.go
  lib/web/mfa.go
  web/packages/teleport/src/Account/ChangePassword/useChangePassword.ts
  web/packages/teleport/src/services/auth/auth.ts
  web/packages/teleport/src/services/auth/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v15

#38694 Refactor Presence service to add ListRemoteClusters, context.Context and returning updated/created RemoteClusters
  integration/integration_test.go
  integration/kube_integration_test.go
  lib/auth/api.go
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver_test.go
  lib/auth/http_client.go
  lib/auth/init.go
  lib/auth/tls_test.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/client/client.go
  lib/proxy/router.go
  lib/reversetunnel/srv.go
  lib/reversetunnelclient/api_with_roles.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/local/services_test.go
  lib/services/presence.go
  lib/services/suite/suite.go
  lib/tbot/config/bot.go
  lib/tbot/config/bot_test.go
  lib/tbot/config/template_ssh_client.go
  lib/tbot/service_outputs.go
  lib/web/apiserver.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
  tool/tctl/common/resource_command.go
  tool/tsh/common/config.go
  tool/tsh/common/tsh.go
Labels: tsh, tctl, machine-id, size/md, no-changelog

#38958 Update `electron-builder`
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  yarn.lock
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38959 [v15] Bump mio from 0.8.9 to 0.8.11
  Cargo.lock
Labels: backport, dependencies, rust, size/sm, no-changelog

#38811 Move lib/web tests to new web login MFA helpers
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38963 Fix dependabot Go configuration for "/"
  .github/dependabot.yml
Labels: size/sm, no-changelog

#38950 teleport configure - Accept `--insecure` flag with awsoidc-idp configure
  tool/teleport/common/teleport.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#38891 [Web] Update database connection instructions
  web/packages/shared/services/databases/databases.ts
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.story.tsx
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.test.tsx
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.tsx
  web/packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
Labels: ui, size/sm, backport/branch/v14, backport/branch/v15

#38968 [v13] Move lib/web tests to new web login MFA helpers
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: backport, size/sm, no-changelog

#38970 [v15] Move lib/web tests to new web login MFA helpers
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: backport, size/sm, no-changelog

#38967 [v13] Update `electron-builder`
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  yarn.lock
Labels: ui, backport, size/sm

#38964 [v15] Update `electron-builder`
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  yarn.lock
Labels: ui, backport, size/sm

#38183 RFD 0165 - SSH Connection Hand-over
  rfd/0165-ssh-connection-handover.md
Labels: rfd, size/sm, no-changelog

#38969 [v14] Move lib/web tests to new web login MFA helpers
  lib/web/apiserver_login_test.go
  lib/web/apiserver_test.go
  lib/web/login_helper_test.go
Labels: backport, size/sm, no-changelog

#38983 [v15] chore: Bump Go to v1.21.8
  build.assets/versions.mk
  go.mod
Labels: size/sm

#38985 [v14] chore: Bump Go to v1.21.8
  build.assets/versions.mk
  go.mod
Labels: size/sm

#38986 [v13] chore: Bump Go to v1.21.8
  build.assets/versions.mk
Labels: size/sm

#38706 Consolidate webasset bundle to single chunks
  web/packages/build/vite/config.ts
  web/packages/teleport/src/AccessRequests/index.ts
  web/packages/teleport/src/Account/Account.test.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/AccountNew.ts
  web/packages/teleport/src/Account/index.ts
  web/packages/teleport/src/AppLauncher/index.ts
  web/packages/teleport/src/Audit/Audit.story.tsx
  web/packages/teleport/src/Audit/Audit.tsx
  web/packages/teleport/src/Audit/index.tsx
  web/packages/teleport/src/AuthConnectors/index.ts
  web/packages/teleport/src/Bots/Add/index.tsx
  web/packages/teleport/src/Bots/index.ts
  web/packages/teleport/src/Clusters/index.ts
  web/packages/teleport/src/Console/index.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/index.ts
  web/packages/teleport/src/DeviceTrust/index.ts
  web/packages/teleport/src/Discover/index.tsx
  web/packages/teleport/src/HeadlessRequest/index.ts
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/index.ts
  web/packages/teleport/src/Integrations/Enroll/IntegrationRoute.tsx
  web/packages/teleport/src/Integrations/Enroll/index.ts
  web/packages/teleport/src/Integrations/index.ts
  web/packages/teleport/src/LocksV2/Locks/index.ts
  web/packages/teleport/src/LocksV2/NewLock/LockCheckout/index.ts
  web/packages/teleport/src/LocksV2/NewLock/index.ts
  web/packages/teleport/src/Login/Login.story.tsx
  web/packages/teleport/src/Login/Login.test.tsx
  web/packages/teleport/src/Login/Login.tsx
  web/packages/teleport/src/Login/LoginFailed.tsx
  web/packages/teleport/src/Login/LoginSuccess.test.tsx
  web/packages/teleport/src/Login/LoginSuccess.tsx
  web/packages/teleport/src/Login/index.ts
  web/packages/teleport/src/Main/index.ts
  web/packages/teleport/src/Nodes/index.ts
  web/packages/teleport/src/Player/Player.story.tsx
  web/packages/teleport/src/Player/Player.tsx
  web/packages/teleport/src/Player/index.ts
  web/packages/teleport/src/Recordings/Recordings.story.tsx
  web/packages/teleport/src/Recordings/Recordings.tsx
  web/packages/teleport/src/Recordings/index.ts
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Roles/index.ts
  web/packages/teleport/src/Sessions/Sessions.tsx
  web/packages/teleport/src/Sessions/index.js
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/index.ts
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/TrustedClusters/index.ts
  web/packages/teleport/src/UnifiedResources/index.ts
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/index.ts
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/Welcome/Welcome.story.tsx
  web/packages/teleport/src/Welcome/Welcome.test.tsx
  web/packages/teleport/src/Welcome/Welcome.tsx
  web/packages/teleport/src/Welcome/index.ts
  web/packages/teleport/src/features.tsx
Labels: ui, backport-required, size/sm, no-changelog, backport/branch/v15

#38982 chore: Bump Go to v1.22.1
  build.assets/versions.mk
  go.mod
Labels: size/sm, no-changelog

#38952 build: Remove docker builder from building buildboxes
  .github/workflows/build-ci-buildbox-images.yaml
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
  build.assets/Makefile
  build.assets/arch.mk
Labels: size/sm, no-changelog, backport/branch/v15

#38996 [v15] build: Remove docker builder from building buildboxes
  .github/workflows/build-ci-buildbox-images.yaml
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
  build.assets/Makefile
  build.assets/arch.mk
Labels: backport, size/sm, no-changelog

#38937 Enable automatic upgrade server by default
  integration/proxy/automaticupgrades_test.go
  lib/automaticupgrades/channel.go
  lib/automaticupgrades/channel_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: size/sm, backport/branch/v14, backport/branch/v15

#37492 Add aggregated usage report fields for bot joins and issued certs
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  lib/usagereporter/teleport/aggregating/reporter.go
  proto/prehog/v1/teleport.proto
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#38962 [v15] Always verify the old password when changing it
  lib/auth/methods.go
  lib/auth/password.go
  lib/auth/password_test.go
Labels: backport, size/sm

#38717 [v15] Treat "expired certs" errors returned from RPCs as retryable on the client side
  api/client/errors.go
  lib/auth/auth_with_roles.go
  lib/client/api.go
Labels: backport, size/sm, no-changelog

#38335 [v15] Upgrade `grpc-ecosystem/go-grpc-middleware/v2` from release candidate (#38319)
  go.mod
  go.sum
  lib/auth/middleware.go
  lib/observability/metrics/prometheus.go
  lib/service/connect.go
Labels: backport, size/sm, no-changelog

#38966 [v14] Update `electron-builder`
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  yarn.lock
Labels: ui, backport, size/sm

#39015 Fix the import on the account settings page
  web/packages/teleport/src/features.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v15

#38728 A new password change wizard
  web/packages/teleport/src/Account/Account.story.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/ChangePassword/useChangePassword.ts
  web/packages/teleport/src/Account/ChangePasswordWizard/ChangePasswordWizard.story.tsx
  web/packages/teleport/src/Account/ChangePasswordWizard/ChangePasswordWizard.test.tsx
  web/packages/teleport/src/Account/ChangePasswordWizard/ChangePasswordWizard.tsx
  web/packages/teleport/src/Account/ChangePasswordWizard/index.ts
  web/packages/teleport/src/Account/DialogHeader.tsx
  web/packages/teleport/src/Account/ManageDevices/AddAuthDeviceWizard/AddAuthDeviceWizard.tsx
  web/packages/teleport/src/Account/ManageDevices/AuthDeviceList/AuthDeviceList.story.tsx
  web/packages/teleport/src/Account/ManageDevices/AuthDeviceList/AuthDeviceList.test.tsx
  web/packages/teleport/src/Account/PasswordBox.tsx
  web/packages/teleport/src/services/mfa/makeMfaDevice.ts
  web/packages/teleport/src/services/mfa/types.ts
Labels: ui, size/lg, backport/branch/v15

#39017 [v15] Enable automatic upgrade server by default
  integration/proxy/automaticupgrades_test.go
  lib/automaticupgrades/channel.go
  lib/automaticupgrades/channel_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: backport, size/sm, discovery

#38979 Add web support for the "device.webtoken.create" event
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, no-changelog

#38989 [v15] Consolidate webasset bundle to single chunks
  web/packages/build/vite/config.ts
  web/packages/teleport/src/AccessRequests/index.ts
  web/packages/teleport/src/Account/Account.test.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/AccountNew.ts
  web/packages/teleport/src/Account/index.ts
  web/packages/teleport/src/AppLauncher/index.ts
  web/packages/teleport/src/Audit/Audit.story.tsx
  web/packages/teleport/src/Audit/Audit.tsx
  web/packages/teleport/src/Audit/index.tsx
  web/packages/teleport/src/AuthConnectors/AuthConnectors.tsx
  web/packages/teleport/src/AuthConnectors/index.ts
  web/packages/teleport/src/Bots/Add/index.tsx
  web/packages/teleport/src/Bots/index.ts
  web/packages/teleport/src/Clusters/index.ts
  web/packages/teleport/src/Console/index.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/index.ts
  web/packages/teleport/src/DeviceTrust/index.ts
  web/packages/teleport/src/Discover/index.tsx
  web/packages/teleport/src/HeadlessRequest/index.ts
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/index.ts
  web/packages/teleport/src/Integrations/Enroll/IntegrationRoute.tsx
  web/packages/teleport/src/Integrations/Enroll/index.ts
  web/packages/teleport/src/Integrations/index.ts
  web/packages/teleport/src/LocksV2/Locks/index.ts
  web/packages/teleport/src/LocksV2/NewLock/LockCheckout/index.ts
  web/packages/teleport/src/LocksV2/NewLock/index.ts
  web/packages/teleport/src/Login/Login.story.tsx
  web/packages/teleport/src/Login/Login.test.tsx
  web/packages/teleport/src/Login/Login.tsx
  web/packages/teleport/src/Login/LoginFailed.tsx
  web/packages/teleport/src/Login/LoginSuccess.test.tsx
  web/packages/teleport/src/Login/LoginSuccess.tsx
  web/packages/teleport/src/Login/index.ts
  web/packages/teleport/src/Main/index.ts
  web/packages/teleport/src/Nodes/index.ts
  web/packages/teleport/src/Player/Player.story.tsx
  web/packages/teleport/src/Player/Player.tsx
  web/packages/teleport/src/Player/index.ts
  web/packages/teleport/src/Recordings/Recordings.story.tsx
  web/packages/teleport/src/Recordings/Recordings.tsx
  web/packages/teleport/src/Recordings/index.ts
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Roles/index.ts
  web/packages/teleport/src/Sessions/Sessions.tsx
  web/packages/teleport/src/Sessions/index.js
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/index.ts
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/TrustedClusters/index.ts
  web/packages/teleport/src/UnifiedResources/index.ts
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/index.ts
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/Welcome/Welcome.story.tsx
  web/packages/teleport/src/Welcome/Welcome.test.tsx
  web/packages/teleport/src/Welcome/Welcome.tsx
  web/packages/teleport/src/Welcome/index.ts
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#38945 [v15] Implement granular db permissions for Postgres (RFD 151)
  api/utils/slices.go
  api/utils/slices_test.go
  go.mod
  lib/auth/init.go
  lib/services/access_checker.go
  lib/services/role_test.go
  lib/srv/db/autousers_test.go
  lib/srv/db/common/permissions/calculation.go
  lib/srv/db/common/permissions/calculation_test.go
  lib/srv/db/common/permissions/import_rules.go
  lib/srv/db/common/permissions/import_rules_test.go
  lib/srv/db/common/permissions/presets.go
  lib/srv/db/common/permissions/presets_test.go
  lib/srv/db/common/state.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/schema.go
  lib/srv/db/postgres/sql/remove-permissions.sql
  lib/srv/db/postgres/sql/update-permissions.sql
  lib/srv/db/postgres/test.go
  lib/srv/db/postgres/users.go
  lib/srv/db/postgres/users_test.go
Labels: database-access, backport, size/xl

#39023 Revert "[v15] Consolidate webasset bundle to single chunks"
  web/packages/build/vite/config.ts
  web/packages/teleport/src/AccessRequests/index.ts
  web/packages/teleport/src/Account/Account.test.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/AccountNew.ts
  web/packages/teleport/src/Account/index.ts
  web/packages/teleport/src/AppLauncher/index.ts
  web/packages/teleport/src/Audit/Audit.story.tsx
  web/packages/teleport/src/Audit/Audit.tsx
  web/packages/teleport/src/Audit/index.tsx
  web/packages/teleport/src/AuthConnectors/AuthConnectors.tsx
  web/packages/teleport/src/AuthConnectors/index.ts
  web/packages/teleport/src/Bots/Add/index.tsx
  web/packages/teleport/src/Bots/index.ts
  web/packages/teleport/src/Clusters/index.ts
  web/packages/teleport/src/Console/index.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/index.ts
  web/packages/teleport/src/DeviceTrust/index.ts
  web/packages/teleport/src/Discover/index.tsx
  web/packages/teleport/src/HeadlessRequest/index.ts
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/index.ts
  web/packages/teleport/src/Integrations/Enroll/IntegrationRoute.tsx
  web/packages/teleport/src/Integrations/Enroll/index.ts
  web/packages/teleport/src/Integrations/index.ts
  web/packages/teleport/src/LocksV2/Locks/index.ts
  web/packages/teleport/src/LocksV2/NewLock/LockCheckout/index.ts
  web/packages/teleport/src/LocksV2/NewLock/index.ts
  web/packages/teleport/src/Login/Login.story.tsx
  web/packages/teleport/src/Login/Login.test.tsx
  web/packages/teleport/src/Login/Login.tsx
  web/packages/teleport/src/Login/LoginFailed.tsx
  web/packages/teleport/src/Login/LoginSuccess.test.tsx
  web/packages/teleport/src/Login/LoginSuccess.tsx
  web/packages/teleport/src/Login/index.ts
  web/packages/teleport/src/Main/index.ts
  web/packages/teleport/src/Nodes/index.ts
  web/packages/teleport/src/Player/Player.story.tsx
  web/packages/teleport/src/Player/Player.tsx
  web/packages/teleport/src/Player/index.ts
  web/packages/teleport/src/Recordings/Recordings.story.tsx
  web/packages/teleport/src/Recordings/Recordings.tsx
  web/packages/teleport/src/Recordings/index.ts
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Roles/index.ts
  web/packages/teleport/src/Sessions/Sessions.tsx
  web/packages/teleport/src/Sessions/index.js
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/index.ts
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/TrustedClusters/index.ts
  web/packages/teleport/src/UnifiedResources/index.ts
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/index.ts
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/Welcome/Welcome.story.tsx
  web/packages/teleport/src/Welcome/Welcome.test.tsx
  web/packages/teleport/src/Welcome/Welcome.tsx
  web/packages/teleport/src/Welcome/index.ts
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#38240 GCP MySQL IAM Auth support
  lib/cloud/gcp/sql.go
  lib/cloud/mocks/gcp.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/gcp.go
  lib/srv/db/mysql/gcp_test.go
Labels: database-access, size/md, backport/branch/v13, backport/branch/v14, backport/branch/v15

#39028 Use an absolute path in `ExecReload` in `teleport.service`
  examples/systemd/teleport.service
Labels: size/sm, backport/branch/v15

#39027 [v15] [Web] Update database connection instructions
  web/packages/shared/services/databases/databases.ts
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.story.tsx
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.test.tsx
  web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.tsx
  web/packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
Labels: ui, backport, size/sm

#38955 Make calls to the auth server concurrently
  lib/teleterm/clusters/cluster.go
  lib/teleterm/services/userpreferences/userpreferences.go
Labels: teleport-connect, size/sm, no-changelog, backport/branch/v15

#38709 Deprecate `kindAppOrSAMLIdPServiceProvider, AppServerOrSAMLIdPServiceProvider` and use `types.SAMLIdPServiceProvider`
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/appserver_or_saml_idp_sp.go
  api/types/constants.go
  api/types/saml_idp_service_provider.go
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/services/matchers.go
  lib/services/matchers_test.go
  lib/services/unified_resource.go
  lib/teleterm/services/unifiedresources/unifiedresources.go
  lib/teleterm/services/unifiedresources/unififedresources_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/apps.go
  lib/web/ui/app.go
  lib/web/ui/app_test.go
Labels: size/sm, no-changelog

#36596 Improve Linux installation instructions
  docs/pages/access-controls/access-request-plugins/opsgenie.mdx
  docs/pages/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/desktop-access/active-directory-manual.mdx
  docs/pages/desktop-access/active-directory.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/getting-started.mdx
Labels: documentation, size/md, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38981 Add CompareResources support for custom equals functions.
  .github/workflows/lint.yaml
  Makefile
  api/types/derived.gen.go
  api/types/okta.go
  api/types/okta_test.go
  api/types/resource.go
  api/types/resource_test.go
  build.assets/tooling/cmd/goderive/main.go
  build.assets/tooling/cmd/goderive/plugin/teleportequal/teleportequal.go
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  lib/services/compare.go
  lib/services/compare_test.go
Labels: size/lg, no-changelog, backport/branch/v15

#39048 [v15] Add CompareResources support for custom equals functions.
  .github/workflows/lint.yaml
  Makefile
  api/types/derived.gen.go
  api/types/okta.go
  api/types/okta_test.go
  api/types/resource.go
  api/types/resource_test.go
  build.assets/tooling/cmd/goderive/main.go
  build.assets/tooling/cmd/goderive/plugin/teleportequal/teleportequal.go
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  lib/services/compare.go
  lib/services/compare_test.go
Labels: backport, size/lg, no-changelog

#39012 [v15] Cache remote clients in Connect
  integration/teleterm_test.go
  lib/teleterm/apiserver/handler/handler_apps.go
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/apiserver/handler/handler_databases.go
  lib/teleterm/apiserver/middleware.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_gateways.go
  lib/teleterm/clusters/cluster_headless.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/teleterm/clusters/cluster_leaves.go
  lib/teleterm/clusters/cluster_servers.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_headless.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/services/clientcache/clientcache.go
  lib/teleterm/services/userpreferences/userpreferences.go
  web/packages/teleterm/src/ui/utils/retryWithRelogin.ts
Labels: ui, backport, size/md

#39045 Extend EC2 joining method to other AWS regions
  lib/auth/aws_certs.go
Labels: size/md, backport/branch/v13, backport/branch/v14, backport/branch/v15

#39016 Add ButtonWithMenu
  web/packages/design/src/Button/Button.jsx
  web/packages/design/src/ButtonWithMenu/ButtonWithMenu.test.tsx
  web/packages/design/src/ButtonWithMenu/ButtonWithMenu.tsx
  web/packages/design/src/ButtonWithMenu/index.ts
  web/packages/design/src/Menu/Menu.jsx
  web/packages/design/src/buttons.story.tsx
  web/packages/design/src/index.ts
  web/packages/shared/components/FieldInput/__snapshots__/FieldInput.test.tsx.snap
  web/packages/teleport/src/AccessRequests/__snapshots__/AccessRequests.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Login/__snapshots__/LoginSuccess.test.tsx.snap
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
  web/packages/teleport/src/Welcome/NewCredentials/__snapshots__/NewCredentials.story.test.tsx.snap
  web/packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.tsx
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
Labels: ui, size/md, no-changelog, backport/branch/v15

#39014 Add rotate360 keyframes
  web/packages/design/src/Indicator/Indicator.jsx
  web/packages/design/src/index.ts
  web/packages/design/src/keyframes.ts
  web/packages/shared/components/ClusterDropdown/ClusterDropdown.story.tsx
  web/packages/teleport/src/Assist/Conversation/CommandResultEntry.tsx
  web/packages/teleport/src/Assist/MessageBox/MessageBox.tsx
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/ProgressBar.tsx
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39052 [v14] Extend EC2 joining method to other AWS regions
  lib/auth/aws_certs.go
Labels: backport, size/md

#39051 [v15] Extend EC2 joining method to other AWS regions
  lib/auth/aws_certs.go
Labels: backport, size/md

#39058 Remove `auth.ClientI` from `tbot`
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/tbot.go
  lib/tbot/testhelpers/srv.go
Labels: machine-id, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39025 fix: Remove multiple group attempts from Dependabot
  .github/dependabot.yml
Labels: size/sm, no-changelog

#39038 Remove the Teleport Team mention from the README
  README.md
Labels: size/sm

#39061 [v15] Remove `auth.ClientI` from `tbot`
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/tbot.go
  lib/tbot/testhelpers/srv.go
Labels: backport, machine-id, size/sm, no-changelog

#39037 [v14] Remove Teleport Team mentions from the docs
  docs/config.json
  docs/pages/access-controls/access-graph.mdx
  docs/pages/access-controls/access-graph/self-hosted-helm.mdx
  docs/pages/access-controls/access-graph/self-hosted.mdx
  docs/pages/access-controls/idps/saml-guide.mdx
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/agents/deploy-agents-terraform.mdx
  docs/pages/ai-assist.mdx
  docs/pages/choose-an-edition/introduction.mdx
  docs/pages/choose-an-edition/teleport-cloud/external-audit-storage.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/choose-an-edition/teleport-cloud/get-started.mdx
  docs/pages/choose-an-edition/teleport-cloud/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/core-concepts.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/documentation-overview.mdx
  docs/pages/faq.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/includes/configure-event-handler.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/db-configure-start.mdx
  docs/pages/includes/edition-comparison.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/ent-vs-community-faq.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-windows.mdx
  docs/pages/includes/no-oss-prereqs-tabs.mdx
  docs/pages/includes/plugins/enroll.mdx
  docs/pages/index.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/admin/uninstall-teleport.mdx
  docs/pages/management/admin/users.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/operations/backup-restore.mdx
  docs/pages/management/operations/tls-routing.mdx
  docs/pages/reference/audit.mdx
  docs/pages/reference/authentication.mdx
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/overview.mdx
Labels: documentation, backport, size/sm

#38944 [v15] Add missing redirects
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#39020 bump cloud docs to v15
  docs/config.json
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38993 Fix MySQL Server version auto-update
  lib/srv/db/access_test.go
  lib/srv/db/common/engines.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/server.go
Labels: database-access, db/mysql, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#39071 Fix kube credentials lock in separate mode
  tool/tsh/common/kube.go
Labels: tsh, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#39066 AWS OIDC - DeployService: Add ecs:TagResource policy
  lib/cloud/aws/policy_statements.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38897 [v13] role pagination (#38714)
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/services/access.go
  lib/services/access_checker.go
  lib/services/local/access.go
  lib/services/local/session.go
  lib/services/local/session_test.go
  lib/services/role.go
  lib/services/role_test.go
Labels: backport, size/md, no-changelog

#38894 [v14] role pagination (#38714)
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/api.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/services/access.go
  lib/services/local/access.go
  lib/services/local/session.go
  lib/services/local/session_test.go
  lib/services/role.go
  lib/services/role_test.go
Labels: backport, size/md, no-changelog

#39039 Add `saml_idp_service_provider` label and label expression to RoleConditions
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
Labels: size/sm, no-changelog

#39062 Fix .clangd file on lib/devicetrust/native
  lib/devicetrust/native/.clangd
Labels: size/sm, no-changelog

#39077 [v13] AWS OIDC - DeployService: Add ecs:TagResource policy
  lib/cloud/aws/policy_statements.go
Labels: backport, size/sm, no-changelog

#39078 [v14] AWS OIDC - DeployService: Add ecs:TagResource policy
  lib/cloud/aws/policy_statements.go
Labels: backport, size/sm, no-changelog

#39079 [v15] AWS OIDC - DeployService: Add ecs:TagResource policy
  lib/cloud/aws/policy_statements.go
Labels: backport, size/sm, no-changelog

#39064 [v14] Remove `auth.ClientI` from `tbot` (#39058)
  lib/auth/authclient/authclient.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
  lib/tbot/testhelpers/srv.go
  tool/tctl/common/helpers_test.go
Labels: backport, machine-id, size/sm, no-changelog

#39059 Replace `auth.ClientI` references in `tool/tctl`
  lib/client/db/database_certificates.go
  tool/tctl/common/access_request_command.go
  tool/tctl/common/accessmonitoring/command.go
  tool/tctl/common/acl_command.go
  tool/tctl/common/admin_action_test.go
  tool/tctl/common/alert_command.go
  tool/tctl/common/app_command.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
  tool/tctl/common/bots_command.go
  tool/tctl/common/db_command.go
  tool/tctl/common/desktop_command.go
  tool/tctl/common/devices.go
  tool/tctl/common/edit_command.go
  tool/tctl/common/edit_command_test.go
  tool/tctl/common/externalauditstorage_command.go
  tool/tctl/common/helpers_test.go
  tool/tctl/common/idp_command.go
  tool/tctl/common/inventory_command.go
  tool/tctl/common/kube_command.go
  tool/tctl/common/loadtest_command.go
  tool/tctl/common/lock_command.go
  tool/tctl/common/loginrule/command.go
  tool/tctl/common/node_command.go
  tool/tctl/common/proxy_command.go
  tool/tctl/common/recordings_command.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/saml_command.go
  tool/tctl/common/status_command.go
  tool/tctl/common/tctl.go
  tool/tctl/common/token_command.go
  tool/tctl/common/top_command.go
  tool/tctl/common/user_command.go
  tool/tctl/sso/configure/command.go
  tool/tctl/sso/configure/github.go
  tool/tctl/sso/tester/command.go
  tool/tctl/sso/tester/github.go
Labels: tctl, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39073 [v13] Fix kube credentials lock in separate mode
  tool/tsh/kube.go
Labels: tsh, backport, size/sm

#39082 [v15] Update `ExecReload` in all Teleport systemd unit files
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-node.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
  examples/systemd/fips/teleport.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
Labels: backport, size/sm, no-changelog

#39084 chore: Bump grpcbox base to golang:1.22
  build.assets/Dockerfile-grpcbox
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39074 [v14] Fix kube credentials lock in separate mode
  tool/tsh/common/kube.go
Labels: tsh, backport, size/sm

#39080 Fix broken links in examples/README.md
  examples/README.md
Labels: size/sm, no-changelog

#39089 [v15] chore: Bump grpcbox base to golang:1.22
  build.assets/Dockerfile-grpcbox
Labels: backport, size/sm, no-changelog

#39034 [v15] Remove Teleport Team mentions from the docs
  docs/config.json
  docs/pages/access-controls/access-graph.mdx
  docs/pages/access-controls/access-graph/self-hosted-helm.mdx
  docs/pages/access-controls/access-graph/self-hosted.mdx
  docs/pages/access-controls/idps/saml-guide.mdx
  docs/pages/access-controls/sso/github-sso.mdx
  docs/pages/access-controls/sso/okta.mdx
  docs/pages/agents/deploy-agents-terraform.mdx
  docs/pages/ai-assist.mdx
  docs/pages/choose-an-edition/introduction.mdx
  docs/pages/choose-an-edition/teleport-cloud/external-audit-storage.mdx
  docs/pages/choose-an-edition/teleport-cloud/faq.mdx
  docs/pages/choose-an-edition/teleport-cloud/get-started.mdx
  docs/pages/choose-an-edition/teleport-cloud/introduction.mdx
  docs/pages/choose-an-edition/teleport-enterprise/introduction.mdx
  docs/pages/core-concepts.mdx
  docs/pages/database-access/faq.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/desktop-access/getting-started.mdx
  docs/pages/documentation-overview.mdx
  docs/pages/faq.mdx
  docs/pages/includes/cloud/call-to-action.mdx
  docs/pages/includes/configure-event-handler.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/db-configure-start.mdx
  docs/pages/includes/edition-comparison.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/ent-vs-community-faq.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-windows.mdx
  docs/pages/includes/no-oss-prereqs-tabs.mdx
  docs/pages/includes/plugins/enroll.mdx
  docs/pages/index.mdx
  docs/pages/installation.mdx
  docs/pages/kubernetes-access/getting-started.mdx
  docs/pages/management/admin/trustedclusters.mdx
  docs/pages/management/admin/uninstall-teleport.mdx
  docs/pages/management/admin/users.mdx
  docs/pages/management/dynamic-resources.mdx
  docs/pages/management/operations/backup-restore.mdx
  docs/pages/management/operations/tls-routing.mdx
  docs/pages/reference/audit.mdx
  docs/pages/reference/authentication.mdx
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/cloud-linux.mdx
  docs/pages/upgrading/overview.mdx
Labels: documentation, backport, size/sm, no-changelog

#39087 [v13] chore: Bump grpcbox base to golang:1.22
  build.assets/Dockerfile-grpcbox
Labels: backport, size/sm, no-changelog

#39088 [v14] chore: Bump grpcbox base to golang:1.22
  build.assets/Dockerfile-grpcbox
Labels: backport, size/sm, no-changelog

#38984 TAG: Poll AWS EKS clusters fom AWS
  gen/proto/go/accessgraph/v1alpha/aws.pb.go
  lib/cloud/mocks/aws.go
  lib/srv/discovery/fetchers/aws-sync/aws-sync.go
  lib/srv/discovery/fetchers/aws-sync/eks.go
  lib/srv/discovery/fetchers/aws-sync/eks_test.go
  lib/srv/discovery/fetchers/aws-sync/merge.go
  lib/srv/discovery/fetchers/aws-sync/reconcile.go
  proto/accessgraph/v1alpha/aws.proto
Labels: size/md, discovery, no-changelog

#38915 Corrects the scancode for numlock, pause
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, desktop-access, size/sm, backport/branch/v15

#39013 TAG: Poll AWS RDS instances and clusters fom AWS
  gen/proto/go/accessgraph/v1alpha/aws.pb.go
  lib/srv/discovery/fetchers/aws-sync/aws-sync.go
  lib/srv/discovery/fetchers/aws-sync/merge.go
  lib/srv/discovery/fetchers/aws-sync/rds.go
  lib/srv/discovery/fetchers/aws-sync/rds_test.go
  lib/srv/discovery/fetchers/aws-sync/reconcile.go
  proto/accessgraph/v1alpha/aws.proto
Labels: size/md, discovery, no-changelog

#39033 Query target version in discovery script
  api/types/installers/agentless-installer.sh.tmpl
  api/types/installers/installer.sh.tmpl
  lib/web/apiserver_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#38943 [docs] GCP MySQL IAM authentication support
  docs/img/database-access/guides/cloudsql/add-user-account-mysql@2x.png
  docs/img/database-access/guides/cloudsql/instance-id-mysql@2x.png
  docs/pages/database-access/guides/mysql-cloudsql.mdx
  docs/pages/database-access/guides/postgres-cloudsql.mdx
  docs/pages/includes/database-access/aws-troubleshooting.mdx
  docs/pages/includes/database-access/cloudsql_create_db_user_account.mdx
  docs/pages/includes/database-access/cloudsql_download_root_ca.mdx
  docs/pages/includes/database-access/cloudsql_enable_iam_auth.mdx
  docs/pages/includes/database-access/cloudsql_grant_db_service_account.mdx
  docs/pages/includes/database-access/cloudsql_grant_db_user.mdx
  docs/pages/includes/database-access/cloudsql_service_account_key.mdx
  docs/pages/includes/database-access/cloudsql_service_credentials.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#38992 Refactor operator to support several types of resources + propagate labels
  integrations/operator/apis/resources/v1/loginrule_types.go
  integrations/operator/controllers/reconciler.go
  integrations/operator/controllers/reconcilers/base.go
  integrations/operator/controllers/reconcilers/generic.go
  integrations/operator/controllers/reconcilers/generic_test.go
  integrations/operator/controllers/reconcilers/legacy_resource_with_labels.go
  integrations/operator/controllers/reconcilers/legacy_resource_without_labels.go
  integrations/operator/controllers/reconcilers/resource153.go
  integrations/operator/controllers/reconcilers/utils.go
  integrations/operator/controllers/reconcilers/utils_test.go
  integrations/operator/controllers/resources/accesslist_controller.go
  integrations/operator/controllers/resources/github_connector_controller.go
  integrations/operator/controllers/resources/github_connector_controller_test.go
  integrations/operator/controllers/resources/login_rule_controller.go
  integrations/operator/controllers/resources/newkuberesource_test.go
  integrations/operator/controllers/resources/oidc_connector_controller.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
  integrations/operator/controllers/resources/okta_import_rule_controller.go
  integrations/operator/controllers/resources/okta_import_rule_controller_test.go
  integrations/operator/controllers/resources/openssheiceserverv2_controller.go
  integrations/operator/controllers/resources/openssheiceserverv2_controller_test.go
  integrations/operator/controllers/resources/opensshserverv2_controller.go
  integrations/operator/controllers/resources/opensshserverv2_controller_test.go
  integrations/operator/controllers/resources/provision_token_controller.go
  integrations/operator/controllers/resources/provision_token_controller_test.go
  integrations/operator/controllers/resources/role_controller_test.go
  integrations/operator/controllers/resources/rolev6_controller_test.go
  integrations/operator/controllers/resources/rolev7_controller_test.go
  integrations/operator/controllers/resources/rolevX_controller.go
  integrations/operator/controllers/resources/saml_connector_controller.go
  integrations/operator/controllers/resources/saml_connector_controller_test.go
  integrations/operator/controllers/resources/setup.go
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/teleport_reconciler_test.go
  integrations/operator/controllers/resources/testlib/accesslist_controller_tests.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/testlib/login_rule_controller_tests.go
  integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go
  integrations/operator/controllers/resources/user_controller.go
  integrations/operator/controllers/resources/user_controller_test.go
  integrations/operator/controllers/scheme.go
  integrations/operator/main.go
Labels: size/md, backport/branch/v15

#38994 Add e2e tests for Hardware Key support
  .github/ISSUE_TEMPLATE/testplan.md
  Makefile
  api/utils/keys/privatekey.go
  api/utils/keys/privatekey_test.go
  api/utils/keys/yubikey.go
  api/utils/keys/yubikey_fake.go
  api/utils/keys/yubikey_other.go
  lib/auth/auth.go
  lib/modules/test.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_azure_test.go
  tool/tsh/common/app_test.go
  tool/tsh/common/db_test.go
  tool/tsh/common/hardware_key_test.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/tctl_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/md, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39029 Remove `WORKLOAD_IDENTITY_EXPERIMENT` flag
  lib/auth/machineid/machineidv1/experiment/experiment.go
  lib/auth/machineid/machineidv1/workload_identity_service.go
  lib/auth/machineid/machineidv1/workload_identity_service_test.go
  lib/tbot/config/output_spiffe_svid.go
  lib/tbot/config/output_spiffe_svid_test.go
  lib/tbot/config/service_spiffe_workload_api_test.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/tbot_test.go
Labels: machine-id, size/sm, no-changelog, backport/branch/v15

#39010 [v15] Allow password change with identity verification
  api/gen/proto/go/teleport/mfa/v1/mfa.pb.go
  api/proto/teleport/mfa/v1/mfa.proto
  lib/auth/accountrecovery_test.go
  lib/auth/auth_login_test.go
  lib/auth/auth_test.go
  lib/auth/methods.go
  lib/auth/password.go
  lib/auth/password_test.go
  lib/auth/webauthn/login.go
  lib/web/mfa.go
  web/packages/teleport/src/Account/ChangePassword/useChangePassword.ts
  web/packages/teleport/src/services/auth/auth.ts
  web/packages/teleport/src/services/auth/types.ts
Labels: ui, backport, size/md, no-changelog

#39041 [v14] GCP MySQL IAM Auth support
  lib/cloud/gcp/sql.go
  lib/cloud/mocks/gcp.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/gcp.go
  lib/srv/db/mysql/gcp_test.go
Labels: database-access, backport, size/md

#39042 [v13] GCP MySQL IAM Auth support
  lib/cloud/gcp/sql.go
  lib/cloud/mocks/gcp.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/gcp.go
  lib/srv/db/mysql/gcp_test.go
Labels: database-access, backport, size/md

#39040 [v15] GCP MySQL IAM Auth support
  lib/cloud/gcp/sql.go
  lib/cloud/mocks/gcp.go
  lib/srv/db/common/auth.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/gcp.go
  lib/srv/db/mysql/gcp_test.go
Labels: database-access, backport, size/md

#39103 [v13] Query target version in discovery script
  api/types/installers/agentless-installer.sh.tmpl
  api/types/installers/installer.sh.tmpl
  lib/web/apiserver_test.go
Labels: backport, size/md
