Repository gravitational/teleport, pull requests merged in 2024-10, with the labels that each got.

#46971 Take the file path from `webUtils.getPathForFile` instead of `File.path`
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/fixtures/mocks.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46959 Add `LicenseAutoUpdate` entitlement
  entitlements/entitlements.go
  lib/modules/modules_test.go
  lib/service/connect_test.go
  lib/web/apiserver_test.go
Labels: size/sm, no-changelog

#47023 docs: update server access guides
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47007 docs: remove version 12.1 reference
  docs/pages/admin-guides/access-controls/idps.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46770 Add support for custom SQS consumer lock and disabling consumer
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/consumer.go
  lib/service/service_test.go
Labels: audit-log, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#47008 docs: update api user
  docs/pages/admin-guides/api/getting-started.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46806 [v16] Update AWS roles ARNs displayed on tsh app login for AWS console apps
  tool/teleport/testenv/test_server.go
  tool/tsh/common/app.go
  tool/tsh/common/app_aws.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_azure.go
  tool/tsh/common/app_azure_test.go
  tool/tsh/common/app_gcp.go
  tool/tsh/common/proxy.go
Labels: tsh, backport, size/md

#45979 Update proxy features
  entitlements/entitlements.go
  entitlements/entitlements_test.go
  lib/service/connect.go
  lib/service/connect_test.go
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/features.go
  lib/web/features_test.go
  lib/web/integrations_awsoidc.go
  lib/web/join_tokens.go
Labels: size/md, no-changelog, backport/branch/v16

#47011 [v16] Take the file path from `webUtils.getPathForFile` instead of `File.path`
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/fixtures/mocks.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, backport, size/sm

#47013 [v15] Take the file path from `webUtils.getPathForFile` instead of `File.path`
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/fixtures/mocks.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, backport, size/sm

#47036 [v15] docs: update server access guides
  docs/pages/admin-guides/access-controls/idps.mdx
  docs/pages/admin-guides/api/getting-started.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
Labels: documentation, backport, size/sm, no-changelog

#47035 [v16] docs: update server access guides
  docs/pages/admin-guides/access-controls/idps.mdx
  docs/pages/admin-guides/api/getting-started.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
Labels: documentation, backport, size/sm, no-changelog

#47037 [v14] docs: update server access guides
  docs/pages/admin-guides/access-controls/idps.mdx
  docs/pages/admin-guides/api/getting-started.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
Labels: documentation, backport, size/sm, no-changelog

#47005 docs: sso user update
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47033 [v16] docs: Include version requirement for setting users default shell
  docs/pages/admin-guides/access-controls/sso.mdx
  docs/pages/enroll-resources/server-access/guides/host-user-creation.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv6.mdx
Labels: documentation, backport, size/sm, no-changelog

#47046 Add optional pagerPosition prop to device table
  web/packages/teleport/src/DeviceTrust/types.ts
Labels: ui, size/sm, no-changelog

#47047 [v15] Remove v15 redirects
  docs/config.json
Labels: documentation, backport, size/sm

#47009 display all security group rules for a port range
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/SingleEnrollment.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupPicker.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupRulesDialog.tsx
  web/packages/teleport/src/config.ts
Labels: ui, discover, size/sm, backport/branch/v16

#47042 [v15] docs: sso user update
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#47055 [v16] fix: Update operator CRD docs
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv6.mdx
Labels: documentation, backport, size/sm, no-changelog

#47053 [v14] chore: Bump Go to v1.22.8
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#47058 Increase feature slider height for smallest screens
  web/packages/shared/components/EmptyState/EmptyState.tsx
Labels: ui, size/sm, no-changelog

#47048 chore: Bump Go to v1.23.2
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm

#47052 [v15] chore: Bump Go to v1.22.8
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#47043 [v14] docs: sso user update
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#47050 [v16] chore: Bump Go to v1.22.8
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#46789 Better debug logging for host user creation
  constants.go
  integration/hostuser_test.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_linux.go
  lib/srv/usermgmt_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46748 [v16] Add AutoUpdate Client/Cache implementation
  api/client/client.go
  api/client/events.go
  api/types/autoupdate/config_test.go
  api/types/autoupdate/version_test.go
  lib/auth/accesspoint/accesspoint.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/autoupdate/autoupdatev1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/service/service.go
  lib/services/autoupdates.go
  lib/services/local/autoupdate.go
  lib/services/local/autoupdate_test.go
  lib/services/local/events.go
Labels: backport, size/md, no-changelog

#46749 [v15] Add AutoUpdate Client/Cache implementation
  api/client/client.go
  api/client/events.go
  api/types/autoupdate/config_test.go
  api/types/autoupdate/version_test.go
  lib/auth/accesspoint/accesspoint.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/autoupdate/autoupdatev1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/service/service.go
  lib/services/autoupdates.go
  lib/services/local/autoupdate.go
  lib/services/local/autoupdate_test.go
  lib/services/local/events.go
Labels: backport, size/md, no-changelog

#47061 all: use package filepath for file paths
  api/client/credentials_test.go
  build.assets/tooling/cmd/difftest/ast.go
  build.assets/tooling/cmd/difftest/main.go
  build.assets/tooling/cmd/notarize-apple-binaries/gon_wrapper.go
  examples/dynamoathenamigration/migration_test.go
  integration/utmp_integration_test.go
  integrations/event-handler/cli_test.go
  integrations/event-handler/configure_cmd.go
  integrations/event-handler/fake_fluentd_test.go
  integrations/event-handler/mtls_certs_test.go
  integrations/event-handler/state.go
  integrations/lib/tar/extract.go
  lib/backend/pgbk/common/gcp_test.go
  lib/cgroup/cgroup_test.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/opensearch/profile.go
  lib/client/db/opensearch/profile_test.go
  lib/client/tshconfig_test.go
  lib/config/configuration_test.go
  lib/srv/server/installer/autodiscover.go
  lib/srv/server/installer/autodiscover_test.go
  lib/srv/sess.go
  lib/tbot/output_utils.go
  lib/tbot/tbot_test.go
  lib/utils/packagemanager/apt.go
  tool/tbot/systemd_test.go
  tool/tctl/sso/configure/flags/file_reader_test.go
  tool/tctl/sso/configure/saml_test.go
  tool/tsh/common/app_azure.go
  tool/tsh/common/app_azure_test.go
  tool/tsh/common/app_gcp.go
  tool/tsh/common/kube_proxy.go
  tool/tsh/common/kube_proxy_test.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/kubectl_test.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/recording_export_test.go
  tool/tsh/common/workload_identity.go
  tool/tsh/common/workload_identity_test.go
Labels: tsh, tctl, machine-id, size/sm, no-changelog

#46849 tsh play --format=text
  tool/tsh/common/play.go
  tool/tsh/common/tsh.go
Labels: tsh, size/sm, backport/branch/v16

#47004 Disable disk-based recording for TestDynamicClientReuse
  lib/backend/backend.go
  lib/config/configuration_test.go
  lib/service/service_test.go
  lib/service/servicecfg/config.go
  lib/services/local/doc.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46750 [v14] Add AutoUpdate Client/Cache implementation
  api/client/client.go
  api/client/events.go
  api/types/autoupdate/config_test.go
  api/types/autoupdate/version_test.go
  lib/auth/accesspoint/accesspoint.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/autoupdate/autoupdatev1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/service/service.go
  lib/services/autoupdates.go
  lib/services/local/autoupdate.go
  lib/services/local/autoupdate_test.go
  lib/services/local/events.go
Labels: backport, size/md, no-changelog

#47066 Update static host user RFD
  rfd/0175-static-host-users.md
Labels: rfd, size/sm, no-changelog

#47073 [v16] tsh play --format=text
  tool/tsh/common/play.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm

#47057 docs: include terraform_cloud in join methods
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#46824 Add INTEGRATION_ENROLL_KIND_DATADOG_INCIDENT_MANAGEMENT
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  proto/prehog/v1alpha/teleport.proto
  web/packages/teleport/src/Integrations/fixtures.ts
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v16

#47044 chore: update IAM join method to use aws-sdk-go-v2
  integration/ec2_test.go
  integration/teleterm_test.go
  lib/auth/join/iam/endpoints.go
  lib/auth/join/iam/iam.go
  lib/auth/join/iam/iam_test.go
  lib/auth/join/join.go
  lib/auth/join_iam.go
  lib/auth/register.go
Labels: size/md, no-changelog

#36510 RFD 0162: Machine ID Fleet Management, `BotInstance` resource and other `token` joining improvements
  rfd/0162-machine-id-token-join-method-bot-instance.md
Labels: rfd, size/md, size/lg, no-changelog

#46761 Migrate ReverseTunnel Resource APIs from HTTP to gRPC
  api/client/client.go
  api/gen/proto/go/teleport/presence/v1/service.pb.go
  api/gen/proto/go/teleport/presence/v1/service_grpc.pb.go
  api/proto/teleport/presence/v1/service.proto
  lib/auth/apiserver.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/authclient/http_client.go
  lib/auth/authclient/httpfallback.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/auth/presence/presencev1/service.go
  lib/auth/presence/presencev1/service_test.go
  lib/auth/trustedcluster.go
  lib/auth/trustedcluster_test.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/cache/resource_reverse_tunnel.go
  lib/cache/resource_reverse_tunnel_test.go
  lib/reversetunnel/rc_manager_test.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
  lib/services/suite/suite.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/lg, no-changelog

#46968 Workload ID: Add Auth Server JWT SVID support
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service.pb.go
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service_grpc.pb.go
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/machineid/v1/workload_identity_service.proto
  api/types/events/events.pb.go
  lib/auth/machineid/machineidv1/workload_identity_service.go
  lib/auth/machineid/machineidv1/workload_identity_service_test.go
  lib/jwt/jwt.go
Labels: size/md, no-changelog, backport/branch/v16

#47071 [v15] Disable disk-based recording for TestDynamicClientReuse
  lib/backend/backend.go
  lib/config/configuration_test.go
  lib/service/service_test.go
  lib/service/servicecfg/config.go
  lib/services/local/doc.go
Labels: backport, size/sm, no-changelog

#47063 [v16] Fix v16 redirects
  docs/config.json
Labels: documentation, backport, size/sm

#47076 [v16] docs: include terraform_cloud in join methods
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#47084 chore: Bump google.golang.org/grpc to v1.66.3
  api/go.mod
  api/go.sum
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#47087 Expose `AccessGraphSettings` permissions in user's ACLs
  lib/services/useracl.go
  lib/services/useracl_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47090 [v16] Expose `AccessGraphSettings` permissions in user's ACLs
  lib/services/useracl.go
  lib/services/useracl_test.go
Labels: backport, size/sm, no-changelog

#47089 [v15] Expose `AccessGraphSettings` permissions in user's ACLs
  lib/services/useracl.go
  lib/services/useracl_test.go
Labels: backport, size/sm, no-changelog

#46957 Add `mfa_weakest_device` to `UserStatusV2`
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  api/types/user.go
  docs/pages/reference/terraform-provider/data-sources/user.mdx
  docs/pages/reference/terraform-provider/resources/user.mdx
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
  lib/auth/tls_test.go
  lib/services/local/resource.go
  lib/services/local/resource_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  tool/tctl/common/edit_command_test.go
Labels: tctl, size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47088 web: remove dead code
  lib/web/assets.go
  lib/web/cachehandler.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#46816 [v16] [access_graph] add usage events for Crown Jewel's create and AccessPa…
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/auth/crownjewel/crownjewelv1/service.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/audit_test.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/usagereporter_test.go
  lib/usagereporter/web/userevent.go
  lib/usagereporter/web/userevent_test.go
  proto/prehog/v1alpha/teleport.proto
Labels: size/md, no-changelog

#46055 RFD 0181: PostgreSQL database access through Web UI
  rfd/0181-pg-database-access-webui.md
  rfd/assets/0181-connect-dialog-roles.png
  rfd/assets/0181-connect-dialog.png
  rfd/assets/0181-connect-pg.png
  rfd/assets/0181-pg-shell.png
  rfd/assets/0181-select-connect-webui.png
Labels: rfd, size/md, no-changelog

#47092 [v16] Add `mfa_weakest_device` to `UserStatusV2`
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  api/types/user.go
  docs/pages/reference/terraform-provider/data-sources/user.mdx
  docs/pages/reference/terraform-provider/resources/user.mdx
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
  lib/auth/tls_test.go
  lib/services/local/resource.go
  lib/services/local/resource_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  tool/tctl/common/edit_command_test.go
Labels: documentation, tctl, backport, size/md, no-changelog

#47051 Add static host user tests
  lib/srv/statichostuser_test.go
  lib/srv/statichostusers.go
Labels: size/md, no-changelog, backport/branch/v16

#47097 [v15] web: remove dead code
  lib/web/assets.go
  lib/web/cachehandler.go
Labels: backport, size/sm, no-changelog

#47098 [v16] web: remove dead code
  lib/web/assets.go
  lib/web/cachehandler.go
Labels: backport, size/sm, no-changelog

#46868 [v16] Add tctl resource commands for AutoUpdateConfig and AutoUpdateVersion
  api/client/client.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/edit_command_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/md, no-changelog

#47093 [v15] Add `mfa_weakest_device` to `UserStatusV2`
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  api/types/user.go
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
  lib/auth/tls_test.go
  lib/services/local/resource.go
  lib/services/local/resource_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  tool/tctl/common/edit_command_test.go
Labels: tctl, backport, size/md, no-changelog

#46866 [v14]Add tctl resource commands for AutoUpdateConfig and AutoUpdateVersion
  api/client/client.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/md, no-changelog

#47101 integrations: remove dead code
  integrations/lib/download.go
  integrations/lib/sha256.go
  integrations/lib/tsh/tsh.go
Labels: size/sm, no-changelog

#47096 [v16] Document usage event validation
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#46520 Allow SSO users to delete their last passwordless device
  lib/auth/auth.go
  lib/auth/grpcserver_test.go
Labels: size/sm

#47056 Display user friendly name of resources with preview_as_roles
  api/client/client.go
Labels: access-requests, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46986 Unify and simplify MFA Ceremony helpers
  api/client/mfa.go
  api/mfa/ceremony.go
  api/mfa/ceremony_test.go
  api/utils/grpc/interceptors/mfa.go
  lib/auth/helpers_mfa.go
  lib/client/api.go
  lib/client/cluster_client.go
  lib/client/cluster_client_test.go
  lib/client/local_proxy_middleware.go
  lib/client/mfa.go
  lib/client/presence.go
  lib/client/weblogin.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_headless.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/web/desktop.go
  lib/web/kube.go
  lib/web/terminal.go
  tool/tsh/common/app.go
  tool/tsh/common/kube_proxy.go
  tool/tsh/common/mfa.go
  tool/tsh/common/tsh_test.go
Labels: tsh, desktop-access, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47099 Simplify integrations/lib/backoff
  integrations/lib/backoff/backoff.go
  integrations/lib/backoff/backoff_test.go
  integrations/lib/backoff/decorr.go
  integrations/lib/backoff/measure.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#46867 [v15] Add tctl resource commands for AutoUpdateConfig and AutoUpdateVersion
  api/client/client.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/edit_command_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/md, no-changelog

#47077 [v16] display all security group rules for a port range
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/SingleEnrollment.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupPicker.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupRulesDialog.tsx
  web/packages/teleport/src/config.ts
Labels: ui, backport, discover, size/sm

#46780 tsh: Deduplicate the list of request IDs
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47118 [v16] Add new empty state for Bots page in the web UI
  web/packages/shared/components/EmptyState/EmptyState.tsx
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/List/Bots.story.tsx
  web/packages/teleport/src/Bots/List/Bots.test.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Bots/List/EmptyState/EmptyState.tsx
  web/packages/teleport/src/Bots/List/EmptyState/argocd.png
  web/packages/teleport/src/Bots/List/EmptyState/control-workflows-light.svg
  web/packages/teleport/src/Bots/List/EmptyState/control-workflows.svg
  web/packages/teleport/src/Bots/List/EmptyState/eliminate-secrets-light.svg
  web/packages/teleport/src/Bots/List/EmptyState/eliminate-secrets.svg
  web/packages/teleport/src/DeviceTrust/types.ts
Labels: ui, backport, size/lg, no-changelog

#46998 Machine ID: Bot instance management in `tctl bots instances`
  tool/tctl/common/admin_action_test.go
  tool/tctl/common/bots_command.go
  tool/tctl/common/bots_command_test.go
Labels: tctl, size/md, backport/branch/v16

#47115 [v15] Simplify integrations/lib/backoff
  integrations/lib/backoff/backoff.go
  integrations/lib/backoff/backoff_test.go
  integrations/lib/backoff/decorr.go
  integrations/lib/backoff/measure.go
Labels: backport, size/sm, no-changelog

#47116 [v16] Simplify integrations/lib/backoff
  integrations/lib/backoff/backoff.go
  integrations/lib/backoff/backoff_test.go
  integrations/lib/backoff/decorr.go
  integrations/lib/backoff/measure.go
Labels: backport, size/sm, no-changelog

#47108 Added 10/02 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm

#47120 [v16] Add notice to web UI that users arent equal to MAU
  web/packages/teleport/src/Users/Users.story.tsx
  web/packages/teleport/src/Users/Users.test.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/services/storageService/storageService.ts
  web/packages/teleport/src/services/storageService/types.ts
Labels: ui, backport, size/md, no-changelog

#47122 [v15] Add notice to web UI that users arent equal to MAU
  web/packages/teleport/src/Users/Users.story.tsx
  web/packages/teleport/src/Users/Users.test.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/services/storageService/storageService.ts
  web/packages/teleport/src/services/storageService/types.ts
Labels: ui, backport, size/md, no-changelog

#46838 [v15] [plugins] add plugin audit events boilerplate to CUD operations
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.go
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/events/events_test.go
Labels: audit-log, backport, size/md, no-changelog

#47110 [v14] Display user friendly name of resources with preview_as_roles
  api/client/client.go
Labels: backport, size/sm

#47112 [v16] Display user friendly name of resources with preview_as_roles
  api/client/client.go
Labels: backport, size/sm

#47111 [v15] Display user friendly name of resources with preview_as_roles
  api/client/client.go
Labels: backport, size/sm

#46817 [v15] [access_graph] add usage events for Crown Jewel's create and AccessPa…
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/auth/crownjewel/crownjewelv1/service.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/audit_test.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/usagereporter_test.go
  lib/usagereporter/web/userevent.go
  lib/usagereporter/web/userevent_test.go
  proto/prehog/v1alpha/teleport.proto
Labels: size/md, no-changelog

#46812 Implement new inputs and select components
  web/packages/design/src/Checkbox/Checkbox.tsx
  web/packages/design/src/Icon/Icon.tsx
  web/packages/design/src/Input/Input.story.tsx
  web/packages/design/src/Input/Input.test.tsx
  web/packages/design/src/Input/Input.tsx
  web/packages/design/src/Input/index.ts
  web/packages/design/src/LabelInput/LabelInput.tsx
  web/packages/design/src/ThemeProvider/globals.js
  web/packages/design/src/theme/typography.ts
  web/packages/shared/@types/react-select.d.ts
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/Apps.tsx
  web/packages/shared/components/FieldInput/FieldInput.story.tsx
  web/packages/shared/components/FieldInput/FieldInput.test.tsx
  web/packages/shared/components/FieldInput/FieldInput.tsx
  web/packages/shared/components/FieldSelect/FieldSelect.story.tsx
  web/packages/shared/components/FieldSelect/FieldSelect.tsx
  web/packages/shared/components/FieldSelect/FieldSelectCreatable.tsx
  web/packages/shared/components/FieldSelect/index.ts
  web/packages/shared/components/FieldSelect/shared.tsx
  web/packages/shared/components/FileTransfer/FileTransferStateless/CommonElements.tsx
  web/packages/shared/components/FileTransfer/FileTransferStateless/DownloadForm/DownloadForm.tsx
  web/packages/shared/components/FormPassword/FormPassword.tsx
  web/packages/shared/components/Select/Select.story.tsx
  web/packages/shared/components/Select/Select.tsx
  web/packages/shared/components/Select/index.ts
  web/packages/shared/components/Select/types.ts
  web/packages/teleport/src/Account/ChangePasswordWizard/ChangePasswordWizard.test.tsx
  web/packages/teleport/src/Account/ChangePasswordWizard/ChangePasswordWizard.tsx
  web/packages/teleport/src/Account/ManageDevices/wizards/AddAuthDeviceWizard.tsx
  web/packages/teleport/src/Apps/AddApp/Automatically.tsx
  web/packages/teleport/src/Bots/Add/GitHubActions/ConnectGitHub.test.tsx
  web/packages/teleport/src/Bots/Add/GitHubActions/ConnectGitHub.tsx
  web/packages/teleport/src/Console/DocumentNodes/ClusterSelector/ClusterSelector.tsx
  web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx
  web/packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
  web/packages/teleport/src/Discover/Shared/CustomInputFieldForAsterisks.tsx
  web/packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
  web/packages/teleport/src/Discover/Shared/SelectCreatable/SelectCreatable.tsx
  web/packages/teleport/src/Integrations/EditAwsOidcIntegrationDialog.tsx
  web/packages/teleport/src/JoinTokens/JoinTokenForms.tsx
  web/packages/teleport/src/components/EventRangePicker/EventRangePicker.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleport/src/components/LabelsInput/LabelsInput.tsx
  web/packages/teleport/src/components/ReAuthenticate/ReAuthenticate.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/ReAuthenticate/ReAuthenticate.tsx
  web/packages/teleterm/src/ui/components/FieldInputs.tsx
Labels: ui, size/lg

#47113 Cassandra driver fork update
  go.mod
  go.sum
Labels: size/sm, no-changelog

#47124 docs: update proxy service ports networking example
  docs/pages/reference/networking.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47138 [v15] Better debug logging for host user creation
  constants.go
  integration/hostuser_test.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_linux.go
  lib/srv/usermgmt_test.go
Labels: backport, size/md, no-changelog

#47125 [v16] Updates self-hosted db discover to use 2190h ttl for certificate
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/useMutualTls.ts
  web/packages/teleport/src/config.ts
Labels: ui, backport, size/sm

#47128 [v14] Updates self-hosted db discover to use 2190h ttl for certificate
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/useMutualTls.ts
  web/packages/teleport/src/config.ts
Labels: ui, backport, size/sm

#47127 [v15] Updates self-hosted db discover to use 2190h ttl for certificate
  web/packages/teleport/src/Discover/Database/MutualTls/MutualTls.tsx
  web/packages/teleport/src/Discover/Database/MutualTls/useMutualTls.ts
  web/packages/teleport/src/config.ts
Labels: ui, backport, size/sm

#47143 [secscanner] close stream after each report
  lib/secretsscanner/authorizedkeys/authorized_keys.go
  lib/secretsscanner/authorizedkeys/authorized_keys_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47146 [v15] [secscanner] close stream after each report
  lib/secretsscanner/authorizedkeys/authorized_keys.go
  lib/secretsscanner/authorizedkeys/authorized_keys_test.go
Labels: backport, size/sm, no-changelog

#47147 [v16] [secscanner] close stream after each report
  lib/secretsscanner/authorizedkeys/authorized_keys.go
  lib/secretsscanner/authorizedkeys/authorized_keys_test.go
Labels: backport, size/sm, no-changelog

#46961 [v15] update msteams plugin guided url link
  integrations/access/msteams/configure.go
Labels: backport, size/sm, no-changelog

#46731 Better error messaging when writing invalid sudoer entries
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#46911 [Web] Redesign "Help & Support" page
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/modules/modules.go
  lib/web/apiserver.go
  lib/web/ui/cluster.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/tsh_test.go
  web/packages/teleport/src/Support/Support.story.tsx
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
  web/packages/teleport/src/services/clusters/makeCluster.ts
  web/packages/teleport/src/services/clusters/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v16

#47114 fix: Always prompt if multiple MFA methods are running
  lib/auth/webauthnwin/api.go
  lib/client/mfa.go
  lib/client/mfa/cli.go
  lib/client/mfa/cli_test.go
  lib/client/mfa/prompt.go
  tool/tsh/common/mfa.go
Labels: size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#47045 Migrate access/msteams to slog + add debug logs
  integrations/access/msteams/app.go
  integrations/access/msteams/bot.go
  integrations/access/msteams/bot_test.go
  integrations/access/msteams/cmd/teleport-msteams/main.go
  integrations/access/msteams/testlib/suite.go
  integrations/access/msteams/uninstall.go
  integrations/access/msteams/validate.go
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/lib/logger/logger.go
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/config/configuration.go
Labels: size/md, backport/branch/v16

#46950 verify AWS account ID for external audit storage
  lib/integrations/awsoidc/access_graph_aws_sync.go
  lib/integrations/awsoidc/access_graph_aws_sync_test.go
  lib/integrations/awsoidc/aws_app_access_iam_config.go
  lib/integrations/awsoidc/aws_app_access_iam_config_test.go
  lib/integrations/awsoidc/clients.go
  lib/integrations/awsoidc/clients_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_config.go
  lib/integrations/awsoidc/deployservice_iam_config_test.go
  lib/integrations/awsoidc/ec2_ssm_iam_config.go
  lib/integrations/awsoidc/ec2_ssm_iam_config_test.go
  lib/integrations/awsoidc/eice_iam_config.go
  lib/integrations/awsoidc/eice_iam_config_test.go
  lib/integrations/awsoidc/eks_iam_config.go
  lib/integrations/awsoidc/eks_iam_config_test.go
  lib/integrations/awsoidc/externalauditstorage_iam_config.go
  lib/integrations/awsoidc/idp_iam_config.go
  lib/integrations/awsoidc/idp_iam_config_test.go
  lib/integrations/awsoidc/listdatabases_iam_config.go
  lib/integrations/awsoidc/listdatabases_iam_config_test.go
  lib/integrations/externalauditstorage/easconfig/externalauditstroageconfig.go
  tool/teleport/common/integration_configure.go
  tool/teleport/common/teleport.go
Labels: size/sm, no-changelog, backport/branch/v16

#47141 [v16] docs: update proxy service ports networking example
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#47142 [v15] docs: update proxy service ports networking example
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#47158 [v16] Migrate access/msteams to slog + add debug logs
  integrations/access/msteams/app.go
  integrations/access/msteams/bot.go
  integrations/access/msteams/bot_test.go
  integrations/access/msteams/cmd/teleport-msteams/main.go
  integrations/access/msteams/testlib/suite.go
  integrations/access/msteams/uninstall.go
  integrations/access/msteams/validate.go
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/lib/logger/logger.go
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/config/configuration.go
Labels: backport, size/md

#46747 make `configure awsoidc-idp` transparent
  lib/cloud/aws/policy.go
  lib/cloud/aws/policy_statements.go
  lib/cloud/aws/policy_test.go
  lib/cloud/provisioning/awsactions/common.go
  lib/cloud/provisioning/awsactions/create_oidc_idp.go
  lib/cloud/provisioning/awsactions/create_role.go
  lib/cloud/provisioning/operations.go
  lib/cloud/provisioning/operations_test.go
  lib/config/configuration.go
  lib/configurators/aws/aws.go
  lib/integrations/awsoidc/idp_iam_config.go
  lib/integrations/awsoidc/idp_iam_config_test.go
  lib/integrations/awsoidc/tags/tags.go
  lib/integrations/awsoidc/testdata/TestConfigureIdPIAMOutput.golden
  lib/srv/db/cloud/aws.go
  tool/teleport/common/integration_configure.go
  tool/teleport/common/teleport.go
Labels: ux, aws, discover, size/lg, no-changelog, backport/branch/v16

#46832 Edits to RFD 136: Modern Signature Algorithms
  rfd/0136-modern-signature-algorithms.md
Labels: rfd, size/sm, no-changelog

#46829 Refactor host group reconciliation
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: size/md, no-changelog

#46690 Edit the "Connecting Apps" guide
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47172 Fix plugin builds
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/lib/logger/logger.go
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/config/configuration.go
Labels: size/sm, no-changelog, backport/branch/v16

#47175 feat: update `tctl status` to show key algorithms and storage
  api/constants/constants.go
  api/types/authority.go
  constants.go
  docs/pages/admin-guides/deploy-a-cluster/aws-kms.mdx
  docs/pages/admin-guides/deploy-a-cluster/gcp-kms.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/reference/cli/tctl.mdx
  tool/tctl/common/status_command.go
Labels: documentation, tctl, size/md

#47179 revert SPIFFE CA JWT key to RSA
  lib/cryptosuites/suites.go
  rfd/0136-modern-signature-algorithms.md
Labels: rfd, size/sm, no-changelog

#47155 [v15] fix: Always prompt if multiple MFA methods are running
  lib/auth/webauthnwin/api.go
  lib/client/mfa.go
  lib/client/mfa/cli.go
  lib/client/mfa/cli_test.go
  lib/client/mfa/prompt.go
  tool/tsh/common/mfa.go
Labels: tsh, backport, size/md

#46981 Add filesystem lock for unix and windows platforms
  lib/utils/fs.go
  lib/utils/fs_test.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47062 User Tasks: add `discover-ec2` task type
  api/gen/proto/go/teleport/usertasks/v1/user_tasks.pb.go
  api/proto/teleport/usertasks/v1/user_tasks.proto
  api/types/usertasks/object.go
  api/types/usertasks/object_test.go
  lib/cache/cache_test.go
  lib/services/local/user_task_test.go
  lib/services/user_task_test.go
Labels: size/md, no-changelog, backport/branch/v16

#47184 Update terraform and event-handler `go.mod` replacements
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#46854 [kube] support tunneled SPDY protocol for outgoing connections
  lib/kube/proxy/auth_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/portforward_spdy.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/portforward_websocket.go
  lib/kube/proxy/resource_deletecollection.go
  lib/kube/proxy/roundtrip.go
  lib/kube/proxy/roundtrip_websocket.go
  lib/kube/proxy/server.go
  lib/kube/proxy/sess.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/utils_testing.go
  lib/kube/proxy/watcher.go
  lib/kube/proxy/websocket_client_testing.go
Labels: kubernetes-access, size/md, no-changelog

#47182 docs: include fdpass-teleport in machine-id getting started
  docs/pages/enroll-resources/machine-id/getting-started.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47187 [v15] docs: include fdpass-teleport in machine-id getting started
  docs/pages/enroll-resources/machine-id/getting-started.mdx
Labels: documentation, backport, size/sm, no-changelog

#46563 [v14] Turn Architecture section intro into an overview
  docs/pages/reference/architecture/architecture.mdx
Labels: documentation, backport, size/md, no-changelog

#47181 docs: update aws opensearch tokens
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-opensearch.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47199 [v15] docs: update aws opensearch tokens
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-opensearch.mdx
Labels: documentation, backport, size/sm, no-changelog

#44967 Bump JS deps (major)
  package.json
  pnpm-lock.yaml
  web/packages/build/package.json
Labels: ui, backport-required, size/sm, size/md, no-changelog, backport/branch/v16

#47210 [v16] use branch/v16 as default target for dependency review workflow
  .github/workflows/dependency-review.yaml
Labels: backport, size/sm, no-changelog

#47176 [v16] Fix plugin builds
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/lib/logger/logger.go
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/config/configuration.go
Labels: backport, size/sm, no-changelog

#47185 [v16] User Tasks: add `discover-ec2` task type
  api/gen/proto/go/teleport/usertasks/v1/user_tasks.pb.go
  api/proto/teleport/usertasks/v1/user_tasks.proto
  api/types/usertasks/object.go
  api/types/usertasks/object_test.go
  lib/cache/cache_test.go
  lib/services/local/user_task_test.go
  lib/services/user_task_test.go
Labels: backport, size/md, no-changelog

#45267 Update host-user-creation.mdx - Update sudoers instructions
  docs/cspell.json
  docs/pages/enroll-resources/server-access/guides/host-user-creation.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47167 [v15] Better error messaging when writing invalid sudoer entries
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: backport, size/sm, no-changelog

#47198 [v16] docs: update aws opensearch tokens
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-opensearch.mdx
Labels: documentation, backport, size/sm, no-changelog

#47168 [v16] Better error messaging when writing invalid sudoer entries
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: backport, size/sm, no-changelog

#47186 [v16] docs: include fdpass-teleport in machine-id getting started
  docs/pages/enroll-resources/machine-id/getting-started.mdx
Labels: documentation, backport, size/sm, no-changelog

#47153 Deprecate `/webapi/ssh/certs` + Use 2-step MFA login flow for Teleport Connect
  gen/proto/go/teleport/lib/teleterm/v1/auth_settings.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  lib/client/api.go
  lib/client/mfa/prompt.go
  lib/client/weblogin.go
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/daemon/mfaprompt.go
  lib/web/apiserver.go
  lib/web/apiserver_login_test.go
  proto/teleport/lib/teleterm/v1/auth_settings.proto
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts
  web/packages/teleterm/src/ui/services/clusters/types.ts
Labels: ui, size/sm

#47121 [v16] tsh: Deduplicate the list of request IDs
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, backport, size/sm, no-changelog

#47166 Clarify the wording on the device trust authorization dialog
  web/packages/teleterm/src/ui/ModalsHost/modals/AuthenticateWebDevice/AuthenticateWebDevice.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#47180 Fix flaky integrations tests
  integrations/event-handler/teleport_events_watcher_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#47159 MySQL fork driver update
  e2e/aws/rds_test.go
  go.mod
  go.sum
  integration/db/db_integration_test.go
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/benchmark/db/mysql.go
  lib/client/conntest/database/mysql.go
  lib/srv/db/access_test.go
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/test.go
  lib/srv/db/server_test.go
Labels: database-access, size/sm, no-changelog

#47218 [v16] Fix flaky integrations tests
  integrations/event-handler/teleport_events_watcher_test.go
Labels: backport, size/sm, no-changelog

#47177 [v16] Add INTEGRATION_ENROLL_KIND_DATADOG_INCIDENT_MANAGEMENT
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  proto/prehog/v1alpha/teleport.proto
  web/packages/teleport/src/Integrations/fixtures.ts
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport, size/sm, no-changelog

#47219 [v16] Clarify the wording on the device trust authorization dialog
  web/packages/teleterm/src/ui/ModalsHost/modals/AuthenticateWebDevice/AuthenticateWebDevice.tsx
Labels: ui, backport, size/sm, no-changelog

#47204 Replace EOL Debian Buster with Bullseye in `Dockerfile-node`
  build.assets/Dockerfile-node
  build.assets/versions.mk
Labels: size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#47220 [v15] Add new empty state for Bots page in the web UI (#47118)
  web/packages/shared/components/EmptyState/EmptyState.tsx
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/List/Bots.story.tsx
  web/packages/teleport/src/Bots/List/Bots.test.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Bots/List/EmptyState/EmptyState.tsx
  web/packages/teleport/src/Bots/List/EmptyState/argocd.png
  web/packages/teleport/src/Bots/List/EmptyState/control-workflows-light.svg
  web/packages/teleport/src/Bots/List/EmptyState/control-workflows.svg
  web/packages/teleport/src/Bots/List/EmptyState/eliminate-secrets-light.svg
  web/packages/teleport/src/Bots/List/EmptyState/eliminate-secrets.svg
  web/packages/teleport/src/DeviceTrust/types.ts
Labels: ui, backport, size/lg, no-changelog

#47217 [v15] Fix flaky integrations tests
  integrations/event-handler/teleport_events_watcher_test.go
Labels: backport, size/sm, no-changelog

#47162 Add AutoUpdateAgentPlan proto messages
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_agent_plan.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service_grpc.pb.go
  api/proto/teleport/autoupdate/v1/autoupdate_agent_plan.proto
  api/proto/teleport/autoupdate/v1/autoupdate_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/auth/autoupdate/autoupdatev1/service_test.go
Labels: size/md, no-changelog, backport/branch/v16

#47209 Add Docs about Standing Privileges
  docs/img/access-graph/standing-privileges.png
  docs/pages/admin-guides/teleport-policy/policy-how-to-use.mdx
Labels: documentation, size/sm, no-changelog

#47226 docs: update `tsh play` description
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#46741 Web: Define fetch kube resource web api endpoint
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/servers.go
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/generateResourcePath.test.ts
  web/packages/teleport/src/generateResourcePath.ts
  web/packages/teleport/src/services/kube/kube.ts
  web/packages/teleport/src/services/kube/makeKube.ts
  web/packages/teleport/src/services/kube/types.ts
  web/packages/teleport/src/services/resources/makeUnifiedResource.ts
Labels: ui, size/md, no-changelog, backport/branch/v16

#47149 Toggle light/dark themes
  web/packages/design/src/ResourceIcon/assets/entra-id.svg
  web/packages/design/src/ResourceIcon/icons.ts
  web/packages/design/src/ResourceIcon/resourceIconSpecs.ts
  web/packages/teleport/src/Integrations/IntegrationList.tsx
Labels: ui, size/sm, no-changelog

#47227 rfd spell fixes
  rfd/0171-database-session-playback.md
  rfd/0181-pg-database-access-webui.md
Labels: rfd, size/sm, no-changelog

#47183 fix signature_algorithm_suite checks for HSM and Cloud
  api/types/authentication.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: size/md, no-changelog

#47152 display security group id rules
  api/gen/proto/go/teleport/integration/v1/awsoidc_service.pb.go
  api/proto/teleport/integration/v1/awsoidc_service.proto
  lib/auth/integration/integrationv1/awsoidc.go
  lib/integrations/awsoidc/list_security_groups.go
  lib/integrations/awsoidc/list_security_groups_test.go
  lib/web/integrations_awsoidc.go
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.story.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupPicker.tsx
  web/packages/teleport/src/Discover/Shared/SecurityGroupPicker/SecurityGroupRulesDialog.tsx
  web/packages/teleport/src/services/integrations/integrations.ts
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, discover, size/sm, backport/branch/v16

#46835 Implement new tooltips
  web/packages/design/src/Modal/Modal.tsx
  web/packages/design/src/Modal/index.ts
  web/packages/design/src/Popover/Popover.jsx
  web/packages/design/src/Popover/Popover.story.tsx
  web/packages/design/src/Popover/Popover.tsx
  web/packages/design/src/Popover/Transition.tsx
  web/packages/design/src/Popover/index.ts
  web/packages/design/src/theme/themes/bblpTheme.ts
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
  web/packages/shared/components/ToolTip/HoverTooltip.tsx
  web/packages/shared/components/ToolTip/ToolTip.story.tsx
  web/packages/shared/components/ToolTip/ToolTip.tsx
  web/packages/shared/components/ToolTip/shared.tsx
  web/packages/teleport/src/DesktopSession/TopBar.tsx
  web/packages/teleport/src/components/LabelSelector/LabelSelector.tsx
  web/packages/teleport/src/components/ToolTipBadge/ToolTipBadge.tsx
Labels: ui, size/lg, no-changelog, backport/branch/v16

#47080 [v16] Workload ID: Add Auth Server JWT SVID support (#46968)
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service.pb.go
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service_grpc.pb.go
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/machineid/v1/workload_identity_service.proto
  api/types/events/events.pb.go
  lib/auth/machineid/machineidv1/workload_identity_service.go
  lib/auth/machineid/machineidv1/workload_identity_service_test.go
  lib/jwt/jwt.go
Labels: backport, size/md, no-changelog

#47205 [16.4.2] bump cloud docs
  docs/config.json
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#47268 Install the expected `protoc-gen-terraform` version in `lint.yaml`
  .github/workflows/lint.yaml
  integrations/terraform/Makefile
Labels: size/sm, no-changelog, backport/branch/v16

#46301 [v16] docs: removing tctl and tsh version from pre-reqs partial block
  docs/pages/includes/commercial-prereqs-tabs.mdx
Labels: documentation, backport, size/sm, no-changelog

#47261 Fix Workload Attestation failure regression
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/spiffe/workloadattest/attest.go
Labels: machine-id, size/sm, backport/branch/v15, backport/branch/v16
