Repository gravitational/teleport, pull requests merged in 2024-09, with the labels that each got.

#45927 filesessions: continue processing uploads on error
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_test.go
Labels: audit-log, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46072 Fix incorrect PostgreSQL spelling
  api/types/database.go
  api/types/database_test.go
  api/utils/azure/endpoints.go
  docs/pages/includes/config-reference/proxy-service.yaml
  lib/srv/discovery/fetchers/db/azure_dbserver.go
  lib/srv/discovery/fetchers/db/azure_dbserver_test.go
Labels: documentation, backport, size/sm, discovery, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43348 Workload Identity: SPIFFE Federation and Join Method RFD
  rfd/0175-spiffe-federation.md
Labels: rfd, size/md, no-changelog

#46090 [v16] Add documentation for the log configuration
  docs/config.json
  docs/cspell.json
  docs/pages/admin-guides/management/diagnostics/logging.mdx
Labels: documentation, backport, size/sm, no-changelog

#46094 docs: remove version 12 references
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/kubernetes-access/faq.mdx
  docs/pages/faq.mdx
  docs/pages/reference/access-controls/saml-idp.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46073 Replace `yarn` with `pnpm` in DevBox
  devbox.json
  devbox.lock
Labels: size/sm, no-changelog, backport/branch/v16

#46137 [v16] docs: remove version 12 references
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/kubernetes-access/faq.mdx
  docs/pages/faq.mdx
  docs/pages/reference/access-controls/saml-idp.mdx
Labels: documentation, backport, size/sm, no-changelog

#46138 [v15] docs: remove version 12 references
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/kubernetes-access/faq.mdx
  docs/pages/faq.mdx
  docs/pages/reference/access-controls/saml-idp.mdx
Labels: documentation, backport, size/sm, no-changelog

#46139 [v14] docs: remove version 12 references
  docs/pages/access-controls/idps/saml-reference.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/kubernetes-access/faq.mdx
  docs/pages/faq.mdx
Labels: documentation, backport, size/sm, no-changelog

#46136 pgevents: fix retention_period and disable_cleanup on crdb
  lib/events/pgevents/pgevents.go
Labels: audit-log, size/sm, backport/branch/v15, backport/branch/v16

#46144 kube: expose cluster domain to statefulset pod
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
Labels: helm, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46147 [v16] pgevents: fix retention_period and disable_cleanup on crdb
  lib/events/pgevents/pgevents.go
Labels: audit-log, backport, size/sm

#46148 [v15] pgevents: fix retention_period and disable_cleanup on crdb
  lib/events/pgevents/pgevents.go
Labels: audit-log, backport, size/sm

#46079 [v16] docs: document Teleport reporting proxy variables
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#46080 [v15] docs: document Teleport reporting proxy variables
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#46081 [v14] docs: document Teleport reporting proxy variables
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#43819 [v15] Add context around AWS join methods
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/aws-ec2.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/aws-iam.mdx
Labels: documentation, backport, size/sm, no-changelog

#46098 [v15] Correct Arch Linux spelling
  docs/cspell.json
  docs/pages/enroll-resources/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#46150 [v16] kube: expose cluster domain to statefulset pod
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
Labels: helm, backport, size/sm

#46099 [v16] Correct Arch Linux spelling
  docs/cspell.json
  docs/pages/enroll-resources/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#46151 [v15] kube: expose cluster domain to statefulset pod
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
Labels: helm, backport, size/sm

#46152 [v14] kube: expose cluster domain to statefulset pod
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
Labels: helm, backport, size/sm

#46088 [v16] docs: update upgrading
  docs/pages/reference/architecture/agent-update-management.mdx
  docs/pages/upgrading.mdx
Labels: documentation, backport, size/sm, no-changelog

#46097 [v14] Correct Arch Linux spelling
  docs/cspell.json
  docs/pages/enroll-resources/server-access/guides/bpf-session-recording.mdx
  docs/pages/enroll-resources/server-access/guides/restricted-session.mdx
Labels: documentation, backport, size/sm, no-changelog

#46089 [v15] docs: update upgrading
  docs/pages/reference/architecture/agent-update-management.mdx
  docs/pages/upgrading.mdx
Labels: documentation, backport, size/sm, no-changelog

#45451 Edit SSH Certificate Extensions guide
  docs/pages/admin-guides/management/guides/ssh-key-extensions.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46140 [v16] Replace `yarn` with `pnpm` in DevBox
  devbox.json
  devbox.lock
Labels: backport, size/sm, no-changelog

#46048 Restore the Datadog Event Handler guide
  docs/img/management/datadog-generate-api.png
  docs/pages/admin-guides/management/export-audit-events/datadog.mdx
  docs/pages/admin-guides/management/guides/datadog.mdx
  docs/pages/includes/configure-event-handler.mdx
  docs/pages/includes/install-event-handler.mdx
  docs/pages/includes/start-event-handler.mdx
Labels: documentation, size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46082 [v14] Return better error during group creation with invalid group name
  lib/srv/usermgmt.go
  lib/utils/host/hostusers.go
Labels: backport, size/sm, no-changelog

#46084 [v16] Return better error during group creation with invalid group name
  lib/srv/usermgmt.go
  lib/utils/host/hostusers.go
Labels: backport, size/sm, no-changelog

#46142 Add `pkg-config` to devbox to fix FIDO2 builds
  devbox.json
  devbox.lock
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46083 [v15] Return better error during group creation with invalid group name
  lib/srv/usermgmt.go
  lib/utils/host/hostusers.go
Labels: backport, size/sm, no-changelog

#43936 docs: aws console/cli troubleshooting
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
Labels: documentation, inactive, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46122 [v14] Fix incorrect PostgreSQL spelling
  api/types/database.go
  api/types/database_test.go
  api/utils/azure/endpoints.go
  docs/pages/includes/config-reference/proxy-service.yaml
  lib/srv/discovery/fetchers/db/azure_dbserver.go
  lib/srv/discovery/fetchers/db/azure_dbserver_test.go
Labels: documentation, backport, size/sm, discovery, no-changelog

#46120 [v16] Fix incorrect PostgreSQL spelling
  api/types/database.go
  api/types/database_test.go
  api/utils/azure/endpoints.go
  docs/pages/includes/config-reference/proxy-service.yaml
  lib/srv/discovery/fetchers/db/azure_dbserver.go
  lib/srv/discovery/fetchers/db/azure_dbserver_test.go
Labels: documentation, backport, size/sm, discovery, no-changelog

#46121 [v15] Fix incorrect PostgreSQL spelling
  api/types/database.go
  api/types/database_test.go
  api/utils/azure/endpoints.go
  docs/pages/includes/config-reference/proxy-service.yaml
  lib/srv/discovery/fetchers/db/azure_dbserver.go
  lib/srv/discovery/fetchers/db/azure_dbserver_test.go
Labels: documentation, backport, size/sm, discovery, no-changelog

#42827 docs: update sso community edition instructions
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, inactive, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46162 [v15] docs: aws console/cli troubleshooting
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
Labels: documentation, backport, size/sm, no-changelog

#44122 docs: s3 backend update
  docs/pages/admin-guides/management/external-audit-storage.mdx
  docs/pages/reference/backends.mdx
Labels: documentation, inactive, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46157 chore: Bump OpenSSL to 3.0.15
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/buildbox/thirdparty-libs.mk
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46160 [v16] Restore the Datadog Event Handler guide
  docs/img/management/datadog-generate-api.png
  docs/pages/admin-guides/management/export-audit-events/datadog.mdx
  docs/pages/admin-guides/management/guides/datadog.mdx
  docs/pages/includes/configure-event-handler.mdx
  docs/pages/includes/install-event-handler.mdx
  docs/pages/includes/start-event-handler.mdx
Labels: documentation, backport, size/md, no-changelog

#46161 [v16] docs: aws console/cli troubleshooting
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
Labels: documentation, backport, size/sm, no-changelog

#46087 fix local re-register
  lib/auth/register.go
  lib/service/connect.go
Labels: size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46174 Web Bug Fix: Remove view status button for okta (not fully implemented)
  web/packages/teleport/src/Integrations/IntegrationList.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#46074 Make the Cloud migration guide more general
  docs/config.json
  docs/pages/admin-guides/migrate-plans.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#46054 update rds loadtest IAM permissions
  assets/loadtest/databases/rds/main.tf
Labels: aws, size/sm, no-changelog

#46002 Add Terraform Provider support for the installer resource
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider.mdx
  docs/pages/reference/terraform-provider/data-sources.mdx
  docs/pages/reference/terraform-provider/data-sources/installer.mdx
  docs/pages/reference/terraform-provider/resources.mdx
  docs/pages/reference/terraform-provider/resources/installer.mdx
  integrations/terraform/DOCS.md
  integrations/terraform/README.md
  integrations/terraform/examples/resources/teleport_installer/resource.tf
  integrations/terraform/gen/main.go
  integrations/terraform/protoc-gen-terraform-teleport.yaml
  integrations/terraform/provider/data_source_teleport_installer.go
  integrations/terraform/provider/provider.go
  integrations/terraform/provider/resource_teleport_installer.go
  integrations/terraform/testlib/fixtures/installer_0_create.tf
  integrations/terraform/testlib/fixtures/installer_1_update.tf
  integrations/terraform/testlib/installer_test.go
  integrations/terraform/testlib/main_test.go
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, size/lg, backport/branch/v15, backport/branch/v16

#46179 Web bug fix: Remove okta row click handler (not fully implemented)
  web/packages/teleport/src/Integrations/IntegrationList.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#43818 [v14] Add context around AWS join methods
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/aws-ec2.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/aws-iam.mdx
Labels: documentation, backport, size/sm, no-changelog

#46180 [v16] chore: Bump OpenSSL to 3.0.15
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport, size/sm

#46181 [v15] chore: Bump OpenSSL to 3.0.15 (#46157)
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: backport, size/sm

#46184 [v16] fix local re-register
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm

#46178 [v16] Web Bug Fix: Remove view status button for okta (not fully implemented)
  web/packages/teleport/src/Integrations/IntegrationList.tsx
Labels: ui, backport, size/sm, no-changelog

#46165 Simplify tctl and tsh partials
  docs/pages/admin-guides/access-controls/sso/okta.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/includes/cloud/tctl-tsh-prerequisite.mdx
  docs/pages/includes/enterprise/tctl-tsh-prerequisite.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46171 [v15] docs: update sso community edition instructions
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46176 [v15] docs: s3 backend update
  docs/pages/admin-guides/management/external-audit-storage.mdx
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#46127 [v14] filesessions: continue processing uploads on error
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_test.go
Labels: audit-log, backport, size/sm, no-changelog

#46085 [v16] docs: add troubleshooting step for directory sharing failures
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#46129 [v16] filesessions: continue processing uploads on error
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_test.go
Labels: audit-log, backport, size/sm, no-changelog

#46188 [v16] Web bug fix: Remove okta row click handler (not fully implemented)
  web/packages/teleport/src/Integrations/IntegrationList.tsx
Labels: ui, backport, size/sm, no-changelog

#46128 [v15] filesessions: continue processing uploads on error
  lib/events/filesessions/fileasync.go
  lib/events/filesessions/fileasync_test.go
Labels: audit-log, backport, size/sm, no-changelog

#46186 docs: Add additional RemoteFX screenshots
  docs/img/desktop-access/enable-remotefx-step-1.png
  docs/img/desktop-access/enable-remotefx-step-2.png
  docs/img/desktop-access/enable-remotefx-step-3.png
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46164 [v15] docs: add troubleshooting step for directory sharing failures
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#46182 [v14] fix local re-register
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm

#46183 [v15] fix local re-register
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm

#46177 docs: include web ui users page for managing users desciption
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46115 update language on deleting token
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#45897 [v16] Increase contrast on banner alerts
  web/packages/teleport/src/components/BannerList/Banner.tsx
Labels: ui, backport, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#46197 [v16] docs: include web ui users page for managing users desciption
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46175 [v16] docs: s3 backend update
  docs/pages/admin-guides/management/external-audit-storage.mdx
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#46199 [v14] docs: include web ui users page for managing users desciption
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46198 [v15] docs: include web ui users page for managing users desciption
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46200 [v16] Add Terraform Provider support for the installer resource
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider.mdx
  docs/pages/reference/terraform-provider/data-sources.mdx
  docs/pages/reference/terraform-provider/data-sources/installer.mdx
  docs/pages/reference/terraform-provider/resources.mdx
  docs/pages/reference/terraform-provider/resources/installer.mdx
  integrations/terraform/DOCS.md
  integrations/terraform/README.md
  integrations/terraform/examples/resources/teleport_installer/resource.tf
  integrations/terraform/gen/main.go
  integrations/terraform/protoc-gen-terraform-teleport.yaml
  integrations/terraform/provider/data_source_teleport_installer.go
  integrations/terraform/provider/provider.go
  integrations/terraform/provider/resource_teleport_installer.go
  integrations/terraform/testlib/fixtures/installer_0_create.tf
  integrations/terraform/testlib/fixtures/installer_1_update.tf
  integrations/terraform/testlib/installer_test.go
  integrations/terraform/testlib/main_test.go
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, backport, size/lg

#46077 [v16] Clarify role of the Auth Service in diagram
  docs/pages/reference/architecture/proxy.mdx
Labels: documentation, backport, size/sm, no-changelog

#46212 docs: include amazon linux 2023 in supported ec2 instances for auto enrollment
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46210 docs: restore create connector instructions in sso
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#46213 docs: remove installer tmpl link for default installer
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/gcp-discovery.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#45259 [v15] Reorganize Teleport Policy docs
  docs/pages/admin-guides/access-controls/access-graph/access-graph.mdx
  docs/pages/admin-guides/access-controls/teleport-policy/policy-integrations.mdx
  docs/pages/admin-guides/access-controls/teleport-policy/teleport-policy.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/access-graph.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/self-hosted-helm.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/self-hosted.mdx
  docs/pages/admin-guides/management/guides/awsoidc-integration.mdx
  docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/entra-id.mdx
  docs/pages/admin-guides/teleport-policy/integrations/gitlab.mdx
  docs/pages/admin-guides/teleport-policy/integrations/integrations.mdx
  docs/pages/admin-guides/teleport-policy/integrations/ssh-keys-scan.mdx
  docs/pages/admin-guides/teleport-policy/policy-connections.mdx
  docs/pages/admin-guides/teleport-policy/policy-how-to-use.mdx
  docs/pages/admin-guides/teleport-policy/teleport-policy.mdx
  docs/pages/index.mdx
  docs/pages/reference/helm-reference/teleport-access-graph.mdx
Labels: documentation, backport, size/sm, no-changelog

#46029 Adding extra pod labels to post-upgrade and post-delete hook job pods
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/templates/hook.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46170 [v16] docs: update sso community edition instructions
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46095 docs: add note on trusted clusters
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46218 Run integration tests on proto changes
  .github/workflows/unit-tests-integrations.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_accesslists.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_githubconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_oidcconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_openssheiceserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_opensshserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv6.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv7.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_samlconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_users.yaml
  integrations/operator/crdgen/testdata/protofiles/teleport/accesslist/v1/accesslist.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/attestation/v1/attestation.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/metadata.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/resourceheader.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/authservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/certs.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/event.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/joinservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/proxyservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/device.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/athena.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/events.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/webauthn/webauthn.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/wrappers/wrappers.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule_service.proto
Labels: size/xl, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45964 Refactor `addOrRemoveResource` in Connect to support bulk requests
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
Labels: ui, backport-required, size/sm, backport/branch/v16

#46241 [v14] Run integration tests on proto changes
  .github/workflows/unit-tests-integrations.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_githubconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_oidcconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_samlconnectors.yaml
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/authservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/certs.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/event.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/joinservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/events.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/webauthn/webauthn.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule_service.proto
Labels: backport, size/xl, no-changelog

#46242 [v15] Run integration tests on proto changes
  .github/workflows/unit-tests-integrations.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_accesslists.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_githubconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_oidcconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_openssheiceserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_opensshserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv6.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv7.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_samlconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_users.yaml
  integrations/operator/crdgen/testdata/protofiles/teleport/accesslist/v1/accesslist.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/attestation/v1/attestation.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/metadata.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/resourceheader.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/authservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/certs.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/event.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/joinservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/proxyservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/device.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/athena.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/events.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/webauthn/webauthn.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/wrappers/wrappers.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule_service.proto
Labels: backport, size/xl, no-changelog

#46227 [v16] docs: Add additional RemoteFX screenshots
  docs/img/desktop-access/enable-remotefx-step-1.png
  docs/img/desktop-access/enable-remotefx-step-2.png
  docs/img/desktop-access/enable-remotefx-step-3.png
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
Labels: documentation, backport, size/sm, no-changelog

#46233 [v16] docs: add note on trusted clusters
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
Labels: documentation, backport, size/sm, no-changelog

#46219 [v16] docs: include amazon linux 2023 in supported ec2 instances for auto enrollment
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#46220 [v15] docs: include amazon linux 2023 in supported ec2 instances for auto enrollment
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#46234 [v15] docs: add note on trusted clusters
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
Labels: documentation, backport, size/sm, no-changelog

#46096 [v16] [docs] fix elasticache/memorydb permissions reference
  docs/pages/includes/database-access/reference/aws-iam/redis/auto-password-access-policy.mdx
  docs/pages/reference/agent-services/database-access-reference/aws.mdx
Labels: documentation, backport, size/sm, no-changelog

#46154 [v16] Edit SSH Certificate Extensions guide
  docs/pages/admin-guides/management/guides/ssh-key-extensions.mdx
Labels: documentation, backport, size/sm, no-changelog

#46155 [v15] Edit SSH Certificate Extensions guide
  docs/pages/admin-guides/management/guides/ssh-key-extensions.mdx
Labels: documentation, backport, size/sm, no-changelog

#46249 [v16] Use buf.gen.yaml v2
  buf-connect-go.gen.yaml
  buf-go.gen.yaml
  buf-gogo.gen.yaml
  buf-ts.gen.yaml
  build.assets/genproto.sh
Labels: backport, size/sm, no-changelog

#46156 [v14] Edit SSH Certificate Extensions guide
  docs/pages/admin-guides/management/guides/ssh-key-extensions.mdx
Labels: documentation, backport, size/sm, no-changelog

#46250 [v15] Use buf.gen.yaml v2
  buf-connect-go.gen.yaml
  buf-go.gen.yaml
  buf-gogo.gen.yaml
  buf-ts.gen.yaml
  build.assets/genproto.sh
Labels: backport, size/sm, no-changelog

#46243 ci: Ensure Helm lint is run on helm changes
  .github/workflows/unit-tests-helm.yaml
  Makefile
  docs/pages/includes/helm-reference/zz_generated.teleport-kube-agent.mdx
  examples/chart/Makefile
Labels: bug, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46238 [v16] Refactor `addOrRemoveResource` in Connect to support bulk requests
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
Labels: ui, backport, size/md

#46240 [v16] Run integration tests on proto changes
  .github/workflows/unit-tests-integrations.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_accesslists.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_githubconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_oidcconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_openssheiceserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_opensshserversv2.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv6.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv7.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_samlconnectors.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_users.yaml
  integrations/operator/crdgen/testdata/protofiles/teleport/accesslist/v1/accesslist.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/attestation/v1/attestation.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/metadata.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/header/v1/resourceheader.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/authservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/certs.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/event.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/joinservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/proxyservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/device.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/athena.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/events.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/webauthn/webauthn.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/wrappers/wrappers.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/loginrule/v1/loginrule_service.proto
Labels: backport, size/xl, no-changelog

#46229 [v16] docs: remove installer tmpl link for default installer
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/gcp-discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#46228 [v15] docs: restore create connector instructions in sso
  docs/pages/admin-guides/access-controls/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#46235 [v14] docs: add note on trusted clusters
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
Labels: documentation, backport, size/sm, no-changelog

#45876 support split SSH/TLS keys in SSO login endpoints
  api/proto/teleport/legacy/types/types.proto
  api/types/github.go
  api/types/oidc.go
  api/types/saml.go
  api/types/types.pb.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/authclient/clt.go
  lib/auth/github.go
  lib/auth/github_test.go
  lib/auth/sessions.go
  lib/client/redirect.go
  lib/client/weblogin.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/app/redirect.go
  tool/tctl/sso/tester/github.go
  tool/tctl/sso/tester/oidc.go
  tool/tctl/sso/tester/saml.go
Labels: size/md, no-changelog

#46247 Use buf.gen.yaml v2
  buf-connect-go.gen.yaml
  buf-go.gen.yaml
  buf-gogo.gen.yaml
  buf-ts.gen.yaml
  build.assets/genproto.sh
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46254 [v16] ci: Ensure Helm lint is run on helm changes
  .github/workflows/unit-tests-helm.yaml
  Makefile
  examples/chart/Makefile
Labels: helm, backport, size/sm, no-changelog

#46173 Add autoupdate resources config/version
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service_grpc.pb.go
  api/proto/teleport/autoupdate/v1/autoupdate.proto
  api/proto/teleport/autoupdate/v1/autoupdate_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
Labels: size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46203 support file configuration of `signature_algorithm_suite`
  api/types/signaturealgorithmsuite.go
  lib/config/fileconf.go
  lib/config/fileconf_test.go
Labels: size/sm, no-changelog

#46248 [v15] docs: Add additional RemoteFX screenshots
  docs/img/desktop-access/enable-remotefx-step-1.png
  docs/img/desktop-access/enable-remotefx-step-2.png
  docs/img/desktop-access/enable-remotefx-step-3.png
  docs/pages/enroll-resources/desktop-access/active-directory-manual.mdx
Labels: documentation, backport, size/sm, no-changelog

#46251 [v14] Use buf.gen.yaml v2
  buf-connect-go.gen.yaml
  buf-go.gen.yaml
  buf-gogo.gen.yaml
  buf-js.gen.yaml
  build.assets/genproto.sh
Labels: backport, size/sm, no-changelog

#46255 [v15] ci: Ensure Helm lint is run on helm changes
  .github/workflows/unit-tests-helm.yaml
  Makefile
  examples/chart/Makefile
Labels: helm, backport, size/sm, no-changelog

#44834 Add a two-part Terraform starter guide
  docs/config.json
  docs/cspell.json
  docs/img/tf-agent-diagram.png
  docs/pages/admin-guides/deploy-a-cluster/linux-demo.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/enroll-resources.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
  docs/pages/enroll-resources/agents/deploy-agents-terraform.mdx
  docs/pages/enroll-resources/agents/introduction.mdx
  docs/pages/enroll-resources/application-access/guides/dynamic-registration.mdx
  docs/pages/get-started.mdx
  docs/pages/installation.mdx
  examples/agent-pool-terraform/teleport/inputs.tf
  examples/terraform-starter/agent-installation/inputs.tf
  examples/terraform-starter/agent-installation/outputs.tf
  examples/terraform-starter/agent-installation/required_providers.tf
  examples/terraform-starter/agent-installation/token.tf
  examples/terraform-starter/agent-installation/userdata
  examples/terraform-starter/aws/ec2-instance.tf
  examples/terraform-starter/aws/inputs.tf
  examples/terraform-starter/aws/required_providers.tf
  examples/terraform-starter/azure/azure-instance.tf
  examples/terraform-starter/azure/inputs.tf
  examples/terraform-starter/azure/required_providers.tf
  examples/terraform-starter/env_role/env_role.tf
  examples/terraform-starter/env_role/inputs.tf
  examples/terraform-starter/env_role/required_providers.tf
  examples/terraform-starter/env_role/reviewer.tf
  examples/terraform-starter/gcp/gcp-instance.tf
  examples/terraform-starter/gcp/inputs.tf
  examples/terraform-starter/gcp/required_providers.tf
  examples/terraform-starter/main.tf
  examples/terraform-starter/oidc/auth_pref.tf
  examples/terraform-starter/oidc/inputs.tf
  examples/terraform-starter/oidc/oidc_connector.tf
  examples/terraform-starter/oidc/required_providers.tf
  examples/terraform-starter/saml/auth_pref.tf
  examples/terraform-starter/saml/inputs.tf
  examples/terraform-starter/saml/required_providers.tf
  examples/terraform-starter/saml/saml.tf
Labels: documentation, size/lg, no-changelog, backport/branch/v16

#46221 [v14] docs: include amazon linux 2023 in supported ec2 instances for auto enrollment
  docs/pages/enroll-resources/server-access/guides/ec2-discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#46201 Clean up desktop access alerts (part 1)
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/tdp/conn.go
  lib/srv/desktop/tdp/proto.go
  lib/srv/desktop/tdp/proto_test.go
  lib/srv/desktop/windows_server.go
  lib/web/apiserver_test.go
  lib/web/desktop.go
  rfd/0037-desktop-access-protocol.md
  web/packages/teleport/src/DesktopSession/AlertDropdown.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/TopBar.tsx
  web/packages/teleport/src/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, rdp, rfd, desktop-access, size/sm, no-changelog

#46259 Ignore Operator references in the spellcheck
  docs/cspell.json
Labels: documentation, size/sm

#45877 fix duplicate session recording creation
  lib/events/filesessions/fileasync.go
  lib/events/s3sessions/s3handler_thirdparty_test.go
  lib/events/stream.go
  lib/events/test/streamsuite.go
Labels: audit-log, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#46224 [16.2.0] Bump cloud docs
  docs/config.json
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46187 add new stream combinators
  api/internalutils/stream/stream.go
  api/internalutils/stream/stream_test.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46093 Add static host user tctl
  lib/services/presets.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/edit_command_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, size/md

#46209 [v16] update language on deleting token
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
Labels: ui, backport, size/sm, no-changelog

#46258 [v14] Add autoupdate resources config/version
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service_grpc.pb.go
  api/proto/teleport/autoupdate/v1/autoupdate.proto
  api/proto/teleport/autoupdate/v1/autoupdate_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
Labels: backport, size/md

#46256 [v16] Add autoupdate resources config/version
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service_grpc.pb.go
  api/proto/teleport/autoupdate/v1/autoupdate.proto
  api/proto/teleport/autoupdate/v1/autoupdate_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
Labels: backport, size/md

#46263 [v14] fix duplicate session recording creation
  lib/events/filesessions/fileasync.go
  lib/events/s3sessions/s3handler_thirdparty_test.go
  lib/events/stream.go
  lib/events/test/streamsuite.go
Labels: audit-log, backport, size/sm

#46264 [v15] fix duplicate session recording creation
  lib/events/filesessions/fileasync.go
  lib/events/s3sessions/s3handler_thirdparty_test.go
  lib/events/stream.go
  lib/events/test/streamsuite.go
Labels: audit-log, backport, size/sm

#46257 [v15] Add autoupdate resources config/version
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service.pb.go
  api/gen/proto/go/teleport/autoupdate/v1/autoupdate_service_grpc.pb.go
  api/proto/teleport/autoupdate/v1/autoupdate.proto
  api/proto/teleport/autoupdate/v1/autoupdate_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
Labels: backport, size/md

#45898 [v16] Login redirect changes
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/history/history.ts
Labels: ui, backport, size/sm, no-changelog

#45901 [v15] Login redirect changes
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/history/history.ts
Labels: ui, backport, size/sm, no-changelog

#46208 Add documentation and references for `fdpass-teleport`
  assets/install-scripts/install.sh
  docs/pages/admin-guides/management/admin/uninstall-teleport.mdx
  docs/pages/installation.mdx
  docs/pages/reference/cli.mdx
  docs/pages/reference/cli/fdpass-teleport.mdx
  tool/fdpass-teleport/src/main.rs
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#46205 [v16] Fix an incomplete backport of the type system PR
  package.json
  pnpm-lock.yaml
  web/packages/build/package.json
  web/packages/design/src/DataTable/InputSearch/InputSearch.tsx
  web/packages/design/src/SlideTabs/SlideTabs.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/ToolTip/ToolTip.tsx
Labels: ui, backport, size/sm, no-changelog

#46239 Fix the alert layout
  web/packages/design/src/Alert/Alert.tsx
Labels: ui, size/sm, no-changelog

#45972 Add a link text label to the ClusterAlert resource
  api/types/cluster_alert.go
  api/types/cluster_alert_test.go
  api/types/constants.go
  lib/auth/auth.go
  lib/usagereporter/teleport/aggregating/submitter.go
Labels: size/sm, no-changelog, backport/branch/v16

#46217 docs: include db queries in sessions arch
  docs/pages/reference/architecture/session-recording.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46215 [v15] Simplify tctl and tsh partials
  docs/pages/admin-guides/access-controls/sso/okta.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/includes/cloud/tctl-tsh-prerequisite.mdx
  docs/pages/includes/enterprise/tctl-tsh-prerequisite.mdx
Labels: documentation, backport, size/sm, no-changelog

#46290 [v16] chore: Bump Buf to v1.40.0
  buf-legacy.yaml
  buf.yaml
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#46289 [v15] chore: Bump Buf to v1.40.0
  buf-legacy.yaml
  buf.yaml
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#46288 [v14] chore: Bump Buf to v1.40.0
  buf-legacy.yaml
  buf.yaml
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#46267 [v15] add new stream combinators
  api/internalutils/stream/stream.go
  api/internalutils/stream/stream_test.go
Labels: backport, size/md, no-changelog

#46265 [v16] fix duplicate session recording creation
  lib/events/filesessions/fileasync.go
  lib/events/s3sessions/s3handler_thirdparty_test.go
  lib/events/stream.go
  lib/events/test/streamsuite.go
Labels: audit-log, backport, size/sm

#46032 Fix debug service not being disabled by configuration
  lib/config/configuration.go
  lib/config/configuration_test.go
  tool/teleport/common/teleport.go
Labels: size/sm, backport/branch/v15, backport/branch/v16

#45978 Added 08/28 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#46266 [v14] add new stream combinators
  api/internalutils/stream/stream.go
  api/internalutils/stream/stream_test.go
Labels: backport, size/md, no-changelog

#46268 [v16] add new stream combinators
  api/internalutils/stream/stream.go
  api/internalutils/stream/stream_test.go
Labels: backport, size/md, no-changelog

#46282 [v14] docs: include db queries in sessions arch
  docs/pages/reference/architecture/session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#46280 [v16] docs: include db queries in sessions arch
  docs/pages/reference/architecture/session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#44954 Document the multiple Terraform provider setups
  docs/config.json
  docs/cspell.json
  docs/pages/admin-guides/infrastructure-as-code/managing-resources/import-existing-resources.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/ci-or-cloud.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/dedicated-server.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/local.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/long-lived-credentials.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
  docs/pages/enroll-resources/machine-id/access-guides.mdx
  docs/pages/enroll-resources/machine-id/deployment/circleci.mdx
  docs/pages/includes/machine-id/recover-circle-ci-claims.mdx
  docs/pages/includes/management/dynamic-resources/terraform-role.mdx
  docs/pages/reference/terraform-provider.mdx
  integrations/terraform/templates/index.md.tmpl
Labels: documentation, size/lg, no-changelog, backport/branch/v16

#46204 docs: removing tctl and tsh version from pre-reqs partial block
  docs/pages/includes/commercial-prereqs-tabs.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#46292 [v15] Fix debug service not being disabled by configuration
  lib/config/configuration.go
  lib/config/configuration_test.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm

#46293 [v16] Fix debug service not being disabled by configuration
  lib/config/configuration.go
  lib/config/configuration_test.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm

#46260 [v16] Add a two-part Terraform starter guide
  docs/config.json
  docs/cspell.json
  docs/img/tf-agent-diagram.png
  docs/pages/admin-guides/deploy-a-cluster/linux-demo.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/enroll-resources.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
  docs/pages/enroll-resources/agents/deploy-agents-terraform.mdx
  docs/pages/enroll-resources/agents/introduction.mdx
  docs/pages/enroll-resources/application-access/guides/dynamic-registration.mdx
  docs/pages/get-started.mdx
  docs/pages/installation.mdx
  examples/agent-pool-terraform/teleport/inputs.tf
  examples/terraform-starter/agent-installation/inputs.tf
  examples/terraform-starter/agent-installation/outputs.tf
  examples/terraform-starter/agent-installation/required_providers.tf
  examples/terraform-starter/agent-installation/token.tf
  examples/terraform-starter/agent-installation/userdata
  examples/terraform-starter/aws/ec2-instance.tf
  examples/terraform-starter/aws/inputs.tf
  examples/terraform-starter/aws/required_providers.tf
  examples/terraform-starter/azure/azure-instance.tf
  examples/terraform-starter/azure/inputs.tf
  examples/terraform-starter/azure/required_providers.tf
  examples/terraform-starter/env_role/env_role.tf
  examples/terraform-starter/env_role/inputs.tf
  examples/terraform-starter/env_role/required_providers.tf
  examples/terraform-starter/env_role/reviewer.tf
  examples/terraform-starter/gcp/gcp-instance.tf
  examples/terraform-starter/gcp/inputs.tf
  examples/terraform-starter/gcp/required_providers.tf
  examples/terraform-starter/main.tf
  examples/terraform-starter/oidc/auth_pref.tf
  examples/terraform-starter/oidc/inputs.tf
  examples/terraform-starter/oidc/oidc_connector.tf
  examples/terraform-starter/oidc/required_providers.tf
  examples/terraform-starter/saml/auth_pref.tf
  examples/terraform-starter/saml/inputs.tf
  examples/terraform-starter/saml/required_providers.tf
  examples/terraform-starter/saml/saml.tf
Labels: documentation, backport, size/lg, no-changelog

#46298 [v14] chore: Bump Go to v1.22.7
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#46296 [v16] chore: Bump Go to v1.22.7
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm
