Repository gravitational/teleport, pull requests merged in 2024-11, with the labels that each got.

#47173 Add a new `role.allow.request` field called `kubernetes_resources`
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources.teleport.dev_roles.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv6.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv7.mdx
  docs/pages/reference/terraform-provider/data-sources/role.mdx
  docs/pages/reference/terraform-provider/resources/role.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/role_test.go
  tool/tsh/common/tsh.go
  web/packages/teleport/src/services/kube/types.ts
Labels: ui, kubernetes-access, tsh, size/md, size/lg, backport/branch/v16, backport/branch/v17

#48168 WebShared: Update how request checkout handles kube resource related errors
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/kube.test.ts
  web/packages/shared/components/AccessRequests/NewRequest/kube.ts
  web/packages/shared/components/AccessRequests/NewRequest/useSpecifiableFields.ts
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
Labels: ui, size/md, no-changelog, backport/branch/v16, backport/branch/v17

#48023 [v17] temporarily remove app label checker for `saml_idp_service_provider` resources
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
Labels: backport, size/sm, no-changelog

#48137 [v16] Extend resource access request validation checks
  lib/services/access_request.go
  lib/services/access_request_test.go
Labels: backport, size/sm, no-changelog

#48255 new `aws-sdk-go-v2` deps
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog, backport/branch/v17

#48083 [v14] Add troubleshooting info to Usage and Billing page
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#48141 [v16] Remove nested tabs from docs pages
  docs/pages/admin-guides/access-controls/guides/locking.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/aws.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/connect-your-client/introduction.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/aws.mdx
  docs/pages/reference/architecture/architecture.mdx
Labels: documentation, backport, size/sm, no-changelog

#48242 fix agent connection to proxy behind l7 lb
  lib/service/connect.go
Labels: size/sm, no-changelog, backport/branch/v17

#48289 fix: Exempt dependabot from the changelog workflow
  .github/workflows/changelog.yaml
Labels: size/sm, no-changelog

#48204 [v17] [entraid] ignore unsuported groups members and parse nested group members
  lib/msgraph/client_test.go
  lib/msgraph/models.go
Labels: backport, size/sm, no-changelog

#48203 [v16] [entraid] ignore unsuported groups members and parse nested group members
  lib/msgraph/client_test.go
  lib/msgraph/models.go
Labels: backport, size/sm, no-changelog

#47960 Discover EKS: handle 'CONFIG_MAP' authentication mode gracefully
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: discover, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48138 [v17] Extend resource access request validation checks
  lib/services/access_request.go
  lib/services/access_request_test.go
Labels: backport, size/sm, no-changelog

#48248 Fix flaky integration tests caused by prometheus metrics conflict
  integration/tctl_terraform_env_test.go
Labels: flaky tests, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#48235 [v17] Increasing timeout for pam smoke tests
  build.assets/charts/smoke_tests/01_pam/test.sh
Labels: backport, size/sm, no-changelog

#48234 [v16] Increasing timeout for pam smoke tests
  build.assets/charts/smoke_tests/01_pam/test.sh
Labels: backport, size/sm, no-changelog

#48233 [v15] Increasing timeout for pam smoke tests
  build.assets/charts/smoke_tests/01_pam/test.sh
Labels: backport, size/sm, no-changelog

#48060 Discover EKS: handle invalid Auth Mode and Private only endpoint
  lib/integrations/awsoidc/eks_list_clusters.go
  lib/integrations/awsoidc/eks_list_clusters_test.go
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EksClustersList.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEKSCluster.test.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.story.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, discover, size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48290 [v17] fix agent connection to proxy behind l7 lb
  lib/service/connect.go
Labels: backport, size/sm, no-changelog

#48232 [v14] Increasing timeout for pam smoke tests
  build.assets/charts/smoke_tests/01_pam/test.sh
Labels: backport, size/sm, no-changelog

#48193 [v17] fix: Provide `membershipKind` fields for owners/members in tests
  integrations/operator/controllers/resources/testlib/accesslist_controller_tests.go
Labels: backport, no-changelog

#48247 Properly default auth's storage config
  lib/service/service.go
  lib/service/servicecfg/config.go
  lib/service/servicecfg/config_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48259 [v17] WebShared: Update how request checkout handles kube resource related errors
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/kube.test.ts
  web/packages/shared/components/AccessRequests/NewRequest/kube.ts
  web/packages/shared/components/AccessRequests/NewRequest/useSpecifiableFields.ts
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
Labels: ui, backport, size/md, no-changelog

#48253 docs: update External Audit Storage integration screenshot
  docs/img/externalauditstorage/integration.png
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#48136 [v17] Update wasm-pack to 0.13.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#48308 [v17] docs: update External Audit Storage integration screenshot
  docs/img/externalauditstorage/integration.png
Labels: documentation, backport, size/sm, no-changelog

#48282 [v16] gha(update-docs-webhook): use env variable in shell script
  .github/workflows/update-docs-webhook.yaml
Labels: backport, size/sm, no-changelog

#47921 add RDS to AWS Aurora db enrollment web ui tiles
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
Labels: ui, discover, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#48258 [v17] Add a new `role.allow.request` field called `kubernetes_resources`
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources.teleport.dev_roles.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv6.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv7.mdx
  docs/pages/reference/terraform-provider/data-sources/role.mdx
  docs/pages/reference/terraform-provider/resources/role.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/role_test.go
  tool/tsh/common/tsh.go
  web/packages/teleport/src/services/kube/types.ts
Labels: documentation, ui, tsh, helm, backport, size/xl

#48296 [v17] Fix flaky integration tests caused by prometheus metrics conflict
  integration/tctl_terraform_env_test.go
Labels: backport, size/sm, no-changelog

#38738 Allow including access lists in other access lists
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/usageevents/v1/usageevents.proto
  api/types/accesslist/convert/v1/member.go
  api/types/events/events.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.client.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.grpc-server.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  integrations/access/accesslist/app.go
  integrations/access/common/config.go
  integrations/access/common/teleport/client.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/authclient/api.go
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/modules/modules.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/simple/access_list.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/usagereporter_test.go
  proto/prehog/v1alpha/teleport.proto
  tool/tctl/common/acl_command.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/tsh_test.go
  web/packages/teleport/src/services/api/api.ts
Labels: tctl, size/md

#48144 [v17] Prevent SAML service provider from deletion if referenced by AWS Identity Center plugin
  lib/services/local/saml_idp_service_provider.go
  lib/services/local/saml_idp_service_provider_test.go
Labels: backport, size/sm, no-changelog

#48250 [v17] Machine ID: Fix `tshwrap` destination dir handling
  lib/tbot/tshwrap/wrap.go
  lib/tbot/tshwrap/wrap_test.go
  tool/tbot/db.go
  tool/tbot/proxy.go
Labels: backport, machine-id, size/sm, no-changelog

#47778 fix app access regression when the app is on a leaf cluster
  lib/web/app/handler.go
  lib/web/app/middleware.go
Labels: ui, size/md

#48312 [v17] Allow including Access Lists as nested members and owners
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/usageevents/v1/usageevents.proto
  api/types/accesslist/convert/v1/member.go
  api/types/events/events.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.client.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.grpc-server.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  integrations/access/accesslist/app.go
  integrations/access/common/config.go
  integrations/access/common/teleport/client.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/authclient/api.go
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/modules/modules.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/simple/access_list.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/usagereporter_test.go
  proto/prehog/v1alpha/teleport.proto
  tool/tctl/common/acl_command.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/tsh_test.go
  web/packages/teleport/src/services/api/api.ts
Labels: ui, tsh, tctl, backport, size/md

#48334 [v17] fix app access regression when the app is on a leaf cluster
  lib/web/app/handler.go
  lib/web/app/middleware.go
Labels: backport, size/sm

#48202 [v15] [entraid] ignore unsuported groups members and parse nested group members
  lib/msgraph/client_test.go
  lib/msgraph/models.go
Labels: backport, size/sm, no-changelog

#48305 [v16] Properly default auth's storage config
  lib/service/service.go
  lib/service/servicecfg/config.go
  lib/service/servicecfg/config_test.go
Labels: backport, size/sm, no-changelog

#48306 [v17] Properly default auth's storage config
  lib/service/service.go
  lib/service/servicecfg/config.go
  lib/service/servicecfg/config_test.go
Labels: backport, size/sm, no-changelog

#48304 [v15] Properly default auth's storage config
  lib/service/service.go
  lib/service/servicecfg/config.go
  lib/service/servicecfg/config_test.go
Labels: backport, size/sm, no-changelog

#48344 Release 17.0.0-alpha.3
  Makefile
  api/version.go
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#48286 Discover: update supported distro versions in pick resource screen
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
Labels: ui, discover, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48302 [v16] Discover EKS: handle invalid Auth Mode and Private only endpoint
  lib/integrations/awsoidc/eks_list_clusters.go
  lib/integrations/awsoidc/eks_list_clusters_test.go
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EksClustersList.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEKSCluster.test.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.story.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/md, no-changelog

#48303 [v17] Discover EKS: handle invalid Auth Mode and Private only endpoint
  lib/integrations/awsoidc/eks_list_clusters.go
  lib/integrations/awsoidc/eks_list_clusters_test.go
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EksClustersList.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEKSCluster.test.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.story.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/md, no-changelog

#48311 Decrease log severity when using non-resumable connection to mux
  lib/resumption/server_detect.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48301 [v15] Discover EKS: handle invalid Auth Mode and Private only endpoint
  lib/integrations/awsoidc/eks_list_clusters.go
  lib/integrations/awsoidc/eks_list_clusters_test.go
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EksClustersList.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEKSCluster.test.tsx
  web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.story.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/md, no-changelog

#48294 [v16] Discover EKS: handle 'CONFIG_MAP' authentication mode gracefully
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: backport, size/sm, no-changelog

#48295 [v15] Discover EKS: handle 'CONFIG_MAP' authentication mode gracefully
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: backport, size/sm, no-changelog

#48343 [cli] update tbot command descriptions
  lib/tbot/cli/start_application.go
  lib/tbot/cli/start_application_tunnel.go
  lib/tbot/cli/start_database.go
  lib/tbot/cli/start_database_tunnel.go
  lib/tbot/cli/start_identity.go
  lib/tbot/cli/start_kubernetes.go
  lib/tbot/cli/start_legacy.go
  lib/tbot/cli/start_spiffe_svid.go
Labels: no-changelog, backport/branch/v17

#48293 [v17] Discover EKS: handle 'CONFIG_MAP' authentication mode gracefully
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: backport, size/sm, no-changelog

#48147 [v15] docs: update cloud networking on proxy service
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#48143 Clean up spacing in login modal in Connect
  web/packages/design/src/index.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterConnect.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLoginReason.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/FormSso.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/SsoButtons.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptPasswordless/PromptPasswordless.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptSsoStatus/PromptSsoStatus.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/storyHelpers.tsx
  web/packages/teleterm/src/ui/ClusterConnect/spacing.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#48354 [v17] [cli] update tbot command descriptions
  lib/tbot/cli/start_application.go
  lib/tbot/cli/start_application_tunnel.go
  lib/tbot/cli/start_database.go
  lib/tbot/cli/start_database_tunnel.go
  lib/tbot/cli/start_identity.go
  lib/tbot/cli/start_kubernetes.go
  lib/tbot/cli/start_legacy.go
  lib/tbot/cli/start_spiffe_svid.go
Labels: backport, machine-id, size/sm, no-changelog

#48145 [v17] docs: update cloud networking on proxy service
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#48349 [v16] Decrease log severity when using non-resumable connection to mux
  lib/resumption/server_detect.go
Labels: backport, size/sm, no-changelog

#48350 [v17] Decrease log severity when using non-resumable connection to mux
  lib/resumption/server_detect.go
Labels: backport, size/sm, no-changelog

#48351 docs: update networking reference
  docs/pages/reference/networking.mdx
Labels: documentation, size/sm, no-changelog

#48317 [v17] add a hidden `--tunnel` flag to `tsh db connect` to force local proxy tunnel
  tool/tsh/common/db.go
  tool/tsh/common/db_test.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#48146 [v16] docs: update cloud networking on proxy service
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#46640 Add proto definitions and plugin spec Microsoft Teams no code integration
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/types.pb.go
  integrations/access/accessmonitoring/access_monitoring_rules.go
  integrations/access/common/recipient.go
  integrations/access/msteams/app.go
  integrations/access/msteams/bot.go
  integrations/access/msteams/config.go
  integrations/access/msteams/configure.go
  integrations/access/msteams/msapi/config.go
  integrations/access/msteams/testlib/helpers.go
  integrations/access/msteams/testlib/suite.go
  integrations/access/msteams/validate.go
  integrations/terraform/go.sum
  lib/web/apiserver.go
  lib/web/integrations.go
  web/packages/shared/utils/saveOnDisk.ts
  web/packages/teleport/src/Integrations/IntegrationList.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, size/md

#48318 [v16] add a hidden `--tunnel` flag to `tsh db connect` to force local proxy tunnel
  tool/tsh/common/db.go
  tool/tsh/common/db_test.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#48319 [v15] add a hidden `--tunnel` flag to `tsh db connect` to force local proxy tunnel
  tool/tsh/common/db.go
  tool/tsh/common/db_test.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#48346 [v16] Discover: update supported distro versions in pick resource screen
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
Labels: ui, backport, size/sm, no-changelog

#48347 [v17] Discover: update supported distro versions in pick resource screen
  web/packages/teleport/src/Discover/SelectResource/resources.tsx
Labels: ui, backport, size/sm, no-changelog

#48368 [v16] Fix markdown-lint issues
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/mongodb-self-hosted.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#48364 Fix markdown-lint issues
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/mongodb-self-hosted.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, size/sm, no-changelog

#48367 [v17] Fix markdown-lint issues
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/mongodb-self-hosted.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, backport, size/sm, no-changelog

#48356 [v17] Clean up spacing in login modal in Connect
  web/packages/design/src/index.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterConnect.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLoginReason.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/FormSso.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/SsoButtons.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptPasswordless/PromptPasswordless.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptSsoStatus/PromptSsoStatus.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/storyHelpers.tsx
  web/packages/teleterm/src/ui/ClusterConnect/spacing.ts
Labels: ui, backport, size/sm, no-changelog

#48371 Downgrade wasm-pack to 0.12.1
  build.assets/versions.mk
Labels: size/sm, no-changelog, backport/branch/v17

#48224 [v15] Update Proxy Features
  lib/service/service.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/features.go
  lib/web/features_test.go
  lib/web/integrations_awsoidc.go
  lib/web/join_tokens.go
Labels: backport, size/md, no-changelog

#48292 Move most of `lib/srv/discovery` from logrus to slog
  lib/service/discovery.go
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/database_watcher.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/srv/discovery/kube_integration_watcher_test.go
  lib/srv/discovery/kube_services_watcher.go
  lib/srv/discovery/kube_watcher.go
  lib/srv/discovery/reconciler.go
  lib/srv/discovery/status.go
Labels: size/sm, discovery, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48316 operator: fix oidc connector max age
  integrations/operator/Makefile
  integrations/operator/apis/resources/v3/oidcconnector_types.go
  integrations/operator/apis/resources/v3/oidcconnector_types_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
Labels: bug, size/sm, kube-operator, backport/branch/v14, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48321 [kube] use local image for kubernetes integration tests
  .github/workflows/kube-integration-tests-non-root.yaml
  .gitignore
  fixtures/alpine/Dockerfile
  fixtures/alpine/README.md
  fixtures/alpine/alpine-ncopa.at.alpinelinux.org.asc
  fixtures/alpine/webserver.go
  integration/kube_integration_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48240 enforce conditional updates on AutoUpdate* + rename typos
  api/types/autoupdate/rollout.go
  lib/services/autoupdates.go
  lib/services/local/autoupdate.go
  lib/services/local/autoupdate_test.go
  tool/tctl/common/edit_command_test.go
Labels: bug, size/sm, no-changelog, backport/branch/v17, merge-for-v17

#47304 Fix `tsh play` `--skip-idle-time` not working correctly
  lib/client/api.go
  lib/player/player.go
  lib/player/player_test.go
Labels: size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48374 [v16] Web: rename generic variable name to a helpful name
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.test.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
Labels: ui, backport, size/sm, no-changelog

#48386 [v14][kube] use local image for kubernetes integration tests (#48321)
  .github/workflows/kube-integration-tests-non-root.yaml
  .gitignore
  fixtures/alpine/Dockerfile
  fixtures/alpine/README.md
  fixtures/alpine/alpine-ncopa.at.alpinelinux.org.asc
  fixtures/alpine/webserver.go
  integration/kube_integration_test.go
Labels: backport, size/md, no-changelog

#48385 [v15][kube] use local image for kubernetes integration tests (#48321)
  .github/workflows/kube-integration-tests-non-root.yaml
  .gitignore
  fixtures/alpine/Dockerfile
  fixtures/alpine/README.md
  fixtures/alpine/alpine-ncopa.at.alpinelinux.org.asc
  fixtures/alpine/webserver.go
  integration/kube_integration_test.go
Labels: backport, size/md, no-changelog

#48329 fix: prevent tctl edit overwriting static file config
  tool/tctl/common/edit_command.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48380 [v17] Apply request.kubernetes_resources allow/deny settings when querying for kube resources
  lib/kube/grpc/grpc.go
  lib/kube/grpc/grpc_test.go
  lib/services/access_checker.go
  lib/services/role.go
  lib/services/role_test.go
Labels: kubernetes-access, backport, size/md, no-changelog

#48394 chore: Bump go root dependencies
  go.mod
  go.sum
  integrations/access/email/mailers.go
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/tbot/service_ssh_multiplexer.go
  lib/teleagent/agent.go
Labels: machine-id, size/sm, no-changelog

#48379 [v17] Downgrade wasm-pack to 0.12.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#48369 [v15] Fix markdown-lint issues
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/mongodb-self-hosted.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, backport, size/sm, no-changelog

#48370 [v14] Fix markdown-lint issues
  docs/pages/admin-guides/access-controls/sso/google-workspace.mdx
  docs/pages/admin-guides/deploy-a-cluster/gcp-kms.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/deploy-a-cluster/hsm.mdx
  docs/pages/contributing/documentation/style-guide.mdx
  docs/pages/upgrading/cloud-kubernetes.mdx
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
  docs/pages/upgrading/self-hosted-kubernetes.mdx
Labels: documentation, backport, size/sm, no-changelog

#47929 [teleport-update] Add support for reloading the agent & reverting symlinks on failed reload
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/process.go
  lib/autoupdate/agent/process_test.go
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  lib/utils/unpack.go
  tool/teleport-update/main.go
Labels: size/md, no-changelog

#48405 chore: Bump (more) go root dependencies
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#48365 Improve 'Please run' messages in the CI
  Makefile
  build.assets/please-run.sh
  integrations/operator/Makefile
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48406 [v17] add RDS to AWS Aurora db enrollment web ui tiles
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
Labels: ui, backport, size/sm, no-changelog

#48251 [v17] Provide isSearchable prop to paginated table
  web/packages/design/src/DataTable/Table.tsx
  web/packages/design/src/DataTable/types.ts
Labels: ui, backport, size/sm, no-changelog

#48408 Add owner property to TrustedDevices type
  web/packages/teleport/src/DeviceTrust/types.ts
Labels: ui, size/sm, no-changelog

#48393 [v15] fix: prevent tctl edit overwriting static file config
  tool/tctl/common/edit_command.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm

#48156 Fix discover reporting for static matchers
  lib/srv/discovery/status.go
Labels: size/sm, discovery, no-changelog, backport/branch/v16, backport/branch/v17

#48353 Connect: Replace legacy useStore hook with useStoreSelector in WorkspacesService
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.test.tsx
  web/packages/teleterm/src/ui/Documents/workspaceContext.tsx
  web/packages/teleterm/src/ui/Search/SearchBar.tsx
  web/packages/teleterm/src/ui/Search/SearchContext.tsx
  web/packages/teleterm/src/ui/Search/pickers/useDisplayResults.ts
  web/packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedback.test.tsx
  web/packages/teleterm/src/ui/StatusBar/ShareFeedback/useShareFeedback.ts
  web/packages/teleterm/src/ui/StatusBar/useAccessRequestCheckoutButton.ts
  web/packages/teleterm/src/ui/StatusBar/useActiveDocumentClusterBreadcrumbs.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.tsx
  web/packages/teleterm/src/ui/TopBar/AdditionalActions.tsx
  web/packages/teleterm/src/ui/TopBar/Clusters/useClusters.ts
  web/packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts
  web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts
  web/packages/teleterm/src/ui/hooks/useStoreSelector.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#48372 Allow TtyPlayer.stop to be called while still connecting
  web/packages/teleport/src/lib/term/ttyPlayer.js
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48383 [v16] Fix a redirect
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#48396 [v17] Fix `tsh play` `--skip-idle-time` not working correctly
  lib/client/api.go
  lib/player/player.go
  lib/player/player_test.go
Labels: backport, size/sm

#48397 [v16] Fix `tsh play` `--skip-idle-time` not working correctly
  lib/client/api.go
  lib/player/player.go
  lib/player/player_test.go
Labels: backport, size/sm

#48402 [v16] fix: Assert credentials individually on U2F devices
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/md

#48431 [v17] Connect: Replace legacy useStore hook with useStoreSelector in WorkspacesService
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.test.tsx
  web/packages/teleterm/src/ui/Documents/workspaceContext.tsx
  web/packages/teleterm/src/ui/Search/SearchBar.tsx
  web/packages/teleterm/src/ui/Search/SearchContext.tsx
  web/packages/teleterm/src/ui/Search/pickers/useDisplayResults.ts
  web/packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedback.test.tsx
  web/packages/teleterm/src/ui/StatusBar/ShareFeedback/useShareFeedback.ts
  web/packages/teleterm/src/ui/StatusBar/useAccessRequestCheckoutButton.ts
  web/packages/teleterm/src/ui/StatusBar/useActiveDocumentClusterBreadcrumbs.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.tsx
  web/packages/teleterm/src/ui/TopBar/AdditionalActions.tsx
  web/packages/teleterm/src/ui/TopBar/Clusters/useClusters.ts
  web/packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts
  web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts
  web/packages/teleterm/src/ui/hooks/useStoreSelector.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, backport, size/sm, no-changelog

#48425 [v16] Fix discover reporting for static matchers
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#48433 Connect: Fix fetching access requests when leaf cluster is selected
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.tsx
Labels: ui, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48428 [v16] Move most of `lib/srv/discovery` from logrus to slog
  lib/service/discovery.go
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/database_watcher.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/srv/discovery/kube_integration_watcher_test.go
  lib/srv/discovery/kube_services_watcher.go
  lib/srv/discovery/kube_watcher.go
  lib/srv/discovery/reconciler.go
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#48429 [v15] Move most of `lib/srv/discovery` from logrus to slog
  lib/service/discovery.go
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/database_watcher.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/srv/discovery/kube_integration_watcher_test.go
  lib/srv/discovery/kube_services_watcher.go
  lib/srv/discovery/kube_watcher.go
  lib/srv/discovery/reconciler.go
Labels: backport, size/sm, discovery, no-changelog

#48424 [v17] Fix discover reporting for static matchers
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#48377 [v15] operator: fix oidc connector max age
  integrations/operator/Makefile
  integrations/operator/apis/resources/v3/oidcconnector_types.go
  integrations/operator/apis/resources/v3/oidcconnector_types_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
Labels: backport, size/sm

#48376 [v16] operator: fix oidc connector max age
  integrations/operator/Makefile
  integrations/operator/apis/resources/v3/oidcconnector_types.go
  integrations/operator/apis/resources/v3/oidcconnector_types_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
Labels: backport, size/sm

#48403 [v15] fix: Assert credentials individually on U2F devices
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/md

#48410 [v16] Improve 'Please run' messages in the CI
  Makefile
  build.assets/please-run.sh
  integrations/operator/Makefile
Labels: backport, size/sm, no-changelog

#48411 [v15] Improve 'Please run' messages in the CI (#48365)
  Makefile
  build.assets/please-run.sh
  integrations/operator/Makefile
Labels: backport, size/sm, no-changelog

#48378 [v14] operator: fix oidc connector max age
  integrations/operator/Makefile
  integrations/operator/apis/resources/v3/oidcconnector_types.go
  integrations/operator/apis/resources/v3/oidcconnector_types_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
Labels: backport, size/sm

#48375 [v17] operator: fix oidc connector max age
  integrations/operator/Makefile
  integrations/operator/apis/resources/v3/oidcconnector_types.go
  integrations/operator/apis/resources/v3/oidcconnector_types_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
Labels: backport, size/sm

#48441 [v16] Connect: Fix fetching access requests when leaf cluster is selected
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.tsx
Labels: ui, backport, size/sm

#48440 [v17] Connect: Fix fetching access requests when leaf cluster is selected
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.tsx
Labels: ui, backport, size/sm

#48390 [v17] enforce conditional updates on AutoUpdate* + rename typos
  api/types/autoupdate/rollout.go
  lib/services/autoupdates.go
  lib/services/local/autoupdate.go
  lib/services/local/autoupdate_test.go
  tool/tctl/common/edit_command_test.go
Labels: tctl, backport, size/sm, no-changelog

#48426 [v17] Move most of `lib/srv/discovery` from logrus to slog
  lib/service/discovery.go
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/database_watcher.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/srv/discovery/kube_integration_watcher_test.go
  lib/srv/discovery/kube_services_watcher.go
  lib/srv/discovery/kube_watcher.go
  lib/srv/discovery/reconciler.go
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#48245 adding missing GID value when fetching Hostuser
  integration/hostuser_test.go
  lib/srv/usermgmt.go
Labels: size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48409 [v17] Improve 'Please run' messages in the CI
  Makefile
  build.assets/please-run.sh
  integrations/operator/Makefile
Labels: backport, size/sm, no-changelog

#48432 docs: include aws oidc in integration list
  docs/pages/admin-guides/management/guides/guides.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48359 Make conditional vs unconditional updates clearer
  lib/services/local/access_monitoring_rules.go
  lib/services/local/databaseobject.go
  lib/services/local/databaseobjectimportrule.go
  lib/services/local/generic/generic_wrapper.go
  lib/services/local/generic/generic_wrapper_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#48450 support plugin audit events in web ui
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#47501 [v15] Simplify `IsBoringCrypto`
  lib/auth/native/boring.go
  lib/auth/native/native.go
  lib/auth/native/notboring.go
Labels: backport, size/sm, no-changelog

#48458 [v17] docs: include aws oidc in integration list
  docs/pages/admin-guides/management/guides/guides.mdx
Labels: documentation, backport, size/sm, no-changelog

#48460 [v15] docs: include aws oidc in integration list
  docs/pages/admin-guides/management/guides/guides.mdx
Labels: documentation, backport, size/sm, no-changelog

#47502 [v14] Simplify `IsBoringCrypto`
  lib/auth/native/boring.go
  lib/auth/native/native.go
  lib/auth/native/notboring.go
Labels: backport, size/sm, no-changelog

#48035 Teleport Connect allow SSO hostname
  api/client/webclient/webclient.go
  api/profile/profile.go
  gen/proto/go/teleport/lib/teleterm/v1/cluster.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/cluster_pb.ts
  lib/client/api.go
  lib/client/client_store.go
  lib/client/profile.go
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/storage.go
  lib/web/apiserver.go
  proto/teleport/lib/teleterm/v1/cluster.proto
  web/packages/teleterm/src/mainProcess/rootClusterProxyHostAllowList.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#47500 [v16] Simplify `IsBoringCrypto`
  lib/auth/native/boring.go
  lib/auth/native/native.go
  lib/auth/native/notboring.go
Labels: backport, size/sm, no-changelog

#48459 [v16] docs: include aws oidc in integration list
  docs/pages/admin-guides/management/guides/guides.mdx
Labels: documentation, backport, size/sm, no-changelog

#48461 [v17] support plugin audit events in web ui
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#48462 [v16] support plugin audit events in web ui
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#48463 [v15] support plugin audit events in web ui
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#48474 Narrow EnrollStatus type in web UI
  web/packages/teleport/src/DeviceTrust/types.ts
Labels: ui, size/sm, no-changelog

#48455 [v16] adding missing GID value when fetching Hostuser
  integration/hostuser_test.go
  lib/srv/usermgmt.go
Labels: backport, size/sm

#48454 [v17] adding missing GID value when fetching Hostuser
  integration/hostuser_test.go
  lib/srv/usermgmt.go
Labels: backport, size/sm

#48413 [v16] Add Connect and Web UI support for selecting Kubernetes namespaces during access requests
  web/packages/design/src/DataTable/Table.tsx
  web/packages/design/src/DataTable/types.ts
  web/packages/design/src/Link/Link.jsx
  web/packages/design/src/Onboard/__snapshots__/WelcomeWrapper.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/CheckableOption.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/CrossIcon.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.test.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/index.ts
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/Apps.tsx
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/ResourceList.tsx
  web/packages/shared/components/AccessRequests/NewRequest/index.ts
  web/packages/shared/components/AccessRequests/NewRequest/kube.test.ts
  web/packages/shared/components/AccessRequests/NewRequest/kube.ts
  web/packages/shared/components/AccessRequests/NewRequest/resource.ts
  web/packages/shared/components/AccessRequests/NewRequest/useSpecifiableFields.ts
  web/packages/shared/components/AccessRequests/Shared/utils.ts
  web/packages/shared/components/FieldSelect/FieldSelect.tsx
  web/packages/shared/components/Select/types.ts
  web/packages/shared/services/accessRequests/accessRequests.ts
  web/packages/shared/utils/text.test.ts
  web/packages/shared/utils/text.ts
  web/packages/teleport/src/AccessRequests/__snapshots__/AccessRequests.story.test.tsx.snap
  web/packages/teleport/src/AccessRequests/service.ts
  web/packages/teleport/src/AccessRequests/types.ts
  web/packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Welcome/NewCredentials/__snapshots__/NewCredentials.story.test.tsx.snap
  web/packages/teleport/src/config.ts
  web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
  web/packages/teleterm/src/ui/DocumentAccessRequests/NewRequest/NewRequest.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/NewRequest/useNewRequest.ts
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
Labels: ui, backport, size/lg

#48457 Fixing some issues with the Mac build for ent
  build.assets/build-package.sh
  build.assets/build-pkg-app.sh
  build.assets/macos/install
Labels: backport, size/sm, no-changelog, backport/branch/v17

#48407 [v16] add RDS to AWS Aurora db enrollment web ui tiles
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/databases.tsx
Labels: ui, backport, size/sm, no-changelog

#48481 ensure ca caches include correct revision
  lib/services/local/trust.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48176 upsert trusted cluster cleanup
  lib/auth/trustedcluster.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48486 [v15] ensure ca caches include correct revision
  lib/services/local/trust.go
Labels: backport, size/sm, no-changelog

#48488 [v17] ensure ca caches include correct revision
  lib/services/local/trust.go
Labels: backport, size/sm, no-changelog

#48492 [v16] fix makefile typo
  Makefile
Labels: backport, size/sm, no-changelog

#48415 Machine ID: Fix usage of "starts" and "configures" in help text
  lib/tbot/cli/cli_test.go
  lib/tbot/cli/start_application.go
  lib/tbot/cli/start_application_tunnel.go
  lib/tbot/cli/start_database.go
  lib/tbot/cli/start_database_tunnel.go
  lib/tbot/cli/start_identity.go
  lib/tbot/cli/start_kubernetes.go
  lib/tbot/cli/start_legacy.go
  lib/tbot/cli/start_shared.go
  lib/tbot/cli/start_spiffe_svid.go
  tool/tbot/main.go
Labels: machine-id, size/sm, no-changelog, backport/branch/v17

#48170 [v16] Use cloud anonymization key (#46819)
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/helpers.go
  lib/modules/modules.go
  lib/modules/modules_test.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/usagereporter.go
  lib/utils/anonymizer.go
  lib/web/features.go
Labels: backport, size/md, no-changelog

#48387 [v16] Add a new `role.allow.request` field called kubernetes_resources
  api/proto/teleport/legacy/types/types.proto
  api/types/role.go
  api/types/role_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources.teleport.dev_roles.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv6.mdx
  docs/pages/reference/operator-resources/resources.teleport.dev_rolesv7.mdx
  docs/pages/reference/terraform-provider/data-sources/role.mdx
  docs/pages/reference/terraform-provider/resources/role.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/kube/grpc/grpc.go
  lib/kube/grpc/grpc_test.go
  lib/services/access_checker.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/role.go
  lib/services/role_test.go
  tool/tsh/common/tsh.go
  web/packages/teleport/src/services/kube/types.ts
Labels: documentation, ui, kubernetes-access, tsh, helm, backport, size/xl

#48171 [v17] Use cloud anonymization key
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/helpers.go
  lib/modules/modules.go
  lib/modules/modules_test.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/usagereporter.go
  lib/utils/anonymizer.go
  lib/web/features.go
Labels: backport, size/md, no-changelog

#48169 [v15] Use cloud anonymization key
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/helpers.go
  lib/modules/modules.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/usagereporter.go
  lib/utils/anonymizer.go
  lib/web/features.go
Labels: backport, size/md, no-changelog

#48484 [v17] Fixing some issues with the Mac build for ent
  build.assets/build-package.sh
  build.assets/build-pkg-app.sh
  build.assets/macos/install
Labels: backport, size/sm, no-changelog

#48323 Make `tsh puttyconfig` disable GSSApi auth
  tool/tsh/common/putty_config_windows.go
Labels: windows, tsh, size/sm, PuTTY, backport/branch/v14, backport/branch/v15, backport/branch/v16, backport/branch/v17

#48467 [v17] Teleport Connect allow SSO hostname
  api/client/webclient/webclient.go
  api/profile/profile.go
  gen/proto/go/teleport/lib/teleterm/v1/cluster.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/cluster_pb.ts
  lib/client/api.go
  lib/client/client_store.go
  lib/client/profile.go
  lib/teleterm/apiserver/handler/handler_clusters.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_auth.go
  lib/teleterm/clusters/storage.go
  lib/web/apiserver.go
  proto/teleport/lib/teleterm/v1/cluster.proto
  web/packages/teleterm/src/mainProcess/rootClusterProxyHostAllowList.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
Labels: ui, backport, size/sm, no-changelog

#47946 Add user type (local or sso) to tlsca.Identity
  lib/auth/auth_test.go
  lib/tlsca/ca.go
  lib/tlsca/ca_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17
