Repository gravitational/teleport, pull requests merged in 2024-08, with the labels that each got.

#44888 Add device trust web redirect to githubCallback
  lib/web/apiserver.go
Labels: backport-required, size/sm, backport/branch/v16

#44883 [v16] Workload Identity: Kubernetes Workload Attestation (#44209)
  go.mod
  go.sum
  lib/tbot/config/service_spiffe_workload_api.go
  lib/tbot/config/service_spiffe_workload_api_test.go
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/minimal.golden
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_spiffe_workload_api_test.go
  lib/tbot/spiffe/workloadattest/attest.go
  lib/tbot/spiffe/workloadattest/kubernetes.go
  lib/tbot/spiffe/workloadattest/kubernetes_unix.go
  lib/tbot/spiffe/workloadattest/kubernetes_unix_test.go
  lib/tbot/spiffe/workloadattest/kubernetes_windows.go
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-docker-desktop
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-gcp-v1.29.5-gke.1091002
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-k3s-ubuntu-v1.28.6+k3s2
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-orbstack
  lib/tbot/spiffe/workloadattest/unix.go
  lib/tbot/spiffe/workloadattest/unix_test.go
Labels: backport, machine-id, size/lg

#44868 VNet: Use NSObject instead of C struct in XPC message
  lib/vnet/daemon/client_darwin.go
  lib/vnet/daemon/client_darwin.h
  lib/vnet/daemon/client_darwin.m
  lib/vnet/daemon/common_darwin.h
  lib/vnet/daemon/common_darwin.m
  lib/vnet/daemon/service_darwin.m
Labels: size/sm, no-changelog, backport/branch/v16

#44884 [v15] Workload Identity: Kubernetes Workload Attestation (#44209)
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/tbot/config/service_spiffe_workload_api.go
  lib/tbot/config/service_spiffe_workload_api_test.go
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/minimal.golden
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_spiffe_workload_api_test.go
  lib/tbot/spiffe/workloadattest/attest.go
  lib/tbot/spiffe/workloadattest/kubernetes.go
  lib/tbot/spiffe/workloadattest/kubernetes_unix.go
  lib/tbot/spiffe/workloadattest/kubernetes_unix_test.go
  lib/tbot/spiffe/workloadattest/kubernetes_windows.go
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-docker-desktop
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-gcp-v1.29.5-gke.1091002
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-k3s-ubuntu-v1.28.6+k3s2
  lib/tbot/spiffe/workloadattest/testdata/mountfile/k8s-real-orbstack
  lib/tbot/spiffe/workloadattest/unix.go
  lib/tbot/spiffe/workloadattest/unix_test.go
Labels: backport, machine-id, size/lg

#44741 [v16] Update xterm
  pnpm-lock.yaml
  web/packages/teleport/package.json
  web/packages/teleport/src/Console/DocumentSsh/Terminal/Terminal.tsx
  web/packages/teleport/src/Console/StyledXterm/StyledXterm.tsx
  web/packages/teleport/src/lib/term/terminal.ts
  web/packages/teleterm/package.json
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts
Labels: ui, backport, size/sm, no-changelog

#44909 Web: fix undefined limit sending undefined as a value to backend
  web/packages/teleport/src/generateResourcePath.test.ts
  web/packages/teleport/src/generateResourcePath.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44811 [v16] Backport part of the typography changes
  web/packages/design/src/Text/Text.jsx
  web/packages/design/src/Text/index.js
  web/packages/design/src/index.ts
  web/packages/design/src/theme/typography.js
Labels: ui, backport, size/md, no-changelog

#44757 Add a section about typography to the design package readme file
  web/packages/design/README.md
Labels: ui, size/sm, no-changelog

#44924 iam-join: Add additional test cases to cover assumed-role arns
  lib/auth/join_iam_test.go
Labels: size/md, no-changelog

#44843 Add OneLogin entity descriptor URL instructions
  docs/pages/access-controls/sso/one-login.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44914 Remove warnings about passwordless support in Firefox
  web/packages/teleport/src/Welcome/NewCredentials/NewPasswordlessDevice.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44949 pluralize: Return plural noun when num is 0
  web/packages/shared/utils/text.test.ts
  web/packages/shared/utils/text.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44692 teleterm: Close VNet service before stopping gRPC server
  lib/teleterm/apiserver/apiserver.go
Labels: size/sm, no-changelog, backport/branch/v16

#44922 Add a separate `package.json` for `docs/check-redirects`
  docs/check-redirects/README.md
  docs/check-redirects/check-redirects.js
  docs/check-redirects/index.js
  docs/check-redirects/package.json
  docs/check-redirects/pnpm-lock.yaml
  docs/check-redirects/pnpm-workspace.yaml
Labels: documentation, size/xl, no-changelog

#44937 docs: include apps in locking description
  docs/pages/access-controls/guides/locking.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44707 link to ECS service for RDS enrollment
  api/gen/proto/go/teleport/integration/v1/awsoidc_service.pb.go
  api/proto/teleport/integration/v1/awsoidc_service.proto
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
Labels: aws, size/sm, no-changelog, backport/branch/v16

#44920 Fix the login page divider
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44853 Add Query field to CrownJewel specifications
  api/gen/proto/go/teleport/crownjewel/v1/crownjewel.pb.go
  api/proto/teleport/crownjewel/v1/crownjewel.proto
  lib/auth/crownjewel/object.go
  lib/auth/crownjewel/object_test.go
  lib/services/crown_jewels_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#44893 [kube] fix greedy deny rule blocking namespace list when blocking other resources
  lib/kube/proxy/forwarder.go
  lib/services/role.go
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: kubernetes-access, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#44901 Update TeleportGearIcon with new logo
  web/packages/design/src/SVGIcon/TeleportGearIcon.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44941 re-add grace period to Upload completer (again)
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/azsessions/azsessions.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/uploader.go
  lib/events/filesessions/filestream.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream_test.go
Labels: audit-log, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#44943 docs: Don't provide commands to use Homebrew
  docs/pages/access-controls/guides/passwordless.mdx
  docs/pages/includes/install-tsh.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44975 [v15] [kube] fix greedy deny rule blocking namespace list when blocking other resources
  lib/kube/proxy/forwarder.go
  lib/services/role.go
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: kubernetes-access, backport, size/md

#44976 [v14] [kube] fix greedy deny rule blocking namespace list when blocking other resources
  lib/kube/proxy/forwarder.go
  lib/services/role.go
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: kubernetes-access, backport, size/md

#44974 [v16] [kube] fix greedy deny rule blocking namespace list when blocking other resources
  lib/kube/proxy/forwarder.go
  lib/services/role.go
  lib/utils/replace.go
  lib/utils/replace_test.go
Labels: kubernetes-access, backport, size/md

#44906 [v16] Add device trust web redirect to githubCallback
  lib/web/apiserver.go
Labels: backport, size/sm

#44918 [v16] VNet: Use NSObject instead of C struct in XPC message
  lib/vnet/daemon/client_darwin.go
  lib/vnet/daemon/client_darwin.h
  lib/vnet/daemon/client_darwin.m
  lib/vnet/daemon/common_darwin.h
  lib/vnet/daemon/common_darwin.m
  lib/vnet/daemon/service_darwin.m
Labels: backport, size/sm, no-changelog

#44896 [v15] update db enrollment task role instructions
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
Labels: ui, backport, size/sm, no-changelog

#44895 [v16] update db enrollment task role instructions
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
Labels: ui, backport, size/sm, no-changelog

#44973 [v16] link to ECS service for RDS enrollment
  api/gen/proto/go/teleport/integration/v1/awsoidc_service.pb.go
  api/proto/teleport/integration/v1/awsoidc_service.proto
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
Labels: backport, size/sm, no-changelog

#44897 [v14] update db enrollment task role instructions
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
Labels: ui, backport, size/sm, no-changelog

#44886 [v16] Add discovery label account ID when deploying services
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#44887 [v15] Add discovery label account ID when deploying services
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#44963 [v16] Web: fix undefined limit sending undefined as a value to backend
  web/packages/teleport/src/generateResourcePath.test.ts
  web/packages/teleport/src/generateResourcePath.ts
Labels: ui, backport, size/sm, no-changelog

#44911 [v14] Add discovery label account ID when deploying services
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#44964 [v15] Web: fix undefined limit sending undefined as a value to backend
  web/packages/teleport/src/generateResourcePath.test.ts
  web/packages/teleport/src/generateResourcePath.ts
Labels: ui, backport, size/sm, no-changelog

#44907 Machine ID: Document 24h TTL limit and warn when exceeded
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
  lib/tbot/config/config.go
Labels: documentation, machine-id, size/sm, backport/branch/v15, backport/branch/v16

#44965 [v14] Web: fix undefined limit sending undefined as a value to backend
  web/packages/teleport/src/generateResourcePath.test.ts
  web/packages/teleport/src/generateResourcePath.ts
Labels: ui, backport, size/sm, no-changelog

#44706 web: resource access request for `saml_idp_service_provider`
  api/types/constants.go
  lib/services/local/presence.go
  lib/web/apiserver.go
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/ResourceList.story.tsx
  web/packages/shared/components/AccessRequests/NewRequest/resource.ts
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/__snapshots__/RequestView.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/Shared/utils.ts
  web/packages/shared/components/AccessRequests/fixtures/index.ts
  web/packages/teleport/src/services/agents/types.ts
  web/packages/teleterm/src/ui/DocumentAccessRequests/NewRequest/NewRequest.tsx
Labels: ui, size/sm, no-changelog

#44904 Machine ID: Remove `BOT_INSTANCE_EXPERIMENT` feature flag
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/bot_test.go
  lib/auth/machineid/machineidv1/bot_instance_experiment/experiment.go
  lib/tbot/tbot.go
Labels: machine-id, size/sm

#44857 Clean up dependencies after migrating to Storybook v8
  jest.config.js
  package.json
  pnpm-lock.yaml
  web/packages/build/.babelrc.js
  web/packages/build/package.json
Labels: documentation, ui, size/sm, no-changelog

#44984 fix errors.As() panic in msteams plugin
  integrations/access/msteams/msapi/graph_client.go
Labels: bug, size/sm, backport/branch/v15, backport/branch/v16

#44536 [v16] Add `application-tunnel` to Machine ID docs
  docs/pages/enroll-resources/machine-id/access-guides/applications.mdx
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#44980 [v14] re-add grace period to Upload completer (again)
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/azsessions/azsessions.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/uploader.go
  lib/events/filesessions/filestream.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream_test.go
Labels: audit-log, backport, size/md

#44978 [v16] re-add grace period to Upload completer (again)
  lib/events/api.go
  lib/events/auditlog.go
  lib/events/azsessions/azsessions.go
  lib/events/complete.go
  lib/events/complete_test.go
  lib/events/eventstest/uploader.go
  lib/events/filesessions/filestream.go
  lib/events/gcssessions/gcsstream.go
  lib/events/s3sessions/s3stream.go
  lib/events/stream_test.go
Labels: audit-log, backport, size/md

#44870 Workload Identity: Federation bundle endpoint
  lib/web/apiserver.go
  lib/web/spiffe.go
  lib/web/spiffe_test.go
Labels: size/md, backport/branch/v15, backport/branch/v16

#44873 Fix the button border color for the neutral+border combination
  web/packages/design/src/Button/Button.tsx
  web/packages/design/src/Button/__snapshots__/buttons.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/__snapshots__/ResourceList.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/__snapshots__/RequestView.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
Labels: ui, size/sm, no-changelog

#44966 Update automatic-agent-updates.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
Labels: documentation, size/sm, backport/branch/v15, backport/branch/v16

#44995 [v16] teleterm: Close VNet service before stopping gRPC server
  lib/teleterm/apiserver/apiserver.go
Labels: backport, size/sm, no-changelog

#44850 [v16] docs: monitoring and metrics overhaul
  docs/pages/management/diagnostics.mdx
Labels: documentation, backport, size/md, no-changelog

#45005 chore: Bump AWS modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/srv/app/aws/endpoints.go
Labels: application-access, size/sm, no-changelog

#45009 chore: Bump google.golang.org/grpc/cmd/protoc-gen-go-grpc to v1.5.1
  api/gen/proto/go/teleport/accessgraph/v1/secrets_service_grpc.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/gen/proto/go/teleport/accessmonitoringrules/v1/access_monitoring_rules_service_grpc.pb.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog_grpc.pb.go
  api/gen/proto/go/teleport/clusterconfig/v1/clusterconfig_service_grpc.pb.go
  api/gen/proto/go/teleport/crownjewel/v1/crownjewel_service_grpc.pb.go
  api/gen/proto/go/teleport/dbobject/v1/dbobject_service_grpc.pb.go
  api/gen/proto/go/teleport/dbobjectimportrule/v1/dbobjectimportrule_service_grpc.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service_grpc.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service_grpc.pb.go
  api/gen/proto/go/teleport/externalauditstorage/v1/externalauditstorage_service_grpc.pb.go
  api/gen/proto/go/teleport/integration/v1/awsoidc_service_grpc.pb.go
  api/gen/proto/go/teleport/integration/v1/integration_service_grpc.pb.go
  api/gen/proto/go/teleport/kube/v1/kube_service_grpc.pb.go
  api/gen/proto/go/teleport/kubewaitingcontainer/v1/kubewaitingcontainer_service_grpc.pb.go
  api/gen/proto/go/teleport/loginrule/v1/loginrule_service_grpc.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_instance_service_grpc.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_service_grpc.pb.go
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service_grpc.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service_grpc.pb.go
  api/gen/proto/go/teleport/okta/v1/okta_service_grpc.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/gen/proto/go/teleport/presence/v1/service_grpc.pb.go
  api/gen/proto/go/teleport/resourceusage/v1/resourceusage_service_grpc.pb.go
  api/gen/proto/go/teleport/samlidp/v1/samlidp_grpc.pb.go
  api/gen/proto/go/teleport/scim/v1/scim_service_grpc.pb.go
  api/gen/proto/go/teleport/secreports/v1/secreports_service_grpc.pb.go
  api/gen/proto/go/teleport/transport/v1/transport_service_grpc.pb.go
  api/gen/proto/go/teleport/trust/v1/trust_service_grpc.pb.go
  api/gen/proto/go/teleport/userloginstate/v1/userloginstate_service_grpc.pb.go
  api/gen/proto/go/teleport/userprovisioning/v1/statichostuser_service_grpc.pb.go
  api/gen/proto/go/teleport/users/v1/users_service_grpc.pb.go
  api/gen/proto/go/teleport/vnet/v1/vnet_config_service_grpc.pb.go
  api/gen/proto/go/userpreferences/v1/userpreferences_grpc.pb.go
  gen/proto/go/accessgraph/v1alpha/access_graph_service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/vnet/v1/vnet_service_grpc.pb.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/multiplexer/test/ping_grpc.pb.go
Labels: size/sm, no-changelog

#45012 [v15] fix errors.As() panic in msteams plugin
  integrations/access/msteams/msapi/graph_client.go
Labels: backport, size/sm

#45017 Fix SVG attributes
  web/packages/design/src/SVGIcon/TeleportGearIcon.tsx
Labels: ui, size/sm, no-changelog

#44971 [v15] docs: include apps in locking description
  docs/pages/access-controls/guides/locking.mdx
Labels: documentation, backport, size/sm, no-changelog

#44970 [v16] docs: include apps in locking description
  docs/pages/access-controls/guides/locking.mdx
Labels: documentation, backport, size/sm, no-changelog

#44972 [v14] docs: include apps in locking description
  docs/pages/access-controls/guides/locking.mdx
Labels: documentation, backport, size/sm, no-changelog

#44946 [v16] Add OneLogin entity descriptor URL instructions
  docs/pages/access-controls/sso/one-login.mdx
Labels: documentation, backport, size/sm, no-changelog

#45003 [v16] Update TeleportGearIcon with new logo
  web/packages/design/src/SVGIcon/TeleportGearIcon.tsx
Labels: ui, backport, size/sm, no-changelog

#45002 [v15] Update TeleportGearIcon with new logo
  web/packages/design/src/SVGIcon/TeleportGearIcon.tsx
Labels: ui, backport, size/sm, no-changelog

#45011 [v16] fix errors.As() panic in msteams plugin
  integrations/access/msteams/msapi/graph_client.go
Labels: backport, size/sm

#44989 [v16] Machine ID: Document 24h TTL limit and warn when exceeded
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
  lib/tbot/config/config.go
Labels: documentation, backport, machine-id, size/sm

#44988 [v15] Machine ID: Document 24h TTL limit and warn when exceeded
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
  lib/tbot/config/config.go
Labels: documentation, backport, machine-id, size/sm

#44993 Machine ID: Only set legacy generation counter for renewable joins
  lib/auth/bot.go
Labels: size/sm, no-changelog

#45008 chore: Bump gcloud modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#44838 Update install script references to use CDN
  .github/workflows/post-release.yaml
  docs/config.json
  docs/pages/deploy-a-cluster/linux-demo.mdx
  docs/pages/includes/install-linux-oss.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/installation.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  examples/agent-pool-terraform/teleport/userdata
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#44981 [v16] Add Query field to CrownJewel specifications
  api/gen/proto/go/teleport/crownjewel/v1/crownjewel.pb.go
  api/proto/teleport/crownjewel/v1/crownjewel.proto
  lib/auth/crownjewel/object.go
  lib/auth/crownjewel/object_test.go
  lib/services/crown_jewels_test.go
Labels: backport, size/sm, no-changelog

#45037 docs: remove prerequisites notice that tctl only linux and macos
  docs/pages/includes/tctl.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#44760 [v15] Change to using tctl desktop ls
  docs/pages/choose-an-edition/migrate-to-cloud.mdx
Labels: documentation, backport, size/sm, no-changelog

#45001 [v14] Update TeleportGearIcon with new logo
  web/packages/design/src/SVGIcon/TeleportGearIcon.tsx
Labels: ui, backport, size/sm, no-changelog

#44869 Strictly check attributes in button wrappers
  web/packages/design/src/Button/Button.tsx
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
  web/packages/teleport/src/Login/Motd/Motd.tsx
  web/packages/teleport/src/Users/UserAddEdit/TraitsEditor.tsx
Labels: ui, size/sm, no-changelog

#44982 [v15] Add Query field to CrownJewel specifications
  api/gen/proto/go/teleport/crownjewel/v1/crownjewel.pb.go
  api/proto/teleport/crownjewel/v1/crownjewel.proto
  lib/auth/crownjewel/object.go
  lib/auth/crownjewel/object_test.go
  lib/services/crown_jewels_test.go
Labels: backport, size/sm, no-changelog

#44474 hide the flag that allows users to pass their own Okta SCIM auth token to tctl
  tool/tctl/common/plugin/okta.go
Labels: tctl, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45059 docs: update tctl references to include windows
  docs/pages/enroll-resources/server-access/getting-started.mdx
  docs/pages/installation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#45014 Set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env vars in Teleport Connect
  web/packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
Labels: ui, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#44986 [v16] Document SSO caveats on UserSpecV2.TrustedDeviceIDs
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/reference/terraform-provider/data-sources/user.mdx
  docs/pages/reference/terraform-provider/resources/user.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_users.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_users.yaml
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, helm, backport, size/sm, no-changelog

#44879 [v16] Fix Help And Support links
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#44878 [v15] Fix Help And Support links
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#45043 [v16] Update electron to 31.3.1 and electron-builder to 25.0.3
  pnpm-lock.yaml
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/package.json
Labels: ui, backport, size/sm, no-changelog

#45044 [v15] Update electron and electron-builder
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#45042 Clean up electron-builder peer deps
  pnpm-lock.yaml
Labels: size/sm, no-changelog

#45045 [v14] Update electron and electron-builder
  web/packages/build/package.json
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#45019 Document changes to auto-enroll since v16.1.1
  docs/pages/access-controls/device-trust/device-management.mdx
  docs/pages/access-controls/guides/webauthn.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#44940 [v16] Fill in missing CHANGELOG releases
  CHANGELOG.md
Labels: backport, size/md, no-changelog

#45062 [v16] docs: update tctl references to include windows
  docs/pages/enroll-resources/server-access/getting-started.mdx
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#45052 [v15] Remove warnings about passwordless support in Firefox
  web/packages/teleport/src/Welcome/NewCredentials/NewPasswordlessDevice.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
Labels: ui, backport, size/sm, no-changelog

#45053 [v14] Remove warnings about passwordless support in Firefox
  web/packages/teleport/src/Welcome/NewCredentials/NewPasswordlessDevice.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
Labels: ui, backport, size/sm, no-changelog

#45007 [v15] docs: include tpm in machine-id token join reference
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#45006 [v16] docs: include tpm in machine-id token join reference
  docs/pages/enroll-resources/machine-id/reference/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#45041 Add Protobuf types for SPIFFE Federation resource and audit events
  api/gen/proto/go/teleport/machineid/v1/federation.pb.go
  api/gen/proto/go/teleport/machineid/v1/federation_service.pb.go
  api/gen/proto/go/teleport/machineid/v1/federation_service_grpc.pb.go
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/machineid/v1/federation.proto
  api/proto/teleport/machineid/v1/federation_service.proto
  api/types/constants.go
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  lib/events/events_test.go
Labels: audit-log, size/md, no-changelog, backport/branch/v15, backport/branch/v16

#45072 docs: adding getting-started to route to linux demo
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#45036 docs: include all services in kube agent description
  docs/pages/installation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#44985 Add Device Trust Requirement icon to web UI
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/sessions.go
  lib/web/apiserver.go
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ShieldWarning.tsx
  web/packages/design/src/Icon/assets/ShieldWarning.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/DeviceTrust/types.ts
  web/packages/teleport/src/Login/useLogin.ts
  web/packages/teleport/src/TopBar/DeviceTrustIcon.tsx
  web/packages/teleport/src/TopBar/DeviceTrustStatus.tsx
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/components/Authenticated/Authenticated.tsx
  web/packages/teleport/src/components/UserMenuNav/UserMenuNav.test.tsx
  web/packages/teleport/src/components/UserMenuNav/UserMenuNav.tsx
  web/packages/teleport/src/services/websession/websession.ts
Labels: ui, backport-required, size/md, backport/branch/v16

#45051 [v16] Remove warnings about passwordless support in Firefox
  web/packages/teleport/src/Welcome/NewCredentials/NewPasswordlessDevice.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
Labels: ui, backport, size/sm, no-changelog

#45063 [v16] Set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env vars in Teleport Connect
  web/packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
Labels: ui, backport, size/sm

#45064 [v15] Set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env vars in Teleport Connect
  web/packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
Labels: ui, backport, size/sm

#45076 [v15] docs: include all services in kube agent description
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#45074 [v16] docs: adding getting-started to route to linux demo
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#45061 [v15] Update install script references to use CDN (#44838)
  .github/workflows/post-release.yaml
  docs/config.json
  docs/pages/deploy-a-cluster/linux-demo.mdx
  docs/pages/includes/install-linux-oss.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/installation.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  examples/agent-pool-terraform/teleport/userdata
Labels: documentation, backport, size/sm, no-changelog

#44950 integrations: build with -trimpath option
  integrations/access/common.mk
  integrations/event-handler/Makefile
  integrations/operator/Makefile
  integrations/terraform/Makefile
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45060 [v16] Update install script references to use CDN (#44838)
  .github/workflows/post-release.yaml
  docs/config.json
  docs/pages/deploy-a-cluster/linux-demo.mdx
  docs/pages/includes/install-linux-oss.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/installation.mdx
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  examples/agent-pool-terraform/teleport/userdata
Labels: documentation, backport, size/sm, no-changelog

#45075 [v16] docs: include all services in kube agent description
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#45081 docs: include tctl.exe in uninstalling from windows
  docs/pages/admin-guides/management/admin/uninstall-teleport.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#45090 [v16] docs: include tctl.exe in uninstalling from windows
  docs/pages/management/admin/uninstall-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#45071 [v16] Document that crdb can be used a a pg replacement for events
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#45065 [v14] Set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env vars in Teleport Connect
  web/packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
Labels: ui, backport, size/sm

#45049 [v16] pluralize: Return plural noun when num is 0
  web/packages/shared/utils/text.test.ts
  web/packages/shared/utils/text.ts
Labels: ui, backport, size/sm, no-changelog

#44936 Allow passing arguments to Storybook from CLI
  package.json
  web/scripts/run-storybook.sh
Labels: ui, size/sm, no-changelog

#45057 Update Resource Guidelines RFD to mention adding parser for Resource
  rfd/0153-resource-guidelines.md
Labels: rfd, size/sm, no-changelog

#45088 Remove last traces of webpack
  web/packages/README.md
  web/packages/build/webpack/resolvepath.js
  web/packages/build/webpack/webpack.base.js
  web/packages/teleterm/build_resources/README.md
  web/packages/teleterm/src/staticConfig.ts
Labels: ui, size/sm, no-changelog

#45112 Remove `VirtualScroll` component
  web/packages/teleterm/src/ui/components/VirtualScroll/VirtualScroll.story.tsx
  web/packages/teleterm/src/ui/components/VirtualScroll/VirtualScroll.tsx
  web/packages/teleterm/src/ui/components/VirtualScroll/index.ts
  web/packages/teleterm/src/ui/components/VirtualScroll/prepareVirtualScrollItems.ts
  web/packages/teleterm/src/ui/components/VirtualScroll/types.ts
  web/packages/teleterm/src/ui/components/VirtualScroll/useVirtualScrollNodes.tsx
Labels: ui, size/sm, no-changelog

#45108 docs: include Panther link in export audit logs intro
  docs/pages/admin-guides/management/export-audit-events.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#45120 tctl: Fix typo in tctl desktop bootstrap
  lib/auth/windows/configure-ad.ps1
Labels: size/sm, no-changelog, backport/branch/v16

#45106 Update pnpm to 9.6.0
  package.json
Labels: size/sm, no-changelog, backport/branch/v16

#45125 [v16] tctl: Fix typo in tctl desktop bootstrap
  lib/auth/windows/configure-ad.ps1
Labels: backport, size/sm, no-changelog

#45127 [v15] docs: Don't provide commands to use Homebrew
  docs/pages/access-controls/guides/passwordless.mdx
  docs/pages/includes/install-tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#45126 [v14] docs: Don't provide commands to use Homebrew
  docs/pages/access-controls/guides/passwordless.mdx
  docs/pages/includes/install-tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#45101 Make bot resources honour their expiry
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
Labels: size/md, backport/branch/v15, backport/branch/v16

#45121 Fix singing -> signing typos where necessary
  integrations/kube-agent-updater/hack/cosign-fixtures.go
  integrations/kube-agent-updater/pkg/img/doc.go
  lib/auth/saml.go
  lib/services/saml.go
  lib/services/saml_test.go
Labels: size/sm, no-changelog

#45113 docs: update role specification for automatic agent updates
  docs/pages/upgrading/automatic-agent-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#45119 [aws_matchers] validate aws regions
  api/types/discoveryconfig/discoveryconfig_test.go
  api/types/matchers_accessgraph.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45073 [v16] Document changes to auto-enroll since v16.1.1
  docs/pages/access-controls/device-trust/device-management.mdx
  docs/pages/access-controls/guides/webauthn.mdx
Labels: documentation, backport, size/sm, no-changelog

#45129 [v16] Update pnpm to 9.6.0
  package.json
Labels: backport, size/sm, no-changelog

#45024 fix regression that denied access to launch some Apps
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
Labels: ui, size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#45128 [v16] docs: Don't provide commands to use Homebrew
  docs/pages/access-controls/guides/passwordless.mdx
  docs/pages/includes/install-tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#45122 docs: Fix singing -> signing typos
  docs/pages/reference/join-methods.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45131 [v16] docs: update role specification for automatic agent updates
  docs/pages/upgrading/automatic-agent-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#45134 [v14] docs: update role specification for automatic agent updates
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#45117 [v16] docs: include Panther link in export audit logs intro
  docs/pages/management/export-audit-events.mdx
Labels: documentation, backport, size/sm, no-changelog

#45118 [v15] docs: include Panther link in export audit logs intro
  docs/pages/management/export-audit-events.mdx
Labels: documentation, backport, size/sm, no-changelog

#45132 [v15] docs: update role specification for automatic agent updates
  docs/pages/upgrading/automatic-agent-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#45089 Fixed typo in Google Cloud KMS documentation.
  docs/pages/admin-guides/deploy-a-cluster/gcp-kms.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45149 [v16] fix regression that denied access to launch some Apps
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
Labels: ui, backport, size/md

#45133 [v15] Make bot resources honour their expiry
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
Labels: backport, size/md

#45130 [v16] Make bot resources honour their expiry
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
Labels: backport, size/md

#45150 [v15] fix regression that denied access to launch some Apps
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
Labels: ui, backport, size/md

#45142 [v16] docs: Fix singing -> signing typos
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/sm, no-changelog

#45140 [v14] docs: Fix singing -> signing typos
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/sm, no-changelog

#45141 [v15] docs: Fix singing -> signing typos
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/sm, no-changelog

#45153 [v16] spelling fixes for examples
  examples/athena/variables.tf
  examples/chart/teleport-cluster/charts/teleport-operator/templates/crds.yaml
  examples/chart/teleport-cluster/values.yaml
Labels: helm, backport, size/sm, no-changelog

#44891 Added 07/31 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#45154 [v15] spelling fixes for examples
  examples/athena/variables.tf
  examples/chart/teleport-cluster/charts/teleport-operator/templates/crds.yaml
  examples/chart/teleport-cluster/values.yaml
Labels: helm, backport, size/sm, no-changelog

#45058 Eliminate `services.Services` interface and `XXXClient()` methods on `auth.Services`
  lib/auth/access.go
  lib/auth/accesspoint/accesspoint.go
  lib/auth/auth.go
  lib/auth/helpers.go
  lib/service/service.go
  lib/services/services.go
  lib/srv/discovery/discovery_test.go
  lib/srv/discovery/kube_integration_watcher_test.go
Labels: size/sm, discovery, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#45079 [v16] Add Device Trust Requirement icon to web UI
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/sessions.go
  lib/web/apiserver.go
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ShieldWarning.tsx
  web/packages/design/src/Icon/assets/ShieldWarning.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/DeviceTrust/types.ts
  web/packages/teleport/src/Login/useLogin.ts
  web/packages/teleport/src/TopBar/DeviceTrustIcon.tsx
  web/packages/teleport/src/TopBar/DeviceTrustStatus.tsx
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/components/Authenticated/Authenticated.tsx
  web/packages/teleport/src/components/UserMenuNav/UserMenuNav.test.tsx
  web/packages/teleport/src/components/UserMenuNav/UserMenuNav.tsx
  web/packages/teleport/src/services/websession/websession.ts
Labels: ui, backport, size/md

#45151 [v14] fix regression that denied access to launch some Apps
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
Labels: ui, backport, size/md, no-changelog

#44991 Host user creation - Only update groups if needed
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
Labels: size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#45093 [v15] integrations: build with -trimpath option
  integrations/access/common.mk
  integrations/event-handler/Makefile
  integrations/operator/Makefile
  integrations/terraform/Makefile
Labels: backport, size/sm, no-changelog

#45169 [v16] Add missing `entitlements` directory to container image builds
  integrations/operator/Dockerfile
  integrations/operator/Dockerfile.gha
  integrations/teleport-spacelift-runner/Dockerfile
Labels: backport, size/sm, no-changelog

#45157 [v14] spelling fixes for examples
  examples/athena/variables.tf
  examples/chart/teleport-cluster/values.yaml
Labels: helm, backport, size/sm, no-changelog

#45168 [v16] Remove extra hints from `tsh` app proxies.
  tool/tsh/common/app_local_proxy.go
  tool/tsh/common/proxy.go
Labels: tsh, backport, size/sm
