Repository gravitational/teleport, pull requests merged in 2024-04, with the labels that each got.

#39927 Document Jamf page_size parameter
  docs/pages/includes/config-reference/jamf-service.yaml
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40067 Re-enable the `show_desktop_wallpaper` flag
  Cargo.lock
  Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
Labels: rdp, desktop-access, size/sm, backport/branch/v15

#39469 Hardware Key Support for App Access
  rfd/0080-hardware-key-support.md
Labels: rfd, size/sm, no-changelog

#40035 Introduce plugins cleanup command line function.
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/proto/teleport/plugins/v1/plugin_service.proto
  api/types/plugin.go
  tool/tctl/common/cmds.go
  tool/tctl/common/plugins_command.go
Labels: tctl, size/sm, no-changelog, backport/branch/v15

#38399 Document server access enhanced recording option `root_path`
  docs/cspell.json
  docs/pages/includes/config-reference/ssh-service.yaml
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40060 [v15] Replace UnixShellQuote with shsprintf.EscapeDefaultContext from github.com/google/safetext
  go.mod
  go.sum
  lib/utils/cli.go
  lib/utils/cli_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/integrations_samlidp.go
  lib/web/join_tokens.go
Labels: backport, size/sm, no-changelog

#40094 [v14] Document server access enhanced recording option `root_path`
  docs/cspell.json
  docs/pages/includes/config-reference/ssh-service.yaml
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#40093 [v13] Document server access enhanced recording option `root_path`
  docs/cspell.json
  docs/pages/includes/config-reference/ssh-service.yaml
  docs/pages/server-access/guides/bpf-session-recording.mdx
Labels: documentation, backport, size/sm, no-changelog

#39844 add filter to ListUsers
  api/client/client.go
  api/gen/proto/go/teleport/users/v1/users_service.pb.go
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/users/v1/users_service.proto
  api/types/types.pb.go
  api/types/user.go
  lib/auth/tls_test.go
  lib/services/local/users.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15

#40018 Clarify environment vars in the teleport unit file
  docs/pages/reference/networking.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#39938 Remove gh-trigger-workflow
  build.assets/tooling/cmd/gh-trigger-workflow/args.go
  build.assets/tooling/cmd/gh-trigger-workflow/main.go
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
Labels: size/sm, no-changelog

#39716 build: Add cloud-only tag-build/publish option
  Makefile
Labels: size/sm, no-changelog, backport/branch/v15

#40017 Clean up TypeScript types related to tsh daemon
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/rootClusterProxyHostAllowList.ts
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/services/tshd/createClient.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/index.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.test.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/connectMyComputer/connectMyComputerService.ts
  web/packages/teleterm/src/ui/services/fileTransferClient/fileTransferService.ts
  web/packages/teleterm/src/ui/services/headlessAuthn/headlessAuthnService.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.test.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/services/usage/usageService.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v15

#39898 [v13] Use :not(:disabled) instead of :enabled for ButtonIcon
  web/packages/design/src/ButtonIcon/ButtonIcon.jsx
  web/packages/design/src/buttons.story.jsx
  web/packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Console/Tabs/__snapshots__/Tabs.story.test.tsx.snap
  web/packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#39896 [v15] Use :not(:disabled) instead of :enabled for ButtonIcon
  web/packages/design/src/ButtonIcon/ButtonIcon.jsx
  web/packages/design/src/buttons.story.tsx
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Console/Tabs/__snapshots__/Tabs.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#38671 Migrate RemoteClusters CRUD to gRPC
  api/client/client.go
  lib/auth/apiserver.go
  lib/auth/auth_with_roles.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/http_client.go
  lib/auth/httpfallback.go
  lib/auth/presence/presencev1/service.go
  lib/auth/presence/presencev1/service_test.go
  lib/services/presence.go
Labels: size/lg, no-changelog

#40105 [v14] Use dbcmd.WithPrintFormat only for preview of teleterm gateway command
  gen/proto/go/teleport/lib/teleterm/v1/gateway.pb.go
  integration/proxy/teleterm_test.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/teleterm/cmd/cmds/cmds.go
  lib/teleterm/cmd/db.go
  lib/teleterm/cmd/db_test.go
  lib/teleterm/cmd/kube.go
  lib/teleterm/cmd/kube_test.go
  lib/teleterm/gateway/base.go
  lib/teleterm/gateway/base_test.go
  proto/teleport/lib/teleterm/v1/gateway.proto
Labels: backport, size/md

#40106 [v13] Use dbcmd.WithPrintFormat only for preview of teleterm gateway command
  gen/proto/go/teleport/lib/teleterm/v1/gateway.pb.go
  lib/client/db/dbcmd/dbcmd.go
  lib/client/db/dbcmd/dbcmd_test.go
  lib/teleterm/clusters/dbcmd_cli_command_provider.go
  lib/teleterm/clusters/dbcmd_cli_command_provider_test.go
  lib/teleterm/cmd/cmds/cmds.go
  lib/teleterm/gateway/gateway.go
  lib/teleterm/gateway/gateway_test.go
  proto/teleport/lib/teleterm/v1/gateway.proto
Labels: backport, size/sm

#40089 docs: remove unnecessary dsacls command for AD service account
  docs/pages/desktop-access/active-directory-manual.mdx
  lib/web/scripts/desktop/configure-ad.ps1
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#40096 chore: Bump golangci-lint to v1.57.2
  build.assets/versions.mk
  lib/srv/desktop/rdp/rdpclient/client_nop.go
Labels: rdp, desktop-access, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40110 Update GitHub update event audit log display
  lib/auth/github.go
  lib/auth/oidc.go
  lib/auth/saml.go
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: audit-log, size/sm, backport/branch/v15

#40053 docs: correctly describe the behavior of host user creation
  docs/pages/server-access/guides/host-user-creation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#39143 Add access monitoring rules services and backend
  api/client/accessmonitoringrules/access_monitoring_rules_client.go
  api/client/client.go
  lib/accessmonitoringrules/accessmonitoringrulesv1/service.go
  lib/accessmonitoringrules/accessmonitoringrulesv1/service_test.go
  lib/auth/auth.go
  lib/auth/clt.go
  lib/auth/init.go
  lib/services/access_monitoring_rules.go
  lib/services/local/access_monitoring_rules.go
  lib/services/local/access_monitoring_rules_test.go
  lib/services/services.go
Labels: size/lg, no-changelog, backport/branch/v15

#40111 [v15] Clarify environment vars in the teleport unit file
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#40099 Remove lingering Drone references
  .github/ISSUE_TEMPLATE/testplan.md
  build.assets/Makefile
  darwin-signing.mk
  docs/cspell.json
  rfd/0089-merge-webapps.md
  rfd/cspell.json
  web/.drone.yml
Labels: documentation, ui, rfd, size/sm, no-changelog

#40118 [v15] docs: correctly describe the behavior of host user creation
  docs/pages/server-access/guides/host-user-creation.mdx
Labels: documentation, backport, size/sm, no-changelog

#40045 Include system annotations in audit event entries for access requests
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#40116 [v15] Update GitHub update event audit log display
  lib/auth/github.go
  lib/auth/oidc.go
  lib/auth/saml.go
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#38951 Workload Identity Docs
  docs/config.json
  docs/cspell.json
  docs/pages/includes/role-spec.mdx
  docs/pages/machine-id/access-guides.mdx
  docs/pages/machine-id/introduction.mdx
  docs/pages/machine-id/workload-identity.mdx
  docs/pages/machine-id/workload-identity/best-practices.mdx
  docs/pages/machine-id/workload-identity/getting-started.mdx
  docs/pages/machine-id/workload-identity/tsh.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15

#40090 [v15] Introduce plugins cleanup command line function.
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/proto/teleport/plugins/v1/plugin_service.proto
  api/types/plugin.go
  tool/tctl/common/cmds.go
  tool/tctl/common/plugins_command.go
Labels: tctl, backport, size/md, no-changelog

#40097 Add device trust "token move check" protos
  api/gen/proto/go/teleport/devicetrust/v1/device_confirmation_token.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service_grpc.pb.go
  api/proto/teleport/devicetrust/v1/device_confirmation_token.proto
  api/proto/teleport/devicetrust/v1/devicetrust_service.proto
  gen/proto/go/teleport/lib/teleterm/v1/service.pb.go
  gen/proto/ts/teleport/devicetrust/v1/device_confirmation_token_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.client.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.grpc-server.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.ts
  proto/teleport/lib/teleterm/v1/service.proto
Labels: size/sm, no-changelog

#40123 [v15] Include system annotations in audit event entries for access requests
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: backport, size/sm

#40065 update AWS RDS db e2e tests
  .github/workflows/aws-e2e-tests-non-root.yaml
  e2e/aws/eks_test.go
  e2e/aws/fixtures_test.go
  e2e/aws/main_test.go
  e2e/aws/rds_test.go
  go.mod
  go.sum
Labels: database-access, size/md, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40128 [v14] chore: Bump golangci-lint to v1.57.2
  build.assets/versions.mk
  lib/srv/desktop/rdp/rdpclient/client_nop.go
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#40127 [v15] chore: Bump golangci-lint to v1.57.2
  build.assets/versions.mk
  lib/srv/desktop/rdp/rdpclient/client_nop.go
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#39497 Wrap diag service listener with multiplexer so it can work behind PROXY enabled loadbalancer/proxy.
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/service/service.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#39742 Refactor `NewWebSessionRequest` into lib/auth - follow up
  api/types/session.go
  lib/auth/auth.go
  lib/auth/sessions.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40131 [v15] update AWS RDS db e2e tests
  .github/workflows/aws-e2e-tests-non-root.yaml
  e2e/aws/eks_test.go
  e2e/aws/fixtures_test.go
  e2e/aws/main_test.go
  e2e/aws/rds_test.go
  go.mod
  go.sum
Labels: backport, size/md, no-changelog

#39962 [v15] docs: update usage & billing to mention ephemeral SSO users
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#40124 [v15] Workload Identity Docs
  docs/config.json
  docs/cspell.json
  docs/pages/includes/role-spec.mdx
  docs/pages/machine-id/access-guides.mdx
  docs/pages/machine-id/introduction.mdx
  docs/pages/machine-id/workload-identity.mdx
  docs/pages/machine-id/workload-identity/best-practices.mdx
  docs/pages/machine-id/workload-identity/getting-started.mdx
  docs/pages/machine-id/workload-identity/tsh.mdx
Labels: documentation, backport, size/md, no-changelog

#40139 [v14] Wrap diag service listener with multiplexer so it can work behind PROXY enabled loadbalancer/proxy.
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/service/service.go
Labels: backport, size/sm

#40138 [v15] Wrap diag service listener with multiplexer so it can work behind PROXY enabled loadbalancer/proxy.
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/service/service.go
Labels: backport, size/sm

#40132 [v14] update AWS RDS db e2e tests
  .github/workflows/aws-e2e-tests-non-root.yaml
  e2e/aws/eks_test.go
  e2e/aws/fixtures_test.go
  e2e/aws/main_test.go
  e2e/aws/rds_test.go
  go.mod
  go.sum
Labels: backport, size/md, no-changelog

#40083 Add a way to configure the `RunWhileLocked.RunWhileLockedRetryInteral` for tests
  lib/auth/api.go
  lib/services/local/access_list.go
  lib/services/local/generic/generic.go
  lib/services/local/options.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40088 [v15] Re-enable the `show_desktop_wallpaper` flag
  Cargo.lock
  Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
Labels: rdp, backport, desktop-access, size/sm

#40130 [v15] docs: remove unnecessary dsacls command for AD service account
  docs/pages/desktop-access/active-directory-manual.mdx
  lib/web/scripts/desktop/configure-ad.ps1
Labels: documentation, backport, size/sm, no-changelog

#40029 [v14] Return eligible status with UpsertAccessListWithMembers
  api/client/accesslist/accesslist.go
Labels: backport, size/sm, no-changelog

#40140 [v13] Wrap diag service listener with multiplexer so it can work behind PROXY enabled loadbalancer/proxy.
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/service/service.go
Labels: backport, size/sm

#40137 [v13] Refactor `NewWebSessionRequest` into lib/auth - follow up
  api/types/session.go
  lib/auth/auth.go
  lib/auth/sessions.go
Labels: backport, size/sm, no-changelog

#40104 [v15] Remove custom tshd types and `createTshdClient` boilerplate
  web/packages/teleterm/src/mainProcess/rootClusterProxyHostAllowList.ts
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/services/tshd/cloneableClient.test.ts
  web/packages/teleterm/src/services/tshd/cloneableClient.ts
  web/packages/teleterm/src/services/tshd/createClient.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.story.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/access.ts
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
  web/packages/teleterm/src/ui/DocumentCluster/DocumentCluster.test.tsx
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
  web/packages/teleterm/src/ui/DocumentCluster/useUserPreferences.test.tsx
  web/packages/teleterm/src/ui/DocumentCluster/useUserPreferences.ts
  web/packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.test.tsx
  web/packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
  web/packages/teleterm/src/ui/DocumentGatewayApp/DocumentGatewayApp.story.tsx
  web/packages/teleterm/src/ui/DocumentGatewayKube/DocumentGatewayKube.tsx
  web/packages/teleterm/src/ui/services/clusters/clustersService.test.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/clusters/types.ts
  web/packages/teleterm/src/ui/services/connectMyComputer/connectMyComputerService.ts
  web/packages/teleterm/src/ui/services/fileTransferClient/fileTransferService.ts
  web/packages/teleterm/src/ui/services/headlessAuthn/headlessAuthnService.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.test.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/uri.ts
Labels: ui, backport, size/sm, no-changelog

#39880 Machine ID: Database Tunnel service
  lib/tbot/config/config.go
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/config/service_database_tunnel_test.go
  lib/tbot/config/testdata/TestDatabaseTunnelService_YAML/full.golden
  lib/tbot/database_access.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  lib/tbot/testhelpers/srv.go
Labels: machine-id, size/lg, backport/branch/v14, backport/branch/v15

#40143 [v14] replace missing api deps
  api/client/client.go
Labels: backport, size/sm, no-changelog

#39912 AWS OIDC set up: S3 is optional
  integration/integrations/integration_test.go
  lib/web/integrations.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/ui/integration.go
Labels: aws, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40151 [v15] Machine ID: Database Tunnel service
  lib/tbot/config/config.go
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/config/service_database_tunnel_test.go
  lib/tbot/config/testdata/TestDatabaseTunnelService_YAML/full.golden
  lib/tbot/database_access.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  lib/tbot/testhelpers/srv.go
Labels: backport, machine-id, size/lg

#40163 [v14] Add support for generating a kubeconfig that does not depend on tbot binary
  lib/tbot/config/bot_test.go
  lib/tbot/config/output_kubernetes.go
  lib/tbot/config/template_kubernetes.go
  lib/tbot/config/template_kubernetes_test.go
  lib/tbot/config/testdata/TestKubernetesOutput_YAML/full.golden
  lib/tbot/config/testdata/TestKubernetesOutput_YAML/minimal.golden
  lib/tbot/config/testdata/TestTemplateKubernetesRender/exec_plugin_disabled/kubeconfig.yaml.golden
Labels: backport, machine-id, size/md

#40162 [v15] Add support for generating a kubeconfig that does not depend on tbot binary
  lib/tbot/config/bot_test.go
  lib/tbot/config/output_kubernetes.go
  lib/tbot/config/template_kubernetes.go
  lib/tbot/config/template_kubernetes_test.go
  lib/tbot/config/testdata/TestKubernetesOutput_YAML/full.golden
  lib/tbot/config/testdata/TestKubernetesOutput_YAML/minimal.golden
  lib/tbot/config/testdata/TestTemplateKubernetesRender/exec_plugin_disabled/kubeconfig.yaml.golden
Labels: backport, machine-id, size/md

#39778 [v14] [15.1.9] bump docs for upgrade
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#40051 [v13] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#40150 Set CommonName to first DNS SAN when issuing X509 SVIDs
  docs/cspell.json
  docs/pages/machine-id/workload-identity/best-practices.mdx
  lib/auth/machineid/machineidv1/workload_identity_service.go
  lib/auth/machineid/machineidv1/workload_identity_service_test.go
Labels: documentation, size/sm, backport/branch/v15

#40158 [v14] AWS OIDC set up: S3 is optional
  integration/integrations/integration_test.go
  lib/web/integrations.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/ui/integration.go
Labels: backport, size/sm, no-changelog

#40129 [v13] chore: Bump golangci-lint to v1.57.2
  build.assets/versions.mk
  lib/srv/desktop/rdp/rdpclient/client_nop.go
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#40175 chore: Bump Go to v1.22.2
  build.assets/versions.mk
  go.mod
Labels: size/sm, no-changelog

#40177 [v14] chore: Bump Go to v1.21.9
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#40176 [v15] chore: Bump Go to v1.21.9
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#40178 [v13] chore: Bump Go to v1.21.9
  build.assets/versions.mk
Labels: backport, size/sm

#40120 [v15] add user filtering
  api/client/client.go
  api/gen/proto/go/teleport/users/v1/users_service.pb.go
  api/internalutils/stream/stream.go
  api/internalutils/stream/stream_test.go
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/users/v1/users_service.proto
  api/types/types.pb.go
  api/types/user.go
  lib/auth/api.go
  lib/auth/clt.go
  lib/auth/tls_test.go
  lib/auth/users/usersv1/service.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/services/identity.go
  lib/services/local/resource.go
  lib/services/local/users.go
  lib/services/local/users_test.go
  lib/services/user.go
Labels: backport, size/md, no-changelog

#40173 Add a timeout to certain internal cluster requests
  lib/auth/register.go
  lib/service/connect.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#39109 [docs] Database Access Controls
  docs/config.json
  docs/cspell.json
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/auto-user-provisioning/database-access-controls.mdx
  docs/pages/database-access/auto-user-provisioning/postgres.mdx
  docs/pages/includes/database-access/auto-user-provisioning/database-object-import-rule-spec.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15

#39764 Change the `tctl` format for `database_object_import_rule` resource
  lib/services/databaseobjectimportrule.go
  lib/services/databaseobjectimportrule_test.go
  lib/services/local/databaseobjectimportrule.go
  lib/services/local/databaseobjectimportrule_test.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/databaseobjectimportrule/resource.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, size/sm, backport/branch/v15

#40179 Reduce flakiness of `TestBotDatabaseTunnel`
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/tbot_test.go
Labels: machine-id, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40200 [v14] Add a timeout to certain internal cluster requests
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm, no-changelog

#40199 [v15] Add a timeout to certain internal cluster requests
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm, no-changelog

#40201 [v13] Add a timeout to certain internal cluster requests
  lib/auth/register.go
  lib/service/connect.go
Labels: backport, size/sm, no-changelog

#40206 [v14] Reduce flakiness of `TestBotDatabaseTunnel` (#40179)
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/tbot_test.go
Labels: backport, machine-id, size/sm, no-changelog

#40204 [v15] Reduce flakiness of `TestBotDatabaseTunnel`
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/tbot_test.go
Labels: backport, machine-id, size/sm, no-changelog

#40202 [v15] Implement persistence for `database_object` resource (#39756)
  api/client/client.go
  api/gen/proto/go/teleport/dbobject/v1/dbobject_service.pb.go
  api/gen/proto/go/teleport/dbobject/v1/dbobject_service_grpc.pb.go
  api/proto/teleport/dbobject/v1/dbobject_service.proto
  lib/auth/auth.go
  lib/auth/clt.go
  lib/auth/dbobject/dbobjectv1/service.go
  lib/auth/dbobject/dbobjectv1/service_test.go
  lib/auth/grpcserver.go
  lib/auth/init.go
  lib/authz/permissions.go
  lib/services/databaseobject.go
  lib/services/local/databaseobject.go
  lib/services/local/databaseobject_test.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/databaseobject/resource.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/lg, no-changelog

#40198 [v15] [docs] Database Access Controls
  docs/config.json
  docs/cspell.json
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/auto-user-provisioning/database-access-controls.mdx
  docs/pages/database-access/auto-user-provisioning/postgres.mdx
  docs/pages/includes/database-access/auto-user-provisioning/database-object-import-rule-spec.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/md, no-changelog

#40194 Add `node:rw` to RoleDiscovery to allow EICE
  lib/authz/permissions.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#39983 [v14] Keep any TAG related local storage values on logout
  web/packages/teleport/src/services/storageService/storageService.ts
Labels: ui, backport, size/sm, no-changelog

#40214 [v15] Add `node:rw` to RoleDiscovery to allow EICE
  lib/authz/permissions.go
Labels: backport, size/sm, no-changelog

#39984 [v15] Keep any TAG related local storage values on logout
  web/packages/teleport/src/services/storageService/storageService.ts
Labels: ui, backport, size/sm, no-changelog

#40189 Configure the systemd unit file RestartSec value
  examples/systemd/fips/teleport.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#40233 chore: Bump Buf to v1.30.1
  build.assets/versions.mk
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40235 Broken External Links
  docs/pages/application-access/guides/amazon-athena.mdx
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#40238 [v14] Fix flaky test `TestProxySSHJumpHost`
  api/utils/grpc/stream/stream.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/tsh_helper_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, backport, size/sm, no-changelog

#40239 [v13] Fix flaky test `TestProxySSHJumpHost`
  api/utils/grpc/stream/stream.go
  tool/teleport/testenv/test_server.go
  tool/tsh/app_aws_test.go
  tool/tsh/proxy_test.go
  tool/tsh/tsh_helper_test.go
  tool/tsh/tsh_test.go
Labels: tsh, backport, size/sm, no-changelog

#39006 [v14] build: Use buildx and caching for buildboxes, push to ghcr.io
  build.assets/Makefile
  build.assets/images.mk
Labels: backport, size/sm, no-changelog

#40197 Connect: Show all recent connections in connection list
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.test.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
  web/packages/teleterm/src/ui/components/KeyboardArrowsNavigation/useKeyboardArrowsNavigation.ts
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#40229 [v15] Configure the systemd unit file RestartSec value
  examples/systemd/fips/teleport.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
Labels: backport, size/sm

#40231 [v13] Configure the systemd unit file RestartSec value
  examples/systemd/fips/teleport.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
Labels: backport, size/sm

#40136 DiscoveryConfig: Add `status` field to report discovered objects and errors
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service_grpc.pb.go
  api/proto/teleport/discoveryconfig/v1/discoveryconfig.proto
  api/proto/teleport/discoveryconfig/v1/discoveryconfig_service.proto
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40122 [v14] Include system annotations in audit event entries for access requests
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: backport, size/sm

#40234 [v15] fix: Set an upper bound for the DMI cache file
  lib/devicetrust/native/device_linux.go
Labels: backport, size/sm

#40216 [v13] Include system annotations in audit event entries for access requests
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: backport, size/sm

#40250 [v15] Connect: Show all recent connections in connection list
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.test.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
  web/packages/teleterm/src/ui/components/KeyboardArrowsNavigation/useKeyboardArrowsNavigation.ts
Labels: ui, backport, size/md

#40252 [v13] Connect: Show all recent connections in connection list
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.test.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
  web/packages/teleterm/src/ui/components/KeyboardArrowsNavigation/useKeyboardArrowsNavigation.ts
Labels: ui, backport, size/md

#40251 [v14] Connect: Show all recent connections in connection list
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.test.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
  web/packages/teleterm/src/ui/components/KeyboardArrowsNavigation/useKeyboardArrowsNavigation.ts
Labels: ui, backport, size/md

#40258 [v13] chore: Bump Buf to v1.30.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#39883 Login form UI redesign
  web/packages/build/package.json
  web/packages/teleport/src/Account/ManageDevices/AddAuthDeviceWizard/AddAuthDeviceWizard.tsx
  web/packages/teleport/src/Login/Login.test.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.story.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.test.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleport/src/components/FormLogin/SsoButtons.tsx
  web/packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
  web/packages/teleport/src/components/PasskeyIcons/PasskeyIcons.tsx
  web/packages/teleport/src/components/PasskeyIcons/index.ts
  yarn.lock
Labels: ui, size/lg, backport/branch/v15

#40256 [v15] chore: Bump Buf to v1.30.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#40230 [v14] Configure the systemd unit file RestartSec value
  examples/systemd/fips/teleport.service
  examples/systemd/production/auth/teleport.service
  examples/systemd/production/node/teleport.service
  examples/systemd/production/proxy/teleport.service
  examples/systemd/teleport.service
  lib/config/systemd.go
  lib/config/testdata/TestWriteSystemdUnitFile.golden
Labels: backport, size/sm

#40261 [v14] Fix EAS token generation used for AWS APIs
  lib/auth/externalauditstorage.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/integrations/awsoidc/token_generator.go
  lib/integrations/externalauditstorage/configurator.go
  lib/integrations/externalauditstorage/configurator_test.go
Labels: backport, size/sm, no-changelog

#40282 Release 15.2.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#40068 Adds support for `SharedDirectoryTruncateRequest` and `SharedDirectoryTruncateResponse` messages
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/tdp.rs
  lib/srv/desktop/tdp/proto.go
  rfd/0067-desktop-access-file-system-sharing.md
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
  web/packages/teleport/src/lib/tdp/sharedDirectoryManager.ts
Labels: ui, rdp, rfd, desktop-access, size/md, backport/branch/v15

#39003 Add automatic role access requests
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/auth.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/kube.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/md, backport/branch/v15

#40260 [v15] Introduce role friendly name labels and frontend utilities.
  api/types/constants.go
  api/types/resource.go
  api/types/resource_test.go
Labels: backport, size/sm

#40285 [v15] Add automatic role access requests (#39003)
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/auth.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/kube.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, backport, size/md

#40187 docs: bump cloud version to 15.2.0
  docs/config.json
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40146 Refactors rust lint out into its own job which runs on a bare GH runner
  .github/workflows/build-macos.yaml
  .github/workflows/build-windows.yaml
  .github/workflows/lint-bypass.yaml
  .github/workflows/lint.yaml
  .github/workflows/post-release.yaml
  Makefile
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40185 Added 04/03 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#40001 Clean up some TODOs
  lib/auth/apiserver.go
  lib/auth/github.go
  lib/web/apiserver.go
  web/packages/teleport/src/Assist/service.ts
  web/packages/teleport/src/config.ts
Labels: ui, size/sm, no-changelog

#40241 [v13] build: Use buildx and caching for buildboxes, push to ghcr.io
  build.assets/Makefile
  build.assets/images.mk
Labels: backport, size/sm, no-changelog

#40259 [v15] Fix EAS token generation used for AWS APIs
  lib/auth/externalauditstorage.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/integrations/awsoidc/token_generator.go
  lib/integrations/externalauditstorage/configurator.go
  lib/integrations/externalauditstorage/configurator_test.go
Labels: backport, size/sm, no-changelog

#40049 [v15] Access Graph AWS sync docs
  docs/config.json
  docs/pages/access-controls/access-graph/aws-sync.mdx
Labels: documentation, backport, size/md, no-changelog

#40048 [v14] Access Graph AWS sync docs
  docs/config.json
  docs/pages/access-controls/access-graph/aws-sync.mdx
Labels: documentation, backport, size/md, no-changelog

#40247 [v15] DiscoveryConfig: Add `status` field to report discovered objects and errors
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service_grpc.pb.go
  api/proto/teleport/discoveryconfig/v1/discoveryconfig.proto
  api/proto/teleport/discoveryconfig/v1/discoveryconfig_service.proto
Labels: backport, size/sm, no-changelog

#40248 [v14] DiscoveryConfig: Add `status` field to report discovered objects and errors
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service_grpc.pb.go
  api/proto/teleport/discoveryconfig/v1/discoveryconfig.proto
  api/proto/teleport/discoveryconfig/v1/discoveryconfig_service.proto
Labels: backport, size/sm, no-changelog

#40253 Disable session recording/audit to prevent tempdir flakiness in tbot tests
  lib/tbot/testhelpers/srv.go
  tool/tctl/common/resource_command_test.go
Labels: machine-id, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40298 Reset `tlsConfig.ServerName` field before dialing to TAG
  lib/service/discovery.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#40288 [v14] update e_imports.go
  e_imports.go
  go.mod
  go.sum
Labels: backport, size/sm, no-changelog

#40301 [v14] Reset `tlsConfig.ServerName` field before dialing to TAG
  lib/service/discovery.go
Labels: backport, size/sm, no-changelog

#40300 [v15] Reset `tlsConfig.ServerName` field before dialing to TAG
  lib/service/discovery.go
Labels: backport, size/sm, no-changelog

#40084 Update github SSO doc to clarify incorrect guidance about org slug
  docs/pages/access-controls/sso/github-sso.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40085 [v15] Document Jamf page_size parameter
  docs/pages/includes/config-reference/jamf-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#40215 DiscoveryConfig: Implement `UpdateDiscoveryConfigStatus` handler
  api/types/discoveryconfig/convert/v1/discoveryconfig.go
  api/types/discoveryconfig/convert/v1/discoveryconfig_test.go
  api/types/discoveryconfig/discoveryconfig.go
  lib/auth/discoveryconfig/discoveryconfigv1/service.go
  lib/auth/discoveryconfig/discoveryconfigv1/service_test.go
  lib/cache/cache_test.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15

#37857 Refresh the AWS app access guide
  docs/img/application-access/federated-login@2x.png
  docs/img/application-access/iam-role-selector.png
  docs/pages/application-access/cloud-apis/aws-console.mdx
Labels: documentation, size/md, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40255 GoDerive: Generate `Equal` stubs for `DiscoveryConfig` object.
  Makefile
  api/types/discoveryconfig/derived.gen.go
  api/types/discoveryconfig/discoveryconfig.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15

#40155 Add missing discovery fields "Integration" and "KubeAppDiscovery" to the file config
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/fetchers/eks.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/srv/discovery/kube_integration_watcher_test.go
  lib/srv/discovery/kube_watcher.go
Labels: size/md, discovery, backport/branch/v15

#40303 [v14] Disable session recording/audit to prevent tempdir flakiness in tbot tests
  lib/tbot/testhelpers/srv.go
Labels: backport, machine-id, size/sm, no-changelog

#40299 Modify docs to include reference to `tbot` FIPS compliant image
  docs/pages/installation.mdx
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#40254 Lower bcrypt cost when testing
  lib/accessmonitoringrules/accessmonitoringrulesv1/service_test.go
  lib/auth/assist/assistv1/test/service_test.go
  lib/auth/auth_test.go
  lib/auth/discoveryconfig/discoveryconfigv1/service_test.go
  lib/auth/helpers.go
  lib/auth/integration/integrationv1/service_test.go
  lib/auth/kubewaitingcontainer/service_test.go
  lib/auth/okta/service_test.go
  lib/auth/userloginstate/service_test.go
  lib/auth/userpreferences/userpreferencesv1/service_test.go
  lib/auth/users/usersv1/service_test.go
  lib/authz/permissions_test.go
  lib/cache/cache_test.go
  lib/services/local/resource_test.go
  lib/services/local/services_test.go
  lib/services/local/session_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40240 docs: warn about unprivileged access to KMS credentials
  docs/cspell.json
  docs/pages/choose-an-edition/teleport-enterprise/aws-kms.mdx
  docs/pages/choose-an-edition/teleport-enterprise/gcp-kms.mdx
  docs/pages/includes/aws-credentials.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#39030 Remove auto-discovery from specific DB guides
  docs/pages/auto-discovery/databases.mdx
  docs/pages/database-access/guides/aws-dynamodb.mdx
  docs/pages/database-access/guides/aws-opensearch.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/rds-proxy-mysql.mdx
  docs/pages/database-access/guides/rds-proxy-postgres.mdx
  docs/pages/database-access/guides/rds-proxy-sqlserver.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-aws.mdx
  docs/pages/database-access/guides/redshift-serverless.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/aws-bootstrap.mdx
  docs/pages/includes/database-access/aws-create-db-configuration.mdx
  docs/pages/includes/database-access/discovery-guide-brief.mdx
  docs/pages/includes/database-access/guides-next-steps.mdx
  docs/pages/includes/database-access/rds-proxy.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15

#40314 [v15] docs: bump cloud version to 15.2.0
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#40325 Pin now time during the access request creation
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/sm, backport/branch/v14, backport/branch/v15

#40313 [v13] docs: bump cloud version to 15.2.0
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#40319 [v14] docs: bump cloud version to 15.2.0
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#40327 [v15] docs: warn about unprivileged access to KMS credentials
  docs/cspell.json
  docs/pages/choose-an-edition/teleport-enterprise/aws-kms.mdx
  docs/pages/choose-an-edition/teleport-enterprise/gcp-kms.mdx
  docs/pages/includes/aws-credentials.mdx
Labels: documentation, backport, size/sm, no-changelog

#40330 [v14] allow agents to dial to `GetClusterAccessGraphConfig`
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/clusterconfig/clusterconfigv1/service_test.go
  lib/auth/grpcserver_test.go
  lib/auth/tls_test.go
Labels: backport, size/sm, no-changelog

#40333 [v15] fix access request test cache sync
  lib/auth/access_request_test.go
Labels: backport, size/sm, no-changelog

#40334 [v14] fix access request test cache sync
  lib/auth/access_request_test.go
Labels: backport, size/sm, no-changelog

#40331 [v15] Remove auto-discovery from specific DB guides
  docs/pages/auto-discovery/databases.mdx
  docs/pages/database-access/guides/aws-dynamodb.mdx
  docs/pages/database-access/guides/aws-opensearch.mdx
  docs/pages/database-access/guides/dynamic-registration.mdx
  docs/pages/database-access/guides/postgres-redshift.mdx
  docs/pages/database-access/guides/rds-proxy-mysql.mdx
  docs/pages/database-access/guides/rds-proxy-postgres.mdx
  docs/pages/database-access/guides/rds-proxy-sqlserver.mdx
  docs/pages/database-access/guides/rds.mdx
  docs/pages/database-access/guides/redis-aws.mdx
  docs/pages/database-access/guides/redshift-serverless.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/aws-bootstrap.mdx
  docs/pages/includes/database-access/aws-create-db-configuration.mdx
  docs/pages/includes/database-access/discovery-guide-brief.mdx
  docs/pages/includes/database-access/guides-next-steps.mdx
  docs/pages/includes/database-access/rds-proxy.mdx
Labels: documentation, backport, size/md, no-changelog

#40066 add RDS MariaDB e2e tests
  .github/workflows/aws-e2e-tests-non-root.yaml
  e2e/aws/main_test.go
  e2e/aws/rds_test.go
  lib/srv/db/mysql/sql/mariadb_delete_user.sql
  lib/srv/db/mysql/sql/mysql_delete_user.sql
  lib/srv/db/postgres/sql/delete-user.sql
  lib/srv/db/postgres/sql/redshift-delete-user.sql
Labels: database-access, size/md, backport/branch/v14, no-changelog, backport/branch/v15

#40335 [v15] Pin now time during the access request creation
  lib/services/access_request.go
  lib/services/access_request_test.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, backport, size/sm

#39916 add genmap helper
  lib/utils/genmap/genmap.go
  lib/utils/genmap/genmap_test.go
Labels: size/md, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#40165 Switch `ListRoles` to the paginated API
  lib/web/apiserver.go
  lib/web/resources.go
  lib/web/resources_test.go
  web/packages/design/src/DataTable/Pager/ServerSidePager.tsx
  web/packages/design/src/DataTable/Table.tsx
  web/packages/design/src/DataTable/types.ts
  web/packages/shared/components/Search/SearchPanel.tsx
  web/packages/teleport/src/Bots/EditBot.test.tsx
  web/packages/teleport/src/Bots/EditBot.tsx
  web/packages/teleport/src/Bots/List/BotList.test.tsx
  web/packages/teleport/src/Bots/List/BotList.tsx
  web/packages/teleport/src/Bots/List/Bots.story.tsx
  web/packages/teleport/src/Bots/List/Bots.test.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Bots/types.ts
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/Roles.tsx
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/ServerSideSupportedList.tsx
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/SimpleList/SimpleList.tsx
  web/packages/teleport/src/LocksV2/NewLock/common.tsx
  web/packages/teleport/src/Nodes/Nodes.story.tsx
  web/packages/teleport/src/Roles/RoleList/RoleList.tsx
  web/packages/teleport/src/Roles/RoleList/index.ts
  web/packages/teleport/src/Roles/Roles.story.tsx
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Roles/useRoles.ts
  web/packages/teleport/src/Users/UserAddEdit/UserAddEdit.story.tsx
  web/packages/teleport/src/Users/UserAddEdit/UserAddEdit.tsx
  web/packages/teleport/src/Users/UserAddEdit/useDialog.tsx
  web/packages/teleport/src/Users/Users.story.tsx
  web/packages/teleport/src/Users/Users.test.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/components/hooks/useServersidePagination.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/agents/types.ts
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/md, backport/branch/v14, backport/branch/v15

#40326 [v15] Modify docs to include reference to `tbot` FIPS compliant image
  docs/pages/installation.mdx
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, backport, size/sm, no-changelog

#40317 [v15] Add conditional update methods for `AccessList` and `AccessListMembers`
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.client.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.grpc-server.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  lib/auth/api.go
  lib/cache/cache.go
  lib/cache/collections.go
  lib/services/access_list.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/generic/generic.go
  lib/services/simple/access_list.go
Labels: backport, size/md, no-changelog

#40249 Make VNet connection item behave like other items
  web/packages/design/src/StepSlider/StepSlider.tsx
  web/packages/shared/libs/mergeRefs.test.tsx
  web/packages/shared/libs/mergeRefs.ts
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.test.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionsFilterableList.tsx
  web/packages/teleterm/src/ui/Vnet/VnetConnectionItem.test.tsx
  web/packages/teleterm/src/ui/Vnet/VnetConnectionItem.tsx
  web/packages/teleterm/src/ui/Vnet/VnetSliderStep.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
Labels: ui, size/md, no-changelog

#40265 Do not stringify log messages in the browser console
  web/packages/teleterm/src/services/logger/loggerService.ts
  web/packages/teleterm/src/services/tshd/interceptors.test.ts
  web/packages/teleterm/src/services/tshd/interceptors.ts
Labels: ui, teleport-connect, size/sm, no-changelog, developer-experience, backport/branch/v15
