Repository gravitational/teleport, pull requests merged in 2024-06, with the labels that each got.

#42247 dynamoevents: Fix panic if cursor is outside of [fromUTC,toUTC] range
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15, backport/branch/v16

#42240 fix app keepalive
  lib/inventory/controller.go
  lib/inventory/controller_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15, backport/branch/v16

#42251 [v16] Add --node-name to the teleport configure command
  tool/teleport/common/teleport.go
Labels: backport, size/sm

#42250 [v15] Add --node-name to the teleport configure command
  tool/teleport/common/teleport.go
Labels: backport, size/sm

#42249 [v14] Add --node-name to the teleport configure command
  tool/teleport/common/teleport.go
Labels: backport, size/sm

#41804 [docs] add Google Cloud Spanner integration docs
  docs/config.json
  docs/cspell.json
  docs/img/database-access/guides/spanner/create-spanner-user@2x.png
  docs/img/database-access/guides/spanner/grant-service-account-access-to-instance@2x.png
  docs/img/database-access/guides/spanner/grant-token-creator@2x.png
  docs/img/database-access/guides/spanner/select-instance@2x.png
  docs/img/database-access/guides/spanner/service-account-permissions-tab@2x.png
  docs/img/database-access/guides/spanner_cloud.png
  docs/img/database-access/guides/spanner_selfhosted.png
  docs/img/database-access/spanner-gui/datagrip-choose-no-auth@2x.png
  docs/img/database-access/spanner-gui/datagrip-data-source-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-connection-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-copy-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-create-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-open-driver-manager@2x.png
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/database-access/enroll-google-cloud-databases.mdx
  docs/pages/database-access/enroll-google-cloud-databases/mysql-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/postgres-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/spanner.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/cloudsql_service_credentials.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/gui-clients/spanner-local-proxy.mdx
  docs/pages/includes/database-access/gui-clients/spanner-reuse-port-note.mdx
Labels: documentation, gcp, size/md, backport/branch/v15, backport/branch/v16

#42265 [v13] dynamoevents: Fix panic if cursor is outside of [fromUTC,toUTC] range
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, backport, size/sm

#42266 [v14] dynamoevents: Fix panic if cursor is outside of [fromUTC,toUTC] range
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, backport, size/sm

#42267 [v15] dynamoevents: Fix panic if cursor is outside of [fromUTC,toUTC] range
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, backport, size/sm

#42220 [v16] Improve handling of various lifecycle erorrs in VNet
  lib/vnet/setup.go
  lib/vnet/setup_darwin.go
  lib/vnet/setup_other.go
  lib/vnet/setup_test.go
  lib/vnet/vnet.go
  lib/vnet/vnet_test.go
  tool/tsh/common/vnet_common.go
  tool/tsh/common/vnet_darwin.go
Labels: tsh, backport, size/md, no-changelog

#42264 [v16] dynamoevents: Fix panic if cursor is outside of [fromUTC,toUTC] range
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, backport, size/sm

#42058 Add docs for web_idle_timeout
  docs/pages/connect-your-client/web-ui.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42223 [v16] Add plugin resource handling in tctl
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/proto/teleport/plugins/v1/plugin_service.proto
  lib/services/local/plugins.go
  lib/services/plugins.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/resource_command_test.go
Labels: tctl, backport, size/md

#41715 Show real proxy hostnames in VNet UI
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/Vnet/VnetSliderStep.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#41889 Handle expired certs in VNet in Connect
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/vnet/service.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/helpers.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/services/modals/modalsService.ts
  web/packages/teleterm/src/ui/services/relogin/reloginService.ts
  web/packages/teleterm/src/ui/services/tshdNotifications/tshdNotificationService.ts
  web/packages/teleterm/src/ui/tshdEvents.ts
Labels: ui, size/md, no-changelog, backport/branch/v16

#42155 [buddy] changes in teleport-event-handler.toml docs
  docs/pages/includes/start-event-handler.mdx
Labels: documentation, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#42269 [v14] fix app keepalive
  lib/inventory/controller.go
  lib/inventory/controller_test.go
Labels: backport, size/sm

#41952 Document Jamf API credentials support
  docs/config.json
  docs/cspell.json
  docs/pages/access-controls/device-trust/jamf-integration.mdx
  docs/pages/includes/config-reference/jamf-service.yaml
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#42151 Reduce log level on TOTP failures
  lib/auth/password.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42295 Change the keyboard shortcut for opening new terminal tab on macOS
  CHANGELOG.md
  docs/pages/connect-your-client/teleport-connect.mdx
  web/packages/teleterm/src/services/config/appConfigSchema.ts
Labels: documentation, ui, size/sm, no-changelog, backport/branch/v16

#42284 [v16] audit: populate `server_version` in `ServerMetadata`
  lib/bpf/bpf.go
  lib/events/eventstest/generate.go
  lib/srv/app/common/audit.go
  lib/srv/ctx.go
  lib/srv/db/common/audit.go
  lib/srv/forward/sshserver.go
  lib/srv/monitor.go
  lib/srv/regular/sshserver.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/web/apps.go
Labels: bpf, audit-log, application-access, database-access, backport, size/sm, no-changelog

#42290 [v13] Add docs for web_idle_timeout
  docs/pages/connect-your-client/web-ui.mdx
Labels: documentation, backport, size/sm, no-changelog

#42283 [v15] audit: populate `server_version` in `ServerMetadata`
  lib/bpf/bpf.go
  lib/events/eventstest/generate.go
  lib/srv/app/common/audit.go
  lib/srv/ctx.go
  lib/srv/db/common/audit.go
  lib/srv/forward/sshserver.go
  lib/srv/monitor.go
  lib/srv/regular/sshserver.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/web/apps.go
Labels: bpf, audit-log, application-access, database-access, backport, size/sm, no-changelog

#42292 [v16] Show real proxy hostnames in VNet UI
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/Vnet/VnetSliderStep.tsx
Labels: ui, backport, size/sm, no-changelog

#42293 [v16] Handle expired certs in VNet in Connect
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/vnet/service.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/helpers.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/services/modals/modalsService.ts
  web/packages/teleterm/src/ui/services/relogin/reloginService.ts
  web/packages/teleterm/src/ui/services/tshdNotifications/tshdNotificationService.ts
  web/packages/teleterm/src/ui/tshdEvents.ts
Labels: ui, backport, size/md, no-changelog

#42309 [v13] Reduce log level on TOTP failures
  lib/auth/password.go
Labels: backport, size/sm, no-changelog

#42306 [v16] Reduce log level on TOTP failures
  lib/auth/password.go
Labels: backport, size/sm, no-changelog

#42282 [v14] audit: populate `server_version` in `ServerMetadata`
  lib/bpf/bpf.go
  lib/events/eventstest/generate.go
  lib/srv/app/common/audit.go
  lib/srv/ctx.go
  lib/srv/db/common/audit.go
  lib/srv/forward/sshserver.go
  lib/srv/monitor.go
  lib/srv/regular/sshserver.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/web/apps.go
Labels: bpf, audit-log, application-access, database-access, backport, size/sm, no-changelog

#42307 [v15] Reduce log level on TOTP failures
  lib/auth/password.go
Labels: backport, size/sm, no-changelog

#42310 [v16] Change the keyboard shortcut for opening new terminal tab on macOS
  CHANGELOG.md
  docs/pages/connect-your-client/teleport-connect.mdx
  web/packages/teleterm/src/services/config/appConfigSchema.ts
Labels: documentation, ui, backport, size/sm, no-changelog

#42304 Remove feature flag for VNet, unhide `tsh vnet`
  tool/tsh/common/vnet_darwin.go
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.tsx
Labels: ui, tsh, size/sm, no-changelog, backport/branch/v16

#42271 [v16] fix app keepalive
  lib/inventory/controller.go
  lib/inventory/controller_test.go
Labels: backport, size/sm

#42313 [v16] Remove feature flag for VNet, unhide `tsh vnet`
  tool/tsh/common/vnet_darwin.go
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.tsx
Labels: ui, tsh, backport, size/sm, no-changelog

#42288 [v15] Add docs for web_idle_timeout
  docs/pages/connect-your-client/web-ui.mdx
Labels: documentation, backport, size/sm, no-changelog

#42308 [v14] Reduce log level on TOTP failures
  lib/auth/password.go
Labels: backport, size/sm, no-changelog

#42232 node-agent chart improvements
  assets/loadtest/helm/node-agent/templates/config.yaml
  assets/loadtest/helm/node-agent/templates/deployment.yaml
  assets/loadtest/helm/node-agent/values.yaml
Labels: size/sm, no-changelog

#41392 GCP SQL PostgreSQL backend
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/backend/pgbk/atomicwrite.go
  lib/backend/pgbk/background.go
  lib/backend/pgbk/common/auth.go
  lib/backend/pgbk/common/auth_test.go
  lib/backend/pgbk/common/azure.go
  lib/backend/pgbk/common/gcp.go
  lib/backend/pgbk/common/gcp_test.go
  lib/backend/pgbk/common/utils.go
  lib/backend/pgbk/pgbk.go
  lib/events/pgevents/pgevents.go
  lib/events/pgevents/pgevents_test.go
  lib/utils/gcp/gcp.go
  lib/utils/gcp/gcp_test.go
Labels: audit-log, gcp, size/md, size/lg, backport/branch/v15, backport/branch/v16

#42316 chore: Bump AWS modules
  api/utils/aws/identifiers.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/utils/aws/region_test.go
Labels: size/sm, no-changelog

#42298 [v14] docs: Add peer_public_addr to proxy reference
  docs/pages/includes/config-reference/proxy-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#42303 [v16] [buddy] changes in teleport-event-handler.toml docs
  docs/pages/includes/start-event-handler.mdx
Labels: documentation, backport, size/sm, no-changelog

#42296 [v16] docs: Add peer_public_addr to proxy reference
  docs/pages/includes/config-reference/proxy-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#42278 [v16] [docs] add Google Cloud Spanner integration docs
  docs/config.json
  docs/cspell.json
  docs/img/database-access/guides/spanner/create-spanner-user@2x.png
  docs/img/database-access/guides/spanner/grant-service-account-access-to-instance@2x.png
  docs/img/database-access/guides/spanner/grant-token-creator@2x.png
  docs/img/database-access/guides/spanner/select-instance@2x.png
  docs/img/database-access/guides/spanner/service-account-permissions-tab@2x.png
  docs/img/database-access/guides/spanner_cloud.png
  docs/img/database-access/guides/spanner_selfhosted.png
  docs/img/database-access/spanner-gui/datagrip-choose-no-auth@2x.png
  docs/img/database-access/spanner-gui/datagrip-data-source-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-connection-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-copy-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-create-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-open-driver-manager@2x.png
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/database-access/enroll-google-cloud-databases.mdx
  docs/pages/database-access/enroll-google-cloud-databases/mysql-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/postgres-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/spanner.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/cloudsql_service_credentials.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/gui-clients/spanner-local-proxy.mdx
  docs/pages/includes/database-access/gui-clients/spanner-reuse-port-note.mdx
Labels: documentation, backport, size/md, no-changelog

#42279 [v15] [docs] add Google Cloud Spanner integration docs
  docs/config.json
  docs/cspell.json
  docs/img/database-access/guides/spanner/create-spanner-user@2x.png
  docs/img/database-access/guides/spanner/grant-service-account-access-to-instance@2x.png
  docs/img/database-access/guides/spanner/grant-token-creator@2x.png
  docs/img/database-access/guides/spanner/select-instance@2x.png
  docs/img/database-access/guides/spanner/service-account-permissions-tab@2x.png
  docs/img/database-access/guides/spanner_cloud.png
  docs/img/database-access/guides/spanner_selfhosted.png
  docs/img/database-access/spanner-gui/datagrip-choose-no-auth@2x.png
  docs/img/database-access/spanner-gui/datagrip-data-source-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-connection-from-jdbc-url@2x.png
  docs/img/database-access/spanner-gui/dbeaver-copy-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-create-spanner-driver@2x.png
  docs/img/database-access/spanner-gui/dbeaver-open-driver-manager@2x.png
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/database-access/enroll-google-cloud-databases.mdx
  docs/pages/database-access/enroll-google-cloud-databases/mysql-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/postgres-cloudsql.mdx
  docs/pages/database-access/enroll-google-cloud-databases/spanner.mdx
  docs/pages/database-access/reference/audit.mdx
  docs/pages/database-access/reference/cli.mdx
  docs/pages/database-access/reference/configuration.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/cloudsql_service_credentials.mdx
  docs/pages/includes/database-access/create-user.mdx
  docs/pages/includes/database-access/gui-clients/spanner-local-proxy.mdx
  docs/pages/includes/database-access/gui-clients/spanner-reuse-port-note.mdx
Labels: documentation, backport, size/md, no-changelog

#42305 [v16] Document Jamf API credentials support
  docs/config.json
  docs/cspell.json
  docs/pages/access-controls/device-trust/jamf-integration.mdx
  docs/pages/includes/config-reference/jamf-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#42302 [v15] [buddy] changes in teleport-event-handler.toml docs
  docs/pages/includes/start-event-handler.mdx
Labels: documentation, backport, size/sm, no-changelog

#42297 [v15] docs: Add peer_public_addr to proxy reference
  docs/pages/includes/config-reference/proxy-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#41009 Refactor agent architecture guides into one
  docs/config.json
  docs/cspell.json
  docs/img/architecture/agent-architecture.png
  docs/img/architecture/k8s-tunnel.png
  docs/pages/access-controls/compliance-frameworks/soc2.mdx
  docs/pages/access-controls/reference.mdx
  docs/pages/agents/introduction.mdx
  docs/pages/application-access/introduction.mdx
  docs/pages/architecture/agents.mdx
  docs/pages/architecture/authentication.mdx
  docs/pages/architecture/authorization.mdx
  docs/pages/architecture/introduction.mdx
  docs/pages/architecture/nodes.mdx
  docs/pages/architecture/session-recording.mdx
  docs/pages/choose-an-edition/teleport-cloud/architecture.mdx
  docs/pages/database-access/architecture.mdx
  docs/pages/database-access/guides/ha.mdx
  docs/pages/database-access/introduction.mdx
  docs/pages/desktop-access/introduction.mdx
  docs/pages/kubernetes-access/introduction.mdx
  docs/pages/management/operations/db-ca-migrations.mdx
  docs/pages/management/operations/db-ca-rotation.mdx
  docs/pages/reference/backends.mdx
  docs/pages/reference/cli/teleport.mdx
  docs/pages/server-access/getting-started.mdx
  docs/pages/server-access/guides/bpf-session-recording.mdx
  docs/pages/server-access/introduction.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#41925 Refactor the Database Object Permissions guide
  docs/config.json
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/auto-user-provisioning/database-access-controls.mdx
  docs/pages/database-access/auto-user-provisioning/postgres.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#42336 [v15] Web: fix notification dropdown from being too long with max height
  web/packages/teleport/src/TopBar/Notifications/Notifications.tsx
Labels: ui, backport, size/md

#42322 Add NONE option to availability filter in the web UI
  api/gen/proto/go/userpreferences/v1/unified_resource_preferences.pb.go
  api/proto/teleport/userpreferences/v1/unified_resource_preferences.proto
  gen/proto/ts/teleport/userpreferences/v1/unified_resource_preferences_pb.ts
  lib/auth/userpreferences/userpreferencesv1/service_test.go
  lib/services/local/userpreferences.go
  lib/services/local/userpreferences_test.go
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/components/UnifiedResources/types.ts
  web/packages/teleport/src/generateResourcePath.ts
  web/packages/teleport/src/services/userPreferences/userPreferences.ts
Labels: ui, backport-required, size/sm, no-changelog, backport/branch/v16

#42338 [v14] Web: fix notification dropdown from being too long with max height
  web/packages/teleport/src/TopBar/Notifications/Notifications.tsx
Labels: ui, backport, size/sm

#42325 Add --invite and --reason to tsh ssh
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  constants.go
  docs/pages/access-controls/guides/moderated-sessions.mdx
  lib/srv/sess.go
  tool/tsh/common/tsh.go
Labels: documentation, kubernetes-access, tsh, rfd, moderated-sessions, size/sm, no-changelog, backport/branch/v16

#42289 [v14] Add docs for web_idle_timeout
  docs/pages/connect-your-client/web-ui.mdx
Labels: documentation, backport, size/sm, no-changelog

#42294 [v16] Entra ID integration: integration script updates and web prerequisites
  api/client/webclient/webconfig.go
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/integrations/azureoidc/accessgraph.go
  lib/integrations/azureoidc/private.go
  lib/integrations/azureoidc/provision.go
  lib/web/apiserver.go
  lib/web/integrations_azureoidc.go
  lib/web/integrations_azureoidc_test.go
  proto/prehog/v1alpha/teleport.proto
  tool/teleport/common/integration_configure.go
  web/packages/design/src/assets/images/icons/entra-id.svg
  web/packages/teleport/src/Integrations/IntegrationList.tsx
  web/packages/teleport/src/Integrations/fixtures.ts
  web/packages/teleport/src/components/ButtonLockedFeature/ButtonLockedFeature.tsx
  web/packages/teleport/src/components/ToolTipNoPermBadge/ToolTipNoPermBadge.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/integrations/types.ts
  web/packages/teleport/src/services/sales/index.ts
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport, size/sm

#42299 Do not overwrite an existing cluster when adding it again
  web/packages/teleterm/src/ui/services/clusters/clustersService.test.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42331 event-hanlder chart: re-create pods when a PV is mounted
  examples/chart/event-handler/templates/deployment.yaml
  examples/chart/event-handler/tests/deployment_test.yaml
Labels: helm, size/sm, backport/branch/v15, backport/branch/v16

#42353 [v15] Add properties field to the edge message
  gen/proto/go/accessgraph/v1alpha/graph.pb.go
  proto/accessgraph/v1alpha/graph.proto
Labels: backport, size/sm, no-changelog

#42029 Add "Access Graph Path Changed" event tracking
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  gen/proto/go/accessgraph/v1alpha/events.pb.go
  lib/events/api.go
  lib/events/dynamic.go
  proto/accessgraph/v1alpha/events.proto
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, audit-log, size/sm, no-changelog, backport/branch/v16

#42362 [v16] event-handler chart: re-create pods when a PV is mounted
  examples/chart/event-handler/templates/deployment.yaml
  examples/chart/event-handler/tests/deployment_test.yaml
Labels: helm, backport, size/sm

#42363 [v15] event-handler chart: re-create pods when a PV is mounted
  examples/chart/event-handler/templates/deployment.yaml
  examples/chart/event-handler/tests/deployment_test.yaml
Labels: helm, backport, size/sm

#42372 Rename AccessGraphAccessPathChanged
  lib/events/api.go
Labels: audit-log, size/sm, no-changelog

#42361 [v15] Refactor the Database Object Permissions guide
  docs/config.json
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/auto-user-provisioning/database-access-controls.mdx
  docs/pages/database-access/auto-user-provisioning/postgres.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/sm, no-changelog

#42360 [v16] Refactor the Database Object Permissions guide
  docs/config.json
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/auto-user-provisioning/database-access-controls.mdx
  docs/pages/database-access/auto-user-provisioning/postgres.mdx
  docs/pages/database-access/rbac.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/sm, no-changelog

#41587 Add telemetry to VNet in Connect
  integration/teleterm_test.go
  lib/teleterm/apiserver/apiserver.go
  lib/teleterm/apiserver/config.go
  lib/teleterm/clusteridcache/clusteridcache.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/config.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/teleterm.go
  lib/teleterm/teleterm_test.go
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_test.go
  lib/vnet/app_resolver.go
  lib/vnet/vnet_test.go
  tool/tsh/common/daemon.go
  tool/tsh/common/tsh.go
  tool/tsh/common/vnet_common.go
  web/packages/teleterm/src/mainProcess/runtimeSettings.ts
Labels: ui, tsh, size/md, no-changelog, backport/branch/v16

#42350 Allow custom hostname for EICE instances
  lib/srv/discovery/common/server.go
  lib/srv/discovery/common/server_test.go
Labels: size/sm, discovery, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42345 Fix getting chart url for non standard releases during EKS enrollment.
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: kubernetes-access, discover, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#42323 Use auto-generated TOC pages in the database access section
  docs/config.json
  docs/gen-topic-pages/README.md
  docs/gen-topic-pages/gen-topic-pages.js
  docs/gen-topic-pages/gen-topic-pages.test.js
  docs/gen-topic-pages/index.js
  docs/pages/database-access.mdx
  docs/pages/database-access/auto-user-provisioning.mdx
  docs/pages/database-access/enroll-aws-databases.mdx
  docs/pages/database-access/enroll-azure-databases.mdx
  docs/pages/database-access/enroll-google-cloud-databases.mdx
  docs/pages/database-access/enroll-managed-databases.mdx
  docs/pages/database-access/enroll-self-hosted-databases.mdx
  docs/pages/database-access/guides.mdx
  docs/pages/database-access/overview.mdx
  docs/pages/database-access/reference.mdx
  package.json
Labels: documentation, size/lg

#42343 [v16] Add NONE option to availability filter in the web UI
  api/gen/proto/go/userpreferences/v1/unified_resource_preferences.pb.go
  api/proto/teleport/userpreferences/v1/unified_resource_preferences.proto
  gen/proto/ts/teleport/userpreferences/v1/unified_resource_preferences_pb.ts
  lib/auth/userpreferences/userpreferencesv1/service_test.go
  lib/services/local/userpreferences.go
  lib/services/local/userpreferences_test.go
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/components/UnifiedResources/types.ts
  web/packages/teleport/src/generateResourcePath.ts
  web/packages/teleport/src/services/userPreferences/userPreferences.ts
Labels: ui, backport, size/sm, no-changelog

#41978 Use auto-generated menu pages for Access Controls
  docs/config.json
  docs/pages/access-controls.mdx
  docs/pages/access-controls/access-graph.mdx
  docs/pages/access-controls/access-graph/overview.mdx
  docs/pages/access-controls/access-lists.mdx
  docs/pages/access-controls/access-request-plugins.mdx
  docs/pages/access-controls/access-requests.mdx
  docs/pages/access-controls/access-requests/overview.mdx
  docs/pages/access-controls/compliance-frameworks.mdx
  docs/pages/access-controls/device-trust.mdx
  docs/pages/access-controls/device-trust/concepts.mdx
  docs/pages/access-controls/guides.mdx
  docs/pages/access-controls/idps.mdx
  docs/pages/access-controls/login-rules.mdx
  docs/pages/access-controls/sso.mdx
  docs/pages/access-controls/sso/overview.mdx
  package.json
Labels: documentation, size/md, size/lg

#41545 [vnet][7] custom DNS zones
  lib/teleterm/vnet/service.go
  lib/vnet/app_resolver.go
  lib/vnet/customdnszonevalidator.go
  lib/vnet/osconfig.go
  lib/vnet/vnet_test.go
  tool/tsh/common/vnet_common.go
Labels: size/sm, no-changelog, backport/branch/v16

#42340 Web: fix back button for guided bot flows to return to previous location
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.test.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.tsx
  web/packages/teleport/src/Bots/Add/Shared/GuidedFlow.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#42384 [v15] Instruments pgevents to report metrics
  docs/pages/includes/metrics.mdx
  lib/events/pgevents/metrics.go
  lib/events/pgevents/pgevents.go
Labels: documentation, audit-log, backport, size/md

#42367 Remove handling of old env var
  lib/srv/sess.go
Labels: size/sm, no-changelog

#42110 docs: refactor desktop access intro
  docs/pages/desktop-access/introduction.mdx
Labels: documentation, desktop-access, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42387 [v16] Fix getting chart url for non standard releases during EKS enrollment.
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: backport, size/sm, no-changelog

#42374 Use generated TOC pages for smaller sections
  docs/config.json
  docs/pages/agents.mdx
  docs/pages/agents/introduction.mdx
  docs/pages/agents/join-services-to-your-cluster.mdx
  docs/pages/agents/join-services-to-your-cluster/overview.mdx
  docs/pages/api.mdx
  docs/pages/architecture.mdx
  docs/pages/auto-discovery.mdx
  docs/pages/auto-discovery/introduction.mdx
  docs/pages/auto-discovery/kubernetes-applications.mdx
  docs/pages/auto-discovery/kubernetes.mdx
  docs/pages/auto-discovery/kubernetes/overview.mdx
  docs/pages/auto-discovery/servers.mdx
  docs/pages/choose-an-edition.mdx
  docs/pages/choose-an-edition/teleport-cloud.mdx
  docs/pages/choose-an-edition/teleport-enterprise.mdx
  docs/pages/connect-your-client.mdx
  docs/pages/desktop-access.mdx
  docs/pages/desktop-access/reference.mdx
  docs/pages/includes/connect-your-client/connect-my-computer-prerequisites.mdx
  docs/pages/includes/connect-your-client/launch-connect-with-flags-macos.mdx
  docs/pages/includes/kubernetes-access/helm/helm-repo-add.mdx
  docs/pages/includes/kubernetes-access/helm/kubernetes-externaladdress.mdx
  docs/pages/includes/kubernetes-access/helm/teleport-cluster-cloud-warning.mdx
  docs/pages/includes/kubernetes-access/helm/teleport-cluster-install.mdx
  docs/pages/includes/kubernetes-access/helm/teleport-cluster-prereqs.mdx
  docs/pages/kubernetes-access.mdx
  docs/pages/kubernetes-access/register-clusters.mdx
  package.json
Labels: documentation, size/lg

#42398 Docs: v16 supported versions in FAQ
  docs/pages/faq.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#42400 [v16] Add `show_resources` to ui config docs
  docs/pages/includes/config-reference/proxy-service.yaml
  docs/pages/includes/ui-config-spec.mdx
  docs/pages/management/dynamic-resources.mdx
Labels: documentation, backport, size/sm, no-changelog

#42366 [v14] Move --reason and --invite to tsh ssh
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  constants.go
  docs/pages/access-controls/guides/moderated-sessions.mdx
  lib/srv/sess.go
  tool/tsh/common/tsh.go
Labels: documentation, tsh, backport, size/sm, no-changelog

#42099 Make ID_LIKE instructions more prominent
  docs/pages/installation.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42364 [v16] Add --invite and --reason to tsh ssh
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  constants.go
  docs/pages/access-controls/guides/moderated-sessions.mdx
  lib/srv/sess.go
  tool/tsh/common/tsh.go
Labels: documentation, tsh, backport, size/sm, no-changelog

#42365 [v15] Move --reason and --invite to tsh ssh
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  constants.go
  docs/pages/access-controls/guides/moderated-sessions.mdx
  lib/srv/sess.go
  tool/tsh/common/tsh.go
Labels: documentation, tsh, backport, size/sm, no-changelog

#42404 [v15] chore: Bump Go to v1.21.11
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm, backport/branch/v14

#42403 chore: Bump Go to v1.22.4
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm, no-changelog, backport/branch/v16

#42388 [v15] Fix getting chart url for non standard releases during EKS enrollment.
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/integrations/awsoidc/eks_enroll_clusters_test.go
Labels: backport, size/sm, no-changelog

#42337 Update SAML IdP getting started guide
  docs/cspell.json
  docs/img/access-controls/saml-idp/access-app.png
  docs/img/access-controls/saml-idp/add-entity-descriptor.png
  docs/img/access-controls/saml-idp/enroll-saml-app.png
  docs/img/access-controls/saml-idp/iamshowcase-protected-page.png
  docs/img/access-controls/saml-idp/protected-page-access.png
  docs/img/access-controls/saml-idp/samltestid-0-successful-upload.png
  docs/img/access-controls/saml-idp/samltestid-1-test-idp.png
  docs/img/access-controls/saml-idp/samltestid-2-successful-login.png
  docs/img/access-controls/saml-idp/teleport-idp-metadata.png
  docs/pages/access-controls/idps/saml-guide.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#41963 Invoke signing function for Windows Connect binary
  build.assets/windows/build.ps1
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport-required, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15, backport/branch/v16

#42401 Update device trust docs for v16
  docs/pages/access-controls/device-trust/enforcing-device-trust.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#42383 [v16] Instruments pgevents to report metrics
  docs/pages/includes/metrics.mdx
  lib/events/pgevents/metrics.go
  lib/events/pgevents/pgevents.go
Labels: documentation, audit-log, backport, size/md

#42357 [v15] Do not overwrite an existing cluster when adding it again
  web/packages/teleterm/src/ui/services/clusters/clustersService.test.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
Labels: ui, backport, size/sm, no-changelog

#42390 [v16] Web: fix back button for guided bot flows to return to previous location
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.test.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.tsx
  web/packages/teleport/src/Bots/Add/Shared/GuidedFlow.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, backport, size/sm, no-changelog

#42356 [v16] Do not overwrite an existing cluster when adding it again
  web/packages/teleterm/src/ui/services/clusters/clustersService.test.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
Labels: ui, backport, size/sm, no-changelog

#42397 Update users and device trust testplan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#42275 Allow athenaevents to bypass SNS
  examples/dynamoathenamigration/migration.go
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/fakequeue_test.go
  lib/events/athena/integration_test.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
  lib/events/athena/test.go
Labels: audit-log, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42448 [v16] Update device trust docs for v16
  docs/pages/access-controls/device-trust/enforcing-device-trust.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#42393 [v16][vnet][7] custom DNS zones
  lib/teleterm/vnet/service.go
  lib/vnet/app_resolver.go
  lib/vnet/customdnszonevalidator.go
  lib/vnet/osconfig.go
  lib/vnet/vnet_test.go
  tool/tsh/common/vnet_common.go
Labels: tsh, backport, size/md, no-changelog

#42396 [v15] Web: fix back button for guided bot flows to return to previous location
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.test.tsx
  web/packages/teleport/src/Bots/Add/Shared/FlowButtons.tsx
  web/packages/teleport/src/Bots/Add/Shared/GuidedFlow.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
Labels: ui, backport, size/sm, no-changelog

#42415 [v16] chore: Bump Go to v1.22.4
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm, no-changelog

#42463 [v16] Allow athenaevents to bypass SNS
  examples/dynamoathenamigration/migration.go
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/fakequeue_test.go
  lib/events/athena/integration_test.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
  lib/events/athena/test.go
Labels: audit-log, backport, size/md, no-changelog

#42464 [v15] Allow athenaevents to bypass SNS
  examples/dynamoathenamigration/migration.go
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/fakequeue_test.go
  lib/events/athena/integration_test.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
  lib/events/athena/test.go
Labels: audit-log, backport, size/md, no-changelog

#42378 [v16] Add telemetry to VNet in Connect
  integration/teleterm_test.go
  lib/teleterm/apiserver/apiserver.go
  lib/teleterm/apiserver/config.go
  lib/teleterm/clusteridcache/clusteridcache.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/config.go
  lib/teleterm/daemon/config.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/teleterm.go
  lib/teleterm/teleterm_test.go
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_test.go
  lib/vnet/app_resolver.go
  lib/vnet/vnet_test.go
  tool/tsh/common/daemon.go
  tool/tsh/common/tsh.go
  tool/tsh/common/vnet_common.go
  web/packages/teleterm/src/mainProcess/runtimeSettings.ts
Labels: ui, tsh, backport, size/md, no-changelog

#42471 [v13] [branch/v16] Invoke signing function for Windows Connect binary (#41963)
  build.assets/windows/build.ps1
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#42465 [v14] Allow athenaevents to bypass SNS
  examples/dynamoathenamigration/migration.go
  lib/events/athena/athena.go
  lib/events/athena/athena_test.go
  lib/events/athena/fakequeue_test.go
  lib/events/athena/integration_test.go
  lib/events/athena/publisher.go
  lib/events/athena/publisher_test.go
  lib/events/athena/test.go
Labels: audit-log, backport, size/md, no-changelog

#42416 [v14] chore: Bump Go to v1.21.11
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#42473 [v14] [branch/v16] Invoke signing function for Windows Connect binary (#41963)
  build.assets/windows/build.ps1
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#42408 [v16] docs: refactor desktop access intro
  docs/pages/desktop-access/introduction.mdx
Labels: documentation, backport, size/sm

#42410 [v14] docs: refactor desktop access intro
  docs/pages/desktop-access/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#42474 accesslist: return "ineligible_status" for all write operations
  api/client/accesslist/accesslist.go
  api/client/events.go
  api/types/accesslist/convert/v1/member.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42329 Fix External Audit Storage CTA condition
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.test.tsx
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#42376 [v14] fix app cache ctx cancel
  lib/srv/app/azure/handler.go
  lib/srv/app/azure/handler_test.go
Labels: application-access, backport, size/sm, no-changelog

#42479 [v14] accesslist: return "ineligible_status" for all write operations
  api/client/accesslist/accesslist.go
  api/client/events.go
  api/types/accesslist/convert/v1/member.go
Labels: backport, size/sm, no-changelog

#42480 [v15] accesslist: return "ineligible_status" for all write operations
  api/client/accesslist/accesslist.go
  api/client/events.go
  api/types/accesslist/convert/v1/member.go
Labels: backport, size/sm, no-changelog

#42375 [v15] lazy load azure credentials for app and fix cache ctx cancel
  lib/srv/app/azure/credential.go
  lib/srv/app/azure/handler.go
  lib/srv/app/azure/handler_test.go
Labels: application-access, backport, size/sm, no-changelog

#42486 cleanup: remove `StreamUnstructuredSessionEvents` fallback
  api/client/client.go
Labels: size/sm, no-changelog, backport/branch/v16

#42481 [v16] accesslist: return "ineligible_status" for all write operations
  api/client/accesslist/accesslist.go
  api/client/events.go
  api/types/accesslist/convert/v1/member.go
Labels: backport, size/sm, no-changelog

#42488 Add Table of Contents pages to two sections
  docs/config.json
  docs/pages/deploy-a-cluster.mdx
  docs/pages/deploy-a-cluster/deployments.mdx
  docs/pages/deploy-a-cluster/helm-deployments.mdx
  docs/pages/server-access.mdx
  docs/pages/server-access/guides.mdx
  docs/pages/server-access/openssh.mdx
  package.json
Labels: documentation, size/sm, no-changelog

#42472 [v15] Invoke signing function for Windows Connect binary
  build.assets/windows/build.ps1
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#42406 [v15] Make ID_LIKE instructions more prominent
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#42407 [v16] Make ID_LIKE instructions more prominent
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#42234 [v15] Docs: TAG policy revision
  docs/config.json
  docs/pages/access-controls/access-graph.mdx
  docs/pages/access-controls/access-graph/aws-sync.mdx
Labels: documentation, backport, size/sm, no-changelog

#42491 [v15] docs: OKTA SCIM only integration
  docs/cspell.json
  docs/img/enterprise/plugins/okta/scim-provision-existing-users.png
  docs/pages/application-access/okta.mdx
  docs/pages/application-access/okta/scim-only.mdx
Labels: documentation, backport, size/md, no-changelog

#42413 [v15] Update SAML IdP getting started guide
  docs/cspell.json
  docs/img/access-controls/saml-idp/access-app.png
  docs/img/access-controls/saml-idp/add-entity-descriptor.png
  docs/img/access-controls/saml-idp/enroll-saml-app.png
  docs/img/access-controls/saml-idp/iamshowcase-protected-page.png
  docs/img/access-controls/saml-idp/protected-page-access.png
  docs/img/access-controls/saml-idp/samltestid-0-successful-upload.png
  docs/img/access-controls/saml-idp/samltestid-1-test-idp.png
  docs/img/access-controls/saml-idp/samltestid-2-successful-login.png
  docs/img/access-controls/saml-idp/teleport-idp-metadata.png
  docs/pages/access-controls/idps/saml-guide.mdx
Labels: documentation, backport, size/sm, no-changelog

#42482 [v15] Fix External Audit Storage CTA condition
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.test.tsx
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
Labels: ui, backport, size/sm, no-changelog

#42070 Report unexpected VNet shutdown from tsh daemon to Electron app
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service_grpc.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.client.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.grpc-server.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  lib/teleterm/vnet/service.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.tsx
  web/packages/teleterm/src/ui/Vnet/VnetConnectionItem.tsx
  web/packages/teleterm/src/ui/Vnet/VnetSliderStep.tsx
  web/packages/teleterm/src/ui/Vnet/useVnetLauncher.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.test.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.tsx
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/tshdEvents.ts
  web/packages/teleterm/src/ui/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v16

#42489 [v16] docs: OKTA SCIM only integration
  docs/cspell.json
  docs/img/enterprise/plugins/okta/scim-provision-existing-users.png
  docs/pages/application-access/okta.mdx
  docs/pages/application-access/okta/scim-only.mdx
Labels: documentation, backport, size/md, no-changelog

#42483 [v16] Fix External Audit Storage CTA condition
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.test.tsx
  web/packages/teleport/src/components/ExternalAuditStorageCta/ExternalAuditStorageCta.tsx
Labels: ui, backport, size/sm, no-changelog

#42500 Web UI tweaks
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/ServerSideSupportedList.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42412 [v16] Update SAML IdP getting started guide
  docs/cspell.json
  docs/img/access-controls/saml-idp/access-app.png
  docs/img/access-controls/saml-idp/add-entity-descriptor.png
  docs/img/access-controls/saml-idp/enroll-saml-app.png
  docs/img/access-controls/saml-idp/iamshowcase-protected-page.png
  docs/img/access-controls/saml-idp/protected-page-access.png
  docs/img/access-controls/saml-idp/samltestid-0-successful-upload.png
  docs/img/access-controls/saml-idp/samltestid-1-test-idp.png
  docs/img/access-controls/saml-idp/samltestid-2-successful-login.png
  docs/img/access-controls/saml-idp/teleport-idp-metadata.png
  docs/pages/access-controls/idps/saml-guide.mdx
Labels: documentation, backport, size/sm, no-changelog

#42414 [v14] Update SAML IdP getting started guide
  docs/cspell.json
  docs/img/access-controls/saml-idp/access-app.png
  docs/img/access-controls/saml-idp/add-entity-descriptor.png
  docs/img/access-controls/saml-idp/enroll-saml-app.png
  docs/img/access-controls/saml-idp/iamshowcase-protected-page.png
  docs/img/access-controls/saml-idp/protected-page-access.png
  docs/img/access-controls/saml-idp/samltestid-0-successful-upload.png
  docs/img/access-controls/saml-idp/samltestid-1-test-idp.png
  docs/img/access-controls/saml-idp/samltestid-2-successful-login.png
  docs/img/access-controls/saml-idp/teleport-idp-metadata.png
  docs/pages/access-controls/idps/saml-guide.mdx
Labels: documentation, backport, size/sm, no-changelog

#41662 Add access list notifications support to new notifications list
  web/packages/teleport/src/Navigation/NavigationItem.test.tsx
  web/packages/teleport/src/Navigation/NavigationItem.tsx
  web/packages/teleport/src/Notifications/Notification.story.tsx
  web/packages/teleport/src/Notifications/Notification.tsx
  web/packages/teleport/src/Notifications/Notifications.test.tsx
  web/packages/teleport/src/Notifications/Notifications.tsx
  web/packages/teleport/src/Notifications/notificationContentFactory.tsx
  web/packages/teleport/src/TopBar/Notifications/Notifications.test.tsx
  web/packages/teleport/src/TopBar/Notifications/Notifications.tsx
  web/packages/teleport/src/TopBar/Notifications/index.ts
  web/packages/teleport/src/TopBar/TopBar.story.tsx
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/services/notifications/types.ts
  web/packages/teleport/src/services/storageService/types.ts
  web/packages/teleport/src/stores/storeNotifications.test.ts
  web/packages/teleport/src/stores/storeNotifications.ts
Labels: ui, size/md, no-changelog, backport/branch/v16

#42503 [v15] Web UI tweaks
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/ServerSideSupportedList.tsx
Labels: ui, backport, size/sm, no-changelog

#42502 [v16] Web UI tweaks
  web/packages/teleport/src/Discover/Database/EnrollRdsDatabase/EnrollRdsDatabase.tsx
  web/packages/teleport/src/Integrations/Enroll/common.tsx
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/ServerSideSupportedList/ServerSideSupportedList.tsx
Labels: ui, backport, size/sm, no-changelog

#42023 Support CockroachDB in `pgevents`
  lib/backend/pgbk/common/utils.go
  lib/events/pgevents/pgevents.go
  lib/events/pgevents/pgevents_test.go
Labels: audit-log, size/sm, backport/branch/v15, backport/branch/v16

#42382 [v16] GCP SQL PostgreSQL backend
  go.mod
  go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/backend/pgbk/atomicwrite.go
  lib/backend/pgbk/background.go
  lib/backend/pgbk/common/auth.go
  lib/backend/pgbk/common/auth_test.go
  lib/backend/pgbk/common/azure.go
  lib/backend/pgbk/common/gcp.go
  lib/backend/pgbk/common/gcp_test.go
  lib/backend/pgbk/common/utils.go
  lib/backend/pgbk/pgbk.go
  lib/events/pgevents/pgevents.go
  lib/events/pgevents/pgevents_test.go
  lib/utils/gcp/gcp.go
  lib/utils/gcp/gcp_test.go
Labels: audit-log, backport, size/lg

#42399 [v15] GCP SQL PostgreSQL backend
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/backend/pgbk/atomicwrite.go
  lib/backend/pgbk/background.go
  lib/backend/pgbk/common/auth.go
  lib/backend/pgbk/common/auth_test.go
  lib/backend/pgbk/common/azure.go
  lib/backend/pgbk/common/gcp.go
  lib/backend/pgbk/common/gcp_test.go
  lib/backend/pgbk/common/utils.go
  lib/backend/pgbk/pgbk.go
  lib/events/pgevents/pgevents.go
  lib/events/pgevents/pgevents_test.go
  lib/utils/gcp/gcp.go
  lib/utils/gcp/gcp_test.go
Labels: audit-log, backport, size/lg

#42505 fix: Address macOS build deprecation warning
  lib/auth/touchid/register.m
Labels: size/sm, no-changelog, backport/branch/v16

#42355 Always issue relogin and per-session mfa requests for the root cluster URI
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/daemon/mfaprompt.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/ModalsHost/modals/ReAuthenticate/ReAuthenticate.story.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/ReAuthenticate/ReAuthenticate.tsx
  web/packages/teleterm/src/ui/services/modals/modalsService.ts
Labels: teleport-connect, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42514 [v16] fix: Address macOS build deprecation warning
  lib/auth/touchid/register.m
Labels: backport, size/sm, no-changelog

#42513 fix: Do not DNS resolve on TestJoinServiceClient_RegisterUsingTPMMethod
  api/client/joinservice_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42507 [v16] Add access list notifications support to new notifications list
  web/packages/teleport/src/Navigation/NavigationItem.test.tsx
  web/packages/teleport/src/Navigation/NavigationItem.tsx
  web/packages/teleport/src/Notifications/Notification.story.tsx
  web/packages/teleport/src/Notifications/Notification.tsx
  web/packages/teleport/src/Notifications/Notifications.test.tsx
  web/packages/teleport/src/Notifications/Notifications.tsx
  web/packages/teleport/src/Notifications/notificationContentFactory.tsx
  web/packages/teleport/src/TopBar/Notifications/Notifications.test.tsx
  web/packages/teleport/src/TopBar/Notifications/Notifications.tsx
  web/packages/teleport/src/TopBar/Notifications/index.ts
  web/packages/teleport/src/TopBar/TopBar.story.tsx
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/services/notifications/types.ts
  web/packages/teleport/src/services/storageService/types.ts
  web/packages/teleport/src/stores/storeNotifications.test.ts
  web/packages/teleport/src/stores/storeNotifications.ts
Labels: ui, backport, size/md, no-changelog

#42496 [v16] Check usageReporting.enabled before enabling VNet telemetry
  buf.yaml
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service_grpc.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.client.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.grpc-server.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  lib/teleterm/daemon/daemon.go
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_test.go
  proto/teleport/lib/teleterm/v1/tshd_events_service.proto
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/runtimeSettings.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/ui/tshdEvents.ts
Labels: ui, backport, size/sm, no-changelog

#41416 Log information about second_factors removal at startup
  lib/auth/init.go
  lib/modules/modules.go
  lib/modules/modules_test.go
Labels: size/sm, no-changelog, backport/branch/v16

#42517 [v16] fix: Do not DNS resolve on TestJoinServiceClient_RegisterUsingTPMMethod
  api/client/joinservice_test.go
Labels: backport, size/sm, no-changelog

#42494 chore: Bump OpenSSL to 3.0.14
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libcrypto-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libcrypto-static.pc
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#42497 chore: Bump protoc-gen-go-grpc to v1.4.0
  Makefile
  api/gen/proto/go/assist/v1/assist_grpc.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/gen/proto/go/teleport/accessmonitoringrules/v1/access_monitoring_rules_service_grpc.pb.go
  api/gen/proto/go/teleport/auditlog/v1/auditlog_grpc.pb.go
  api/gen/proto/go/teleport/clusterconfig/v1/clusterconfig_service_grpc.pb.go
  api/gen/proto/go/teleport/crownjewel/v1/crownjewel_service_grpc.pb.go
  api/gen/proto/go/teleport/dbobject/v1/dbobject_service_grpc.pb.go
  api/gen/proto/go/teleport/dbobjectimportrule/v1/dbobjectimportrule_service_grpc.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service_grpc.pb.go
  api/gen/proto/go/teleport/discoveryconfig/v1/discoveryconfig_service_grpc.pb.go
  api/gen/proto/go/teleport/externalauditstorage/v1/externalauditstorage_service_grpc.pb.go
  api/gen/proto/go/teleport/integration/v1/awsoidc_service_grpc.pb.go
  api/gen/proto/go/teleport/integration/v1/integration_service_grpc.pb.go
  api/gen/proto/go/teleport/kube/v1/kube_service_grpc.pb.go
  api/gen/proto/go/teleport/kubewaitingcontainer/v1/kubewaitingcontainer_service_grpc.pb.go
  api/gen/proto/go/teleport/loginrule/v1/loginrule_service_grpc.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_service_grpc.pb.go
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service_grpc.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service_grpc.pb.go
  api/gen/proto/go/teleport/okta/v1/okta_service_grpc.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/gen/proto/go/teleport/presence/v1/service_grpc.pb.go
  api/gen/proto/go/teleport/resourceusage/v1/resourceusage_service_grpc.pb.go
  api/gen/proto/go/teleport/samlidp/v1/samlidp_grpc.pb.go
  api/gen/proto/go/teleport/scim/v1/scim_service_grpc.pb.go
  api/gen/proto/go/teleport/secreports/v1/secreports_service_grpc.pb.go
  api/gen/proto/go/teleport/transport/v1/transport_service_grpc.pb.go
  api/gen/proto/go/teleport/trust/v1/trust_service_grpc.pb.go
  api/gen/proto/go/teleport/userloginstate/v1/userloginstate_service_grpc.pb.go
  api/gen/proto/go/teleport/users/v1/users_service_grpc.pb.go
  api/gen/proto/go/teleport/vnet/v1/vnet_config_service_grpc.pb.go
  api/gen/proto/go/userpreferences/v1/userpreferences_grpc.pb.go
  gen/proto/go/accessgraph/v1alpha/access_graph_service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/tshd_events_service_grpc.pb.go
  gen/proto/go/teleport/lib/teleterm/vnet/v1/vnet_service_grpc.pb.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/multiplexer/test/ping_grpc.pb.go
Labels: size/sm, no-changelog

#42461 Remove old websocket endpoints
  lib/web/apiserver.go
Labels: size/sm, no-changelog, backport/branch/v16

#42460 Add a guide for economic buyers
  docs/config.json
  docs/pages/agents/introduction.mdx
  docs/pages/deploy-a-cluster/introduction.mdx
  docs/pages/deploy-a-cluster/linux-demo.mdx
  docs/pages/index.mdx
  docs/pages/management/admin/self-signed-certs.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15, backport/branch/v16

#42518 [vnet] clean up osconfig on startup
  lib/vnet/osconfig.go
  lib/vnet/setup.go
Labels: size/sm, no-changelog, vnet, backport/branch/v16

#42524 [v16] Remove old websocket endpoints
  lib/web/apiserver.go
Labels: backport, size/sm, no-changelog

#42499 Fix typo in Edit Integration screen
  web/packages/teleport/src/Integrations/EditAwsOidcIntegrationDialog.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16
