Repository gravitational/teleport, pull requests merged in 2024-07, with the labels that each got.

#43653 [v16] Add AppArmor profile for Connect
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/build_resources/linux/after-remove.tpl
  web/packages/teleterm/build_resources/linux/apparmor-profile
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#43651 [v14] Add AppArmor profile for Connect
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/build_resources/linux/after-remove.tpl
  web/packages/teleterm/build_resources/linux/apparmor-profile
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#43652 [v15] Add AppArmor profile for Connect
  web/packages/teleterm/build_resources/linux/after-install.tpl
  web/packages/teleterm/build_resources/linux/after-remove.tpl
  web/packages/teleterm/build_resources/linux/apparmor-profile
  web/packages/teleterm/electron-builder-config.js
Labels: ui, backport, size/sm

#43630 Reword "Preview" admonition in Workload Identity documentation to remove Production warning.
  docs/pages/machine-id/workload-identity.mdx
  docs/pages/machine-id/workload-identity/aws-roles-anywhere.mdx
  docs/pages/machine-id/workload-identity/best-practices.mdx
  docs/pages/machine-id/workload-identity/getting-started.mdx
  docs/pages/machine-id/workload-identity/tsh.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43585 Remove unused JS dependencies
  web/packages/build/bin/g-build.js
  web/packages/build/bin/g-start.js
  web/packages/build/devserver/index.js
  web/packages/build/devserver/initCompiler.js
  web/packages/build/devserver/modifyResponse.js
  web/packages/build/package.json
  web/packages/build/webpack/webpack.base.js
  web/packages/build/webpack/webpack.dev.config.js
  web/packages/build/webpack/webpack.prod.config.js
  web/packages/design/package.json
  web/packages/design/src/.storybook/config.js
  web/packages/design/src/.storybook/webpack.config.js
  web/packages/design/src/DraggableList/DraggableList.tsx
  web/packages/design/src/DraggableList/index.ts
  web/packages/e-imports/package.json
  web/packages/shared/package.json
  web/packages/teleport/package.json
  web/packages/teleport/webpack.dev.config.js
  web/packages/teleport/webpack.prod.config.js
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, size/sm, no-changelog, backport/branch/v16

#43269 [v15] MockedUnaryCall.then: Handle onrejected not being defined
  web/packages/teleterm/src/services/tshd/cloneableClient.ts
Labels: ui, backport, size/sm, no-changelog

#43645 Update Connect icons
  web/packages/teleterm/build_resources/icon-linux/512x512.png
  web/packages/teleterm/build_resources/icon-mac.png
  web/packages/teleterm/build_resources/icon-win.ico
Labels: backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43677 web/README.md: Add socat method to MFA development
  web/README.md
Labels: ui, size/sm, no-changelog

#43660 [v16] Convert lib/labels to slog
  lib/kube/proxy/cluster_details.go
  lib/labels/cloud.go
  lib/labels/labels.go
  lib/service/kubernetes.go
  lib/srv/app/server.go
  lib/srv/db/server.go
Labels: kubernetes-access, application-access, database-access, backport, size/sm, no-changelog

#43659 [v15] Convert lib/labels to slog
  lib/kube/proxy/cluster_details.go
  lib/labels/cloud.go
  lib/labels/labels.go
  lib/service/kubernetes.go
  lib/srv/app/server.go
  lib/srv/db/server.go
Labels: kubernetes-access, application-access, database-access, backport, size/sm, no-changelog

#42596 Update test plan with desktop resize tests
  .github/ISSUE_TEMPLATE/testplan.md
  lib/srv/desktop/tdp/proto.go
Labels: desktop-access, size/sm, no-changelog

#43709 Add more cases to Machine ID test plan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#43578 docs: updates to networking reference
  docs/pages/reference/networking.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43670 [v16] Update IronRDP
  Cargo.lock
  Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#43546 Record PostgreSQL queries/command results
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
Labels: audit-log, database-access, size/md

#43717 Remove index.ejs from web package
  Makefile
  web/packages/build/index.ejs
Labels: ui, backport-required, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43720 [v15] docs: updates to networking reference
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#43721 [v14] docs: updates to networking reference
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#43719 [v16] docs: updates to networking reference
  docs/pages/reference/networking.mdx
Labels: documentation, backport, size/sm, no-changelog

#43508 remove `api.types.protoKnownFieldsEqual` hack with goderive
  api/types/cmp.go
  api/types/cmp_test.go
  api/types/database.go
  api/types/derived.gen.go
  api/types/kubernetes.go
Labels: size/sm, no-changelog, backport/branch/v16

#43726 [v16] Remove index.ejs from web package
  Makefile
  web/packages/build/index.ejs
Labels: ui, backport, size/sm, no-changelog

#43727 [v15] Remove index.ejs from web package
  Makefile
  web/packages/build/index.ejs
Labels: ui, backport, size/sm, no-changelog

#43728 [v14] Remove index.ejs from web package
  Makefile
  web/packages/build/index.ejs
Labels: ui, backport, size/sm, no-changelog

#43335 fix redshift auto user deadlocking
  e2e/aws/redshift_test.go
  lib/srv/db/common/autousers.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/sql/redshift-deactivate-user.sql
  lib/srv/db/postgres/users.go
Labels: database-access, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43627 [v16] docs: Add Okta integration warning
  docs/config.json
  docs/pages/application-access/okta/hosted-guide.mdx
Labels: documentation, backport, size/sm, no-changelog

#43701 [v15] Reword "Preview" admonition in Workload Identity documentation to remove Production warning.
  docs/pages/machine-id/workload-identity.mdx
  docs/pages/machine-id/workload-identity/aws-roles-anywhere.mdx
  docs/pages/machine-id/workload-identity/best-practices.mdx
  docs/pages/machine-id/workload-identity/getting-started.mdx
  docs/pages/machine-id/workload-identity/tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#43723 Added markdown doc with artifact signing info
  docs/security/signing-info.md
Labels: documentation, backport-required, size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43736 [v16] Bump immer from 9.0.19 to 10.1.1
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#43737 [v15] Bump immer from 9.0.19 to 10.1.1
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#43702 [v16] Reword "Preview" admonition in Workload Identity documentation to remove Production warning.
  docs/pages/machine-id/workload-identity.mdx
  docs/pages/machine-id/workload-identity/aws-roles-anywhere.mdx
  docs/pages/machine-id/workload-identity/best-practices.mdx
  docs/pages/machine-id/workload-identity/getting-started.mdx
  docs/pages/machine-id/workload-identity/tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#43739 [v16] remove `api.types.protoKnownFieldsEqual` hack with goderive
  api/types/cmp.go
  api/types/cmp_test.go
  api/types/database.go
  api/types/derived.gen.go
  api/types/kubernetes.go
Labels: backport, size/sm, no-changelog

#43382 convert db lib to use slog, part 1
  lib/srv/db/auth_test.go
  lib/srv/db/ca.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
  lib/srv/db/sqlserver/proxy.go
  lib/srv/db/watcher.go
Labels: database-access, size/sm, no-changelog, backport/branch/v16

#43724 [v16] improve session resumption error message
  lib/resumption/client.go
Labels: backport, size/sm, no-changelog

#43725 [v15] improve session resumption error message
  lib/resumption/client.go
Labels: backport, size/sm, no-changelog

#43422 readonly cluster configs
  api/types/authentication.go
  api/types/sessionrecording.go
  integration/helpers/helpers.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/auth/sessions.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/service/service.go
  lib/services/access_checker.go
  lib/services/readonly/cache.go
  lib/services/readonly/readonly.go
  lib/services/readonly/readonly_test.go
  lib/services/role.go
  lib/srv/db/common/session.go
  lib/srv/db/common/session_test.go
  lib/srv/db/sqlserver/engine_test.go
Labels: database-access, size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43519 [v16] Show cloud commands as default installation instructions
  docs/pages/includes/install-windows-clients.mdx
  docs/pages/includes/install-windows.mdx
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#43733 docs: remove tsh recording exports
  docs/pages/desktop-access/reference/sessions.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43754 [v16] Added markdown doc with artifact signing info
  docs/security/signing-info.md
Labels: documentation, backport, size/md

#43671 [v15] Update IronRDP
  Cargo.lock
  Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
Labels: backport, size/sm, no-changelog

#43752 [v15] Added markdown doc with artifact signing info
  docs/security/signing-info.md
Labels: documentation, backport, size/md

#43753 [v14] Added markdown doc with artifact signing info
  docs/security/signing-info.md
Labels: documentation, backport, size/md

#43749 [v16] convert db lib to use slog, part 1
  lib/srv/db/auth_test.go
  lib/srv/db/ca.go
  lib/srv/db/mysql/proxy.go
  lib/srv/db/postgres/proxy.go
  lib/srv/db/proxyserver.go
  lib/srv/db/server.go
  lib/srv/db/sqlserver/proxy.go
  lib/srv/db/watcher.go
Labels: database-access, backport, size/sm, no-changelog

#43755 [v16] readonly cluster configs
  api/types/authentication.go
  api/types/sessionrecording.go
  integration/helpers/helpers.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/auth/sessions.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/service/service.go
  lib/services/access_checker.go
  lib/services/readonly/cache.go
  lib/services/readonly/readonly.go
  lib/services/readonly/readonly_test.go
  lib/services/role.go
  lib/srv/db/common/session.go
  lib/srv/db/common/session_test.go
  lib/srv/db/sqlserver/engine_test.go
Labels: database-access, backport, size/md

#43760 [v15] readonly shared cluster configs
  api/types/authentication.go
  api/types/sessionrecording.go
  integration/helpers/helpers.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/grpcserver.go
  lib/auth/helpers.go
  lib/auth/sessions.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/service/service.go
  lib/services/access_checker.go
  lib/services/readonly/cache.go
  lib/services/readonly/readonly.go
  lib/services/readonly/readonly_test.go
  lib/services/role.go
  lib/srv/db/common/session.go
  lib/srv/db/common/session_test.go
  lib/srv/db/sqlserver/engine_test.go
Labels: database-access, backport, size/md

#43761 chore: Bump Go to v1.22.5
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43521 Omit control plane instances from inventory list
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43764 [v15] docs: remove tsh recording exports
  docs/pages/desktop-access/reference/sessions.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#43772 chore: Bump AWS modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#43750 added audit events for discovery config actions
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/auth/discoveryconfig/discoveryconfigv1/service.go
  lib/auth/discoveryconfig/discoveryconfigv1/service_test.go
  lib/auth/grpcserver.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
Labels: audit-log, size/md, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43787 Update Bot Terraform docs
  docs/pages/machine-id/reference.mdx
  docs/pages/reference/terraform-provider/resources/bot.mdx
  integrations/terraform/examples/resources/teleport_bot/resource.tf
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#43770 [v14] chore: Bump Go to v1.22.5
  build.assets/versions.mk
  go.mod
Labels: backport, size/sm

#43768 [v16] chore: Bump Go to v1.22.5
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#43654 Move most of the service.Connector functionality into methods
  integration/instance_test.go
  integration/integration_test.go
  lib/fixtures/keys.go
  lib/reversetunnel/agentpool.go
  lib/reversetunnel/agentpool_test.go
  lib/reversetunnel/rc_manager.go
  lib/service/connect.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/discovery.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/regular/sshserver_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: size/sm, no-changelog

#43779 [v16] Omit control plane instances from inventory list
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, backport, size/sm

#43810 fix: Bypass OS compat workflow until GLIBC is fixed
  .github/workflows/os-compatibility-test.yaml
Labels: size/sm, no-changelog

#43380 Add context around AWS join methods
  docs/pages/agents/join-services-to-your-cluster/aws-ec2.mdx
  docs/pages/agents/join-services-to-your-cluster/aws-iam.mdx
Labels: documentation, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43798 chore: Bump gcloud modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/utils/gcp/gcp.go
Labels: size/sm, no-changelog

#43785 buildbox: Update centos7 buildbox for EOL, using vault
  build.assets/Dockerfile-centos7
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43817 [v16] fix: Bypass OS compat workflow until GLIBC is fixed
  .github/workflows/os-compatibility-test.yaml
Labels: backport, size/sm, no-changelog

#43799 chore: Bump otel modules
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#43788 Add CI/CD check ensuring Terraform resources are up-to-date
  .github/workflows/lint.yaml
  Makefile
  docs/pages/reference/terraform-provider/data-sources/auth_preference.mdx
  docs/pages/reference/terraform-provider/resources/auth_preference.mdx
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#43826 [v15] fix: Bypass OS compat workflow until GLIBC is fixed
  .github/workflows/os-compatibility-test.yaml
Labels: backport, size/sm, no-changelog

#43827 [v14] fix: Bypass OS compat workflow until GLIBC is fixed
  .github/workflows/os-compatibility-test.yaml
Labels: backport, size/sm, no-changelog

#43571 [Web] Update notification card styles
  web/packages/teleport/src/Notifications/Notification.story.tsx
  web/packages/teleport/src/Notifications/Notification.tsx
  web/packages/teleport/src/Notifications/Notifications.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16

#43577 Create Bot Instances during initial bot join
  api/gen/proto/go/teleport/machineid/v1/bot_instance.pb.go
  api/proto/teleport/machineid/v1/bot_instance.proto
  constants.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/bot_test.go
  lib/auth/join.go
  lib/auth/keygen/keygen.go
  lib/auth/machineid/machineidv1/bot_instance_experiment/experiment.go
  lib/auth/machineid/machineidv1/bot_instance_service.go
  lib/services/authority.go
  lib/services/local/bot_instance.go
  lib/services/local/bot_instance_test.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/tlsca/ca.go
Labels: size/md, no-changelog

#43800 Address staticcheck false positives
  lib/srv/usermgmt.go
  lib/srv/usermgmt_other.go
Labels: size/sm, no-changelog

#43794 [v15] added audit events for discovery config actions
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/auth/discoveryconfig/discoveryconfigv1/service.go
  lib/auth/discoveryconfig/discoveryconfigv1/service_test.go
  lib/auth/grpcserver.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
Labels: audit-log, backport, size/md

#43837 [v16] buildbox: Update centos7 buildbox for EOL, using vault
  build.assets/Dockerfile-centos7
Labels: backport, size/sm, no-changelog

#43838 [v15] buildbox: Update centos7 buildbox for EOL, using vault
  build.assets/Dockerfile-centos7
Labels: backport, size/sm, no-changelog

#43805 [v16] Update Bot Terraform docs
  docs/pages/machine-id/reference.mdx
  docs/pages/reference/terraform-provider/resources/bot.mdx
  integrations/terraform/examples/resources/teleport_bot/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#43662 Implement new buttons design
  web/packages/design/src/Button/Button.jsx
  web/packages/design/src/Button/Button.test.tsx
  web/packages/design/src/Button/Button.tsx
  web/packages/design/src/Button/__snapshots__/buttons.story.test.tsx.snap
  web/packages/design/src/Button/buttons.story.test.tsx
  web/packages/design/src/Button/buttons.story.tsx
  web/packages/design/src/Button/index.ts
  web/packages/design/src/ButtonLink/ButtonLink.jsx
  web/packages/design/src/DialogConfirmation/DialogConfirmation.story.jsx
  web/packages/design/src/buttons.story.tsx
  web/packages/design/src/index.ts
  web/packages/design/src/theme/themes/bblpTheme.ts
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
  web/packages/design/src/theme/themes/types.ts
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/__snapshots__/ResourceList.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/RequestDelete/__snapshots__/RequestDelete.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/RequestReview/__snapshots__/RequestReview.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/__snapshots__/RequestView.story.test.tsx.snap
  web/packages/shared/components/AwsLaunchButton/AwsLaunchButton.tsx
  web/packages/shared/components/ButtonSso/ButtonSso.tsx
  web/packages/shared/components/FormPassword/__snapshots__/FormPassword.test.tsx.snap
  web/packages/shared/components/MenuLogin/MenuLogin.tsx
  web/packages/shared/components/TextSelectCopy/__snapshots__/TextSelectCopy.story.test.tsx.snap
  web/packages/shared/components/TextSelectCopy/__snapshots__/TextSelectCopyMulti.story.test.tsx.snap
  web/packages/teleport/src/AccessRequests/__snapshots__/AccessRequests.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentBlank/__snapshots__/DocumentBlank.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/Kubes/ConnectDialog/__snapshots__/ConnectDialog.story.test.tsx.snap
  web/packages/teleport/src/LocksV2/NewLock/ResourceList/Logins.tsx
  web/packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
  web/packages/teleport/src/Recordings/RecordingsList.tsx
  web/packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
  web/packages/teleport/src/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap
  web/packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
  web/packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
  web/packages/teleport/src/Welcome/NewCredentials/__snapshots__/NewCredentials.story.test.tsx.snap
  web/packages/teleport/src/components/AgentButtonAdd/__snapshots__/AgentButtonAdd.story.test.tsx.snap
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
  web/packages/teleport/src/components/ReAuthenticate/__snapshots__/ReAuthenticate.story.test.tsx.snap
  web/packages/teleport/src/components/RecoveryCodes/__snapshots__/RecoveryCodes.story.test.tsx.snap
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
Labels: ui, size/md, no-changelog

#43542 [v15] Add plugin status details proto for Entra ID
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/types.pb.go
Labels: backport, size/sm, no-changelog

#43404 RFD 177: Upgrade JS package manager
  rfd/0177-upgrade-js-package-manager.md
Labels: rfd, size/md, no-changelog

#43855 Add missing license header to make linter happy
  web/packages/design/src/Button/buttons.story.test.tsx
Labels: ui, size/sm, no-changelog

#43854 Move embedded tbot out of the operator for reuse by other integrations
  integrations/lib/embeddedtbot/bot.go
  integrations/lib/embeddedtbot/bot_test.go
  integrations/lib/embeddedtbot/config.go
  integrations/operator/main.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43849 convert db lib to use slog, part 2
  lib/srv/db/cassandra/engine.go
  lib/srv/db/clickhouse/engine.go
  lib/srv/db/clickhouse/engine_native.go
  lib/srv/db/common/autousers.go
  lib/srv/db/common/databaseobjectimportrule/apply.go
  lib/srv/db/common/databaseobjectimportrule/apply_test.go
  lib/srv/db/common/engines.go
  lib/srv/db/common/engines_test.go
  lib/srv/db/common/session.go
  lib/srv/db/dynamodb/engine.go
  lib/srv/db/dynamodb/engine_test.go
  lib/srv/db/elasticsearch/engine.go
  lib/srv/db/elasticsearch/fuzz_test.go
  lib/srv/db/elasticsearch/util.go
  lib/srv/db/elasticsearch/util_test.go
  lib/srv/db/mongodb/autousers.go
  lib/srv/db/mongodb/autousers_admin.go
  lib/srv/db/mongodb/connect.go
  lib/srv/db/mongodb/engine.go
  lib/srv/db/mongodb/engine_test.go
  lib/srv/db/mysql/autousers.go
  lib/srv/db/mysql/autousers_test.go
  lib/srv/db/mysql/engine.go
  lib/srv/db/mysql/gcp.go
  lib/srv/db/mysql/gcp_test.go
  lib/srv/db/opensearch/engine.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/users.go
  lib/srv/db/redis/cmds.go
  lib/srv/db/redis/engine.go
  lib/srv/db/server.go
  lib/srv/db/snowflake/engine.go
  lib/srv/db/spanner/engine.go
  lib/srv/db/spanner/grpcserver.go
  lib/srv/db/spanner/interceptors.go
  lib/srv/db/sqlserver/engine.go
  lib/srv/db/sqlserver/engine_test.go
Labels: database-access, size/sm, no-changelog, backport/branch/v16

#43540 [v16] Add plugin status details proto for Entra ID
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/types.pb.go
Labels: backport, size/sm, no-changelog

#43745 Web: Process SAML IdP service provider preset value in Apps type
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/services/apps/apps.test.ts
  web/packages/teleport/src/services/apps/makeApps.ts
  web/packages/teleport/src/services/apps/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43851 [v16] Remove `buffer` dependency from web terminal
  web/packages/teleport/src/lib/term/protobuf.test.ts
  web/packages/teleport/src/lib/term/protobuf.ts
Labels: ui, backport, size/sm, no-changelog

#43852 [v15] Remove `buffer` dependency from web terminal
  web/packages/teleport/src/lib/term/protobuf.test.ts
  web/packages/teleport/src/lib/term/protobuf.ts
Labels: ui, backport, size/sm, no-changelog

#43853 [v14] Remove `buffer` dependency from web terminal
  web/packages/teleport/src/lib/term/protobuf.test.ts
  web/packages/teleport/src/lib/term/protobuf.ts
Labels: ui, backport, size/sm, no-changelog

#43874 Pass a client cert getter through auth.TLSServer and plugins
  lib/auth/helpers.go
  lib/auth/middleware.go
  lib/plugin/registry.go
  lib/service/service.go
Labels: size/sm, no-changelog

#43804 Add the device assertion protos
  api/gen/proto/go/teleport/devicetrust/v1/assert.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/authenticate_challenge.pb.go
  api/gen/proto/go/teleport/devicetrust/v1/devicetrust_service.pb.go
  api/proto/teleport/devicetrust/v1/assert.proto
  api/proto/teleport/devicetrust/v1/authenticate_challenge.proto
  api/proto/teleport/devicetrust/v1/devicetrust_service.proto
  gen/proto/ts/teleport/devicetrust/v1/assert_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/authenticate_challenge_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.ts
Labels: size/sm, no-changelog

#43859 [v16] Move embedded tbot out of the operator for reuse by other integrations
  integrations/lib/embeddedtbot/bot.go
  integrations/lib/embeddedtbot/bot_test.go
  integrations/lib/embeddedtbot/config.go
  integrations/operator/main.go
Labels: backport, size/sm, no-changelog

#43858 [v15] Move embedded tbot out of the operator for reuse by other integrations
  integrations/lib/embeddedtbot/bot.go
  integrations/lib/embeddedtbot/bot_test.go
  integrations/lib/embeddedtbot/config.go
  integrations/operator/main.go
Labels: backport, size/sm, no-changelog

#43850 Clean up styles config
  tsconfig.json
  web/@types/styled-components.d.ts
  web/packages/design/@types/styled-system.d.ts
  web/packages/teleport/src/components/Layout/Layout.jsx
  web/packages/teleterm/src/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43857 Add fakejoin.KubernetesSigner test helper
  integrations/lib/testing/fakejoin/kubesigner.go
  lib/kubernetestoken/token_validator.go
  lib/kubernetestoken/token_validator_test.go
Labels: kubernetes-access, size/md, no-changelog, backport/branch/v15, backport/branch/v16

#43825 docs: search_as_roles only supports literals
  docs/pages/access-controls/access-requests/access-request-configuration.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43879 [v15] Add fakejoin.KubernetesSigner test helper
  integrations/lib/testing/fakejoin/kubesigner.go
  lib/kubernetestoken/token_validator.go
  lib/kubernetestoken/token_validator_test.go
Labels: kubernetes-access, backport, size/md, no-changelog

#43878 [v16] Add fakejoin.KubernetesSigner test helper
  integrations/lib/testing/fakejoin/kubesigner.go
  lib/kubernetestoken/token_validator.go
  lib/kubernetestoken/token_validator_test.go
Labels: kubernetes-access, backport, size/md, no-changelog

#43872 Web UI: saml service provider resource type and type refactoring
  web/packages/teleport/src/Discover/SelectResource/resourcesE.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/services/apps/types.ts
  web/packages/teleport/src/services/samlidp/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43870 deprecate unused CertAuthority fields
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43881 [v15] docs: search_as_roles only supports literals
  docs/pages/access-controls/access-requests/access-request-configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#43880 [v16] docs: search_as_roles only supports literals
  docs/pages/access-controls/access-requests/access-request-configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#43763 [v16] docs: remove tsh recording exports
  docs/pages/desktop-access/reference/sessions.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#43882 [v14] docs: search_as_roles only supports literals
  docs/pages/access-controls/access-requests/access-request-configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#43861 Discovery Config Status: allow for other Fetchers to contribute to the global Status
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/access_graph_test.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/status.go
Labels: size/sm, discovery, no-changelog, backport/branch/v16

#43633 [v14] kube: resolve Kubernetes cluster domain
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/templates/deployment.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/values.yaml
  lib/services/app.go
  lib/services/app_test.go
  lib/srv/discovery/fetchers/kube_services.go
Labels: documentation, helm, backport, size/sm, discovery

#43463 Machine ID: Bot Instance heartbeating
  lib/auth/machineid/machineidv1/bot_instance_service.go
  lib/auth/machineid/machineidv1/bot_instance_service_test.go
  lib/tbot/service_heartbeat_test.go
  lib/tbot/service_heatbeat.go
  lib/tbot/tbot.go
Labels: size/md, no-changelog

#43908 [v15] Clean up styles config
  package.json
  tsconfig.json
  web/packages/teleport/src/components/Layout/Layout.jsx
  web/packages/teleterm/src/types.ts
Labels: ui, backport, size/sm, no-changelog

#43912 Remove redundant creation of channel in runOnInterval helper
  lib/tbot/loop.go
Labels: machine-id, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43910 [v16] Remove unused JS dependencies
  web/packages/build/bin/g-build.js
  web/packages/build/bin/g-start.js
  web/packages/build/devserver/index.js
  web/packages/build/devserver/initCompiler.js
  web/packages/build/devserver/modifyResponse.js
  web/packages/build/package.json
  web/packages/build/webpack/webpack.base.js
  web/packages/build/webpack/webpack.dev.config.js
  web/packages/build/webpack/webpack.prod.config.js
  web/packages/design/package.json
  web/packages/design/src/.storybook/config.js
  web/packages/design/src/.storybook/webpack.config.js
  web/packages/design/src/DraggableList/DraggableList.tsx
  web/packages/design/src/DraggableList/index.ts
  web/packages/e-imports/package.json
  web/packages/shared/package.json
  web/packages/teleport/package.json
  web/packages/teleport/webpack.dev.config.js
  web/packages/teleport/webpack.prod.config.js
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#43907 [v16] Clean up styles config
  package.json
  tsconfig.json
  web/packages/teleport/src/components/Layout/Layout.jsx
  web/packages/teleterm/src/types.ts
Labels: ui, backport, size/sm, no-changelog

#43791 Update Event Handler guides to correctly configure Machine ID
  docs/pages/includes/plugins/rbac-impersonate-event-handler-machine-id.mdx
  docs/pages/includes/plugins/rbac-impersonate-event-handler.mdx
  docs/pages/management/export-audit-events/datadog.mdx
  docs/pages/management/export-audit-events/elastic-stack.mdx
  docs/pages/management/export-audit-events/fluentd.mdx
  docs/pages/management/export-audit-events/panther.mdx
  docs/pages/management/export-audit-events/splunk.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43919 [v14] Update electron to 31.1.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#43832 [docs] remove iam user instructions
  docs/pages/database-access/enroll-aws-databases/aws-cross-account.mdx
  docs/pages/database-access/enroll-aws-databases/redshift-serverless.mdx
  docs/pages/database-access/reference/aws.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43731 [v14] [docs] update discovery config references
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/kubernetes-access/discovery.mdx
Labels: documentation, backport, size/sm, no-changelog

#43845 Always use PEM PKIX DER representation of public keys for BotInstances
  api/gen/proto/go/teleport/machineid/v1/bot_instance.pb.go
  api/proto/teleport/machineid/v1/bot_instance.proto
  lib/auth/bot.go
  lib/auth/join.go
Labels: size/sm, no-changelog

#43149 [docs] add database discovery overview
  docs/config.json
  docs/pages/auto-discovery/databases.mdx
  docs/pages/auto-discovery/databases/aws.mdx
  docs/pages/auto-discovery/kubernetes.mdx
  docs/pages/auto-discovery/kubernetes/aws.mdx
  docs/pages/auto-discovery/kubernetes/azure.mdx
  docs/pages/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/database-access/enroll-azure-databases.mdx
  docs/pages/includes/discovery/database-service-troubleshooting.mdx
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/includes/discovery/discovery-group.mdx
  docs/pages/includes/discovery/discovery-service-troubleshooting.mdx
  docs/pages/includes/discovery/kubernetes-service-troubleshooting.mdx
  docs/pages/includes/discovery/step-description.mdx
  docs/pages/includes/discovery/troubleshooting.mdx
Labels: documentation, size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43923 [v15] [docs] remove iam user instructions
  docs/pages/database-access/enroll-aws-databases/aws-cross-account.mdx
  docs/pages/database-access/enroll-aws-databases/redshift-serverless.mdx
  docs/pages/database-access/reference/aws.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
Labels: documentation, backport, size/sm, no-changelog

#43922 [v16] [docs] remove iam user instructions
  docs/pages/database-access/enroll-aws-databases/aws-cross-account.mdx
  docs/pages/database-access/enroll-aws-databases/redshift-serverless.mdx
  docs/pages/database-access/reference/aws.mdx
  docs/pages/includes/database-access/aws-bootstrap.mdx
Labels: documentation, backport, size/sm, no-changelog

#43866 helm: Apply extraLabels to post-delete hooks in teleport-kube-agent chart
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: helm, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43807 Add default value for static ui config
  lib/config/configuration.go
  lib/config/configuration_test.go
Labels: backport-required, size/sm, backport/branch/v16

#43729 [v16] [docs] update discovery config references
  docs/pages/auto-discovery/kubernetes.mdx
  docs/pages/includes/discovery/discovery-config.yaml
Labels: documentation, backport, size/sm, no-changelog

#43730 [v15] [docs] update discovery config references
  docs/pages/auto-discovery/kubernetes.mdx
  docs/pages/includes/discovery/discovery-config.yaml
Labels: documentation, backport, size/sm, no-changelog

#43931 [v15] helm: Apply extraLabels to post-delete hooks in teleport-kube-agent chart
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/sm

#43933 [v14] helm: Apply extraLabels to post-delete hooks in teleport-kube-agent chart
  docs/pages/reference/helm-reference/teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/sm

#43778 [v15] Omit control plane instances from inventory list
  docs/pages/upgrading/automatic-agent-updates.mdx
  docs/pages/upgrading/reference.mdx
  tool/tctl/common/inventory_command.go
Labels: documentation, tctl, backport, size/sm

#43932 [v16] helm: Apply extraLabels to post-delete hooks in teleport-kube-agent chart
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/.lint/extra-labels.yaml
  examples/chart/teleport-kube-agent/templates/delete_hook.yaml
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/sm

#43590 event-handler chart updates
  examples/chart/event-handler/templates/configmap.yaml
  examples/chart/event-handler/values.schema.json
  examples/chart/event-handler/values.yaml
Labels: helm, size/sm, backport/branch/v15, backport/branch/v16

#43834 update AWS OIDC database service task IAM permissions
  lib/integrations/awsoidc/clientsv1_test.go
  lib/integrations/awsoidc/deployservice_iam_config.go
  lib/integrations/awsoidc/deployservice_iam_config_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43902 [v14] buildbox: Update centos7 buildbox for EOL, using vault
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-fips
Labels: backport, size/sm, no-changelog

#43626 Add /etc/default/teleport as EnvironmentFile to Teleport AMIs
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
Labels: terraform-deployment-examples, ami, size/sm, backport/branch/v14, backport/branch/v15, backport/branch/v16

#43462 [sec_scan][1] Add `teleport.access_graph.v1.SecretsScannerService`
  api/gen/proto/go/teleport/accessgraph/v1/authorized_key.pb.go
  api/gen/proto/go/teleport/accessgraph/v1/private_key.pb.go
  api/gen/proto/go/teleport/accessgraph/v1/secrets_service.pb.go
  api/gen/proto/go/teleport/accessgraph/v1/secrets_service_grpc.pb.go
  api/proto/teleport/access_graph/v1/authorized_key.proto
  api/proto/teleport/access_graph/v1/private_key.proto
  api/proto/teleport/access_graph/v1/secrets_service.proto
  buf.yaml
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43467 [sec_scan][2] expose `ssh_scan_enabled` in `AccessGraphConfig` response
  api/gen/proto/go/teleport/clusterconfig/v1/access_graph.pb.go
  api/proto/teleport/clusterconfig/v1/access_graph.proto
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43486 fix: fix `nextKey` values when using multiple prefixes
  lib/services/local/generic/generic.go
  lib/services/local/generic/generic_test.go
  lib/services/local/generic/generic_wrapper.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43468 [sec_scan][3] add `PrivateKey`, `AuthorizedKey` and `Device` to Access Graph resources
  gen/proto/go/accessgraph/v1alpha/resources.pb.go
  proto/accessgraph/v1alpha/resources.proto
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43918 [v15] Update electron to 31.1.0
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#43423 Teleport install command for discovery agents (go)
  api/types/constants.go
  lib/srv/server/installer/autodiscover.go
  lib/srv/server/installer/autodiscover_test.go
  lib/srv/server/installer/defaultinstallers.go
  lib/utils/packagemanager/apt.go
  lib/utils/packagemanager/distro_info.go
  lib/utils/packagemanager/package_metadata.go
  lib/utils/packagemanager/system_binaries.go
  lib/utils/packagemanager/yum.go
  lib/utils/packagemanager/zypper.go
  tool/teleport/common/install.go
  tool/teleport/common/teleport.go
Labels: size/xl, no-changelog, backport/branch/v15, backport/branch/v16

#43920 [v15] Remove redundant creation of channel in runOnInterval helper
  lib/tbot/loop.go
Labels: backport, machine-id, size/sm, no-changelog

#43921 [v16] Remove redundant creation of channel in runOnInterval helper
  lib/tbot/loop.go
Labels: backport, machine-id, size/sm, no-changelog

#43847 Export configured Vite plugins from `packages/build`
  web/packages/build/vite/config.ts
  web/packages/build/vite/csp.ts
  web/packages/build/vite/react.mjs
  web/packages/build/vite/tsconfigPaths.mjs
  web/packages/teleterm/electron.vite.config.mts
Labels: ui, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#43877 Ensure tbot compiles on windows
  .github/workflows/build-windows.yaml
  Makefile
  lib/tbot/botfs/botfs.go
  lib/tbot/botfs/fs_linux.go
  lib/tbot/botfs/fs_unix.go
  lib/tbot/botfs/fs_windows.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_ssh_multiplexer_unix.go
  lib/tbot/service_ssh_multiplexer_windows.go
  tool/tbot/main.go
  tool/tbot/signals_unix.go
  tool/tbot/signals_windows.go
Labels: machine-id, size/md

#43949 Fix import order for darwin-only vnet file
  lib/vnet/setup_nodaemon_darwin.go
Labels: size/sm, no-changelog

#43939 [v15] event-handler chart updates
  examples/chart/event-handler/templates/configmap.yaml
  examples/chart/event-handler/values.schema.json
  examples/chart/event-handler/values.yaml
Labels: helm, backport, size/sm

#43938 [v16] event-handler chart updates
  examples/chart/event-handler/templates/configmap.yaml
  examples/chart/event-handler/values.schema.json
  examples/chart/event-handler/values.yaml
Labels: helm, backport, size/sm

#43846 Remove `aws-sdk-go/aws/awsutil` package
  lib/integrations/awsoidc/deployservice_update.go
  lib/integrations/awsoidc/deployservice_update_test.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43959 [v16] Ensure tbot compiles on windows
  .github/workflows/build-windows.yaml
  Makefile
  lib/tbot/botfs/botfs.go
  lib/tbot/botfs/fs_linux.go
  lib/tbot/botfs/fs_unix.go
  lib/tbot/botfs/fs_windows.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_ssh_multiplexer_unix.go
  lib/tbot/service_ssh_multiplexer_windows.go
  tool/tbot/main.go
  tool/tbot/signals_unix.go
  tool/tbot/signals_windows.go
Labels: backport, machine-id, size/md

#43963 [v16] Remove `aws-sdk-go/aws/awsutil` package
  lib/integrations/awsoidc/deployservice_update.go
  lib/integrations/awsoidc/deployservice_update_test.go
Labels: backport, size/sm, no-changelog

#43961 [v15] Add /etc/default/teleport as EnvironmentFile to Teleport AMIs
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
Labels: backport, size/sm

#43896 Improve error handling for shared directory errors
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/filesystem.rs
  web/packages/teleport/src/lib/tdp/client.ts
Labels: ui, rdp, desktop-access, size/sm, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43960 [v14] Add /etc/default/teleport as EnvironmentFile to Teleport AMIs
  assets/aws/files/system/teleport-acm.service
  assets/aws/files/system/teleport-auth.service
  assets/aws/files/system/teleport-proxy-acm.service
  assets/aws/files/system/teleport-proxy.service
  assets/aws/files/system/teleport.service
Labels: backport, size/sm

#42932 Surface entitlements to auth
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  entitlements/entitlements.go
  integrations/operator/controllers/resources/setup.go
  integrations/terraform/testlib/device_trust_test.go
  integrations/terraform/testlib/loginrule_test.go
  integrations/terraform/testlib/oidc_connector_test.go
  integrations/terraform/testlib/saml_connector_test.go
  lib/auth/auth.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/utils_testing.go
  lib/modules/modules.go
  lib/modules/modules_test.go
  lib/service/kubernetes.go
  lib/srv/discovery/access_graph.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
Labels: kubernetes-access, size/sm, size/md, discovery, no-changelog

#43950 [v16] Bump JS deps
  jest.config.js
  package.json
  web/packages/build/package.json
  web/packages/design/src/ButtonLink/ButtonLink.jsx
  web/packages/e-imports/package.json
  web/packages/shared/package.json
  web/packages/shared/setupTests.tsx
  web/packages/teleport/package.json
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/components/LogoHero/LogoHero.tsx
  web/packages/teleterm/package.json
  web/packages/teleterm/src/services/tshd/cloneableClient.ts
  yarn.lock
Labels: ui, backport, size/md, no-changelog

#43948 [v16] Teleport install command for discovery agents (go)
  api/types/constants.go
  lib/srv/server/installer/autodiscover.go
  lib/srv/server/installer/autodiscover_test.go
  lib/srv/server/installer/defaultinstallers.go
  lib/utils/packagemanager/apt.go
  lib/utils/packagemanager/distro_info.go
  lib/utils/packagemanager/package_metadata.go
  lib/utils/packagemanager/system_binaries.go
  lib/utils/packagemanager/yum.go
  lib/utils/packagemanager/zypper.go
  tool/teleport/common/install.go
  tool/teleport/common/teleport.go
Labels: backport, size/xl, no-changelog

#43964 [v15] Remove `aws-sdk-go/aws/awsutil` package
  lib/integrations/awsoidc/deployservice_update.go
  lib/integrations/awsoidc/deployservice_update_test.go
Labels: backport, size/sm, no-changelog

#43945 Update electron-builder to 25.0.0-alpha.11
  package.json
  web/packages/build/package.json
  web/packages/teleterm/electron-builder-config.js
  yarn.lock
Labels: ui, size/md, backport/branch/v14, no-changelog, backport/branch/v15, backport/branch/v16

#43904 [v16] Discovery Config Status: allow for other Fetchers to contribute to the global Status
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/access_graph_test.go
  lib/srv/discovery/discovery.go
  lib/srv/discovery/status.go
Labels: backport, size/md, discovery, no-changelog

#43955 [v16] Record PostgreSQL queries/command results
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/srv/db/access_test.go
  lib/srv/db/audit_test.go
  lib/srv/db/common/audit.go
  lib/srv/db/postgres/engine.go
  lib/srv/db/postgres/test.go
Labels: audit-log, database-access, backport, size/md

#43967 [v16] Add quicker retry to get kube cluster details if the cluster was offline
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/cluster_details_test.go
  lib/kube/proxy/kube_creds.go
  lib/kube/proxy/scheme_test.go
Labels: kubernetes-access, backport, size/md
