Repository gravitational/teleport, pull requests merged in 2024-02, with the labels that each got.

#37630 Release 15.0.0
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  docs/cspell.json
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/md, no-changelog

#37586 [v15] Fixes Okta plugin settings validation
  api/types/plugin.go
Labels: backport, size/sm, no-changelog

#37448 [v13] Fix last good identity not being used by tbot if token is not configured
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm

#37563 Add `UserName` to `BotJoin` event
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/auth/join.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  proto/prehog/v1alpha/teleport.proto
Labels: machine-id, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37605 Tests for connection resumption
  lib/resumption/client.go
  lib/resumption/resumable_test.go
  lib/resumption/resumption_test.go
Labels: size/md, no-changelog, backport/branch/v15

#37589 chore: Remove deprecated MFA streaming methods
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/clt.go
  lib/auth/grpcserver.go
Labels: size/sm, no-changelog

#37644 [v13] Skip the RPID pre-flight check whenever possible
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm

#37643 [v14] Skip the RPID pre-flight check whenever possible
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm

#37641 [v13] Use FIDO2 touch functions to wait for touch
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm, no-changelog

#37639 [v15] Use FIDO2 touch functions to wait for touch
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm, no-changelog

#37124 Update the index page for v15
  docs/img/add-resources.png
  docs/pages/index.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#37370 Update the edition comparison chart
  docs/pages/includes/edition-comparison.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#37636 Remove deprecated Bot API methods
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/machineid/machineidv1/bot_service_legacy.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/tbot_test.go
  lib/tbot/testhelpers/srv.go
  tool/tctl/common/bots_command.go
Labels: tctl, size/sm, no-changelog

#37640 [v14] Use FIDO2 touch functions to wait for touch
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm, no-changelog

#37642 [v15] Skip the RPID pre-flight check whenever possible
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/sm

#34940 [docs] IAM-auth-as-IAM-roles for Redshift
  docs/img/database-access/guides/create-redshift-iam-role-policy.png
  docs/pages/database-access/guides/postgres-redshift.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#36845 Add [disabled] Bots list view
  lib/web/apiserver.go
  lib/web/machineid.go
  lib/web/machineid_test.go
  web/packages/design/src/Icon/Icons/Bots.tsx
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/Bots/DeleteBot.test.tsx
  web/packages/teleport/src/Bots/DeleteBot.tsx
  web/packages/teleport/src/Bots/List/ActionCell.tsx
  web/packages/teleport/src/Bots/List/BotList.test.tsx
  web/packages/teleport/src/Bots/List/BotList.tsx
  web/packages/teleport/src/Bots/List/Bots.story.tsx
  web/packages/teleport/src/Bots/List/Bots.test.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Bots/List/index.ts
  web/packages/teleport/src/Bots/fixtures/index.ts
  web/packages/teleport/src/Bots/index.ts
  web/packages/teleport/src/Bots/types.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/bot/consts.ts
  web/packages/teleport/src/services/bot/index.ts
  web/packages/teleport/src/services/bot/types.ts
  web/packages/teleport/src/types.ts
Labels: ui, size/lg, no-changelog

#37647 fix: Do not wrap io.EOF intercepted by stream Sends
  api/utils/grpc/interceptors/errors.go
  api/utils/grpc/interceptors/errors_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37662 [v15] fix: Do not wrap io.EOF intercepted by stream Sends
  api/utils/grpc/interceptors/errors.go
  api/utils/grpc/interceptors/errors_test.go
Labels: backport, size/sm

#37562 [v15] Add in Okta access list sync audit event.
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/events/api.go
  lib/events/codes.go
  lib/events/dynamic.go
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, audit-log, backport, size/md, no-changelog

#37631 Add MFA for admin actions docs
  docs/config.json
  docs/pages/access-controls/guides/mfa-for-admin-actions.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/includes/access-control-guides.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15

#37593 Fix list all access list members/reviews pagination.
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/generic/generic.go
  lib/services/local/generic/generic_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37333 Add buttons to download and copy to clipboard content to `TextEditor`
  web/packages/shared/components/TextEditor/TextEditor.jsx
  web/packages/shared/components/TextEditor/TextEditor.story.tsx
  web/packages/shared/components/TextEditor/TextEditor.test.tsx
  web/packages/shared/utils/download.ts
Labels: ui, size/md, no-changelog

#37665 [v15] Update the index page for v15
  docs/img/add-resources.png
  docs/pages/index.mdx
Labels: documentation, backport, size/sm, no-changelog

#37666 [v15] Update the edition comparison chart
  docs/pages/includes/edition-comparison.mdx
Labels: documentation, backport, size/sm, no-changelog

#36925 [v13] fix: Do not attempt relogin on remote BadParameter errors
  api/client/client_test.go
  api/utils/grpc/interceptors/errors.go
  api/utils/grpc/interceptors/errors_test.go
  lib/auth/grpcserver_test.go
  lib/auth/tls_test.go
  lib/client/api.go
Labels: backport, size/sm

#37420 [v15] Edit version-agnostic pages for v15
  CHANGELOG.md
  docs/cspell.json
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/lg, no-changelog

#36924 [v14] fix: Do not attempt relogin on remote BadParameter errors
  api/client/client_test.go
  api/utils/grpc/interceptors/errors.go
  api/utils/grpc/interceptors/errors_test.go
  lib/auth/grpcserver_test.go
  lib/auth/tls_test.go
  lib/client/api.go
Labels: backport, size/sm

#37663 Replace kustomize dependency with fork.
  go.mod
  go.sum
Labels: size/sm, no-changelog, backport/branch/v15

#37671 [v15] Add MFA for admin actions docs
  docs/config.json
  docs/pages/access-controls/guides/mfa-for-admin-actions.mdx
  docs/pages/access-controls/guides/webauthn.mdx
  docs/pages/includes/access-control-guides.mdx
Labels: documentation, backport, size/md, no-changelog

#37654 [v15] [docs] IAM-auth-as-IAM-roles for Redshift
  docs/img/database-access/guides/create-redshift-iam-role-policy.png
  docs/pages/database-access/guides/postgres-redshift.mdx
Labels: documentation, backport, size/sm, no-changelog

#37526 Removed old Drone pipelines
  .drone.yml
  dronegen/buildbox.go
  dronegen/common.go
  dronegen/container_image_triggers.go
  dronegen/container_images.go
  dronegen/container_images_repos.go
  dronegen/container_images_testing.go
  dronegen/main.go
  dronegen/misc.go
Labels: size/sm, no-changelog

#37686 [v15] Replace kustomize dependency with fork.
  go.mod
  go.sum
Labels: backport, size/sm, no-changelog

#37689 [v13] Fix oversized report submission
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
Labels: backport, size/sm

#37687 [v15] Fix oversized report submission
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
Labels: backport, size/sm

#37690 [v12] Fix oversized report submission
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
Labels: backport, size/sm

#37688 [v14] Fix oversized report submission
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
Labels: backport, size/sm

#37673 [v15] Fix list all access list members/reviews pagination.
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/generic/generic.go
  lib/services/local/generic/generic_test.go
Labels: backport, size/md

#37676 Post-major version release activities
  .drone.yml
  docker/teleport-lab.yml
  docker/teleport-quickstart.yml
  docs/postrelease.md
  docs/preflight.md
  dronegen/container_images.go
Labels: documentation, size/sm, no-changelog

#37674 [v14] Fix list all access list members/reviews pagination.
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/generic/generic.go
  lib/services/local/generic/generic_test.go
Labels: backport, size/md

#37697 [v15] Web: Add outline-info Alert.tsx + move navigation code for general use
  web/packages/design/src/Alert/Alert.jsx
  web/packages/design/src/Alert/Alert.story.js
  web/packages/teleport/src/Discover/Discover.tsx
  web/packages/teleport/src/Discover/Navigation/Navigation.tsx
  web/packages/teleport/src/Discover/Navigation/StepItem.tsx
  web/packages/teleport/src/Discover/flow.test.tsx
  web/packages/teleport/src/Discover/flow.tsx
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.story.tsx
  web/packages/teleport/src/components/StepNavigation/StepNavigation.tsx
  web/packages/teleport/src/components/Wizard/Navigation/Bullet.tsx
  web/packages/teleport/src/components/Wizard/Navigation/Navigation.story.tsx
  web/packages/teleport/src/components/Wizard/Navigation/Navigation.test.tsx
  web/packages/teleport/src/components/Wizard/Navigation/Navigation.tsx
  web/packages/teleport/src/components/Wizard/Navigation/Shared.tsx
  web/packages/teleport/src/components/Wizard/Navigation/StepItem.tsx
  web/packages/teleport/src/components/Wizard/Navigation/StepList.tsx
  web/packages/teleport/src/components/Wizard/Navigation/index.ts
  web/packages/teleport/src/components/Wizard/flow.test.tsx
  web/packages/teleport/src/components/Wizard/flow.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm

#37660 Unmarshal and compare user objects in CompareAndSwapUser
  lib/services/local/export_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
Labels: size/sm, backport/branch/v15

#37646 Clean up the account settings code from the legacy files
  web/packages/teleport/src/Account/Account.story.tsx
  web/packages/teleport/src/Account/Account.test.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/AccountNew.story.tsx
  web/packages/teleport/src/Account/AccountNew.ts
  web/packages/teleport/src/Account/AccountNew.tsx
  web/packages/teleport/src/Account/ChangePassword/ChangePassword.story.tsx
  web/packages/teleport/src/Account/ChangePassword/ChangePassword.tsx
  web/packages/teleport/src/Account/ChangePassword/index.ts
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.story.test.tsx
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.test.tsx
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.tsx
  web/packages/teleport/src/Account/ManageDevices/__snapshots__/ManageDevices.story.test.tsx.snap
  web/packages/teleport/src/features.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v15

#37703 [v15] Unmarshal and compare user objects in CompareAndSwapUser
  lib/services/local/export_test.go
  lib/services/local/users.go
  lib/services/local/users_test.go
Labels: backport, size/sm

#37710 fix: Correctly handle non-registered U2F keys
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: size/md, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37675 [v13] Fix list all access list members/reviews pagination.
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/generic/generic.go
  lib/services/local/generic/generic_test.go
Labels: backport, size/md

#37709 [Web] Change Assist icon in top bar
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ChatCircleSparkle.tsx
  web/packages/design/src/Icon/assets/ChatCircleSparkle.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/TopBar/TopBar.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v15

#37724 Add the deprecated option GenerateUserSingleUseCerts
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
Labels: size/sm, no-changelog

#37725 [v15] [Web] Change Assist icon in top bar
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ChatCircleSparkle.tsx
  web/packages/design/src/Icon/assets/ChatCircleSparkle.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/TopBar/TopBar.tsx
Labels: ui, backport, size/md, no-changelog

#37682 [v15] docs: move team to cloud uninstall section instructions
  docs/pages/management/admin/uninstall-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#37683 [v14] docs: move team to cloud uninstall section instructions
  docs/pages/management/admin/uninstall-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#37684 [v13] docs: move team to cloud uninstall section instructions
  docs/pages/management/admin/uninstall-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#37655 integrations/operator: Fix the operator deleting unowned resources
  integrations/operator/controllers/resources/teleport_reconciler.go
  integrations/operator/controllers/resources/teleport_reconciler_test.go
Labels: bug, size/md, kube-operator, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37506 [v14] AWS OIDC: remove config dependency in ExternalAuditStorage
  lib/config/configuration.go
  lib/integrations/awsoidc/externalauditstorage_iam_config.go
  lib/integrations/awsoidc/externalauditstorage_iam_config_test.go
  lib/service/servicecfg/externalauditstorage.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#37721 [v13] fix: Correctly handle non-registered U2F keys
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/md

#37722 [v14] fix: Correctly handle non-registered U2F keys
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/md

#37717 [v15] Clean up the account settings code from the legacy files
  web/packages/teleport/src/Account/Account.story.tsx
  web/packages/teleport/src/Account/Account.test.tsx
  web/packages/teleport/src/Account/Account.tsx
  web/packages/teleport/src/Account/AccountNew.story.tsx
  web/packages/teleport/src/Account/AccountNew.ts
  web/packages/teleport/src/Account/AccountNew.tsx
  web/packages/teleport/src/Account/ChangePassword/ChangePassword.story.tsx
  web/packages/teleport/src/Account/ChangePassword/ChangePassword.tsx
  web/packages/teleport/src/Account/ChangePassword/index.ts
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.story.test.tsx
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.test.tsx
  web/packages/teleport/src/Account/ManageDevices/ManageDevices.tsx
  web/packages/teleport/src/Account/ManageDevices/__snapshots__/ManageDevices.story.test.tsx.snap
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#37749 Temporarily disable AWS Database E2E tests
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37753 [v15] Temporarily disable AWS Database E2E tests
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: backport, size/sm, no-changelog

#37733 docs: include all values for proxyListenerMode helm value
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37754 [v14] Temporarily disable AWS Database E2E tests
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: no-changelog

#37505 [v15] AWS OIDC: remove config dependency in ExternalAuditStorage
  lib/config/configuration.go
  lib/integrations/awsoidc/externalauditstorage_iam_config.go
  lib/integrations/awsoidc/externalauditstorage_iam_config_test.go
  lib/service/servicecfg/externalauditstorage.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#37720 [v15] fix: Correctly handle non-registered U2F keys
  lib/auth/webauthncli/fido2.go
  lib/auth/webauthncli/fido2_test.go
Labels: backport, size/md

#37758 [v13] docs: include all values for proxyListenerMode helm value
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm, no-changelog

#37757 [v14] docs: include all values for proxyListenerMode helm value
  docs/pages/reference/helm-reference/teleport-cluster.mdx
Labels: documentation, backport, size/sm, no-changelog

#37335 AWS OIDC Service: bootstrap and ListDatabases stub
  api/gen/proto/go/teleport/integration/v1/awsoidc_service.pb.go
  api/gen/proto/go/teleport/integration/v1/awsoidc_service_grpc.pb.go
  api/proto/teleport/integration/v1/awsoidc_service.proto
  lib/auth/clt.go
  lib/auth/grpcserver.go
  lib/auth/integration/integrationv1/awsoidc.go
Labels: size/md, backport/branch/v14, no-changelog, backport/branch/v15

#37765 Run check-devbox on dependabot PRs
  .github/workflows/check-devbox.yaml
Labels: size/sm, no-changelog

#37774 Revert "Temporarily disable AWS Database E2E tests (#37749)"
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: size/sm, no-changelog

#37777 [v14] Revert "Temporarily disable AWS Database E2E tests (#37754)"
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: no-changelog

#37776 [v15] Revert "Temporarily disable AWS Database E2E tests (#37753)"
  .github/workflows/aws-e2e-tests-non-root.yaml
Labels: backport, size/sm, no-changelog

#37769 Release 15.0.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm, no-changelog

#37316 Remove unused const in `auth` - TokenLenBytes
  lib/auth/auth.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37744 Remove use of `CanonicalizeHostname` in Machine ID Ansible guide
  docs/pages/machine-id/access-guides/ansible.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37579 Ensure yarn.lock is up to date, run workflows on relevant changes in root dir
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/build/scripts/yarn-install-frozen-lockfile.sh
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37508 AWS OIDC - Deploy ECS Service: increase number of replicas to 2
  lib/integrations/awsoidc/deployservice.go
Labels: size/sm, backport/branch/v14, backport/branch/v15

#37743 Don't submit add device form through the browser if validation fails
  web/packages/teleport/src/Account/ManageDevices/AddDevice/AddDevice.tsx
Labels: backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37619 Clear SAML IdP session on logout
  lib/idp/saml/session.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37786 Fix image name for Kubernetes/Machine ID guide
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15

#37800 [v13] Update xterm.js and its addons
  web/packages/teleport/package.json
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm

#37810 [v13] Ensure yarn.lock is up to date, run workflows on relevant changes in root dir
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/build/scripts/yarn-install-frozen-lockfile.sh
Labels: ui, backport, size/sm, no-changelog

#37809 [v14] Ensure yarn.lock is up to date, run workflows on relevant changes in root dir
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/build/scripts/yarn-install-frozen-lockfile.sh
Labels: ui, backport, size/sm, no-changelog

#37792 [v15] Remove use of `CanonicalizeHostname` in Machine ID Ansible guide
  docs/pages/machine-id/access-guides/ansible.mdx
Labels: documentation, backport, size/sm, no-changelog

#37799 [v14] Update xterm.js and its addons
  web/packages/teleport/package.json
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/sm

#37793 [v14] Remove use of `CanonicalizeHostname` in Machine ID Ansible guide
  docs/pages/machine-id/access-guides/ansible.mdx
Labels: documentation, backport, size/sm, no-changelog

#37264 AWS OIDC: remove config dependency in DeployService
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config_test.go
  lib/web/integrations_awsoidc.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37768 devbox: add wasm-bindgen
  devbox.json
  devbox.lock
Labels: size/sm, no-changelog

#37789 [v15] Athena Events: log execution duration
  lib/events/athena/querier.go
Labels: audit-log, backport, size/sm, no-changelog

#29678 Correct tsh join error when attempting to join a kubernetes session
  lib/client/api.go
Labels: inactive, size/sm, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37788 [v14] Athena Events: log execution duration
  lib/events/athena/querier.go
Labels: audit-log, backport, size/sm, no-changelog

#37760 [v14] spell fixes in warning/error messages
  lib/services/database.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm, no-changelog

#37759 [v15] spell fixes in warning/error messages
  lib/services/database.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm, no-changelog

#37816 [v14] AWS OIDC: remove config dependency in DeployService
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config_test.go
  lib/web/integrations_awsoidc.go
Labels: backport, size/sm, no-changelog

#37821 charts/kube-agent: support restricted PSS by default
  docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx
  examples/chart/teleport-kube-agent/tests/__snapshot__/clusterrole_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/deployment_test.yaml
  examples/chart/teleport-kube-agent/tests/job_test.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, size/sm

#37817 [v15] AWS OIDC: remove config dependency in DeployService
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config.go
  lib/integrations/awsoidc/deployserviceconfig/deployservice_config_test.go
  lib/web/integrations_awsoidc.go
Labels: backport, size/sm, no-changelog

#37824 [v13] Correct tsh join error when attempting to join a kubernetes session
  lib/client/api.go
Labels: backport, size/sm, no-changelog

#37823 [v14] Correct tsh join error when attempting to join a kubernetes session
  lib/client/api.go
Labels: backport, size/sm, no-changelog

#37829 Release 13.4.16
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  integrations/kube-agent-updater/version.go
  version.go
Labels: helm, backport, size/sm, no-changelog

#37830 Release 12.4.34
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  version.go
Labels: helm, backport, size/sm, no-changelog

#37771 Remove quiet/silent flags from authz checks
  lib/auth/assist/assistv1/service.go
  lib/auth/auth_with_roles.go
  lib/auth/discoveryconfig/discoveryconfigv1/service.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/okta/service.go
  lib/auth/trust/trustv1/service.go
  lib/auth/trust/trustv1/service_test.go
  lib/auth/userloginstate/service.go
  lib/auth/users/usersv1/service.go
  lib/auth/users/usersv1/service_test.go
  lib/authz/permissions.go
  lib/services/access_checker.go
  lib/services/role.go
  lib/services/role_test.go
  lib/services/useracl.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37804 [v14] AWS OIDC - Deploy ECS Service: increase number of replicas to 2
  lib/integrations/awsoidc/deployservice.go
Labels: backport, size/sm

#37849 [v13] chore: Bump Go to v1.21.7
  build.assets/versions.mk
Labels: size/sm

#37848 [v14] chore: Bump Go to v1.21.7
  .drone.yml
  build.assets/versions.mk
  go.mod
Labels: size/sm

#37820 [v14] clear SAML IdP session on logout
  lib/idp/saml/session.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
Labels: backport, size/md, no-changelog

#37845 chore: Bump Go toolchain to 1.22.0
  build.assets/versions.mk
  docs/config.json
  go.mod
  lib/auth/webauthn/login_test.go
Labels: documentation, size/sm

#37858 [v14] build: add --locked flag to cargo build
  Makefile
Labels: backport, size/sm, backport/branch/v13, no-changelog

#37854 chore: Bump golangci-lint to v1.56.0
  .github/workflows/lint.yaml
  .golangci.yml
  api/types/cluster_alert_test.go
  api/types/integration_test.go
  api/types/provisioning_test.go
  build.assets/Dockerfile
  lib/auth/auth_with_roles_test.go
  lib/auth/webauthn/login_test.go
  lib/integrations/awsoidc/deployservice_iam_jointoken_test.go
  lib/resumption/managedconn_test.go
  lib/services/local/access_list_test.go
  lib/services/local/presence_test.go
  lib/services/role_test.go
  lib/services/services_test.go
  lib/srv/discovery/discovery_test.go
  lib/utils/certs_test.go
  lib/web/apiserver_test.go
  lib/web/databases_test.go
  lib/web/resources_test.go
  lib/web/servers_test.go
Labels: size/sm, backport/branch/v13, discovery, backport/branch/v14, no-changelog, backport/branch/v15

#37499 memory backend atomic write impl
  lib/backend/memory/atomicwrite.go
  lib/backend/memory/atomicwrite_test.go
  lib/backend/test/atomicwrite_shim.go
Labels: size/md, no-changelog, backport/branch/v15

#37500 sqlite atomic write impl
  lib/backend/lite/atomicwrite.go
  lib/backend/lite/atomicwrite_test.go
  lib/backend/lite/lite.go
Labels: size/md, no-changelog, backport/branch/v15

#37599 postgres atomic write impl
  lib/backend/pgbk/atomicwrite.go
  lib/backend/pgbk/atomicwrite_test.go
Labels: size/md, no-changelog, backport/branch/v15

#36363 fix iterate range
  lib/backend/backend.go
  lib/backend/memory/memory_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37797 Add DatabasePermissions field to role
  api/proto/teleport/legacy/types/types.proto
  api/types/database_permissions.go
  api/types/database_permissions_test.go
  api/types/role.go
  api/types/types.pb.go
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  lib/services/access_checker.go
Labels: helm, size/md, no-changelog, backport/branch/v15

#37856 [v15] Fix wasm-pack builds
  Cargo.lock
  Makefile
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-node
  web/packages/teleport/package.json
  web/packages/teleport/src/ironrdp/Cargo.toml
Labels: ui, backport, size/sm, no-changelog

#37685 Make styled indicator position absolute
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/components/Authenticated/Authenticated.tsx
Labels: ui, backport-required, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37707 Add protos for Notifications resources and CRUD RPCs
  api/gen/proto/go/teleport/notifications/v1/notifications.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service_grpc.pb.go
  api/proto/teleport/notifications/v1/notifications.proto
  api/proto/teleport/notifications/v1/notifications_service.proto
Labels: size/md, no-changelog, backport/branch/v15

#37729 add spec section to automatic-agent update docs
  docs/pages/upgrading/self-hosted-automatic-agent-updates.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37822 [v15] Correct tsh join error when attempting to join a kubernetes session
  lib/client/api.go
Labels: backport, size/sm, no-changelog

#37805 [v15] AWS OIDC - Deploy ECS Service: increase number of replicas to 2
  lib/integrations/awsoidc/deployservice.go
Labels: backport, size/sm

#37791 [v15] Remove unused const in `auth` - TokenLenBytes
  lib/auth/auth.go
Labels: backport, size/sm, no-changelog

#37877 [v13] chore: Bump golangci-lint to v1.56.0
  .github/workflows/lint.yaml
  api/types/cluster_alert_test.go
  api/types/integration_test.go
  api/types/provisioning_test.go
  build.assets/Dockerfile
  lib/auth/auth_with_roles_test.go
  lib/integrations/awsoidc/deployservice_iam_jointoken_test.go
  lib/services/local/access_list_test.go
  lib/services/local/presence_test.go
  lib/services/role_test.go
  lib/services/services_test.go
  lib/srv/discovery/discovery_test.go
  lib/utils/certs_test.go
  lib/web/apiserver_test.go
  lib/web/databases_test.go
  lib/web/resources_test.go
  lib/web/servers_test.go
Labels: backport, size/sm, discovery, no-changelog

#37876 [v14] chore: Bump golangci-lint to v1.56.0
  .github/workflows/lint.yaml
  api/types/cluster_alert_test.go
  api/types/integration_test.go
  api/types/provisioning_test.go
  build.assets/Dockerfile
  lib/auth/auth_with_roles_test.go
  lib/integrations/awsoidc/deployservice_iam_jointoken_test.go
  lib/services/local/access_list_test.go
  lib/services/local/presence_test.go
  lib/services/role_test.go
  lib/services/services_test.go
  lib/srv/discovery/discovery_test.go
  lib/utils/certs_test.go
  lib/web/apiserver_test.go
  lib/web/databases_test.go
  lib/web/resources_test.go
  lib/web/servers_test.go
Labels: backport, size/sm, discovery, no-changelog

#37866 [v15] chore: Bump golangci-lint to v1.56.0
  .github/workflows/lint.yaml
  .golangci.yml
  api/types/cluster_alert_test.go
  api/types/integration_test.go
  api/types/provisioning_test.go
  build.assets/Dockerfile
  lib/auth/auth_with_roles_test.go
  lib/auth/webauthn/login_test.go
  lib/integrations/awsoidc/deployservice_iam_jointoken_test.go
  lib/resumption/managedconn_test.go
  lib/services/local/access_list_test.go
  lib/services/local/presence_test.go
  lib/services/role_test.go
  lib/services/services_test.go
  lib/srv/discovery/discovery_test.go
  lib/utils/certs_test.go
  lib/web/apiserver_test.go
  lib/web/databases_test.go
  lib/web/resources_test.go
  lib/web/servers_test.go
Labels: backport, size/sm, discovery, no-changelog

#37862 [v15] postgres atomic write impl
  lib/backend/pgbk/atomicwrite.go
  lib/backend/pgbk/atomicwrite_test.go
Labels: backport, size/md, no-changelog

#37815 [v15] Clear SAML IdP session on logout
  lib/idp/saml/session.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/sessions.go
Labels: backport, size/md, no-changelog

#37814 [v15] Fix image name for Kubernetes/Machine ID guide
  docs/pages/machine-id/deployment/kubernetes.mdx
Labels: documentation, backport, size/sm, no-changelog

#37520 Read the bearer token over websocket endpoints instead of query parameter
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/assistant.go
  lib/web/command.go
  lib/web/desktop.go
  lib/web/terminal.go
  lib/web/terminal_test.go
  web/packages/teleport/src/Assist/context/AssistContext.tsx
  web/packages/teleport/src/Console/DocumentSsh/TerminalAssist/TerminalAssistContext.tsx
  web/packages/teleport/src/Console/consoleContext.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/lib/AuthenticatedWebSocket.ts
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/term/tty.ts
  web/packages/teleport/src/types.ts
Labels: ui, desktop-access, size/md, backport/branch/v13, backport/branch/v14, backport/branch/v15

#37796 [v15] Ensure yarn.lock is up to date, run workflows on relevant changes in root dir
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/build/scripts/yarn-install-frozen-lockfile.sh
Labels: ui, backport, size/sm, no-changelog

#37755 Add kubeAppDiscovery bool parameters to the Discovery proto config
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: size/sm, no-changelog, backport/branch/v15

#37840 Update `cert-manager` instructions in Teleport cluster guides
  assets/loadtest/control-plane/dns/init-cert-manager.sh
  docs/pages/deploy-a-cluster/helm-deployments/aws.mdx
  docs/pages/deploy-a-cluster/helm-deployments/gcp.mdx
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#36755 RFD: Improving Password Management UX
  rfd/0159-password-status.md
Labels: rfd, size/md, no-changelog

#37837 Update Prettier to 3.2.5
  package.json
  web/packages/design/src/AnimatedProgressBar/AnimatedProgressBar.tsx
  web/packages/shared/components/AnimatedTerminal/TerminalContent.tsx
  web/packages/shared/components/ClusterDropdown/ClusterDropdown.story.tsx
  web/packages/shared/components/UnifiedResources/shared/PinButton.tsx
  web/packages/shared/components/Window/WindowComponents.tsx
  web/packages/shared/hooks/useRefClickOutside/useRefClickOutside.ts
  web/packages/teleport/src/AccessRequests/LockedAccessRequests/LockedAccessRequests.tsx
  web/packages/teleport/src/Assist/Assist.tsx
  web/packages/teleport/src/Assist/Conversation/EntryContainer.tsx
  web/packages/teleport/src/Assist/Settings/DisplaySettings.tsx
  web/packages/teleport/src/Assist/context/AssistContext.tsx
  web/packages/teleport/src/Assist/markdown.ts
  web/packages/teleport/src/Assist/types.ts
  web/packages/teleport/src/AuthConnectors/styles/AuthConnectors.styles.ts
  web/packages/teleport/src/AuthConnectors/styles/LockedFeatureContainer.styles.ts
  web/packages/teleport/src/DeviceTrust/DeviceTrustLocked.tsx
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ProxyDesktopServiceDiagram.tsx
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/WindowsComputer.tsx
  web/packages/teleport/src/Discover/Shared/HintBox.tsx
  web/packages/teleport/src/Navigation/NavigationSection.tsx
  web/packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
  web/packages/teleport/src/components/Dropdown/Dropdown.tsx
  web/packages/teleport/src/lib/term/terminal.ts
  web/packages/teleport/src/services/audit/types.ts
  web/packages/teleport/src/services/integrations/types.ts
  web/packages/teleterm/src/services/tshd/interceptors.test.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/Terminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts
  web/packages/teleterm/src/ui/Search/searchResult.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/Tabs/TabItem.tsx
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
  yarn.lock
Labels: ui, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37871 [v15] Add protos for Notifications resources and CRUD RPCs
  api/gen/proto/go/teleport/notifications/v1/notifications.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service.pb.go
  api/gen/proto/go/teleport/notifications/v1/notifications_service_grpc.pb.go
  api/proto/teleport/notifications/v1/notifications.proto
  api/proto/teleport/notifications/v1/notifications_service.proto
Labels: backport, size/md, no-changelog

#37807 docs: bump cloud version v14.3.4
  docs/config.json
Labels: documentation, size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37901 [v15] Update Prettier to 3.2.5
  package.json
  web/packages/design/src/AnimatedProgressBar/AnimatedProgressBar.tsx
  web/packages/shared/components/AnimatedTerminal/TerminalContent.tsx
  web/packages/shared/components/UnifiedResources/shared/PinButton.tsx
  web/packages/shared/components/Window/WindowComponents.tsx
  web/packages/shared/hooks/useRefClickOutside/useRefClickOutside.ts
  web/packages/teleport/src/AccessRequests/LockedAccessRequests/LockedAccessRequests.tsx
  web/packages/teleport/src/Assist/Assist.tsx
  web/packages/teleport/src/Assist/Conversation/EntryContainer.tsx
  web/packages/teleport/src/Assist/Settings/DisplaySettings.tsx
  web/packages/teleport/src/Assist/context/AssistContext.tsx
  web/packages/teleport/src/Assist/markdown.ts
  web/packages/teleport/src/Assist/types.ts
  web/packages/teleport/src/AuthConnectors/styles/AuthConnectors.styles.ts
  web/packages/teleport/src/AuthConnectors/styles/LockedFeatureContainer.styles.ts
  web/packages/teleport/src/DeviceTrust/DeviceTrustLocked.tsx
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ProxyDesktopServiceDiagram.tsx
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/WindowsComputer.tsx
  web/packages/teleport/src/Discover/Shared/HintBox.tsx
  web/packages/teleport/src/Navigation/NavigationSection.tsx
  web/packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
  web/packages/teleport/src/components/Dropdown/Dropdown.tsx
  web/packages/teleport/src/lib/term/terminal.ts
  web/packages/teleport/src/services/audit/types.ts
  web/packages/teleport/src/services/integrations/types.ts
  web/packages/teleterm/src/services/tshd/interceptors.test.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/Terminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts
  web/packages/teleterm/src/ui/Search/searchResult.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/Tabs/TabItem.tsx
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#37902 [v14] Update Prettier to 3.2.5
  package.json
  web/packages/design/src/AnimatedProgressBar/AnimatedProgressBar.tsx
  web/packages/shared/components/AnimatedTerminal/TerminalContent.tsx
  web/packages/shared/components/Select/types.ts
  web/packages/shared/components/UnifiedResources/shared/PinButton.tsx
  web/packages/shared/components/Window/WindowComponents.tsx
  web/packages/shared/hooks/useRefClickOutside/useRefClickOutside.ts
  web/packages/teleport/src/AccessRequests/LockedAccessRequests/LockedAccessRequests.tsx
  web/packages/teleport/src/Assist/Assist.tsx
  web/packages/teleport/src/Assist/Conversation/EntryContainer.tsx
  web/packages/teleport/src/Assist/Settings/DisplaySettings.tsx
  web/packages/teleport/src/Assist/context/AssistContext.tsx
  web/packages/teleport/src/Assist/markdown.ts
  web/packages/teleport/src/Assist/types.ts
  web/packages/teleport/src/AuthConnectors/styles/AuthConnectors.styles.ts
  web/packages/teleport/src/AuthConnectors/styles/LockedFeatureContainer.styles.ts
  web/packages/teleport/src/DeviceTrust/DeviceTrustLocked.tsx
  web/packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ProxyDesktopServiceDiagram.tsx
  web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/WindowsComputer.tsx
  web/packages/teleport/src/Discover/Shared/HintBox.tsx
  web/packages/teleport/src/Navigation/Navigation.tsx
  web/packages/teleport/src/Navigation/NavigationSection.tsx
  web/packages/teleport/src/Navigation/NavigationSwitcher.tsx
  web/packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
  web/packages/teleport/src/components/Dropdown/Dropdown.tsx
  web/packages/teleport/src/lib/term/terminal.ts
  web/packages/teleport/src/services/audit/types.ts
  web/packages/teleport/src/services/integrations/types.ts
  web/packages/teleterm/src/services/tshd/middleware.test.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/ConnectMyComputer/DocumentConnectMyComputer/Setup.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/connectMyComputerContext.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/Terminal.tsx
  web/packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts
  web/packages/teleterm/src/ui/Search/searchResult.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/Tabs/TabItem.tsx
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
  yarn.lock
Labels: ui, backport, size/sm, no-changelog

#37910 Add missing error checks for against backend operations
  lib/services/local/generic/generic.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37874 [v14] Fix testing bug in ./lib/auth/webauthn
  lib/auth/webauthn/login_test.go
Labels: backport, size/sm, no-changelog

#37873 [v15] Fix testing bug in ./lib/auth/webauthn
  lib/auth/webauthn/login_test.go
Labels: backport, size/sm, no-changelog

#37889 [v14] AWS OIDC: remove dependency on servicecfg
  lib/config/configuration.go
  lib/integrations/awsoidc/externalauditstorage_iam_config.go
  lib/integrations/awsoidc/externalauditstorage_iam_config_test.go
  lib/integrations/externalauditstorage/easconfig/externalauditstroageconfig.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#37890 [v15] AWS OIDC: remove dependency on servicecfg
  lib/config/configuration.go
  lib/integrations/awsoidc/externalauditstorage_iam_config.go
  lib/integrations/awsoidc/externalauditstorage_iam_config_test.go
  lib/integrations/externalauditstorage/easconfig/externalauditstroageconfig.go
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#37912 [v14] docs: bump cloud version v14.3.4
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#37898 External Audit Storage: fix error handling for get integration
  lib/integrations/externalauditstorage/configurator.go
Labels: size/sm, backport/branch/v14, no-changelog, backport/branch/v15

#37913 [v15] docs: bump cloud version v14.3.4
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#37885 Fix data race in lib/client tests
  lib/client/client_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog, backport/branch/v15

#37661 Add a guide for setting up Access Graph on-prem
  docs/config.json
  docs/img/access-graph/menu-item.png
  docs/pages/access-controls/access-graph.mdx
  docs/pages/access-controls/access-graph/self-hosted.mdx
Labels: documentation, size/md, backport/branch/v14, no-changelog, backport/branch/v15

#37925 [v14] Fix data race in lib/client tests
  lib/client/client_test.go
Labels: backport, size/sm, no-changelog

#37926 [v15] Fix data race in lib/client tests
  lib/client/client_test.go
Labels: backport, size/sm, no-changelog

#37828 add bot edit-role flow
  lib/web/apiserver.go
  lib/web/machineid.go
  lib/web/machineid_test.go
  web/packages/design/src/Icon/Icons/Bots.tsx
  web/packages/teleport/src/Bots/EditBot.test.tsx
  web/packages/teleport/src/Bots/EditBot.tsx
  web/packages/teleport/src/Bots/List/ActionCell.tsx
  web/packages/teleport/src/Bots/List/BotList.test.tsx
  web/packages/teleport/src/Bots/List/BotList.tsx
  web/packages/teleport/src/Bots/List/Bots.story.tsx
  web/packages/teleport/src/Bots/List/Bots.test.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Bots/types.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/bot/types.ts
Labels: ui, size/md, no-changelog

#37888 [v15] Add DatabasePermissions field to role
  api/proto/teleport/legacy/types/types.proto
  api/types/database_permissions.go
  api/types/database_permissions_test.go
  api/types/role.go
  api/types/types.pb.go
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  lib/services/access_checker.go
Labels: helm, backport, size/md, no-changelog

#37859 chore: Bump libfido2 to v1.14.0
  build.assets/Dockerfile
  build.assets/Dockerfile-centos7
  build.assets/build-fido2-macos.sh
  build.assets/pkgconfig/buildbox/usr/local/lib/pkgconfig/libfido2-static.pc
  build.assets/pkgconfig/centos7/usr/local/lib64/pkgconfig/libfido2-static.pc
Labels: size/sm

#37867 [v15] Make styled indicator position absolute
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/components/Authenticated/Authenticated.tsx
Labels: ui, backport, size/sm, no-changelog
