Repository gravitational/teleport, pull requests merged in 2024-01, with the labels that each got.

#35927 [v12] Ensure JS protos import necessary dependencies
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/teleterm/src/services/tshd/types.test.ts
Labels: ui, backport, size/sm, no-changelog

#35928 [v13] Ensure JS protos import necessary dependencies
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/teleterm/src/services/tshd/types.test.ts
Labels: ui, backport, size/sm, no-changelog

#35929 [v14] Ensure JS protos import necessary dependencies
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui-bypass.yaml
  .github/workflows/unit-tests-ui.yaml
  web/packages/teleterm/src/services/tshd/types.test.ts
Labels: ui, backport, size/sm, no-changelog

#36175 [v12] Standardize buttons in login prompts in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptSsoStatus/PromptSsoStatus.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptWebauthn/PromptWebauthn.tsx
Labels: ui, backport, size/sm, no-changelog

#36174 [v13] Standardize buttons in login prompts in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptSsoStatus/PromptSsoStatus.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptWebauthn/PromptWebauthn.tsx
Labels: ui, backport, size/sm, no-changelog

#36173 [v14] Standardize buttons in login prompts in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptSsoStatus/PromptSsoStatus.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/PromptWebauthn/PromptWebauthn.tsx
Labels: ui, backport, size/sm, no-changelog

#36122 [v13] Update gravitational/license module
  go.mod
  go.sum
Labels: backport, size/sm, no-changelog

#36123 [v14] Update gravitational/license module
  go.mod
  go.sum
Labels: backport, size/sm, no-changelog

#36098 [v13] integrations/updater: add nop validator
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  integrations/kube-agent-updater/pkg/img/insecure.go
  integrations/kube-agent-updater/pkg/img/nop.go
  integrations/kube-agent-updater/pkg/img/nop_test.go
Labels: backport, size/md

#36097 [v14] integrations/updater: add nop validator
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  integrations/kube-agent-updater/pkg/img/insecure.go
  integrations/kube-agent-updater/pkg/img/nop.go
  integrations/kube-agent-updater/pkg/img/nop_test.go
Labels: backport, size/md

#36021 Use the cache for user login state.
  lib/auth/auth.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#36083 Improve Access Plugins/Audit Exporter docs flows
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/includes/plugins/config-toml-teleport.mdx
  docs/pages/includes/plugins/finish-event-handler-config.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/machine-id-exporter-config.mdx
  docs/pages/includes/plugins/refresh-plugin-identity.mdx
  examples/resources/plugins/teleport-discord-helm.yaml
  examples/resources/plugins/teleport-discord.toml
  examples/resources/plugins/teleport-email-helm.yaml
  examples/resources/plugins/teleport-jira-cloud.toml
  examples/resources/plugins/teleport-jira-helm-cloud.yaml
  examples/resources/plugins/teleport-mattermost-cloud.toml
  examples/resources/plugins/teleport-mattermost-helm-cloud.yaml
  examples/resources/plugins/teleport-msteams-helm.yaml
  examples/resources/plugins/teleport-msteams.toml
  examples/resources/plugins/teleport-pagerduty-cloud.toml
  examples/resources/plugins/teleport-pagerduty-helm-cloud.yaml
  examples/resources/plugins/teleport-pagerduty-helm.yaml
  examples/resources/plugins/teleport-slack-helm.yaml
  examples/resources/plugins/teleport-slack.toml
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#36187 Add architecture diagrams to the docs
  docs/img/application-access/architecture.png
  docs/img/server-access/architecture.png
  docs/pages/application-access/introduction.mdx
  docs/pages/server-access/introduction.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#35981 Correct trusted cluster diagram
  docs/img/trusted-clusters/simplified-trusted-cluster.png
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36149 [v12] fix backend range keys
  lib/services/local/access.go
  lib/services/local/apps.go
  lib/services/local/assistant.go
  lib/services/local/configuration.go
  lib/services/local/databases.go
  lib/services/local/databaseservice.go
  lib/services/local/desktops.go
  lib/services/local/dynamic_access.go
  lib/services/local/generic/generic.go
  lib/services/local/inventory.go
  lib/services/local/kube.go
  lib/services/local/plugins.go
  lib/services/local/presence.go
  lib/services/local/provisioning.go
  lib/services/local/session.go
  lib/services/local/sessiontracker.go
  lib/services/local/status.go
  lib/services/local/trust.go
  lib/services/local/users.go
  lib/services/local/usertoken.go
Labels: backport, size/sm, no-changelog

#36148 [v13] fix backend range keys
  lib/services/local/access.go
  lib/services/local/apps.go
  lib/services/local/assistant.go
  lib/services/local/configuration.go
  lib/services/local/databases.go
  lib/services/local/databaseservice.go
  lib/services/local/desktops.go
  lib/services/local/dynamic_access.go
  lib/services/local/generic/generic.go
  lib/services/local/inventory.go
  lib/services/local/kube.go
  lib/services/local/plugins.go
  lib/services/local/presence.go
  lib/services/local/provisioning.go
  lib/services/local/session.go
  lib/services/local/sessiontracker.go
  lib/services/local/status.go
  lib/services/local/trust.go
  lib/services/local/users.go
  lib/services/local/usertoken.go
Labels: backport, size/sm, no-changelog

#36151 [v13] add openssh root login troubleshooting
  docs/pages/server-access/troubleshooting-server.mdx
Labels: documentation, backport, size/sm, no-changelog

#36147 [v14] fix backend range keys
  lib/services/local/access.go
  lib/services/local/apps.go
  lib/services/local/assistant.go
  lib/services/local/configuration.go
  lib/services/local/databases.go
  lib/services/local/databaseservice.go
  lib/services/local/desktops.go
  lib/services/local/generic/generic.go
  lib/services/local/inventory.go
  lib/services/local/kube.go
  lib/services/local/plugins.go
  lib/services/local/presence.go
  lib/services/local/provisioning.go
  lib/services/local/session.go
  lib/services/local/sessiontracker.go
  lib/services/local/status.go
  lib/services/local/trust.go
  lib/services/local/users.go
  lib/services/local/usertoken.go
Labels: backport, size/sm, no-changelog

#36150 [v14] add openssh root login troubleshooting
  docs/pages/server-access/troubleshooting-server.mdx
Labels: documentation, backport, size/sm, no-changelog

#34547 Convert `tsh play` to a streaming API
  CHANGELOG.md
  docs/pages/connect-your-client/tsh.mdx
  lib/auth/auth_with_roles_test.go
  lib/auth/http_client.go
  lib/client/api.go
  lib/client/player.go
  lib/client/player_test.go
  lib/client/terminal/terminal_common.go
  lib/client/terminal/terminal_unix.go
  lib/events/auditlog.go
  lib/session/session.go
  tool/tsh/common/play.go
  tool/tsh/common/tsh.go
Labels: documentation, tsh, audit-log, size/sm, no-changelog

#35582 Add database roles to `tsh db ls -v`
  tool/tsh/common/db.go
  tool/tsh/common/db_print.go
  tool/tsh/common/db_print_test.go
  tool/tsh/common/tsh.go
Labels: tsh, database-access, size/md, backport/branch/v14

#36191 [v14] Improve Access Plugins/Audit Exporter docs flows
  docs/pages/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/includes/plugins/config-toml-teleport.mdx
  docs/pages/includes/plugins/finish-event-handler-config.mdx
  docs/pages/includes/plugins/identity-export.mdx
  docs/pages/includes/plugins/machine-id-exporter-config.mdx
  docs/pages/includes/plugins/refresh-plugin-identity.mdx
  examples/resources/plugins/teleport-discord-helm.yaml
  examples/resources/plugins/teleport-discord.toml
  examples/resources/plugins/teleport-email-helm.yaml
  examples/resources/plugins/teleport-jira-cloud.toml
  examples/resources/plugins/teleport-jira-helm-cloud.yaml
  examples/resources/plugins/teleport-mattermost-cloud.toml
  examples/resources/plugins/teleport-mattermost-helm-cloud.yaml
  examples/resources/plugins/teleport-msteams-helm.yaml
  examples/resources/plugins/teleport-msteams.toml
  examples/resources/plugins/teleport-pagerduty-cloud.toml
  examples/resources/plugins/teleport-pagerduty-helm-cloud.yaml
  examples/resources/plugins/teleport-pagerduty-helm.yaml
  examples/resources/plugins/teleport-slack-helm.yaml
  examples/resources/plugins/teleport-slack.toml
Labels: documentation, backport, size/sm, no-changelog

#35971 changelog: add instructions for enabling RemoteFX
  CHANGELOG.md
  docs/cspell.json
Labels: size/sm, no-changelog

#36200 [v14] Correct trusted cluster diagram
  docs/img/trusted-clusters/simplified-trusted-cluster.png
Labels: documentation, backport, size/sm, no-changelog

#36199 [v13] Correct trusted cluster diagram
  docs/img/trusted-clusters/simplified-trusted-cluster.png
Labels: documentation, backport, size/sm, no-changelog

#36201 [v14] Add architecture diagrams to the docs
  docs/img/application-access/architecture.png
  docs/img/server-access/architecture.png
  docs/pages/application-access/introduction.mdx
  docs/pages/server-access/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#35982 Remove notes that the default cap is blank
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/management/security/reduce-blast-radius.mdx
  docs/pages/reference/authentication.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36209 [v12] Update logrus
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: backport, size/sm, no-changelog

#36198 update TPR, MAU and TIA definitions
  docs/pages/usage-billing.mdx
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36208 [v13] api: update logrus
  api/go.mod
  api/go.sum
Labels: backport, size/sm, no-changelog

#35960 Adds Lock handling methods to OktaAccessPoint
  lib/auth/api.go
Labels: backport/branch/v14, no-changelog

#36159 [v13] Add `Architecture` tag to hardened AMIs
  assets/aws/single-ami.pkr.hcl
Labels: backport, size/sm, no-changelog

#36158 [v14] Add `Architecture` tag to hardened AMIs
  assets/aws/single-ami.pkr.hcl
Labels: size/sm, no-changelog

#36180 Use current year in `LICENSE.header` template
  build.assets/LICENSE.header
Labels: size/sm, no-changelog

#36176 Add Access List messages to TAG protobuf
  gen/proto/go/accessgraph/v1alpha/access_graph_service.pb.go
  gen/proto/go/accessgraph/v1alpha/resources.pb.go
  proto/accessgraph/v1alpha/access_graph_service.proto
  proto/accessgraph/v1alpha/resources.proto
Labels: size/sm, backport/branch/v14, no-changelog

#36214 Relax Kubernetes CRD discovery when building cache
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/scheme.go
  lib/kube/proxy/scheme_test.go
Labels: kubernetes-access, size/sm, backport/branch/v14

#36215 Use cmp and cmpots properly in operator tests
  integrations/operator/controllers/resources/github_connector_controller_test.go
  integrations/operator/controllers/resources/oidc_connector_controller_test.go
  integrations/operator/controllers/resources/okta_import_rule_controller_test.go
  integrations/operator/controllers/resources/provision_token_controller_test.go
  integrations/operator/controllers/resources/saml_connector_controller_test.go
  integrations/operator/controllers/resources/testlib/accesslist_controller_tests.go
  integrations/operator/controllers/resources/testlib/compare.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/testlib/login_rule_controller_tests.go
  integrations/operator/controllers/resources/user_controller_test.go
Labels: size/sm, kube-operator, backport/branch/v13, backport/branch/v14, no-changelog

#36227 [v14] Relax Kubernetes CRD discovery when building cache
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/scheme.go
  lib/kube/proxy/scheme_test.go
Labels: kubernetes-access, backport, size/sm

#36196 [v14] Use the cache for user login state.
  lib/auth/auth.go
Labels: backport, size/sm

#36195 [v13] Use the cache for user login state.
  lib/auth/auth.go
Labels: backport, size/sm

#36242 Reviewer bot should use the stable version of Go
  .github/workflows/check.yaml
Labels: size/sm, no-changelog

#36244 [v12] Update go-restful to to v3.11.0 to address PRISMA-2022-0227
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  go.mod
  go.sum
Labels: go, backport, dependencies, size/sm, no-changelog

#36245 [v13] Update go-restful to to v3.11.0 to address PRISMA-2022-0227
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  go.mod
  go.sum
Labels: go, backport, dependencies, size/sm, no-changelog

#36241 [v14] Update k8s.io to 0.29.0 to address PRISMA-2022-0227
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  go.mod
  go.sum
  integration/kube_integration_test.go
  integrations/kube-agent-updater/go.mod
  integrations/kube-agent-updater/go.sum
Labels: security, go, backport, dependencies, size/sm, no-changelog

#35968 Report resource usage counts by handling heartbeat events
  gen/proto/go/prehog/v1/prehogv1connect/teleport.connect.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1/teleport_grpc_pb.js
  gen/proto/js/prehog/v1/teleport_pb.d.ts
  gen/proto/js/prehog/v1/teleport_pb.js
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/aggregating/service.go
  lib/usagereporter/teleport/aggregating/service_test.go
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/teleport.proto
Labels: size/md, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36216 fix flaky `lib/auth` cache-enabled tests
  lib/auth/helpers.go
Labels: flaky tests, size/sm, backport/branch/v14, no-changelog

#36213 Add structuredClone to jest JSDOMEnvironment
  web/packages/build/jest/jest-environment-patched-jsdom.js
Labels: ui, size/sm, backport/branch/v14, no-changelog

#36103 ButtonTextWithAddIcon shared component
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.story.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.test.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/index.ts
  web/packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
Labels: ui, size/md, backport/branch/v14, no-changelog

#36250 [v14] fix flaky `lib/auth` cache-enabled tests
  lib/auth/helpers.go
Labels: backport, size/sm, no-changelog

#36221 [v14] Adds Lock handling methods to OktaAccessPoint
  lib/auth/api.go
Labels: backport, size/sm, no-changelog

#36171 Allow Reconciler update handler to examine old value during update
  lib/kube/proxy/watcher.go
  lib/services/reconciler.go
  lib/services/reconciler_test.go
  lib/srv/app/watcher.go
  lib/srv/db/watcher.go
  lib/srv/desktop/discovery.go
  lib/srv/discovery/database_watcher.go
  lib/srv/discovery/kube_services_watcher.go
  lib/srv/discovery/kube_watcher.go
Labels: kubernetes-access, application-access, database-access, desktop-access, size/sm, discovery, backport/branch/v14, no-changelog

#36248 Prevent deleting enum values in `buf breaking`
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  proto/buf.yaml
Labels: backport-required, size/sm, no-changelog

#35040 Support running Teleport in a "hot reload" mode
  Makefile
  README.md
Labels: size/sm, no-changelog

#35961 [Web] Make Unified Resources page responsive
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/components/UnifiedResources/unifiedStyles.css
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Main/index.ts
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
Labels: ui, size/sm, backport/branch/v14

#36235 Auth device list component
  web/packages/design/src/Box/Box.jsx
  web/packages/design/src/Button/Button.jsx
  web/packages/design/src/MultiRowBox/MultiRowBox.story.test.tsx
  web/packages/design/src/MultiRowBox/MultiRowBox.story.tsx
  web/packages/design/src/MultiRowBox/MultiRowBox.tsx
  web/packages/design/src/MultiRowBox/__snapshots__/MultiRowBox.story.test.tsx.snap
  web/packages/design/src/MultiRowBox/index.ts
  web/packages/design/src/system/index.js
  web/packages/design/src/theme/themes/bblpTheme.ts
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
  web/packages/design/src/theme/themes/types.ts
  web/packages/teleport/src/Account/Header.tsx
  web/packages/teleport/src/Account/ManageDevices/AuthDeviceList/AuthDeviceList.story.tsx
  web/packages/teleport/src/Account/ManageDevices/AuthDeviceList/AuthDeviceList.test.tsx
  web/packages/teleport/src/Account/ManageDevices/AuthDeviceList/AuthDeviceList.tsx
Labels: ui, size/md, no-changelog

#36273 Undelete `CreateHostUserMode_HOST_USER_MODE_DROP`
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: size/sm, no-changelog

#36246 [v14] Add database roles to `tsh db ls -v`
  tool/tsh/common/db.go
  tool/tsh/common/db_print.go
  tool/tsh/common/db_print_test.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/md

#36251 Warn about CPU limits in `teleport-cluster` Helm chart
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36267 [v13] Prevent deleting enum values in `buf breaking` (#36248)
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  proto/buf.yaml
Labels: backport, size/sm, no-changelog

#36266 [v14] Prevent deleting enum values in `buf breaking` (#36248)
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  proto/buf.yaml
Labels: backport, size/sm, no-changelog

#35973 backend: support enterprise backends
  lib/backend/backend.go
  lib/backend/dynamo/dynamodbbk.go
  lib/backend/etcdbk/etcd.go
  lib/backend/firestore/firestorebk.go
  lib/backend/lite/lite.go
  lib/backend/pgbk/pgbk.go
  lib/backend/registry.go
  lib/service/service.go
Labels: size/md, backport/branch/v14, no-changelog

#36278 Wrap Reconnect in DocumentGatewayKube in Document
  web/packages/teleterm/src/ui/DocumentGatewayKube/DocumentGatewayKube.tsx
Labels: ui, size/sm, backport/branch/v14, no-changelog

#36279 fix: bot workflows
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/changelog.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/label.yaml
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36284 chore: Bump gci to v0.12.1
  build.assets/Dockerfile
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36268 [v12] Prevent deleting enum values in `buf breaking` (#36248)
  api/proto/buf-legacy.yaml
  api/proto/buf.yaml
  proto/buf.yaml
Labels: backport, size/sm, no-changelog

#36226 [v14] Add Access List messages to TAG protobuf
  gen/proto/go/accessgraph/v1alpha/access_graph_service.pb.go
  gen/proto/go/accessgraph/v1alpha/resources.pb.go
  proto/accessgraph/v1alpha/access_graph_service.proto
  proto/accessgraph/v1alpha/resources.proto
Labels: backport, size/sm, no-changelog

#36211 [v13] Remove notes that the default cap is blank
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/management/security/reduce-blast-radius.mdx
  docs/pages/reference/authentication.mdx
Labels: documentation, backport, size/sm, no-changelog

#36212 [v12] Remove notes that the default cap is blank
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/management/security/reduce-blast-radius.mdx
  docs/pages/reference/authentication.mdx
Labels: documentation, backport, size/sm, no-changelog

#36210 [v14] Remove notes that the default cap is blank
  docs/pages/access-controls/guides/per-session-mfa.mdx
  docs/pages/management/security/reduce-blast-radius.mdx
  docs/pages/reference/authentication.mdx
Labels: documentation, backport, size/sm, no-changelog

#36290 [v13] Warn about CPU limits in `teleport-cluster` Helm chart
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport, size/sm, no-changelog

#35997 [v14] Add okta user sync CTA event
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  proto/prehog/v1alpha/teleport.proto
  web/packages/teleport/src/services/userEvent/types.ts
Labels: ui, backport, size/sm, no-changelog

#36289 [v14] Warn about CPU limits in `teleport-cluster` Helm chart
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, backport, size/sm, no-changelog

#36293 [v13] chore: Bump gci to v0.12.1
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#36294 [v12] chore: Bump gci to v0.12.1
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#36292 [v14] chore: Bump gci to v0.12.1
  build.assets/Dockerfile
Labels: backport, size/sm, no-changelog

#36298 fix: panic in external audit watcher
  lib/services/local/externalauditstorage_watcher.go
  lib/services/local/externalauditstorage_watcher_test.go
Labels: size/sm, backport/branch/v14

#36254 [v14] ButtonTextWithAddIcon shared component
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.story.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.test.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/ButtonTextWithAddIcon.tsx
  web/packages/shared/components/ButtonTextWithAddIcon/index.ts
  web/packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
Labels: ui, backport, size/md, no-changelog

#35281 RFD 0156: Notifications
  rfd/0156-notifications.md
Labels: rfd, size/md, no-changelog

#35881 Add bot field to certificates and various usage events
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  constants.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/bot.go
  lib/auth/bot_test.go
  lib/auth/join.go
  lib/auth/keygen/keygen.go
  lib/auth/tls_test.go
  lib/services/authority.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/db/sqlserver/engine_test.go
  lib/srv/exec_test.go
  lib/tlsca/ca.go
  lib/tlsca/ca_test.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
Labels: backport/branch/v13, backport/branch/v14

#36307 [v12] Fix flaky test `TestTSHConfigConnectWithOpenSSHClient`
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm, no-changelog

#36257 [v13] Report resource usage counts by handling heartbeat events
  gen/proto/go/prehog/v1/prehogv1connect/teleport.connect.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1/teleport_grpc_pb.js
  gen/proto/js/prehog/v1/teleport_pb.d.ts
  gen/proto/js/prehog/v1/teleport_pb.js
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/aggregating/service.go
  lib/usagereporter/teleport/aggregating/service_test.go
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/md, no-changelog

#36295 [v12] fix: bot workflow
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/changelog.yaml
  .github/workflows/check.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/label.yaml
Labels: backport, size/sm, no-changelog

#36296 [v13] fix: bot workflow
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/changelog.yaml
  .github/workflows/check.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/label.yaml
Labels: backport, size/sm, no-changelog

#36249 [v14] Add structuredClone to jest JSDOMEnvironment
  web/packages/build/jest/jest-environment-patched-jsdom.js
Labels: ui, backport, size/sm, no-changelog

#36305 [v14] Fix flaky test `TestTSHConfigConnectWithOpenSSHClient`
  tool/tsh/common/proxy_test.go
Labels: tsh, backport, size/sm, no-changelog

#36297 [v14] fix: bot workflow
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/changelog.yaml
  .github/workflows/check.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/label.yaml
Labels: backport, size/sm, no-changelog

#36301 [v14] fix: panic in external audit watcher
  lib/services/local/externalauditstorage_watcher.go
  lib/services/local/externalauditstorage_watcher_test.go
Labels: backport, size/sm

#36256 [v14] Report resource usage counts by handling heartbeat events
  gen/proto/go/prehog/v1/prehogv1connect/teleport.connect.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1/teleport_grpc_pb.js
  gen/proto/js/prehog/v1/teleport_pb.d.ts
  gen/proto/js/prehog/v1/teleport_pb.js
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/aggregating/service.go
  lib/usagereporter/teleport/aggregating/service_test.go
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/md, no-changelog

#36019 Use app names when creating user_group for UI
  lib/web/apiserver_test.go
  lib/web/user_groups.go
Labels: backport-required, size/sm, backport/branch/v14, no-changelog

#36280 Fix `rdp-client` FIPS builds
  Cargo.lock
  build.assets/Dockerfile-centos7
  build.assets/Dockerfile-centos7-assets
  build.assets/Dockerfile-node
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, desktop-access, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36316 [v14] Fix `rdp-client` FIPS builds
  Cargo.lock
  build.assets/Dockerfile-centos7-fips
  build.assets/Dockerfile-connect
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#36318 [v12] Fix `rdp-client` FIPS builds
  Cargo.lock
  build.assets/Dockerfile-centos7-fips
  build.assets/Dockerfile-connect
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#36317 [v13] Fix `rdp-client` FIPS builds
  Cargo.lock
  build.assets/Dockerfile-centos7-fips
  build.assets/Dockerfile-connect
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#36314 Use GetRole in the user login state generator, fail if not found.
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14, no-changelog

#36203 Add protos for Workload Identity Service
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service.pb.go
  api/gen/proto/go/teleport/machineid/v1/workload_identity_service_grpc.pb.go
  api/proto/teleport/machineid/v1/workload_identity_service.proto
Labels: size/sm, no-changelog

#36269 Auto Discover tests: increment timeout for reconcile loops
  lib/srv/discovery/discovery_test.go
Labels: size/sm, discovery, backport/branch/v14, no-changelog

#36274 Upgrade Rust to 1.75.0
  build.assets/versions.mk
  web/packages/teleport/src/ironrdp/src/lib.rs
Labels: ui, size/sm

#36020 Add access lists, members, and reviews to cache.
  api/client/accesslist/accesslist.go
  api/client/events.go
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  api/proto/teleport/legacy/client/proto/event.proto
  gen/proto/js/teleport/accesslist/v1/accesslist_service_grpc_pb.d.ts
  gen/proto/js/teleport/accesslist/v1/accesslist_service_grpc_pb.js
  gen/proto/js/teleport/accesslist/v1/accesslist_service_pb.d.ts
  gen/proto/js/teleport/accesslist/v1/accesslist_service_pb.js
  lib/auth/accesspoint/accesspoint.go
  lib/auth/api.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
  lib/services/local/events.go
  lib/services/simple/access_list.go
Labels: size/lg, backport/branch/v13, backport/branch/v14

#36258 [v12] Report resource usage counts by handling heartbeat events
  gen/proto/go/prehog/v1/prehogv1connect/teleport.connect.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/js/prehog/v1/teleport_grpc_pb.js
  gen/proto/js/prehog/v1/teleport_pb.d.ts
  gen/proto/js/prehog/v1/teleport_pb.js
  gen/proto/js/prehog/v1alpha/teleport_pb.d.ts
  gen/proto/js/prehog/v1alpha/teleport_pb.js
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/aggregating/service.go
  lib/usagereporter/teleport/aggregating/service_test.go
  lib/usagereporter/teleport/aggregating/submitter.go
  lib/usagereporter/teleport/aggregating/submitter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/md, no-changelog

#36237 Bump cloud version
  docs/config.json
Labels: documentation, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36332 [v14] JoinScript: add DiscoveryService installation method
  lib/web/apiserver.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/node-join/install.sh
Labels: backport, size/md, no-changelog

#35918 Web: Don't merge custom headers with default values
  web/packages/teleport/src/Assist/service.ts
  web/packages/teleport/src/services/api/api.test.ts
  web/packages/teleport/src/services/api/api.ts
  web/packages/teleport/src/services/auth/makeMfa.ts
Labels: ui, size/sm, no-changelog

#35578 desktop access: stop writing to the NTAuth store
  CHANGELOG.md
  docs/pages/desktop-access/active-directory-manual.mdx
  lib/auth/windows/certificate_authority.go
  lib/srv/desktop/windows_server.go
  lib/web/scripts/desktop/configure-ad.ps1
Labels: documentation, desktop-access, size/sm, no-changelog

#36320 [v13] Use GetRole in the user login state generator, fail if not found.
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
Labels: backport, size/sm, no-changelog

#36321 [v14] Use GetRole in the user login state generator, fail if not found.
  lib/auth/userloginstate/generator.go
  lib/auth/userloginstate/generator_test.go
Labels: backport, size/sm, no-changelog

#36322 Fix incorrect audit log IP when using Kubernetes impersonation
  lib/auth/middleware.go
  lib/auth/middleware_test.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#36327 [v14] Auto Discover tests: increment timeout for reconcile loops
  lib/srv/discovery/discovery_test.go
Labels: backport, size/sm, discovery, no-changelog

#36263 update address description for teleport join openssh
  tool/teleport/common/teleport.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36345 [v13] Fix incorrect audit log IP when using Kubernetes impersonation
  lib/auth/middleware.go
  lib/auth/middleware_test.go
Labels: backport, size/sm

#36337 [v12] Bump bitflags from 1.3.2 to 2.0.2 (#23741)
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/cliprdr.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/flags.rs
  lib/srv/desktop/rdp/rdpclient/src/rdpdr/scard.rs
  lib/srv/desktop/rdp/rdpclient/src/vchan.rs
Labels: rdp, backport, desktop-access, size/sm, no-changelog

#36339 [v12] Bump cloud version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#36340 [v13] Bump cloud version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#36333 [v13] Update Rust version to 1.71.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#36341 [v14] Bump cloud version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#36346 [v14] Fix incorrect audit log IP when using Kubernetes impersonation
  lib/auth/middleware.go
  lib/auth/middleware_test.go
Labels: backport, size/sm

#36312 [v13] update TPR, MAU and TIA definitions
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#36311 [v14] update TPR, MAU and TIA definitions
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#36335 [v12] Update Rust version to 1.71.1
  build.assets/versions.mk
Labels: backport, size/sm, no-changelog

#36265 [v14] [Web] Make Unified Resources page responsive
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/components/UnifiedResources/unifiedStyles.css
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Main/index.ts
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
Labels: ui, backport, size/sm

#36365 Ensure that login time is set for app sessions
  api/types/session.go
  lib/auth/sessions.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#36352 [v13] update address description for teleport join openssh
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#36350 [v14] update address description for teleport join openssh
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#36238 feat: AWS KMS keystore backend
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/aws_kms_test.go
  lib/auth/keystore/gcp_kms.go
  lib/auth/keystore/keystore_test.go
  lib/auth/keystore/manager.go
  lib/auth/keystore/pkcs11.go
  lib/auth/keystore/software.go
  lib/cloud/clients.go
Labels: size/lg, no-changelog

#35956 Update AWS HA autoscale and starter cluster examples to use hardened AMIs with Graviton/ARM64
  CHANGELOG.md
  assets/aws/files/bin/teleport-all-pre-start
  assets/aws/files/bin/teleport-generate-config
  assets/aws/files/bin/teleport-get-cert
  assets/aws/files/bin/teleport-lock
  assets/aws/files/tests/ha-auth-fips-tlsrouting.bats
  assets/aws/files/tests/ha-auth-fips.bats
  assets/aws/files/tests/ha-auth-oss.bats
  assets/aws/files/tests/ha-auth-tlsrouting.bats
  assets/aws/files/tests/ha-auth.bats
  assets/aws/files/tests/ha-node.bats
  assets/aws/files/tests/ha-proxy-acm-alias.bats
  assets/aws/files/tests/ha-proxy-acm-tlsrouting.bats
  assets/aws/files/tests/ha-proxy-acm.bats
  assets/aws/files/tests/ha-proxy-mysql.bats
  assets/aws/files/tests/ha-proxy-no-db.bats
  assets/aws/files/tests/ha-proxy-tlsrouting.bats
  assets/aws/files/tests/ha-proxy.bats
  docs/pages/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx
  docs/pages/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx
  docs/pages/installation.mdx
  examples/aws/terraform/ha-autoscale-cluster/Makefile
  examples/aws/terraform/ha-autoscale-cluster/README.md
  examples/aws/terraform/ha-autoscale-cluster/ansible/upgrade.yaml
  examples/aws/terraform/ha-autoscale-cluster/assets/grafana-nginx-acm.conf
  examples/aws/terraform/ha-autoscale-cluster/assets/grafana-nginx.conf
  examples/aws/terraform/ha-autoscale-cluster/assets/health-dashboard.json
  examples/aws/terraform/ha-autoscale-cluster/auth-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/auth_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/bastion.tf
  examples/aws/terraform/ha-autoscale-cluster/data.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/monitor_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/monitor_iam.tf
  examples/aws/terraform/ha-autoscale-cluster/node-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/node_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/provider.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy-user-data.tpl
  examples/aws/terraform/ha-autoscale-cluster/proxy_asg.tf
  examples/aws/terraform/ha-autoscale-cluster/proxy_network.tf
  examples/aws/terraform/ha-autoscale-cluster/route53.tf
  examples/aws/terraform/ha-autoscale-cluster/s3.tf
  examples/aws/terraform/ha-autoscale-cluster/ssm.tf
  examples/aws/terraform/ha-autoscale-cluster/vars.tf
  examples/aws/terraform/ha-autoscale-cluster/vpc.tf
  examples/aws/terraform/starter-cluster/Makefile
  examples/aws/terraform/starter-cluster/README.md
  examples/aws/terraform/starter-cluster/data.tf
  examples/aws/terraform/starter-cluster/ssm.tf
  examples/aws/terraform/starter-cluster/vars.tf
Labels: documentation, size/sm, no-changelog

#36264 Make UI part of tshd events service one-to-one
  web/packages/teleterm/package.json
  web/packages/teleterm/src/preload.ts
  web/packages/teleterm/src/services/tshd/middleware.ts
  web/packages/teleterm/src/services/tshdEvents/index.ts
  web/packages/teleterm/src/types.ts
  web/packages/teleterm/src/ui/appContext.ts
  web/packages/teleterm/src/ui/fixtures/mocks.ts
  web/packages/teleterm/src/ui/types.ts
  yarn.lock
Labels: ui, size/sm, no-changelog

#36192 Remove deprecated migration from `tbot`
  lib/tbot/identity/artifact.go
Labels: machine-id, size/sm

#36329 [v14] Remove the assist popup
  web/packages/teleport/src/Assist/Popup/Popup.ts
  web/packages/teleport/src/Assist/Popup/index.ts
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/TopBar/TopBar.test.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
Labels: ui, backport, size/sm, no-changelog

#36140 Machine ID: Internal Service Management
  lib/tbot/bot/service.go
  lib/tbot/bot_identity.go
  lib/tbot/config/config.go
  lib/tbot/config/config_test.go
  lib/tbot/config/service_example.go
  lib/tbot/config/testdata/TestBotConfig_MarshalYAML/minimal_config.golden
  lib/tbot/config/testdata/TestBotConfig_MarshalYAML/standard_config.golden
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_ca_rotation_test.go
  lib/tbot/service_diagnostics.go
  lib/tbot/service_outputs.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
Labels: machine-id, size/md, backport/branch/v14, no-changelog

#36379 faq link fix in web ui
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14, no-changelog

#36303 Sanitize backend keys with .. in them.
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
Labels: size/sm, backport/branch/v12, backport/branch/v13, backport/branch/v14

#36396 [v14] faq link fix in web ui
  web/packages/teleport/src/Support/Support.tsx
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#36228 Fix the access list reminder pagination loop.
  docs/pages/includes/plugins/rbac-with-friendly-name.mdx
  integrations/access/accesslist/app.go
  integrations/access/accesslist/app_test.go
  integrations/access/common/config.go
  integrations/access/common/teleport/client.go
Labels: documentation, size/sm, backport/branch/v14

#36306 [v13] Fix flaky test `TestTSHConfigConnectWithOpenSSHClient`
  tool/tsh/proxy_test.go
Labels: tsh, backport, size/sm, no-changelog

#35899 AWS OIDC: DeployDatabaseService per VPC
  lib/cloud/aws/policy_statements.go
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_config.go
  lib/integrations/awsoidc/deployservice_config_test.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/integrations/awsoidc/deployservice_update_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: discover, size/lg, backport/branch/v14, no-changelog

#36402 [v12] Sanitize backend keys with .. in them.
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
Labels: backport, size/sm

#36404 [v14] Sanitize backend keys with .. in them.
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
Labels: backport, size/sm

#36358 negotiated screen resolution polish
  lib/srv/desktop/tdp/proto.go
  lib/srv/desktop/windows_server.go
  rfd/0037-desktop-access-protocol.md
  web/packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
  web/packages/teleport/src/lib/tdp/playerClient.ts
Labels: ui, rfd, desktop-access, size/sm, no-changelog

#36016 [v14] AWSOIDC: Collect required vpcs and its subnets for use in web UI (#35930)
  api/types/databaseservice.go
  lib/integrations/awsoidc/listdatabases.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
  lib/web/ui/integration.go
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/integrations/integrations.ts
Labels: ui, backport, size/md, no-changelog

#36371 docs: correct wording in Vitess instrs
  docs/pages/database-access/guides/vitess.mdx
Labels: documentation, size/sm, backport/branch/v14, no-changelog

#36408 [v14] AWS OIDC: DeployDatabaseService per VPC
  lib/cloud/aws/policy_statements.go
  lib/integrations/awsoidc/deploydatabaseservice.go
  lib/integrations/awsoidc/deploydatabaseservice_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_config.go
  lib/integrations/awsoidc/deployservice_config_test.go
  lib/integrations/awsoidc/deployservice_test.go
  lib/integrations/awsoidc/deployservice_update_test.go
  lib/web/apiserver.go
  lib/web/integrations_awsoidc.go
  lib/web/ui/integration.go
Labels: backport, size/lg, no-changelog

#36364 fallback to upstream when sessions are missing from cache
  lib/cache/cache.go
Labels: size/sm, backport/branch/v13, backport/branch/v14

#36356 [v14] Use app names when creating user_group for UI
  lib/web/apiserver_test.go
  lib/web/user_groups.go
Labels: backport, size/sm, no-changelog

#36391 [v14] Wrap Reconnect in DocumentGatewayKube in Document
  web/packages/teleterm/src/ui/DocumentGatewayKube/DocumentGatewayKube.tsx
Labels: ui, backport, size/sm, no-changelog

#36413 API: Remove fallback support for `SearchUnstructuredEvents` and `StreamUnstructuredSessionEvents`
  api/client/client.go
Labels: size/sm, no-changelog

#36414 [v14] docs: correct wording in Vitess instrs
  docs/pages/database-access/guides/vitess.mdx
Labels: documentation, backport, size/sm, no-changelog

#36409 tty_playback: Fix `handlePlaybackAction` panic on unit16 overflow
  fuzz/oss-fuzz-build.sh
  lib/web/tty_playback.go
  lib/web/tty_playback_test.go
Labels: size/sm, no-changelog

#36418 lock: Remove deprecated lock per `node`
  api/types/lock.go
  tool/tctl/common/lock_command.go
Labels: tctl, size/sm, no-changelog

#36220 [v14] Support proxy version server
  .github/dependabot.yml
  .github/workflows/flaky-tests.yaml
  .github/workflows/lint.yaml
  examples/chart/teleport-kube-agent/templates/updater/deployment.yaml
  examples/chart/teleport-kube-agent/tests/updater_deployment_test.yaml
  examples/chart/teleport-kube-agent/values.yaml
  go.mod
  go.sum
  integration/proxy/automaticupgrades_test.go
  integrations/kube-agent-updater/Dockerfile
  integrations/kube-agent-updater/Makefile
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  integrations/kube-agent-updater/go.mod
  integrations/kube-agent-updater/go.sum
  integrations/kube-agent-updater/pkg/controller/deployment.go
  integrations/kube-agent-updater/pkg/controller/errors.go
  integrations/kube-agent-updater/pkg/controller/statefulset.go
  integrations/kube-agent-updater/pkg/controller/updater.go
  integrations/kube-agent-updater/pkg/controller/updater_test.go
  integrations/kube-agent-updater/pkg/controller/utils.go
  integrations/kube-agent-updater/pkg/maintenance/unhealthy.go
  integrations/kube-agent-updater/pkg/maintenance/window.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/main.go
  lib/automaticupgrades/basichttp/client.go
  lib/automaticupgrades/basichttp/servermock.go
  lib/automaticupgrades/cache/cache.go
  lib/automaticupgrades/cache/cache_test.go
  lib/automaticupgrades/cache/error.go
  lib/automaticupgrades/channel.go
  lib/automaticupgrades/channel_test.go
  lib/automaticupgrades/constants/constants.go
  lib/automaticupgrades/maintenance/basichttp.go
  lib/automaticupgrades/maintenance/basichttp_test.go
  lib/automaticupgrades/maintenance/mock.go
  lib/automaticupgrades/maintenance/trigger.go
  lib/automaticupgrades/version.go
  lib/automaticupgrades/version/basichttp.go
  lib/automaticupgrades/version/basichttp_test.go
  lib/automaticupgrades/version/errors.go
  lib/automaticupgrades/version/static.go
  lib/automaticupgrades/version/versionget.go
  lib/automaticupgrades/version/versionget_test.go
  lib/automaticupgrades/version_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/awsoidc.go
  lib/service/service.go
  lib/service/servicecfg/proxy.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/automaticupgrades.go
  lib/web/integrations_awsoidc.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
Labels: helm, backport, size/sm

#36412 Kubernetes: Cleanup code marked to be deleted for v15
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/transport.go
  lib/kube/proxy/transport_test.go
Labels: kubernetes-access, size/sm, no-changelog

#36302 update FieldSelectCreatable component to accept option, ariaLabel and formatCreateLabel
  web/packages/shared/components/FieldSelect/FieldSelectCreatable.tsx
  web/packages/shared/components/Select/types.ts
Labels: ui, size/sm, backport/branch/v14, no-changelog
