Repository gravitational/teleport, pull requests merged in 2025-10, with the labels that each got.

#59647 Add shared troubleshooting section for Oracle db access
  docs/cspell.json
  docs/pages/enroll-resources/database-access/enroll-aws-databases/rds-oracle.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/oracle-exadata.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/includes/database-access/oracle-troubleshooting.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v18

#59764 [v18] Fix TestWorkloadIdentityService_SignX509SVIDs flakiness
  lib/auth/machineid/machineidv1/workload_identity_service_test.go
Labels: backport, size/sm, no-changelog

#59746 [v18] [flaky] attempt to fix TestAppAccess/AuditEvents by hardening ensureAuditEvent
  integration/appaccess/appaccess_test.go
  integration/appaccess/pack.go
Labels: backport, size/sm, no-changelog

#58397 Update test plan for static Access Lists
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#59786 Include sid in command execution message for event log ui
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59769 [v18] docs: new design for MWI docs homepage
  docs/img/machine-id/mwi-hero.png
  docs/pages/machine-workload-identity/introduction.mdx
  docs/pages/machine-workload-identity/machine-workload-identity.mdx
Labels: documentation, backport, size/md, no-changelog

#59752 [v18] [clientutils] Add CollectWithFallback helper
  api/utils/clientutils/resources.go
  api/utils/clientutils/resources_test.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm, no-changelog

#59815 [v16] Update bintest to 3.3.0
  go.mod
  go.sum
  integrations/event-handler/go.sum
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#59341 feat: client side impl for new join service
  lib/auth/join/join.go
  lib/client/proxy/insecure/insecure.go
  lib/join/join_test.go
  lib/join/joinclient/join.go
  lib/join/joinv1/client.go
Labels: size/md, no-changelog, backport/branch/v18

#59562 [v17] Add `teleport-tools` package for use with client tools managed updates
  lib/autoupdate/package_url.go
  lib/autoupdate/tools/utils.go
  lib/autoupdate/tools/utils_test.go
Labels: backport, size/md, no-changelog

#58783 [v16] docs: broken mwi links in tilegrid
  docs/pages/machine-workload-identity/hybrid-multi-mwi.mdx
  docs/pages/machine-workload-identity/iac-mwi.mdx
  docs/pages/machine-workload-identity/mwi-ci-cd.mdx
Labels: documentation, backport, size/sm, no-changelog

#58963 feat: bound keypair support in new join service
  api/gen/proto/go/teleport/join/v1/joinservice.pb.go
  api/proto/teleport/join/v1/joinservice.proto
  lib/auth/auth.go
  lib/auth/bound_keypair_tokens.go
  lib/auth/export_test.go
  lib/auth/grpcserver.go
  lib/auth/join_bound_keypair_adapter.go
  lib/auth/join_bound_keypair_test.go
  lib/join/adapters.go
  lib/join/boundkeypair/boundkeypair.go
  lib/join/internal/messages/messages.go
  lib/join/joinclient/join.go
  lib/join/joinclient/join_boundkeypair.go
  lib/join/joinv1/messages.go
  lib/join/joinv1/messages_boundkeypair.go
  lib/join/server.go
  lib/join/server_boundkeypair.go
  lib/join/server_token.go
Labels: size/lg, no-changelog

#59612 [v17] docs: identity governance use cases
  docs/pages/identity-governance/identity-gov-use-cases.mdx
Labels: documentation, backport, size/sm, no-changelog

#59849 Release 18.2.4
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#59756 [v18] Docs: add section about suffix installations in server discovery
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/gcp-discovery.mdx
  docs/pages/includes/auto-discovery/ec2-config.mdx
Labels: documentation, backport, size/sm, no-changelog

#59655 feat(webui): New bot instances experience
  web/packages/shared/components/Search/SearchPanel.tsx
  web/packages/shared/components/TextEditor/TextEditor.mock.tsx
  web/packages/teleport/src/BotInstances/BotInstances.story.tsx
  web/packages/teleport/src/BotInstances/BotInstances.test.tsx
  web/packages/teleport/src/BotInstances/BotInstances.tsx
  web/packages/teleport/src/BotInstances/Details/BotInstanceDetails.story.tsx
  web/packages/teleport/src/BotInstances/Details/BotInstanceDetails.test.tsx
  web/packages/teleport/src/BotInstances/Details/BotInstanceDetails.tsx
  web/packages/teleport/src/BotInstances/InfoGuide.tsx
  web/packages/teleport/src/BotInstances/List/BotInstancesList.story.tsx
  web/packages/teleport/src/BotInstances/List/BotInstancesList.test.tsx
  web/packages/teleport/src/BotInstances/List/BotInstancesList.tsx
  web/packages/teleport/src/Bots/Details/Instance.story.tsx
  web/packages/teleport/src/Bots/Details/Instance.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/teleportContext.tsx
  web/packages/teleport/src/test/helpers/botInstances.ts
  web/packages/teleport/src/types.ts
Labels: ui, machine-id, size/lg, backport/branch/v17, backport/branch/v18

#59640 Make time marker labels display better on long recordings at low zoom
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimeMarksRenderer.test.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimeMarksRenderer.ts
Labels: ui, size/md, no-changelog, backport/branch/v18

#59701 [v18] Add skip inactivity button in SSH session recording playback
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/FastForward.tsx
  web/packages/design/src/Icon/assets/FastForward.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/SessionRecordings/view/CurrentEventInfo.tsx
  web/packages/teleport/src/SessionRecordings/view/RecordingPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/RecordingWithMetadata.tsx
  web/packages/teleport/src/SessionRecordings/view/player/RecordingPlayer.tsx
Labels: ui, backport, size/md

#59794 [v18] Add shared troubleshooting section for Oracle db access
  docs/cspell.json
  docs/pages/enroll-resources/database-access/enroll-aws-databases/rds-oracle.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/oracle-exadata.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/includes/database-access/oracle-troubleshooting.mdx
Labels: documentation, backport, size/md, no-changelog

#59826 [v18] tag: remove LastSyncTime from AWS and Azure resource proto definitions
  gen/proto/go/accessgraph/v1alpha/aws.pb.go
  gen/proto/go/accessgraph/v1alpha/azure.pb.go
  lib/srv/discovery/fetchers/aws-sync/ec2.go
  lib/srv/discovery/fetchers/aws-sync/eks.go
  lib/srv/discovery/fetchers/aws-sync/eks_test.go
  lib/srv/discovery/fetchers/aws-sync/groups.go
  lib/srv/discovery/fetchers/aws-sync/iam_test.go
  lib/srv/discovery/fetchers/aws-sync/idp.go
  lib/srv/discovery/fetchers/aws-sync/kms.go
  lib/srv/discovery/fetchers/aws-sync/kms_test.go
  lib/srv/discovery/fetchers/aws-sync/policies.go
  lib/srv/discovery/fetchers/aws-sync/rds.go
  lib/srv/discovery/fetchers/aws-sync/rds_test.go
  lib/srv/discovery/fetchers/aws-sync/roles.go
  lib/srv/discovery/fetchers/aws-sync/s3.go
  lib/srv/discovery/fetchers/aws-sync/s3_test.go
  lib/srv/discovery/fetchers/aws-sync/users.go
  lib/srv/discovery/fetchers/azuresync/principals.go
  lib/srv/discovery/fetchers/azuresync/roleassignments.go
  lib/srv/discovery/fetchers/azuresync/roledefinitions.go
  lib/srv/discovery/fetchers/azuresync/virtualmachines.go
  proto/accessgraph/v1alpha/aws.proto
  proto/accessgraph/v1alpha/azure.proto
Labels: backport, size/sm, discovery, no-changelog

#59861 [cache] Fixes incorrect trace name for GetWebTokens
  lib/cache/web_tokens.go
Labels: size/sm, no-changelog, backport/branch/v18

#59860 [v18] Make time marker labels display better on long recordings at low zoom
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimeMarksRenderer.test.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimeMarksRenderer.ts
Labels: ui, backport, size/md, no-changelog

#59851 [v18] teleport-usage: Bump golang docker image to 1.24
  examples/teleport-usage/Dockerfile
Labels: backport, size/sm, no-changelog

#57383 Docs: Document OIDC Setting Enabling Signed Request Objects
  docs/pages/zero-trust-access/sso/oidc.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58159 Docs: add Amazon ECS installation mode
  docs/cspell.json
  docs/pages/installation/amazon-ecs.mdx
  docs/pages/installation/installation.mdx
  docs/sidebar.json
  examples/aws/terraform/ecs-agent/main.tf
  examples/aws/terraform/ecs-agent/providers.tf
  examples/aws/terraform/ecs-agent/variables.tf
Labels: documentation, size/md, no-changelog, backport/branch/v18

#59848 [v18] MWI: Add Ansible AWX guide
  docs/cspell.json
  docs/pages/machine-workload-identity/machine-id/access-guides/access-guides.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/ansible-awx.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/ansible.mdx
Labels: documentation, backport, size/md, no-changelog

#59714 Teleport Identity Security - Add Identity Activity Center alerts documentation
  docs/img/access-graph/alerts.png
  docs/pages/identity-security/usage/alerts.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v18

#59886 Fix lint error in node-join/install.sh
  lib/web/scripts/node-join/install.sh
Labels: size/sm, no-changelog

#59841 Added Week of 10/01 Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#59620 MWI: Static keys and environment loading for bound keypair joining params
  lib/auth/join/boundkeypair/boundkeypair.go
  lib/auth/join/boundkeypair/boundkeypair_test.go
  lib/auth/join/join.go
  lib/join/joinclient/join_boundkeypair.go
  lib/tbot/bot/onboarding/config.go
  lib/tbot/cli/keypair_create.go
  lib/tbot/cli/start_shared.go
  lib/tbot/config/uri.go
  lib/tbot/config/uri_test.go
  lib/tbot/internal/identity/service.go
  tool/tbot/keypair.go
Labels: machine-id, size/md, backport/branch/v17, backport/branch/v18

#59690 [AWSIC] Protobuf definitions for the Identity Center gRPC service
  api/gen/proto/go/teleport/identitycenter/v1/service.pb.go
  api/gen/proto/go/teleport/identitycenter/v1/service_grpc.pb.go
  api/gen/proto/go/teleport/provisioning/v1/provisioning.pb.go
  api/proto/teleport/identitycenter/v1/service.proto
  api/proto/teleport/provisioning/v1/provisioning.proto
Labels: size/md, no-changelog, aws-iam-identity-center

#59677 docs: include tbot.exe in windows uninstall instrs
  docs/pages/zero-trust-access/management/admin/uninstall-teleport.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#59761 Fix issue with dry-run access_request.spec.expires overwrite
  tool/tsh/common/tsh.go
Labels: tsh, backport-required, size/sm, backport/branch/v17, backport/branch/v18

#59792 Deflake TestIntegrations/DifferentPinnedIP
  integration/integration_test.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59902 Refactor WebToken interface
  api/client/sessions.go
  api/types/session.go
  lib/auth/accesspoint/accesspoint.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/clt.go
  lib/auth/authtest/authtest.go
  lib/auth/grpcserver.go
  lib/auth/sessions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/web_tokens.go
  lib/cache/web_tokens_test.go
  lib/service/service.go
  lib/services/identity.go
  lib/services/local/session.go
  lib/services/session.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59777 Simplify lib/utils loadbalancer
  lib/multiplexer/multiplexer_test.go
  lib/utils/conn.go
  lib/utils/loadbalancer.go
  lib/utils/loadbalancer_test.go
Labels: size/sm, no-changelog

#59909 [v18] Deflake TestIntegrations/DifferentPinnedIP
  integration/integration_test.go
Labels: backport, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#59855 Use cache for ProvisionToken resource access in AWS OIDC deploy service
  lib/auth/authclient/api.go
  lib/auth/grpcserver.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/auth/integration/integrationv1/awsoidc_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_jointoken.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/service/awsoidc.go
  lib/service/service.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#59871 [v18] Docs: add Amazon ECS installation mode
  docs/cspell.json
  docs/pages/installation/amazon-ecs.mdx
  docs/pages/installation/installation.mdx
  docs/sidebar.json
  examples/aws/terraform/ecs-agent/main.tf
  examples/aws/terraform/ecs-agent/providers.tf
  examples/aws/terraform/ecs-agent/variables.tf
Labels: documentation, backport, size/md, no-changelog

#59913 [v18] Use cache for ProvisionToken resource access in AWS OIDC deploy service
  lib/auth/authclient/api.go
  lib/auth/grpcserver.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/auth/integration/integrationv1/awsoidc_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_jointoken.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/service/awsoidc.go
  lib/service/service.go
Labels: backport, size/sm, no-changelog

#59914 [v17] Use cache for ProvisionToken resource access in AWS OIDC deploy service
  lib/auth/authclient/api.go
  lib/auth/grpcserver.go
  lib/auth/integration/integrationv1/awsoidc.go
  lib/auth/integration/integrationv1/awsoidc_test.go
  lib/integrations/awsoidc/deployservice.go
  lib/integrations/awsoidc/deployservice_iam_jointoken.go
  lib/integrations/awsoidc/deployservice_vcr_test.go
  lib/integrations/awsoidc/eks_enroll_clusters.go
  lib/service/awsoidc.go
  lib/service/service.go
Labels: backport, size/sm, no-changelog

#59917 [v17] docs: clarify cluster upgrade process
  docs/pages/includes/compatibility.mdx
  docs/pages/upgrading/overview.mdx
Labels: documentation, backport, size/sm, no-changelog

#59206 Make SSH session client provide session params upfront rather than with synchronous `envs@goteleport.com` requests
  api/observability/tracing/ssh/client.go
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
  lib/client/client_test.go
  lib/client/session.go
  lib/srv/ctx.go
  lib/srv/forward/sshserver.go
  lib/srv/git/forward.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/term.go
  lib/srv/termhandlers.go
  lib/sshutils/sftp/http.go
  lib/sshutils/sftp/sftp.go
  lib/web/files.go
  lib/web/terminal.go
Labels: size/md, no-changelog

#59899 [v17] docs: include tbot.exe in windows uninstall instrs
  docs/pages/zero-trust-access/management/admin/uninstall-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#59937 [v17] [Web] Improve side navigation search indexing
  web/packages/teleport/src/Navigation/Search.tsx
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#59936 [v18] [Web] Improve side navigation search indexing
  web/packages/teleport/src/Navigation/Search.tsx
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#59894 Update pnpm to 10.18.0
  package.json
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59578 Fix the access graph preview on non-standard roles
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#59905 [v17] [docs] Add app name conflicts to trusted cluster troubleshooting
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  docs/pages/zero-trust-access/management/admin/trustedclusters.mdx
Labels: documentation, backport, size/sm, no-changelog

#59904 [v18] [docs] Add app name conflicts to trusted cluster troubleshooting
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  docs/pages/zero-trust-access/management/admin/trustedclusters.mdx
Labels: documentation, backport, size/sm, no-changelog

#59900 fix(app): prevent premature removal of app servers from session cache
  lib/web/app/transport.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59779 Support editing the `default_relay_addr` trait in `tctl users`
  api/types/user.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
  tool/tsh/common/tsh.go
Labels: tsh, tctl, size/sm, no-changelog

#59951 [v18] Skip AWS E2E tests to unblock merges
  e2e/aws/databases_test.go
  e2e/aws/eks_test.go
Labels: backport, size/sm, no-changelog

#59964 [v18] Tweak MWI documentation tiles (#59950)
  docs/pages/machine-workload-identity/machine-workload-identity.mdx
Labels: documentation, backport, size/sm, no-changelog

#58904 Add a button to copy session ID to session recording tiles
  web/packages/shared/components/CopyButton/CopyButton.story.tsx
  web/packages/shared/components/CopyButton/CopyButton.test.tsx
  web/packages/shared/components/CopyButton/CopyButton.tsx
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
  web/packages/shared/components/UnifiedResources/ListView/ResourceListItem.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.tsx
  web/packages/teleport/src/Bots/Details/Instance.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
  web/packages/teleport/src/SessionRecordings/list/RecordingItem.tsx
  web/packages/teleport/src/WorkloadIdentity/List/WorkloadIdentitiesList.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#59954 [v16] fix(app): prevent premature removal of app servers from session cache
  lib/web/app/transport.go
Labels: backport, size/sm

#59702 [flaky] TestReplaceHTTPResponse to use synctest
  lib/utils/mcputils/http_test.go
Labels: size/sm, no-changelog

#59876 [v16] Move ec2.go from lib/utils to lib/utils/aws
  lib/auth/join/join.go
  lib/auth/join_ec2.go
  lib/inventory/metadata/metadata.go
  lib/utils/aws/ec2.go
  lib/utils/hostid/hostid.go
Labels: backport, size/sm, no-changelog

#59877 [v17] Move ec2.go from lib/utils to lib/utils/aws
  lib/auth/join/join.go
  lib/auth/join_ec2.go
  lib/inventory/metadata/metadata.go
  lib/utils/aws/ec2.go
  lib/utils/hostid/hostid.go
Labels: backport, size/sm, no-changelog

#59528 [v16] Unified resources card: Add a gap between the name and the button
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
Labels: ui, backport, size/sm, no-changelog

#59878 [v18] Move ec2.go from lib/utils to lib/utils/aws
  lib/auth/join/join.go
  lib/auth/join_ec2.go
  lib/inventory/metadata/metadata.go
  lib/utils/aws/ec2.go
  lib/utils/hostid/hostid.go
Labels: backport, size/sm, no-changelog

#59526 [v18] Unified resources card: Add a gap between the name and the button
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
Labels: ui, backport, size/sm, no-changelog

#59667 Make sure we wait for all services before being ready
  integration/helpers/instance.go
  integration/readiness_test.go
  lib/kube/proxy/server.go
  lib/service/db.go
  lib/service/desktop.go
  lib/service/discovery.go
  lib/service/kubernetes.go
  lib/service/relay.go
  lib/service/service.go
  lib/service/state.go
  lib/service/state_test.go
  lib/srv/app/server.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59788 [v17] Refactor tracessh.Client to cover untraced paths - session requests
  api/observability/tracing/ssh/client.go
  api/observability/tracing/ssh/client_test.go
  api/observability/tracing/ssh/ssh_test.go
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
  lib/client/session.go
  lib/web/sessions.go
  lib/web/terminal.go
Labels: backport, size/md, no-changelog

#59948 [v16] Update pnpm to 10.18.0
  package.json
Labels: backport, size/sm, no-changelog

#59947 [v17] Update pnpm to 10.18.0
  package.json
Labels: backport, size/sm, no-changelog

#59986 Fix tf windows example, undo commit mistake
  docs/pages/reference/infrastructure-as-code/terraform-provider/resources/dynamic_windows_desktop.mdx
  integrations/terraform/examples/resources/teleport_dynamic_windows_desktop/resource.tf
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#59977 [teleport-update] Fix SELinux warning and error breaking `teleport-update remove`
  lib/selinux/selinux_linux.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18, selinux

#59940 Revert connectrpc.com/connect Go module to v1.18.1
  go.mod
  go.sum
Labels: size/sm, no-changelog

#59921 fix: ensure all tsh spans are rooted to the command
  tool/tsh/common/tsh.go
Labels: tsh, size/sm, no-changelog, backport/branch/v18

#58939 docs: new design for identity security docs homepage
  docs/img/identity-security/identity-security-hero.png
  docs/pages/identity-security/identity-security.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59972 [v18] Fix error reporting in EC2 auto discovery
  lib/srv/server/ssm_install.go
  lib/srv/server/ssm_install_test.go
Labels: backport, size/sm

#59993 [v18] fix: ensure all tsh spans are rooted to the command
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#59978 [v18] Revert "Skip AWS E2E tests to unblock merges (#59951)"
  e2e/aws/databases_test.go
  e2e/aws/eks_test.go
Labels: backport, size/sm, no-changelog

#59709 feat(webui): Edit bot description
  lib/auth/machineid/machineidv1/bot_service.go
  lib/auth/machineid/machineidv1/machineidv1_test.go
  lib/web/apiserver.go
  lib/web/machineid.go
  lib/web/machineid_test.go
  web/packages/shared/components/Validation/rules.test.ts
  web/packages/shared/components/Validation/rules.ts
  web/packages/teleport/src/Bots/Details/BotDetails.story.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.test.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.tsx
  web/packages/teleport/src/Bots/Edit/EditDialog.story.tsx
  web/packages/teleport/src/Bots/Edit/EditDialog.test.tsx
  web/packages/teleport/src/Bots/Edit/EditDialog.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/bot/consts.ts
  web/packages/teleport/src/services/bot/types.ts
  web/packages/teleport/src/test/helpers/bots.ts
Labels: ui, machine-id, size/md, backport/branch/v17, backport/branch/v18

#59981 [v18] Fix sftp handling of colons in paths
  lib/client/api.go
  lib/sshutils/sftp/parse.go
  lib/sshutils/sftp/parse_test.go
Labels: backport, size/sm

#59998 [v18] docs: new design for identity security docs homepage #58939
  docs/img/identity-security/identity-security-hero.png
  docs/pages/identity-security/identity-security.mdx
Labels: documentation, backport, size/md, no-changelog

#59924 [v18] Fix issue with dry-run access_request.spec.expires overwrite
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm

#60015 [v18] Fix tf windows example, undo commit mistake
  docs/pages/reference/infrastructure-as-code/terraform-provider/resources/dynamic_windows_desktop.mdx
  integrations/terraform/examples/resources/teleport_dynamic_windows_desktop/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#59994 [v18] Fix `tcp scp` getting stuck in symlink loops
  lib/srv/forward/sftp.go
  lib/sshutils/sftp/http.go
  lib/sshutils/sftp/local.go
  lib/sshutils/sftp/sftp.go
  lib/sshutils/sftp/sftp_test.go
  tool/teleport/common/sftp.go
Labels: backport, size/md

#60005 Add "Overhauled Bot Instances Dashboard" to 18.4.0 Upcoming Releases
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#60013 Update link to downloads page in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/CompatibilityWarning.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59989 [v18] core scope pinning logic
  lib/auth/apiserver.go
  lib/auth/auth.go
  lib/auth/auth_login_test.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/clt.go
  lib/auth/bot.go
  lib/auth/export_test.go
  lib/auth/grpcserver.go
  lib/auth/methods.go
  lib/auth/sessions.go
  lib/auth/trust/trustv1/service.go
  lib/authz/permissions.go
  lib/authz/scoped.go
  lib/backend/dynamo/atomicwrite.go
  lib/backend/test/atomicwrite_shim.go
  lib/client/api.go
  lib/client/api_login_test.go
  lib/client/profile.go
  lib/client/weblogin.go
  lib/inventory/inventory.go
  lib/scopes/pinning/pinning.go
  lib/scopes/scopes.go
  lib/scopes/scopes_test.go
  lib/service/service.go
  lib/services/access_checker.go
  lib/services/readonly/cache.go
  lib/services/scoped_access_checker.go
  lib/services/split_access_checker.go
  lib/services/unified_resource.go
  lib/utils/once/keyedvalue.go
  lib/utils/once/keyedvalue_test.go
  lib/versioncontrol/target.go
  lib/versioncontrol/upgradewindow/upgradewindow.go
  lib/web/apiserver.go
  lib/web/sessions.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/lg, no-changelog

#59983 [v16] Fix sftp handling of colons in paths
  lib/client/api.go
  lib/sshutils/sftp/parse.go
  lib/sshutils/sftp/parse_test.go
Labels: backport, size/sm

#60017 MWI: Add `tctl` get and delete mappings for `AutoUpdateBotInstanceReport`
  api/client/client.go
  lib/services/resource.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
Labels: tctl, machine-id, size/sm, no-changelog

#59565 Add health checks to Kubernetes agent and proxy
  api/types/kubernetes_server.go
  lib/auth/authclient/api.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/healthcheck/config.go
  lib/healthcheck/config_test.go
  lib/healthcheck/manager.go
  lib/healthcheck/worker.go
  lib/healthcheck/worker_experimental_test.go
  lib/kube/grpc/utils_test.go
  lib/kube/proxy/cluster_details.go
  lib/kube/proxy/server.go
  lib/kube/proxy/server_test.go
  lib/kube/proxy/utils_test.go
  lib/kube/proxy/watcher.go
  lib/service/kubernetes.go
  lib/service/service.go
  lib/services/health_check_config.go
  lib/services/health_check_config_test.go
  lib/services/unified_resource.go
  lib/services/unified_resource_test.go
  lib/web/apiserver_test.go
Labels: kubernetes-access, size/md, no-changelog, health-check

#60023 [v17] Update link to downloads page in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/CompatibilityWarning.tsx
Labels: ui, backport, size/sm, no-changelog

#60022 [v18] Update link to downloads page in Connect
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/CompatibilityWarning.tsx
Labels: ui, backport, size/sm, no-changelog

#59774 MWI: Add `teleport_bot_instances` metric
  docs/pages/includes/metrics.mdx
  lib/auth/auth.go
  lib/auth/machineid/machineidv1/auto_update_version_reporter.go
  lib/auth/machineid/machineidv1/auto_update_version_reporter_test.go
  metrics.go
Labels: documentation, observability, machine-id, size/md

#58930 docs: add required roles for client managed updates
  docs/pages/upgrading/client-tools-managed-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#60012 First round of changes to MWI Getting Started guide based on UX testing
  docs/pages/machine-workload-identity/getting-started.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#60046 [v18] EC2 Auto Discovery: retry matchers
  lib/srv/server/ec2_watcher.go
  lib/srv/server/ec2_watcher_test.go
Labels: backport, size/sm

#59820 [api] Add ListKubernetesClusters
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  build.assets/tooling/cmd/buf-plugin-linters/default.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/authclient/api.go
  lib/auth/grpcserver.go
  lib/cache/kube.go
  lib/cache/kube_test.go
  lib/services/kubernetes.go
  lib/services/local/kube.go
  lib/services/local/kube_test.go
  lib/services/watcher.go
  lib/srv/discovery/discovery_eks_test.go
  lib/srv/discovery/kube_integration_watcher.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/md, discovery, backport/branch/v16, backport/branch/v17, backport/branch/v18
