Repository gravitational/teleport, pull requests merged in 2025-06, with the labels that each got.

#55228 [vnet] feat: write VNet SSH keys to TELEPORT_HOME
  api/utils/keypaths/keypaths.go
  gen/proto/go/teleport/lib/vnet/v1/client_application_service.pb.go
  gen/proto/go/teleport/lib/vnet/v1/client_application_service_grpc.pb.go
  lib/client/keystore.go
  lib/vnet/admin_process_common.go
  lib/vnet/admin_process_darwin.go
  lib/vnet/admin_process_windows.go
  lib/vnet/client_application_service.go
  lib/vnet/client_application_service_client.go
  lib/vnet/opensshconfig.go
  lib/vnet/ssh_provider.go
  lib/vnet/vnet_test.go
  proto/teleport/lib/vnet/v1/client_application_service.proto
Labels: backport-required, size/md, no-changelog, vnet

#55239 [vnet] feat: write OpenSSH-compatible config file for VNet SSH
  api/utils/keypaths/keypaths.go
  lib/vnet/opensshconfig.go
  lib/vnet/opensshconfig_test.go
  lib/vnet/user_process.go
  lib/vnet/user_process_darwin.go
  lib/vnet/user_process_windows.go
Labels: backport-required, size/md, no-changelog

#55278 [v18] Avoid unnecessary unified resources re-renders
  web/packages/design/src/utils/testing.tsx
  web/packages/shared/components/SlidingSidePanel/InfoGuide/InfoGuideContext.tsx
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.test.tsx
Labels: ui, backport, size/sm, no-changelog

#55353 [v18] Fix dynamoDB tests
  lib/backend/dynamo/dynamodbbk_test.go
Labels: backport, size/sm, no-changelog

#55193 [v15] Use the correct label for new cache metrics
  lib/cache/cache.go
Labels: backport, size/sm

#55389 [v17] docs: set step numbers in gitlab sso instrs
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, backport, size/sm, no-changelog

#55388 [v18] docs: set step numbers in gitlab sso instrs
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, backport, size/sm, no-changelog

#55392 [v15] docs: set step numbers in gitlab sso instrs
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
Labels: documentation, backport, size/sm, no-changelog

#55391 [v16] docs: set step numbers in gitlab sso instrs
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, backport, size/sm, no-changelog

#55308 Slack Plugin: Remove trailing dot
  integrations/access/accessrequest/message.go
  integrations/access/accessrequest/message_test.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55295 [v18] Backport Kubernetes rbac docs
  docs/pages/admin-guides/access-controls/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/controls.mdx
  docs/pages/includes/role-spec.mdx
  docs/pages/reference/access-controls/roles.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/md, no-changelog

#55400 [v17] remove identity center and provisioning state rpc service
  api/client/client.go
  api/gen/proto/go/teleport/identitycenter/v1/identitycenter_service.pb.go
  api/gen/proto/go/teleport/identitycenter/v1/identitycenter_service_grpc.pb.go
  api/gen/proto/go/teleport/provisioning/v1/provisioning_service.pb.go
  api/gen/proto/go/teleport/provisioning/v1/provisioning_service_grpc.pb.go
  api/proto/teleport/identitycenter/v1/identitycenter_service.proto
  api/proto/teleport/provisioning/v1/provisioning_service.proto
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/cache/identitycenter.go
  lib/cache/identitycenter_test.go
  lib/services/identitycenter.go
  lib/services/local/identitycenter.go
  lib/services/local/identitycenter_test.go
  lib/services/local/provisioningstates.go
  lib/services/provisioningstates.go
Labels: backport, size/sm

#55374 Support Azure CLI (`az`) version `2.73.0` and newer.
  api/types/constants.go
  lib/srv/alpnproxy/azure_token_middleware.go
  lib/srv/alpnproxy/azure_token_middleware_test.go
  lib/srv/alpnproxy/forward_proxy.go
  lib/srv/app/azure/handler.go
  lib/web/app/transport.go
  tool/tsh/common/app.go
  tool/tsh/common/app_azure.go
  tool/tsh/common/app_azure_test.go
Labels: tsh, application-access, size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55419 Add Identity Security IAC enabled to storage service
  web/packages/teleport/src/services/storageService/storageService.ts
  web/packages/teleport/src/services/storageService/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v18

#55410 build: Update master for v19
  Makefile
  api/version.go
  build.assets/images.mk
  docs/preflight.md
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
  lib/auth/grpcserver_test.go
Labels: documentation, size/sm, no-changelog

#55383 [v18] feat: add SQS, S3, and KMS support for AWS Access Graph integration
  lib/cloud/aws/policy_statements.go
  lib/config/configuration.go
  lib/integrations/awsoidc/accessgraph_sync.go
  lib/integrations/awsoidc/accessgraph_sync_test.go
  lib/integrations/awsoidc/testdata/TestAccessGraphAWSIAMConfigWithActivityCenterOuput.golden
  lib/web/integrations_awsoidc.go
  tool/teleport/common/integration_configure.go
  tool/teleport/common/teleport.go
Labels: backport, size/md, no-changelog

#54431 Initial PostgreSQL MCP support
  lib/client/db/mcp/errors.go
  lib/client/db/mcp/mcp.go
  lib/client/db/mcp/server.go
  lib/client/db/mcp/server_test.go
  lib/client/db/postgres/mcp/mcp.go
  lib/client/db/postgres/mcp/mcp_test.go
  lib/client/local_proxy_middleware.go
  lib/client/local_proxy_middleware_test.go
  lib/client/mcp/uri.go
  lib/client/mcp/uri_test.go
  lib/utils/cli.go
  lib/utils/listener/memory.go
  lib/utils/listener/memory_test.go
  lib/utils/log/log.go
  tool/tsh/common/logger.go
  tool/tsh/common/mcp.go
  tool/tsh/common/mcp_db.go
  tool/tsh/common/mcp_db_test.go
  tool/tsh/common/tsh.go
Labels: tsh, size/xl, no-changelog

#55432 ci: Update master to use :teleport19 buildboxes
  .github/workflows/aws-e2e-tests-non-root.yaml
  .github/workflows/benchmark-code-nonroot.yaml
  .github/workflows/benchmark-code-root.yaml
  .github/workflows/bloat.yaml
  .github/workflows/e2e-tests.yaml
  .github/workflows/flaky-tests.yaml
  .github/workflows/integration-tests-non-root.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/kube-integration-tests-non-root.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/lint.yaml
  .github/workflows/os-compatibility-test.yaml
Labels: size/sm, no-changelog

#55289 Unified resources: Make "Show requestable resources" clickable
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55350 Ensure sharing remains enabled if the initial desktop connection attempt fails
  web/packages/shared/components/DesktopSession/ActionMenu.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/TopBar.tsx
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
Labels: test-plan-problem, ui, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55422 Ensure correct workspace is set before opening desktop document
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55390 Add focus-visible style to Toggle
  web/packages/design/src/Toggle/Toggle.story.tsx
  web/packages/design/src/Toggle/Toggle.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55450 Connect login form: Refocus password field on submission error
  web/packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.test.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55307 label calling binary's path for SELinux
  lib/selinux/selinux.go
  lib/selinux/selinux_linux.go
  lib/selinux/selinux_others.go
  lib/selinux/selinux_test.go
  lib/selinux/teleport_ssh.fc.tmpl
  tool/teleport/common/teleport.go
Labels: size/sm, no-changelog, backport/branch/v18

#55481 ci: Use :teleport19 buildbox in lint RFD job
  .github/workflows/lint.yaml
Labels: size/sm, no-changelog

#55492 Release 15.5.2
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  docs/cspell.json
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, size/sm, no-changelog

#55401 Fix validation in PIV PIN and PUK form in Connect, increase new PIN timeout
  api/utils/keys/piv/yubikey.go
  web/packages/teleterm/src/ui/ModalsHost/modals/HardwareKeys/ChangePin.tsx
Labels: ui, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55306 MCP access part 7: MCP app in Web UI
  lib/web/ui/app.go
  web/packages/shared/components/UnifiedResources/shared/guessAppIcon.ts
  web/packages/shared/components/UnifiedResources/shared/viewItemsFactory.ts
  web/packages/shared/components/UnifiedResources/types.ts
  web/packages/shared/services/types.ts
  web/packages/teleport/src/Apps/MCPAppConnectDialog.story.tsx
  web/packages/teleport/src/Apps/MCPAppConnectDialog.tsx
  web/packages/teleport/src/Apps/fixtures/index.ts
  web/packages/teleport/src/UnifiedResources/ResourceActionButton.story.tsx
  web/packages/teleport/src/UnifiedResources/ResourceActionButton.tsx
  web/packages/teleport/src/services/apps/apps.test.ts
  web/packages/teleport/src/services/apps/makeApps.ts
  web/packages/teleport/src/services/apps/types.ts
  web/packages/teleterm/src/services/tshd/app.ts
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
Labels: ui, size/md, no-changelog, MCP

#55479 Fix InitLogger call expecting single return type
  tool/tsh/common/vnet_daemon_darwin.go
Labels: tsh, size/sm, no-changelog

#55411 MWI: Fix missing O_CLOEXEC in `botfs.openSecure()` and other issues
  lib/tbot/botfs/botfs.go
  lib/tbot/botfs/fs_linux.go
  lib/tbot/botfs/fs_unix.go
  lib/tbot/botfs/fs_windows.go
Labels: machine-id, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55473 [v17] Connect login form: Refocus password field on submission error
  web/packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.test.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
Labels: ui, backport, size/sm, no-changelog

#55511 [v17] Make `<b>` and `<strong>` bolder in Connect
  web/packages/teleterm/src/ui/ThemeProvider/globals.ts
Labels: ui, backport, size/sm, no-changelog

#55367 add Identity Activity Center documentation and Terraform setup for AWS infrastructure
  docs/cspell.json
  docs/pages/admin-guides/access-controls/okta/okta.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/identity-activity-center.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/self-hosted-helm.mdx
  docs/pages/admin-guides/deploy-a-cluster/access-graph/self-hosted.mdx
  docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/github.mdx
  docs/pages/admin-guides/teleport-policy/integrations/teleport.mdx
  docs/pages/admin-guides/teleport-policy/teleport-policy.mdx
  docs/pages/includes/config-reference/identity-security.yaml
  docs/pages/includes/policy/identity-activity-center.mdx
  docs/pages/reference/identity-security-config.mdx
  examples/identity-activity-center/README.md
  examples/identity-activity-center/identity_activity_center.tf
  examples/identity-activity-center/policy.tf
  examples/identity-activity-center/variables.tf
Labels: documentation, size/lg, no-changelog, backport/branch/v18

#53036 Add location constraint when creating aws buckets via s3handler
  lib/events/s3sessions/s3client.go
  lib/events/s3sessions/s3handler.go
  lib/events/s3sessions/s3handler_test.go
Labels: audit-log, size/sm, no-changelog, backport/branch/v17

#55455 [v16] Ensure sharing remains enabled if the initial desktop connection attempt fails
  web/packages/shared/components/DesktopSession/ActionMenu.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/TopBar.tsx
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
Labels: ui, backport, size/md, no-changelog

#55477 [v16] Organize the sidebar to aid practitioner focus
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#55516 [v17] Connect: minor style improvements
  web/packages/teleterm/src/ui/App.test.tsx
  web/packages/teleterm/src/ui/ClusterLogout/ClusterLogout.tsx
  web/packages/teleterm/src/ui/DocumentsReopen/DocumentsReopen.tsx
  web/packages/teleterm/src/ui/HeadlessAuthn/HeadlessPrompt/HeadlessPrompt.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/ChangeAccessRequestKind/ChangeAccessRequestKind.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/HardwareKeys/ChangePin.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/HardwareKeys/OverwriteSlot.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/ReAuthenticate/ReAuthenticate.tsx
  web/packages/teleterm/src/ui/ModalsHost/modals/UsageData/UsageData.tsx
  web/packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClustersFilterableList.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionsFilterableList.tsx
  web/packages/teleterm/src/ui/components/FilterableList/FilterableList.test.tsx
Labels: ui, backport, size/sm, no-changelog

#55494 docs: remove note about kube joining not working in the web UI
  docs/pages/admin-guides/access-controls/guides/joining-sessions.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55453 [v18] Ensure sharing remains enabled if the initial desktop connection attempt fails
  web/packages/shared/components/DesktopSession/ActionMenu.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/TopBar.tsx
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
Labels: test-plan-problem, ui, backport, size/sm

#55452 [v17] Ensure correct workspace is set before opening desktop document
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.ts
Labels: ui, backport, size/sm, no-changelog

#55510 [v18] Make `<b>` and `<strong>` bolder in Connect
  web/packages/teleterm/src/ui/ThemeProvider/globals.ts
Labels: ui, backport, size/sm, no-changelog

#55507 [v18] Fix validation in PIV PIN and PUK form in Connect, increase new PIN timeout
  api/utils/keys/piv/yubikey.go
  web/packages/teleterm/src/ui/ModalsHost/modals/HardwareKeys/ChangePin.tsx
Labels: ui, backport, size/sm

#55526 [v18] Fix typo in Join Methods documentation page
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/sm, no-changelog

#55470 [v16] Add Stack component
  web/packages/design/src/Flex/Flex.story.js
  web/packages/design/src/Flex/Flex.tsx
  web/packages/design/src/Flex/Stack.story.tsx
  web/packages/design/src/Flex/index.ts
  web/packages/design/src/index.ts
  web/packages/design/src/system/index.ts
  web/packages/design/src/theme/themes/sharedStyles.ts
  web/packages/design/src/theme/themes/types.ts
Labels: ui, backport, size/md, no-changelog

#55525 [v17] Fix typo in Join Methods documentation page
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/sm, no-changelog

#55393 MWI: Terraform Provider - Skeleton
  .github/workflows/flaky-tests.yaml
  .github/workflows/unit-tests-integrations.yaml
  Makefile
  integrations/Makefile
  integrations/terraform-mwi/LICENSE
  integrations/terraform-mwi/Makefile
  integrations/terraform-mwi/README.md
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/main.go
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_data_source_test.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource_test.go
  integrations/terraform-mwi/provider/provider.go
  integrations/terraform-mwi/provider/provider_test.go
Labels: size/lg, no-changelog, backport/branch/v17, backport/branch/v18

#55486 [v18] label calling binary's path for SELinux
  lib/selinux/selinux.go
  lib/selinux/selinux_linux.go
  lib/selinux/selinux_others.go
  lib/selinux/selinux_test.go
  lib/selinux/teleport_ssh.fc.tmpl
  tool/teleport/common/teleport.go
Labels: backport, size/sm, no-changelog

#55092 Teleport Connect: Support requiring reason and custom reason prompts
  gen/proto/go/teleport/lib/teleterm/v1/access_request.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/access_request_pb.ts
  lib/teleterm/apiserver/handler/handler_access_requests.go
  proto/teleport/lib/teleterm/v1/access_request.proto
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/DocumentAccessRequests.story.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.test.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55527 [v16] docs: remove note about kube joining not working in the web UI
  docs/pages/admin-guides/access-controls/guides/joining-sessions.mdx
Labels: documentation, backport, size/sm, no-changelog

#55528 [v17] docs: remove note about kube joining not working in the web UI
  docs/pages/admin-guides/access-controls/guides/joining-sessions.mdx
Labels: documentation, backport, size/sm, no-changelog

#55529 [v18] docs: remove note about kube joining not working in the web UI
  docs/pages/admin-guides/access-controls/guides/joining-sessions.mdx
Labels: documentation, backport, size/sm, no-changelog

#55466 [v16] Document `tbot` Identity Service `allow_reissue` flag
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#55467 [v17] Document `tbot` Identity Service `allow_reissue` flag
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#55458 [v16] Add focus-visible style to Toggle
  web/packages/design/src/Toggle/Toggle.story.tsx
  web/packages/design/src/Toggle/Toggle.tsx
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
Labels: ui, backport, size/sm, no-changelog

#55551 terraform: remove deprecated fields in iac example
  examples/identity-activity-center/identity_activity_center.tf
Labels: size/sm, no-changelog

#55242 [v17] Add AWS Roles Anywhere as valid origin label
  api/types/common/constants.go
Labels: backport, size/sm, no-changelog

#55559 [v17] Fix database web UI connect dialog not allowing users to type/select database username
  lib/services/role.go
  lib/services/role_test.go
  lib/web/ui/server.go
  lib/web/ui/server_test.go
Labels: backport, size/sm

#55522 [v17] Fix six Vale warnings
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/enroll-resources/machine-id/deployment/azure-devops.mdx
Labels: documentation, backport, size/sm, no-changelog

#55566 Fix missing permissions in operator role
  examples/chart/teleport-cluster/charts/teleport-operator/templates/role.yaml
Labels: helm, size/sm, backport/branch/v18

#55504 [v16] MWI: Fix missing O_CLOEXEC in `botfs.openSecure()` and other issues (#55411)
  lib/tbot/botfs/botfs.go
  lib/tbot/botfs/fs_linux.go
  lib/tbot/botfs/fs_unix.go
  lib/tbot/botfs/fs_windows.go
Labels: backport, machine-id, size/sm

#55414 exporter: Remove clockwork Clock
  lib/events/export/date_exporter.go
  lib/events/export/exporter.go
Labels: audit-log, size/sm, no-changelog

#55565 Update Teleport 18 release week
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#55582 [v17] Okta: Add more test coverage for Access Requests
  lib/auth/auth_with_roles_test.go
Labels: backport, size/sm, no-changelog

#55579 [docs] Add missing quotes to variables.auto.tfvars
  docs/pages/admin-guides/deploy-a-cluster/access-graph/identity-activity-center.mdx
Labels: documentation, size/sm, no-changelog

#55212 [v17] keystore: add support for aws kms multi-region key replication (#53927)
  lib/auth/init.go
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/aws_kms_test.go
  lib/auth/keystore/keystore_test.go
  lib/auth/keystore/manager.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/servicecfg/auth.go
Labels: backport, size/md

#55057 Refactor prerequisite partials
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
  docs/pages/admin-guides/access-controls/idps/saml-attribute-mapping.mdx
  docs/pages/admin-guides/access-controls/idps/saml-gcp-workforce-identity-federation.mdx
  docs/pages/admin-guides/access-controls/idps/saml-grafana.mdx
  docs/pages/admin-guides/access-controls/idps/saml-guide.mdx
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/admin-guides/access-controls/sso/adfs.mdx
  docs/pages/admin-guides/access-controls/sso/azuread.mdx
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/access-controls/sso/google-workspace.mdx
  docs/pages/admin-guides/access-controls/sso/keycloak.mdx
  docs/pages/admin-guides/access-controls/sso/oidc.mdx
  docs/pages/admin-guides/access-controls/sso/okta.mdx
  docs/pages/admin-guides/access-controls/sso/one-login.mdx
  docs/pages/admin-guides/api/access-plugin.mdx
  docs/pages/admin-guides/infrastructure-as-code/managing-resources/login-rules-terraform.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/guides/github-integration.mdx
  docs/pages/enroll-resources/agents/aws-ec2.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/oracle-exadata.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/recording-proxy-mode.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/get-started.mdx
  docs/pages/identity-governance/access-lists/guide.mdx
  docs/pages/identity-governance/access-lists/nested-access-lists.mdx
  docs/pages/identity-governance/access-request-plugins/datadog-hosted.mdx
  docs/pages/identity-governance/access-request-plugins/servicenow.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-email.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/identity-governance/access-requests/automatic-reviews.mdx
  docs/pages/identity-governance/access-requests/resource-requests.mdx
  docs/pages/identity-governance/access-requests/role-requests.mdx
  docs/pages/identity-governance/device-trust/device-management.mdx
  docs/pages/identity-governance/device-trust/enforcing-device-trust.mdx
  docs/pages/identity-governance/device-trust/guide.mdx
  docs/pages/identity-governance/device-trust/jamf-integration.mdx
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
  docs/pages/identity-governance/okta/guided-sso.mdx
  docs/pages/identity-governance/okta/scim-integration.mdx
  docs/pages/identity-governance/okta/user-sync.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/self-hosted-prereqs-tabs.mdx
  docs/pages/includes/tctl-tsh-prerequisite.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55553 Fix example Access Request plugin values files
  examples/resources/plugins/teleport-discord-helm.yaml
  examples/resources/plugins/teleport-msteams-helm.yaml
  examples/resources/plugins/teleport-slack-helm.yaml
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55607 [v18] Correctly scope member counts per Access List
  lib/cache/access_list.go
  lib/cache/access_list_test.go
  lib/cache/cache_test.go
Labels: backport, size/sm, no-changelog

#55496 Updating default shell when changed for existing users
  integration/hostuser_test.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_linux.go
  lib/srv/usermgmt_test.go
  lib/utils/host/hostusers.go
Labels: size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55622 [docs] Restructuring agent homepage links
  docs/pages/enroll-resources/application-access/application-access.mdx
  docs/pages/enroll-resources/auto-discovery/auto-discovery.mdx
  docs/pages/enroll-resources/database-access/database-access.mdx
  docs/pages/enroll-resources/desktop-access/desktop-access.mdx
  docs/pages/enroll-resources/kubernetes-access/kubernetes-access.mdx
  docs/pages/enroll-resources/machine-id/machine-id.mdx
  docs/pages/enroll-resources/server-access/server-access.mdx
  docs/pages/enroll-resources/workload-identity/workload-identity.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v18

#55596 Update Identity Center `Okta -> Teleport` migration docs
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/migrating-identity-center-from-okta-to-teleport.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55256 add documentation for SSH SELinux module
  docs/cspell.json
  docs/pages/admin-guides/management/security/selinux.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v18

#55561 [docs] database access minor updates v18 release testing
  docs/img/database-access/guides/create-redshift-iam-role-policy.png
  docs/pages/enroll-resources/database-access/auto-user-provisioning/mariadb.mdx
  docs/pages/enroll-resources/database-access/auto-user-provisioning/mysql.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-opensearch.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/postgres-redshift.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/redshift-serverless.mdx
  docs/pages/includes/database-access/auto-user-provisioning/mysql-default-database-note.mdx
  docs/pages/includes/database-access/reference/aws-iam/redshift/role-as-user-policy.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55563 [docs] break ElastiCache and MemoryDB guide and add Valkey
  docs/cspell.json
  docs/img/database-access/guides/aws_memorydb_cloud.png
  docs/img/database-access/guides/aws_memorydb_selfhosted.png
  docs/pages/enroll-resources/auto-discovery/databases/databases.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-memorydb.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/enroll-aws-databases.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/redis-aws.mdx
  docs/pages/enroll-resources/database-access/faq.mdx
  docs/pages/includes/config-reference/database-config.yaml
  docs/pages/includes/database-access/aws-db-iam-policy-picker.mdx
  docs/pages/includes/database-access/aws-redis-how-it-works.mdx
  docs/pages/includes/database-access/aws-redis-no-auth.mdx
  docs/pages/includes/database-access/aws-redis-tsh-db-user-auth.mdx
  docs/pages/includes/database-access/reference/aws-iam/elasticache/access-policy.mdx
  docs/pages/includes/discovery/aws-db-discovery-config-picker.mdx
  docs/pages/includes/discovery/aws-db-discovery-config.mdx
  docs/pages/includes/discovery/aws-db-iam-policy-picker.mdx
  docs/pages/includes/discovery/discovery-config.yaml
  docs/pages/reference/agent-services/auto-discovery-reference/aws-iam.mdx
  docs/pages/reference/agent-services/database-access-reference/aws.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, size/md, no-changelog

#55273 Web: remove multi re-authn in a row when creating github bot
  web/packages/teleport/src/Bots/Add/GitHubActions/useGitHubFlow.tsx
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/resources/resource.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55632 docs: State that Proxy Peering and Trusted Clusters are not compatible
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/management/operations/proxy-peering.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55653 [v18] add documentation for SSH SELinux module
  docs/cspell.json
  docs/pages/admin-guides/management/security/selinux.mdx
Labels: documentation, backport, size/md, no-changelog

#55514 Clone tooltip child instead of wrapping it
  web/packages/design/src/Button/Button.tsx
  web/packages/design/src/Button/buttons.story.tsx
  web/packages/design/src/ButtonIcon/ButtonIcon.test.tsx
  web/packages/design/src/ButtonIcon/ButtonIcon.tsx
  web/packages/design/src/ButtonWithMenu/ButtonWithMenu.tsx
  web/packages/design/src/Menu/Menu.story.tsx
  web/packages/design/src/Popover/Popover.story.tsx
  web/packages/design/src/Tooltip/HoverTooltip.test.tsx
  web/packages/design/src/Tooltip/HoverTooltip.tsx
  web/packages/design/src/utils/mergeRefs.test.tsx
  web/packages/design/src/utils/mergeRefs.ts
  web/packages/shared/components/AwsLaunchButton/AwsLaunchButton.tsx
  web/packages/shared/components/ButtonSso/ButtonSso.tsx
  web/packages/shared/components/Controls/MultiselectMenu.tsx
  web/packages/shared/components/FieldMultiInput/FieldMultiInput.tsx
  web/packages/shared/components/FileTransfer/FileTransferActionBar.tsx
  web/packages/shared/components/MenuAction/MenuActionButton.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
  web/packages/shared/components/MenuLogin/MenuLogin.tsx
  web/packages/shared/components/MenuLoginWithActionMenu/MenuLoginWithActionMenu.tsx
  web/packages/shared/components/Select/Select.tsx
  web/packages/shared/components/Select/types.ts
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
  web/packages/shared/components/UnifiedResources/ListView/ResourceListItem.tsx
  web/packages/shared/components/UnifiedResources/shared/CopyButton.tsx
  web/packages/shared/components/UnifiedResources/shared/PinButton.tsx
  web/packages/shared/libs/mergeRefs.ts
  web/packages/teleport/src/BotInstances/List/BotInstancesList.tsx
  web/packages/teleport/src/Notifications/Notifications.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/TopBar/TopBar.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ConnectMyComputer/NavigationMenu.tsx
  web/packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedback.tsx
  web/packages/teleterm/src/ui/Tabs/TabItem.tsx
Labels: ui, size/sm, no-changelog

#55370 MCP access part 8: tsh mcp config
  lib/client/mcp/claude/config.go
  lib/client/mcp/claude/config_test.go
  tool/tsh/common/help.go
  tool/tsh/common/logger.go
  tool/tsh/common/mcp.go
  tool/tsh/common/mcp_app.go
  tool/tsh/common/mcp_app_test.go
  tool/tsh/common/mcp_db.go
  tool/tsh/common/mcp_test.go
  tool/tsh/common/tsh.go
Labels: tsh, size/lg, no-changelog, MCP

#55642 [v18] Update Identity Center `Okta -> Teleport` migration docs
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/migrating-identity-center-from-okta-to-teleport.mdx
Labels: documentation, backport, size/sm, no-changelog

#55657 tools: Query teleport-private in addition for latest releases
  build.assets/tooling/cmd/query-latest/main.go
  build.assets/tooling/cmd/query-latest/main_test.go
Labels: size/sm, no-changelog

#53943 ci: Make node buildbox runtime-architecture specific
  build.assets/images.mk
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55667 [v16] docs: State that Proxy Peering and Trusted Clusters are not compatible
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/management/operations/proxy-peering.mdx
Labels: documentation, backport, size/sm, no-changelog

#55661 [v16] Replace custom macOS notarization script with electron-builder's built-in notarization
  pnpm-lock.yaml
  web/packages/teleterm/README.md
  web/packages/teleterm/electron-builder-config.js
  web/packages/teleterm/notarize.js
  web/packages/teleterm/package.json
Labels: ui, backport, size/sm, no-changelog

#55659 [v18] Replace custom macOS notarization script with electron-builder's built-in notarization
  pnpm-lock.yaml
  web/packages/teleterm/README.md
  web/packages/teleterm/electron-builder-config.js
  web/packages/teleterm/notarize.js
  web/packages/teleterm/package.json
Labels: ui, backport, size/sm, no-changelog

#55681 Fix docs links in Test Plan issue template
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#55619 [v17] Elevate the Linux Demo guide
  docs/config.json
  docs/pages/admin-guides/infrastructure-as-code/managing-resources/trusted-cluster.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/enroll-resources.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/security/proxy-protocol.mdx
  docs/pages/admin-guides/migrate-plans.mdx
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/core-concepts.mdx
  docs/pages/get-started.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/self-hosted-prereqs-tabs.mdx
  docs/pages/index.mdx
  docs/pages/linux-demo.mdx
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#55745 docs: replacing blurry app access architecture image
  docs/img/application-access/architecture.png
  docs/img/application-access/architecture.svg
  docs/pages/enroll-resources/application-access/introduction.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55656 [docs] Add `hcl` language marker in the code blocks
  docs/pages/identity-security/access-graph/identity-activity-center.mdx
Labels: documentation, size/sm, no-changelog

#55733 [v16] kube: fix websocket fallback logic
  lib/kube/proxy/exec_test.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/roundtrip.go
  lib/kube/proxy/roundtrip_websocket.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
Labels: kubernetes-access, backport, size/sm

#55754 [v17] fix: retry first app connection in TestAppCommands
  tool/tsh/common/app_test.go
Labels: tsh, backport, size/sm, no-changelog

#55753 [v18] fix: retry first app connection in TestAppCommands
  tool/tsh/common/app_test.go
Labels: tsh, backport, size/sm, no-changelog

#55658 Support custom envvars in the loadtest node-agent chart
  assets/loadtest/helm/node-agent/templates/deployment.yaml
  assets/loadtest/helm/node-agent/values.yaml
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55716 [v16] Fix unasserted contains checks in tests
  lib/auth/machineid/machineidv1/spiffe_federation_service_test.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
Labels: backport, size/sm, no-changelog

#55728 [v16] allow OSS GitHub connector with public github endpoint
  lib/services/github.go
  lib/services/github_test.go
Labels: backport, size/sm

#55763 [v17] Support custom envvars in the loadtest node-agent chart
  assets/loadtest/helm/node-agent/templates/deployment.yaml
  assets/loadtest/helm/node-agent/values.yaml
Labels: backport, size/sm, no-changelog

#55764 fix: prevent panic in `httputils.Forwarder` on client cancellation
  lib/httplib/reverseproxy/reverse_proxy.go
  lib/httplib/reverseproxy/reverse_proxy_test.go
  lib/kube/proxy/resource_list.go
Labels: kubernetes-access, size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55762 [v18] Support custom envvars in the loadtest node-agent chart
  assets/loadtest/helm/node-agent/templates/deployment.yaml
  assets/loadtest/helm/node-agent/values.yaml
Labels: backport, size/sm, no-changelog

#55768 [v16] fix: prevent panic in `httputils.Forwarder` on client cancellation
  lib/httplib/reverseproxy/reverse_proxy.go
  lib/httplib/reverseproxy/reverse_proxy_test.go
  lib/kube/proxy/resource_list.go
Labels: kubernetes-access, backport, size/md

#55769 [v15] fix: prevent panic in `httputils.Forwarder` on client cancellation
  lib/httplib/reverseproxy/reverse_proxy.go
  lib/httplib/reverseproxy/reverse_proxy_test.go
  lib/kube/proxy/resource_list.go
Labels: kubernetes-access, backport, size/md

#55739 [v17] Add an Identity Security section
  docs/config.json
  docs/pages/admin-guides/management/guides/awsoidc-integration.mdx
  docs/pages/feature-matrix.mdx
  docs/pages/identity-security/access-graph/access-graph.mdx
  docs/pages/identity-security/access-graph/self-hosted-helm.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/identity-security/crown-jewels.mdx
  docs/pages/identity-security/identity-security.mdx
  docs/pages/identity-security/integrations/aws-sync.mdx
  docs/pages/identity-security/integrations/azure-sync.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/identity-security/integrations/gitlab.mdx
  docs/pages/identity-security/integrations/integrations.mdx
  docs/pages/identity-security/integrations/netiq.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/identity-security/policy-connections.mdx
  docs/pages/identity-security/policy-how-to-use.mdx
  docs/pages/identity-security/teleport-policy.mdx
  docs/pages/index.mdx
  docs/pages/reference/helm-reference/teleport-access-graph.mdx
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#55718 [v18] Fix link in the Agentless OpenSSH guide
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
Labels: documentation, backport, size/sm, no-changelog

#55606 [v18] Refactor prerequisite partials
  docs/pages/admin-guides/access-controls/access-lists/guide.mdx
  docs/pages/admin-guides/access-controls/access-lists/nested-access-lists.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/datadog-hosted.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/servicenow.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-email.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/admin-guides/access-controls/access-requests/automatic-reviews.mdx
  docs/pages/admin-guides/access-controls/access-requests/resource-requests.mdx
  docs/pages/admin-guides/access-controls/access-requests/role-requests.mdx
  docs/pages/admin-guides/access-controls/device-trust/device-management.mdx
  docs/pages/admin-guides/access-controls/device-trust/enforcing-device-trust.mdx
  docs/pages/admin-guides/access-controls/device-trust/guide.mdx
  docs/pages/admin-guides/access-controls/device-trust/jamf-integration.mdx
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
  docs/pages/admin-guides/access-controls/idps/saml-attribute-mapping.mdx
  docs/pages/admin-guides/access-controls/idps/saml-gcp-workforce-identity-federation.mdx
  docs/pages/admin-guides/access-controls/idps/saml-grafana.mdx
  docs/pages/admin-guides/access-controls/idps/saml-guide.mdx
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/admin-guides/access-controls/okta/app-and-group-sync.mdx
  docs/pages/admin-guides/access-controls/okta/guided-sso.mdx
  docs/pages/admin-guides/access-controls/okta/scim-integration.mdx
  docs/pages/admin-guides/access-controls/okta/user-sync.mdx
  docs/pages/admin-guides/access-controls/sso/adfs.mdx
  docs/pages/admin-guides/access-controls/sso/azuread.mdx
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/access-controls/sso/google-workspace.mdx
  docs/pages/admin-guides/access-controls/sso/keycloak.mdx
  docs/pages/admin-guides/access-controls/sso/oidc.mdx
  docs/pages/admin-guides/access-controls/sso/okta.mdx
  docs/pages/admin-guides/access-controls/sso/one-login.mdx
  docs/pages/admin-guides/api/access-plugin.mdx
  docs/pages/admin-guides/infrastructure-as-code/managing-resources/login-rules-terraform.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/guides/github-integration.mdx
  docs/pages/enroll-resources/agents/aws-ec2.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/oracle-exadata.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/recording-proxy-mode.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/get-started.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/self-hosted-prereqs-tabs.mdx
  docs/pages/includes/tctl-tsh-prerequisite.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#55608 [v17] Refactor prerequisite partials
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
  docs/pages/admin-guides/access-controls/idps/saml-attribute-mapping.mdx
  docs/pages/admin-guides/access-controls/idps/saml-gcp-workforce-identity-federation.mdx
  docs/pages/admin-guides/access-controls/idps/saml-grafana.mdx
  docs/pages/admin-guides/access-controls/idps/saml-guide.mdx
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/admin-guides/access-controls/sso/adfs.mdx
  docs/pages/admin-guides/access-controls/sso/azuread.mdx
  docs/pages/admin-guides/access-controls/sso/gitlab.mdx
  docs/pages/admin-guides/access-controls/sso/google-workspace.mdx
  docs/pages/admin-guides/access-controls/sso/keycloak.mdx
  docs/pages/admin-guides/access-controls/sso/oidc.mdx
  docs/pages/admin-guides/access-controls/sso/okta.mdx
  docs/pages/admin-guides/access-controls/sso/one-login.mdx
  docs/pages/admin-guides/api/access-plugin.mdx
  docs/pages/admin-guides/infrastructure-as-code/managing-resources/login-rules-terraform.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/terraform-cloud.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/guides/github-integration.mdx
  docs/pages/enroll-resources/agents/aws-ec2.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/oracle-exadata.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/recording-proxy-mode.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/identity-governance/access-lists/guide.mdx
  docs/pages/identity-governance/access-lists/nested-access-lists.mdx
  docs/pages/identity-governance/access-request-plugins/datadog-hosted.mdx
  docs/pages/identity-governance/access-request-plugins/servicenow.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-email.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/identity-governance/access-requests/resource-requests.mdx
  docs/pages/identity-governance/access-requests/role-requests.mdx
  docs/pages/identity-governance/device-trust/device-management.mdx
  docs/pages/identity-governance/device-trust/enforcing-device-trust.mdx
  docs/pages/identity-governance/device-trust/guide.mdx
  docs/pages/identity-governance/device-trust/jamf-integration.mdx
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
  docs/pages/identity-governance/okta/guided-sso.mdx
  docs/pages/identity-governance/okta/scim-integration.mdx
  docs/pages/identity-governance/okta/user-sync.mdx
  docs/pages/includes/commercial-prereqs-tabs.mdx
  docs/pages/includes/edition-prereqs-tabs-not-admin.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/self-hosted-prereqs-tabs.mdx
  docs/pages/includes/tctl-tsh-prerequisite.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#55742 [v15] Add an Identity Security section
  docs/config.json
  docs/pages/admin-guides/management/guides/awsoidc-integration.mdx
  docs/pages/identity-security/access-graph/access-graph.mdx
  docs/pages/identity-security/access-graph/self-hosted-helm.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/identity-security/crown-jewels.mdx
  docs/pages/identity-security/identity-security.mdx
  docs/pages/identity-security/integrations/aws-sync.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/identity-security/integrations/gitlab.mdx
  docs/pages/identity-security/integrations/integrations.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/identity-security/policy-connections.mdx
  docs/pages/identity-security/policy-how-to-use.mdx
  docs/pages/identity-security/teleport-policy.mdx
  docs/pages/index.mdx
  docs/pages/reference/helm-reference/teleport-access-graph.mdx
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#55562 Add ButtonSelect component
  web/packages/design/src/ButtonSelect/ButtonSelect.story.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.test.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.tsx
  web/packages/design/src/ButtonSelect/index.ts
  web/packages/design/src/index.ts
Labels: ui, size/md, no-changelog

#55747 [v15] docs: replacing blurry app access architecture image
  docs/img/application-access/architecture.png
  docs/img/application-access/architecture.svg
  docs/pages/enroll-resources/application-access/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#55756 [v16] fix: retry first app connection in TestAppCommands
  tool/tsh/common/app_test.go
  tool/tsh/common/hardware_key_test.go
Labels: tsh, backport, size/sm, no-changelog

#55748 [v16] docs: replacing blurry app access architecture image
  docs/img/application-access/architecture.png
  docs/img/application-access/architecture.svg
  docs/pages/enroll-resources/application-access/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#55267 Add Managed Updates reference + document agent reports
  docs/img/architecture/managed-updates-v2.svg
  docs/pages/includes/reference/resources/autoupdate_agent_report.mdx
  docs/pages/includes/reference/resources/autoupdate_agent_rollout.mdx
  docs/pages/includes/reference/resources/autoupdate_config.mdx
  docs/pages/includes/reference/resources/autoupdate_version.mdx
  docs/pages/reference/architecture/agent-update-management.mdx
  docs/pages/reference/managed-updates-v2.mdx
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55787 [v15] Add Managed Updates reference + document agent reports
  docs/img/architecture/managed-updates-v2.svg
  docs/pages/includes/reference/resources/autoupdate_agent_report.mdx
  docs/pages/includes/reference/resources/autoupdate_agent_rollout.mdx
  docs/pages/includes/reference/resources/autoupdate_config.mdx
  docs/pages/includes/reference/resources/autoupdate_version.mdx
  docs/pages/reference/architecture/agent-update-management.mdx
  docs/pages/reference/managed-updates-v2.mdx
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/md, no-changelog

#55784 [v18] Add Managed Updates reference + document agent reports
  docs/img/architecture/managed-updates-v2.svg
  docs/pages/includes/reference/resources/autoupdate_agent_report.mdx
  docs/pages/includes/reference/resources/autoupdate_agent_rollout.mdx
  docs/pages/includes/reference/resources/autoupdate_config.mdx
  docs/pages/includes/reference/resources/autoupdate_version.mdx
  docs/pages/reference/architecture/agent-update-management.mdx
  docs/pages/reference/managed-updates-v2.mdx
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/md, no-changelog

#55744 Adds `KindSAMLIdPServiceProvider` to `Cache.listResources`
  lib/auth/auth_with_roles_test.go
  lib/cache/cache.go
Labels: size/sm, no-changelog, backport/branch/v18

#55713 [v18] Fix small docs typos found during test plan
  docs/pages/admin-guides/access-controls/sso/oidc.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/ibm.mdx
Labels: documentation, backport, size/sm, no-changelog

#55416 MWI: Terraform Provider - Basic validation/attributes
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_data_source_test.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource_test.go
  integrations/terraform-mwi/provider/provider.go
Labels: size/lg, no-changelog, backport/branch/v17, backport/branch/v18

#55795 Fix typo in okta integration docs
  docs/pages/admin-guides/access-controls/sso/okta.mdx
Labels: documentation, size/sm, no-changelog

#55743 [v17] Add an EKS disaster recovery guide
  docs/cspell.json
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/disaster-recovery.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/helm-deployments.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/management/operations/backup-restore.mdx
  docs/pages/includes/self-hosted-helm-dns.mdx
Labels: documentation, backport, size/md, no-changelog

#55441 `relay_server` definition, CRUD api and caching
  api/client/client.go
  api/client/events.go
  api/client/proto/event.pb.go
  api/gen/proto/go/teleport/presence/v1/relay_server.pb.go
  api/gen/proto/go/teleport/presence/v1/service.pb.go
  api/gen/proto/go/teleport/presence/v1/service_grpc.pb.go
  api/proto/teleport/legacy/client/proto/event.proto
  api/proto/teleport/presence/v1/relay_server.proto
  api/proto/teleport/presence/v1/service.proto
  api/types/constants.go
  lib/auth/authclient/api.go
  lib/auth/presence/presencev1/service.go
  lib/authz/permissions.go
  lib/cache/cache.go
  lib/cache/cache_test.go
  lib/cache/collections.go
  lib/cache/generic_operations.go
  lib/cache/relay_server.go
  lib/services/local/events.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  lib/services/presence.go
  lib/services/relay_server.go
Labels: size/md, no-changelog

#55800 [v18] make: turn *LDFLAGS properly evaluated
  Makefile
  build.assets/kubectl-version/main.go
Labels: backport, size/sm, no-changelog

#55609 MWI: Implement RFD 216 - `tbot` resiliency improvements
  integrations/lib/embeddedtbot/bot_test.go
  integrations/operator/main.go
  lib/tbot/client/client.go
  lib/tbot/config/config.go
  lib/tbot/database_access.go
  lib/tbot/output_utils.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_spiffe_svid_output.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/service_workload_identity_jwt.go
  lib/tbot/service_workload_identity_x509.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  lib/tbot/workloadidentity/issue.go
  tool/tctl/common/terraform_command.go
Labels: tctl, machine-id, size/md, backport/branch/v17, backport/branch/v18

#55610 MWI: Wait for bot identity before starting services
  lib/tbot/loop.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_heartbeat.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/tbot.go
  lib/tbot/workloadidentity/crl_cache.go
  lib/tbot/workloadidentity/trust_bundle_cache.go
Labels: machine-id, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#55805 [v18] github: fix default start date on plugin creation
  tool/tctl/common/plugin/github.go
Labels: tctl, backport, size/sm, no-changelog

#55790 [v18] Adds `KindSAMLIdPServiceProvider` to `Cache.listResources`
  lib/auth/auth_with_roles_test.go
  lib/cache/cache.go
Labels: backport, size/sm, no-changelog

#55826 [v15] Update docs version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#55825 [v16] Update docs version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#55655 [vnet] feat: support VNet SSH when cluster name does not match proxy public addr
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_darwin.go
  lib/vnet/admin_process_darwin.go
  lib/vnet/admin_process_windows.go
  lib/vnet/client_application_service.go
  lib/vnet/clusterconfigcache.go
  lib/vnet/fqdn_resolver.go
  lib/vnet/local_osconfig_provider.go
  lib/vnet/osconfig.go
  lib/vnet/osconfig_provider.go
  lib/vnet/osconfig_provider_test.go
  lib/vnet/unified_cluster_config_provider.go
  lib/vnet/user_process.go
  lib/vnet/vnet_test.go
Labels: backport-required, size/sm, no-changelog, vnet

#55778 docs: Link to jwt_claims information from JWT page
  docs/pages/enroll-resources/application-access/jwt/introduction.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55380 MWI: Bound Keypair - Registration Secrets
  api/types/provisioning.go
  api/types/provisioning_test.go
  lib/auth/join/boundkeypair/boundkeypair.go
  lib/auth/join_bound_keypair.go
  lib/auth/join_bound_keypair_test.go
  lib/joinserver/joinserver.go
  lib/tbot/cli/start_shared.go
  lib/tbot/service_bot_identity.go
Labels: machine-id, size/md, no-changelog

#55822 [v18] Spell fixes for error messages
  lib/auth/join/boundkeypair/boundkeypair.go
  lib/utils/aws/region/internal/codegen.go
Labels: backport, size/sm, no-changelog

#55617 Add additional checks for dynamic desktops test plan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#55647 [v18] Web: fix navigation for locked access request
  web/packages/teleport/src/features.tsx
Labels: ui, backport, size/sm, no-changelog

#55690 [v17] Web: remove multi re-authn in a row when creating github bot
  web/packages/teleport/src/Bots/Add/GitHubActions/useGitHubFlow.tsx
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/resources/resource.ts
Labels: ui, backport, size/sm, no-changelog

#55689 [v18] Web: remove multi re-authn in a row when creating github bot
  web/packages/teleport/src/Bots/Add/GitHubActions/useGitHubFlow.tsx
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/services/resources/resource.ts
Labels: ui, backport, size/sm, no-changelog

#55855 [v17] build: Install correct version (0.2.95) of wasm-bindgen
  build.assets/windows/build.ps1
Labels: backport, size/sm, no-changelog

#55843 [v17] docs: Link to jwt_claims information from JWT page
  docs/pages/enroll-resources/application-access/jwt/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#55841 [v15] docs: Link to jwt_claims information from JWT page
  docs/pages/enroll-resources/application-access/jwt/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#55842 [v16] docs: Link to jwt_claims information from JWT page
  docs/pages/enroll-resources/application-access/jwt/introduction.mdx
Labels: documentation, backport, size/sm, no-changelog

#55616 Fix dynamic windows registration
  lib/services/watcher.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
Labels: desktop-access, size/md, no-changelog, backport/branch/v18

#55427 Don't consume messages in readClientKeyboardLayout
  Makefile
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_test.go
  lib/srv/desktop/tdp/conn.go
Labels: rdp, desktop-access, size/sm, no-changelog, backport/branch/v18

#55861 [v17] Fix dynamic windows registration
  lib/services/watcher.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
Labels: backport, desktop-access, size/md, no-changelog

#55652 Adding decryption to AWS KMS keystore backend
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/keystore_test.go
Labels: size/sm, no-changelog

#55848 Attempt to reduce `TestTrackActiveConnections` flakiness
  .golangci.yml
  integration/db/db_integration_test.go
  integration/db/fixture.go
  lib/srv/db/access_test.go
  lib/srv/db/cassandra/testing/test.go
  lib/srv/db/cassandra_test.go
Labels: database-access, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55779 Edit Proxy Peering documentation
  docs/config.json
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
  docs/pages/admin-guides/deploy-a-cluster/multi-region-blueprint.mdx
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/management/operations/proxy-peering.mdx
  docs/pages/reference/architecture/architecture.mdx
  docs/pages/reference/architecture/proxy-peering.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55833 [web] Changes for generic SCIM enrol flow
  web/packages/shared/components/TextSelectCopy/TextSelectCopy.story.tsx
  web/packages/shared/components/TextSelectCopy/TextSelectCopy.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55594 [vnet] feat: add SSH configuration diagnostic
  api/profile/profile.go
  api/utils/keypaths/keypaths.go
  gen/proto/go/teleport/lib/vnet/diag/v1/diag.pb.go
  gen/proto/ts/teleport/lib/vnet/diag/v1/diag_pb.ts
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_darwin.go
  lib/vnet/diag/ssh.go
  lib/vnet/diag/ssh_test.go
  proto/teleport/lib/vnet/diag/v1/diag.proto
  web/packages/teleterm/src/helpers.ts
  web/packages/teleterm/src/services/vnet/__snapshots__/diag.test.ts.snap
  web/packages/teleterm/src/services/vnet/diag.test.ts
  web/packages/teleterm/src/services/vnet/diag.ts
  web/packages/teleterm/src/ui/Vnet/DocumentVnetDiagReport.story.tsx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetDiagReport.tsx
Labels: ui, backport-required, size/md, no-changelog, vnet

#55881 Modernize tool/, examples/, and e2e/
  e2e/aws/databases_test.go
  e2e/aws/rds_test.go
  e2e/aws/redshift_test.go
  examples/dynamoathenamigration/dynamo_deserializer.go
  examples/dynamoathenamigration/migration.go
  examples/dynamoathenamigration/migration_test.go
  tool/common/fido2/fido2.go
  tool/tbot/kube_test.go
  tool/tbot/main_test.go
  tool/tbot/spiffe.go
  tool/tctl/common/access_request_command.go
  tool/tctl/common/auth_command.go
  tool/tctl/common/auth_command_test.go
  tool/tctl/common/autoupdate_command.go
  tool/tctl/common/bots_command.go
  tool/tctl/common/bots_command_test.go
  tool/tctl/common/collection_test.go
  tool/tctl/common/loadtest_command.go
  tool/tctl/common/loginrule/resource.go
  tool/tctl/common/node_command.go
  tool/tctl/common/oktaassignment/resource_test.go
  tool/tctl/common/resource_command_test.go
  tool/tctl/common/token_command.go
  tool/tctl/common/top/table.go
  tool/tctl/common/user_command.go
  tool/tctl/common/user_command_test.go
  tool/tctl/sso/tester/format.go
  tool/tctl/sso/tester/format_test.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/access_request_test.go
  tool/tsh/common/aliases.go
  tool/tsh/common/app.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_azure_test.go
  tool/tsh/common/app_gcp_test.go
  tool/tsh/common/db.go
  tool/tsh/common/db_print.go
  tool/tsh/common/db_test.go
  tool/tsh/common/git_clone_test.go
  tool/tsh/common/git_config.go
  tool/tsh/common/git_config_test.go
  tool/tsh/common/kube.go
  tool/tsh/common/kube_proxy.go
  tool/tsh/common/kube_test.go
  tool/tsh/common/options_test.go
  tool/tsh/common/proxy.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/recording_export.go
  tool/tsh/common/resolve_default_addr_test.go
  tool/tsh/common/scan.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_helper_test.go
  tool/tsh/common/tsh_test.go
Labels: tsh, tctl, machine-id, size/sm, no-changelog

#55908 [v17] fix: Text alignment in bot instances alert
  web/packages/teleport/src/BotInstances/List/BotInstancesList.tsx
Labels: ui, backport, size/sm, no-changelog

#55802 [v17] Update brace-expansion to 1.1.12 and 2.0.2
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog

#55804 [v15] Update brace-expansion to 1.1.12 and 2.0.2
  yarn.lock
Labels: backport, size/sm, no-changelog

#55803 [v16] Update brace-expansion to 1.1.12 and 2.0.2
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog
