Repository gravitational/teleport, pull requests merged in 2025-07, with the labels that each got.

#56132 [v18] Align GetClusterMaintenanceConfig NotFound error message
  lib/services/local/configuration.go
Labels: backport, size/sm, no-changelog

#56110 MWI: Use specific lock targets when locking out bots
  lib/auth/auth.go
  lib/auth/bot.go
  lib/auth/bot_test.go
  lib/auth/join_bound_keypair.go
  lib/auth/join_bound_keypair_test.go
Labels: size/md

#56248 [v16] Fix misleading error in Terraform Provider
  integrations/terraform/provider/credentials.go
Labels: backport, size/sm, no-changelog

#56247 [v17] Fix misleading error in Terraform Provider
  integrations/terraform/provider/credentials.go
Labels: backport, size/sm, no-changelog

#56246 [v18] Fix misleading error in Terraform Provider
  integrations/terraform/provider/credentials.go
Labels: backport, size/sm, no-changelog

#56221 [v18] Raise Oneshot mode log message from Debug to Info
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm, no-changelog

#56223 [v16] Raise Oneshot mode log message from Debug to Info
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm, no-changelog

#54968 AWS IAM Roles Anywhere: write `~/.aws/config` when doing `tsh apps login <roles anywhere profile>`
  lib/auth/auth.go
  lib/aws/awsconfigfile/awsconfigfile.go
  lib/aws/awsconfigfile/awsconfigfile_test.go
  tool/tsh/common/app.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_external_files.go
Labels: tsh, size/md, no-changelog, backport/branch/v18

#56116 Fix directory re-sharing in desktop session
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/Withholder.test.ts
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/shared/libs/tdp/sharedDirectoryAccess.ts
  web/packages/shared/utils/error.ts
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/lib/tdp/playerClient.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
Labels: ui, support-load, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55869 [v17] MWI: Wait for bot identity before starting services
  lib/tbot/loop.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_heartbeat.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/tbot.go
  lib/tbot/workloadidentity/crl_cache.go
  lib/tbot/workloadidentity/trust_bundle_cache.go
Labels: backport, machine-id, size/md, no-changelog

#56249 Support traits in `workload_identity_labels`
  docs/pages/includes/role-spec.mdx
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/role.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55714 [v18] Fix unasserted contains checks in tests
  lib/auth/machineid/machineidv1/spiffe_federation_service_test.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
Labels: backport, size/sm, no-changelog

#56298 [v16] Support traits in `workload_identity_labels` (#56249)
  docs/pages/includes/role-spec.mdx
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/role.go
Labels: documentation, backport, size/sm

#56299 [v17] Support traits in `workload_identity_labels` (#56249)
  docs/pages/includes/role-spec.mdx
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/role.go
Labels: documentation, backport, size/sm

#56302 Upgrade quic-go to v0.53.0
  go.mod
  go.sum
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/proxy/peer/quic/client.go
  lib/proxy/peer/quic/server.go
Labels: size/sm, no-changelog

#55776 MWI: Document tbot's new `/readyz` endpoint
  docs/pages/includes/machine-id/common-output-config.yaml
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/machine-id/diagnostics-service.mdx
Labels: documentation, machine-id, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55969 Add access_list.spec.type field
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  docs/pages/reference/operator-resources/resources-teleport-dev-accesslists.mdx
  docs/pages/reference/terraform-provider/data-sources/access_list.mdx
  docs/pages/reference/terraform-provider/resources/access_list.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_accesslists.yaml
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  integrations/operator/config/crd/bases/resources.teleport.dev_accesslists.yaml
  integrations/terraform/tfschema/accesslist/v1/accesslist_terraform.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55735 [v18] Add an Identity Security section
  docs/config.json
  docs/pages/admin-guides/management/guides/awsoidc-integration.mdx
  docs/pages/feature-matrix.mdx
  docs/pages/identity-security/access-graph/access-graph.mdx
  docs/pages/identity-security/access-graph/identity-activity-center.mdx
  docs/pages/identity-security/access-graph/self-hosted-helm.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/identity-security/crown-jewels.mdx
  docs/pages/identity-security/identity-security.mdx
  docs/pages/identity-security/integrations/aws-sync.mdx
  docs/pages/identity-security/integrations/azure-sync.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/identity-security/integrations/github.mdx
  docs/pages/identity-security/integrations/gitlab.mdx
  docs/pages/identity-security/integrations/integrations.mdx
  docs/pages/identity-security/integrations/netiq.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/identity-security/integrations/teleport.mdx
  docs/pages/identity-security/policy-connections.mdx
  docs/pages/identity-security/policy-how-to-use.mdx
  docs/pages/identity-security/teleport-policy.mdx
  docs/pages/index.mdx
  docs/pages/reference/helm-reference/teleport-access-graph.mdx
  docs/pages/reference/identity-security-config.mdx
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#55628 docs: [RFD-0217] Bot Details (web)
  rfd/0217-bot-details-web.md
  rfd/assets/0217-feature-access-graph.png
  rfd/assets/0217-feature-active-instances.png
  rfd/assets/0217-feature-activity-timeseries.png
  rfd/assets/0217-feature-audit-log.png
  rfd/assets/0217-feature-delete-bot.png
  rfd/assets/0217-feature-edit.png
  rfd/assets/0217-feature-info.png
  rfd/assets/0217-feature-join-tokens-lock.png
  rfd/assets/0217-feature-join-tokens.png
  rfd/assets/0217-feature-lock-bot.png
  rfd/assets/0217-feature-recent-intances.png
  rfd/assets/0217-feature-roles-traits.png
  rfd/assets/0217-feature-session-recordings.png
  rfd/assets/0217-iteration-1.png
  rfd/cspell.json
Labels: rfd, machine-id, size/md, no-changelog

#56134 Web: add new icons
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/CircleDashed.tsx
  web/packages/design/src/Icon/Icons/UserCheck.tsx
  web/packages/design/src/Icon/assets/CircleDashed.svg
  web/packages/design/src/Icon/assets/UserCheck.svg
  web/packages/design/src/Icon/index.ts
Labels: ui, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#56006 Validate that the "/web/sso_confirm" redirect URL is only used for MFA ceremonies
  lib/auth/github.go
  lib/auth/github_test.go
  lib/client/sso/redirector.go
  lib/client/sso/redirector_test.go
Labels: size/sm, no-changelog

#56323 MWI: Fix flaky tests for automatic bot lockouts
  lib/auth/bot_test.go
  lib/auth/join_bound_keypair_test.go
Labels: size/sm, no-changelog

#56306 [v17] MWI: Add a useful `/readyz` endpoint to tbot
  docs/pages/includes/machine-id/common-output-config.yaml
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/machine-id/diagnostics-service.mdx
  lib/tbot/config/config.go
  lib/tbot/config/config_test.go
  lib/tbot/config/service_application.go
  lib/tbot/config/service_application_tunnel.go
  lib/tbot/config/service_client_credential.go
  lib/tbot/config/service_database.go
  lib/tbot/config/service_database_tunnel.go
  lib/tbot/config/service_example.go
  lib/tbot/config/service_identity.go
  lib/tbot/config/service_kubernetes.go
  lib/tbot/config/service_kubernetes_v2.go
  lib/tbot/config/service_spiffe_svid.go
  lib/tbot/config/service_spiffe_workload_api.go
  lib/tbot/config/service_ssh_host.go
  lib/tbot/config/service_ssh_multiplexer.go
  lib/tbot/config/service_workload_identity_api.go
  lib/tbot/config/service_workload_identity_aws_ra.go
  lib/tbot/config/service_workload_identity_jwt.go
  lib/tbot/config/service_workload_identity_x509.go
  lib/tbot/loop.go
  lib/tbot/readyz/http.go
  lib/tbot/readyz/readyz.go
  lib/tbot/readyz/readyz_test.go
  lib/tbot/readyz/reporter.go
  lib/tbot/readyz/status.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_diagnostics.go
  lib/tbot/service_example.go
  lib/tbot/service_heartbeat.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_spiffe_svid_output.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/service_workload_identity_jwt.go
  lib/tbot/service_workload_identity_x509.go
  lib/tbot/tbot.go
  lib/tbot/workloadidentity/crl_cache.go
  lib/tbot/workloadidentity/trust_bundle_cache.go
Labels: documentation, backport, machine-id, size/lg

#56217 [v17] Fix gRPC -> Teleport types message conversion
  api/types/accesslist/convert/v1/member.go
  api/types/accesslist/convert/v1/review.go
  api/types/discoveryconfig/convert/v1/discoveryconfig.go
  api/types/externalauditstorage/convert/v1/externalauditstorage.go
  api/types/header/convert/v1/header.go
  api/types/secreports/convert/v1/secreprot.go
  api/types/userloginstate/convert/v1/user_login_state.go
  tool/tctl/common/clusterconfig/accessgraphsettings.go
Labels: tctl, backport, size/sm, no-changelog

#56341 Set AuthServerAddressMode in terraform provider
  integrations/terraform/provider/credentials.go
Labels: size/sm, backport/branch/v17, backport/branch/v18

#56322 [v17] Add access_list.spec.type field
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  docs/pages/reference/operator-resources/resources-teleport-dev-accesslists.mdx
  docs/pages/reference/terraform-provider/data-sources/access_list.mdx
  docs/pages/reference/terraform-provider/resources/access_list.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_accesslists.yaml
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  integrations/operator/config/crd/bases/resources.teleport.dev_accesslists.yaml
  integrations/terraform/tfschema/accesslist/v1/accesslist_terraform.go
Labels: documentation, helm, backport, size/md, no-changelog

#56339 [v17] Update pnpm to 10.12.4
  package.json
Labels: backport, size/sm, no-changelog

#56343 [v17] Set AuthServerAddressMode in terraform provider
  integrations/terraform/provider/credentials.go
Labels: backport, size/sm

#56275 [v17] Fix directory re-sharing in desktop session
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/Withholder.test.ts
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/shared/libs/tdp/sharedDirectoryAccess.ts
  web/packages/shared/utils/error.ts
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/lib/tdp/playerClient.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
Labels: ui, backport, size/sm

#56024 feat: Bot instance sorting (web)
  api/gen/proto/go/teleport/machineid/v1/bot_instance_service.pb.go
  api/proto/teleport/machineid/v1/bot_instance_service.proto
  lib/auth/authclient/api.go
  lib/auth/machineid/machineidv1/bot_instance_service.go
  lib/cache/bot_instance.go
  lib/cache/bot_instance_test.go
  lib/cache/generic_operations.go
  lib/services/bot_instance.go
  lib/services/local/bot_instance.go
  lib/services/local/bot_instance_test.go
  lib/web/machineid.go
  web/packages/design/src/DataTable/sort.test.ts
  web/packages/design/src/DataTable/sort.ts
  web/packages/teleport/src/BotInstances/BotInstances.test.tsx
  web/packages/teleport/src/BotInstances/BotInstances.tsx
  web/packages/teleport/src/BotInstances/List/BotInstancesList.tsx
  web/packages/teleport/src/components/hooks/useUrlFiltering/encodeUrlQueryParams.ts
  web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts
  web/packages/teleport/src/services/bot/bot.ts
  web/packages/teleport/src/test/helpers/botInstances.ts
Labels: ui, machine-id, size/md, backport/branch/v17, backport/branch/v18

#56375 [v17] Fix aws oidc tasks story
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Task.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Tasks.story.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Tasks.tsx
  web/packages/teleport/src/services/integrations/integrations.ts
Labels: ui, backport, size/md, no-changelog

#56381 Release 17.5.4
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#56352 [v17] Align Access List type handling
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
Labels: backport, size/sm, no-changelog

#56327 [v17] Add ButtonSelect component
  web/packages/design/src/ButtonSelect/ButtonSelect.story.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.test.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.tsx
  web/packages/design/src/ButtonSelect/index.ts
  web/packages/design/src/index.ts
Labels: ui, backport, size/md, no-changelog

#56332 [v16] Add ButtonSelect component
  web/packages/design/src/ButtonSelect/ButtonSelect.story.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.test.tsx
  web/packages/design/src/ButtonSelect/ButtonSelect.tsx
  web/packages/design/src/ButtonSelect/index.ts
  web/packages/design/src/Onboard/__snapshots__/WelcomeWrapper.story.test.tsx.snap
  web/packages/design/src/index.ts
  web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/__snapshots__/RequestCheckout.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/NewRequest/ResourceList/__snapshots__/ResourceList.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/RequestDelete/__snapshots__/RequestDelete.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/RequestReview/__snapshots__/RequestReview.story.test.tsx.snap
  web/packages/shared/components/AccessRequests/ReviewRequests/RequestView/__snapshots__/RequestView.story.test.tsx.snap
  web/packages/shared/components/TextSelectCopy/__snapshots__/TextSelectCopyMulti.story.test.tsx.snap
  web/packages/teleport/src/AccessRequests/__snapshots__/AccessRequests.story.test.tsx.snap
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentBlank/__snapshots__/DocumentBlank.story.test.tsx.snap
  web/packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
  web/packages/teleport/src/Console/Tabs/__snapshots__/Tabs.story.test.tsx.snap
  web/packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
  web/packages/teleport/src/Discover/SelectResource/__snapshots__/SelectResource.story.test.tsx.snap
  web/packages/teleport/src/Kubes/ConnectDialog/__snapshots__/ConnectDialog.story.test.tsx.snap
  web/packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
  web/packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
  web/packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
  web/packages/teleport/src/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap
  web/packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
  web/packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap
  web/packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
  web/packages/teleport/src/Welcome/NewCredentials/__snapshots__/NewCredentials.story.test.tsx.snap
  web/packages/teleport/src/components/ReAuthenticate/__snapshots__/ReAuthenticate.story.test.tsx.snap
  web/packages/teleport/src/components/RecoveryCodes/__snapshots__/RecoveryCodes.story.test.tsx.snap
Labels: ui, backport, size/md, no-changelog

#56153 Restructuring Installations Page
  .github/ISSUE_TEMPLATE/test-plan-docs.md
  .github/workflows/doc-tests.yaml
  CHANGELOG.md
  docs/pages/admin-guides/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/admin-guides/access-controls/guides/headless.mdx
  docs/pages/admin-guides/access-controls/guides/passwordless.mdx
  docs/pages/admin-guides/access-controls/guides/webauthn.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/gcp.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/management/security/proxy-protocol.mdx
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/enroll-resources/application-access/getting-started.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/snowflake.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/elastic.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/redis.mdx
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
  docs/pages/enroll-resources/desktop-access/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/getting-started.mdx
  docs/pages/get-started.mdx
  docs/pages/identity-governance/access-request-plugins/notification-routing-rules.mdx
  docs/pages/identity-governance/access-request-plugins/opsgenie.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/includes/application-access/aws-database-start-app-service.mdx
  docs/pages/includes/client-cluster-compatibility.mdx
  docs/pages/includes/device-trust/prereqs.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/ent-vs-community-faq.mdx
  docs/pages/includes/install-linux-enterprise.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/server-access/custom-installer.mdx
  docs/pages/installation.mdx
  docs/pages/installation/amazon-ec2.mdx
  docs/pages/installation/docker.mdx
  docs/pages/installation/helm.mdx
  docs/pages/installation/installation.mdx
  docs/pages/installation/linux.mdx
  docs/pages/installation/macos.mdx
  docs/pages/installation/source.mdx
  docs/pages/installation/windows.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/databases.mdx
  docs/pages/machine-workload-identity/machine-id/faq.mdx
  docs/pages/reference/cloud-faq.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
  docs/sidebar.json
Labels: documentation, size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56162 [v17] Replace react-markdown with a simple lightweight parser
  pnpm-lock.yaml
  web/__mocks__/react-markdown.js
  web/packages/teleport/package.json
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Markdown.test.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Markdown.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Task.tsx
Labels: ui, backport, size/md, no-changelog

#55568 Add a guide to Proxy Service traffic separation
  docs/pages/admin-guides/deploy-a-cluster/separate-proxy-service-endpoints.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55729 [v18] [doc] database "multi-session" MFA
  docs/pages/admin-guides/access-controls/guides/per-session-mfa.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, backport, size/sm, no-changelog

#56401 [v16] Add missing quote to AD docs
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
Labels: documentation, backport, size/sm, no-changelog

#55375 Update usage-billing.mdx to include IG MAUs
  docs/pages/usage-billing.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56403 [v17] Align Integration Web Test Client
  integration/conntest/database_test.go
  integration/db/database_service_test.go
  integration/helpers/web.go
  integration/integrations/integration_test.go
  integration/web/web_test.go
Labels: backport, size/sm, no-changelog

#56393 Unset AWS_PROFILE in TestCreateSignedSTSIdentityRequest
  lib/auth/join/iam/iam_test.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56170 [v18] check integration reference in the current state of the plugin resource
  lib/auth/integration/integrationv1/service_test.go
  lib/services/local/integrations.go
Labels: backport, size/sm, no-changelog

#56425 [v17] Unset AWS_PROFILE in TestCreateSignedSTSIdentityRequest
  lib/auth/join/iam/iam_test.go
Labels: backport, size/sm, no-changelog

#55680 [v18] [docs] Restructuring agent homepage links
  docs/pages/enroll-resources/application-access/application-access.mdx
  docs/pages/enroll-resources/auto-discovery/auto-discovery.mdx
  docs/pages/enroll-resources/database-access/database-access.mdx
  docs/pages/enroll-resources/desktop-access/desktop-access.mdx
  docs/pages/enroll-resources/kubernetes-access/kubernetes-access.mdx
  docs/pages/enroll-resources/server-access/server-access.mdx
  docs/pages/machine-workload-identity/machine-id/machine-id.mdx
  docs/pages/machine-workload-identity/workload-identity/workload-identity.mdx
Labels: documentation, backport, size/md, no-changelog

#56411 [v18] Restructuring Installations Page
  .github/ISSUE_TEMPLATE/test-plan-docs.md
  .github/workflows/doc-tests.yaml
  CHANGELOG.md
  docs/pages/admin-guides/access-controls/compliance-frameworks/fedramp.mdx
  docs/pages/admin-guides/access-controls/guides/headless.mdx
  docs/pages/admin-guides/access-controls/guides/passwordless.mdx
  docs/pages/admin-guides/access-controls/guides/webauthn.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/gcp.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/digitalocean.mdx
  docs/pages/admin-guides/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/admin-guides/management/admin/self-signed-certs.mdx
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/management/security/proxy-protocol.mdx
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/enroll-resources/application-access/getting-started.mdx
  docs/pages/enroll-resources/database-access/enroll-managed-databases/snowflake.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/elastic.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/redis.mdx
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
  docs/pages/enroll-resources/desktop-access/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/getting-started.mdx
  docs/pages/get-started.mdx
  docs/pages/identity-governance/access-request-plugins/notification-routing-rules.mdx
  docs/pages/identity-governance/access-request-plugins/opsgenie.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/includes/application-access/aws-database-start-app-service.mdx
  docs/pages/includes/client-cluster-compatibility.mdx
  docs/pages/includes/device-trust/prereqs.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
  docs/pages/includes/edition-prereqs-tabs.mdx
  docs/pages/includes/ent-vs-community-faq.mdx
  docs/pages/includes/install-linux-enterprise.mdx
  docs/pages/includes/install-linux.mdx
  docs/pages/includes/install-tsh.mdx
  docs/pages/includes/server-access/custom-installer.mdx
  docs/pages/installation.mdx
  docs/pages/installation/amazon-ec2.mdx
  docs/pages/installation/docker.mdx
  docs/pages/installation/helm.mdx
  docs/pages/installation/installation.mdx
  docs/pages/installation/linux.mdx
  docs/pages/installation/macos.mdx
  docs/pages/installation/source.mdx
  docs/pages/installation/windows.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/databases.mdx
  docs/pages/machine-workload-identity/machine-id/faq.mdx
  docs/pages/reference/cloud-faq.mdx
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
  docs/sidebar.json
Labels: documentation, backport, size/md, no-changelog

#56261 autoupdate canary support: inventory and auth primitives
  api/types/autoupdate/constants.go
  api/types/autoupdate/rollout.go
  api/types/autoupdate/rollout_test.go
  lib/auth/autoupdate_agent_version_report.go
  lib/auth/autoupdate_agent_version_report_test.go
  lib/auth/autoupdate_rollout.go
  lib/auth/autoupdate_rollout_test.go
  lib/inventory/controller.go
  lib/inventory/store.go
Labels: size/md, no-changelog, automatic-upgrades

#56080 [v18] Include version in terraform token example
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  integrations/terraform/examples/resources/teleport_provision_token/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#55284 [v18] docs: include sudo for install systemd examples
  docs/pages/admin-guides/management/diagnostics/logging.mdx
  docs/pages/includes/machine-id/daemon.mdx
Labels: documentation, backport, size/sm, no-changelog

#55475 [v18] Organize the sidebar to aid practitioner focus
  docs/sidebar.json
Labels: documentation, backport, size/sm, no-changelog

#56434 [v18] Add a guide to Proxy Service traffic separation
  docs/pages/admin-guides/deploy-a-cluster/separate-proxy-service-endpoints.mdx
Labels: documentation, backport, size/md, no-changelog

#56413 [v18] Docs: Describe custom prompts for Access Requests
  docs/pages/identity-governance/access-requests/access-request-configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#56092 [v18] Update notices related to Managed Updates rollout status
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#56117 [v18] VNet docs: Provide clear instructions for getting debug logs
  docs/cspell.json
  docs/pages/connect-your-client/vnet.mdx
Labels: documentation, backport, size/sm, no-changelog

#56087 [v18] Adding VPN reference in VNet doc for search purposes
  docs/pages/connect-your-client/vnet.mdx
Labels: documentation, backport, size/sm, no-changelog

#56112 [v18] Adjust docs on app/database tunnel service and one-shot mode
  docs/pages/machine-workload-identity/machine-id/access-guides/applications.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#56398 Forbid setting audit in non-dynamic Access Lists
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist_test.go
  api/types/accesslist/funcs.go
  api/types/accesslist/review.go
  lib/services/local/access_list.go
Labels: backport-required, no-changelog, backport/branch/v17, backport/branch/v18

#56449 [v18] Fixing Tile Links
  docs/pages/installation/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#56450 [v18] [docs] Add health check docs
  docs/img/resource-health-check/database-health-warning-indicator.png
  docs/pages/enroll-resources/database-access/guides/guides.mdx
  docs/pages/enroll-resources/database-access/guides/health-checks.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/md, no-changelog

#56296 [v18] Support traits in `workload_identity_labels`
  docs/pages/includes/role-spec.mdx
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/role.go
Labels: documentation, backport, size/sm

#55548 [v18] MWI: Terraform Provider - Skeleton
  .github/workflows/flaky-tests.yaml
  .github/workflows/unit-tests-integrations.yaml
  Makefile
  integrations/Makefile
  integrations/terraform-mwi/LICENSE
  integrations/terraform-mwi/Makefile
  integrations/terraform-mwi/README.md
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/main.go
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_data_source_test.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource_test.go
  integrations/terraform-mwi/provider/provider.go
  integrations/terraform-mwi/provider/provider_test.go
Labels: backport, size/lg, no-changelog

#56457 [v18] MWI: Terraform Provider - Basic validation/attributes (#55416)
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_data_source_test.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource_test.go
  integrations/terraform-mwi/provider/provider.go
Labels: backport, size/lg, no-changelog

#55987 [v18] Add react-error-boundary
  jest.config.js
  package.json
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog

#56437 [v18] Update usage-billing.mdx to include IG MAUs
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#56466 [v18] Fix missing permissions in operator role
  examples/chart/teleport-cluster/charts/teleport-operator/templates/role.yaml
Labels: helm, backport, size/sm

#56462 [v18] MWI: Implement ephemeral resource & data source for Kubernetes Access (#55865)
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_data_source_test.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource_test.go
  integrations/terraform-mwi/provider/kubernetes_test.go
  integrations/terraform-mwi/provider/provider.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/testing/kube_server/namespaces.go
  lib/tbot/config/destination_memory.go
  tool/teleport/testenv/test_server.go
Labels: kubernetes-access, backport, machine-id, size/lg, no-changelog

#56147 [docs] VNet SSH
  docs/img/vnet/configure-ssh-clients.png
  docs/img/vnet/how-it-works.svg
  docs/img/vnet/ssh-connect.png
  docs/img/vnet/start-vnet.png
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/connect-your-client/vnet.mdx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetInfo.tsx
Labels: documentation, backport-required, size/sm, no-changelog, vnet

#56193 Update VNet SSH RFD state to implemented
  rfd/0207-vnet-ssh.md
  rfd/cspell.json
Labels: rfd, size/sm, no-changelog

#55933 [Web] Implement identifier-first login frontend
  web/packages/teleport/src/components/FormLogin/FormIdentifierFirst.test.tsx
  web/packages/teleport/src/components/FormLogin/FormIdentifierFirst.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.story.tsx
  web/packages/teleport/src/components/FormLogin/FormLogin.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleport/src/services/storageService/storageService.ts
  web/packages/teleport/src/services/storageService/types.ts
Labels: ui, size/md, backport/branch/v18

#55499 [teleport-update] Use teleport config package to generate systemd services
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/no_namespace/deprecated.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/no_namespace/dropin.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/no_namespace/service.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/no_namespace/timer.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/test_namespace/dropin.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/test_namespace/service.golden
  lib/autoupdate/agent/testdata/TestWriteConfigFiles/test_namespace/timer.golden
  lib/autoupdate/agent/testdata/TestWriteTeleportService/FIPS.golden
  lib/autoupdate/agent/testdata/TestWriteTeleportService/custom.golden
  lib/autoupdate/agent/testdata/TestWriteTeleportService/default.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  lib/autoupdate/agent/validate.go
  lib/config/systemd/systemd.go
  lib/config/systemd/systemd_test.go
  lib/config/systemd/testdata/TestWriteUnitFile.golden
  tool/teleport-update/main.go
  tool/teleport/common/configurator.go
  tool/teleport/common/teleport.go
Labels: size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55818 [v18] MWI: Implement RFD 216 - `tbot` resiliency improvements
  integrations/lib/embeddedtbot/bot_test.go
  integrations/operator/main.go
  integrations/terraform/provider/credentials.go
  lib/tbot/cli/cli.go
  lib/tbot/client/client.go
  lib/tbot/config/config.go
  lib/tbot/database_access.go
  lib/tbot/output_utils.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_ca_rotation.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_spiffe_svid_output.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/service_workload_identity_jwt.go
  lib/tbot/service_workload_identity_x509.go
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  lib/tbot/workloadidentity/issue.go
  tool/tctl/common/terraform_command.go
Labels: tctl, backport, machine-id, size/lg

#56480 Fix spelling on log and error messages
  integration/helpers/instance.go
  lib/config/configuration.go
  lib/srv/discovery/access_graph_aws.go
Labels: size/sm, discovery, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#55456 [v18] Add focus-visible style to Toggle
  web/packages/design/src/Toggle/Toggle.story.tsx
  web/packages/design/src/Toggle/Toggle.tsx
Labels: ui, backport, size/sm, no-changelog

#55460 [v18] Unified resources: Make "Show requestable resources" clickable
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
Labels: ui, backport, size/sm, no-changelog

#55472 [v18] Connect login form: Refocus password field on submission error
  web/packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.test.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx
Labels: ui, backport, size/sm, no-changelog

#55801 [v18] Update brace-expansion to 1.1.12 and 2.0.2
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog

#56338 [v18] Update pnpm to 10.12.4
  package.json
Labels: backport, size/sm, no-changelog

#56436 [v16] Add a guide to Proxy Service traffic separation
  docs/pages/admin-guides/deploy-a-cluster/separate-proxy-service-endpoints.mdx
Labels: documentation, backport, size/md, no-changelog

#56439 [v16] Update usage-billing.mdx to include IG MAUs
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#56486 [v18] Fix spelling on log and error messages
  integration/helpers/instance.go
  lib/config/configuration.go
  lib/srv/discovery/access_graph_aws.go
Labels: backport, size/sm, discovery, no-changelog

#54891 Kubernetes CRD support in access request
  api/types/constants.go
  api/types/kubernetes.go
  api/types/resource_ids.go
  api/types/resource_ids_test.go
  api/types/role.go
  api/types/role_test.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/kube/grpc/grpc.go
  lib/kube/grpc/grpc_test.go
  lib/kube/grpc/utils.go
  lib/kube/proxy/resource_rbac_test.go
  lib/kube/proxy/scheme.go
  lib/services/access_checker.go
  lib/services/access_checker_test.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/matchers.go
  lib/services/role.go
  lib/services/role_test.go
  lib/sshca/identity_test.go
  lib/web/servers.go
  tool/tsh/common/access_request.go
  tool/tsh/common/access_request_test.go
  tool/tsh/common/tsh.go
Labels: kubernetes-access, tsh, size/lg, backport/branch/v18

#56495 [v18] Add autoupdate agent report commands
  api/client/client.go
  lib/autoupdate/rollout/strategy_haltonerror_test.go
  lib/services/resource.go
  tool/tctl/common/autoupdate_command.go
  tool/tctl/common/autoupdate_command_test.go
  tool/tctl/common/collection.go
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/lg

#56382 Web: move sliding tab logic to a single file for sharing
  web/packages/design/src/ButtonIcon/ButtonIcon.tsx
  web/packages/design/src/Tabs/Tabs.story.tsx
  web/packages/design/src/Tabs/Tabs.ts
  web/packages/design/src/Tabs/index.ts
  web/packages/design/src/Tabs/useSlidingBottomBorderTabs.ts
  web/packages/teleport/src/Integrations/status/AwsOidc/Details/Rds.tsx
Labels: ui, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#56503 [v18] [docs] Add `hcl` language marker in the code blocks
  docs/pages/identity-security/access-graph/identity-activity-center.mdx
Labels: documentation, backport, size/sm, no-changelog

#55858 Add testplan tasks for access request kubernetes.
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog, backport/branch/v18

#56505 Add Type.IsReviewable()
  api/types/accesslist/accesslist.go
Labels: backport-required, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#55897 Add assume-role for EC2 discovery
  lib/cloud/awsconfig/awsconfig.go
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
  lib/configurators/common.go
  lib/srv/discovery/discovery.go
  lib/srv/server/ec2_watcher.go
  lib/srv/server/ec2_watcher_test.go
  tool/teleport/common/teleport.go
Labels: size/sm, discovery, backport/branch/v18

#56533 fix: don't return db_client CA when listing db CAs
  lib/cache/cert_authority.go
  lib/cache/cert_authority_test.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56091 [v18] Add support for rocky and almalinux to CDN install script
  lib/web/scripts/install/install.sh
  web/packages/teleport/src/Discover/SelectResource/resources/resources.tsx
Labels: ui, backport, size/sm, no-changelog

#55917 MWI: Refactor identity impersonation
  lib/tbot/client/builder.go
  lib/tbot/identity/generator.go
  lib/tbot/output_utils.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_spiffe_svid_output.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/service_workload_identity_jwt.go
  lib/tbot/service_workload_identity_x509.go
  lib/tbot/tbot.go
Labels: machine-id, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#56510 Forbid creating access_list_review for non-reviewable access_lists
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: backport-required, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#56520 [v18] Update docs with new access request format to enable CRD support.
  docs/pages/enroll-resources/kubernetes-access/controls.mdx
  docs/pages/identity-governance/access-requests/resource-requests.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, backport, size/sm, no-changelog

#56513 Fix schema with transparent background
  docs/img/architecture/managed-updates-v2.svg
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#56498 [v18] fixes a broken link in the SELinux docs
  docs/pages/admin-guides/management/security/selinux.mdx
Labels: documentation, backport, size/sm, no-changelog

#56557 [v18] Deflake EKS Discovery with User Tasks
  lib/srv/discovery/discovery_eks_test.go
  lib/srv/discovery/discovery_test.go
Labels: backport, size/md, discovery, no-changelog

#56559 Trace the correct error return value in Router.DialWindowsDesktop
  lib/proxy/router.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#56517 [v17] Remove `autoupdate_agent_report` mentions in v17 and below
  docs/img/architecture/managed-updates-v2.svg
  docs/pages/reference/managed-updates-v2.mdx
Labels: documentation, backport, size/sm, no-changelog, backport/branch/v15, backport/branch/v16

#56497 gha(docs-amplify): update amplify preview to v0.0.2
  .github/workflows/docs-amplify.yaml
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56477 [v18][vnet] feat: serve DNS on IPv4
  lib/vnet/admin_process_darwin.go
  lib/vnet/admin_process_windows.go
  lib/vnet/network_stack.go
  lib/vnet/osconfig.go
  lib/vnet/osconfig_darwin.go
  lib/vnet/osconfig_windows.go
  lib/vnet/remote_osconfig_provider.go
  lib/vnet/remote_osconfig_provider_test.go
  lib/vnet/unsupported_os.go
Labels: backport, size/sm

#56501 [v18] docs: Fix multi-region blueprint
  docs/pages/admin-guides/deploy-a-cluster/multi-region-blueprint.mdx
Labels: documentation, backport, size/sm, no-changelog

#56320 [v18] Web: add new icons
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/CircleDashed.tsx
  web/packages/design/src/Icon/Icons/UserCheck.tsx
  web/packages/design/src/Icon/assets/CircleDashed.svg
  web/packages/design/src/Icon/assets/UserCheck.svg
  web/packages/design/src/Icon/index.ts
Labels: ui, backport, size/md, no-changelog

#56572 [v18] Remove Teleport v14 references from the docs
  docs/pages/admin-guides/infrastructure-as-code/teleport-operator/teleport-operator.mdx
  docs/pages/connect-your-client/putty-winscp.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
  docs/pages/reference/backends.mdx
  docs/pages/reference/join-methods.mdx
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#56569 [v18] Web: move sliding tab logic to a single file for sharing
  web/packages/design/src/Tabs/Tabs.story.tsx
  web/packages/design/src/Tabs/Tabs.ts
  web/packages/design/src/Tabs/index.ts
  web/packages/design/src/Tabs/useSlidingBottomBorderTabs.ts
  web/packages/teleport/src/Integrations/status/AwsOidc/Details/Rds.tsx
Labels: ui, backport, size/md, no-changelog

#56468 autoupdate canary support: modulate proxy response
  lib/web/apiserver.go
  lib/web/apiserver_ping_test.go
  lib/web/autoupdate_common.go
  lib/web/autoupdate_common_test.go
Labels: size/md, no-changelog

#56511 Document autoupdate agent report
  CHANGELOG.md
  docs/pages/reference/managed-updates-v2.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#56055 Docs: Rename Access Monitoring to Access Automation
  docs/img/access-controls/automatic-reviews/create-automatic-review-rule.png
  docs/img/access-controls/automatic-reviews/view-access-requests.png
  docs/pages/identity-governance/access-requests/automatic-reviews.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#56576 [v18] Trace the correct error return value in Router.DialWindowsDesktop
  lib/proxy/router.go
Labels: backport, size/sm, no-changelog

#56575 [v17] Trace the correct error return value in Router.DialWindowsDesktop
  lib/proxy/router.go
Labels: backport, size/sm, no-changelog

#56412 [v17] Docs: Describe custom prompts for Access Requests
  docs/pages/identity-governance/access-requests/access-request-configuration.mdx
Labels: documentation, backport, size/sm, no-changelog

#56492 Docs: Clarify CA bundle instructions for HSM/AWS KMS-backed keys
  docs/pages/enroll-resources/desktop-access/getting-started.mdx
Labels: documentation, size/sm, no-changelog

#56608 [v18] Align ACL conv
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
Labels: backport, size/sm, no-changelog

#56438 [v17] Update usage-billing.mdx to include IG MAUs
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#55896 [v18] [web] Changes for generic SCIM enrol flow
  web/packages/shared/components/TextSelectCopy/TextSelectCopy.story.tsx
  web/packages/shared/components/TextSelectCopy/TextSelectCopy.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#56619 [v18] Remove unnecessary clipPaths from icons
  web/packages/design/src/Icon/Icons/Camera.tsx
  web/packages/design/src/Icon/Icons/Sun.tsx
  web/packages/design/src/Icon/README.md
  web/packages/design/src/Icon/assets/Camera.svg
  web/packages/design/src/Icon/assets/Sun.svg
Labels: ui, backport, size/sm

#56625 [v16] Fix incorrect usage of EventuallyWithT in TestSPIFFEFederationSyncer
  lib/auth/machineid/machineidv1/spiffe_federation_syncer_test.go
Labels: backport, size/sm, no-changelog

#56623 [v18] Fix incorrect usage of EventuallyWithT in TestSPIFFEFederationSyncer
  lib/auth/machineid/machineidv1/spiffe_federation_syncer_test.go
Labels: backport, size/sm, no-changelog

#56220 [v18] Add JWT sign/verify methods for Plugin Token
  lib/jwt/jwt.go
  lib/jwt/jwt_test.go
Labels: backport, size/sm, no-changelog

#56474 Enhances MCP servers usage with Cursor
  lib/client/db/mcp/server.go
  lib/client/db/mcp/server_test.go
  lib/client/mcp/claude/config.go
  tool/tsh/common/help.go
  tool/tsh/common/mcp.go
Labels: tsh, size/sm, no-changelog, MCP

#56616 [v18] Bump helm.sh/helm/v3 to 3.18.4
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/service/servicecfg/config_test.go
Labels: backport, size/sm, no-changelog

#56545 [v18] Docs: Describe disabling okta-requester role assignment
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
Labels: documentation, backport, size/sm, no-changelog

#56546 [v17] Docs: Describe disabling okta-requester role assignment
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
Labels: documentation, backport, size/sm, no-changelog

#56566 [v18] changelog: add missing keyboard layout change
  CHANGELOG.md
Labels: backport, size/sm, no-changelog

#56601 [docs] add VNet warnings
  docs/pages/connect-your-client/vnet.mdx
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
Labels: documentation, size/sm, no-changelog, vnet

#56645 [v17][docs] add VNet warnings
  docs/pages/connect-your-client/vnet.mdx
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
Labels: documentation, backport, size/sm, no-changelog

#56646 [v18][docs] add VNet warnings
  docs/pages/connect-your-client/vnet.mdx
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
Labels: documentation, backport, size/sm, no-changelog

#56159 Extend client tools updates RFD with Teleport Connect auto updates
  rfd/0144-client-tools-updates.md
Labels: rfd, size/md, no-changelog

#56627 [v18] Add Plugin Token gRPC API
  api/gen/proto/go/teleport/plugins/v1/plugin_service.pb.go
  api/gen/proto/go/teleport/plugins/v1/plugin_service_grpc.pb.go
  api/proto/teleport/plugins/v1/plugin_service.proto
Labels: backport, size/sm, no-changelog

#56600 docs: tbot-machine-id changes requested
  docs/pages/machine-workload-identity/machine-id/deployment/aws.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure-devops.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/bitbucket.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/circleci.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/deployment.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gcp.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/github-actions.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gitlab.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/jenkins.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux-tpm.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux.mdx
Labels: documentation, size/sm, no-changelog, access-monitoring, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56664 [v16] Fix renewal timer behaviour for Workload Identity (#56626)
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_x509.go
Labels: backport, machine-id, size/sm

#56663 [v17] Fix Workload API handling of SVID renewal interval
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_x509.go
Labels: backport, machine-id, size/sm

#55874 [v18] SELinux improvements
  lib/selinux/selinux_linux.go
  lib/selinux/teleport_ssh.te
  lib/srv/reexec.go
Labels: backport, size/sm, no-changelog

#56650 [v17] followup: Remove piv-go v1
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#56647 [v18] Validate that the "/web/sso_confirm" redirect URL is only used for MFA ceremonies
  lib/auth/github.go
  lib/auth/github_test.go
  lib/client/sso/redirector.go
  lib/client/sso/redirector_test.go
Labels: backport, size/md, no-changelog

#56649 [v18] followup: Remove piv-go v1
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#56530 [v17] integrations/terraform: add test for joining via a proxy server
  api/constants/constants.go
  docs/pages/reference/terraform-provider/terraform-provider.mdx
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  integrations/terraform/provider/credentials.go
  integrations/terraform/provider/provider.go
  integrations/terraform/testlib/machineid_join_test.go
Labels: documentation, backport, size/xl, terraform-provider

#56527 [v18] integrations/terraform: add test for joining via a proxy server
  api/constants/constants.go
  docs/pages/reference/terraform-provider/terraform-provider.mdx
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  integrations/terraform/provider/credentials.go
  integrations/terraform/provider/provider.go
  integrations/terraform/testlib/machineid_join_test.go
Labels: documentation, backport, size/md, terraform-provider

#56640 [v18] Add access_list.spec.type field
  api/gen/proto/go/teleport/accesslist/v1/accesslist.pb.go
  api/proto/teleport/accesslist/v1/accesslist.proto
  api/types/accesslist/accesslist.go
  api/types/accesslist/accesslist_test.go
  api/types/accesslist/convert/v1/accesslist.go
  api/types/accesslist/convert/v1/accesslist_test.go
  docs/pages/reference/operator-resources/resources-teleport-dev-accesslists.mdx
  docs/pages/reference/terraform-provider/data-sources/access_list.mdx
  docs/pages/reference/terraform-provider/resources/access_list.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_accesslists.yaml
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  integrations/operator/config/crd/bases/resources.teleport.dev_accesslists.yaml
  integrations/terraform/tfschema/accesslist/v1/accesslist_terraform.go
Labels: documentation, helm, backport, size/md, no-changelog

#56666 [v18] Add a make target for running all docs generators
  Makefile
Labels: backport, size/sm, no-changelog

#56669 [v17] Add a make target for running all docs generators
  Makefile
Labels: backport, size/sm, no-changelog

#56574 [v16] Remove Teleport v14 references from the docs
  docs/pages/admin-guides/infrastructure-as-code/teleport-operator/teleport-operator.mdx
  docs/pages/connect-your-client/putty-winscp.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
  docs/pages/reference/backends.mdx
  docs/pages/reference/join-methods.mdx
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/usage-billing.mdx
Labels: documentation, backport, size/sm, no-changelog

#56256 [v17] Pinning shared-workflow references
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/bloat.yaml
  .github/workflows/changelog.yaml
  .github/workflows/check.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/docs-amplify.yaml
  .github/workflows/flaky-tests.yaml
  .github/workflows/label.yaml
  .github/workflows/terraform-lint.yaml
  .github/workflows/trivy.yaml
Labels: backport, size/sm, no-changelog

#56257 [v16] Pinning shared-workflow references
  .github/workflows/assign.yaml
  .github/workflows/backport.yaml
  .github/workflows/bloat.yaml
  .github/workflows/changelog.yaml
  .github/workflows/check.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/dismiss.yaml
  .github/workflows/docs-amplify.yaml
  .github/workflows/flaky-tests.yaml
  .github/workflows/label.yaml
  .github/workflows/terraform-lint.yaml
  .github/workflows/trivy.yaml
Labels: backport, size/sm, no-changelog

#56611 [v18] Document autoupdate agent report
  CHANGELOG.md
  docs/pages/reference/managed-updates-v2.mdx
Labels: documentation, backport, size/sm, no-changelog

#56653 MWI: Fix typos in bound keypair ProvisionTokenV2 proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/reference/terraform-provider/data-sources/provision_token.mdx
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, size/sm, no-changelog

#56312 AWS Roles Anywhere: list profiles endpoint
  lib/auth/grpcserver.go
  lib/auth/integration/integrationv1/awsra.go
  lib/integrations/awsra/client.go
  lib/integrations/awsra/list_rolesanywhere_profiles.go
  lib/integrations/awsra/list_rolesanywhere_profiles_test.go
  lib/integrations/awsra/profile_syncer.go
  lib/web/apiserver.go
  lib/web/integrations_awsra.go
  lib/web/ui/integration.go
Labels: size/md, no-changelog, backport/branch/v18

#56668 [v17] Align SCIM Plugin tctl plugin install flow
  tool/tctl/common/plugin/plugins_command.go
  tool/tctl/common/plugin/scim.go
Labels: tctl, backport, size/sm, no-changelog

#56667 [v18] Align SCIM Plugin tctl plugin install flow
  tool/tctl/common/plugin/plugins_command.go
  tool/tctl/common/plugin/scim.go
Labels: tctl, backport, size/sm, no-changelog

#56675 AWS Roles Anywhere: add Status field to integration
  api/proto/teleport/legacy/types/types.proto
  api/types/integration.go
  api/types/types.pb.go
Labels: size/sm, no-changelog, backport/branch/v18

#56405 MWI: Add build/release steps to MWI Terraform Provider Makefile
  integrations/terraform-mwi/CONTRIBUTING.md
  integrations/terraform-mwi/Makefile
  integrations/terraform-mwi/main.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18
