Repository gravitational/teleport, pull requests merged in 2025-05, with the labels that each got.

#54430 [v16] Remove non-Bourne-shell-compatible script option
  lib/srv/server/installer/defaultinstallers.go
  lib/srv/server/installer/defaultinstallers_test.go
Labels: backport, size/sm

#54429 [v17] Remove non-Bourne-shell-compatible script option
  lib/srv/server/installer/defaultinstallers.go
  lib/srv/server/installer/defaultinstallers_test.go
Labels: backport, size/sm

#54307 Workload Identity: Kubernetes Attestor Bug Fixes
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix_test.go
Labels: machine-id, size/sm, backport/branch/v16, backport/branch/v17

#54374 feat(join-tokens): [44794] API changes for managing GitHub Join Tokens
  api/types/provisioning.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/ui/join_token.go
  lib/web/yaml.go
  lib/web/yaml_test.go
Labels: machine-id, size/md, backport/branch/v16, backport/branch/v17

#54362 [17.4.6] Bump cloud docs version
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54350 Use new access_list_title when showing audit events
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, backport/branch/v16, backport/branch/v17

#54423 Fix tsh ssh multi-node output issues
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54444 [v15] [17.4.6] Bump cloud docs version
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#54456 [v17] Fix tsh ssh multi-node output issues
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
Labels: backport, size/sm

#54427 Web: remove unified resource card styling when require request
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
  web/packages/shared/components/UnifiedResources/ListView/ResourceListItem.tsx
  web/packages/shared/components/UnifiedResources/shared/ResourceActionButton.tsx
  web/packages/shared/components/UnifiedResources/shared/getBackgroundColor.ts
Labels: ui, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54455 [v16] Fix tsh ssh multi-node output issues
  integration/integration_test.go
  lib/client/api.go
  lib/client/client.go
Labels: backport, size/sm

#54453 Fix 31 Vale warnings and one error
  docs/pages/admin-guides/access-controls/device-trust/jamf-integration.mdx
  docs/pages/admin-guides/api/automatically-register-agents.mdx
  docs/pages/admin-guides/deploy-a-cluster/aws-kms.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/teleport-policy/integrations/azure-sync.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/azure-aks-workload-id.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/google-cloud.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/azure.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/enroll-resources/desktop-access/directory-sharing.mdx
  docs/pages/enroll-resources/kubernetes-access/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/manage-access.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/iam-joining.mdx
  docs/pages/enroll-resources/machine-id/deployment/aws.mdx
  docs/pages/enroll-resources/machine-id/deployment/azure.mdx
  docs/pages/enroll-resources/machine-id/deployment/gcp.mdx
  docs/pages/enroll-resources/machine-id/deployment/kubernetes.mdx
  docs/pages/enroll-resources/machine-id/deployment/linux.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
  docs/pages/get-started.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#54418 Add api group to k8s resources.
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-roles.mdx
  docs/pages/reference/operator-resources/resources-teleport-dev-rolesv6.mdx
  docs/pages/reference/operator-resources/resources-teleport-dev-rolesv7.mdx
  docs/pages/reference/operator-resources/resources-teleport-dev-rolesv8.mdx
  docs/pages/reference/terraform-provider/data-sources/role.mdx
  docs/pages/reference/terraform-provider/resources/role.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_roles.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv6.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv7.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_rolesv8.yaml
  gen/proto/ts/prehog/v1/teleport_pb.ts
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/device_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/tpm_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/access_request_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/app_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/database_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/kube_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/server_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/windows_desktop_pb.ts
  gen/proto/ts/teleport/lib/vnet/diag/v1/diag_pb.ts
  integrations/operator/config/crd/bases/resources.teleport.dev_roles.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv6.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv7.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_rolesv8.yaml
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, helm, size/md

#54454 [v16] feat(join-tokens): API changes for managing GitHub Join Tokens
  api/types/provisioning.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/ui/join_token.go
  lib/web/yaml.go
  lib/web/yaml_test.go
Labels: backport, machine-id, size/md

#54448 Update the AWS multi-region architecture guide
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54416 Edit the Resource Requests guide
  docs/pages/admin-guides/access-controls/access-requests/resource-requests.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54468 Update cloud docs to include ap-southeast-2
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54459 [v17] Use new access_list_title when showing audit events
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#54458 [v16] Use new access_list_title when showing audit events
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#54470 [v17] [Okta Integration] More specific error codes for Okta Integration
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/device_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/tpm_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/access_request_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/app_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/database_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/kube_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/server_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  gen/proto/ts/teleport/lib/vnet/diag/v1/diag_pb.ts
  web/packages/teleport/src/Integrations/IntegrationList.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#54419 [v17] docs: Model Context Protocol preview
  docs/cspell.json
  docs/pages/model-context-preview.mdx
Labels: documentation, backport, size/sm, no-changelog, backport/branch/v16

#54495 [v16] Update the AWS multi-region architecture guide
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
Labels: documentation, backport, size/sm, no-changelog

#54411 Allow cloud to request access graph config
  lib/auth/clusterconfig/clusterconfigv1/service.go
Labels: backport-required, size/sm, no-changelog, backport/branch/v17

#54507 Upgrade vite to 6.2.7
  package.json
  pnpm-lock.yaml
Labels: size/sm, no-changelog

#54069 DB multi-session MFA Part 2: MFA reuse for GenerateUserCerts
  api/client/proto/authservice.pb.go
  api/client/proto/types.go
  api/mfa/mfa.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/webauthn/login.go
  lib/auth/webauthn/login_test.go
  lib/client/api.go
  lib/client/client.go
  lib/client/cluster_client.go
  lib/client/cluster_client_test.go
  lib/client/local_proxy_middleware.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/web/databases.go
  lib/web/desktop.go
  lib/web/kube.go
  lib/web/terminal.go
  tool/tsh/common/app.go
  tool/tsh/common/db_exec.go
  tool/tsh/common/kube_proxy.go
Labels: tsh, database-access, size/md

#54404 [v17] Role editor dialog layout tweaks
  web/packages/design/src/SlideTabs/SlideTabs.story.tsx
  web/packages/design/src/SlideTabs/SlideTabs.tsx
  web/packages/teleport/src/Roles/RoleEditor/EditorHeader.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.story.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorVisualizer.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/Roles.tsx
Labels: ui, backport, size/md, no-changelog

#54369 docs: Add Hardware Key Agent and PIN Caching sections
  docs/img/access-controls/hardware-key-support/agent.png
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#54176 Send goodbye even when doing soft-reload
  api/client/proto/authservice.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/inventory/controller_test.go
  lib/inventory/inventory.go
  lib/service/service.go
  lib/srv/app/server_test.go
  lib/srv/db/server_test.go
  lib/utils/retry.go
  lib/web/sessions.go
Labels: application-access, database-access, size/sm, size/md, no-changelog, backport/branch/v17

#54516 [v17] Allow cloud to request access graph config
  lib/auth/clusterconfig/clusterconfigv1/service.go
Labels: backport, size/sm, no-changelog

#54500 fix: fixes a possible deadlock in kube moderator joining
  lib/client/kubesession.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54324 Display update group in `tctl inventory`
  api/proto/teleport/legacy/types/types.proto
  api/types/instance.go
  api/types/instance_test.go
  api/types/types.pb.go
  lib/inventory/inventory.go
  tool/tctl/common/inventory_command.go
Labels: tctl, size/sm

#52934 Add autoupdate manual rollout audit events
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.go
  api/types/events/events.pb.go
  api/types/events/oneof.go
  lib/auth/autoupdate/autoupdatev1/service.go
  lib/auth/autoupdate/autoupdatev1/service_test.go
  lib/events/api.go
  lib/events/codes.go
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: audit-log, size/md, no-changelog

#52837 Fix major version check for stateless environment
  api/gen/proto/go/teleport/backendinfo/v1/backendinfo.pb.go
  api/proto/teleport/backendinfo/v1/backendinfo.proto
  api/types/backendinfo/info.go
  api/types/constants.go
  lib/auth/auth.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/auth/storage/storage.go
  lib/auth/version.go
  lib/service/service.go
  lib/services/backendinfo.go
  lib/services/local/backendinfo.go
  lib/services/local/backendinfo_test.go
Labels: size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54442 [v17] Workload Identity: Kubernetes Attestor Bug Fixes
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix_test.go
Labels: backport, machine-id, size/sm

#54443 [v16] Workload Identity: Kubernetes Attestor Bug Fixes
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go
  lib/tbot/workloadidentity/workloadattest/kubernetes_unix_test.go
Labels: backport, machine-id, size/sm

#54484 Workload Identity: `SigstorePolicy` validation improvements
  lib/services/sigstore_policies.go
  lib/services/sigstore_policies_test.go
Labels: machine-id, size/sm, no-changelog

#54532 Turn off `strictPeerDependencies` to fix Dependabot
  pnpm-workspace.yaml
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#54523 [v17] fix: fixes a possible deadlock in kube moderator joining
  lib/client/kubesession.go
Labels: backport, size/sm

#54519 Add SOC2 info for CC8.1
  docs/pages/admin-guides/access-controls/compliance-frameworks/soc2.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54512 [v17] Edit the Resource Requests guide
  docs/pages/admin-guides/access-controls/access-requests/resource-requests.mdx
Labels: documentation, backport, size/sm, no-changelog

#54513 [v16] Edit the Resource Requests guide
  docs/pages/admin-guides/access-controls/access-requests/resource-requests.mdx
Labels: documentation, backport, size/sm, no-changelog

#54239 Add `--os-log` to tsh, make `--debug` take precedence over `TELEPORT_DEBUG`
  lib/utils/darwinbundle/darwinbundle_darwin.go
  lib/utils/darwinbundle/darwinbundle_darwin.h
  lib/utils/darwinbundle/darwinbundle_darwin.m
  tool/tsh/common/logger.go
  tool/tsh/common/logger_darwin.go
  tool/tsh/common/logger_other.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/md

#54542 [v16] Turn off `strictPeerDependencies` to fix Dependabot
  pnpm-workspace.yaml
Labels: backport, size/sm, no-changelog

#54543 [v17] Turn off `strictPeerDependencies` to fix Dependabot
  pnpm-workspace.yaml
Labels: backport, size/sm, no-changelog

#54555 [v16] Pin the protoc-gen-ts dependency graph
  buf-ts.gen.yaml
Labels: backport, size/sm, no-changelog

#54554 [v17] Pin the protoc-gen-ts dependency graph
  buf-ts.gen.yaml
  gen/proto/ts/prehog/v1/teleport_pb.ts
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_pb.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/device_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/devicetrust_service_pb.ts
  gen/proto/ts/teleport/devicetrust/v1/tpm_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/access_request_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/app_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/database_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/kube_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/server_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.ts
  gen/proto/ts/teleport/lib/teleterm/v1/tshd_events_service_pb.ts
  gen/proto/ts/teleport/lib/vnet/diag/v1/diag_pb.ts
Labels: backport, size/sm, no-changelog

#54557 [v15] Pin the protoc-gen-ts dependency graph
  buf-ts.gen.yaml
Labels: backport, size/sm, no-changelog

#54081 refactor lib/srv to adopt pdp-style patterns
  api/gen/proto/go/teleport/decision/v1alpha1/ssh_access.pb.go
  api/proto/teleport/decision/v1alpha1/ssh_access.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/lock.go
  api/types/lock_test.go
  api/types/types.pb.go
  integration/hostuser_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_okta_rbac_test.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver_test.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/decision/service.go
  lib/decision/service_test.go
  lib/decision/tls_identity.go
  lib/proxy/peer/client.go
  lib/proxy/router.go
  lib/reversetunnelclient/api_with_roles.go
  lib/services/access_checker.go
  lib/services/local/access_test.go
  lib/services/lock.go
  lib/services/lock_test.go
  lib/services/role_test.go
  lib/services/watcher_test.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/exec_linux_test.go
  lib/srv/exec_test.go
  lib/srv/forward/sshserver.go
  lib/srv/forward/sshserver_test.go
  lib/srv/git/forward.go
  lib/srv/mock.go
  lib/srv/monitor.go
  lib/srv/monitor_test.go
  lib/srv/reexec_test.go
  lib/srv/regular/proxy.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/srv/session_control_test.go
  lib/srv/sessiontracker_test.go
  lib/srv/statichostuser_test.go
  lib/srv/statichostusers.go
  lib/srv/term_test.go
  lib/srv/transport/transportv1/transport.go
  lib/srv/transport/transportv1/transport_test.go
  lib/srv/usermgmt.go
  lib/srv/usermgmt_test.go
  lib/sshca/identity.go
  lib/utils/utils.go
  lib/web/apiserver.go
  lib/web/files.go
  lib/web/terminal.go
Labels: size/lg, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54561 Add External PKI & Sigstore integration to Enterprise feature matrix
  docs/cspell.json
  docs/pages/feature-matrix.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#54514 [v15] Edit the Resource Requests guide
  docs/pages/admin-guides/access-controls/access-requests/resource-requests.mdx
Labels: documentation, backport, size/sm, no-changelog

#54161 [v15] Add Access Request fields to the Role Reference
  docs/pages/reference/access-controls/roles.mdx
Labels: documentation, backport, size/sm, no-changelog

#54160 [v16] Add Access Request fields to the Role Reference
  docs/pages/reference/access-controls/roles.mdx
Labels: documentation, backport, size/sm, no-changelog

#54574 [v17] Fix 31 Vale warnings and one error
  docs/pages/admin-guides/access-controls/device-trust/jamf-integration.mdx
  docs/pages/admin-guides/api/automatically-register-agents.mdx
  docs/pages/admin-guides/deploy-a-cluster/aws-kms.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/admin-guides/management/admin/trustedclusters.mdx
  docs/pages/admin-guides/teleport-policy/integrations/azure-sync.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/azure-aks-workload-id.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/google-cloud.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/azure.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/enroll-resources/desktop-access/directory-sharing.mdx
  docs/pages/enroll-resources/kubernetes-access/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/manage-access.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/iam-joining.mdx
  docs/pages/enroll-resources/machine-id/deployment/aws.mdx
  docs/pages/enroll-resources/machine-id/deployment/azure.mdx
  docs/pages/enroll-resources/machine-id/deployment/gcp.mdx
  docs/pages/enroll-resources/machine-id/deployment/kubernetes.mdx
  docs/pages/enroll-resources/machine-id/deployment/linux.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
  docs/pages/get-started.mdx
Labels: documentation, backport, size/sm, no-changelog

#54575 [v17] Add External PKI & Sigstore integration to Enterprise feature matrix
  docs/cspell.json
  docs/pages/feature-matrix.mdx
Labels: documentation, backport, size/sm, no-changelog

#54473 delete unused `app_server_or_saml_idp_sp` type and its usage
  api/client/client.go
  api/client/client_test.go
  api/client/proto/authservice.pb.go
  api/client/proto/types.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/appserver_or_saml_idp_sp.go
  api/types/appserver_or_saml_idp_sp_test.go
  api/types/constants.go
  api/types/resource_test.go
  api/types/saml_idp_service_provider.go
  api/types/types.pb.go
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/client/proto/authservice.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/services/matchers.go
  lib/services/matchers_test.go
  lib/services/unified_resource.go
  lib/services/unified_resource_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/apps.go
  lib/web/ui/app.go
  lib/web/ui/app_test.go
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/sm, no-changelog

#54581 Release 17.4.8
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  docs/cspell.json
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#54548 Update NodeJS and pnpm in Devbox
  devbox.json
  devbox.lock
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#52827 Add latency detector for desktop sessions
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/tdp/proto.go
  lib/web/desktop.go
  lib/web/latency.go
  lib/web/terminal.go
  rfd/0037-desktop-access-protocol.md
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/TopBar.tsx
  web/packages/shared/components/LatencyDiagnostic/LatencyDiagnostic.tsx
  web/packages/shared/components/MenuAction/MenuActionIcon.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/shared/libs/tdp/codec.ts
Labels: ui, rdp, desktop-access, size/md, backport/branch/v17

#54585 ci: Update CI buildbox to teleport18
  .github/workflows/aws-e2e-tests-non-root.yaml
  .github/workflows/benchmark-code-nonroot.yaml
  .github/workflows/benchmark-code-root.yaml
  .github/workflows/bloat.yaml
  .github/workflows/e2e-tests.yaml
  .github/workflows/flaky-tests.yaml
  .github/workflows/integration-tests-non-root.yaml
  .github/workflows/integration-tests-root.yaml
  .github/workflows/kube-integration-tests-non-root.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/lint.yaml
  .github/workflows/os-compatibility-test.yaml
  docs/preflight.md
Labels: documentation, size/sm, no-changelog

#54587 [v17] Convert desktop session dialogs to inline messages
  package.json
  pnpm-lock.yaml
  web/packages/build/jest/jest-environment-patched-jsdom.js
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/components/DesktopSession/TopBar.tsx
  web/packages/shared/components/DesktopSession/index.ts
  web/packages/shared/libs/tdp/client.ts
  web/packages/teleport/package.json
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/lib/tdp/webSocketTransportAdapter.ts
  web/packages/teleport/src/lib/useMfa.test.tsx
  web/packages/teleport/src/lib/useMfa.ts
  web/packages/teleterm/package.json
Labels: ui, backport, size/md, no-changelog

#54565 Add missing redirect
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#54599 [v17] Enable SSO MFA for headless (#53741)
  lib/auth/auth_with_roles.go
  lib/client/weblogin.go
  lib/web/headless.go
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.test.tsx
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.tsx
  web/packages/teleport/src/services/auth/auth.ts
Labels: ui, backport, size/sm

#54166 RFD 209: MCP access
  rfd/0209-mcp-access.md
  rfd/assets/0209-audit-events.png
  rfd/assets/0209-claude-desktop-disconnected.png
  rfd/assets/0209-claude-desktop-tools.png
  rfd/cspell.json
Labels: rfd, size/md, no-changelog

#54571 [v15] Add SOC2 info for CC8.1
  docs/pages/admin-guides/access-controls/compliance-frameworks/soc2.mdx
Labels: documentation, backport, size/sm, no-changelog

#54569 [v17] Add SOC2 info for CC8.1
  docs/pages/admin-guides/access-controls/compliance-frameworks/soc2.mdx
Labels: documentation, backport, size/sm, no-changelog

#54570 [v16] Add SOC2 info for CC8.1
  docs/pages/admin-guides/access-controls/compliance-frameworks/soc2.mdx
Labels: documentation, backport, size/sm, no-changelog

#52573 Deprecate custom ALPN upgrade
  CHANGELOG.md
  api/client/alpn_conn_upgrade.go
  api/client/alpn_conn_upgrade_test.go
  api/client/alpn_websocket.go
  api/defaults/defaults.go
  docs/cspell.json
  docs/img/architecture/tls-routing-connection-upgrade.png
  docs/img/architecture/tls-routing-connection-upgrade.svg
  docs/pages/includes/reference/code-blocks-no-cspell/tls-routing-conn-upgrade-test-command.mdx
  docs/pages/includes/reference/code-blocks-no-cspell/tls-routing-conn-upgrade-test-result.mdx
  docs/pages/reference/architecture/tls-routing.mdx
  lib/web/conn_upgrade.go
Labels: documentation, size/sm

#54590 ci: Update CI buildbox to teleport18, part 2
  .github/workflows/unit-tests-code.yaml
  .github/workflows/unit-tests-helm.yaml
  .github/workflows/unit-tests-integrations.yaml
  .github/workflows/unit-tests-rust.yaml
  .github/workflows/unit-tests-ui.yaml
Labels: size/sm, no-changelog

#54475 Web: add support for rendering status panel
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/databases.go
  lib/web/servers.go
  lib/web/ui/server.go
  web/packages/shared/components/SlidingSidePanel/InfoGuide/InfoGuideContext.tsx
  web/packages/shared/components/SlidingSidePanel/InfoGuide/const.ts
  web/packages/shared/components/UnifiedResources/UnifiedResources.story.tsx
  web/packages/shared/components/UnifiedResources/UnifiedResources.tsx
  web/packages/shared/components/UnifiedResources/shared/StatusInfo.story.tsx
  web/packages/shared/components/UnifiedResources/shared/StatusInfo.tsx
  web/packages/shared/components/UnifiedResources/types.ts
  web/packages/teleport/src/Databases/fixtures/index.ts
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/UnifiedResources/StatusInfo.tsx
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/databases/makeDatabase.ts
  web/packages/teleport/src/services/databases/types.ts
  web/packages/teleterm/src/ui/DocumentCluster/UnifiedResources.tsx
Labels: ui, size/md, health-check

#54619 [v17] Remove timeout for TestUpdate
  integration/autoupdate/tools/updater_test.go
Labels: backport, size/sm, no-changelog

#54624 Fix duplicate CopyNSString symbol in `lib/utils/darwinbundle`
  lib/auth/touchid/common.m
  lib/utils/darwinbundle/darwinbundle_darwin.m
  lib/vnet/daemon/common_darwin.m
Labels: size/sm, no-changelog

#54607 update test plan for db access and github proxy
  .github/ISSUE_TEMPLATE/testplan.md
  rfd/0167-debug-service.md
  rfd/0171-database-session-playback.md
  rfd/0178-github-proxy.md
  rfd/0181-pg-database-access-webui.md
  rfd/0202-db-multi-session-mfa.md
Labels: rfd, size/sm, no-changelog

#54598 [v16] Fixes potential nil return from `multiplexer.Conn.RemoteAddr()`
  lib/multiplexer/proxyline.go
  lib/multiplexer/wrapper_test.go
  lib/service/servicecfg/proxy.go
Labels: backport, size/sm

#54597 [v17] Fixes potential nil return from `multiplexer.Conn.RemoteAddr()`
  lib/multiplexer/proxyline.go
  lib/multiplexer/wrapper_test.go
  lib/service/servicecfg/proxy.go
Labels: backport, size/sm

#53566 Machine ID: Add Protos for Bound Keypair Joining
  api/client/proto/joinservice.pb.go
  api/gen/proto/go/teleport/machineid/v1/bot_instance.pb.go
  api/proto/teleport/legacy/client/proto/joinservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/machineid/v1/bot_instance.proto
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-provisiontokens.mdx
  docs/pages/reference/terraform-provider/data-sources/provision_token.mdx
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, helm, size/lg, no-changelog

#54643 Release 16.5.7
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  docs/cspell.json
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: documentation, helm, backport, size/sm, no-changelog

#54280 Add `ProxyWindowsDesktopSession` API
  api/client/proxy/client.go
  api/client/proxy/transport/transportv1/client.go
  api/gen/proto/go/teleport/transport/v1/transport_service.pb.go
  api/gen/proto/go/teleport/transport/v1/transport_service_grpc.pb.go
  api/proto/teleport/transport/v1/transport_service.proto
  lib/auth/authclient/api.go
  lib/cache/cache.go
  lib/desktop/conn.go
  lib/proxy/router.go
  lib/proxy/router_test.go
  lib/service/service.go
  lib/srv/transport/transportv1/transport.go
  lib/srv/transport/transportv1/transport_test.go
  lib/web/desktop.go
Labels: desktop-access, size/md, no-changelog, backport/branch/v17

#54317 Support Windows desktop certs in tsh
  api/utils/keypaths/keypaths.go
  lib/client/client.go
  lib/client/cluster_client.go
  lib/client/interfaces.go
  lib/client/keyagent.go
  lib/client/keystore.go
Labels: size/md, no-changelog, backport/branch/v17

#54545 Abstract directory sharing file system
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.test.tsx
  web/packages/shared/components/DesktopSession/Withholder.test.ts
  web/packages/shared/components/DesktopSession/useDesktopSession.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/shared/libs/tdp/index.ts
  web/packages/shared/libs/tdp/sharedDirectoryAccess.ts
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/lib/tdp/playerClient.ts
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#54634 Increase test timeout
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#54408 Auth: Initialize VNet config
  api/types/constants.go
  api/types/vnet/vnet.go
  lib/auth/auth.go
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/services/local/vnet_config.go
  lib/services/local/vnet_config_test.go
  lib/vnet/clusterconfigcache.go
  lib/vnet/network_stack.go
  lib/vnet/vnet_test.go
Labels: size/md, no-changelog

#54373 Support desktop access in Connect
  gen/proto/go/teleport/lib/teleterm/v1/service.pb.go
  gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.client.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.grpc-server.ts
  gen/proto/ts/teleport/lib/teleterm/v1/service_pb.ts
  lib/srv/desktop/tdp/conn.go
  lib/teleterm/api/uri/uri.go
  lib/teleterm/apiserver/handler/handler_desktops.go
  lib/teleterm/daemon/daemon.go
  lib/teleterm/services/desktop/desktop.go
  lib/web/desktop.go
  proto/teleport/lib/teleterm/v1/service.proto
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/shared/libs/tdp/codec.ts
  web/packages/teleterm/package.json
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/interceptors.ts
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
  web/packages/teleterm/src/ui/DocumentDesktopSession/index.ts
  web/packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.story.tsx
  web/packages/teleterm/src/ui/services/usage/usageService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsUtils.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/testHelpers.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
Labels: ui, size/md

#54524 [v15] fix: fixes a possible deadlock in kube moderator joining
  lib/client/kubesession.go
Labels: backport, size/sm

#54414 Update VNet docs to use `tctl edit` instead of `tctl create`
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
Labels: documentation, size/sm, no-changelog

#54616 add basic scopes pkgs
  lib/scopes/cache/cache.go
  lib/scopes/cache/cache_test.go
  lib/scopes/doc.go
  lib/scopes/scopes.go
  lib/scopes/scopes_test.go
Labels: size/xl, no-changelog

#54632 Update react-day-picker to 9.6.7
  package.json
  pnpm-lock.yaml
  web/packages/design/src/DatePicker.tsx
  web/packages/teleport/src/components/EventRangePicker/Custom/Custom.tsx
Labels: ui, size/sm, no-changelog

#54526 Default resource unresolved count values to zero
  web/packages/teleport/src/Integrations/status/AwsOidc/Details/Details.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#54521 support app label matcher for saml service provider in role v8
  lib/auth/auth_with_roles.go
  lib/services/access_checker.go
  lib/services/role.go
  lib/services/role_test.go
Labels: size/md, no-changelog

#54592 [v17] Add missing redirect
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#54498 Synchronize access to tsh exit status
  lib/client/api.go
  lib/client/client.go
  tool/tsh/common/tsh.go
Labels: tsh, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#54646 fix: unlock teleterm vnet mutex
  lib/teleterm/vnet/service.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#54673 Fix panic when listing malformed SSO users in web UI
  lib/web/ui/user.go
  lib/web/ui/user_test.go
Labels: bug, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54651 [v17] MWI: Fix certain `--no-` flags failing to override config file
  lib/tbot/cli/cli.go
  lib/tbot/cli/cli_test.go
  lib/tbot/cli/globals.go
  lib/tbot/cli/globals_test.go
  lib/tbot/cli/start_legacy.go
  lib/tbot/cli/start_shared.go
Labels: backport, machine-id, size/sm

#54674 [v17] Synchronize access to tsh exit status
  lib/client/api.go
  lib/client/client.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#54675 [v16] Synchronize access to exit status
  lib/client/api.go
  lib/client/client.go
  tool/tsh/common/tsh.go
Labels: tsh, backport, size/sm, no-changelog

#54678 [v17] fix: unlock teleterm vnet mutex
  lib/teleterm/vnet/service.go
Labels: backport, size/sm, no-changelog

#54679 [v16] fix: unlock teleterm vnet mutex
  lib/teleterm/vnet/service.go
Labels: backport, size/sm, no-changelog

#54639 [v17] Fix major version check for stateless environment
  api/gen/proto/go/teleport/backendinfo/v1/backendinfo.pb.go
  api/proto/teleport/backendinfo/v1/backendinfo.proto
  api/types/backendinfo/info.go
  api/types/constants.go
  lib/auth/auth.go
  lib/auth/helpers.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/auth/storage/storage.go
  lib/auth/version.go
  lib/service/service.go
  lib/services/backendinfo.go
  lib/services/local/backendinfo.go
  lib/services/local/backendinfo_test.go
Labels: backport, size/md

#54681 [v17] Fix panic when listing malformed SSO users in web UI
  lib/web/ui/user.go
  lib/web/ui/user_test.go
Labels: backport, size/sm

#54683 [v15] Fix panic when listing malformed SSO users in web UI
  lib/web/ui/user.go
  lib/web/ui/user_test.go
Labels: backport, size/sm

#54559 Set empty state for sync timestamps
  web/packages/design/src/SyncStamp/SyncStamp.test.tsx
  web/packages/design/src/SyncStamp/SyncStamp.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/StatCard.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#54617 Revamp the Hardware Key Support test plan
  .github/ISSUE_TEMPLATE/testplan.md
Labels: size/sm, no-changelog

#54614 fix: don't cache an incorrect PIV PIN
  api/utils/keys/hardwarekey/cliprompt.go
  api/utils/keys/piv/pincache.go
  api/utils/keys/piv/pincache_test.go
  api/utils/keys/piv/service_test.go
  api/utils/keys/piv/yubikey.go
  lib/teleterm/daemon/hardwarekeyprompt.go
Labels: size/md, backport/branch/v16, backport/branch/v17

#54652 build: Add Makefile target to install wasm-{pack,bindgen}
  .github/workflows/build-macos.yaml
  Makefile
  build.assets/Makefile
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#54702 [v16] build: Add Makefile target to install wasm-{pack,bindgen}
  .github/workflows/build-macos.yaml
  Makefile
  build.assets/Makefile
Labels: backport, size/sm, no-changelog

#54703 Release 16.5.8
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#53032 Support Access Request for GitHub proxy
  api/client/client.go
  api/types/constants.go
  api/types/server.go
  api/types/userloginstate/user_login_state.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/userloginstate/generator.go
  lib/services/access_checker.go
  lib/services/local/presence.go
  lib/services/local/presence_test.go
  tool/tsh/common/git.go
  tool/tsh/common/git_login.go
Labels: tsh, size/md, backport/branch/v17, github-integration

#54477 [v17] feat(join-tokens): [44794] Add Join Token form for GitHub
  web/packages/design/src/utils/testing.tsx
  web/packages/shared/utils/collectKeys.test.ts
  web/packages/shared/utils/collectKeys.ts
  web/packages/teleport/src/JoinTokens/JoinTokenForms.tsx
  web/packages/teleport/src/JoinTokens/JoinTokenGithubForm.test.tsx
  web/packages/teleport/src/JoinTokens/JoinTokenGithubForm.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.test.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
  web/packages/teleport/src/JoinTokens/UpsertJoinTokenDialog.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/sections.tsx
  web/packages/teleport/src/services/joinToken/joinToken.ts
  web/packages/teleport/src/services/joinToken/makeJoinToken.ts
  web/packages/teleport/src/services/joinToken/types.ts
  web/packages/teleport/src/services/yaml/types.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, machine-id, size/lg

#54656 [v17] Increase test timeout
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
Labels: ui, backport, size/sm, no-changelog

#54486 Add more telemetry to the role editor
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/usageevents/v1/usageevents.proto
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/usagereporter/teleport/types.go
  lib/usagereporter/web/userevent.go
  proto/prehog/v1alpha/teleport.proto
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/YamlEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/yamlmodel.ts
  web/packages/teleport/src/services/userEvent/types.ts
  web/packages/teleport/src/services/userEvent/userEvent.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#54659 WMI: Enable Sigstore Integration
  gen/preset-roles.json
  lib/services/presets.go
  tool/tctl/common/resource_command.go
Labels: tctl, machine-id, size/md

#54482 Workload Identity: Document Sigstore Attestation
  docs/cspell.json
  docs/img/workload-identity/sigstore-integration.png
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/workload-identity/sigstore-attestation.mdx
  docs/pages/reference/workload-identity/workload-identity-api-and-workload-attestation.mdx
Labels: documentation, machine-id, size/md, no-changelog

#54344 Make VNet service send logs to Event Log on Windows
  .gitignore
  build.assets/windows/build.ps1
  lib/utils/log/eventlog/README.md
  lib/utils/log/eventlog/eventlog_windows.go
  lib/utils/log/eventlog/msgfile.mc
  lib/utils/log/slog_text_handler_windows.go
  lib/vnet/install_service_windows.go
  lib/vnet/service_windows.go
  web/packages/teleterm/README.md
  web/packages/teleterm/build_resources/installer.nsh
  web/packages/teleterm/electron-builder-config.js
Labels: ui, size/md

#54353 Add docs for os_log and Event Log
  docs/cspell.json
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/connect-your-client/vnet.mdx
  tool/tsh/common/tsh.go
Labels: documentation, tsh, size/sm, no-changelog

#54715 [v16] Workload ID: Include attributes in issuance audit events
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/auth/machineid/workloadidentityv1/issuer_service.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
Labels: backport, machine-id, size/sm

#54672 [Web] Fix MAU banner showing up during loading on users page
  web/packages/teleport/src/Users/Users.tsx
Labels: ui, backport-required, size/sm, no-changelog, backport/branch/v17

#54695 Web: show status on unhealthy state only
  web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx
  web/packages/shared/components/UnifiedResources/ListView/ResourceListItem.tsx
  web/packages/shared/components/UnifiedResources/shared/StatusInfo.tsx
Labels: ui, size/sm, no-changelog, health-check

#54690 [v17] Default resource unresolved count values to zero
  web/packages/teleport/src/Integrations/status/AwsOidc/Details/Details.tsx
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#54712 MWI: Add SSRF protection to Sigstore discovery
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/workload-identity/sigstore-attestation.mdx
  docs/pages/reference/workload-identity/workload-identity-api-and-workload-attestation.mdx
  go.mod
  go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/tbot/workloadidentity/workloadattest/sigstore.go
  lib/tbot/workloadidentity/workloadattest/sigstore/discovery.go
  lib/tbot/workloadidentity/workloadattest/sigstore/discovery_test.go
  lib/tbot/workloadidentity/workloadattest/sigstore/repository.go
  lib/tbot/workloadidentity/workloadattest/sigstore_test.go
Labels: documentation, machine-id, size/sm

#54668 Show desktops in connection tracker
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
  web/packages/teleterm/src/ui/DocumentDesktopSession/DocumentDesktopSession.tsx
  web/packages/teleterm/src/ui/Search/pickers/results.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
  web/packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
  web/packages/teleterm/src/ui/services/connectionTracker/trackedConnectionUtils.ts
  web/packages/teleterm/src/ui/services/connectionTracker/types.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/testHelpers.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
  web/packages/teleterm/src/ui/uri.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#54692 [v17] Set empty state for sync timestamps
  web/packages/design/src/SyncStamp/SyncStamp.test.tsx
  web/packages/design/src/SyncStamp/SyncStamp.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/StatCard.tsx
Labels: ui, backport, size/sm, no-changelog

#54653 Add protos for Identity Activity Center
  api/gen/proto/go/teleport/clusterconfig/v1/access_graph.pb.go
  api/gen/proto/go/teleport/okta/v1/okta_service.pb.go
  api/proto/teleport/clusterconfig/v1/access_graph.proto
  api/proto/teleport/legacy/types/types.proto
  api/proto/teleport/okta/v1/okta_service.proto
  api/types/discoveryconfig/derived.gen.go
  api/types/types.pb.go
  gen/proto/go/accessgraph/v1alpha/access_graph_service.pb.go
  gen/proto/go/accessgraph/v1alpha/access_graph_service_grpc.pb.go
  gen/proto/go/accessgraph/v1alpha/github.pb.go
  gen/proto/go/accessgraph/v1alpha/okta.pb.go
  integrations/operator/crdgen/testdata/protofiles/teleport/okta/v1/okta_service.proto
  proto/accessgraph/v1alpha/access_graph_service.proto
  proto/accessgraph/v1alpha/github.proto
  proto/accessgraph/v1alpha/okta.proto
Labels: size/lg, no-changelog

#54697 [v17] fix: don't cache an incorrect PIV PIN
  api/utils/keys/hardwarekey/cliprompt.go
  api/utils/keys/piv/pincache.go
  api/utils/keys/piv/pincache_test.go
  api/utils/keys/piv/service_test.go
  api/utils/keys/piv/yubikey.go
  lib/teleterm/daemon/hardwarekeyprompt.go
Labels: backport, size/md

#54698 [v16] fix: don't cache an incorrect PIV PIN
  api/utils/keys/hardwarekey/cliprompt.go
  api/utils/keys/piv/pincache.go
  api/utils/keys/piv/pincache_test.go
  api/utils/keys/piv/service_test.go
  api/utils/keys/piv/yubikey.go
  lib/teleterm/daemon/hardwarekeyprompt.go
Labels: backport, size/md

#54716 [v17] Workload ID: Add `binary_path` and `binary_hash` to Unix workload attestor
  api/gen/proto/go/teleport/workloadidentity/v1/attrs.pb.go
  api/proto/teleport/workloadidentity/v1/attrs.proto
  lib/tbot/config/service_spiffe_workload_api_test.go
  lib/tbot/config/service_workload_identity_api_test.go
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/minimal.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/minimal.golden
  lib/tbot/workloadidentity/workloadattest/attest.go
  lib/tbot/workloadidentity/workloadattest/unix.go
  lib/tbot/workloadidentity/workloadattest/unix_linux.go
  lib/tbot/workloadidentity/workloadattest/unix_other.go
  lib/tbot/workloadidentity/workloadattest/unix_test.go
Labels: backport, machine-id, size/md

#51918 Remove broken apply-on-startup + add docs
  docs/pages/reference/cli/teleport.mdx
  lib/auth/init.go
  lib/auth/init_test.go
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#54611 [v15] [teleport-update] Run FIPS teleport with --fips flag
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/FIPS.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/custom.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/default.golden
  lib/autoupdate/agent/updater.go
  tool/teleport-update/main.go
Labels: backport, size/sm

#54609 [v17] [teleport-update] Run FIPS teleport with --fips flag
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/FIPS.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/custom.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/default.golden
  lib/autoupdate/agent/updater.go
  tool/teleport-update/main.go
Labels: backport, size/sm

#54610 [v16] [teleport-update] Run FIPS teleport with --fips flag
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/FIPS.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/custom.golden
  lib/autoupdate/agent/testdata/TestReplaceTeleportService/default.golden
  lib/autoupdate/agent/updater.go
  tool/teleport-update/main.go
Labels: backport, size/sm

#54731 [v18] Remove broken apply-on-startup + add docs
  docs/pages/reference/cli/teleport.mdx
  lib/auth/init.go
  lib/auth/init_test.go
Labels: documentation, backport, size/sm, no-changelog

#54701 Add .pnpm-store to .gitignore
  .gitignore
  build.assets/Makefile
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#54645 [vnet] chore: refactor for better cache sharing
  lib/teleterm/vnet/service.go
  lib/teleterm/vnet/service_darwin.go
  lib/vnet/client_application_service.go
  lib/vnet/daemon/service_darwin.go
  lib/vnet/local_app_provider.go
  lib/vnet/local_osconfig_provider.go
  lib/vnet/remote_osconfig_provider.go
  lib/vnet/unsupported_os.go
  lib/vnet/user_process.go
  lib/vnet/user_process_darwin.go
  lib/vnet/user_process_windows.go
  lib/vnet/vnet_test.go
  tool/tsh/common/vnet.go
Labels: tsh, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#54483 [v17] Update the AWS multi-region architecture guide
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
Labels: documentation, backport, size/sm, no-changelog

#54496 [v15] Update the AWS multi-region architecture guide
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
Labels: no-changelog

#54623 AWS IAM Roles Anywhere: proto changes for sync process
  api/proto/teleport/legacy/types/types.proto
  api/types/integration.go
  api/types/integration_test.go
  api/types/types.pb.go
Labels: size/md, no-changelog, backport/branch/v18

#54658 Azure Devops Join Method Protos
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-provisiontokens.mdx
  docs/pages/reference/terraform-provider/data-sources/provision_token.mdx
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/web/join_tokens_test.go
Labels: size/sm, no-changelog

#54707 [v17] build: Add Makefile target to install wasm-{pack,bindgen}
  .github/workflows/build-macos.yaml
  Makefile
  build.assets/Makefile
Labels: backport, size/sm, no-changelog

#54745 Refactor RegisterUsingToken for perf and better audit log on failure
  lib/auth/join.go
  lib/auth/join_bitbucket.go
  lib/auth/join_circleci.go
  lib/auth/join_gcp.go
  lib/auth/join_github.go
  lib/auth/join_gitlab.go
  lib/auth/join_kubernetes.go
  lib/auth/join_spacelift.go
  lib/auth/join_terraformcloud.go
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#54667 Azure DevOps token source and validator
  api/gen/proto/go/teleport/workloadidentity/v1/join_attrs.pb.go
  api/proto/teleport/workloadidentity/v1/join_attrs.proto
  go.mod
  lib/azuredevops/azuredevops.go
  lib/azuredevops/token_source.go
  lib/azuredevops/token_source_test.go
  lib/azuredevops/token_validator.go
  lib/azuredevops/token_validator_test.go
Labels: size/lg, no-changelog

#54735 [v17] Use `second_factor` in the v17 `teleport-cluster` chart
  docs/pages/reference/helm-reference/teleport-cluster.mdx
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/values.yaml
Labels: documentation, helm, size/sm

#54738 prevent role v8 to be created/updated with idp option
  api/types/role.go
  api/types/role_test.go
  gen/preset-roles.json
  integrations/operator/controllers/resources/role_controller_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/grpcserver_test.go
  lib/services/role.go
  lib/web/resources_test.go
  web/packages/shared/utils/highbar.test.ts
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.story.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/withDefaults.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v18

#54747 [v17] Refactor RegisterUsingToken for perf and better audit log on failure
  lib/auth/join.go
  lib/auth/join_bitbucket.go
  lib/auth/join_circleci.go
  lib/auth/join_gcp.go
  lib/auth/join_github.go
  lib/auth/join_gitlab.go
  lib/auth/join_kubernetes.go
  lib/auth/join_spacelift.go
  lib/auth/join_terraformcloud.go
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#54740 [v17] Do not crash when reading unsupported connection from app state
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
Labels: ui, backport, size/sm

#54488 [v15] Update cloud docs to include ap-southeast-2
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, backport, size/sm, no-changelog

#54489 [v16] Update cloud docs to include ap-southeast-2
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, backport, size/sm, no-changelog

#54741 [v16] Do not crash when reading unsupported connection from app state
  web/packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
Labels: ui, backport, size/sm

#54558 Update docs link to feature matrix
  docs/pages/core-concepts.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#54749 [v16] Refactor RegisterUsingToken for perf and better audit log on failure
  lib/auth/join.go
  lib/auth/join_bitbucket.go
  lib/auth/join_circleci.go
  lib/auth/join_gcp.go
  lib/auth/join_github.go
  lib/auth/join_gitlab.go
  lib/auth/join_kubernetes.go
  lib/auth/join_spacelift.go
  lib/auth/join_terraformcloud.go
  web/packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/sm

#54753 Terraform: add -debug flag to the provider
  integrations/terraform/main.go
Labels: size/sm, no-changelog, backport/branch/v17

#54752 [v15] Add ShuffleVisit utility function
  lib/auth/auth.go
  lib/kube/proxy/transport.go
  lib/utils/rand.go
  lib/utils/rand_test.go
  lib/web/app/match.go
  lib/web/app/session.go
  lib/web/apps.go
  lib/web/desktop.go
Labels: kubernetes-access, backport, desktop-access, size/sm, no-changelog
