Repository gravitational/teleport, pull requests merged in 2025-04, with the labels that each got.

#53531 Add VNet info tab
  web/packages/design/src/Box/Box.tsx
  web/packages/design/src/Flex/Flex.tsx
  web/packages/design/src/system/index.ts
  web/packages/design/src/theme/themes/sharedStyles.ts
  web/packages/design/src/theme/themes/types.ts
  web/packages/shared/components/DemoTerminal/DemoTerminal.story.tsx
  web/packages/shared/components/DemoTerminal/DemoTerminal.tsx
  web/packages/shared/components/DemoTerminal/index.ts
  web/packages/teleterm/src/services/tshd/cluster.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx
  web/packages/teleterm/src/ui/DocumentAuthorizeWebSession/DocumentAuthorizeWebSession.test.tsx
  web/packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.story.tsx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetInfo.story.tsx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetInfo.tsx
  web/packages/teleterm/src/ui/Vnet/VnetConnectionItem.tsx
  web/packages/teleterm/src/ui/Vnet/app-access.png
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsUtils.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/testHelpers.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
Labels: ui, size/lg, no-changelog, backport/branch/v17

#53320 [v17] Improve error message for invalid application names
  lib/auth/integration/integrationv1/service.go
  lib/config/configuration_test.go
  lib/service/servicecfg/app.go
  lib/service/servicecfg/config_test.go
  lib/services/app.go
  lib/web/scripts/install_node.go
Labels: backport, size/sm, no-changelog

#53321 [v16] Improve error message for invalid application names
  lib/auth/integration/integrationv1/service.go
  lib/config/configuration_test.go
  lib/service/servicecfg/app.go
  lib/service/servicecfg/config_test.go
  lib/services/app.go
  lib/web/scripts/install_node.go
Labels: backport, size/sm, no-changelog

#53552 Make LabelsInput accept container's size
  web/packages/design/src/ButtonIcon/ButtonIcon.jsx
  web/packages/design/src/ButtonIcon/constants.ts
  web/packages/design/src/ButtonIcon/index.ts
  web/packages/teleport/src/Bots/Add/GitHubActions/ConfigureBot.tsx
  web/packages/teleport/src/components/LabelsInput/LabelsInput.story.tsx
  web/packages/teleport/src/components/LabelsInput/LabelsInput.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53462 [v15] docs: clarify pgevents retention period
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#53628 [v17] Update pnpm to 10.7.0
  package.json
Labels: backport, size/sm, no-changelog

#53629 [v16] Update pnpm to 10.7.0
  package.json
Labels: backport, size/sm, no-changelog

#53591 [v17] fix an issue expired app session won't redirect to login on DynamoDB backend
  lib/web/app/auth.go
  lib/web/app/handler.go
  lib/web/app/handler_test.go
Labels: backport, size/sm

#53371 Add DemoMode and Status to AccessGraphSettings
  api/gen/proto/go/teleport/clusterconfig/v1/access_graph_settings.pb.go
  api/proto/teleport/clusterconfig/v1/access_graph_settings.proto
  api/types/clusterconfig/access_graph_settings.go
  api/types/clusterconfig/access_graph_settings_test.go
Labels: size/sm, no-changelog

#52873 [web] Type changes for Bidirectional Sync for Okta Integration
  lib/auth/auth.go
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#53570 [v17] docs: mention desktop support for AD and local users
  docs/pages/enroll-resources/desktop-access/active-directory.mdx
  docs/pages/enroll-resources/desktop-access/getting-started.mdx
Labels: documentation, backport, size/sm, no-changelog

#53367 Partial revert of CSRF auth related removals
  lib/client/https_client.go
  lib/web/apiserver.go
Labels: ui, size/sm, size/md, no-changelog

#53514 [v16] Clean up LDAP packages
  lib/auth/windows/ldap.go
  lib/auth/windows/windows.go
  lib/auth/windows/windows_test.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
Labels: backport, desktop-access, size/sm, no-changelog

#53590 Auth: Rework resourceAccess to unifiedResourceLister
  lib/auth/auth_with_roles.go
Labels: size/sm, no-changelog, backport/branch/v17

#53648 Release 17.4.2
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#53632 [v17] docs: Oracle RDS guide
  docs/cspell.json
  docs/img/database-access/guides/aws_ad_set_spn.png
  docs/pages/enroll-resources/database-access/enroll-aws-databases/rds-oracle.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/sql-server-ad.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
Labels: documentation, backport, size/md, no-changelog

#53530 [v17] Hide validation errors on newly added sections
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StatefulSection.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.test.ts
Labels: ui, backport, size/md, no-changelog

#53655 Update go.mod replace section for sub-projects
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm, no-changelog, backport/branch/v17

#53623 Integrate VNet info tab with first VNet launch and deep link
  web/packages/shared/components/Notification/Notification.tsx
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/services/vnet/app.ts
  web/packages/teleterm/src/ui/DeepLinks/DeepLinks.tsx
  web/packages/teleterm/src/ui/DeepLinks/launchDeepLink.test.ts
  web/packages/teleterm/src/ui/DeepLinks/launchDeepLink.ts
  web/packages/teleterm/src/ui/Document/Document.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.tsx
  web/packages/teleterm/src/ui/Search/actions.tsx
  web/packages/teleterm/src/ui/Search/pickers/ActionPicker.tsx
  web/packages/teleterm/src/ui/Search/pickers/useActionAttempts.ts
  web/packages/teleterm/src/ui/TabHost/TabHost.story.tsx
  web/packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetInfo.tsx
  web/packages/teleterm/src/ui/Vnet/VnetSliderStep.story.tsx
  web/packages/teleterm/src/ui/Vnet/index.ts
  web/packages/teleterm/src/ui/Vnet/integration.test.tsx
  web/packages/teleterm/src/ui/Vnet/useVnetAppLauncher.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.test.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.tsx
  web/packages/teleterm/src/ui/hooks/usePersistedState.test.tsx
  web/packages/teleterm/src/ui/hooks/usePersistedState.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.test.ts
  web/packages/teleterm/src/ui/services/resources/resourcesService.ts
  web/packages/teleterm/src/ui/services/statePersistence/statePersistenceService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/testHelpers.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#53365 [web] Fix CollapsibleInfoSection animation with `defaultOpen`
  web/packages/design/src/CollapsibleInfoSection/CollapsibleInfoSection.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#53535 Add RoleEditorVisualizer to Role Editor
  web/packages/teleport/src/Roles/PolicyPlaceholder.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorVisualizer.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorVisualizer.tsx
  web/packages/teleport/src/Roles/Roles.test.tsx
  web/packages/teleport/src/Roles/Roles.tsx
Labels: ui, size/md, no-changelog

#53335 [v17] Clarify the config file in Installation
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53633 [v16] Add correct principal for agentless nodes on leaf clusters
  lib/proxy/router.go
  lib/proxy/router_test.go
Labels: backport, size/sm, no-changelog

#53336 [v16] Clarify the config file in Installation
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53513 [v17] Clean up LDAP packages
  lib/auth/windows/ldap.go
  lib/auth/windows/windows.go
  lib/auth/windows/windows_test.go
  lib/srv/desktop/discovery.go
  lib/srv/desktop/discovery_test.go
  lib/srv/desktop/windows_server.go
  lib/srv/desktop/windows_server_test.go
Labels: backport, desktop-access, size/sm, no-changelog

#53416 [v16] Edit DNS guidance for registered apps
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  docs/pages/includes/dns-app-access.mdx
Labels: documentation, backport, size/sm, no-changelog

#52928 Refresh the Backup and Restore guide
  docs/pages/admin-guides/management/operations/backup-restore.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53337 [v15] Clarify the config file in Installation
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53664 Docs: fix typo in url for openid configuration
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53661 [v17] Update go.mod replace section for sub-projects
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#53649 Web: define func that determines if error is path not found type
  web/packages/teleport/src/services/version/unsupported.test.ts
  web/packages/teleport/src/services/version/unsupported.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#53654 Web: allow customizing info guide side panel
  web/packages/teleport/src/AuthConnectors/AuthConnectorEditor/AuthConnectorEditorContent.tsx
  web/packages/teleport/src/AuthConnectors/AuthConnectors.tsx
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Discover/Discover.tsx
  web/packages/teleport/src/Discover/Overview/Overview.tsx
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
  web/packages/teleport/src/Main/InfoGuideContext.tsx
  web/packages/teleport/src/Main/Main.test.tsx
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/components/SlidingSidePanel/InfoGuideSidePanel/InfoGuideSidePanel.story.tsx
  web/packages/teleport/src/components/SlidingSidePanel/InfoGuideSidePanel/InfoGuideSidePanel.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#53653 github: Fix Proto compatibility check for non-release base branches
  .github/workflows/lint.yaml
  rfd/cspell.json
Labels: rfd, size/sm, no-changelog

#53673 [v17] [web] Type changes for Bidirectional Sync for Okta Integration
  lib/auth/auth.go
  web/packages/teleport/src/services/integrations/types.ts
Labels: ui, backport, size/sm, no-changelog

#53642 Add Workload Identity EmptyState
  web/packages/teleport/src/WorkloadIdentity/EmptyState/EmptyState.tsx
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_1_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_1_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_2_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_2_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_3_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_3_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/WorkloadIdentity.story.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/types.ts
Labels: ui, backport-required, size/md, no-changelog, backport/branch/v17

#53468 Introduce TanStack query
  package.json
  pnpm-lock.yaml
  web/.storybook/preview.tsx
  web/packages/design/src/utils/testing.tsx
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/services/queryHelpers.ts
Labels: ui, size/md, no-changelog, backport/branch/v16, backport/branch/v17

#53658 [v17] Auth: Rework resourceAccess to unifiedResourceLister
  lib/auth/auth_with_roles.go
Labels: backport, size/sm, no-changelog

#53683 [v17] Introduce TanStack query
  package.json
  pnpm-lock.yaml
  web/.storybook/preview.tsx
  web/packages/design/src/utils/testing.tsx
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/services/queryHelpers.ts
Labels: ui, backport, size/md, no-changelog

#53684 [v16] Introduce TanStack query
  package.json
  pnpm-lock.yaml
  web/.storybook/preview.js
  web/packages/design/src/utils/testing.tsx
  web/packages/teleport/src/Teleport.tsx
  web/packages/teleport/src/services/queryHelpers.ts
Labels: ui, backport, size/md, no-changelog

#53665 docs: include Oracle RDS in AWS Database enrollment page
  docs/pages/enroll-resources/database-access/enroll-aws-databases/enroll-aws-databases.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#53354 docs: update tokens creation for rbac api
  docs/pages/admin-guides/api/rbac.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53692 [v16] docs: update tokens creation for rbac api
  docs/pages/admin-guides/api/rbac.mdx
Labels: documentation, backport, size/sm, no-changelog

#53640 [v16] Remove legacy `TabsItem` usage
  docs/pages/includes/database-access/iam_role_trust_relationship.mdx
Labels: documentation, backport, size/sm, no-changelog

#53690 [v17] docs: rbac api token and oracle rds listing
  docs/pages/admin-guides/api/rbac.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/enroll-aws-databases.mdx
Labels: documentation, backport, size/sm, no-changelog

#53667 [v16] Refresh the Backup and Restore guide
  docs/pages/admin-guides/management/operations/backup-restore.mdx
Labels: documentation, backport, size/sm, no-changelog

#53641 [v15] Remove legacy `TabsItem` usage
  docs/pages/includes/database-access/iam_role_trust_relationship.mdx
Labels: documentation, backport, size/sm, no-changelog

#53668 [v15] Refresh the Backup and Restore guide
  docs/pages/admin-guides/management/operations/backup-restore.mdx
Labels: documentation, backport, size/sm, no-changelog

#53639 [v17] Remove legacy `TabsItem` usage
  docs/pages/includes/database-access/iam_role_trust_relationship.mdx
Labels: documentation, backport, size/sm, no-changelog

#53681 [v17] Docs: fix typo in url for openid configuration
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53597 Handle Access Requests in Okta read-only mode
  api/types/okta.go
  api/types/okta_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/init.go
  lib/auth/okta/auth.go
  lib/okta/oktatest/helpers.go
  lib/okta/plugin/okta_plugin.go
Labels: size/lg, no-changelog, backport/branch/v17

#53696 [v15] Move IronRDP to `web/shared`
  Cargo.toml
  Makefile
  package.json
  web/README.md
  web/packages/shared/README.md
  web/packages/shared/libs/ironrdp/Cargo.toml
  web/packages/shared/libs/ironrdp/src/lib.rs
  web/packages/shared/package.json
  web/packages/teleport/package.json
  web/packages/teleport/src/lib/tdp/client.ts
  web/scripts/clean-up-ironrdp-artifacts.mjs
Labels: ui, backport, size/sm, no-changelog

#53697 [v17] Handle Access Requests in Okta read-only mode
  api/types/okta.go
  api/types/okta_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/init.go
  lib/auth/okta/auth.go
  lib/okta/oktatest/helpers.go
  lib/okta/plugin/okta_plugin.go
Labels: backport, size/lg, no-changelog

#53670 [v17] Web: allow customizing info guide side panel
  web/packages/teleport/src/AuthConnectors/AuthConnectorEditor/AuthConnectorEditorContent.tsx
  web/packages/teleport/src/AuthConnectors/AuthConnectors.tsx
  web/packages/teleport/src/Bots/Add/AddBotsPicker.tsx
  web/packages/teleport/src/Bots/List/Bots.tsx
  web/packages/teleport/src/Discover/Discover.tsx
  web/packages/teleport/src/Discover/Overview/Overview.tsx
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/JoinTokens/JoinTokens.tsx
  web/packages/teleport/src/Main/InfoGuideContext.tsx
  web/packages/teleport/src/Main/Main.test.tsx
  web/packages/teleport/src/Main/Main.tsx
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/components/SlidingSidePanel/InfoGuideSidePanel/InfoGuideSidePanel.story.tsx
  web/packages/teleport/src/components/SlidingSidePanel/InfoGuideSidePanel/InfoGuideSidePanel.tsx
Labels: ui, backport, size/sm, no-changelog

#53672 [v17] [web] Fix CollapsibleInfoSection animation with `defaultOpen`
  web/packages/design/src/CollapsibleInfoSection/CollapsibleInfoSection.tsx
Labels: ui, backport, size/sm, no-changelog

#53601 access_monitoring_rule: Restructure the automatic review spec
  api/gen/proto/go/teleport/accessmonitoringrules/v1/access_monitoring_rules.pb.go
  api/proto/teleport/accessmonitoringrules/v1/access_monitoring_rules.proto
  api/types/constants.go
  docs/pages/reference/terraform-provider/data-sources/access_monitoring_rule.mdx
  docs/pages/reference/terraform-provider/resources/access_monitoring_rule.mdx
  integrations/terraform/tfschema/accessmonitoringrules/v1/access_monitoring_rules_terraform.go
  lib/services/access_monitoring_rules.go
  lib/services/access_monitoring_rules_test.go
  lib/services/local/access_monitoring_rules.go
  lib/services/local/access_monitoring_rules_test.go
  web/packages/teleport/src/services/resources/types.ts
Labels: documentation, ui, size/md, no-changelog

#53682 [v16] Docs: fix typo in url for openid configuration
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53630 [v17] Documentation changes for Windows tbot
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/includes/device-trust/prereqs.mdx
  docs/pages/includes/install-windows-clients.mdx
  docs/pages/includes/install-windows.mdx
  docs/pages/installation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53686 [17.4.1] bump cloud docs
  docs/config.json
Labels: documentation, size/sm, no-changelog

#53689 [v17] Add Workload Identity EmptyState
  web/packages/teleport/src/WorkloadIdentity/EmptyState/EmptyState.tsx
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_1_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_1_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_2_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_2_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_3_dark_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/EmptyState/workload_identity_feature_3_light_mode-min.svg
  web/packages/teleport/src/WorkloadIdentity/WorkloadIdentity.story.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/types.ts
Labels: ui, backport, size/md, no-changelog

#53700 Abstract TDP transport layer
  web/packages/shared/components/DesktopSession/DesktopSession.story.tsx
  web/packages/shared/components/DesktopSession/DesktopSession.tsx
  web/packages/shared/libs/tdp/client.ts
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/Player/Player.story.tsx
  web/packages/teleport/src/lib/tdp/index.ts
  web/packages/teleport/src/lib/tdp/playerClient.ts
  web/packages/teleport/src/lib/tdp/webSocketTransportAdapter.ts
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53685 Force focus Connect window after enabling VNet daemon
  build.assets/macos/tshdev/.gitignore
  web/packages/teleterm/src/mainProcess/fixtures/mocks.ts
  web/packages/teleterm/src/mainProcess/mainProcess.ts
  web/packages/teleterm/src/mainProcess/mainProcessClient.ts
  web/packages/teleterm/src/mainProcess/types.ts
  web/packages/teleterm/src/mainProcess/windowsManager.test.ts
  web/packages/teleterm/src/mainProcess/windowsManager.ts
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.tsx
  web/packages/teleterm/src/ui/Vnet/DocumentVnetInfo.tsx
  web/packages/teleterm/src/ui/Vnet/integration.test.tsx
  web/packages/teleterm/src/ui/Vnet/useVnetAppLauncher.tsx
  web/packages/teleterm/src/ui/Vnet/vnetContext.tsx
  web/packages/teleterm/src/ui/services/headlessAuthn/headlessAuthnService.ts
  web/packages/teleterm/src/ui/services/relogin/reloginService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/testHelpers.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
  web/packages/teleterm/src/ui/tshdEvents.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#53720 [v16] Optimize desktop backend reads
  lib/services/local/desktops.go
  lib/services/local/desktops_test.go
Labels: backport, size/md

#53716 [v16] [17.4.1] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#53718 docs: update storage backends to include AWS S3 for audit events
  docs/pages/reference/backends.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53717 [v15] [17.4.1] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#53095 [v16] Support context path for Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/services/app_test.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery

#53096 [v15] Support context path for Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/services/app_test.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery

#53732 [v15] docs: update storage backends to include AWS S3 for audit events
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#53731 [v16] docs: update storage backends to include AWS S3 for audit events
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#53730 [v17] docs: update storage backends to include AWS S3 for audit events
  docs/pages/reference/backends.mdx
Labels: documentation, backport, size/sm, no-changelog

#53712 docs: update tctl status example in ca rotation
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#53094 [v17] Support context path for Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/services/app_test.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery

#53573 Manual post release updates for v16.5.0
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#53747 Add auditlog exports to TAG via grpc
  api/client/client.go
  api/gen/proto/go/teleport/clusterconfig/v1/access_graph.pb.go
  api/proto/teleport/clusterconfig/v1/access_graph.proto
  gen/proto/go/accessgraph/v1alpha/access_graph_service.pb.go
  gen/proto/go/accessgraph/v1alpha/access_graph_service_grpc.pb.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/events/export/date_exporter.go
  lib/events/export/exporter.go
  lib/service/servicecfg/config.go
  proto/accessgraph/v1alpha/access_graph_service.proto
Labels: audit-log, size/md, no-changelog

#53656 docs: update build instructions for access request plugins
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/includes/plugins/install-access-request.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53638 Remove legacy `TabsItem` usage
  docs/pages/includes/database-access/iam_role_trust_relationship.mdx
Labels: documentation, size/sm, no-changelog

#53342 Update teleport.teleport_install_script_url
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53752 docs: include signature algorithm suite in auth config
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#53139 [v16] Remove two-dimensional and dropdown-only docs Tabs
  docs/pages/enroll-resources/application-access/cloud-apis/azure-aks-workload-id.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/google-cloud.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/includes/application-access/azure-teleport-role.mdx
  docs/pages/includes/database-access/aws-db-iam-policy-picker.mdx
  docs/pages/includes/discovery/aws-db-discovery-config-picker.mdx
  docs/pages/includes/discovery/aws-db-iam-policy-picker.mdx
  docs/pages/includes/install-linux-enterprise.mdx
Labels: documentation, backport, size/sm, no-changelog

#53751 No longer show "Fatal error" on normal closure of SPIFFEFederationSyncer
  lib/auth/machineid/machineidv1/spiffe_federation_syncer.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53757 [v17] docs: include signature algorithm suite in auth config
  docs/pages/includes/config-reference/auth-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#53755 [v16] docs: update build instructions for access request plugins
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/includes/plugins/install-access-request.mdx
Labels: documentation, backport, size/sm, no-changelog

#53754 [v17] docs: update build instructions for access request plugins
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/includes/plugins/install-access-request.mdx
Labels: documentation, backport, size/sm, no-changelog

#53735 Pyroscope flush on shutdown
  lib/service/pyroscope.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52875 Workload ID: Document the Systemd attestor and Unix improvements
  docs/cspell.json
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/workload-identity/attributes.mdx
  docs/pages/reference/workload-identity/workload-identity-api-and-workload-attestation.mdx
Labels: documentation, machine-id, size/sm, no-changelog, backport/branch/v17

#53756 [v15] docs: update build instructions for access request plugins
  docs/pages/admin-guides/access-controls/guides/dual-authz.mdx
  docs/pages/includes/plugins/install-access-request.mdx
Labels: documentation, backport, size/sm, no-changelog

#53759 [v17] No longer show "Fatal error" on normal closure of SPIFFEFederationSyncer
  lib/auth/machineid/machineidv1/spiffe_federation_syncer.go
Labels: backport, size/sm, no-changelog

#53635 Use checkboxes for resource permissions (verbs)
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#53733 Clarify compatibility contract between Managed Updates v1 and v2 in docs
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53644 Remember current standard editor tab
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#53760 [v15] Pyroscope flush on shutdown
  lib/service/pyroscope.go
Labels: backport, size/sm, no-changelog

#53761 [v16] Pyroscope flush on shutdown
  lib/service/pyroscope.go
Labels: backport, size/sm, no-changelog

#53657 [v17] Clarify the wording in role editor
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
Labels: ui, backport, size/sm, no-changelog

#53600 Temporarily force pass tflint
  .github/workflows/terraform-lint.yaml
  .tflint.hcl
  examples/terraform-starter/main.tf
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53741 Support SSO MFA for headless
  .github/ISSUE_TEMPLATE/testplan.md
  lib/auth/auth_with_roles.go
  lib/client/weblogin.go
  lib/web/headless.go
  rfd/0180-sso-mfa.md
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.test.tsx
  web/packages/teleport/src/HeadlessRequest/HeadlessRequest.tsx
  web/packages/teleport/src/services/auth/auth.ts
Labels: ui, rfd, size/sm

#53671 feat: Hardware Key Agent - Add `api/utils/keys/hardwarekey` package
  api/client/webclient/webclient.go
  api/profile/profile.go
  api/types/authentication.go
  api/utils/keys/alias.go
  api/utils/keys/cliprompt.go
  api/utils/keys/hardwarekey/attestation.go
  api/utils/keys/hardwarekey/cliprompt.go
  api/utils/keys/hardwarekey/cliprompt_test.go
  api/utils/keys/hardwarekey/prompt.go
  api/utils/keys/hardwarekey/slot.go
  api/utils/keys/hardwarekey/slot_test.go
  api/utils/keys/hardwaresigner.go
  api/utils/keys/policy.go
  api/utils/keys/policy_piv.go
  api/utils/keys/privatekey.go
  api/utils/keys/yubikey.go
  api/utils/keys/yubikey_common.go
  api/utils/keys/yubikey_fake.go
  api/utils/keys/yubikey_other.go
  api/utils/keys/yubikey_test.go
  integration/autoupdate/tools/updater/modules.go
  integration/proxy/teleterm_test.go
  integration/teleterm_test.go
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/clt.go
  lib/auth/github.go
  lib/auth/sessions.go
  lib/client/api.go
  lib/client/client_store.go
  lib/client/cluster_client.go
  lib/client/keystore.go
  lib/client/weblogin.go
  lib/config/fileconf.go
  lib/modules/modules.go
  lib/modules/test.go
  lib/teleterm/clusters/config.go
  lib/teleterm/daemon/daemon_test.go
  lib/teleterm/daemon/hardwarekeyprompt.go
  lib/teleterm/teleterm.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, size/md, no-changelog

#52600 docs: edits to CA rotation docs
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#52912 docs: update warning on data dir on daemon guide
  docs/pages/admin-guides/management/admin/daemon.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53602 [teleport-update] Add local updater metadata
  api/client/webclient/webclient.go
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestUpdater_Install/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_kept_for_validation.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_does_not_exist.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_file.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_user.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/defaults.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/no_need_to_reload.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/override_skip.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/version_already_installed.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/agpl_requires_base_URL.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_is_linked.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/install_error.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/setup_fails.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_during_window.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now,_not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/version_detects_as_linked.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: size/md, backport/branch/v16, backport/branch/v17

#53489 Update fedramp.mdx with v17 migration instructions
  docs/pages/admin-guides/access-controls/compliance-frameworks/fedramp.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#53744 Migrate lib/player tests to testing/synctest
  Makefile
  lib/player/player_experimental_test.go
  lib/player/player_test.go
Labels: size/sm, no-changelog

#53777 [v16] docs: update warning on data dir on daemon guide
  docs/pages/admin-guides/management/admin/daemon.mdx
Labels: documentation, backport, size/sm, no-changelog

#53586 [v16] Workload ID: Support custom claims in JWT-SVIDs
  api/gen/proto/go/teleport/workloadidentity/v1/resource.pb.go
  api/proto/teleport/workloadidentity/v1/resource.proto
  integrations/terraform/protoc-gen-terraform-workloadidentity.yaml
  integrations/terraform/tfschema/workloadidentity/v1/resource_terraform.go
  lib/auth/machineid/workloadidentityv1/decision.go
  lib/auth/machineid/workloadidentityv1/decision_test.go
  lib/auth/machineid/workloadidentityv1/issuer_service.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/jwt/jwt.go
Labels: backport, machine-id, size/md

#53763 Okta: Align sync settings methods
  api/types/okta.go
  api/types/okta_test.go
  lib/auth/okta/auth.go
Labels: size/sm, no-changelog, backport/branch/v17

#53676 add Microsoft Entra ID SAML service provider preset
  api/types/saml_idp_service_provider.go
  api/types/samlsp/samlsp.go
  lib/services/local/saml_idp_service_provider.go
  lib/services/local/saml_idp_service_provider_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#53790 Avoid throttling on dynamodb DescribeStream
  lib/backend/dynamo/shards.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53771 Update docs with new ingress IPs for apse2
  docs/pages/ips.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53795 Avoid losing events at the end of a DynamoDB shard
  lib/backend/dynamo/shards.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52616 [web] Add hooks for ResizeObserver / element size
  web/packages/build/jest/jest-environment-patched-jsdom.js
  web/packages/build/jest/setupTests.ts
  web/packages/design/src/CollapsibleInfoSection/CollapsibleInfoSection.tsx
  web/packages/design/src/Popover/Transition.tsx
  web/packages/design/src/utils/useElementSize.test.tsx
  web/packages/design/src/utils/useElementSize.ts
  web/packages/design/src/utils/useResizeObserver.test.tsx
  web/packages/design/src/utils/useResizeObserver.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/sections.tsx
Labels: ui, size/md, no-changelog, backport/branch/v17

#53820 [v16] Fix dependency review workflow
  .github/workflows/dependency-review.yaml
Labels: backport, size/sm, no-changelog

#53821 [v15] Fix dependency review workflow
  .github/workflows/dependency-review.yaml
Labels: backport, size/sm, no-changelog

#53804 [v17] Avoid throttling on dynamodb DescribeStream
  lib/backend/dynamo/shards.go
Labels: backport, size/sm

#53818 [v17] Avoid losing events at the end of a DynamoDB shard
  lib/backend/dynamo/shards.go
Labels: backport, size/sm, no-changelog

#53806 [v15] Avoid throttling on dynamodb DescribeStream
  lib/backend/dynamo/shards.go
Labels: backport, size/sm

#53822 [v16] Avoid losing events at the end of a DynamoDB shard
  lib/backend/dynamo/shards.go
Labels: backport, size/sm, no-changelog

#53775 Release 17.4.3
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#53833 Remove beta wording for Managed Updates v2
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53828 [v17] [teleport-update] Add local updater metadata
  api/client/webclient/webclient.go
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestUpdater_Install/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_kept_for_validation.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_does_not_exist.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_file.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_user.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/defaults.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/no_need_to_reload.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/override_skip.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/version_already_installed.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/agpl_requires_base_URL.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_is_linked.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/install_error.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/setup_fails.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_during_window.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now,_not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/version_detects_as_linked.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: backport, size/md

#53829 [v16] [teleport-update] Add local updater metadata
  api/client/webclient/webclient.go
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/setup_test.go
  lib/autoupdate/agent/testdata/TestUpdater_Install/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_kept_for_validation.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_does_not_exist.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_file.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/config_from_user.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/defaults.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/no_need_to_reload.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/override_skip.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/version_already_installed.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/FIPS_and_Enterprise_flags.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/agpl_requires_base_URL.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_is_linked.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/backup_version_removed_on_install.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/install_error.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/setup_fails.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_during_window.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now,_not_started_or_enabled.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/updates_enabled_now.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/version_detects_as_linked.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: backport, size/md

#53768 [v17] Clarify compatibility contract between Managed Updates v1 and v2 in docs
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#53823 [v15] Avoid losing events at the end of a DynamoDB shard
  lib/backend/dynamo/shards.go
Labels: backport, size/sm, no-changelog

#53774 [v17] docs: edits to CA rotation docs
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
Labels: documentation, backport, size/sm, no-changelog

#53838 [v17] Remove beta wording for Managed Updates v2
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#53776 [v17] docs: update warning on data dir on daemon guide
  docs/pages/admin-guides/management/admin/daemon.mdx
Labels: documentation, backport, size/sm, no-changelog

#53762 [v17] Pyroscope flush on shutdown
  lib/service/pyroscope.go
Labels: backport, size/sm, no-changelog

#53764 [v17] Use checkboxes for resource permissions (verbs)
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, backport, size/md, no-changelog

#53770 An endpoint that returns a single role
  lib/web/apiserver.go
  lib/web/resources.go
  lib/web/resources_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#53705 [netiq] add `entitlements` field to `NetIQResourceAssignmentRef`
  gen/proto/go/accessgraph/v1alpha/netiq.pb.go
  proto/accessgraph/v1alpha/netiq.proto
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53851 docs: update shrinking guidance for k8s upgrade
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53846 [v17][netiq] add `entitlements` field to `NetIQResourceAssignmentRef`
  gen/proto/go/accessgraph/v1alpha/netiq.pb.go
  proto/accessgraph/v1alpha/netiq.proto
Labels: backport, size/sm, no-changelog

#53800 Allow cloud to update access graph settings
  lib/auth/clusterconfig/clusterconfigv1/service.go
Labels: size/sm, no-changelog

#53484 Operator support for WorkloadIdentity resource
  docs/pages/reference/operator-resources/resources-teleport-dev-workloadidentitiesv1.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_workloadidentitiesv1.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/role.yaml
  examples/chart/teleport-cluster/templates/auth/config.yaml
  integrations/operator/Makefile
  integrations/operator/apis/resources/v1/workload_identityv1_types.go
  integrations/operator/apis/resources/v1/zz_generated.deepcopy.go
  integrations/operator/config/crd/bases/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/controllers/resources/setup.go
  integrations/operator/controllers/resources/testlib/compare.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/workload_identityv1_controller.go
  integrations/operator/controllers/resources/workload_identityv1_controller_test.go
  integrations/operator/crdgen/Makefile
  integrations/operator/crdgen/handlerequest.go
  integrations/operator/crdgen/schemagen.go
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/hack/fixture-operator-role.yaml
Labels: documentation, helm, size/lg, backport/branch/v17

#53808 [v16] Update docs with new ingress IPs for apse2
  docs/pages/ips.mdx
Labels: documentation, backport, size/sm, no-changelog

#53834 Omit unresolved tasks on resource if empty
  lib/web/ui/integration.go
Labels: size/sm, no-changelog, backport/branch/v17

#53854 [v15] docs: update shrinking guidance for k8s upgrade
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, backport, size/sm, no-changelog

#53853 [v16] docs: update shrinking guidance for k8s upgrade
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, backport, size/sm, no-changelog

#53852 [v17] docs: update shrinking guidance for k8s upgrade
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, backport, size/sm, no-changelog

#53789 Docs: fix links to Azure portal
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/includes/database-access/azure-configure-service-principal.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53807 [v17] Update docs with new ingress IPs for apse2
  docs/pages/ips.mdx
Labels: documentation, backport, size/sm, no-changelog

#53864 [v17] Omit unresolved tasks on resource if empty
  lib/web/ui/integration.go
Labels: backport, size/sm, no-changelog

#53787 WMI: Allow max TTL for X509 and JWT SVIDs to be configured
  api/gen/proto/go/teleport/workloadidentity/v1/resource.pb.go
  api/proto/teleport/workloadidentity/v1/resource.proto
  docs/pages/reference/operator-resources/resources-teleport-dev-workloadidentitiesv1.mdx
  docs/pages/reference/terraform-provider/data-sources/workload_identity.mdx
  docs/pages/reference/terraform-provider/resources/workload_identity.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_roles.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv6.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_rolesv7.yaml
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/crdgen/testdata/protofiles/teleport/accessmonitoringrules/v1/access_monitoring_rules.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/clusterconfig/v1/access_graph_settings.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/events/events.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/workloadidentity/v1/attrs.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/workloadidentity/v1/resource.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/workloadidentity/v1/x509_overrides.proto
  integrations/operator/crdgen/testdata/protofiles/teleport/workloadidentity/v1/x509_overrides_service.proto
  integrations/terraform/protoc-gen-terraform-workloadidentity.yaml
  integrations/terraform/tfschema/workloadidentity/v1/custom_types.go
  integrations/terraform/tfschema/workloadidentity/v1/resource_terraform.go
  lib/auth/machineid/workloadidentityv1/issuer_service.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/workload_identity.go
  lib/services/workload_identity_test.go
  lib/tbot/config/config.go
  lib/tbot/config/service_workload_identity_api.go
  lib/tbot/config/service_workload_identity_jwt.go
  lib/tbot/config/service_workload_identity_x509.go
Labels: documentation, size/md, backport/branch/v16, backport/branch/v17

#53862 [v17] Operator support for WorkloadIdentity resource
  docs/pages/reference/operator-resources/resources-teleport-dev-workloadidentitiesv1.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_workloadidentitiesv1.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/templates/role.yaml
  examples/chart/teleport-cluster/templates/auth/config.yaml
  integrations/operator/Makefile
  integrations/operator/apis/resources/v1/workload_identityv1_types.go
  integrations/operator/apis/resources/v1/zz_generated.deepcopy.go
  integrations/operator/config/crd/bases/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/controllers/resources/setup.go
  integrations/operator/controllers/resources/testlib/compare.go
  integrations/operator/controllers/resources/testlib/env.go
  integrations/operator/controllers/resources/workload_identityv1_controller.go
  integrations/operator/controllers/resources/workload_identityv1_controller_test.go
  integrations/operator/crdgen/Makefile
  integrations/operator/crdgen/handlerequest.go
  integrations/operator/crdgen/schemagen.go
  integrations/operator/crdgen/testdata/golden/resources.teleport.dev_workloadidentitiesv1.yaml
  integrations/operator/hack/fixture-operator-role.yaml
Labels: documentation, helm, backport, size/lg

#51632 Allow downgrading PROXY headers from IPv6 to pseudo IPv4
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/multiplexer/multiplexer.go
  lib/multiplexer/multiplexer_test.go
  lib/multiplexer/proxyline.go
  lib/multiplexer/proxyline_test.go
  lib/multiplexer/wrapper_test.go
  lib/multiplexer/wrappers.go
  lib/service/service.go
  lib/service/servicecfg/proxy.go
Labels: size/md, backport/branch/v16, backport/branch/v17

#53571 Update gravitational/license
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#53825 docs: update git clone for terraform starter
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/enroll-resources.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#53779 docs: mention Teleport SAML IdP in Identity Center guide next steps
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/guide.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#53858 auth: prevent cnc agent connection count updates on cloud
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/clusterconfig/clusterconfigv1/service_test.go
Labels: size/md, no-changelog, backport/branch/v16, backport/branch/v17

#53839 [v17] [web] Add hooks for ResizeObserver / element size
  web/packages/build/jest/jest-environment-patched-jsdom.js
  web/packages/build/jest/setupTests.ts
  web/packages/design/src/CollapsibleInfoSection/CollapsibleInfoSection.tsx
  web/packages/design/src/Popover/Transition.tsx
  web/packages/design/src/utils/useElementSize.test.tsx
  web/packages/design/src/utils/useElementSize.ts
  web/packages/design/src/utils/useResizeObserver.test.tsx
  web/packages/design/src/utils/useResizeObserver.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/sections.tsx
Labels: ui, backport, size/md, no-changelog

#53882 fix flaky TestMarshalAndParseKey
  api/utils/keys/privatekey_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#53780 Web: create list db_server endpoint
  lib/web/apiserver.go
  lib/web/databases_test.go
  lib/web/servers.go
  web/packages/shared/components/UnifiedResources/types.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/databases/databases.ts
  web/packages/teleport/src/services/databases/makeDatabase.ts
  web/packages/teleport/src/services/databases/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17
