Repository gravitational/teleport, pull requests merged in 2025-02, with the labels that each got.

#51728 [v17] [Web] Remove local notifications
  web/packages/teleport/src/Notifications/Notification.tsx
  web/packages/teleport/src/Notifications/Notifications.tsx
  web/packages/teleport/src/services/notifications/types.ts
  web/packages/teleport/src/stores/index.ts
  web/packages/teleport/src/stores/storeNotifications.test.ts
  web/packages/teleport/src/stores/storeNotifications.ts
  web/packages/teleport/src/teleportContext.tsx
Labels: ui, backport, size/sm, no-changelog

#51688 [v17] Follow up on Web MFA TODOs
  web/packages/teleport/src/Account/ManageDevices/wizards/AddAuthDeviceWizard.tsx
  web/packages/teleport/src/services/auth/auth.ts
Labels: ui, backport, size/sm, no-changelog

#51720 [v15] Fix misaligned command usage for 'help' commands of Teleport binaries
  lib/utils/cli.go
  lib/utils/cli_test.go
Labels: backport, size/sm, no-changelog

#51761 Update integrity keys used by corepack
  .github/workflows/build-macos.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui.yaml
  build.assets/Dockerfile
  build.assets/Dockerfile-arm
  build.assets/Dockerfile-node
  build.assets/versions.mk
  build.assets/windows/build.ps1
  package.json
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51616 Always create debug socket and expose health endpoints
  constants.go
  lib/service/diagnostic.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/srv/debug/handlers.go
  lib/srv/debug/handlers_test.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51461 docs: remove sudo tctl users reference in cloud install docs
  docs/pages/includes/cloud/install-linux-cloud.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51769 [v16] Update integrity keys used by corepack
  .github/workflows/build-macos.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui.yaml
  build.assets/Dockerfile
  build.assets/Dockerfile-arm
  build.assets/Dockerfile-node
  build.assets/versions.mk
  build.assets/windows/build.ps1
  package.json
Labels: backport, size/sm, no-changelog

#51774 [v16] chore: Bump github.com/gravitational/trace to v1.4.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#51768 [v17] Update integrity keys used by corepack
  .github/workflows/build-macos.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/unit-tests-ui.yaml
  build.assets/Dockerfile
  build.assets/Dockerfile-arm
  build.assets/Dockerfile-node
  build.assets/versions.mk
  build.assets/windows/build.ps1
  package.json
Labels: backport, size/sm, no-changelog

#51521 Add kubernetes enrichment option with pyroscope
  lib/service/pyroscope.go
  lib/service/pyroscope_test.go
Labels: size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51726 [teleport-update] Only use CDN for community / enterprise editions
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/testdata/TestUpdater_Install/agpl_requires_base_URL.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/agpl_requires_base_URL.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
Labels: size/sm, no-changelog, teleport-update

#51705 [v17] Add database User Agent to session start usage event
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/audit_test.go
  lib/usagereporter/teleport/types.go
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/sm, no-changelog

#51771 [v17] Always create debug socket and expose health endpoints
  constants.go
  lib/service/diagnostic.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/srv/debug/handlers.go
  lib/srv/debug/handlers_test.go
Labels: backport, size/md

#51735 [v17] Fix TELEPORT_ALLOW_NO_SECOND_FACTOR
  lib/auth/init.go
  lib/modules/modules.go
Labels: backport, size/sm, no-changelog

#51773 [v17] chore: Bump github.com/gravitational/trace to v1.4.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#51783 [v17] Add kubernetes enrichment option with pyroscope
  lib/service/pyroscope.go
  lib/service/pyroscope_test.go
Labels: backport, size/md, no-changelog

#51736 docs: adding redirects for broken links
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51718 [v17] Fix misaligned command usage for 'help' commands of Teleport binaries
  lib/utils/cli.go
  lib/utils/cli_test.go
Labels: backport, size/sm, no-changelog

#51759 [teleport-update] Warn instead of erroring when disabling the deprecated updater
  lib/service/service.go
Labels: size/sm, no-changelog

#51787 chore: Bump AWS modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#51719 [v16] Fix misaligned command usage for 'help' commands of Teleport binaries
  lib/utils/cli.go
  lib/utils/cli_test.go
Labels: backport, size/sm, no-changelog

#51742 [v16] Deflake TestStaticHostUserHandler (#51578)
  lib/srv/statichostuser_test.go
Labels: backport, size/sm, no-changelog

#51777 [v15] docs: remove sudo tctl users reference in cloud install docs
  docs/pages/includes/cloud/install-linux-cloud.mdx
Labels: documentation, backport, size/sm, no-changelog

#51741 [v17] Deflake TestStaticHostUserHandler (#51578)
  lib/srv/statichostuser_test.go
Labels: backport, size/sm, no-changelog

#51776 [v16] docs: remove sudo tctl users reference in cloud install docs
  docs/pages/includes/cloud/install-linux-cloud.mdx
Labels: documentation, backport, size/sm, no-changelog

#51772 [v17] docs: remove sudo tctl users reference in cloud install docs
  docs/pages/includes/cloud/install-linux-cloud.mdx
Labels: documentation, backport, size/sm, no-changelog

#51790 chore: Bump gcloud modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#51423 GitHub proxy: web apis for enrolment
  api/types/integration_github.go
  api/types/integration_github_test.go
  api/types/server.go
  lib/auth/integration/credentials/credentials.go
  lib/auth/integration/integrationv1/credentials.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/apiserver.go
  lib/web/git_servers.go
  lib/web/git_servers_test.go
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/ca.go
  lib/web/ui/ca_test.go
  lib/web/ui/git_server.go
  lib/web/ui/git_server_test.go
  lib/web/ui/integration.go
Labels: size/lg, no-changelog, backport/branch/v17, github

#51315 In-Product Redirects for updated docs
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51808 [v17] Upgrade Vale in the prose check workflow
  .github/workflows/doc-tests.yaml
Labels: backport, size/sm, no-changelog

#51801 Update Application CORS policy documentation
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
Labels: documentation, backport-required, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51533 [v17] Adds account list to IC plugin settings
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
Labels: backport, size/sm, no-changelog, aws-iam-identity-center

#51765 Update WorkloadIdentity guides for new config resource
  docs/pages/enroll-resources/workload-identity/aws-oidc-federation.mdx
  docs/pages/enroll-resources/workload-identity/aws-roles-anywhere.mdx
  docs/pages/enroll-resources/workload-identity/azure-federated-credentials.mdx
  docs/pages/enroll-resources/workload-identity/gcp-workload-identity-federation-jwt.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v17

#51798 kube: prepare for k8s v1.32.0 deps
  lib/kube/proxy/resource_deletecollection.go
  lib/kube/proxy/testing/kube_server/clusterrole.go
  lib/kube/proxy/testing/kube_server/crd.go
  lib/kube/proxy/testing/kube_server/pods.go
  lib/kube/proxy/testing/kube_server/secrets.go
Labels: kubernetes-access, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51791 chore: Bump k8s modules
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm, no-changelog

#51608 Make sure we don't break the role editor for some preset roles, add support for GH organizations
  Makefile
  build.assets/dump-preset-roles/main.go
  gen/preset-roles.json
  lib/services/presets_test.go
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#51803 Fix autoupdate rollout controller metrics
  lib/autoupdate/rollout/metrics.go
Labels: size/sm, no-changelog

#51762 [buddy] fix superfluous response call for WS request
  lib/web/apiserver.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51815 kube-agent-updater pre-release builds trust the staging repo + insecure validator private repo fix
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/constants.go
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  integrations/kube-agent-updater/pkg/img/insecure.go
Labels: size/sm

#51631 Initial docs for Azure integration
  docs/pages/admin-guides/teleport-policy/crown-jewels.mdx
  docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/azure-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/entra-id.mdx
  docs/pages/admin-guides/teleport-policy/integrations/gitlab.mdx
  docs/pages/admin-guides/teleport-policy/integrations/ssh-keys-scan.mdx
  docs/pages/admin-guides/teleport-policy/teleport-policy.mdx
Labels: documentation, size/md, no-changelog

#51809 Rust: update rand to 0.9.0
  Cargo.lock
  lib/srv/desktop/rdp/rdpclient/Cargo.toml
  lib/srv/desktop/rdp/rdpclient/src/client.rs
Labels: rdp, desktop-access, size/sm, no-changelog

#51618 Fix Admin MFA required check
  api/mfa/ceremony.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51702 Integration Status endpoint: include number of open UserTasks
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/integration.go
Labels: size/md, no-changelog, backport/branch/v17

#51468 initial transition of ssh enforcement logic to use sshca.Identity & removal of ssh certs from most enforcement logic
  api/types/authority.go
  lib/agentless/agentless.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/test/suite.go
  lib/auth/tls_test.go
  lib/authz/permissions.go
  lib/benchmark/db/db.go
  lib/client/cluster_client.go
  lib/client/interfaces.go
  lib/client/local_proxy_middleware.go
  lib/client/profile.go
  lib/devicetrust/authz/authz.go
  lib/devicetrust/authz/authz_test.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/srv_test.go
  lib/services/access_checker.go
  lib/services/access_request.go
  lib/services/authority.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/git/forward.go
  lib/srv/mock.go
  lib/srv/regular/proxy.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/srv/session_control_test.go
  lib/sshca/encoding_helpers.go
  lib/sshca/identity.go
  lib/sshca/identity_test.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/web/files.go
  lib/web/sessions.go
  lib/web/terminal.go
  tool/tsh/common/app.go
  tool/tsh/common/db.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
  tool/tsh/common/vnet_client_application.go
Labels: tsh, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51793 [teleport-update] Adjust non-critical SELinux contexts
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/installer.go
Labels: size/sm, no-changelog

#51833 Update grpc/stats/opentelemetry exclude
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm, no-changelog

#51806 [v15] Import the Mattermost bot logo as a module
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
Labels: documentation, backport, size/sm, no-changelog

#51804 [v17] Import the Mattermost bot logo as a module
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-mattermost.mdx
Labels: documentation, backport, size/sm, no-changelog

#51795 [v17] docs: adding redirects for broken links
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#51839 kube: prevent init failure when proxy listener addr host is unspecified
  lib/kube/grpc/utils.go
  lib/kube/grpc/utils_test.go
Labels: kubernetes-access, size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51755 [web] include git servers as option in filters
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/teleport/src/Navigation/ResourcesSection.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#51811 [v16] Update CORS policy documentation (#51801)
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm, no-changelog

#51810 [v17] Update CORS policy documentation (#51801)
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
Labels: documentation, backport, size/sm, no-changelog

#51394 Fix Per-session MFA for leaf apps
  integration/helpers/web.go
  integration/web/web_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/desktop.go
  lib/web/mfa.go
  tool/teleport/testenv/helpers.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_test.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/tsh_test.go
  web/packages/teleport/src/services/auth/auth.ts
Labels: ui, size/sm, backport/branch/v16, backport/branch/v17

#51850 Fix issue applying the --listen-ip flag
  lib/config/configuration.go
Labels: size/sm, no-changelog

#51672 Web: define discover resource guide ids and add discover user preference field
  api/gen/proto/go/userpreferences/v1/discover_resource_preferences.pb.go
  api/gen/proto/go/userpreferences/v1/userpreferences.pb.go
  api/proto/teleport/userpreferences/v1/discover_resource_preferences.proto
  api/proto/teleport/userpreferences/v1/userpreferences.proto
  gen/proto/ts/teleport/userpreferences/v1/discover_resource_preferences_pb.ts
  gen/proto/ts/teleport/userpreferences/v1/userpreferences_pb.ts
  lib/services/local/userpreferences_test.go
  lib/web/userpreferences.go
  web/packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
  web/packages/teleport/src/Discover/SelectResource/SelectResource.tsx
  web/packages/teleport/src/Discover/SelectResource/Tile.tsx
  web/packages/teleport/src/Discover/SelectResource/resources/databases.tsx
  web/packages/teleport/src/Discover/SelectResource/resources/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/resources/resourcesE.tsx
  web/packages/teleport/src/Discover/SelectResource/utils/checkAccess.ts
  web/packages/teleport/src/Discover/SelectResource/utils/filters.ts
  web/packages/teleport/src/Discover/SelectResource/utils/sort.ts
  web/packages/teleport/src/services/userPreferences/discoverPreference.ts
  web/packages/teleport/src/services/userPreferences/userPreferences.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#51721 [v17] docs: Add NetIQ documentation
  docs/pages/admin-guides/teleport-policy/integrations/netiq.mdx
Labels: documentation, backport, size/md, no-changelog

#51831 Making access graph description & verification steps an include file
  docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/azure-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/entra-id.mdx
  docs/pages/admin-guides/teleport-policy/integrations/gitlab.mdx
  docs/pages/admin-guides/teleport-policy/integrations/ssh-keys-scan.mdx
  docs/pages/includes/policy/access-graph.mdx
Labels: documentation, size/sm, no-changelog

#51574 [docs] Update GitHub Proxy Image with new logo
  docs/img/management/how-it-works-github-proxy.svg
Labels: documentation, size/sm, no-changelog

#51817 `tbot` Helm Chart: Add ability to configure securityContext
  docs/pages/includes/helm-reference/zz_generated.tbot.mdx
  examples/chart/tbot/.lint/full.yaml
  examples/chart/tbot/templates/deployment.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/values.yaml
Labels: documentation, helm, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51848 [v17] [web] include git servers as option in filters
  web/packages/shared/components/UnifiedResources/FilterPanel.tsx
  web/packages/teleport/src/Navigation/ResourcesSection.tsx
Labels: ui, backport, size/sm, no-changelog

#51829 [v17] [buddy] fix superfluous response call for WS request
  lib/web/apiserver.go
Labels: backport, size/sm, no-changelog

#51834 chore: Bump Go to v1.23.6
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: size/sm

#51836 [v16] chore: Bump Go to v1.22.12
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#51837 [v15] chore: Bump Go to v1.22.12
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#51866 [v15][buddy] fix superfluous response call for WS request
  lib/web/apiserver.go
Labels: backport, size/sm, no-changelog

#51835 [v17] chore: Bump Go to v1.23.6
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#51846 [v17] transition ssh enforcement to sshca.Identity
  api/types/authority.go
  lib/agentless/agentless.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/test/suite.go
  lib/auth/tls_test.go
  lib/authz/permissions.go
  lib/benchmark/db/db.go
  lib/client/cluster_client.go
  lib/client/interfaces.go
  lib/client/local_proxy_middleware.go
  lib/client/profile.go
  lib/devicetrust/authz/authz.go
  lib/devicetrust/authz/authz_test.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/srv_test.go
  lib/services/access_checker.go
  lib/services/access_request.go
  lib/services/authority.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/git/forward.go
  lib/srv/mock.go
  lib/srv/regular/proxy.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/srv/session_control_test.go
  lib/sshca/encoding_helpers.go
  lib/sshca/identity.go
  lib/sshca/identity_test.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/web/sessions.go
  lib/web/terminal.go
  tool/tsh/common/app.go
  tool/tsh/common/db.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
  tool/tsh/common/vnet_client_application.go
Labels: tsh, backport, size/sm, no-changelog

#51844 [v15] transition ssh enforcement to sshca.Identity
  api/types/authority.go
  lib/agentless/agentless.go
  lib/auth/access_request_test.go
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/test/suite.go
  lib/auth/tls_test.go
  lib/authz/permissions.go
  lib/benchmark/db/db.go
  lib/client/client.go
  lib/client/cluster_client.go
  lib/client/interfaces.go
  lib/client/local_proxy_middleware.go
  lib/client/profile.go
  lib/devicetrust/authz/authz.go
  lib/devicetrust/authz/authz_test.go
  lib/reversetunnel/srv.go
  lib/reversetunnel/srv_test.go
  lib/services/access_checker.go
  lib/services/access_request.go
  lib/services/authority.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/authhandlers.go
  lib/srv/authhandlers_test.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/mock.go
  lib/srv/regular/proxy.go
  lib/srv/sess.go
  lib/srv/sess_test.go
  lib/srv/session_control.go
  lib/srv/session_control_test.go
  lib/sshca/encoding_helpers.go
  lib/sshca/identity.go
  lib/sshca/identity_test.go
  lib/teleterm/clusters/cluster.go
  lib/teleterm/clusters/cluster_access_requests.go
  lib/teleterm/clusters/cluster_apps.go
  lib/teleterm/clusters/cluster_databases.go
  lib/teleterm/clusters/cluster_kubes.go
  lib/web/sessions.go
  lib/web/terminal.go
  tool/tsh/common/app.go
  tool/tsh/common/db.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, backport, size/sm, no-changelog

#51821 [v17] Respect role max duration when request does not set it
  lib/services/access_request.go
  lib/services/access_request_test.go
Labels: backport, size/sm

#51800 Fetch RequiredApps when resolving app with fqdnHint only
  lib/web/apiserver_test.go
  lib/web/apps.go
Labels: backport-required, size/sm, backport/branch/v16, backport/branch/v17

#51865 [v16][buddy] fix superfluous response call for WS request
  lib/web/apiserver.go
Labels: backport, size/sm, no-changelog

#51863 [v17] Integration Status endpoint: include pending UserTasks
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/integration.go
Labels: backport, size/md, no-changelog

#51613 [teleport-update] Add proper healthcheck for agents
  lib/autoupdate/agent/process.go
  lib/autoupdate/agent/process_test.go
  lib/autoupdate/agent/updater.go
  lib/client/debug/debug.go
  lib/client/debug/debug_test.go
  lib/service/state.go
Labels: size/md, no-changelog, teleport-update

#51642 Add PluginOktaSyncSettings.UserSyncSource
  api/proto/teleport/legacy/types/types.proto
  api/types/okta.go
  api/types/okta_test.go
  api/types/plugin.go
  api/types/types.pb.go
Labels: size/sm, size/md, no-changelog, backport/branch/v17

#51629 [vnet] remote OS config provider
  gen/proto/go/teleport/lib/vnet/v1/client_application_service.pb.go
  gen/proto/go/teleport/lib/vnet/v1/client_application_service_grpc.pb.go
  lib/vnet/admin_process_windows.go
  lib/vnet/client_application_service.go
  lib/vnet/client_application_service_client.go
  lib/vnet/clusterconfigcache.go
  lib/vnet/ipbits.go
  lib/vnet/local_app_provider.go
  lib/vnet/osconfig.go
  lib/vnet/profile_osconfig_provider_darwin.go
  lib/vnet/remote_osconfig_provider.go
  lib/vnet/remote_osconfig_provider_test.go
  lib/vnet/unsupported_os.go
  lib/vnet/user_process_darwin.go
  lib/vnet/vnet_test.go
  proto/teleport/lib/vnet/v1/client_application_service.proto
Labels: size/md, no-changelog, vnet, backport/branch/v17

#51888 [v16] Always create debug socket and expose health endpoints
  constants.go
  lib/service/diagnostic.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/srv/debug/handlers.go
  lib/srv/debug/handlers_test.go
Labels: backport, size/md

#51886 docs: redirect for access-request-plugins
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51853 [v17] Fix Per-session MFA for leaf apps
  integration/helpers/web.go
  integration/web/web_test.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  lib/web/desktop.go
  lib/web/mfa.go
  tool/teleport/testenv/helpers.go
  tool/teleport/testenv/test_server.go
  tool/tsh/common/app_aws_test.go
  tool/tsh/common/app_test.go
  tool/tsh/common/proxy_test.go
  tool/tsh/common/tsh_test.go
  web/packages/teleport/src/services/auth/auth.ts
Labels: ui, tsh, backport, desktop-access, size/md

#51890 [v15] Always create debug socket and expose health endpoints
  constants.go
  lib/service/diagnostic.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/state.go
  lib/srv/debug/handlers.go
  lib/srv/debug/handlers_test.go
Labels: backport, size/md

#51885 Don't emit warning log for reusing reusable MFA
  lib/auth/webauthn/login.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51859 [Web] Update `makeCluster` to handle an empty response
  web/packages/teleport/src/services/clusters/makeCluster.ts
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51889 [v17] Fix incorrect docs URLs
  lib/tbot/config/migrate_test.go
  lib/versioncontrol/github/test_page_1.json
  lib/versioncontrol/github/test_page_2.json
  lib/versioncontrol/github/test_page_3.json
  web/packages/teleport/src/AuthConnectors/AuthConnectorEditor/AuthConnectorEditorContent.tsx
Labels: ui, backport, machine-id, size/sm, no-changelog

#51891 [v16] Fix incorrect docs URLs
  README.md
  lib/tbot/config/migrate_test.go
  lib/versioncontrol/github/test_page_1.json
  lib/versioncontrol/github/test_page_2.json
  lib/versioncontrol/github/test_page_3.json
  lib/web/scripts/desktop/configure-ad.ps1
Labels: backport, machine-id, size/sm, no-changelog

#51732 Default BaseURL only for community / enterprise editions
  integration/autoupdate/tools/updater/modules.go
  integration/autoupdate/tools/updater_test.go
  lib/autoupdate/tools/helper.go
  lib/autoupdate/tools/updater.go
  lib/autoupdate/tools/utils.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51689 [vnet] run os config on windows
  lib/vnet/admin_process_windows.go
Labels: size/sm, no-changelog, vnet, backport/branch/v17

#51690 [vnet] windows ip and route configuration
  lib/vnet/admin_process_windows.go
  lib/vnet/osconfig.go
  lib/vnet/osconfig_darwin.go
  lib/vnet/osconfig_windows.go
  lib/vnet/unsupported_os.go
Labels: size/md, no-changelog, vnet, backport/branch/v17

#46891 UX improvements for `tctl` with Admin MFA
  tool/tctl/common/admin_action_test.go
  tool/tctl/common/edit_command.go
  tool/tctl/common/resource_command.go
Labels: tctl, size/sm

#51576 [teleport-update] Allow teleport-update uninstall to succeed with non-packaged installs
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/installer_test.go
  lib/autoupdate/agent/updater.go
Labels: size/sm, no-changelog, teleport-update

#51734 [teleport-update] use new updater to reload and verify Teleport
  lib/autoupdate/agent/testdata/TestUpdater_Install/setup_fails_already_installed.golden
  lib/autoupdate/agent/testdata/TestUpdater_Update/reload_fails.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: size/sm, no-changelog

#51882 Add engines.node to package.json
  build.assets/versions.mk
  package.json
Labels: size/sm, no-changelog

#51646 Submit aggregated issuance of distinct SPIFFE IDs
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  proto/prehog/v1/teleport.proto
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51895 Applying include file to the crown jewels page
  docs/pages/admin-guides/teleport-policy/crown-jewels.mdx
Labels: documentation, size/sm, no-changelog

#51894 [v17] Initial docs for Azure integration
  docs/pages/admin-guides/teleport-policy/crown-jewels.mdx
  docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/azure-sync.mdx
  docs/pages/admin-guides/teleport-policy/integrations/entra-id.mdx
  docs/pages/admin-guides/teleport-policy/integrations/gitlab.mdx
  docs/pages/admin-guides/teleport-policy/integrations/ssh-keys-scan.mdx
  docs/pages/admin-guides/teleport-policy/teleport-policy.mdx
  docs/pages/includes/policy/access-graph.mdx
Labels: documentation, backport, size/md, no-changelog

#47436 RFD0185: Kubernetes Access without Certificate-based Routing
  rfd/0185-k8s-access-non-cert-routing.md
Labels: rfd, size/md, no-changelog

#51910 [v16] `tbot` Helm Chart: Add ability to configure securityContext (#51817)
  docs/pages/includes/helm-reference/zz_generated.tbot.mdx
  examples/chart/tbot/.lint/full.yaml
  examples/chart/tbot/templates/deployment.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/values.yaml
Labels: documentation, helm, backport, size/sm

#51909 [v15] `tbot` Helm Chart: Add ability to configure securityContext (#51817)
  docs/pages/includes/helm-reference/zz_generated.tbot.mdx
  examples/chart/tbot/.lint/full.yaml
  examples/chart/tbot/templates/deployment.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/values.yaml
Labels: documentation, helm, backport, size/sm

#51908 [v17] [17.2.3] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#51532 docs: updating 'Teleport Enterprise (Managed)' to Cloud
  docs/pages/admin-guides/infrastructure-as-code/terraform-starter/enroll-resources.mdx
  docs/pages/includes/install-windows.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51899 [v17] docs: redirect for access-request-plugins
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#51913 [v17] Submit aggregated issuance of distinct SPIFFE IDs (#51646)
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  proto/prehog/v1/teleport.proto
Labels: backport, size/md, no-changelog

#51912 [v16] Submit aggregated issuance of distinct SPIFFE IDs (#51646)
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  proto/prehog/v1/teleport.proto
Labels: backport, size/md, no-changelog

#51898 [v17] [Web] Update `makeCluster` to handle an empty response
  web/packages/teleport/src/services/clusters/makeCluster.ts
Labels: ui, backport, size/sm, no-changelog

#51738 [vnet] get upstream nameservers on Windows
  go.mod
  go.sum
  lib/vnet/dns/osnameservers.go
  lib/vnet/dns/osnameservers_darwin.go
  lib/vnet/dns/osnameservers_other.go
  lib/vnet/dns/osnameservers_windows.go
Labels: size/sm, no-changelog, vnet, backport/branch/v17

#51828 [v16] Respect role max duration when request does not set it
  lib/services/access_request.go
  lib/services/access_request_test.go
Labels: backport, size/sm

#51897 [v17][vnet] remote OS config provider
  gen/proto/go/teleport/lib/vnet/v1/client_application_service.pb.go
  gen/proto/go/teleport/lib/vnet/v1/client_application_service_grpc.pb.go
  lib/vnet/admin_process_windows.go
  lib/vnet/client_application_service.go
  lib/vnet/client_application_service_client.go
  lib/vnet/clusterconfigcache.go
  lib/vnet/ipbits.go
  lib/vnet/local_app_provider.go
  lib/vnet/osconfig.go
  lib/vnet/profile_osconfig_provider_darwin.go
  lib/vnet/remote_osconfig_provider.go
  lib/vnet/remote_osconfig_provider_test.go
  lib/vnet/unsupported_os.go
  lib/vnet/user_process_darwin.go
  lib/vnet/vnet_test.go
  proto/teleport/lib/vnet/v1/client_application_service.proto
Labels: backport, size/md, no-changelog

#51849 Fix createAppSession call from web
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/apps/apps.test.ts
Labels: ui, size/sm, backport/branch/v17

#51739 [vnet] configure split DNS for VNet on Windows
  lib/vnet/client_application_service_client.go
  lib/vnet/osconfig_windows.go
  lib/vnet/remote_app_provider.go
Labels: size/md, no-changelog, vnet, backport/branch/v17

#51685 [v16] Add support for storing RDP licenses from Windows Desktops
  .github/workflows/dependency-review.yaml
  Cargo.lock
  Cargo.toml
  api/types/desktop.go
  lib/auth/storage/storage.go
  lib/auth/storage/storage_test.go
  lib/service/desktop.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/license.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, backport, desktop-access, size/md

#51684 [v17] Add support for storing RDP licenses from Windows Desktops
  .github/workflows/dependency-review.yaml
  Cargo.lock
  Cargo.toml
  api/types/desktop.go
  lib/auth/storage/storage.go
  lib/auth/storage/storage_test.go
  lib/service/desktop.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/src/client.rs
  lib/srv/desktop/rdp/rdpclient/src/lib.rs
  lib/srv/desktop/rdp/rdpclient/src/license.rs
  lib/srv/desktop/windows_server.go
Labels: rdp, backport, desktop-access, size/md

#51927 [Web] Fix malformed icons
  web/packages/design/src/Icon/Icons/AddCircle.tsx
  web/packages/design/src/Icon/Icons/Devices.tsx
  web/packages/design/src/Icon/Icons/LineSegment.tsx
  web/packages/design/src/Icon/Icons/Ruler.tsx
  web/packages/design/src/Icon/Icons/UserIdBadge.tsx
  web/packages/design/src/Icon/assets/AddCircle.svg
  web/packages/design/src/Icon/assets/Devices.svg
  web/packages/design/src/Icon/assets/LineSegment.svg
  web/packages/design/src/Icon/assets/Ruler.svg
  web/packages/design/src/Icon/assets/UserIdBadge.svg
Labels: ui, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51900 [v17] [vnet] run os config on windows
  lib/vnet/admin_process_windows.go
Labels: backport, size/sm, no-changelog

#51729 SAML: Validate SSO URL matches the one in entity descriptor if both set
  lib/services/saml.go
  lib/services/saml_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#51905 Docs: Adds Okta API key requirements for SCIM-only Okta
  docs/pages/enroll-resources/application-access/okta/scim-only.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51539 Web: Add github integration tile and github related types and endpoints
  web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.test.tsx
  web/packages/teleport/src/Discover/Shared/AwsAccount/AwsAccount.tsx
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/Integrations/EditAwsOidcIntegrationDialog.test.tsx
  web/packages/teleport/src/Integrations/EditAwsOidcIntegrationDialog.tsx
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/FinishDialog.tsx
  web/packages/teleport/src/Integrations/Enroll/AwsOidc/useAwsOidcIntegration.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationEnroll.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles/IntegrationTiles.test.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles/IntegrationTiles.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles/integrations.ts
  web/packages/teleport/src/Integrations/Enroll/index.ts
  web/packages/teleport/src/Integrations/IntegrationList.tsx
  web/packages/teleport/src/Integrations/Integrations.tsx
  web/packages/teleport/src/Integrations/Operations/IntegrationOperations.tsx
  web/packages/teleport/src/Integrations/Operations/useIntegrationOperation.ts
  web/packages/teleport/src/Integrations/fixtures.ts
  web/packages/teleport/src/Integrations/status/AwsOidc/AwsOidcHeader.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/useAwsOidcStatus.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/integrations/integrations.test.ts
  web/packages/teleport/src/services/integrations/integrations.ts
  web/packages/teleport/src/services/integrations/types.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleport/src/services/resources/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#51758 Use new autoupdate APIs in discovery service
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  lib/automaticupgrades/version/proxy.go
  lib/kube/utils/utils.go
  lib/kube/utils/utils_test.go
  lib/srv/discovery/kube_integration_watcher.go
  lib/web/apiserver.go
  lib/web/autoupdate_common.go
  lib/web/autoupdate_rfd109.go
  lib/web/integrations_awsoidc.go
  lib/web/join_tokens.go
Labels: kubernetes-access, size/sm, discovery

#51919 [buddy] gate RBAC creation in the tbot Helm chart behind a dedicated value
  docs/pages/includes/helm-reference/zz_generated.tbot.mdx
  examples/chart/tbot/templates/role.yaml
  examples/chart/tbot/templates/rolebinding.yaml
  examples/chart/tbot/tests/role_test.yaml
  examples/chart/tbot/tests/rolebinding_test.yaml
  examples/chart/tbot/values.yaml
Labels: documentation, helm, size/sm

#51287 Prevent creation of invalid App for AWS OIDC Integration
  integration/integrations/integration_test.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51884 [v16] Fetch RequiredApps when resolving app with fqdnHint only (#51800)
  lib/web/apiserver_test.go
  lib/web/apps.go
Labels: backport, size/sm, no-changelog

#51928 [v17] Fix createAppSession call from web
  web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx
  web/packages/teleport/src/AppLauncher/AppLauncher.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/apps/apps.test.ts
Labels: ui, backport, size/sm

#51873 [v17] Fetch RequiredApps when resolving app with fqdnHint only
  lib/web/apiserver_test.go
  lib/web/apps.go
Labels: backport, size/sm

#51950 Fix comment on `make update-tag`
  Makefile
Labels: size/sm, no-changelog

#51880 Add env var to disable Role Visualizer
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/config.ts
Labels: ui, size/sm, no-changelog

#51789 Add access requests context
  web/packages/shared/components/AccessRequests/Shared/Shared.tsx
  web/packages/shared/hooks/useAsync.ts
  web/packages/teleterm/src/ui/AccessRequests/AccessRequestsContext.tsx
  web/packages/teleterm/src/ui/AccessRequests/index.ts
  web/packages/teleterm/src/ui/DocumentAccessRequests/DocumentAccessRequests.story.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/DocumentAccessRequests.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/RequestList/RequestList.test.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/RequestList/RequestList.tsx
  web/packages/teleterm/src/ui/DocumentAccessRequests/useAccessRequests.tsx
  web/packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
  web/packages/teleterm/src/ui/LayoutManager.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.story.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx
  web/packages/teleterm/src/ui/TabHost/TabHost.tsx
  web/packages/teleterm/src/ui/TopBar/AdditionalActions.tsx
  web/packages/teleterm/src/ui/TopBar/TopBar.tsx
  web/packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.tsx
  web/packages/teleterm/src/ui/services/immutableStore/immutableStore.test.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
  web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#51944 improve dynamoevents cursor logs
  integrations/event-handler/legacy_events_watcher.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#51947 [v16] Prevent creation of invalid App for AWS OIDC Integration
  integration/integrations/integration_test.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
Labels: backport, size/sm, no-changelog

#51946 [v17] Prevent creation of invalid App for AWS OIDC Integration
  integration/integrations/integration_test.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
Labels: backport, size/sm, no-changelog

#51740 Fix MFA always required for file transfers
  web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx
  web/packages/teleport/src/lib/useMfa.test.tsx
  web/packages/teleport/src/lib/useMfa.ts
Labels: ui, size/sm, backport/branch/v17

#51953 [v17] GitHub proxy: web apis for enrolment
  api/types/integration_github.go
  api/types/integration_github_test.go
  api/types/server.go
  lib/auth/integration/credentials/credentials.go
  lib/auth/integration/integrationv1/credentials.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/apiserver.go
  lib/web/git_servers.go
  lib/web/git_servers_test.go
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/ca.go
  lib/web/ui/ca_test.go
  lib/web/ui/git_server.go
  lib/web/ui/git_server_test.go
  lib/web/ui/integration.go
Labels: backport, size/lg, no-changelog

#51948 [v15] Prevent creation of invalid App for AWS OIDC Integration
  integration/integrations/integration_test.go
  lib/auth/integration/integrationv1/service.go
  lib/auth/integration/integrationv1/service_test.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
Labels: backport, size/sm, no-changelog

#51957 [v17] improve dynamoevents cursor logs
  integrations/event-handler/legacy_events_watcher.go
  lib/events/dynamoevents/dynamoevents.go
  lib/events/dynamoevents/dynamoevents_test.go
Labels: audit-log, backport, size/sm, no-changelog

#51724 [v17] Add Role Diff Visual to Role editor
  api/client/webclient/webconfig.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/Shared.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/YamlEditor.tsx
  web/packages/teleport/src/Roles/Roles.test.tsx
  web/packages/teleport/src/Roles/Roles.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/storageService/storageService.ts
  web/packages/teleport/src/services/storageService/types.ts
Labels: ui, backport, size/sm, no-changelog

#51901 [v17][vnet] windows ip and route configuration
  lib/vnet/admin_process_windows.go
  lib/vnet/osconfig.go
  lib/vnet/osconfig_darwin.go
  lib/vnet/osconfig_windows.go
  lib/vnet/unsupported_os.go
Labels: size/md, no-changelog

#51952 docs: Document device trust's high-level architecture
  docs/img/architecture/device-trust-authentication.png
  docs/img/architecture/device-trust-enrollment-macos.png
  docs/pages/reference/architecture/device-trust.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51961 Update upcoming-releases.mdx
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#51446 OCI join method - Add server auth ceremony
  api/types/provisioning.go
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/join/oracle/oracle.go
  lib/auth/join/oracle/oracle_test.go
  lib/auth/join_oracle.go
  lib/auth/join_oracle_test.go
Labels: size/lg

#51090 [v16] Add client tools auto-update documentation
  docs/config.json
  docs/cspell.json
  docs/pages/upgrading/client-tools-autoupdate.mdx
  docs/pages/upgrading/upgrading.mdx
Labels: documentation, backport, size/md, no-changelog

#51633 [teleport-update] Read proxy from teleport.yaml to improve UX
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
Labels: size/md, no-changelog, teleport-update

#51925 [v17][vnet] get upstream nameservers on Windows
  go.mod
  go.sum
  lib/vnet/dns/osnameservers.go
  lib/vnet/dns/osnameservers_darwin.go
  lib/vnet/dns/osnameservers_other.go
  lib/vnet/dns/osnameservers_windows.go
Labels: size/sm, no-changelog

#51033 docs: include debug service in table of services
  docs/pages/reference/config.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#51966 Fix upcoming releases page
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#51930 [v17][vnet] configure split DNS for VNet on Windows
  lib/vnet/client_application_service_client.go
  lib/vnet/osconfig_windows.go
  lib/vnet/remote_app_provider.go
Labels: size/md, no-changelog

#51965 [v16] docs: Document device trust's high-level architecture
  docs/img/architecture/device-trust-authentication.png
  docs/img/architecture/device-trust-enrollment-macos.png
  docs/pages/reference/architecture/device-trust.mdx
Labels: documentation, backport, size/sm, no-changelog

#51974 [v16] docs: include debug service in table of services
  docs/pages/reference/config.mdx
Labels: documentation, backport, size/sm, no-changelog

#51977 [v17] Fix link in the Upcoming Releases page
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#51939 [v17] [Web] Fix malformed icons
  web/packages/design/src/Icon/Icons/AddCircle.tsx
  web/packages/design/src/Icon/Icons/Devices.tsx
  web/packages/design/src/Icon/Icons/LineSegment.tsx
  web/packages/design/src/Icon/Icons/Ruler.tsx
  web/packages/design/src/Icon/Icons/UserIdBadge.tsx
  web/packages/design/src/Icon/assets/AddCircle.svg
  web/packages/design/src/Icon/assets/Devices.svg
  web/packages/design/src/Icon/assets/LineSegment.svg
  web/packages/design/src/Icon/assets/Ruler.svg
  web/packages/design/src/Icon/assets/UserIdBadge.svg
Labels: ui, backport, size/sm, no-changelog

#51973 [teleport-update] Require --force when uninstalling Teleport completely
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: size/sm, no-changelog

#51814 Fetch relevant regions for agents endpoint
  lib/utils/set.go
  lib/utils/set_test.go
  lib/web/integrations_awsoidc.go
  lib/web/integrations_awsoidc_test.go
Labels: size/md, no-changelog

#51962 [v17] Fix MFA always required for file transfers
  web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx
  web/packages/teleport/src/lib/useMfa.test.tsx
  web/packages/teleport/src/lib/useMfa.ts
Labels: ui, backport, size/sm

#51904 Add bootstrap support for AutoUpdateConfig/AutoUpdateVersion resources
  lib/auth/autoupdate/autoupdatev1/service.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/services/local/autoupdate.go
  lib/services/local/resource.go
  lib/services/resource.go
Labels: size/md, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17
