Repository gravitational/teleport, pull requests merged in 2025-09, with the labels that each got.

#58494 [v18] MWI: Allow configuration of default namespace for `kubernetes/v2` service
  lib/tbot/services/k8s/argocd_output.go
  lib/tbot/services/k8s/output_v2.go
  lib/tbot/services/k8s/output_v2_config.go
  lib/tbot/services/k8s/output_v2_config_test.go
  lib/tbot/services/k8s/output_v2_test.go
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/absolute_path/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/exec_plugin_disabled/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/relative_path/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2Output_YAML/full.golden
Labels: backport, machine-id, size/sm

#58478 [v17] Allow `"*"` in `kubernetes_users`
  docs/pages/enroll-resources/kubernetes-access/controls.mdx
  lib/kube/proxy/ephemeral_containers.go
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/forwarder_test.go
  lib/kube/proxy/resource_deletecollection.go
Labels: documentation, kubernetes-access, backport, size/sm

#58479 docs: update role demo
  docs/pages/zero-trust-access/rbac-get-started/role-demo.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58484 [v17] Add `useResourceLock` hook
  lib/auth/auth_with_roles.go
  lib/web/apiserver.go
  lib/web/apiserver_test.go
  web/packages/teleport/src/LocksV2/Locks/Locks.test.tsx
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/lib/locks/useResourceLock.test.tsx
  web/packages/teleport/src/lib/locks/useResourceLock.ts
  web/packages/teleport/src/services/api/api.ts
  web/packages/teleport/src/services/joinToken/joinToken.ts
  web/packages/teleport/src/services/locks/locks.ts
  web/packages/teleport/src/services/locks/types.ts
  web/packages/teleport/src/services/resources/resource.ts
  web/packages/teleport/src/teleportContext.tsx
  web/packages/teleport/src/test/helpers/locks.ts
  web/packages/teleport/src/types.ts
Labels: ui, backport, size/lg, no-changelog

#58556 [v18] docs: update role demo
  docs/pages/zero-trust-access/rbac-get-started/role-demo.mdx
Labels: documentation, backport, size/sm, no-changelog

#58098 add `entra_id_groups_provider` field to oidc connector
  api/proto/teleport/legacy/types/types.proto
  api/types/oidc.go
  api/types/oidc_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-oidcconnectors.mdx
  docs/pages/reference/terraform-provider/data-sources/oidc_connector.mdx
  docs/pages/reference/terraform-provider/resources/oidc_connector.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_oidcconnectors.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_oidcconnectors.yaml
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, helm, size/md, backport/branch/v18

#58570 [v18] feat(web): Add general-use resource lock utilities
  web/packages/design/src/Button/Button.tsx
  web/packages/design/src/Button/buttons.story.tsx
  web/packages/design/src/Button/index.ts
  web/packages/teleport/src/lib/locks/ResourceLockAndUnlock.story.tsx
  web/packages/teleport/src/lib/locks/ResourceLockDialog.test.tsx
  web/packages/teleport/src/lib/locks/ResourceLockDialog.tsx
  web/packages/teleport/src/lib/locks/ResourceLockIndicator.story.tsx
  web/packages/teleport/src/lib/locks/ResourceLockIndicator.test.tsx
  web/packages/teleport/src/lib/locks/ResourceLockIndicator.tsx
  web/packages/teleport/src/lib/locks/ResourceUnlockDialog.test.tsx
  web/packages/teleport/src/lib/locks/ResourceUnlockDialog.tsx
  web/packages/teleport/src/lib/locks/useResourceLock.test.tsx
  web/packages/teleport/src/lib/locks/useResourceLock.ts
  web/packages/teleport/src/test/helpers/locks.ts
Labels: ui, backport, size/lg, no-changelog

#58578 fix: fix predicate `set` function
  lib/services/parser.go
  lib/services/parser_test.go
Labels: size/sm, no-changelog, backport/branch/v18

#58565 MWI: Fix panic in SSH multiplexer
  lib/tbot/services/ssh/multiplexer.go
Labels: machine-id, size/sm, backport/branch/v17, backport/branch/v18

#56848 [v18] mention saml idp rbac changes in resource reference page
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/sm, no-changelog

#58511 Remove outdated SSH language in the SSO guide
  docs/pages/zero-trust-access/sso/sso.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58445 [v17] Implement Compaction of Desktop Shared Directory Read/Write Events
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_compactor.go
  lib/srv/desktop/audit_compactor_test.go
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/md

#58378 [v18] Docs: Add Terraform guide for Access Lists
  docs/cspell.json
  docs/pages/identity-governance/access-lists/terraform.mdx
Labels: documentation, backport, size/md, no-changelog, hold-for-18.2

#58348 Hardcode the lowest supported Connect versions that support managed updates
  web/packages/teleterm/src/mainProcess/mainProcessClient.ts
  web/packages/teleterm/src/services/appUpdater/appUpdater.test.ts
  web/packages/teleterm/src/services/appUpdater/clientToolsUpdateProvider.ts
  web/packages/teleterm/src/services/appUpdater/errors.ts
  web/packages/teleterm/src/ui/AppUpdater/AppUpdaterContext.tsx
  web/packages/teleterm/src/ui/AppUpdater/DetailsView.tsx
  web/packages/teleterm/src/ui/AppUpdater/WidgetView.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58360 [v18] Create thumbnails & metadata for session recordings
  api/gen/proto/go/teleport/recordingmetadata/v1/recordingmetadata.pb.go
  api/proto/teleport/recordingmetadata/v1/recordingmetadata.proto
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/auth/grpcserver.go
  lib/auth/recordingmetadata/provider.go
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata.go
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata_test.go
  lib/auth/recordingmetadata/recordingmetadatav1/service.go
  lib/auth/recordingmetadata/recordingmetadatav1/service_test.go
  lib/auth/recordingmetadata/recordingmetadatav1/thumbnails.go
  lib/auth/recordingmetadata/recordingmetadatav1/thumbnails_test.go
  lib/auth/recordingmetadata/service.go
  lib/events/auditlog.go
  lib/events/stream.go
  lib/service/service.go
  lib/terminal/svg.go
  lib/terminal/testdata/TestTerminalStateToSVG/256Colors.golden
  lib/terminal/testdata/TestTerminalStateToSVG/AlternateScreen.golden
  lib/terminal/testdata/TestTerminalStateToSVG/AlternateScreenSwitch.golden
  lib/terminal/testdata/TestTerminalStateToSVG/BackgroundRects.golden
  lib/terminal/testdata/TestTerminalStateToSVG/BasicText.golden
  lib/terminal/testdata/TestTerminalStateToSVG/Colors.golden
  lib/terminal/testdata/TestTerminalStateToSVG/CombinedAttributes.golden
  lib/terminal/testdata/TestTerminalStateToSVG/ComplexBufferSwap.golden
  lib/terminal/testdata/TestTerminalStateToSVG/ComplexBufferSwapMain.golden
  lib/terminal/testdata/TestTerminalStateToSVG/CursorPosition.golden
  lib/terminal/testdata/TestTerminalStateToSVG/EmptyGlyphs.golden
  lib/terminal/testdata/TestTerminalStateToSVG/EmptyLines.golden
  lib/terminal/testdata/TestTerminalStateToSVG/ExtendedBackgroundColors.golden
  lib/terminal/testdata/TestTerminalStateToSVG/MultilineWithColors.golden
  lib/terminal/testdata/TestTerminalStateToSVG/RGBColors.golden
  lib/terminal/testdata/TestTerminalStateToSVG/ReverseVideo.golden
  lib/terminal/testdata/TestTerminalStateToSVG/SVGStructure.golden
  lib/terminal/testdata/TestTerminalStateToSVG/SpacedText.golden
  lib/terminal/testdata/TestTerminalStateToSVG/SpecialCharacters.golden
  lib/terminal/testdata/TestTerminalStateToSVG/TextAttributes.golden
  lib/web/recordingmetadata.go
Labels: audit-log, backport, size/lg, hold-for-18.2

#58524 docs: list tradeoffs of using FIPS builds
  docs/pages/zero-trust-access/compliance-frameworks/fedramp.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58580 Fix cache ListAllAccessListMembers spin loop
  lib/cache/access_list.go
  lib/cache/access_list_test.go
Labels: size/sm, backport/branch/v18

#58002 [v17] Update the Feature Matrix
  docs/pages/feature-matrix.mdx
Labels: documentation, backport, size/sm, no-changelog

#58620 [v17] docs: list tradeoffs of using FIPS builds
  docs/pages/zero-trust-access/compliance-frameworks/fedramp.mdx
Labels: documentation, backport, size/sm, no-changelog

#58323 Add ListAccessListsV2 to support sorting and searching
  api/client/accesslist/accesslist.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service.pb.go
  api/gen/proto/go/teleport/accesslist/v1/accesslist_service_grpc.pb.go
  api/proto/teleport/accesslist/v1/accesslist_service.proto
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.client.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.grpc-server.ts
  gen/proto/ts/teleport/accesslist/v1/accesslist_service_pb.ts
  lib/auth/authclient/api.go
  lib/cache/access_list.go
  lib/cache/access_list_test.go
  lib/services/access_list.go
  lib/services/access_list_test.go
  lib/services/local/access_list.go
Labels: size/md, no-changelog

#58412 [v18] Fix formatting of RBAC documentation link
  docs/pages/zero-trust-access/rbac-get-started/role-demo.mdx
Labels: documentation, backport, size/sm, no-changelog

#58625 Fix autoupdate package tests for SELinux on MacOS
  lib/autoupdate/agent/updater_test.go
Labels: size/sm, no-changelog

#58527 Component updates to support paginated AccessLists
  api/types/accesslist/member.go
  web/packages/design/src/DataTable/Table.tsx
  web/packages/design/src/DataTable/types.ts
  web/packages/shared/components/Controls/MultiselectMenu.tsx
  web/packages/teleport/src/generateResourcePath.ts
Labels: ui, size/sm, no-changelog

#58611 [v18] Cache fix panic due to missing clone call
  lib/cache/app.go
  lib/cache/database.go
  lib/cache/identitycenter.go
  lib/cache/user_login_state.go
Labels: backport, size/sm

#58614 [v18] Fix cache ListAllAccessListMembers spin loop
  lib/cache/access_list.go
  lib/cache/access_list_test.go
Labels: backport, size/sm

#58319 Add a "What's new" section to the homepage
  docs/pages/includes/homepage/version-highlights.mdx
  docs/pages/index.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58290 Fix TestParallelUpdate test on heavily loaded CI
  integration/autoupdate/tools/updater_test.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58635 Fixing unreliable RSA key length validation
  lib/auth/keystore/pkcs11.go
Labels: size/sm, no-changelog

#58351 [v17] Add docs for Teleport Connect managed updates
  docs/cspell.json
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/upgrading/client-tools-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#58604 [loadtest] switch etcd Helm to legacy images
  assets/loadtest/etcd/Makefile
  assets/loadtest/etcd/etcd-values.yaml
Labels: size/sm, no-changelog

#58202 [v18] GCP AlloyDB support
  api/proto/teleport/legacy/types/types.proto
  api/types/database.go
  api/types/database_test.go
  api/types/derived.gen.go
  api/types/types.pb.go
  api/utils/gcp/alloydb.go
  api/utils/gcp/alloydb_test.go
  docs/pages/reference/operator-resources/resources-teleport-dev-databasesv3.mdx
  docs/pages/reference/terraform-provider/data-sources/database.mdx
  docs/pages/reference/terraform-provider/resources/database.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_databasesv3.yaml
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/operator/config/crd/bases/resources.teleport.dev_databasesv3.yaml
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  integrations/terraform/tfschema/types_terraform.go
  lib/cloud/clients.go
  lib/cloud/gcp/alloydb.go
  lib/cloud/gcp/alloydb_test.go
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/service/servicecfg/database.go
  lib/services/database.go
  lib/services/database_test.go
  lib/srv/db/auth_test.go
  lib/srv/db/common/auth.go
  lib/srv/db/endpoints/endpoints.go
  lib/srv/db/postgres/alloydb.go
  lib/srv/db/postgres/alloydb_test.go
  lib/srv/db/postgres/connector.go
  lib/srv/db/postgres/engine.go
  tool/teleport/common/teleport.go
  tool/tsh/common/tsh_test.go
Labels: documentation, tsh, helm, database-access, backport, size/xl, hold-for-18.2

#58579 [loadtest] Add batch create resource Helm chart
  assets/loadtest/.gitignore
  assets/loadtest/Makefile
  assets/loadtest/helm/fixtures/tbot.yaml
  assets/loadtest/helm/resources/Chart.yaml
  assets/loadtest/helm/resources/README.md
  assets/loadtest/helm/resources/resources/apps.yaml
  assets/loadtest/helm/resources/templates/config.yaml
  assets/loadtest/helm/resources/templates/job.yaml
  assets/loadtest/helm/resources/templates/tbot.yaml
  assets/loadtest/helm/resources/values.yaml
  assets/loadtest/helm/values/app-service-agent.yaml
Labels: size/md, no-changelog

#58294 docs: document session recording RBAC
  docs/pages/reference/access-controls/roles.mdx
  docs/pages/reference/architecture/session-recording.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v18

#58587 Update the session summaries documentation link
  web/packages/teleport/src/SessionRecordings/list/SessionSummariesCta.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#58458 [v18] Fix markdown rendering issues
  web/packages/shared/components/Markdown/Markdown.tsx
Labels: ui, backport, size/sm, no-changelog

#58431 [v18] Session timeline prerequisites
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  web/packages/build/vite/config.ts
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/FilmStrip.tsx
  web/packages/design/src/Icon/assets/FilmStrip.svg
  web/packages/design/src/Icon/index.ts
  web/packages/design/src/theme/themes/bblpTheme.ts
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
  web/packages/design/src/theme/themes/types.ts
  web/packages/teleport/package.json
  web/packages/teleport/src/SessionRecordings/list/mock.ts
  web/packages/teleport/src/SessionRecordings/svg.ts
  web/packages/teleport/src/SessionRecordings/view/ProgressBar/ProgressBar.tsx
  web/packages/teleport/src/SessionRecordings/view/RecordingPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/SshPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/Timeline/constants.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimelineCanvasRenderer.ts
  web/packages/teleport/src/SessionRecordings/view/Xterm/Xterm.tsx
  web/packages/teleport/src/lib/term/ttyPlayer.js
  web/packages/teleport/src/services/recordings/types.ts
  web/packages/teleport/src/services/storageService/types.ts
  web/packages/teleterm/package.json
  web/patches/jest-canvas-mock@2.5.2.patch
Labels: ui, size/md, no-changelog

#58411 Docs: Fix step numbers and "How it works" sections
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery-guided.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery-manual.mdx
  docs/pages/identity-governance/entra-id/configure-access.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/zero-trust-access/management/guides/scim/sailpoint.mdx
  docs/pages/zero-trust-access/management/guides/scim/scim.mdx
  docs/pages/zero-trust-access/rbac-get-started/role-demo.mdx
Labels: documentation, size/sm, no-changelog

#58617 [v16] Remove outdated SSH language in the SSO guide
  docs/pages/zero-trust-access/sso/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#58596 [v17] MWI: Fix panic in SSH multiplexer
  lib/tbot/services/ssh/multiplexer.go
Labels: backport, machine-id, size/sm

#58655 [v18] Add the final main timeline renderer
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimelineRenderer.test.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/TimelineRenderer.ts
Labels: ui, backport, size/lg, no-changelog

#58646 [v18] Update the session summaries documentation link
  web/packages/teleport/src/SessionRecordings/list/SessionSummariesCta.tsx
Labels: ui, backport, size/sm, no-changelog

#58670 [v18] Make the summary box scroll properly
  web/packages/teleport/src/SessionRecordings/view/RecordingWithMetadata.tsx
Labels: ui, backport, size/sm, no-changelog

#58671 [v18] Add an interactive timeline to session recordings
  web/packages/teleport/src/SessionRecordings/view/RecordingWithMetadata.tsx
  web/packages/teleport/src/SessionRecordings/view/Timeline/RecordingTimeline.tsx
  web/packages/teleport/src/SessionRecordings/view/Timeline/ResizeHandle.tsx
  web/packages/teleport/src/SessionRecordings/view/Timeline/useCursor.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/utils.ts
Labels: ui, backport, size/lg

#58672 [v18] Support kubernetes sessions with the new metadata/thumbnails/timeline
  api/gen/proto/go/teleport/recordingmetadata/v1/recordingmetadata.pb.go
  api/proto/teleport/recordingmetadata/v1/recordingmetadata.proto
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata.go
  lib/web/recordingmetadata.go
  web/packages/teleport/src/SessionRecordings/list/RecordingItem.tsx
  web/packages/teleport/src/SessionRecordings/view/RecordingWithMetadata.tsx
  web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.test.tsx
  web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.tsx
Labels: ui, backport, size/sm, no-changelog

#58676 [v18] docs: update azure ad refs to entra id
  docs/config.json
  docs/pages/enroll-resources/application-access/controls.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-postgres-mysql.mdx
  docs/pages/feature-matrix.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/identity-governance/entra-id/terraform.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/zero-trust-access/infrastructure-as-code/terraform-starter/rbac.mdx
  docs/pages/zero-trust-access/sso/entra-id.mdx
Labels: documentation, backport, size/sm, no-changelog

#58654 Optimize UserMeetsRequirements
  lib/accesslists/hierarchy.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58679 [v18] Optimize UserMeetsRequirements
  lib/accesslists/hierarchy.go
Labels: backport, size/sm, no-changelog

#58632 [v18]docs: Add a "What's new" section to the homepage
  docs/pages/includes/homepage/version-highlights.mdx
  docs/pages/index.mdx
Labels: documentation, backport, size/sm, no-changelog

#58681 Use an actual hyperlink instead of a react-router link for docs
  web/packages/teleport/src/SessionRecordings/list/SessionSummariesCta.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#58583 Align AccessListMember.Clone method
  api/types/accesslist/member.go
  api/types/accesslist/member_test.go
Labels: size/sm, no-changelog, backport/branch/v18

#58686 Fix double dashes in markdown parsing
  web/packages/shared/components/Markdown/Markdown.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#58619 [v18] docs: list tradeoffs of using FIPS builds
  docs/pages/zero-trust-access/compliance-frameworks/fedramp.mdx
Labels: documentation, backport, size/sm, no-changelog

#58562 [v18] Don't display links in Markdown unless explicitly enabled
  web/packages/shared/components/Markdown/Markdown.test.tsx
  web/packages/shared/components/Markdown/Markdown.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Task.test.tsx
  web/packages/teleport/src/Integrations/status/AwsOidc/Tasks/Task.tsx
Labels: ui, backport, size/sm, no-changelog, hold-for-18.2

#58446 [v18] Implement Compaction of Desktop Shared Directory Read/Write Events
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_compactor.go
  lib/srv/desktop/audit_compactor_test.go
  lib/srv/desktop/windows_server.go
Labels: backport, desktop-access, size/md

#58694 [v18] Fix double dashes in markdown parsing
  web/packages/shared/components/Markdown/Markdown.tsx
Labels: ui, size/sm, no-changelog

#58689 fix: rbac for missing session fields in where cond
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/events/eventstest/generate.go
  lib/services/parser.go
  lib/services/role_test.go
  lib/srv/db/common/audit.go
  tool/common/common.go
  tool/tsh/common/tsh_test.go
Labels: audit-log, database-access, size/sm, no-changelog, backport/branch/v18, hold-for-18.2

#58705 [v18] fix rbac for missing session fields in where cond
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/events/eventstest/generate.go
  lib/services/parser.go
  lib/services/role_test.go
  lib/srv/db/common/audit.go
  tool/common/common.go
  tool/tsh/common/tsh_test.go
Labels: tsh, audit-log, database-access, backport, size/sm, no-changelog, hold-for-18.2

#58640 docs: Document KMS key discovery in Identity Security AWS Sync
  docs/pages/identity-security/integrations/aws-sync.mdx
Labels: documentation, size/sm, no-changelog

#57660 [v18] allow teleport-update to configure Teleport SSH SELinux module
  lib/autoupdate/agent/config.go
  lib/autoupdate/agent/process.go
  lib/autoupdate/agent/setup.go
  lib/autoupdate/agent/testdata/TestUpdater_Install/install_selinux_from_file.golden
  lib/autoupdate/agent/testdata/TestUpdater_Install/install_selinux_from_user.golden
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  lib/selinux/selinux_linux.go
  lib/selinux/selinux_others.go
  tool/teleport-update/main.go
Labels: backport, size/md, selinux

#58046 [AWSIC] Adds RoleSyncMode selection to `tctl plugins` tooling
  tool/tctl/common/plugin/awsic.go
  tool/tctl/common/plugin/plugins_command.go
Labels: tctl, size/sm, backport/branch/v17, aws-iam-identity-center, backport/branch/v18

#58702 [v17] [docs]:mwi use cases (PR #58333)
  docs/config.json
  docs/pages/machine-workload-identity/ai-agents-mwi.mdx
  docs/pages/machine-workload-identity/hybrid-multi-mwi.mdx
  docs/pages/machine-workload-identity/iac-mwi.mdx
  docs/pages/machine-workload-identity/mwi-ci-cd.mdx
  docs/pages/machine-workload-identity/workload-mwi.mdx
Labels: documentation, backport, size/md, no-changelog, backport/branch/v17

#58704 [v16] [docs]:mwi use cases (PR #58333)
  docs/config.json
  docs/pages/machine-workload-identity/ai-agents-mwi.mdx
  docs/pages/machine-workload-identity/hybrid-multi-mwi.mdx
  docs/pages/machine-workload-identity/iac-mwi.mdx
  docs/pages/machine-workload-identity/mwi-ci-cd.mdx
  docs/pages/machine-workload-identity/workload-mwi.mdx
Labels: documentation, backport, size/md, no-changelog, backport/branch/v16

#58688 [v18] Use an actual hyperlink instead of a react-router link for docs
  web/packages/teleport/src/SessionRecordings/list/SessionSummariesCta.tsx
Labels: ui, backport, size/sm, no-changelog

#58552 Fix session player scrolling for mouse
  web/packages/teleport/src/SessionRecordings/view/Timeline/RecordingTimeline.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#58697 [v16] docs: update azure ad refs to entra id
  docs/config.json
  docs/pages/enroll-resources/application-access/controls.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-postgres-mysql.mdx
  docs/pages/zero-trust-access/infrastructure-as-code/terraform-starter/rbac.mdx
  docs/pages/zero-trust-access/sso/entra-id.mdx
  docs/pages/zero-trust-access/sso/sso.mdx
Labels: documentation, backport, size/sm, no-changelog

#58690 Fill in missing "How it works" sections
  docs/pages/identity-governance/entra-id/terraform.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/argocd.mdx
Labels: documentation, size/sm, no-changelog

#58699 docs: fix issues with Azure AKS guide
  docs/pages/zero-trust-access/deploy-a-cluster/helm-deployments/azure.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58726 Fix logs not being emitted in verbose mode in `lib/tbot`
  lib/tbot/internal/carotation/service_test.go
  lib/tbot/internal/heartbeat/service_test.go
  lib/tbot/internal/loop_test.go
  lib/tbot/internal/sds/handler_test.go
  lib/tbot/services/application/helpers_test.go
  lib/tbot/services/awsra/helpers_test.go
  lib/tbot/services/database/helpers_test.go
  lib/tbot/services/identity/helpers_test.go
  lib/tbot/services/k8s/helpers_test.go
  lib/tbot/services/ssh/helpers_test.go
  lib/tbot/services/workloadidentity/helpers_test.go
  lib/tbot/workloadidentity/trust_bundle_cache_test.go
  lib/tbot/workloadidentity/workloadattest/workloadattest_test.go
Labels: machine-id, size/md, no-changelog, backport/branch/v18

#58742 [v18] Fix autoupdate package tests for SELinux on MacOS
  lib/autoupdate/agent/updater_test.go
Labels: backport, size/sm, no-changelog, selinux

#58708 [v18] Add metrics for `healthcheck` package
  api/types/target_health.go
  docs/pages/includes/metrics.mdx
  lib/healthcheck/manager.go
  lib/healthcheck/manager_test.go
  lib/healthcheck/worker.go
  metrics.go
Labels: documentation, backport, size/md

#58740 [v18] Fix logs not being emitted in verbose mode in `lib/tbot`
  lib/tbot/internal/carotation/service_test.go
  lib/tbot/internal/heartbeat/service_test.go
  lib/tbot/internal/loop_test.go
  lib/tbot/internal/sds/handler_test.go
  lib/tbot/services/application/helpers_test.go
  lib/tbot/services/awsra/helpers_test.go
  lib/tbot/services/database/helpers_test.go
  lib/tbot/services/identity/helpers_test.go
  lib/tbot/services/k8s/helpers_test.go
  lib/tbot/services/ssh/helpers_test.go
  lib/tbot/services/workloadidentity/helpers_test.go
  lib/tbot/workloadidentity/trust_bundle_cache_test.go
  lib/tbot/workloadidentity/workloadattest/workloadattest_test.go
Labels: backport, machine-id, size/md, no-changelog

#56325 Adding docs for encrypted sessions
  docs/cspell.json
  docs/pages/enroll-resources/server-access/guides/encrypted-session-recordings/encrypted-session-recordings.mdx
  docs/pages/enroll-resources/server-access/guides/encrypted-session-recordings/rotating-keys.mdx
  docs/pages/enroll-resources/server-access/guides/encrypted-session-recordings/rotating-manual-keys.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/reference/architecture/session-recording.mdx
  docs/pages/reference/cli/tctl.mdx
  docs/pages/reference/cli/tsh.mdx
  docs/pages/zero-trust-access/deploy-a-cluster/hsm.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58738 [v16] Ignore missing "How it works" sections
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/azure.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/gcp.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/google-cloud.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/azure.mdx
  docs/pages/enroll-resources/auto-discovery/kubernetes/google-cloud.mdx
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/gcp-discovery.mdx
  docs/pages/enroll-resources/database-access/getting-started.mdx
  docs/pages/enroll-resources/desktop-access/directory-sharing.mdx
  docs/pages/enroll-resources/kubernetes-access/getting-started.mdx
  docs/pages/enroll-resources/kubernetes-access/manage-access.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/dynamic-registration.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/iam-joining.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/static-kubeconfig.mdx
  docs/pages/enroll-resources/server-access/getting-started.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-agentless.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
  docs/pages/get-started.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-mattermost.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-slack.mdx
  docs/pages/identity-governance/device-trust/jamf-integration.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/aws.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gcp.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux.mdx
  docs/pages/machine-workload-identity/workload-identity/getting-started.mdx
  docs/pages/zero-trust-access/access-controls/getting-started.mdx
  docs/pages/zero-trust-access/access-controls/guides/hardware-key-support.mdx
  docs/pages/zero-trust-access/api/automatically-register-agents.mdx
  docs/pages/zero-trust-access/deploy-a-cluster/aws-kms.mdx
  docs/pages/zero-trust-access/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx
  docs/pages/zero-trust-access/export-audit-events/elastic-stack.mdx
  docs/pages/zero-trust-access/export-audit-events/fluentd.mdx
  docs/pages/zero-trust-access/export-audit-events/splunk.mdx
  docs/pages/zero-trust-access/infrastructure-as-code/terraform-provider/spacelift.mdx
  docs/pages/zero-trust-access/management/admin/labels.mdx
  docs/pages/zero-trust-access/management/admin/trustedclusters.mdx
  docs/pages/zero-trust-access/management/guides/ssh-key-extensions.mdx
  docs/pages/zero-trust-access/management/operations/proxy-peering.mdx
  docs/pages/zero-trust-access/sso/adfs.mdx
  docs/pages/zero-trust-access/sso/entra-id.mdx
  docs/pages/zero-trust-access/sso/gitlab.mdx
  docs/pages/zero-trust-access/sso/google-workspace.mdx
  docs/pages/zero-trust-access/sso/okta.mdx
  docs/pages/zero-trust-access/sso/one-login.mdx
Labels: documentation, backport, size/md, no-changelog

#58731 [v17] Docs: Fix step numbers and "How it works" sections
  docs/pages/enroll-resources/database-access/getting-started.mdx
  docs/pages/enroll-resources/server-access/getting-started.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/zero-trust-access/management/admin/labels.mdx
Labels: documentation, backport, size/sm, no-changelog

#58739 Replace `assert` with `require` in host user integration tests
  integration/hostuser_test.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58463 Enable merge_group trigger for CLA Assistant workflow
  .github/workflows/cla-assistant.yaml
Labels: size/sm, no-changelog

#58756 [v18] Web UI: Add Entrypoints for AWS Roles Anywhere
  web/packages/teleport/src/Discover/SelectResource/Tile.tsx
  web/packages/teleport/src/Discover/SelectResource/resources/resources.tsx
  web/packages/teleport/src/Discover/SelectResource/types.ts
  web/packages/teleport/src/Discover/useDiscover.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles/IntegrationTiles.test.tsx
  web/packages/teleport/src/Integrations/Enroll/IntegrationTiles/integrations.ts
  web/packages/teleport/src/services/userPreferences/discoverPreference.ts
Labels: ui, backport, size/sm, no-changelog

#58475 fix: Prevent an App from setting a public address that conflicts with a Teleport Proxy public address 👮🏾
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/service/service.go
  lib/services/app.go
  lib/services/app_test.go
  lib/web/app/middleware.go
Labels: documentation, security, backport-required, cli, application-access, size/md, sec-internal, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58759 Fix Encrypted Session Recording guides
  docs/pages/enroll-resources/server-access/guides/encrypted-session-recordings/rotating-keys.mdx
  docs/pages/enroll-resources/server-access/guides/encrypted-session-recordings/rotating-manual-keys.mdx
Labels: documentation, size/sm, no-changelog

#58717 Note required Teleport version in Kubernetes OIDC docs
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes-oidc.mdx
  docs/pages/reference/join-methods.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58780 Fix `TestGetTargetHealth` deadlock
  lib/healthcheck/worker_experimental_test.go
Labels: size/sm, no-changelog, backport/branch/v18

#58651 [v18] docs: document session recording RBAC
  docs/pages/reference/access-controls/roles.mdx
  docs/pages/reference/architecture/session-recording.mdx
Labels: documentation, backport, size/md, no-changelog

#58656 [v18] MWI: Document the `kubernetes/argo-cd` output
  docs/pages/machine-workload-identity/machine-id/access-guides/access-guides.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/argocd.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/md, no-changelog

#58567 [v17] MWI: `kubernetes/argo-cd` service
  docs/pages/includes/helm-reference/zz_generated.tbot.mdx
  examples/chart/tbot/.lint/argocd.yaml
  examples/chart/tbot/templates/_config.tpl
  examples/chart/tbot/tests/__snapshot__/config_test.yaml.snap
  examples/chart/tbot/tests/config_test.yaml
  examples/chart/tbot/values.yaml
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  lib/tbot/config/config.go
  lib/tbot/services/k8s/argocd_output.go
  lib/tbot/services/k8s/argocd_output_config.go
  lib/tbot/services/k8s/argocd_output_config_test.go
  lib/tbot/services/k8s/argocd_output_test.go
  lib/tbot/services/k8s/helpers_test.go
  lib/tbot/services/k8s/k8s.go
  lib/tbot/services/k8s/output_v1.go
  lib/tbot/services/k8s/output_v2.go
  lib/tbot/services/k8s/output_v2_config.go
  lib/tbot/services/k8s/secret_destination.go
  lib/tbot/services/k8s/secret_destination_test.go
  lib/tbot/services/k8s/testdata/TestArgoCDOutput_YAML/full.golden
  lib/tbot/services/k8s/testdata/TestArgoCDOutput_YAML/minimal.golden
  lib/tbot/tbot.go
Labels: documentation, helm, backport, machine-id, size/lg

#58744 [v17] docs: update slack video to import
  docs/pages/identity-governance/access-request-plugins/ssh-approval-slack.mdx
Labels: documentation, backport, size/sm, no-changelog

#58791 [v17] MWI: Allow configuration of default namespace for `kubernetes/v2` service (#58393)
  lib/tbot/services/k8s/argocd_output.go
  lib/tbot/services/k8s/output_v2.go
  lib/tbot/services/k8s/output_v2_config.go
  lib/tbot/services/k8s/output_v2_config_test.go
  lib/tbot/services/k8s/output_v2_test.go
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/absolute_path/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/exec_plugin_disabled/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2OutputService_render/relative_path/kubeconfig.yaml.golden
  lib/tbot/services/k8s/testdata/TestKubernetesV2Output_YAML/full.golden
Labels: backport, machine-id, size/sm

#58659 Align Access Lisit Owners/Members Eligibility status.
  lib/services/local/access_list.go
  lib/services/local/access_list_test.go
Labels: size/md, no-changelog, backport/branch/v17, backport/branch/v18

#58766 [v18] fix: Prevent an App from setting a public address that conflicts with a Teleport Proxy public address 👮
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/service/service.go
  lib/services/app.go
  lib/services/app_test.go
  lib/web/app/middleware.go
Labels: documentation, security, application-access, backport, size/md, sec-internal

#58767 [v17] fix: Prevent an App from setting a public address that conflicts with a Teleport Proxy public address 👮
  docs/pages/enroll-resources/application-access/guides/connecting-apps.mdx
  lib/auth/grpcserver.go
  lib/auth/grpcserver_test.go
  lib/service/service.go
  lib/services/app.go
  lib/services/app_test.go
  lib/web/app/middleware.go
Labels: documentation, security, application-access, backport, size/md, sec-internal

#58789 Round timeline's time value so it doesn't pass a float
  web/packages/teleport/src/SessionRecordings/view/Timeline/RecordingTimeline.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#58804 [v18] fix: populate `user_roles` and `user_traits` for ssh sessions
  api/types/wrappers/wrappers.go
  lib/bpf/bpf.go
  lib/bpf/common.go
  lib/srv/authhandlers.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/sess.go
  lib/srv/session_control.go
Labels: bpf, backport, size/sm

#58788 [v18] Add session recording summarizer documentation
  docs/img/identity-security/rec-list-with-summary.png
  docs/img/identity-security/summary-button.png
  docs/pages/identity-security/session-summaries.mdx
  docs/pages/includes/metrics.mdx
  docs/pages/reference/architecture/session-recording.mdx
  docs/pages/reference/resources.mdx
Labels: documentation, backport, size/md, no-changelog

#58810 Change a heading in the session summaries guide
  docs/pages/identity-security/session-summaries.mdx
Labels: documentation, size/sm, no-changelog

#58772 [v16]. Backport CLA Assistant Workflow
  .github/workflows/cla-assistant.yaml
  CLA.md
Labels: backport, size/sm, no-changelog

#58487 [v18] Add docs for the Intune integration
  docs/cspell.json
  docs/pages/identity-governance/device-trust/device-management.mdx
  docs/pages/identity-governance/device-trust/device-trust.mdx
  docs/pages/identity-governance/device-trust/enforcing-device-trust.mdx
  docs/pages/identity-governance/device-trust/guide.mdx
  docs/pages/identity-governance/device-trust/intune-integration.mdx
  docs/pages/identity-governance/device-trust/jamf-integration.mdx
  docs/pages/includes/device-trust/troubleshooting.mdx
  docs/pages/reference/cli/tctl.mdx
  docs/pages/zero-trust-access/authentication/webauthn.mdx
Labels: documentation, backport, size/md, no-changelog

#58734 [v18] docs: fix issues with Azure AKS guide
  docs/pages/zero-trust-access/deploy-a-cluster/helm-deployments/azure.mdx
Labels: documentation, backport, size/sm, no-changelog

#58643 docs: add saml idp rbac guide under igs pages
  docs/pages/identity-governance/idps/idps.mdx
  docs/pages/identity-governance/idps/saml-guide.mdx
  docs/pages/identity-governance/idps/saml-idp-rbac.mdx
  docs/pages/reference/access-controls/saml-idp.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v18

#58669 [v18] Rename teleport-policy.mdx to identity-security.mdx in docs
  docs/config.json
  docs/cspell.json
  docs/pages/identity-security/access-graph/identity-activity-center.mdx
  docs/pages/identity-security/crown-jewels.mdx
  docs/pages/identity-security/identity-security.mdx
  docs/pages/identity-security/integrations/aws-sync.mdx
  docs/pages/identity-security/integrations/azure-sync.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/identity-security/integrations/github.mdx
  docs/pages/identity-security/integrations/gitlab.mdx
  docs/pages/identity-security/integrations/netiq.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/identity-security/integrations/teleport.mdx
  docs/pages/identity-security/teleport-policy.mdx
  docs/pages/reference/identity-security-config.mdx
  tool/tctl/common/plugin/entraid.go
Labels: documentation, tctl, backport, size/sm, no-changelog

#58803 [v16] Update details on Cloud public IPs
  docs/pages/ips.mdx
Labels: documentation, backport, size/sm, no-changelog

#58784 [v17] docs: broken mwi links in tilegrid
  docs/pages/machine-workload-identity/hybrid-multi-mwi.mdx
  docs/pages/machine-workload-identity/iac-mwi.mdx
  docs/pages/machine-workload-identity/mwi-ci-cd.mdx
Labels: documentation, backport, size/sm, no-changelog

#58801 [v18] Update details on Cloud public IPs
  docs/pages/ips.mdx
Labels: documentation, backport, size/sm, no-changelog

#58835 [v18] chore: Bump Go to 1.24.7 ⬆️
  api/types/summarizer/summarizer_test.go
  assets/backport/go.mod
  build.assets/Dockerfile-grpcbox
  build.assets/tooling/go.mod
  build.assets/versions.mk
  examples/access-plugin-minimal/go.mod
  examples/api-sync-roles/go.mod
  examples/desktop-registration/go.mod
  examples/go-client/go.mod
  examples/service-discovery-api-client/go.mod
  examples/teleport-usage/go.mod
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform-mwi/go.mod
  integrations/terraform/go.mod
Labels: go, backport, dependencies, size/sm

#58724 docs: update link to entra id
  docs/pages/zero-trust-access/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58599 [v16] Update pnpm to 10.15.1
  package.json
Labels: backport, size/sm, no-changelog

#58598 [v17] Update pnpm to 10.15.1
  package.json
Labels: backport, size/sm, no-changelog

#58848 [v18] docs: update link to entra id
  docs/pages/zero-trust-access/infrastructure-as-code/terraform-starter/rbac.mdx
Labels: documentation, backport, size/sm, no-changelog

#58859 Remove unused dev features from Connect
  web/packages/teleterm/src/main.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58872 [v18] fix: session trackers participants inconsistencies
  api/proto/teleport/legacy/types/types.proto
  api/types/session_tracker.go
  api/types/session_tracker_test.go
  api/types/types.pb.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/events/complete_test.go
  lib/kube/proxy/sess.go
  lib/services/local/sessiontracker.go
  lib/services/parser.go
  lib/services/parser_test.go
  lib/services/sessiontracker.go
  lib/services/user.go
  lib/services/user_test.go
  lib/session/session.go
  lib/srv/app/session.go
  lib/srv/db/server.go
  lib/srv/desktop/windows_server.go
  lib/srv/sess.go
  lib/srv/sessiontracker_test.go
  lib/web/apiserver.go
Labels: kubernetes-access, audit-log, application-access, database-access, backport, desktop-access, size/md, no-changelog

#58833 Remove OSS link in prerequisite partial
  docs/pages/includes/edition-prereqs-tabs.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58844 Fix race in LocalSupervisor
  lib/service/supervisor.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58866 Tag MWI docs pages by use case and cloud
  docs/pages/machine-workload-identity/ai-agents-mwi.mdx
  docs/pages/machine-workload-identity/hybrid-multi-mwi.mdx
  docs/pages/machine-workload-identity/iac-mwi.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/access-guides.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/ansible.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/applications.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/argocd.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/databases.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/kubernetes.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/mcp.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/ssh.mdx
  docs/pages/machine-workload-identity/machine-id/access-guides/tctl.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/aws.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure-devops.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/bitbucket.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/circleci.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/deployment.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gcp.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/github-actions.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gitlab.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/jenkins.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes-oidc.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux-tpm.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux.mdx
  docs/pages/machine-workload-identity/machine-id/faq.mdx
  docs/pages/machine-workload-identity/machine-id/getting-started.mdx
  docs/pages/machine-workload-identity/machine-id/introduction.mdx
  docs/pages/machine-workload-identity/machine-id/machine-id.mdx
  docs/pages/machine-workload-identity/machine-id/manifesto.mdx
  docs/pages/machine-workload-identity/machine-id/troubleshooting.mdx
  docs/pages/machine-workload-identity/machine-workload-identity.mdx
  docs/pages/machine-workload-identity/mwi-ci-cd.mdx
  docs/pages/machine-workload-identity/workload-identity/aws-oidc-federation.mdx
  docs/pages/machine-workload-identity/workload-identity/aws-roles-anywhere.mdx
  docs/pages/machine-workload-identity/workload-identity/azure-federated-credentials.mdx
  docs/pages/machine-workload-identity/workload-identity/best-practices.mdx
  docs/pages/machine-workload-identity/workload-identity/federation.mdx
  docs/pages/machine-workload-identity/workload-identity/gcp-workload-identity-federation-jwt.mdx
  docs/pages/machine-workload-identity/workload-identity/getting-started.mdx
  docs/pages/machine-workload-identity/workload-identity/introduction.mdx
  docs/pages/machine-workload-identity/workload-identity/jwt-svids.mdx
  docs/pages/machine-workload-identity/workload-identity/spiffe.mdx
  docs/pages/machine-workload-identity/workload-identity/tsh.mdx
  docs/pages/machine-workload-identity/workload-identity/workload-identity.mdx
  docs/pages/machine-workload-identity/workload-mwi.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58921 [v16] Include fdpass-teleport in install script
  build.assets/install
Labels: backport, size/sm

#58892 docs(backends): remove unused s3:DeleteObject* actions from IAM policy
  docs/pages/reference/backends.mdx
Labels: documentation, size/sm, no-changelog

#58913 [v18] Add the new session recording tty player
  web/packages/teleport/src/SessionRecordings/view/player/tty/AspectFitRatio.ts
  web/packages/teleport/src/SessionRecordings/view/player/tty/TtyPlayer.ts
  web/packages/teleport/src/SessionRecordings/view/player/tty/decoding.ts
  web/packages/teleport/src/SessionRecordings/view/player/tty/types.ts
Labels: ui, backport, size/md, no-changelog

#58912 [v18] Docs: AWS IAM Roles Anywhere integration and profile sync setup
  docs/cspell.json
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console-roles-anywhere.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/aws-console.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/cloud-apis.mdx
Labels: documentation, backport, size/md, no-changelog

#58586 Add the new session recording player component
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata.go
  web/packages/design/src/Box/Box.tsx
  web/packages/design/src/Flex/Flex.tsx
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/CornersIn.tsx
  web/packages/design/src/Icon/Icons/CornersOut.tsx
  web/packages/design/src/Icon/Icons/Pause.tsx
  web/packages/design/src/Icon/Icons/Play.tsx
  web/packages/design/src/Icon/assets/CornersIn.svg
  web/packages/design/src/Icon/assets/CornersOut.svg
  web/packages/design/src/Icon/assets/Pause.svg
  web/packages/design/src/Icon/assets/Play.svg
  web/packages/design/src/Icon/index.ts
  web/packages/design/src/Tooltip/HoverTooltip.tsx
  web/packages/design/src/theme/themes/bblpTheme.ts
  web/packages/design/src/theme/themes/darkTheme.ts
  web/packages/design/src/theme/themes/lightTheme.ts
  web/packages/design/src/theme/themes/types.ts
  web/packages/teleport/src/SessionRecordings/view/RecordingPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/RecordingWithMetadata.tsx
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/FramesRenderer.test.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/FramesRenderer.ts
  web/packages/teleport/src/SessionRecordings/view/Timeline/renderers/ResizeEventsRenderer.ts
  web/packages/teleport/src/SessionRecordings/view/player/PlayerControls.tsx
  web/packages/teleport/src/SessionRecordings/view/player/RecordingPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/player/tty/AspectFitRatio.ts
  web/packages/teleport/src/SessionRecordings/view/player/tty/TtyPlayer.ts
  web/packages/teleport/src/SessionRecordings/view/player/tty/TtyRecordingPlayer.tsx
  web/packages/teleport/src/SessionRecordings/view/stream/SessionStream.ts
  web/packages/teleport/src/components/hooks/useFullscreen.ts
  web/packages/teleport/src/config.ts
Labels: ui, size/lg, backport/branch/v18

#58613 [v18][mcp] add a preset mcp-user role
  api/types/app.go
  api/types/app_test.go
  api/types/constants.go
  constants.go
  lib/auth/init.go
  lib/auth/init_test.go
  lib/services/presets.go
  lib/srv/mcp/helpers_test.go
  tool/tsh/common/testdata/Test_mcpListCommand/JSON_format.golden
  tool/tsh/common/testdata/Test_mcpListCommand/YAML_format.golden
  tool/tsh/common/testdata/Test_mcpListCommand/text_format_in_verbose.golden
Labels: tsh, backport, size/sm

#58871 [v18] Add a new API for session recording playback
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata.go
  lib/auth/recordingmetadata/recordingmetadatav1/recordingmetadata_test.go
  lib/terminal/ansi.go
  lib/terminal/ansi_test.go
  lib/web/apiserver.go
  lib/web/recordingplayback.go
  lib/web/recordingplayback_protocol.go
  lib/web/recordingplayback_protocol_test.go
  lib/web/recordingplayback_test.go
Labels: backport, size/lg, no-changelog

#58827 Deflake TestIntegrations/ModeratedSFTP
  lib/srv/sess.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58700 Make `TargetServer` a required field in the forwarding server
  lib/proxy/router.go
  lib/proxy/router_test.go
  lib/reversetunnel/localsite.go
  lib/reversetunnel/remotesite.go
  lib/reversetunnelclient/api.go
  lib/srv/forward/sshserver.go
  lib/srv/forward/sshserver_test.go
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57227 Adds services for pruning roles when requesting remote resources.
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  integration/helpers/web.go
  lib/auth/auth_with_roles.go
  lib/auth/grpcserver.go
  lib/services/access_request.go
  lib/services/access_request_test.go
  lib/services/trustedcluster.go
Labels: size/md, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58824 RFD 223: Multiple Agents in EC2 Auto Discovery
  rfd/0223-multi-agent-ec2-discovery.md
  rfd/cspell.json
Labels: rfd, size/md, no-changelog

#58914 [v18] Bump zod from 3.25.67 to 4.1.5
  pnpm-lock.yaml
  web/packages/teleterm/package.json
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/services/config/configService.test.ts
  web/packages/teleterm/src/services/config/configService.ts
  web/packages/teleterm/src/services/config/fixtures/mocks.ts
  web/packages/teleterm/src/services/config/keyboardShortcutSchema.test.ts
  web/packages/teleterm/src/services/config/keyboardShortcutSchema.ts
  web/packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Labels: ui, backport, size/sm, no-changelog

#58957 [v16] Deflake TestIntegration/ModeratedSFTP
  lib/srv/sess.go
Labels: backport, size/sm, no-changelog

#58919 [v18] Include fdpass-teleport in install script
  build.assets/install
Labels: backport, size/sm

#58867 Tag guides by cloud provider and use case
  docs/pages/connect-your-client/gui-clients.mdx
  docs/pages/connect-your-client/model-context-protocol/database-access.mdx
  docs/pages/connect-your-client/model-context-protocol/mcp-access.mdx
  docs/pages/connect-your-client/model-context-protocol/model-context-protocol.mdx
  docs/pages/connect-your-client/notifications.mdx
  docs/pages/connect-your-client/putty-winscp.mdx
  docs/pages/connect-your-client/request-access.mdx
  docs/pages/connect-your-client/vnet.mdx
  docs/pages/identity-security/access-graph/access-graph.mdx
  docs/pages/identity-security/access-graph/identity-activity-center.mdx
  docs/pages/identity-security/access-graph/self-hosted-helm.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/identity-security/crown-jewels.mdx
  docs/pages/identity-security/how-to-use.mdx
  docs/pages/identity-security/identity-security.mdx
  docs/pages/identity-security/integrations/aws-sync.mdx
  docs/pages/identity-security/integrations/azure-sync.mdx
  docs/pages/identity-security/integrations/entra-id.mdx
  docs/pages/identity-security/integrations/github.mdx
  docs/pages/identity-security/integrations/gitlab.mdx
  docs/pages/identity-security/integrations/integrations.mdx
  docs/pages/identity-security/integrations/netiq.mdx
  docs/pages/identity-security/integrations/ssh-keys-scan.mdx
  docs/pages/identity-security/integrations/teleport.mdx
  docs/pages/identity-security/policy-connections.mdx
  docs/pages/identity-security/session-summaries.mdx
  docs/pages/installation/amazon-ec2.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58828 [v18] [teleport-update] Expose install suffix, dir, and PATH as env vars
  tool/teleport-update/main.go
Labels: backport, size/sm, no-changelog

#58667 docs: add saml idp rbac related troubleshooting guide in the identity center integration doc
  docs/img/identity-center/ic-saml-login-audit-log.png
  docs/pages/identity-governance/aws-iam-identity-center/guide.mdx
  docs/pages/identity-governance/aws-iam-identity-center/migrating-identity-center-from-okta-to-teleport.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#58989 fix: deflake TestTerminalSizeRequest
  lib/srv/regular/sshserver_test.go
Labels: no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58884 Update Headless docs for SSO MFA
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/faq.mdx
  docs/pages/reference/cli/tsh.mdx
  docs/pages/zero-trust-access/authentication/headless.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#58052 delete process.Config.HostUUID
  integration/helpers/instance.go
  integration/hostuser_test.go
  lib/service/connect.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/servicecfg/config.go
Labels: size/sm, no-changelog, backport/branch/v18

#58947 Fix link in Kube access error messages
  docs/config.json
  lib/kube/proxy/auth.go
Labels: bug, documentation, kubernetes-access, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58995 [v16] fix: deflake TestTerminalSizeRequest
  lib/srv/regular/sshserver_test.go
Labels: backport, size/sm, no-changelog

#58993 [v18] fix: deflake TestTerminalSizeRequest
  lib/srv/regular/sshserver_test.go
Labels: backport, size/sm, no-changelog

#59003 [v18] delete process.Config.HostUUID
  integration/helpers/instance.go
  integration/hostuser_test.go
  lib/service/connect.go
  lib/service/service.go
  lib/service/service_test.go
  lib/service/servicecfg/config.go
Labels: backport, size/sm, no-changelog

#59089 [v17] Fix client tools managed updates sequential update
  Makefile
  integration/autoupdate/tools/main_test.go
  integration/autoupdate/tools/updater/modules.go
  integration/autoupdate/tools/updater/tctl/main.go
  integration/autoupdate/tools/updater/tsh/main.go
  integration/autoupdate/tools/updater_test.go
  integration/autoupdate/tools/updater_tsh_test.go
  integration/helpers/archive/packaging.go
  lib/autoupdate/tools/helper.go
  lib/autoupdate/tools/updater.go
  lib/autoupdate/tools/utils.go
  lib/autoupdate/tools/utils_test.go
  lib/service/service.go
  lib/utils/packaging/unarchive.go
  lib/utils/packaging/unarchive_test.go
  lib/utils/packaging/unarchive_unix.go
Labels: backport, size/md

#59090 [v16] Fix client tools managed updates sequential update (#58954)
  Makefile
  integration/autoupdate/tools/main_test.go
  integration/autoupdate/tools/updater/modules.go
  integration/autoupdate/tools/updater/tctl/main.go
  integration/autoupdate/tools/updater/tsh/main.go
  integration/autoupdate/tools/updater_test.go
  integration/autoupdate/tools/updater_tsh_test.go
  integration/helpers/archive/packaging.go
  lib/autoupdate/tools/helper.go
  lib/autoupdate/tools/updater.go
  lib/autoupdate/tools/utils.go
  lib/autoupdate/tools/utils_test.go
  lib/service/service.go
  lib/utils/packaging/unarchive.go
  lib/utils/packaging/unarchive_test.go
  lib/utils/packaging/unarchive_unix.go
Labels: backport, size/md

#57691 [AWSIC] Update SCIM token with `tctl`
  tool/tctl/common/plugin/awsic.go
  tool/tctl/common/plugin/awsic_test.go
  tool/tctl/common/plugin/entraid.go
  tool/tctl/common/plugin/github.go
  tool/tctl/common/plugin/mocks_test.go
  tool/tctl/common/plugin/netiq.go
  tool/tctl/common/plugin/okta.go
  tool/tctl/common/plugin/plugins_command.go
  tool/tctl/common/plugin/plugins_command_test.go
  tool/tctl/common/plugin/scim.go
Labels: tctl, size/sm, backport/branch/v17, aws-iam-identity-center, backport/branch/v18

#59081 Device Trust empty state UI: Link to integrations list
  web/packages/teleport/src/DeviceTrust/EmptyList.tsx
  web/packages/teleport/src/config.test.ts
  web/packages/teleport/src/config.ts
Labels: ui, size/sm, no-changelog, backport/branch/v18

#59107 WebDiscover: fix aws rds databases language
  web/packages/teleport/src/Discover/Database/SetupAccess/AwsRdsAuthRequirements.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#59118 [v18] WebDiscover: fix aws rds databases language
  web/packages/teleport/src/Discover/Database/SetupAccess/AwsRdsAuthRequirements.tsx
Labels: ui, backport, size/sm, no-changelog

#59112 docs: add info on license auto updates
  docs/pages/zero-trust-access/deploy-a-cluster/license.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58943 Add tags to four Zero Trust Access docs sections
  docs/pages/zero-trust-access/api/automatically-register-agents.mdx
  docs/pages/zero-trust-access/api/rbac.mdx
  docs/pages/zero-trust-access/authentication/hardware-key-support.mdx
  docs/pages/zero-trust-access/authentication/headless.mdx
  docs/pages/zero-trust-access/authentication/ip-pinning.mdx
  docs/pages/zero-trust-access/authentication/joining-sessions.mdx
  docs/pages/zero-trust-access/authentication/login-rules/guide.mdx
  docs/pages/zero-trust-access/authentication/login-rules/login-rules.mdx
  docs/pages/zero-trust-access/authentication/mfa-for-admin-actions.mdx
  docs/pages/zero-trust-access/authentication/passwordless.mdx
  docs/pages/zero-trust-access/authentication/per-session-mfa.mdx
  docs/pages/zero-trust-access/authentication/webauthn.mdx
  docs/pages/zero-trust-access/rbac-get-started/labels.mdx
  docs/pages/zero-trust-access/rbac-get-started/rbac-get-started.mdx
  docs/pages/zero-trust-access/rbac-get-started/role-demo.mdx
  docs/pages/zero-trust-access/rbac-get-started/role-templates.mdx
  docs/pages/zero-trust-access/sso/adfs.mdx
  docs/pages/zero-trust-access/sso/entra-id-oidc.mdx
  docs/pages/zero-trust-access/sso/entra-id.mdx
  docs/pages/zero-trust-access/sso/github-sso.mdx
  docs/pages/zero-trust-access/sso/gitlab.mdx
  docs/pages/zero-trust-access/sso/google-workspace.mdx
  docs/pages/zero-trust-access/sso/keycloak.mdx
  docs/pages/zero-trust-access/sso/oidc.mdx
  docs/pages/zero-trust-access/sso/okta.mdx
  docs/pages/zero-trust-access/sso/one-login.mdx
  docs/pages/zero-trust-access/sso/sso.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#59124 [v18] docs: correct ec2 manual discovery link
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery-guided.mdx
Labels: documentation, backport, size/sm, no-changelog

#59120 [v18] Device Trust empty state UI: Link to integrations list
  web/packages/teleport/src/DeviceTrust/EmptyList.tsx
  web/packages/teleport/src/config.test.ts
  web/packages/teleport/src/config.ts
Labels: ui, backport, size/sm, no-changelog

#58121 fix PuTTY link in putty-winscp.mdx
  docs/pages/connect-your-client/putty-winscp.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#58257 [18.1.8] Bump cloud docs
  docs/config.json
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#59134 Turn off react-hooks/preserve-manual-memoization ESLint rule
  web/packages/build/eslint.config.mjs
Labels: ui, size/sm, no-changelog

#59129 [v18] docs: add info on license auto updates
  docs/pages/zero-trust-access/deploy-a-cluster/license.mdx
Labels: documentation, backport, size/sm, no-changelog

#59132 [v18] docs: fix instructions for creating DynamoDB events table
  docs/cspell.json
  docs/pages/includes/dynamodb-iam-policy.mdx
Labels: documentation, backport, size/sm, no-changelog
