Repository gravitational/teleport, pull requests merged in 2025-08, with the labels that each got.

#57349 [v16] [17.5.6] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#57370 [docs]clarify github integration pre-req
  docs/pages/admin-guides/management/guides/github-integration.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57074 Add protos for Intune plugin
  api/proto/teleport/legacy/types/types.proto
  api/types/intune.go
  api/types/plugin.go
  api/types/plugin_test.go
  api/types/types.pb.go
  tool/tctl/common/collection.go
Labels: tctl, size/sm, no-changelog

#57446 Fix case in icon import, re-run `pnpm process-icons`
  web/packages/design/src/ResourceIcon/assets/windows-dark.svg
  web/packages/design/src/ResourceIcon/assets/windows-light.svg
  web/packages/design/src/ResourceIcon/icons.ts
Labels: ui, size/sm, no-changelog, backport/branch/v18

#57447 [v18] Fix case in icon import
  web/packages/design/src/ResourceIcon/icons.ts
Labels: ui, backport, size/sm, no-changelog

#57211 [v18] Add an optional delay before Teleport shutdown
  docs/pages/includes/config-reference/instance-wide.yaml
  lib/config/configuration.go
  lib/config/configuration_test.go
  lib/config/fileconf.go
  lib/config/testdata_test.go
  lib/service/service.go
  lib/service/servicecfg/config.go
Labels: documentation, backport, size/sm

#57401 Fix printing empty usage and terminate CLI for parsing global flags
  lib/utils/cli.go
  tool/tctl/common/tctl.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, tctl, size/sm, backport/branch/v17, backport/branch/v18

#57323 [v18] Improve discovery bootstrap error messages
  lib/configurators/aws/aws.go
  lib/configurators/aws/aws_test.go
Labels: backport, size/sm, no-changelog

#57394 Lock `mc` to light theme
  web/packages/teleport/src/ThemeProvider.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57451 [v18] Fix printing empty usage and terminate CLI for parsing global flags
  lib/utils/cli.go
  tool/tctl/common/tctl.go
  tool/tsh/common/tsh.go
  tool/tsh/common/tsh_test.go
Labels: tsh, tctl, backport, size/sm

#57423 Clean up some utils
  integration/hostuser_test.go
  lib/client/sso/redirector.go
  lib/client/sso/redirector_internal_test.go
  lib/config/configuration.go
  lib/events/filesessions/filestream_test.go
  lib/release/release.go
  lib/service/service.go
  lib/utils/fs_test.go
  lib/utils/slices/slices.go
  lib/utils/utils.go
  lib/utils/utils_test.go
  tool/tbot/db.go
  tool/tsh/common/db_exec_test.go
Labels: tsh, audit-log, machine-id, size/sm, no-changelog

#57458 [v17] icons: add strapi logo
  web/packages/design/src/ResourceIcon/assets/strapi.svg
  web/packages/design/src/ResourceIcon/icons.ts
  web/packages/design/src/ResourceIcon/resourceIconSpecs.ts
Labels: ui, backport, size/sm, no-changelog

#57459 [v18] icons: add strapi logo
  web/packages/design/src/ResourceIcon/assets/strapi.svg
  web/packages/design/src/ResourceIcon/icons.ts
  web/packages/design/src/ResourceIcon/resourceIconSpecs.ts
Labels: ui, backport, size/sm, no-changelog

#57473 docs: update mcp link to docs on homepage
  docs/pages/includes/homepage/products.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#57495 [v16] Update pnpm to 10.14.0
  package.json
Labels: backport, size/sm, no-changelog

#56803 MWI: Move SSH services to `lib/tbot/services/ssh`
  lib/tbot/config/config.go
  lib/tbot/config/config_test.go
  lib/tbot/config/migrate.go
  lib/tbot/config/migrate_test.go
  lib/tbot/internal/output.go
  lib/tbot/service_identity_output.go
  lib/tbot/services/ssh/helpers_test.go
  lib/tbot/services/ssh/host_output.go
  lib/tbot/services/ssh/host_output_config.go
  lib/tbot/services/ssh/host_output_config_test.go
  lib/tbot/services/ssh/multiplexer.go
  lib/tbot/services/ssh/multiplexer_config.go
  lib/tbot/services/ssh/multiplexer_config_test.go
  lib/tbot/services/ssh/multiplexer_test.go
  lib/tbot/services/ssh/multiplexer_unix.go
  lib/tbot/services/ssh/multiplexer_windows.go
  lib/tbot/services/ssh/ssh.go
  lib/tbot/services/ssh/ssh_proxy.go
  lib/tbot/services/ssh/testdata/TestSSHHostOutput_YAML/full.golden
  lib/tbot/services/ssh/testdata/TestSSHHostOutput_YAML/minimal.golden
  lib/tbot/services/ssh/testdata/TestSSHMultiplexerService_YAML/full.golden
  lib/tbot/tbot.go
  lib/tbot/tbot_test.go
  tool/tbot/proxy_ssh.go
Labels: refactoring, machine-id, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#57444 [v16] Fix Admonitions
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/join-token.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
Labels: documentation, backport, size/sm, no-changelog

#57314 [v16] Fix broken links
  CHANGELOG.md
  docs/pages/machine-workload-identity/machine-workload-identity.mdx
Labels: documentation, backport, size/sm, no-changelog

#57475 [v18] docs: update mcp link to docs on homepage
  docs/pages/includes/homepage/products.mdx
Labels: documentation, backport, size/sm, no-changelog

#57461 Edit the guide to enrolling Amazon Redis caches
  docs/pages/enroll-resources/database-access/enroll-aws-databases/redis-aws.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57396 [v17] Add "How it works" H2s to 15 how-to guides
  docs/pages/admin-guides/access-controls/guides/passwordless.mdx
  docs/pages/admin-guides/access-controls/idps/saml-grafana.mdx
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/admin-guides/api/access-plugin.mdx
  docs/pages/admin-guides/api/getting-started.mdx
  docs/pages/admin-guides/api/rbac.mdx
  docs/pages/admin-guides/management/admin/daemon.mdx
  docs/pages/admin-guides/management/admin/uninstall-teleport.mdx
  docs/pages/enroll-resources/application-access/guides/tcp.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-email.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/linux-demo.mdx
  docs/pages/zero-trust-access/infrastructure-as-code/teleport-operator/teleport-operator-helm.mdx
  docs/pages/zero-trust-access/infrastructure-as-code/teleport-operator/teleport-operator-standalone.mdx
Labels: documentation, backport, size/md, no-changelog

#57442 [v17] Fix Admonitions
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
  docs/pages/enroll-resources/agents/join-token.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
  docs/pages/identity-governance/okta/scim-integration.mdx
  docs/pages/identity-governance/okta/user-sync.mdx
Labels: documentation, backport, size/sm, no-changelog

#57443 [v18] Fix Admonitions
  docs/pages/admin-guides/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment.mdx
  docs/pages/enroll-resources/agents/join-token.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-discord.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-jira.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-msteams.mdx
  docs/pages/identity-governance/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/identity-governance/okta/app-and-group-sync.mdx
  docs/pages/identity-governance/okta/scim-integration.mdx
  docs/pages/identity-governance/okta/user-sync.mdx
Labels: documentation, backport, size/sm, no-changelog

#55488 Move the Teleport IdP section to Identity Governance
  docs/config.json
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/guide.mdx
  docs/pages/admin-guides/management/operations/ca-rotation.mdx
  docs/pages/enroll-resources/application-access/application-access.mdx
  docs/pages/enroll-resources/application-access/cloud-apis/cloud-apis.mdx
  docs/pages/enroll-resources/application-access/introduction.mdx
  docs/pages/identity-governance/idps/idps.mdx
  docs/pages/identity-governance/idps/saml-attribute-mapping.mdx
  docs/pages/identity-governance/idps/saml-gcp-workforce-identity-federation.mdx
  docs/pages/identity-governance/idps/saml-grafana.mdx
  docs/pages/identity-governance/idps/saml-guide.mdx
  docs/pages/identity-governance/idps/saml-microsoft-entra-external-id.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57445 [v18] feat(web): Add Instances to Bot Details (#57023)
  lib/web/machineid.go
  lib/web/machineid_test.go
  pnpm-lock.yaml
  web/packages/design/src/Icon/Icons/ModelContextProtocol.tsx
  web/packages/design/src/Label/Label.tsx
  web/packages/design/src/Label/index.ts
  web/packages/design/src/ResourceIcon/assets/windows-dark.svg
  web/packages/design/src/ResourceIcon/assets/windows-light.svg
  web/packages/design/src/labels.story.jsx
  web/packages/shared/package.json
  web/packages/shared/utils/semVer.test.ts
  web/packages/shared/utils/semVer.ts
  web/packages/teleport/src/Bots/Details/BotDetails.story.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.test.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.tsx
  web/packages/teleport/src/Bots/Details/Instance.story.tsx
  web/packages/teleport/src/Bots/Details/Instance.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.story.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.test.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.tsx
  web/packages/teleport/src/Bots/Details/Panel.tsx
  web/packages/teleport/src/Bots/Edit/EditDialog.test.tsx
  web/packages/teleport/src/Bots/Edit/EditDialog.tsx
  web/packages/teleport/src/services/bot/types.ts
  web/packages/teleport/src/stores/storeUserContext.ts
  web/packages/teleport/src/test/helpers/botInstances.ts
  web/packages/teleport/src/useClusterVersion.test.tsx
  web/packages/teleport/src/useClusterVersion.ts
Labels: ui, backport, machine-id, size/lg, no-changelog

#56809 MWI: Use the new `bot` package in non-`tbot` binaries
  integrations/lib/embeddedtbot/bot.go
  integrations/lib/embeddedtbot/bot_test.go
  integrations/lib/embeddedtbot/config.go
  integrations/operator/main.go
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform-mwi/provider/kubernetes_data_source.go
  integrations/terraform-mwi/provider/kubernetes_ephemeral_resource.go
  integrations/terraform-mwi/provider/provider.go
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  integrations/terraform/provider/credentials.go
  tool/tctl/common/terraform_command.go
Labels: refactoring, tctl, machine-id, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57243 fix: Agent Forwarding - Windows System Agent and 1Password agent
  lib/client/api.go
  lib/client/keyagent.go
  lib/client/session.go
  lib/sshagent/client.go
  lib/sshagent/client_test.go
  lib/sshagent/clientconn_unix.go
  lib/sshagent/clientconn_windows.go
  lib/sshagent/doc.go
  lib/teleagent/agent.go
  lib/utils/agentconn/agent_unix.go
Labels: size/md, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57347 ui: differentiate desktop certs on the audit log page
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57481 [v18] Access request kube_resources tests
  lib/services/access_request_test.go
  lib/services/testdata/roles/v7_kube_accessrequest_validate.yaml
  lib/services/testdata/roles/v8_kube_accessrequest_validate.yaml
Labels: backport, size/lg, no-changelog

#57453 Fix terraform_autoupdate_version when metadata is non-nil
  integrations/terraform/protoc-gen-terraform-autoupdate.yaml
  integrations/terraform/tfschema/autoupdate/v1/autoupdate_terraform.go
Labels: bug, size/sm, terraform-provider, backport/branch/v17, backport/branch/v18

#57465 Gracefully handle NotFoundError for newly created singleton resources
  integrations/terraform/gen/plural_resource.go.tpl
  integrations/terraform/gen/singular_resource.go.tpl
  integrations/terraform/provider/resource_teleport_access_list.go
  integrations/terraform/provider/resource_teleport_access_monitoring_rule.go
  integrations/terraform/provider/resource_teleport_app.go
  integrations/terraform/provider/resource_teleport_auth_preference.go
  integrations/terraform/provider/resource_teleport_autoupdate_config.go
  integrations/terraform/provider/resource_teleport_autoupdate_version.go
  integrations/terraform/provider/resource_teleport_cluster_maintenance_config.go
  integrations/terraform/provider/resource_teleport_cluster_networking_config.go
  integrations/terraform/provider/resource_teleport_database.go
  integrations/terraform/provider/resource_teleport_device_trust.go
  integrations/terraform/provider/resource_teleport_dynamic_windows_desktop.go
  integrations/terraform/provider/resource_teleport_github_connector.go
  integrations/terraform/provider/resource_teleport_health_check_config.go
  integrations/terraform/provider/resource_teleport_installer.go
  integrations/terraform/provider/resource_teleport_login_rule.go
  integrations/terraform/provider/resource_teleport_oidc_connector.go
  integrations/terraform/provider/resource_teleport_okta_import_rule.go
  integrations/terraform/provider/resource_teleport_provision_token.go
  integrations/terraform/provider/resource_teleport_role.go
  integrations/terraform/provider/resource_teleport_saml_connector.go
  integrations/terraform/provider/resource_teleport_server.go
  integrations/terraform/provider/resource_teleport_session_recording_config.go
  integrations/terraform/provider/resource_teleport_static_host_user.go
  integrations/terraform/provider/resource_teleport_trusted_cluster.go
  integrations/terraform/provider/resource_teleport_user.go
  integrations/terraform/provider/resource_teleport_workload_identity.go
Labels: bug, size/sm, terraform-provider, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57403 [v17] docs: update outdated Access Management webui references
  docs/img/access-controls/saml-idp/access-app.png
  docs/img/access-controls/saml-idp/enroll-saml-app.png
  docs/img/access-controls/saml-idp/gcp-workforce/gcp-workforce-tile.png
  docs/img/access-controls/saml-idp/saml-add-auth.png
  docs/img/access-controls/saml-idp/saml-idp.png
  docs/img/access-graph/graph-explorer-ui.png
  docs/img/enterprise/plugins/datadog/review-access-request.png
  docs/img/enterprise/plugins/datadog/teleport-users.png
  docs/img/enterprise/plugins/enroll.png
  docs/pages/admin-guides/access-controls/idps/saml-gcp-workforce-identity-federation.mdx
  docs/pages/admin-guides/access-controls/idps/saml-guide.mdx
  docs/pages/admin-guides/management/guides/awsoidc-integration.mdx
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/identity-governance/access-request-plugins/datadog-hosted.mdx
  docs/pages/identity-governance/access-request-plugins/opsgenie.mdx
  docs/pages/identity-security/access-graph/self-hosted-helm.mdx
  docs/pages/identity-security/access-graph/self-hosted.mdx
  docs/pages/includes/plugins/enroll.mdx
Labels: documentation, backport, size/sm, no-changelog

#57462 [v18] [docs]clarify github integration pre-req
  docs/pages/admin-guides/management/guides/github-integration.mdx
Labels: documentation, backport, size/sm, no-changelog

#57522 FIx potential PATH issue in discovery script
  lib/srv/server/installer/defaultinstallers.go
  lib/srv/server/installer/defaultinstallers_test.go
Labels: size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57485 discovery: Fix boundary condition logging min tag AWS interval
  lib/srv/discovery/access_graph_aws.go
Labels: size/sm, discovery, no-changelog, backport/branch/v17, backport/branch/v18

#57486 [v16] Set packageImportMethod to clone-or-copy for pnpm
  pnpm-workspace.yaml
Labels: backport, size/sm, no-changelog

#57488 [v18] Set packageImportMethod to clone-or-copy for pnpm
  pnpm-workspace.yaml
Labels: backport, size/sm, no-changelog

#57044 [v17] docs: tbot-machine-id changes requested
  docs/pages/machine-workload-identity/machine-id/deployment/aws.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure-devops.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/azure.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/bitbucket.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/circleci.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/deployment.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gcp.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/github-actions.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/gitlab.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/jenkins.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/kubernetes.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux-tpm.mdx
  docs/pages/machine-workload-identity/machine-id/deployment/linux.mdx
Labels: documentation, backport, size/sm, no-changelog

#57455 Edit the Teleport Cloud architecture guide
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#56815 docs: proxy service page update
  docs/pages/admin-guides/deploy-a-cluster/separate-proxy-service-endpoints.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57525 Install `wasm32` target in MacOS workflow
  .github/workflows/build-macos.yaml
Labels: size/sm, no-changelog

#57186 [v18] Fix 25 Vale warnings
  api/gen/proto/go/teleport/accessmonitoringrules/v1/access_monitoring_rules.pb.go
  api/proto/teleport/accessmonitoringrules/v1/access_monitoring_rules.proto
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-redis.mdx
  docs/pages/installation/helm.mdx
  docs/pages/installation/installation.mdx
  docs/pages/reference/cli/tctl.mdx
  docs/pages/reference/terraform-provider/data-sources/access_monitoring_rule.mdx
  docs/pages/reference/terraform-provider/data-sources/cluster_networking_config.mdx
  docs/pages/reference/terraform-provider/data-sources/database.mdx
  docs/pages/reference/terraform-provider/resources/access_monitoring_rule.mdx
  docs/pages/reference/terraform-provider/resources/cluster_networking_config.mdx
  docs/pages/reference/terraform-provider/resources/database.mdx
  docs/pages/usage-billing.mdx
  integrations/terraform/tfschema/accessmonitoringrules/v1/access_monitoring_rules_terraform.go
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, backport, size/sm, no-changelog

#57390 [v18] Allow macOS users to follow the Linux Demo guide
  docs/cspell.json
  docs/pages/includes/tls-certificate-setup.mdx
  docs/pages/linux-demo.mdx
Labels: documentation, backport, size/md, no-changelog

#56930 [docs] Entra ID integration
  docs/img/igs/entraid/entra-api-permission.png
  docs/img/igs/entraid/entra-create-enterprise-app.png
  docs/img/igs/entraid/entra-default-owners.png
  docs/img/igs/entraid/entra-finish.png
  docs/img/igs/entraid/entra-setup-oidc.png
  docs/img/igs/entraid/entra-sso-config.png
  docs/pages/identity-governance/entra-id/entra-id.mdx
  docs/pages/identity-governance/entra-id/faq.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/includes/identity-governance/azure-shell.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v17, backport/branch/v18

#57527 docs: Add a terraform example for `login_rule.traits_expression`
  docs/pages/reference/terraform-provider/resources/login_rule.mdx
  integrations/terraform/examples/resources/teleport_login_rule/resource.tf
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57511 [v18] fix: Agent Forwarding - Windows System Agent and 1Password agent
  lib/client/api.go
  lib/client/keyagent.go
  lib/client/session.go
  lib/sshagent/client.go
  lib/sshagent/client_test.go
  lib/sshagent/clientconn_unix.go
  lib/sshagent/clientconn_windows.go
  lib/sshagent/doc.go
  lib/teleagent/agent.go
  lib/utils/agentconn/agent_unix.go
Labels: backport, size/md

#57537 [v18] MWI: Add Bound Keypair Joining admin and reference guide
  docs/config.json
  docs/pages/machine-workload-identity/machine-id/deployment/deployment.mdx
  docs/pages/reference/cli/tbot.mdx
  docs/pages/reference/join-methods.mdx
  docs/pages/reference/machine-id/bound-keypair/admin-guide.mdx
  docs/pages/reference/machine-id/bound-keypair/bound-keypair.mdx
  docs/pages/reference/machine-id/bound-keypair/concepts.mdx
  docs/pages/reference/machine-id/bound-keypair/getting-started.mdx
  docs/pages/reference/machine-id/machine-id.mdx
Labels: documentation, backport, size/md, no-changelog

#57557 Release 18.1.2
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#57503 [v16] Disallow new uses of gogoproto jsonpb
  .golangci.yml
  api/mfa/mfa.go
  api/types/authentication.go
  api/types/events/struct.go
  api/utils/keys/hardwarekey/attestation.go
  lib/services/local/users.go
  lib/services/plugins.go
  lib/srv/regular/sftp.go
  tool/teleport/common/sftp.go
Labels: backport, size/sm, no-changelog

#57558 [v16] docs: Add a terraform example for `login_rule.traits_expression`
  docs/pages/reference/terraform-provider/resources/login_rule.mdx
  integrations/terraform/examples/resources/teleport_login_rule/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#57559 [v17] docs: Add a terraform example for `login_rule.traits_expression`
  docs/pages/reference/terraform-provider/resources/login_rule.mdx
  integrations/terraform/examples/resources/teleport_login_rule/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#57560 [v18] docs: Add a terraform example for `login_rule.traits_expression`
  docs/pages/reference/terraform-provider/resources/login_rule.mdx
  integrations/terraform/examples/resources/teleport_login_rule/resource.tf
Labels: documentation, backport, size/sm, no-changelog

#56598 feat: JSONPath interpolation for Login Rules (OIDC)
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/loginrule/evaluator.go
Labels: size/md, backport/branch/v18

#57412 [v16] Reduce access point API surface for Authorizer and ConnectionMonitor
  lib/authz/permissions.go
  lib/srv/monitor.go
Labels: backport, size/sm, no-changelog

#57562 [v17] [docs] Entra ID integration
  docs/img/igs/entraid/entra-api-permission.png
  docs/img/igs/entraid/entra-create-enterprise-app.png
  docs/img/igs/entraid/entra-default-owners.png
  docs/img/igs/entraid/entra-finish.png
  docs/img/igs/entraid/entra-setup-oidc.png
  docs/img/igs/entraid/entra-sso-config.png
  docs/pages/identity-governance/entra-id/entra-id.mdx
  docs/pages/identity-governance/entra-id/faq.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/includes/identity-governance/azure-shell.mdx
Labels: documentation, backport, size/md, no-changelog

#57561 [v18] [docs] Entra ID integration
  docs/img/igs/entraid/entra-api-permission.png
  docs/img/igs/entraid/entra-create-enterprise-app.png
  docs/img/igs/entraid/entra-default-owners.png
  docs/img/igs/entraid/entra-finish.png
  docs/img/igs/entraid/entra-setup-oidc.png
  docs/img/igs/entraid/entra-sso-config.png
  docs/pages/identity-governance/entra-id/entra-id.mdx
  docs/pages/identity-governance/entra-id/faq.mdx
  docs/pages/identity-governance/entra-id/getting-started.mdx
  docs/pages/identity-governance/entra-id/manual-installation.mdx
  docs/pages/includes/identity-governance/azure-shell.mdx
Labels: documentation, backport, size/md, no-changelog

#56920 Adding manual encryption key management for encrypted recordings
  api/proto/teleport/legacy/types/types.proto
  api/types/sessionrecording.go
  api/types/sessionrecording_test.go
  api/types/types.pb.go
  docs/pages/reference/terraform-provider/data-sources/session_recording_config.mdx
  docs/pages/reference/terraform-provider/resources/session_recording_config.mdx
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/auth.go
  lib/auth/clusterconfig/clusterconfigv1/service.go
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/gcp_kms.go
  lib/auth/keystore/manager.go
  lib/auth/keystore/pkcs11.go
  lib/auth/keystore/software.go
  lib/auth/recordingencryption/age.go
  lib/auth/recordingencryption/manager.go
  lib/auth/recordingencryption/manager_test.go
  lib/config/configuration.go
  lib/config/fileconf.go
  lib/service/service.go
  lib/services/sessionrecording.go
  lib/services/sessionrecording_test.go
Labels: size/lg, no-changelog

#57518 [v18] Gracefully handle NotFoundError for newly created singleton resources
  integrations/terraform/gen/plural_resource.go.tpl
  integrations/terraform/gen/singular_resource.go.tpl
  integrations/terraform/provider/resource_teleport_access_list.go
  integrations/terraform/provider/resource_teleport_access_monitoring_rule.go
  integrations/terraform/provider/resource_teleport_app.go
  integrations/terraform/provider/resource_teleport_auth_preference.go
  integrations/terraform/provider/resource_teleport_autoupdate_config.go
  integrations/terraform/provider/resource_teleport_autoupdate_version.go
  integrations/terraform/provider/resource_teleport_cluster_maintenance_config.go
  integrations/terraform/provider/resource_teleport_cluster_networking_config.go
  integrations/terraform/provider/resource_teleport_database.go
  integrations/terraform/provider/resource_teleport_device_trust.go
  integrations/terraform/provider/resource_teleport_dynamic_windows_desktop.go
  integrations/terraform/provider/resource_teleport_github_connector.go
  integrations/terraform/provider/resource_teleport_health_check_config.go
  integrations/terraform/provider/resource_teleport_installer.go
  integrations/terraform/provider/resource_teleport_login_rule.go
  integrations/terraform/provider/resource_teleport_oidc_connector.go
  integrations/terraform/provider/resource_teleport_okta_import_rule.go
  integrations/terraform/provider/resource_teleport_provision_token.go
  integrations/terraform/provider/resource_teleport_role.go
  integrations/terraform/provider/resource_teleport_saml_connector.go
  integrations/terraform/provider/resource_teleport_server.go
  integrations/terraform/provider/resource_teleport_session_recording_config.go
  integrations/terraform/provider/resource_teleport_static_host_user.go
  integrations/terraform/provider/resource_teleport_trusted_cluster.go
  integrations/terraform/provider/resource_teleport_user.go
  integrations/terraform/provider/resource_teleport_workload_identity.go
Labels: backport, size/md

#57516 [v18] Fix terraform_autoupdate_version when metadata is non-nil
  integrations/terraform/protoc-gen-terraform-autoupdate.yaml
  integrations/terraform/tfschema/autoupdate/v1/autoupdate_terraform.go
Labels: backport, size/sm

#57580 fix: avoid panic when cloning nil values in cache
  lib/cache/cache_test.go
  lib/cache/cluster_config.go
  lib/cache/plugin_static_credentials_test.go
  lib/cache/tokens.go
  lib/cache/tokens_test.go
  lib/cache/user_group.go
Labels: size/sm, backport/branch/v18

#57570 [v18] feat: JSONPath interpolation for Login Rules
  e_imports.go
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/loginrule/evaluator.go
Labels: backport, size/sm

#57583 [v18] fix: avoid panic when cloning nil values in cache
  lib/cache/cache_test.go
  lib/cache/cluster_config.go
  lib/cache/plugin_static_credentials_test.go
  lib/cache/tokens.go
  lib/cache/tokens_test.go
  lib/cache/user_group.go
Labels: backport, size/sm

#57534 [v17] docs: Fix indent of "enabled" in SSH service reference
  docs/pages/includes/config-reference/ssh-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#57586 Release 18.1.3
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#57532 [v16] FIx potential PATH issue in discovery script
  lib/srv/server/installer/defaultinstallers.go
  lib/srv/server/installer/defaultinstallers_test.go
Labels: backport, size/sm

#57531 [v17] FIx potential PATH issue in discovery script
  lib/srv/server/installer/defaultinstallers.go
  lib/srv/server/installer/defaultinstallers_test.go
Labels: backport, size/sm

#57000 AccessMonitoringRules: Enable resource condition for notification rules
  integrations/access/accessmonitoring/access_monitoring_rules.go
  integrations/access/accessmonitoring/access_monitoring_rules_test.go
Labels: size/sm, backport/branch/v18

#57515 docs: update database access intro for web ui
  docs/pages/connect-your-client/introduction.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57615 [v18] Disable AWSRA profile syncer
  lib/service/service.go
Labels: backport, size/sm, no-changelog

#57622 Release 18.1.4
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#57538 Add new `oidc` subtype for Kubernetes joining
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-provisiontokens.mdx
  docs/pages/reference/terraform-provider/data-sources/provision_token.mdx
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/auth.go
  lib/auth/join_kubernetes.go
  lib/kube/token/validator.go
  lib/kube/token/validator_test.go
Labels: documentation, kubernetes-access, helm, size/md, backport/branch/v17, backport/branch/v18

#57533 [v18] docs: Fix indent of "enabled" in SSH service reference
  docs/pages/includes/config-reference/ssh-service.yaml
Labels: documentation, backport, size/sm, no-changelog

#57540 [v18] [docs][AWSIC] Adds a guide for using IC-granted permissions with AWS CLI
  docs/cspell.json
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/aws-iam-identity-center.mdx
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/using-aws-cli.mdx
Labels: documentation, backport, size/md, no-changelog

#57260 [tctl/top] Add raw metrics view
  go.mod
  go.sum
  tool/tctl/common/top/box.go
  tool/tctl/common/top/keys.go
  tool/tctl/common/top/metrics.go
  tool/tctl/common/top/model.go
  tool/tctl/common/top/report.go
Labels: tctl, size/md, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57593 chore: Bump Buf to v1.56.0
  build.assets/versions.mk
  gen/proto/ts/google/protobuf/descriptor_pb.ts
Labels: size/sm, no-changelog

#56932 [Web] Use serverside pagination for Users in the Web UI
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  api/types/user.go
  lib/web/apiserver.go
  lib/web/users.go
  lib/web/users_test.go
  web/packages/teleport/src/Users/UserAddEdit/UserAddEdit.story.tsx
  web/packages/teleport/src/Users/UserAddEdit/UserAddEdit.tsx
  web/packages/teleport/src/Users/UserDelete/UserDelete.story.tsx
  web/packages/teleport/src/Users/UserDelete/UserDelete.tsx
  web/packages/teleport/src/Users/UserList/UserList.tsx
  web/packages/teleport/src/Users/Users.story.tsx
  web/packages/teleport/src/Users/Users.test.tsx
  web/packages/teleport/src/Users/Users.tsx
  web/packages/teleport/src/Users/useUsers.ts
  web/packages/teleport/src/config.ts
  web/packages/teleport/src/services/user/user.ts
  web/packages/teleport/src/test/helpers/users.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57566 Fix Admonition
  docs/pages/admin-guides/management/guides/aws-iam-identity-center/using-aws-cli.mdx
Labels: documentation, size/sm, no-changelog

#57607 docs: fix join tokens page content
  docs/pages/enroll-resources/agents/join-token.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#54315 Add links between Azure protection guides
  docs/pages/enroll-resources/application-access/cloud-apis/azure.mdx
  docs/pages/identity-governance/idps/saml-microsoft-entra-external-id.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#57460 Database MCP server to support CockroachDB databases
  lib/client/db/postgres/mcp/mcp.go
  lib/player/player.go
  lib/service/service.go
  tool/tsh/common/mcp_db.go
  tool/tsh/common/mcp_db_test.go
Labels: tsh, size/sm, backport/branch/v18

#57600 Allow ignoring errors in `tctl workload-identity x509-issuer-overrides sign-csrs`
  docs/pages/reference/workload-identity/issuer-override.mdx
  tool/tctl/common/workload_identity_command.go
  tool/tctl/common/workload_identity_command_overrides_test.go
Labels: documentation, tctl, size/sm, backport/branch/v17, backport/branch/v18

#57632 [v18] [tctl/top] Add raw metrics view
  go.mod
  go.sum
  tool/tctl/common/top/box.go
  tool/tctl/common/top/keys.go
  tool/tctl/common/top/metrics.go
  tool/tctl/common/top/model.go
  tool/tctl/common/top/report.go
Labels: tctl, backport, size/md

#57634 [v17] [tctl/top] Add raw metrics view
  go.mod
  go.sum
  tool/tctl/common/top/box.go
  tool/tctl/common/top/keys.go
  tool/tctl/common/top/metrics.go
  tool/tctl/common/top/model.go
  tool/tctl/common/top/report.go
Labels: tctl, backport, size/md

#56714 Support cluster level KMS key filtering during deletion
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/aws_kms_test.go
  lib/auth/keystore/manager.go
Labels: size/md, backport/branch/v18

#57667 Introduce 'GetStaticTokens' RPC
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/auth/tls_test.go
  lib/cache/tokens.go
  lib/cache/tokens_test.go
  lib/services/configuration.go
  lib/services/local/configuration.go
  lib/services/local/suite_test.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57608 Enhance the Windows desktop session start audit event
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/events/events_test.go
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_test.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/client_nop.go
  lib/srv/desktop/rdp/rdpclient/client_test.go
  lib/srv/desktop/windows_server.go
  lib/tlsca/ca.go
Labels: rdp, desktop-access, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57643 [cache] fix empty apps spans
  lib/cache/app.go
Labels: size/sm, no-changelog, backport/branch/v18

#52529 RFD for official SELinux policy for SSH agents
  rfd/0208-selinux-policy.md
  rfd/cspell.json
Labels: rfd, size/sm, no-changelog

#57624 [v18] web player: make query parameters optional
  lib/web/tty_playback.go
  web/packages/teleport/src/Player/Player.tsx
  web/packages/teleport/src/services/recordings/recordings.ts
Labels: ui, backport, size/sm, no-changelog

#57665 Introduce paginated 'ListResetPasswordTokens' RPC
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/auth/tls_test.go
  lib/auth/usertoken.go
  lib/auth/usertoken_test.go
  lib/services/identity.go
  lib/services/local/usertoken.go
  lib/services/local/usertoken_test.go
Labels: size/md, no-changelog, backport/branch/v17, backport/branch/v18

#57563 fix(web): Bot details instance spacing
  web/packages/design/src/Label/Label.tsx
  web/packages/design/src/ResourceIcon/assets/oracle.svg
  web/packages/design/src/ResourceIcon/assets/strapi.svg
  web/packages/design/src/ResourceIcon/icons.ts
  web/packages/design/src/ResourceIcon/index.tsx
  web/packages/design/src/ResourceIcon/resourceIconSpecs.ts
  web/packages/teleport/src/Bots/Details/BotDetails.story.tsx
  web/packages/teleport/src/Bots/Details/BotDetails.tsx
  web/packages/teleport/src/Bots/Details/Instance.story.tsx
  web/packages/teleport/src/Bots/Details/Instance.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.story.tsx
  web/packages/teleport/src/Bots/Details/InstancesPanel.tsx
  web/packages/teleport/src/Bots/Details/JoinMethodIcon.tsx
  web/packages/teleport/src/Bots/Details/Panel.tsx
Labels: ui, machine-id, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57661 [v17] Allow ignoring errors in `tctl workload-identity x509-issuer-overrides sign-csrs`
  docs/pages/reference/workload-identity/issuer-override.mdx
  tool/tctl/common/workload_identity_command.go
  tool/tctl/common/workload_identity_command_overrides_test.go
Labels: documentation, tctl, backport, size/sm

#57662 [v18] Allow ignoring errors in `tctl workload-identity x509-issuer-overrides sign-csrs`
  docs/pages/reference/workload-identity/issuer-override.mdx
  tool/tctl/common/workload_identity_command.go
  tool/tctl/common/workload_identity_command_overrides_test.go
Labels: documentation, tctl, backport, size/sm

#57682 [v16] [buddy] chore: Accept 204 from FluentD responses
  integrations/event-handler/fluentd_client.go
Labels: backport, size/sm

#57619 [v17] CTMU documentation update (multi-cluster and multi-version caching support)
  docs/config.json
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/client-tools-autoupdate.mdx
  docs/pages/upgrading/client-tools-managed-updates.mdx
  docs/pages/upgrading/upgrading.mdx
  docs/sidebar.json
Labels: documentation, backport, size/md, no-changelog

#57618 [v18] CTMU documentation update (multi-cluster and multi-version caching support)
  docs/config.json
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/client-tools-autoupdate.mdx
  docs/pages/upgrading/client-tools-managed-updates.mdx
  docs/pages/upgrading/upgrading.mdx
  docs/sidebar.json
Labels: documentation, backport, size/md, no-changelog

#57705 Update `tmp` dependency to 0.2.4
  pnpm-lock.yaml
Labels: size/sm, no-changelog, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57642 [v16] docs: fix join tokens page content
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/join-token.mdx
Labels: documentation, backport, size/sm, no-changelog

#57640 [v18] docs: fix join tokens page content
  docs/pages/enroll-resources/agents/join-token.mdx
Labels: documentation, backport, size/sm, no-changelog

#57700 Add CI check for `pnpm process-icons`
  .github/workflows/lint.yaml
  Makefile
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57708 fix(web): Oracle brand icon
  web/packages/design/src/ResourceIcon/assets/oracle.svg
Labels: ui, size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57679 [v16] Enhance the Windows desktop session start audit event
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/events/events_test.go
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_test.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/client_nop.go
  lib/srv/desktop/windows_server.go
  lib/tlsca/ca.go
Labels: rdp, audit-log, backport, desktop-access, size/sm

#57680 [v18] [buddy] chore: Accept 204 from FluentD responses
  integrations/event-handler/fluentd_client.go
Labels: backport, size/sm

#57626 [v16] web player: make query parameters optional
  lib/web/tty_playback.go
  web/packages/teleport/src/Player/Player.tsx
  web/packages/teleport/src/services/recordings/recordings.ts
Labels: ui, backport, size/sm, no-changelog

#57676 [v18] Enhance the Windows desktop session start audit event
  api/proto/teleport/legacy/types/events/events.proto
  api/types/events/events.pb.go
  lib/events/events_test.go
  lib/srv/desktop/audit.go
  lib/srv/desktop/audit_test.go
  lib/srv/desktop/rdp/rdpclient/client.go
  lib/srv/desktop/rdp/rdpclient/client_common.go
  lib/srv/desktop/rdp/rdpclient/client_nop.go
  lib/srv/desktop/rdp/rdpclient/client_test.go
  lib/srv/desktop/windows_server.go
  lib/tlsca/ca.go
Labels: rdp, audit-log, backport, desktop-access, size/sm

#57683 [v18] Add new `oidc` subtype for Kubernetes joining (#57538)
  api/proto/teleport/legacy/types/types.proto
  api/types/provisioning.go
  api/types/provisioning_test.go
  api/types/types.pb.go
  docs/pages/reference/operator-resources/resources-teleport-dev-provisiontokens.mdx
  docs/pages/reference/terraform-provider/data-sources/provision_token.mdx
  docs/pages/reference/terraform-provider/resources/provision_token.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/operator-crds/resources.teleport.dev_provisiontokens.yaml
  integrations/operator/config/crd/bases/resources.teleport.dev_provisiontokens.yaml
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/auth.go
  lib/auth/join_kubernetes.go
  lib/kube/token/validator.go
  lib/kube/token/validator_test.go
Labels: documentation, kubernetes-access, helm, backport, size/lg

#57718 Deprecate GetTokens and use paginated token API
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/cache/tokens.go
  lib/services/local/provisioning.go
  lib/services/local/suite_test.go
  lib/services/provisioning.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  tool/tctl/common/bots_command_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/token_command.go
Labels: tctl, size/md

#57051 Fix kube port-forward to exit on pod removal
  integration/kube_integration_test.go
  lib/kube/proxy/portforward_spdy.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/portforward_websocket.go
Labels: bug, kubernetes-access, size/sm, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57207 Attempt to fix hostid collision issue
  integrations/event-handler/go.sum
  lib/auth/storage/storage.go
  lib/auth/storage/storage_test.go
  lib/auth/storage/storage_unix.go
  lib/backend/kubernetes/kubernetes.go
  lib/backend/kubernetes/kubernetes_test.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/utils/hostid/hostid.go
  lib/versioncontrol/upgradewindow/upgradewindow.go
  lib/versioncontrol/upgradewindow/upgradewindow_test.go
Labels: kubernetes-access, size/md, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57474 Fix kube port-forward race with multiple ports
  lib/kube/proxy/forwarder.go
  lib/kube/proxy/portforward_test.go
  lib/kube/proxy/testing/kube_server/kube_mock.go
  lib/kube/proxy/utils_test.go
Labels: bug, kubernetes-access, size/sm, size/md, backport/branch/v16, backport/branch/v17, backport/branch/v18

#57601 Fix the test auth server's upload handler
  lib/auth/authtest/authtest.go
Labels: size/sm, no-changelog, backport/branch/v18

#57479 [v16] ci: Move lint-ui workflow into common lint workflow
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/lint.yaml
Labels: backport, size/sm, no-changelog

#57477 [v18] ci: Move lint-ui workflow into common lint workflow
  .github/workflows/lint-ui-bypass.yaml
  .github/workflows/lint-ui.yaml
  .github/workflows/lint.yaml
Labels: backport, size/sm, no-changelog

#57716 [v16] Update `tmp` dependency to 0.2.4
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog

#57508 Add protobuf definitions for storing and retrieving session summaries
  api/gen/proto/go/teleport/summarizer/v1/summarizer.pb.go
  api/gen/proto/go/teleport/summarizer/v1/summarizer_service.pb.go
  api/gen/proto/go/teleport/summarizer/v1/summarizer_service_grpc.pb.go
  api/proto/teleport/summarizer/v1/summarizer.proto
  api/proto/teleport/summarizer/v1/summarizer_service.proto
Labels: size/sm, no-changelog, backport/branch/v18

#57734 [v17] HostID collision bugfix
  integrations/event-handler/go.sum
  lib/auth/storage/storage.go
  lib/auth/storage/storage_test.go
  lib/auth/storage/storage_unix.go
  lib/backend/kubernetes/kubernetes.go
  lib/backend/kubernetes/kubernetes_test.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/utils/hostid/hostid.go
  lib/versioncontrol/upgradewindow/upgradewindow.go
  lib/versioncontrol/upgradewindow/upgradewindow_test.go
Labels: backport, size/sm, no-changelog

#57710 [v18] Add new AWS resource icons
  web/packages/design/src/ResourceIcon/assets/awsaurora.svg
  web/packages/design/src/ResourceIcon/assets/awscommandlineinterface.svg
  web/packages/design/src/ResourceIcon/assets/awsdynamodb.svg
  web/packages/design/src/ResourceIcon/assets/awsec2.svg
  web/packages/design/src/ResourceIcon/assets/awselasticache.svg
  web/packages/design/src/ResourceIcon/assets/awselasticblockstore.svg
  web/packages/design/src/ResourceIcon/assets/awselasticcontainerservice.svg
  web/packages/design/src/ResourceIcon/assets/awselasticsearchservice.svg
  web/packages/design/src/ResourceIcon/assets/awsfargate.svg
  web/packages/design/src/ResourceIcon/assets/awsiamidentitycenter.svg
  web/packages/design/src/ResourceIcon/assets/awsidentityandaccessmanagementiam.svg
  web/packages/design/src/ResourceIcon/assets/awskeyspaces.svg
  web/packages/design/src/ResourceIcon/assets/awsmanagementconsole.svg
  web/packages/design/src/ResourceIcon/assets/awsmemorydb.svg
  web/packages/design/src/ResourceIcon/assets/awsrds.svg
  web/packages/design/src/ResourceIcon/assets/awsredshift.svg
  web/packages/design/src/ResourceIcon/assets/awsredshift2.svg
  web/packages/design/src/ResourceIcon/assets/awssimplestorageservices3.svg
  web/packages/design/src/ResourceIcon/assets/awssinglesignon.svg
  web/packages/design/src/ResourceIcon/icons.ts
  web/packages/design/src/ResourceIcon/resourceIconSpecs.ts
Labels: ui, backport, size/sm, no-changelog

#57549 [v16] Edit the Teleport Cloud architecture guide
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, backport, size/sm, no-changelog

#57548 [v17] Edit the Teleport Cloud architecture guide
  docs/pages/reference/architecture/teleport-cloud-architecture.mdx
Labels: documentation, backport, size/sm, no-changelog

#57671 [v18] Support cluster level KMS key filtering during deletion
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform-mwi/go.mod
  integrations/terraform-mwi/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/auth/keystore/aws_kms.go
  lib/auth/keystore/aws_kms_test.go
  lib/auth/keystore/manager.go
Labels: backport, size/md

#57707 Update discover finished view to accept custom messages
  web/packages/teleport/src/Discover/Shared/Finished/Finished.story.tsx
  web/packages/teleport/src/Discover/Shared/Finished/Finished.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v18

#57735 [v16] HostID collision bugfix
  integrations/event-handler/go.sum
  lib/auth/storage/storage.go
  lib/auth/storage/storage_test.go
  lib/auth/storage/storage_unix.go
  lib/backend/kubernetes/kubernetes.go
  lib/backend/kubernetes/kubernetes_test.go
  lib/service/service.go
  lib/service/service_test.go
  lib/srv/regular/sshserver.go
  lib/srv/regular/sshserver_test.go
  lib/utils/hostid/hostid.go
  lib/versioncontrol/upgradewindow/upgradewindow.go
  lib/versioncontrol/upgradewindow/upgradewindow_test.go
Labels: backport, size/sm, no-changelog

#57746 [v17] Add CI check for `pnpm process-icons`
  .github/workflows/lint.yaml
  Makefile
  web/packages/design/src/ResourceIcon/assets/strapi.svg
Labels: backport, size/sm, no-changelog

#57758 [v17] SCIM: Add bearer token creds support for SCIM Plugin
  tool/tctl/common/plugin/plugins_command.go
  tool/tctl/common/plugin/scim.go
Labels: tctl, backport, size/sm

#57754 Adding New Searchbar Header to Docs Homepage
  docs/pages/index.mdx
Labels: documentation, size/sm, no-changelog

#57772 [v18] Paginate GetTokens RPC
  api/client/client.go
  api/client/proto/authservice.pb.go
  api/client/proto/authservice_grpc.pb.go
  api/proto/teleport/legacy/client/proto/authservice.proto
  lib/auth/auth.go
  lib/auth/auth_test.go
  lib/auth/auth_with_roles.go
  lib/auth/authclient/api.go
  lib/auth/authclient/clt.go
  lib/auth/grpcserver.go
  lib/auth/tls_test.go
  lib/auth/usertoken.go
  lib/auth/usertoken_test.go
  lib/cache/tokens.go
  lib/cache/tokens_test.go
  lib/services/configuration.go
  lib/services/identity.go
  lib/services/local/configuration.go
  lib/services/local/provisioning.go
  lib/services/local/suite_test.go
  lib/services/local/usertoken.go
  lib/services/local/usertoken_test.go
  lib/services/provisioning.go
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  tool/tctl/common/bots_command_test.go
  tool/tctl/common/resource_command.go
  tool/tctl/common/token_command.go
Labels: tctl, backport, size/md

#57792 [v18] remove process.Config.HostUUID ref from service init functions
  lib/service/service.go
Labels: backport, size/sm, no-changelog

#57759 [v18] SCIM: Add bearer token creds support for SCIM Plugin
  tool/tctl/common/plugin/plugins_command.go
  tool/tctl/common/plugin/scim.go
Labels: tctl, backport, size/sm

#57222 [v18] Device Trust: add `required-for-humans` mode
  .github/ISSUE_TEMPLATE/testplan.md
  api/constants/constants.go
  api/proto/teleport/legacy/types/types.proto
  api/types/authentication.go
  api/types/authentication_authpreference_test.go
  api/types/types.pb.go
  docs/pages/identity-governance/device-trust/device-trust.mdx
  docs/pages/identity-governance/device-trust/enforcing-device-trust.mdx
  docs/pages/includes/config-reference/auth-service.yaml
  docs/pages/includes/role-spec.mdx
  docs/pages/reference/access-controls/roles.mdx
  docs/pages/reference/terraform-provider/data-sources/auth_preference.mdx
  docs/pages/reference/terraform-provider/resources/auth_preference.mdx
  integrations/terraform/tfschema/types_terraform.go
  lib/auth/auth.go
  lib/auth/grpcserver_test.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/devicetrust/authz/authz.go
  lib/devicetrust/authz/authz_test.go
  lib/devicetrust/authz/trusted_device_requirement.go
  lib/devicetrust/authz/trusted_device_requirement_test.go
  lib/services/role.go
  lib/services/role_test.go
  lib/srv/db/common/session.go
  lib/srv/db/common/session_test.go
  lib/srv/mcp/session.go
  lib/srv/session_control_test.go
  lib/sshca/identity.go
  lib/tbot/tbot_test.go
  lib/tlsca/ca.go
Labels: documentation, database-access, backport, machine-id, size/md

#57813 docs: include mcp server name in tsh mcp config example
  docs/pages/enroll-resources/mcp-access/getting-started.mdx
  docs/pages/enroll-resources/mcp-access/stdio.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#57824 Helm: add kube joining support to teleport-kube-agent chart (#57603)
  docs/pages/includes/helm-reference/zz_generated.teleport-kube-agent.mdx
  examples/chart/teleport-cluster/charts/teleport-operator/templates/_helpers.tpl
  examples/chart/teleport-kube-agent/templates/statefulset.yaml
  examples/chart/teleport-kube-agent/tests/statefulset_test.yaml
  examples/chart/teleport-kube-agent/values.schema.json
  examples/chart/teleport-kube-agent/values.yaml
Labels: documentation, helm, backport, size/md

#57795 [v18] Fix error management for secret creating in kube backend.
  lib/backend/kubernetes/kubernetes.go
Labels: backport, size/sm, no-changelog

#57820 [v17] followup: Remove `lib/teleagent` aliases
  lib/teleagent/alias.go
Labels: backport, size/sm, no-changelog

#54463 RFD 212: JSONPath interpolation
  rfd/0212-jsonpath-interpolation.md
  rfd/cspell.json
Labels: rfd, size/lg, no-changelog

#57825 [v18] docs: include mcp server name in tsh mcp config example
  docs/pages/enroll-resources/mcp-access/getting-started.mdx
  docs/pages/enroll-resources/mcp-access/stdio.mdx
Labels: documentation, backport, size/sm, no-changelog

#57797 [v18] Web: fix access request checkout layout
  web/packages/teleport/src/Main/Main.tsx
Labels: ui, backport, size/sm

#57727 Improve development environment setup instructions 👨🏾‍💻 ✍🏾 📜
  BUILD_macos.md
  Makefile
  README.md
Labels: documentation, size/sm, no-changelog, developer-experience

#57837 [v17] build: automatically install buf if it is not already installed
  Makefile
Labels: backport, size/sm, no-changelog

#57836 [v18] build: automatically install buf if it is not already installed
  Makefile
Labels: backport, size/sm, no-changelog

#55272 [v18] make session ID env vars agree
  integration/integration_test.go
  lib/client/client_test.go
  lib/client/session.go
  lib/srv/ctx.go
  lib/srv/ctx_test.go
  lib/srv/exec_linux_test.go
  lib/srv/exec_test.go
  lib/srv/mock_test.go
  lib/sshutils/ctx.go
  lib/web/apiserver.go
Labels: backport, size/sm

#57721 [v17] Fix unlink package for every version w/ and w/o `teleport-update`
  examples/systemd/before-remove
Labels: backport, size/sm

#57850 [v18] Remove OmitCDP flag for db certs in PKINIT flow
  lib/srv/db/common/kerberos/kinit/kinit.go
  lib/srv/db/common/kerberos/kinit/kinit_test.go
  lib/srv/db/common/kerberos/kinit/ldap_test.go
Labels: database-access, backport, size/sm

#57839 Deflake Test_formatDatabaseRolesForDB
  tool/tsh/common/db_print.go
Labels: tsh, size/sm, no-changelog

#57019 [v18] MWI: Refactor identity impersonation
  lib/tbot/client/builder.go
  lib/tbot/identity/generator.go
  lib/tbot/output_utils.go
  lib/tbot/service_application_output.go
  lib/tbot/service_application_tunnel.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_database_tunnel.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_spiffe_svid_output.go
  lib/tbot/service_spiffe_workload_api.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/service_workload_identity_api.go
  lib/tbot/service_workload_identity_aws_ra.go
  lib/tbot/service_workload_identity_jwt.go
  lib/tbot/service_workload_identity_x509.go
  lib/tbot/tbot.go
Labels: backport, machine-id, size/md, no-changelog

#57848 fix(web): Join tokens "access denied" with MFA
  web/packages/teleport/src/services/joinToken/joinToken.ts
Labels: ui, size/sm, no-changelog, backport/branch/v18

#57838 [v16] build: automatically install buf if it is not already installed
  Makefile
Labels: backport, size/sm, no-changelog

#57687 Bound Keypair: Fix lock generation on sequence desync
  lib/auth/join_bound_keypair.go
  lib/auth/join_bound_keypair_test.go
Labels: security, machine-id, size/md, backport/branch/v18

#57575 don't fallback to loading user roles from backend on empty tls groups
  lib/auth/auth.go
  lib/auth/auth_with_roles.go
  lib/auth/auth_with_roles_test.go
  lib/auth/authtest/authtest.go
  lib/authz/permissions.go
  lib/authz/permissions_test.go
  lib/services/access_checker.go
  lib/srv/mcp/helpers_test.go
Labels: size/sm, no-changelog, backport/branch/v17, backport/branch/v18

#57278 Add details for EC2 discovery docs
  docs/pages/enroll-resources/auto-discovery/servers/azure-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery-guided.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery-manual.mdx
  docs/pages/enroll-resources/auto-discovery/servers/ec2-discovery/ec2-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/gcp-discovery.mdx
  docs/pages/enroll-resources/auto-discovery/servers/servers.mdx
  docs/pages/includes/auto-discovery/ec2-config.mdx
  docs/pages/includes/auto-discovery/ec2-cross-account-config.mdx
  docs/pages/includes/auto-discovery/ec2-cross-account-token.mdx
  docs/pages/includes/auto-discovery/ec2-invite-token.mdx
  docs/pages/includes/auto-discovery/ec2-next-steps.mdx
  docs/pages/includes/auto-discovery/ec2-troubleshooting.mdx
  docs/pages/includes/database-access/alternative-methods-join.mdx
  docs/pages/includes/server-access/custom-installer-aws.yaml
  docs/pages/includes/server-access/custom-installer-azure.yaml
  docs/pages/includes/server-access/custom-installer-gcp.yaml
  docs/pages/includes/server-access/custom-installer.mdx
  docs/pages/zero-trust-access/api/automatically-register-agents.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v18

#57784 [v18] Enable Managed Updates when adding new Kubernetes agents
  tool/tctl/common/kube_command.go
Labels: tctl, backport, size/sm
