Repository gravitational/teleport, pull requests merged in 2025-03, with the labels that each got.

#52632 [v15] Update `tctl` reference docs with autoupdate commands
  docs/pages/reference/cli/tctl.mdx
  docs/pages/upgrading/client-tools-autoupdate.mdx
  tool/tctl/common/autoupdate_command.go
Labels: documentation, tctl, backport, size/sm, no-changelog

#52525 Added 02/26 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#52582 [v17] Add OCI tags docs
  docs/cspell.json
  docs/pages/admin-guides/management/guides/oracle-tags.mdx
Labels: documentation, backport, size/sm, no-changelog

#52647 docs: update tctl autoupdate agents status command ref
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#52672 [v17] docs: update tctl autoupdate agents status command ref
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#52674 Fix spelling identity center assignment permission set desc
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/reference/terraform-provider/data-sources/app.mdx
  docs/pages/reference/terraform-provider/resources/app.mdx
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, size/sm, no-changelog, backport/branch/v17

#52550 Integration Stats: return open user tasks per task type
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/integration.go
Labels: size/sm, no-changelog, backport/branch/v17

#52639 [v15] Update Platform name in cli to Teleport Infrastructure Identity Platform
  tool/tctl/common/usage.go
  tool/teleport/common/teleport.go
Labels: tctl, backport, size/sm, no-changelog

#52638 [v16] Update Platform name in cli to Teleport Infrastructure Identity Platform
  tool/tctl/common/usage.go
  tool/teleport/common/teleport.go
Labels: tctl, backport, size/sm, no-changelog

#52675 Spell fixes for logs and descriptions
  integrations/event-handler/cli.go
  integrations/kube-agent-updater/cmd/teleport-kube-agent-updater/main.go
  lib/backend/etcdbk/etcd.go
  lib/bpf/bpf.go
  lib/events/athena/athena.go
  lib/events/session_writer.go
Labels: bpf, audit-log, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52579 Improve perf on label key validation
  api/types/common/common.go
  api/types/common/common_test.go
  api/types/resource.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52637 [v17] Update Platform name in cli to Teleport Infrastructure Identity Platform
  tool/tctl/common/usage.go
  tool/teleport/common/teleport.go
Labels: tctl, backport, size/sm, no-changelog

#52677 [v17] Fix spelling identity center assignment permission set desc
  api/proto/teleport/legacy/types/types.proto
  api/types/types.pb.go
  docs/pages/reference/terraform-provider/data-sources/app.mdx
  docs/pages/reference/terraform-provider/resources/app.mdx
  integrations/terraform/tfschema/types_terraform.go
Labels: documentation, backport, size/sm, no-changelog

#52526 Workload ID: Document Support for Predicate Language
  docs/pages/reference/workload-identity/attributes.mdx
  docs/pages/reference/workload-identity/workload-identity-resource.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16

#52564 [v17] Workload ID: Support Predicate Language
  api/gen/proto/go/teleport/workloadidentity/v1/attrs.pb.go
  api/gen/proto/go/teleport/workloadidentity/v1/resource.pb.go
  api/proto/teleport/workloadidentity/v1/attrs.proto
  api/proto/teleport/workloadidentity/v1/resource.proto
  docs/pages/reference/terraform-provider/data-sources/workload_identity.mdx
  docs/pages/reference/terraform-provider/resources/workload_identity.mdx
  integrations/terraform/tfschema/workloadidentity/v1/resource_terraform.go
  lib/auth/machineid/workloadidentityv1/decision.go
  lib/auth/machineid/workloadidentityv1/decision_test.go
  lib/auth/machineid/workloadidentityv1/expression/evaluate.go
  lib/auth/machineid/workloadidentityv1/expression/evaluate_test.go
  lib/auth/machineid/workloadidentityv1/expression/expression.go
  lib/auth/machineid/workloadidentityv1/expression/proto.go
  lib/auth/machineid/workloadidentityv1/expression/template.go
  lib/auth/machineid/workloadidentityv1/expression/template_test.go
  lib/auth/machineid/workloadidentityv1/issuer_service.go
  lib/auth/machineid/workloadidentityv1/workloadidentityv1_test.go
  lib/services/workload_identity.go
  lib/services/workload_identity_test.go
Labels: documentation, backport, size/lg

#52687 [v17] Improve perf on label key validation
  api/types/common/common.go
  api/types/common/common_test.go
  api/types/resource.go
Labels: backport, size/sm, no-changelog

#52688 [v16] Improve perf on label key validation
  api/types/common/common.go
  api/types/common/common_test.go
  api/types/resource.go
Labels: backport, size/sm, no-changelog

#52689 [v15] Improve perf on label key validation
  api/types/common/common.go
  api/types/common/common_test.go
  api/types/resource.go
Labels: backport, size/sm, no-changelog

#52646 Set the autoupdate singleton names
  tool/tctl/common/resource_command.go
Labels: tctl, size/sm, backport/branch/v17

#52671 Remove unnecessary keysIn helper
  api/utils/slices.go
  api/utils/slices_test.go
  lib/auth/init_test.go
  lib/srv/db/common/databaseobjectimportrule/apply.go
Labels: size/sm, no-changelog

#52572 Clear role diff attempt on role editor close
  web/packages/teleport/src/Roles/Roles.tsx
Labels: ui, backport-required, size/sm, no-changelog, backport/branch/v17

#52585 [v17] [17.2.7] bump cloud docs
  docs/config.json
Labels: documentation, backport, size/sm, no-changelog

#52691 Fix a flaky role editor test
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.test.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#52350 Escape labels on Node Join scripts
  lib/web/join_tokens_test.go
  lib/web/scripts/install_node.go
  lib/web/scripts/node-join/install.sh
Labels: size/md, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52680 [v17] Improve perf on backend key validation
  lib/backend/sanitize.go
  lib/backend/sanitize_test.go
Labels: backport, size/sm, no-changelog

#52694 [v17] Correct the changelog entry for 17.2.7
  CHANGELOG.md
Labels: backport, size/sm, no-changelog

#52523 [v16] Re-use the parent logger where available
  lib/srv/app/server.go
Labels: kubernetes-access, application-access, backport, size/sm, no-changelog

#52522 [v17] Re-use the parent logger where available
  lib/srv/app/server.go
Labels: kubernetes-access, application-access, backport, size/sm, no-changelog

#51832 Add version incompatibility warning to Connect
  docs/pages/connect-your-client/teleport-connect.mdx
  gen/proto/go/teleport/lib/teleterm/v1/auth_settings.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  lib/client/api.go
  lib/client/api_test.go
  lib/teleterm/apiserver/handler/handler.go
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/clusters/cluster_auth.go
  lib/utils/ver.go
  proto/teleport/lib/teleterm/v1/auth_settings.proto
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLoginReason.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/CompatibilityWarning.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/FormSso.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/storyHelpers.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/clusters/types.ts
Labels: ui, size/md, backport/branch/v17

#52681 [v17] Integration Stats: return open user tasks per task type
  lib/web/integrations.go
  lib/web/integrations_test.go
  lib/web/ui/integration.go
Labels: backport, size/sm, no-changelog

#52685 [v16] Spell fixes for logs and descriptions
  integrations/event-handler/cli.go
  lib/events/athena/athena.go
Labels: audit-log, backport, size/sm, no-changelog

#52698 [v17] Escape labels on Node Join scripts
  lib/web/join_tokens_test.go
  lib/web/scripts/install_node.go
  lib/web/scripts/node-join/install.sh
Labels: backport, size/md

#52018 [v17] Oracle join method - Add docs
  docs/cspell.json
  docs/img/oracle/oracle-join-dynamic-group@2x.png
  docs/img/oracle/oracle-join-policy@2x.png
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/join-services-to-your-cluster.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/oracle.mdx
  docs/pages/includes/provision-token/oracle-spec.mdx
  docs/pages/reference/join-methods.mdx
Labels: documentation, backport, size/md, no-changelog

#52513 Log in warn level when updating DiscoveryConfigStatus fails
  lib/srv/discovery/status.go
Labels: size/sm, discovery, no-changelog, backport/branch/v16, backport/branch/v17

#52703 Fix RPM linking logic
  build.assets/build-package.sh
  examples/systemd/before-remove
Labels: size/sm

#52704 [v17] Fix RPM linking logic
  build.assets/build-package.sh
  examples/systemd/before-remove
Labels: backport, size/sm

#52715 Release 17.3.1
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#52696 [v17] Clear role diff attempt on role editor close
  web/packages/teleport/src/Roles/Roles.tsx
Labels: ui, backport, size/sm, no-changelog

#52700 [v17] Support setting app public-addr within Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery

#52496 [v17] Machine ID: Add Prometheus metrics for loop tasks
  lib/tbot/loop.go
  lib/tbot/service_application_output.go
  lib/tbot/service_bot_identity.go
  lib/tbot/service_client_credential.go
  lib/tbot/service_database_output.go
  lib/tbot/service_heartbeat.go
  lib/tbot/service_identity_output.go
  lib/tbot/service_kubernetes_output.go
  lib/tbot/service_kubernetes_v2_output.go
  lib/tbot/service_ssh_host_output.go
  lib/tbot/service_ssh_multiplexer.go
  lib/tbot/tbot.go
Labels: backport, machine-id, size/sm

#52707 [v16] Use structured error responses from servicenow and opsgenie (#52434)
  integrations/access/common/response.go
  integrations/access/opsgenie/client.go
  integrations/access/opsgenie/types.go
  integrations/access/servicenow/client.go
  integrations/access/servicenow/types.go
Labels: backport, size/sm, no-changelog

#52629 [v17] Use structured error responses from servicenow and opsgenie (#52434)
  integrations/access/common/response.go
  integrations/access/opsgenie/client.go
  integrations/access/opsgenie/types.go
  integrations/access/servicenow/client.go
  integrations/access/servicenow/types.go
  integrations/event-handler/go.sum
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#52664 docs: update hardware key guide
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52559 docs: update Teleport port to 443 in db examples
  docs/pages/enroll-resources/database-access/enroll-aws-databases/postgres-redshift.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-redis.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52583 docs: remove unsupported version ref for azure sql server
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-sql-server-ad.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52737 [v17] docs: update Teleport db port example and remove unsupported license ref in Azure db
  docs/pages/enroll-resources/database-access/enroll-aws-databases/postgres-redshift.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-redis.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-sql-server-ad.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, backport, size/sm, no-changelog

#52738 [v16] docs: update Teleport db port example and remove unsupported license ref in Azure db
  docs/pages/enroll-resources/database-access/enroll-aws-databases/postgres-redshift.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-redis.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-sql-server-ad.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, backport, size/sm, no-changelog

#52739 [v15] docs: update Teleport db port example and remove unsupported license ref in Azure db
  docs/pages/enroll-resources/database-access/enroll-aws-databases/postgres-redshift.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-redis.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-sql-server-ad.mdx
  docs/pages/reference/agent-services/database-access-reference/cli.mdx
Labels: documentation, backport, size/sm, no-changelog

#52735 [v15] docs: update hardware key guide
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
Labels: documentation, backport, size/sm, no-changelog

#52734 [v16] docs: update hardware key guide
  docs/pages/admin-guides/access-controls/guides/hardware-key-support.mdx
Labels: documentation, backport, size/sm, no-changelog

#52678 Improve readability of Managed Updates docs intro
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, size/sm, no-changelog

#52750 Remove the check-redirects script
  docs/check-redirects/README.md
  docs/check-redirects/check-redirects.js
  docs/check-redirects/check-redirects.test.js
  docs/check-redirects/index.js
  docs/check-redirects/package.json
  docs/check-redirects/pnpm-lock.yaml
  docs/check-redirects/pnpm-workspace.yaml
  jest.config.js
Labels: no-changelog, backport/branch/v17

#52725 [teleport-update] Set umask 0022 for teleport-update to avoid errors on enable
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: size/sm, backport/branch/v17

#52751 [v17] Set the autoupdate singleton names
  tool/tctl/common/resource_command.go
Labels: tctl, backport, size/sm

#52621 docs: add troubleshoting for missing service account SID
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52628 Remove Workload ID design partner CTA
  docs/pages/enroll-resources/workload-identity/aws-oidc-federation.mdx
  docs/pages/enroll-resources/workload-identity/aws-roles-anywhere.mdx
  docs/pages/enroll-resources/workload-identity/azure-federated-credentials.mdx
  docs/pages/enroll-resources/workload-identity/best-practices.mdx
  docs/pages/enroll-resources/workload-identity/federation.mdx
  docs/pages/enroll-resources/workload-identity/gcp-workload-identity-federation-jwt.mdx
  docs/pages/enroll-resources/workload-identity/getting-started.mdx
  docs/pages/enroll-resources/workload-identity/introduction.mdx
  docs/pages/enroll-resources/workload-identity/jwt-svids.mdx
  docs/pages/enroll-resources/workload-identity/tsh.mdx
  docs/pages/enroll-resources/workload-identity/workload-attestation.mdx
  docs/pages/includes/workload-id-preview.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#52709 [v17] Add version incompatibility warning to Connect
  docs/pages/connect-your-client/teleport-connect.mdx
  gen/proto/go/teleport/lib/teleterm/v1/auth_settings.pb.go
  gen/proto/ts/teleport/lib/teleterm/v1/auth_settings_pb.ts
  lib/client/api.go
  lib/client/api_test.go
  lib/teleterm/apiserver/handler/handler.go
  lib/teleterm/apiserver/handler/handler_auth.go
  lib/teleterm/clusters/cluster_auth.go
  lib/utils/ver.go
  proto/teleport/lib/teleterm/v1/auth_settings.proto
  web/packages/teleterm/src/services/config/appConfigSchema.ts
  web/packages/teleterm/src/services/tshd/fixtures/mocks.ts
  web/packages/teleterm/src/services/tshd/testHelpers.ts
  web/packages/teleterm/src/services/tshd/types.ts
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLoginReason.story.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/CompatibilityWarning.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormSso/FormSso.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/storyHelpers.tsx
  web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts
  web/packages/teleterm/src/ui/services/clusters/clustersService.ts
  web/packages/teleterm/src/ui/services/clusters/types.ts
Labels: documentation, ui, backport, size/md

#52757 [v16] Remove Workload ID design partner CTA
  docs/pages/enroll-resources/workload-identity/aws-oidc-federation.mdx
  docs/pages/enroll-resources/workload-identity/aws-roles-anywhere.mdx
  docs/pages/enroll-resources/workload-identity/azure-federated-credentials.mdx
  docs/pages/enroll-resources/workload-identity/best-practices.mdx
  docs/pages/enroll-resources/workload-identity/federation.mdx
  docs/pages/enroll-resources/workload-identity/gcp-workload-identity-federation-jwt.mdx
  docs/pages/enroll-resources/workload-identity/getting-started.mdx
  docs/pages/enroll-resources/workload-identity/introduction.mdx
  docs/pages/enroll-resources/workload-identity/jwt-svids.mdx
  docs/pages/enroll-resources/workload-identity/tsh.mdx
  docs/pages/enroll-resources/workload-identity/workload-attestation.mdx
  docs/pages/includes/workload-id-preview.mdx
Labels: documentation, backport, size/sm, no-changelog

#52726 fix: use SID directly in VNet Windows installer
  lib/vnet/install_service_windows.go
Labels: size/sm, vnet, backport/branch/v17

#52728 fix: support RSA PSS signatures with Windows VNet
  gen/proto/go/teleport/lib/vnet/v1/client_application_service.pb.go
  lib/vnet/client_application_service.go
  lib/vnet/remote_app_provider.go
  lib/vnet/vnet_test.go
  proto/teleport/lib/vnet/v1/client_application_service.proto
Labels: size/sm, backport/branch/v17

#52765 [v17] fix: use SID directly in VNet Windows installer
  lib/vnet/install_service_windows.go
Labels: backport, size/sm

#52767 [v17] fix: support RSA PSS signatures with Windows VNet
  gen/proto/go/teleport/lib/vnet/v1/client_application_service.pb.go
  lib/vnet/client_application_service.go
  lib/vnet/remote_app_provider.go
  lib/vnet/vnet_test.go
  proto/teleport/lib/vnet/v1/client_application_service.proto
Labels: backport, size/sm

#52755 [v17] [teleport-update] Set umask 0022 for teleport-update to avoid errors on enable
  lib/autoupdate/agent/installer.go
  lib/autoupdate/agent/updater.go
  lib/autoupdate/agent/updater_test.go
  tool/teleport-update/main.go
Labels: backport, size/sm

#52763 [v17] Improve readability of Managed Updates docs intro
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
Labels: documentation, backport, size/sm, no-changelog

#52560 [v17] Fix CGO-less TBot Build
  Makefile
  integrations/teleport-spacelift-runner/Makefile
Labels: backport, size/sm

#52772 [v17] chore: Bump Go to 1.23.7
  build.assets/tooling/go.mod
  build.assets/versions.mk
  go.mod
  integrations/event-handler/go.mod
  integrations/terraform/go.mod
Labels: backport, size/sm

#52144 Remove the custom current user lookup function
  api/profile/profile.go
  api/utils/user.go
  api/utils/user_test.go
  docs/pages/faq.mdx
  lib/client/api.go
  lib/client/db/mysql/optionfile.go
  lib/client/db/postgres/servicefile.go
  lib/utils/agentconn/agent_windows.go
  tool/tsh/common/tsh.go
Labels: documentation, tsh, size/sm, no-changelog

#52778 Release 17.3.2
  CHANGELOG.md
  Makefile
  api/version.go
  build.assets/macos/tsh/tsh.app/Contents/Info.plist
  build.assets/macos/tshdev/tsh.app/Contents/Info.plist
  examples/chart/access/datadog/Chart.yaml
  examples/chart/access/datadog/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/datadog/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/discord/Chart.yaml
  examples/chart/access/discord/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/discord/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/email/Chart.yaml
  examples/chart/access/email/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/email/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/jira/Chart.yaml
  examples/chart/access/jira/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/jira/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/mattermost/Chart.yaml
  examples/chart/access/mattermost/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/mattermost/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/msteams/Chart.yaml
  examples/chart/access/msteams/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/msteams/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/pagerduty/Chart.yaml
  examples/chart/access/pagerduty/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/pagerduty/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/access/slack/Chart.yaml
  examples/chart/access/slack/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/access/slack/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/event-handler/Chart.yaml
  examples/chart/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  examples/chart/event-handler/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/tbot/Chart.yaml
  examples/chart/tbot/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-cluster/Chart.yaml
  examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml
  examples/chart/teleport-cluster/tests/__snapshot__/auth_clusterrole_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/auth_deployment_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_config_test.yaml.snap
  examples/chart/teleport-cluster/tests/__snapshot__/proxy_deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/Chart.yaml
  examples/chart/teleport-kube-agent/tests/__snapshot__/deployment_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/job_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/statefulset_test.yaml.snap
  examples/chart/teleport-kube-agent/tests/__snapshot__/updater_deployment_test.yaml.snap
Labels: helm, backport, size/sm, no-changelog

#52713 [v17] Log in warn level when updating DiscoveryConfigStatus fails
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#52716 [v16] Log in warn level when updating DiscoveryConfigStatus fails
  lib/srv/discovery/status.go
Labels: backport, size/sm, discovery, no-changelog

#52692 ListUserTasks WebAPI: include issue type title
  lib/web/ui/usertask.go
  lib/web/usertasks_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#52731 [v17] Fix a flaky role editor test
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/Resources.test.tsx
Labels: ui, backport, size/sm, no-changelog

#52754 [v17] Remove the check-redirects script
  docs/check-redirects/README.md
  docs/check-redirects/check-redirects.js
  docs/check-redirects/check-redirects.test.js
  docs/check-redirects/index.js
  docs/check-redirects/package.json
  docs/check-redirects/pnpm-lock.yaml
  docs/check-redirects/pnpm-workspace.yaml
  jest.config.js
Labels: documentation, backport, size/sm, no-changelog

#52786 [v17] ListUserTasks WebAPI: include issue type title
  lib/web/ui/usertask.go
  lib/web/usertasks_test.go
Labels: backport, size/sm, no-changelog

#52743 [v17] Address 67 Vale warnings
  docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-pagerduty.mdx
  docs/pages/admin-guides/deploy-a-cluster/deployments/gcp.mdx
  docs/pages/admin-guides/deploy-a-cluster/gcp-kms.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/ci-or-cloud.mdx
  docs/pages/admin-guides/infrastructure-as-code/terraform-provider/dedicated-server.mdx
  docs/pages/connect-your-client/introduction.mdx
  docs/pages/connect-your-client/notifications.mdx
  docs/pages/connect-your-client/teleport-connect.mdx
  docs/pages/enroll-resources/agents/join-services-to-your-cluster/kubernetes.mdx
  docs/pages/enroll-resources/application-access/guides/amazon-athena.mdx
  docs/pages/enroll-resources/application-access/guides/dynamodb.mdx
  docs/pages/enroll-resources/application-access/guides/guides.mdx
  docs/pages/enroll-resources/application-access/guides/tcp.mdx
  docs/pages/enroll-resources/application-access/guides/vnet.mdx
  docs/pages/enroll-resources/application-access/okta/hosted-guide.mdx
  docs/pages/enroll-resources/application-access/troubleshooting-apps.mdx
  docs/pages/enroll-resources/database-access/database-access.mdx
  docs/pages/enroll-resources/database-access/enroll-aws-databases/aws-dynamodb.mdx
  docs/pages/enroll-resources/database-access/enroll-azure-databases/azure-postgres-mysql.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/oracle-self-hosted.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/redis-cluster.mdx
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/redis.mdx
  docs/pages/enroll-resources/desktop-access/introduction.mdx
  docs/pages/enroll-resources/kubernetes-access/register-clusters/dynamic-registration.mdx
  docs/pages/enroll-resources/machine-id/access-guides/applications.mdx
  docs/pages/enroll-resources/machine-id/access-guides/databases.mdx
  docs/pages/enroll-resources/machine-id/access-guides/kubernetes.mdx
  docs/pages/enroll-resources/machine-id/access-guides/ssh.mdx
  docs/pages/enroll-resources/machine-id/access-guides/tctl.mdx
  docs/pages/enroll-resources/machine-id/deployment/azure.mdx
  docs/pages/enroll-resources/machine-id/deployment/circleci.mdx
  docs/pages/enroll-resources/machine-id/deployment/gcp.mdx
  docs/pages/enroll-resources/machine-id/deployment/github-actions.mdx
  docs/pages/enroll-resources/machine-id/deployment/gitlab.mdx
  docs/pages/enroll-resources/machine-id/deployment/jenkins.mdx
  docs/pages/enroll-resources/machine-id/deployment/kubernetes.mdx
  docs/pages/enroll-resources/machine-id/deployment/linux.mdx
  docs/pages/enroll-resources/machine-id/troubleshooting.mdx
  docs/pages/enroll-resources/server-access/guides/auditd.mdx
  docs/pages/enroll-resources/server-access/guides/host-user-creation.mdx
  docs/pages/enroll-resources/server-access/guides/jetbrains-sftp.mdx
  docs/pages/enroll-resources/server-access/guides/recording-proxy-mode.mdx
  docs/pages/enroll-resources/server-access/guides/vscode.mdx
  docs/pages/faq.mdx
  docs/pages/includes/provision-token/bitbucket-spec.mdx
  docs/pages/includes/provision-token/circleci-spec.mdx
  docs/pages/includes/provision-token/kubernetes-jwks-spec.mdx
  docs/pages/reference/architecture/device-trust.mdx
  docs/pages/reference/cli/tctl.mdx
  docs/pages/upgrading/overview.mdx
Labels: documentation, backport, size/sm, no-changelog

#52705 [v16] Escape labels on Node Join scripts
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/node-join/install.sh
Labels: backport, size/sm

#52706 [v15] Escape labels on Node Join scripts
  lib/web/join_tokens.go
  lib/web/join_tokens_test.go
  lib/web/scripts/node-join/install.sh
Labels: backport, size/sm

#52702 [v15] Support setting app public-addr within Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery, backport/branch/v17

#52770 [Web] Update sidenav sections
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ArrowSquareIn.tsx
  web/packages/design/src/Icon/assets/ArrowSquareIn.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/Main/MainContainer.tsx
  web/packages/teleport/src/Navigation/CategoryIcon.tsx
  web/packages/teleport/src/Navigation/Navigation.tsx
  web/packages/teleport/src/Navigation/Section.tsx
  web/packages/teleport/src/Navigation/categories.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/types.ts
Labels: ui, size/md, no-changelog, backport/branch/v17

#52545 Fix terraform provider data sources
  integrations/terraform/gen/plural_data_source.go.tpl
  integrations/terraform/gen/singular_data_source.go.tpl
  integrations/terraform/provider/data_source_teleport_access_list.go
  integrations/terraform/provider/data_source_teleport_access_monitoring_rule.go
  integrations/terraform/provider/data_source_teleport_app.go
  integrations/terraform/provider/data_source_teleport_auth_preference.go
  integrations/terraform/provider/data_source_teleport_cluster_maintenance_config.go
  integrations/terraform/provider/data_source_teleport_cluster_networking_config.go
  integrations/terraform/provider/data_source_teleport_database.go
  integrations/terraform/provider/data_source_teleport_device_trust.go
  integrations/terraform/provider/data_source_teleport_dynamic_windows_desktop.go
  integrations/terraform/provider/data_source_teleport_github_connector.go
  integrations/terraform/provider/data_source_teleport_installer.go
  integrations/terraform/provider/data_source_teleport_login_rule.go
  integrations/terraform/provider/data_source_teleport_oidc_connector.go
  integrations/terraform/provider/data_source_teleport_okta_import_rule.go
  integrations/terraform/provider/data_source_teleport_provision_token.go
  integrations/terraform/provider/data_source_teleport_role.go
  integrations/terraform/provider/data_source_teleport_saml_connector.go
  integrations/terraform/provider/data_source_teleport_server.go
  integrations/terraform/provider/data_source_teleport_session_recording_config.go
  integrations/terraform/provider/data_source_teleport_static_host_user.go
  integrations/terraform/provider/data_source_teleport_trusted_cluster.go
  integrations/terraform/provider/data_source_teleport_user.go
  integrations/terraform/provider/data_source_teleport_workload_identity.go
  integrations/terraform/testlib/cluster_networking_config_test.go
  integrations/terraform/testlib/fixtures/networking_config_data_source.tf
  integrations/terraform/testlib/fixtures/role_data_source.tf
  integrations/terraform/testlib/role_test.go
Labels: size/md, backport/branch/v16, backport/branch/v17

#52806 Add resizing wrapper around unified resources
  web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
Labels: ui, backport-required, size/sm, no-changelog, backport/branch/v16, backport/branch/v17

#52801 Change Notices to Admonitions
  docs/pages/reference/resources.mdx
  docs/pages/upgrading/agent-managed-updates-v1.mdx
  docs/pages/upgrading/agent-managed-updates.mdx
  docs/pages/upgrading/upgrading-reference.mdx
Labels: documentation, size/sm, no-changelog

#52809 [v17] [Web] Update sidenav sections
  web/packages/design/src/Icon/Icons.story.tsx
  web/packages/design/src/Icon/Icons/ArrowSquareIn.tsx
  web/packages/design/src/Icon/assets/ArrowSquareIn.svg
  web/packages/design/src/Icon/index.ts
  web/packages/teleport/src/Main/MainContainer.tsx
  web/packages/teleport/src/Navigation/CategoryIcon.tsx
  web/packages/teleport/src/Navigation/Navigation.tsx
  web/packages/teleport/src/Navigation/Section.tsx
  web/packages/teleport/src/Navigation/categories.ts
  web/packages/teleport/src/features.tsx
  web/packages/teleport/src/types.ts
Labels: ui, backport, size/md, no-changelog

#52819 Fix docs prose linting error for deleted files
  .github/workflows/doc-tests.yaml
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52701 [v16] Support setting app public-addr within Kubernetes app discovery
  api/types/constants.go
  docs/pages/reference/agent-services/kubernetes-application-discovery.mdx
  lib/services/app.go
  lib/srv/discovery/discovery_test.go
Labels: documentation, backport, size/sm, discovery, backport/branch/v17

#52783 Machine ID: Document `kubernetes/v2` service
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/reference/cli/tbot.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, size/md, no-changelog, backport/branch/v17

#52802 [v17] Update go-ora dependency to v2.8.24
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm, no-changelog

#52799 [v15] Bump the electron group with 2 updates
  package.json
  web/packages/teleterm/package.json
  yarn.lock
Labels: ui, backport, size/md, no-changelog

#52797 [v17] Bump the electron group with 2 updates
  package.json
  pnpm-lock.yaml
  web/packages/teleterm/package.json
Labels: ui, backport, size/md, no-changelog

#52347 Truncate DiscoveryConfig.Status ErrorMessage
  api/defaults/defaults.go
  lib/srv/discovery/status.go
  lib/srv/discovery/status_test.go
Labels: size/sm, discovery, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52805 Fix: Overlapping unified cache backend key for apps
  lib/services/unified_resource.go
  lib/services/unified_resource_test.go
Labels: size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52260 [v17] git session prehog event
  api/types/session_tracker.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/sm, no-changelog

#52714 Refactor events listeners and fix a race condition when closing RDP stream
  lib/srv/desktop/rdp/rdpclient/client.go
  web/packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, rdp, desktop-access, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52846 [v17] chore: Bump golang.org/x/net to v0.36.0
  api/go.mod
  api/go.sum
  assets/backport/go.mod
  assets/backport/go.sum
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  examples/access-plugin-minimal/go.mod
  examples/access-plugin-minimal/go.sum
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  examples/desktop-registration/go.mod
  examples/desktop-registration/go.sum
  examples/go-client/go.mod
  examples/go-client/go.sum
  examples/service-discovery-api-client/go.mod
  examples/service-discovery-api-client/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm

#52847 [v16] chore: Bump golang.org/x/net to v0.36.0
  api/go.mod
  api/go.sum
  assets/backport/go.mod
  assets/backport/go.sum
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  examples/access-plugin-minimal/go.mod
  examples/access-plugin-minimal/go.sum
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  examples/desktop-registration/go.mod
  examples/desktop-registration/go.sum
  examples/go-client/go.mod
  examples/go-client/go.sum
  examples/service-discovery-api-client/go.mod
  examples/service-discovery-api-client/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm

#52845 chore: Bump golang.org/x/net to v0.37.0
  api/go.mod
  api/go.sum
  assets/backport/go.mod
  assets/backport/go.sum
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  examples/access-plugin-minimal/go.mod
  examples/access-plugin-minimal/go.sum
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  examples/desktop-registration/go.mod
  examples/desktop-registration/go.sum
  examples/go-client/go.mod
  examples/go-client/go.sum
  examples/service-discovery-api-client/go.mod
  examples/service-discovery-api-client/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: size/sm

#52848 [v15] chore: Bump golang.org/x/net to v0.36.0
  api/go.mod
  api/go.sum
  assets/backport/go.mod
  assets/backport/go.sum
  build.assets/tooling/go.mod
  build.assets/tooling/go.sum
  examples/access-plugin-minimal/go.mod
  examples/access-plugin-minimal/go.sum
  examples/api-sync-roles/go.mod
  examples/api-sync-roles/go.sum
  examples/desktop-registration/go.mod
  examples/desktop-registration/go.sum
  examples/go-client/go.mod
  examples/go-client/go.sum
  examples/service-discovery-api-client/go.mod
  examples/service-discovery-api-client/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
Labels: backport, size/sm

#52841 [v17] Fix: Overlapping unified cache backend key for apps
  lib/services/unified_resource.go
  lib/services/unified_resource_test.go
Labels: backport, size/sm

#52831 [v16] Extend user activity report events with Identity events
  api/gen/proto/go/usageevents/v1/usageevents.pb.go
  api/proto/teleport/legacy/types/events/events.proto
  api/proto/teleport/usageevents/v1/usageevents.proto
  api/types/events/conv.go
  api/types/events/events.pb.go
  gen/proto/go/prehog/v1/teleport.pb.go
  gen/proto/go/prehog/v1alpha/teleport.pb.go
  gen/proto/ts/prehog/v1/teleport_pb.ts
  gen/proto/ts/prehog/v1alpha/teleport_pb.ts
  lib/auth/methods.go
  lib/auth/userloginstate/generator.go
  lib/usagereporter/teleport/aggregating/reporter.go
  lib/usagereporter/teleport/aggregating/reporter_test.go
  lib/usagereporter/teleport/audit.go
  lib/usagereporter/teleport/types.go
  lib/usagereporter/teleport/usagereporter_test.go
  proto/prehog/v1/teleport.proto
  proto/prehog/v1alpha/teleport.proto
Labels: backport, size/md, no-changelog

#52524 Add a tab-by-tab mode for creating new roles
  web/packages/design/src/SlideTabs/SlideTabs.story.tsx
  web/packages/design/src/SlideTabs/SlideTabs.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/Shared.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/YamlEditor.tsx
Labels: ui, size/md, no-changelog, backport/branch/v17

#52292 Workload ID: Docker Workload Attestation
  api/gen/proto/go/teleport/workloadidentity/v1/attrs.pb.go
  api/proto/teleport/workloadidentity/v1/attrs.proto
  go.mod
  go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/minimal.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/minimal.golden
  lib/tbot/workloadidentity/workloadattest/attest.go
  lib/tbot/workloadidentity/workloadattest/container/container_test.go
  lib/tbot/workloadidentity/workloadattest/container/docker.go
  lib/tbot/workloadidentity/workloadattest/container/testdata/mountfile/docker-real-27.5.1-rootful-cgroupfs
  lib/tbot/workloadidentity/workloadattest/container/testdata/mountfile/docker-real-27.5.1-rootful-systemd
  lib/tbot/workloadidentity/workloadattest/container/testdata/mountfile/docker-real-27.5.1-rootless-cgroupfs-systemd-enabled
  lib/tbot/workloadidentity/workloadattest/container/testdata/mountfile/docker-real-27.5.1-rootless-systemd
  lib/tbot/workloadidentity/workloadattest/docker.go
  lib/tbot/workloadidentity/workloadattest/docker_test.go
  lib/tbot/workloadidentity/workloadattest/docker_unix.go
  lib/tbot/workloadidentity/workloadattest/docker_unix_test.go
  lib/tbot/workloadidentity/workloadattest/docker_windows.go
Labels: machine-id, size/lg

#52838 [v17] Add autoupdate events to web UI
  web/packages/teleport/src/Audit/EventList/EventTypeCell.tsx
  web/packages/teleport/src/Audit/fixtures/index.ts
  web/packages/teleport/src/services/audit/makeEvent.ts
  web/packages/teleport/src/services/audit/types.ts
Labels: ui, backport, size/md

#52820 Fix access list reminder notifications for access lists overdue by more than 8 days
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: size/sm, no-changelog, backport/branch/v17

#52816 [v17] Fix terraform provider data sources
  integrations/terraform/gen/plural_data_source.go.tpl
  integrations/terraform/gen/singular_data_source.go.tpl
  integrations/terraform/provider/data_source_teleport_access_list.go
  integrations/terraform/provider/data_source_teleport_access_monitoring_rule.go
  integrations/terraform/provider/data_source_teleport_app.go
  integrations/terraform/provider/data_source_teleport_auth_preference.go
  integrations/terraform/provider/data_source_teleport_cluster_maintenance_config.go
  integrations/terraform/provider/data_source_teleport_cluster_networking_config.go
  integrations/terraform/provider/data_source_teleport_database.go
  integrations/terraform/provider/data_source_teleport_device_trust.go
  integrations/terraform/provider/data_source_teleport_dynamic_windows_desktop.go
  integrations/terraform/provider/data_source_teleport_github_connector.go
  integrations/terraform/provider/data_source_teleport_installer.go
  integrations/terraform/provider/data_source_teleport_login_rule.go
  integrations/terraform/provider/data_source_teleport_oidc_connector.go
  integrations/terraform/provider/data_source_teleport_okta_import_rule.go
  integrations/terraform/provider/data_source_teleport_provision_token.go
  integrations/terraform/provider/data_source_teleport_role.go
  integrations/terraform/provider/data_source_teleport_saml_connector.go
  integrations/terraform/provider/data_source_teleport_server.go
  integrations/terraform/provider/data_source_teleport_session_recording_config.go
  integrations/terraform/provider/data_source_teleport_static_host_user.go
  integrations/terraform/provider/data_source_teleport_trusted_cluster.go
  integrations/terraform/provider/data_source_teleport_user.go
  integrations/terraform/provider/data_source_teleport_workload_identity.go
  integrations/terraform/testlib/cluster_networking_config_test.go
  integrations/terraform/testlib/fixtures/networking_config_data_source.tf
  integrations/terraform/testlib/fixtures/role_data_source.tf
  integrations/terraform/testlib/role_test.go
Labels: backport, size/md

#52817 [v16] Fix terraform provider data sources
  integrations/terraform/gen/plural_data_source.go.tpl
  integrations/terraform/gen/singular_data_source.go.tpl
  integrations/terraform/provider/data_source_teleport_access_list.go
  integrations/terraform/provider/data_source_teleport_access_monitoring_rule.go
  integrations/terraform/provider/data_source_teleport_app.go
  integrations/terraform/provider/data_source_teleport_auth_preference.go
  integrations/terraform/provider/data_source_teleport_cluster_maintenance_config.go
  integrations/terraform/provider/data_source_teleport_cluster_networking_config.go
  integrations/terraform/provider/data_source_teleport_database.go
  integrations/terraform/provider/data_source_teleport_device_trust.go
  integrations/terraform/provider/data_source_teleport_github_connector.go
  integrations/terraform/provider/data_source_teleport_installer.go
  integrations/terraform/provider/data_source_teleport_login_rule.go
  integrations/terraform/provider/data_source_teleport_oidc_connector.go
  integrations/terraform/provider/data_source_teleport_okta_import_rule.go
  integrations/terraform/provider/data_source_teleport_provision_token.go
  integrations/terraform/provider/data_source_teleport_role.go
  integrations/terraform/provider/data_source_teleport_saml_connector.go
  integrations/terraform/provider/data_source_teleport_server.go
  integrations/terraform/provider/data_source_teleport_session_recording_config.go
  integrations/terraform/provider/data_source_teleport_static_host_user.go
  integrations/terraform/provider/data_source_teleport_trusted_cluster.go
  integrations/terraform/provider/data_source_teleport_user.go
  integrations/terraform/provider/data_source_teleport_workload_identity.go
  integrations/terraform/testlib/cluster_networking_config_test.go
  integrations/terraform/testlib/fixtures/networking_config_data_source.tf
  integrations/terraform/testlib/fixtures/role_data_source.tf
  integrations/terraform/testlib/role_test.go
Labels: backport, size/md

#52790 Improve per-session MFA in a desktop session
  lib/web/desktop.go
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx
  web/packages/teleport/src/lib/useMfa.test.tsx
  web/packages/teleport/src/lib/useMfa.ts
Labels: ui, desktop-access, size/sm, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52485 access_monitoring_rule: Support contains_all operator
  integrations/access/accessmonitoring/request_mapping.go
  integrations/access/accessmonitoring/request_mapping_test.go
  lib/expression/evaluator_test.go
  lib/expression/parser.go
Labels: size/sm, no-changelog

#52761 [v16] docs: add troubleshoting for missing service account SID
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#52760 [v17] docs: add troubleshoting for missing service account SID
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#52835 [auto] docs: Update version to v16.4.17
  docs/config.json
Labels: documentation, automated, backport, size/sm, no-changelog

#52557 Document the Podman and Docker workload attestors
  docs/cspell.json
  docs/pages/reference/machine-id/configuration.mdx
  docs/pages/reference/workload-identity/attributes.mdx
  docs/pages/reference/workload-identity/workload-identity-api-and-workload-attestation.mdx
Labels: documentation, size/md, no-changelog

#52682 Adds IC plugin status value to trigger IC group import
  api/proto/teleport/legacy/types/types.proto
  api/types/plugin.go
  api/types/types.pb.go
Labels: size/sm, no-changelog, backport/branch/v17, aws-iam-identity-center

#52867 [v17] Fix access list reminder notifications for access lists overdue by more than 8 days
  lib/auth/auth.go
  lib/auth/auth_test.go
Labels: backport, size/sm, no-changelog

#52866 [v17] Refactor client canvas and fix a race condition when closing RDP stream
  lib/srv/desktop/rdp/rdpclient/client.go
  web/packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
  web/packages/teleport/src/components/TdpClientCanvas/index.ts
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, rdp, backport, desktop-access, size/sm

#52843 [v16] Truncate DiscoveryConfig.Status ErrorMessage
  api/defaults/defaults.go
  lib/srv/discovery/status.go
  lib/srv/discovery/status_test.go
Labels: backport, size/sm, discovery, no-changelog

#52764 [docs] add yaml syntax highlight for `login_rule` sepc
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/includes/login-rule-spec.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52512 Deflake TestDiscoveryServer when checking for created UserTasks
  lib/srv/discovery/discovery_test.go
Labels: size/sm, discovery, no-changelog, backport/branch/v17

#52874 Fix missing closing backticks in Workload Identity API & Workload Attestation
  docs/pages/reference/workload-identity/workload-identity-api-and-workload-attestation.mdx
Labels: documentation, size/sm, no-changelog

#52853 [v15] Fix docs prose linting error for deleted files
  .github/workflows/doc-tests.yaml
Labels: backport, size/sm, no-changelog

#52851 [v17] Fix docs prose linting error for deleted files
  .github/workflows/doc-tests.yaml
Labels: no-changelog

#52852 [v16] Fix docs prose linting error for deleted files
  .github/workflows/doc-tests.yaml
Labels: backport, size/sm, no-changelog

#52859 [v17] Add a tab-by-tab mode for creating new roles
  web/packages/design/src/SlideTabs/SlideTabs.story.tsx
  web/packages/design/src/SlideTabs/SlideTabs.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/Shared.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/YamlEditor.tsx
Labels: ui, backport, size/md, no-changelog

#52699 Workload ID: Systemd Workload Attestation
  api/gen/proto/go/teleport/workloadidentity/v1/attrs.pb.go
  api/proto/teleport/workloadidentity/v1/attrs.proto
  go.mod
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  lib/tbot/config/testdata/TestBotConfig_YAML/standard_config.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestSPIFFEWorkloadAPIService_YAML/minimal.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/full.golden
  lib/tbot/config/testdata/TestWorkloadIdentityAPIService_YAML/minimal.golden
  lib/tbot/workloadidentity/workloadattest/attest.go
  lib/tbot/workloadidentity/workloadattest/systemd.go
  lib/tbot/workloadidentity/workloadattest/systemd_linux.go
  lib/tbot/workloadidentity/workloadattest/systemd_linux_test.go
  lib/tbot/workloadidentity/workloadattest/systemd_other.go
Labels: machine-id, size/md

#52577 Rename access rules to admin rules
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.ts
Labels: ui, size/sm, no-changelog, backport/branch/v17

#52762 [v15] docs: add troubleshoting for missing service account SID
  docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
Labels: documentation, backport, size/sm, no-changelog

#52887 Fix a flaky test
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
Labels: ui, size/sm, no-changelog, backport/branch/v17

#52868 [v16] Refactor client canvas and fix a race condition when closing RDP stream
  lib/srv/desktop/rdp/rdpclient/client.go
  web/packages/teleport/src/DesktopSession/DesktopSession.story.test.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  web/packages/teleport/src/DesktopSession/DesktopSession.tsx
  web/packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
  web/packages/teleport/src/DesktopSession/useDesktopSession.tsx
  web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  web/packages/teleport/src/Player/DesktopPlayer.tsx
  web/packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
  web/packages/teleport/src/components/TdpClientCanvas/index.ts
  web/packages/teleport/src/lib/tdp/client.ts
  web/packages/teleport/src/lib/tdp/codec.ts
Labels: ui, rdp, backport, desktop-access, size/sm

#52886 Add story for `ResourceActionButton`
  web/packages/teleport/src/Apps/fixtures/index.ts
  web/packages/teleport/src/SamlApplications/useSamlAppActions.tsx
  web/packages/teleport/src/UnifiedResources/ResourceActionButton.story.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
Labels: ui, size/md, no-changelog, backport/branch/v17

#52780 docs: document tsh sessions ls
  docs/pages/connect-your-client/tsh.mdx
  docs/pages/reference/cli/tsh.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52888 [v17] Rename access rules to admin rules
  web/packages/teleport/src/Roles/RoleEditor/RoleEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/RoleEditorAdapter.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/AdminRules.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.test.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/StandardEditor.tsx
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/standardmodel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/useStandardModel.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.test.ts
  web/packages/teleport/src/Roles/RoleEditor/StandardEditor/validation.ts
Labels: ui, backport, size/sm, no-changelog

#50752 docs: Update preflight docs for building buildboxes
  docs/preflight.md
Labels: documentation, size/sm, no-changelog

#52882 [v17] [docs] add yaml syntax highlight for `login_rule` sepc
  docs/pages/admin-guides/access-controls/login-rules/guide.mdx
  docs/pages/includes/login-rule-spec.mdx
Labels: documentation, backport, size/sm, no-changelog

#44549 Include AD/non-AD status in certificate
  lib/auth/windows/windows.go
  lib/srv/desktop/windows_server.go
  lib/tlsca/ca.go
Labels: desktop-access, size/sm

#52890 [v17] Add story for `ResourceActionButton`
  web/packages/teleport/src/Apps/fixtures/index.ts
  web/packages/teleport/src/SamlApplications/useSamlAppActions.tsx
  web/packages/teleport/src/UnifiedResources/ResourceActionButton.story.tsx
  web/packages/teleterm/src/ui/DocumentCluster/ActionButtons.story.tsx
Labels: ui, backport, size/md, no-changelog

#52883 [v17] Deflake TestDiscoveryServer when checking for created UserTasks
  lib/srv/discovery/discovery_test.go
Labels: backport, size/sm, discovery, no-changelog

#52815 Added 03/03 Upcoming Releases Update
  docs/pages/upcoming-releases.mdx
Labels: documentation, backport, size/sm, no-changelog

#50869 docs: fix for sql server instrs and openssh warning
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/sql-server-ad-pkinit.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52834 [v17] Machine ID: Document `kubernetes/v2` service
  docs/pages/enroll-resources/machine-id/faq.mdx
  docs/pages/reference/cli/tbot.mdx
  docs/pages/reference/machine-id/configuration.mdx
Labels: documentation, backport, size/md, no-changelog

#52915 Update `axios` from 1.8.1 to 1.8.2
  pnpm-lock.yaml
Labels: size/sm, no-changelog, backport/branch/v17

#52844 [v15] Truncate DiscoveryConfig.Status ErrorMessage
  api/defaults/defaults.go
  lib/srv/discovery/access_graph.go
  lib/srv/discovery/status_test.go
Labels: backport, size/sm, discovery, no-changelog

#52919 [v17] Update `axios` from 1.7.5 to 1.8.2
  pnpm-lock.yaml
Labels: backport, size/sm, no-changelog

#52885 [v17] Add Helm instructions for updating a license file
  docs/pages/admin-guides/deploy-a-cluster/license.mdx
Labels: documentation, backport, size/sm, no-changelog

#52253 [v17] Edit the Vale config
  docs/.vale.ini
Labels: documentation, backport, size/sm, no-changelog

#50025 docs: include self-hosted and cloud download reference
  docs/pages/installation.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52910 [v15] docs: fix for sql server instrs and openssh warning
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/sql-server-ad-pkinit.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
Labels: documentation, backport, size/sm, no-changelog

#52909 [v16] docs: fix for sql server instrs and openssh warning
  docs/pages/enroll-resources/database-access/enroll-self-hosted-databases/sql-server-ad-pkinit.mdx
  docs/pages/enroll-resources/server-access/openssh/openssh-manual-install.mdx
Labels: documentation, backport, size/sm, no-changelog

#52923 Bump github.com/gravitational/protobuf to v1.3.2-teleport.2
  buf-gogo.gen.yaml
  build.assets/Dockerfile-grpcbox
  build.assets/tooling/cmd/render-tests/_sample/go.sum
  go.mod
  go.sum
  integrations/event-handler/go.mod
  integrations/event-handler/go.sum
  integrations/terraform/go.mod
  integrations/terraform/go.sum
  protogen.go
Labels: size/sm, no-changelog

#52899 Fixes flaky `TestIntegrations/SessionRecordingModes`
  integration/integration_test.go
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52939 ci: Remove changelog check concurrency
  .github/workflows/changelog-merge-queue.yaml
  .github/workflows/changelog.yaml
Labels: size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17

#52947 docs: eks auto-discovery fixes
  docs/pages/enroll-resources/auto-discovery/kubernetes/aws.mdx
Labels: documentation, size/sm, no-changelog, backport/branch/v15, backport/branch/v16, backport/branch/v17
